### ISSUE TITLE
Affiliate payout via PayPal Adaptive Payments

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#10]
Probably not for version 1.0, but allowing affiliates to be paid out via PayPal Adaptive Payments (similar to what I did with EDD Commissions) would be excellent.

It should allow:
- affiliates to be paid instantly (when a referral is set to `unpaid`)
- affiliates to be paid out in bulk via an admin action

**Comment by flowdee** [comment]
Any update or new plans here?

**Comment by pippinsplugins** [comment]
Adaptive Payments was discontinued by PayPal and is no longer a supported product, nor is it available for new accounts, so for this reason we will not be building this.

**Comment by flowdee** [comment]
Thanks for the info Pippin.
