### ISSUE TITLE
Referrals for WooCommerce Cash on Delivery orders should go to Pending (currently Unpaid)

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1001]
Currently referrals for WooCommerce Cash on Delivery orders go to Unpaid status, so affiliates can see they have generated a referral instantly, even though cash hasn't yet changed hands. Think it would make sense for them to go to Pending, so the site owner can receive the cash first - then when they mark order as Complete in WooCommerce, the referral status will change to Unpaid.

**Comment by sumobi** [comment]
@pippinsplugins This is because COD payments are marked as "processing" in WooCommerce, rather than "on hold". Not sure why that is...

https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-woocommerce.php#L27

**Comment by sumobi** [comment]
Here's why they changed it (back in 2013) from on-hold to processing:
https://github.com/woothemes/woocommerce/issues/3102

**Comment by pippinsplugins** [comment]
We can't remove the completed action on `woocommerce_order_status_processing` as some sites use that as their completed status, or at least as the "this should mark referral as paid" status.

We've had it requested before and now I think this is an excellent time to add in a `What status should AffiliateWP mark the referral as unpaid` option.

**Comment by pippinsplugins** [comment]
Or we could just detect the payment method for this instance (easier).

**Comment by sumobi** [comment]
@pippinsplugins Those sound like good options

**Comment by Ragdog** [comment]
What is happening with this ? Currrently WooCommerce v 2.5.2 is setting orders to Processing but the documentation says that the orders come in as On-Hold.
Why not have a parameter that can be set to specify whether you want this as on-hold or processing ?

**Comment by pippinsplugins** [comment]
@Ragdog this will be addressed with version 1.8

**Comment by Ragdog** [comment]
@pippinsplugins I have two questions 
1. Version 1.8 of what ? Woocommerce is currently version 2.5.2
2. What exactly is the change that is going to be made ?

**Comment by pippinsplugins** [comment]
1. 1.8 of AffiliateWP
2. I can't tell you that as we haven't done it yet.

**Comment by DrewAPicture** [comment]
Added a PR: #1215

**Comment by pippinsplugins** [comment]
Looks good!
