### ISSUE TITLE
Credit last referrer increments visit ID by 1 when refreshing

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1002]
When credit last referrer is enabled and the username is used in the affiliate referral URL (either pretty or non pretty) the visit ID increments by 1 with each page refresh. Using an affiliate ID is fine.

related: https://github.com/AffiliateWP/AffiliateWP/issues/915

**Comment by sumobi** [comment]
Just ran into this issue again on customer's site

**Comment by pippinsplugins** [comment]
Pretty sure the ID should only increment when using a _different_ affiliate's login than the one already tracked, yes?

**Comment by sumobi** [comment]
@pippinsplugins correct.

**Comment by pippinsplugins** [comment]
@sumobi give this a test please? https://github.com/AffiliateWP/AffiliateWP/compare/release/1.8...issue/1002?w=1

**Comment by sumobi** [comment]
@pippinsplugins sorry to say that it does not work, still increments. Made sure I was on correct branch and could see changes in tracking.js.

**Comment by pippinsplugins** [comment]
Do you have fallback tracking enabled? If so, disable it.

**Comment by sumobi** [comment]
Don't have that enabled

**Comment by pippinsplugins** [comment]
@sumobi This still works properly for me. Can you try it again and make sure your browser cache is cleared?

**Comment by sumobi** [comment]
@pippinsplugins this works great for me now, not sure why it didn't before, always clear cache etc.
