### ISSUE TITLE
Can't create new referral in Admin

### ISSUE THREAD

**Issue by KingYes** [AffiliateWP/AffiliateWP#1004]
Hi @pippinsplugins 
When I search Affiliate in that screen (ex: `wp-admin/admin.php?page=affiliate-wp-referrals&action=add_referral`), In ajax response I get this error:

```
<b>Warning</b>:  array_filter() expects parameter 2 to be a valid callback, no array or string given in <b>/public_html/wp-content/plugins/affiliate-wp/includes/admin/ajax-actions.php</b> on line <b>69</b><br />
```

We are using PHP v5.4.37.

**Comment by KingYes** [comment]
You are need to use with direct function in that `array_filter`.

**Comment by michaelbeil** [comment]
You may not have mbstring module within PHP enabled.

**Comment by KingYes** [comment]
`mbstring` is enable in my server. So why I get this error?

**Comment by sumobi** [comment]
@KingYes Can you open up a support ticket so we can investigate further? http://affiliatewp.com/support/.
