### ISSUE TITLE
WishList Member blocks emails, redirects affiliate when specific option is enabled.

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1005]
We don't have a full integration for Wishlist Member but there's a couple of issues caused by WLM when the  "Allow WishList Member To Handle Login Redirect" option is enabled from WishList Member -> Settings -> Miscellaneous. 

1. It redirects the affiliate to the site's homepage, instead of keeping them on the affiliate area

2. It blocks emails being sent to the admin and affiliate when an affiliate registers. This is most likely due to the redirect, our email actions probably don't have time to fire.

**Comment by pippinsplugins** [comment]
What if we just disabled that option in WIshlist programmatically?

**Comment by sumobi** [comment]
@pippinsplugins unfortunately it seems a lot of customers use that option to redirect their customers to a specific page, unless you meant disabling it somehow at login. 

This seems to work as a temporary solution:

    function affwp_wlm_fix_redirect( $user_login, $user ) {

        if ( ! function_exists( 'affiliate_wp' ) ) {
            return;
        }

        $user_id = $user->ID;

 	    // Redirect for affiliates
 	    if ( affwp_is_affiliate( $user_id ) ) {
 		    $redirect = affiliate_wp()->login->get_login_url(); // affiliate dashboard

 		    if ( $redirect ) {
 			    wp_redirect( $redirect );
                exit;
 		    }
 	    }
    }
    add_action( 'wp_login', 'affwp_wlm_fix_redirect', 10, 2 );

That allows an affiliate to get to the affiliate area when logging in or registering. Might need a similar function when logging out, since I think WLM will also redirect to the homepage.

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/146167984/22831/?folderId=634609

**Comment by sumobi** [comment]
Blah, the above code doesn't help with the emails, they are still blocked. WLM have told the customer they might be able to provide some sort of AffiliateWP integration so I've forwarded them some sample code to check for the affiliate. Hopefully they can simply not fire their redirection when an affiliate is logging in, or registering.

**Comment by pippinsplugins** [comment]
@sumobi what about including your snippet above inside of core?

**Comment by michaelbeil** [comment]
Per https://secure.helpscout.net/conversation/148487782/23249/?folderId=205527, we were sent a custom version of WLM with the filter for the login redirect Andrew requested.
   
Also, possible filter for a logout redirect:
``` php
if ( apply_filters( 'wishlistmember_logout_redirect_override', false ) ) {
return;
}
```

**Comment by sumobi** [comment]
@pippinsplugins  ^ Going to test the WLM version above and then WLM will include the new filters in a new update. Then we can just turn off their login/logout redirects for affiliates from our compatibility fix file :+1:

**Comment by sumobi** [comment]
Worked great

**Comment by michaelbeil** [comment]
Rock solid!

**Comment by michaelbeil** [comment]
Confirmed here as well.

**Comment by pippinsplugins** [comment]
@sumobi see my comment on the PR
