### ISSUE TITLE
Single to multisite affiliate table issue

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1007]
When moving a WordPress install from a single site to multisite, an error occurs when attempting to add an affiliate. 

First add the multisite define in the wp-config and then find that the user has no affiliates registered and gets an error when trying to add a new affiliate too. User can see the affiliate table wp_affiliate_wp_affiliates has all the data.    

The table used in multisite works without a prefix. So the user took the original wp_affiliate_wp_affiliate and wp_affiliates_wp_affiliatemeta and removed the prefix to affiliates_wp_affiliate andaffiliates_wp_affiliatemeta.

This then fixed the issue. 

https://secure.helpscout.net/conversation/146645439/22908/

**Comment by pippinsplugins** [comment]
I don't think this is a bug we should be fixing since it's not really a bug. It's an issue with a site migration that was not completed 100%.
