### ISSUE TITLE
Keep username and email fields but set them to disabled for logged in users

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1008]
A common support ticket we get is "I can't see the email or username fields on my affiliate registration form". This is obviously because the user is already logged in.

I'd love to hear everyone's thoughts on what we can do to make this clearer. We could for instance keep the fields there, set them to disabled, and show the user's current username and email address, much like we do on the edit affiliate screen for the user ID.

Since the fields are already there for a logged out user, it wouldn't hurt to keep them there for a logged-in user and would prevent many support tickets for AffiliateWP, and the Affiliate Forms for X add-ons which mimic the same behaviour.

**Comment by pippinsplugins** [comment]
I vote we show them. I get this question incredibly often in Restrict Content Pro, which also hides the fields when a logged in user is registering.

**Comment by michaelbeil** [comment]
Another :+1: for showing non-editable fields of the current username and email.

**Comment by sumobi** [comment]
Nice

**Comment by sumobi** [comment]
@AffiliateWP/core Ready for testing

Here's a logged in WP user that isn't yet an affiliate:

![screen shot 2016-08-10 at 3 57 12 pm](https://cloud.githubusercontent.com/assets/52581/17541394/24fc11e6-5f13-11e6-8179-f2f46e9a9692.png)

Notes:

1. I decided that only the username and email fields should be disabled. Username since WP doesn't allow you to change it, email because although you can change it, it must be done from the WP profile to send the confirmation link.
2. An affiliate can delete their name, or update it to something else if they want and it will update their WP profile.

3. The WP user's URL will be shown if they already have it added to the WP profile. Changing it from this form will also update their WP profile. That is, until we implement https://github.com/AffiliateWP/AffiliateWP/issues/1512

**Comment by michaelbeil** [comment]
Looking nice here:
![screen shot 2016-08-09 at 11 12 14 pm](https://cloud.githubusercontent.com/assets/4752949/17541622/dd95ce82-5e86-11e6-9a8a-d83d978420d5.png)

1-3 are fine and dandy. 

4. It may be nice to add a password field by showing some stars. Although, we have not displayed this to logged in users before.

5. I don't quite think that would be necessary. But, then again, adding a description could be short, simple, and save some headaches later. Let's do it.

**Comment by pippinsplugins** [comment]
4. I don't think we should show a password field.

5. Yes, let's explain why.

**Comment by sumobi** [comment]
@pippinsplugins As much as I'd like to add descriptions, I really don't want to add descriptions. Does that make sense?

It's going to clutter up the UI if we add them beside the inputs or underneath. I wonder if we should introduce front-end tooltips? Perhaps a little question mark next to each disabled input and it would show why it's disabled on hover.

**Comment by pippinsplugins** [comment]
? with hover : +1:

**Comment by sumobi** [comment]
If only those labels had no fixed 200px width...

**Comment by sumobi** [comment]
@pippinsplugins I'm thinking we should wait until we have tooltips in core https://github.com/AffiliateWP/AffiliateWP/issues/1412

**Comment by pippinsplugins** [comment]
:+1:

**Comment by michaelbeil** [comment]
We could banish the fixed width, but that is probably a different issue. Also, waiting for tooltips would be helpful for adding descriptions into the registration fields.

**Comment by pippinsplugins** [comment]
Merged and closing.
