### ISSUE TITLE
Give Integration

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1009]
We should add an integration for Give.

Requested: https://secure.helpscout.net/conversation/148046248/23156/?folderId=205524

**Comment by sumobi** [comment]
:+1:

**Comment by tdegen1981** [comment]
Absolutely!

**Comment by pippinsplugins** [comment]
This should be able to be almost a copy and paste from EDD.

**Comment by pippinsplugins** [comment]
There hasn't been any further requests for this yet so punting to 2.0.

**Comment by sumobi** [comment]
Do we still want to do this for 2.0? No further requests as far as I can see.

**Comment by pippinsplugins** [comment]
Yes I want to get this in.

**Comment by sumobi** [comment]
@ramiabraham Let me know if you've started on this or want to take it over.

**Comment by sumobi** [comment]
At a quick glance, this is what's left. Will hopefully finish up tomorrow.

- [ ] Per-donation form referral rates
- [ ] Revoke referral when donation is deleted
- [ ] Revoke referral when donation is refunded
- [ ] Payment note

**Comment by pippinsplugins** [comment]
:+1: looking good so far

**Comment by sumobi** [comment]
@AffiliateWP/core ready for testing

**Comment by pippinsplugins** [comment]
Works perfectly!
