### ISSUE TITLE
Transits from a referral website

### ISSUE THREAD

**Issue by VictorSlate** [AffiliateWP/AffiliateWP#1015]
Let's imagine - my affiliate have his own site (or blog - www.blog.com) where he wish to promote my service.
At this time he has only two ways to get a referal, right? I can use refefal links (mysite.com?ref=1), or coupons.

What do you think about new feature which add a new option to affiliate's area.

"Transits from a referral website
We suggest you a new way of customer acquisition without utilization of referral links.
You can register your website as a referral one, in this case your partner code will be used for every transit from it to our website.

Transits from referral websites are prioritized over referral links.
Only transits from confirmed websites will be considered."

I hope you'll understand what I mean.

**Comment by michaelbeil** [comment]
We actually have an issue for this: https://github.com/AffiliateWP/AffiliateWP/issues/245.

**Comment by sumobi** [comment]
Closing since #245 covers this
