### ISSUE TITLE
Affiliate welcome email still sending when "Welcome Email" checkbox is not enabled

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1018]
The welcome email seems to be sending regardless of whether the checkbox is enabled or not. If it's not enabled, it shouldn't send.

![screen shot 2015-12-15 at 4 43 38 pm](https://cloud.githubusercontent.com/assets/52581/11801482/29b63b3c-a34b-11e5-9a29-5788909e2996.png)

**Comment by pippinsplugins** [comment]
@sumobi Which are we considering the welcome email? Email after approval? Email after registration but pending?

**Comment by michaelbeil** [comment]
Approval I believe @pippinsplugins.

**Comment by sumobi** [comment]
@pippinsplugins Yeah the email after approval, ie the affiliate accepted email. The email after registration but still pending will be the pending affiliate registration email.

**Comment by pippinsplugins** [comment]
@sumobi ready for testing.

**Comment by sumobi** [comment]
@pippinsplugins not working for me, affiliate is still getting the welcome email when adding the affiliate from the admin:

![screen shot 2015-12-30 at 6 57 08 pm](https://cloud.githubusercontent.com/assets/52581/12046905/44e64f72-af27-11e5-9e88-73eab86b52de.png)

**Comment by pippinsplugins** [comment]
@sumobi why do you break things? J/K I'll hunt it down.

**Comment by pippinsplugins** [comment]
@sumobi test again now please.

**Comment by sumobi** [comment]
@pippinsplugins works perfectly :+1:
