### ISSUE TITLE
affwp_search_users ajax callback chokes on database with large number of users.

### ISSUE THREAD

**Issue by nerrad** [AffiliateWP/AffiliateWP#1021]
This callback method retrieves ALL wp_users (excluding any already existing affiliates) and then runs it through `array_filter` to match the search query against it.  
However on databases with a large user base it chokes because of the sheer number of users being pulled (I ran into this while testing AffiliateWP for a possible implementation on EventEspresso.com).  

Is there a reason why the search match is being done this way vs doing a direct `LIKE '%$search_string%'` against the user table?

If desired I can do a pull request to convert to a direct query?

**Comment by nerrad** [comment]
The above pull request fixes the issue on our site with a large number of users in the db.

**Comment by michaelbeil** [comment]
This looks to be like a great fix. We will check into it.

**Comment by pippinsplugins** [comment]
Thanks @nerrad !
