### ISSUE TITLE
4.4 - Overview page - headers unstyled

### ISSUE THREAD

**Issue by mgibbs189** [AffiliateWP/AffiliateWP#1028]
Looks like it needs a little padding, and increased font size and/or font weight.

<img src="http://i.imgur.com/iZYkDqA.png?1" />

**Comment by pippinsplugins** [comment]
Thanks @mgibbs189 !

@sumobi could you take care of this one

**Comment by sumobi** [comment]
will do

**Comment by sumobi** [comment]
^ The simplest way I could find to fix it. It now looks like how it used to. The other way to fix it was to remove the `dashboard-widgets` ID from one of the parent divs, but then we lose the floating.

![screen shot 2015-12-18 at 10 12 01 pm](https://cloud.githubusercontent.com/assets/52581/11893306/71d4f29c-a5d4-11e5-8bbd-80825faa9c09.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by mgibbs189** [comment]
Great stuff, thanks for the quick fix @sumobi @pippinsplugins :+1:
