### ISSUE TITLE
Add-ons page for showcasing add-ons/upselling

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1035]
Like we do for EDD, I think it would be a great idea to add a new "Add-ons" admin menu item. This page would list all Pro Add-ons, Official free add-ons and could also include 3rd party add-ons.

If a customer with a Professional/Ultimate license activates their license key, this page could offer 1 click installs of the Pro add-ons, and show them which add-ons they currently have installed. 

For anyone else, it could be a great way to showcase/upsell the higher licenses. From what I understand,  this page in EDD performs very well. It's also a common issue that customers don't know we even have add-ons, we're constantly directing them to our add-ons page on the website.

___

EDD's extension page:

![screen shot 2015-12-28 at 12 39 42 pm](https://cloud.githubusercontent.com/assets/52581/12012558/1f5f4a88-ad60-11e5-9207-b883d63228ce.png)

**Comment by pippinsplugins** [comment]
Absolutely! Mock it up and I can make it happen!

**Comment by wordmaid** [comment]
:+1: x :100: to this.

To add to this, if customers can choose to upgrade their license instantly from this page, they could be directed to checkout to purchase a higher license level on the spot.

If Pro add-ons had their own tab, this could help this page look super clean, and make it easier to upsell. Though, there is an argument for displaying all official add-ons on the same page (shows how customizable AffiliateWP is). Think this could be a good discussion point if this page is added.

In any case, :+1: :+1: :+1: :+1:!

**Comment by sumobi** [comment]
Awesome, I'll put something together.

@wordmaid I like the idea of a customer being able to upgrade easily :+1:

**Comment by michaelbeil** [comment]
Oh my lanta yes!

**Comment by sumobi** [comment]
Made a start on this:

![screen shot 2016-03-01 at 11 11 13 pm](https://cloud.githubusercontent.com/assets/52581/13423978/f4dd97a8-e002-11e5-96bf-5e55302aee29.png)

**Comment by sumobi** [comment]
Taking suggestions on tabs. I'm thinking we should just have `Pro` and `Official free`.

**Comment by wordmaid** [comment]
:+1: Sounds good

**Comment by pippinsplugins** [comment]
Let's do just Pro.

**Comment by sumobi** [comment]
@pippinsplugins any particular reason for not including free add-ons?

**Comment by pippinsplugins** [comment]
Free add-ons don't encourage someone to upgrade their license, though they do help customers do more things, so maybe we should do both.

How about including both but separating them?

**Comment by sumobi** [comment]
That's what I meant above, there's 2 tabs, we'll have Pro for one, Official free for the other.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by michaelbeil** [comment]
I vote for two tabs: one Pro and one Official Free. The first one from left to right I think should be Pro.

**Comment by sumobi** [comment]
First pass: https://github.com/AffiliateWP/AffiliateWP/tree/feature/add-ons-page

@pippinsplugins I'd be pretty keen to get this into our next release unless you think otherwise.

**Comment by sumobi** [comment]
Couple of screens, bearing in mind that this is my local set up with missing images etc. Added text to each tab (thanks @wordmaid) with UTM parameters so we can track links to the account page.

![screen shot 2016-03-02 at 8 50 29 pm](https://cloud.githubusercontent.com/assets/52581/13453910/9dc60430-e0b8-11e5-8678-21431396cf85.png)
![screen shot 2016-03-02 at 8 50 17 pm](https://cloud.githubusercontent.com/assets/52581/13453911/9df0814c-e0b8-11e5-9438-f48a4eaa0a06.png)

**Comment by sumobi** [comment]
The theme and functionality plugin have been updated to suit this issue

**Comment by pippinsplugins** [comment]
Let's put it in!

**Comment by pippinsplugins** [comment]
@sumobi Just one tweak necessary.

**Comment by sumobi** [comment]
@pippinsplugins The suspense is killing me, what's the tweak?

**Comment by michaelbeil** [comment]
Methinks it is this: http://beil.io/1hQde.

https://github.com/AffiliateWP/AffiliateWP/pull/1120#discussion-diff-54758377

**Comment by sumobi** [comment]
Aha! missed that

**Comment by michaelbeil** [comment]
No worries. I exist to translate for @pippinsplugins :smirk:. 

(pun fully intended.)

**Comment by pippinsplugins** [comment]
Lol

**Comment by pippinsplugins** [comment]
Beautiful  :)

**Comment by michaelbeil** [comment]
It looks real nice, in case anyone wanted to see: ![slack-imgs](https://cloud.githubusercontent.com/assets/4752949/13501450/59629f46-e12c-11e5-8115-e763b39f5c48.png)

**Comment by pippinsplugins** [comment]
Yes it does!
