### ISSUE TITLE
Fix Fatal Error undefined function `affwp_get_pages` in certain situations.

### ISSUE THREAD

**Issue by nerrad** [AffiliateWP/AffiliateWP#1038]
This is a strange one.  I'm getting this fatal error when attempting to do a custom upload action (via ajax) on one of our plugin settings page with Affiliate WP active.

```
PHP message: PHP Fatal error: Call to undefined function affwp_get_pages() in {redacted}/staging/wp-content/plugins/affiliate-wp/includes/admin/settings/class-settings.php on line 319" while reading response header from upstream, client: {redacted}, server: {redacted}, request: "POST /wp-content/plugins/plugin-update-engine/js/plupload-handlers/upload.php?slug=espresso-recurring HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "{redacted}", referrer: "{redacted}/wp-admin/admin.php?page=plugin_update_page&action=edit&checked%5B0%5D=5520&plugin_status=all&paged=2&s&_wpnonce=702c5827d6"
```

The issue is (as the error reveals) `Affiliate_WP_Settings::register_settings` is calling `affwp_get_pages` when its not declared.  The weird thing is.  I see that `affwp_get_pages` is declared in `display-settings.php` which is required in `affiliate-wp.php` inside a `is_admin()` check and `Affiliate_WP_Settings::register_settings` is called via a callback on the `admin_init` hook (which should only fire when `is_admin()` is true).  So it's kind of puzzling that `affwp_get_pages` isn't available.  But its containing file obviously isn't getting loaded.

I'll investigate some more and will submit a pull request if I can find a clean fix but wanted to get this up in case you guys were already aware and have a fix in place.

**Comment by nerrad** [comment]
Okay I think I know why this is happening now.  It's because in the our plugin, we are using a custom plupload ajax handler.  This custom upload handler is calling `do_action('admin_init')` but I think something is happening where `is_admin()` check ends up being `false` when going through this custom upload handler.  This in turn means the required file isn't getting loaded.

Feel free to close, but this edge-case does reveal a potential flaw with the loading here because class-settings.php is being required everywhere (even on the frontend) but the `display-settings.php` which has dependent functions declared is ONLY being required in the admin.  It might be good to pull some stuff found in `class-settings.php` that is only required in the admin (for registering settings etc) into it's own class/file and have that only required in the admin.

**Comment by nerrad** [comment]
yah confirmed.  Our custom upload handler is calling `wp_load.php` early (which then loads any other plugins but `is_admin()` will return false.` Then later loads `wp-admin/admin.php`  which will in turn trigger the `do_action(`admin_init`)` hook.   We were able to fix our plugin.  It's really old code so there's lots of `doing_it_wrong()` in it.  I *still* think however your loading process here is a bit fragile.  But it is likely only edgecases like ours that will reveal that so totally understand if you decide to just close this issue.

**Comment by pippinsplugins** [comment]
@nerrad Thanks for tracking it down. We'll keep this open for now to see if we can prevent it from happening.

**Comment by DrewAPicture** [comment]
@nerrad I'm going to close this as invalid and chalk it up to `_doing_it_wrong()`.

If you're going to be manually firing `admin_init`, there's a developer expectation that it will only fire when `is_admin()` is true. I would probably recommend defining `WP_ADMIN` as `true` before manually firing an admin-specific hook like that. See the source for `is_admin()` for more information.

**Comment by nerrad** [comment]
yah agree with the status on this.
