### ISSUE TITLE
Affiliates can no longer be found with partial matches 

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1040]
Searching for an affiliate (when adding) now only works if you type the affiliate's full username (at least for me). I take it we changed something recently, I vaguely remember a performance issue.

If so, we'll need to update the text that says:

> Begin typing the name of the affiliate to perform a search for their associated user account.

Examples:

![screen shot 2015-12-30 at 1 48 41 pm](https://cloud.githubusercontent.com/assets/52581/12044761/1ac14376-aefc-11e5-82cc-fa22248d59a3.png)

![screen shot 2015-12-30 at 1 48 48 pm](https://cloud.githubusercontent.com/assets/52581/12044762/2007230a-aefc-11e5-982b-c7674b124119.png)

![screen shot 2015-12-30 at 1 48 54 pm](https://cloud.githubusercontent.com/assets/52581/12044765/25b293fc-aefc-11e5-9b0c-10509b9b38bf.png)

**Comment by michaelbeil** [comment]
Introduced in https://github.com/AffiliateWP/AffiliateWP/commit/d1531ae48f0f4283ca6348f6c405278fdc3d870e from #1032.

**Comment by sumobi** [comment]
@michaelbeil #1023

**Comment by sumobi** [comment]
@pippinsplugins since you tested the PR, is it only supposed to work for full/identical matches now?

**Comment by pippinsplugins** [comment]
Fixed.

**Comment by michaelbeil** [comment]
lol, yes @sumobi. 1032 is pretty much the same number as 1023.

**Comment by sumobi** [comment]
lol
