### ISSUE TITLE
Referrals being created with no status

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1042]
In some situations, referrals are appearing in the referrals section without an icon. This is because the referral has an empty `status` in the database. I've seen it happen on my local test set up a while back but could never replicate it (and now can't find the referral).

So far there's 2 customer tickets with this issue: 

https://secure.helpscout.net/conversation/153319431/24087/?folderId=205527
https://secure.helpscout.net/conversation/154892672/24248/?folderId=205531

The two tickets above both use WooCommerce though I'm sure I've seen it with EDD before and @wordmaid might have seen it with PMP.

@pippinsplugins ever seen this?

**Comment by pippinsplugins** [comment]
That's really strange. The `status` key is never passed to any of the methods that create referrals; it is always handled by `affiliate_wp()->referrals->add()` where `wp_parse_args()` is used to setup the defaults:
```
$defaults = array(
	'status' => 'pending',
	'amount' => 0
);

$args = wp_parse_args( $data, $defaults );
```
I'm guessing it has to do with `affwp_set_referral_status()` being given a blank status in some cases and that not falling back to a default of `pending`.

**Comment by pippinsplugins** [comment]
Yep, that's it:
```
function affwp_set_referral_status( $referral, $new_status = '' ) {

	if( is_object( $referral ) && isset( $referral->referral_id ) ) {
		$referral_id = $referral->referral_id;
	} elseif( is_numeric( $referral ) ) {
		$referral_id = absint( $referral );
		$referral    = affwp_get_referral( $referral_id );
	} else {
		return false;
	}

	$old_status = $referral->status;

	if( $old_status == $new_status ) {
		return false;
	}

	if( affiliate_wp()->referrals->update( $referral_id, array( 'status' => $new_status ), '', 'referral' ) ) {

		if( 'paid' == $new_status ) {

			affwp_increase_affiliate_earnings( $referral->affiliate_id, $referral->amount );
			affwp_increase_affiliate_referral_count( $referral->affiliate_id );

		} elseif ( 'unpaid' == $new_status && ( 'pending' == $old_status || 'rejected' == $old_status ) ) {

			// Update the visit ID that spawned this referral
			affiliate_wp()->visits->update( $referral->visit_id, array( 'referral_id' => $referral->referral_id ), '', 'visit' );

			do_action( 'affwp_referral_accepted', $referral->affiliate_id, $referral );

		} elseif( 'paid' != $new_status && 'paid' == $old_status ) {

			affwp_decrease_affiliate_earnings( $referral->affiliate_id, $referral->amount );
			affwp_decrease_affiliate_referral_count( $referral->affiliate_id );

		}

		do_action( 'affwp_set_referral_status', $referral_id, $new_status, $old_status );

		return true;
	}

	return false;

}
```
`$new_status` is permitted to be empty. We should block that. Also need to find why it's getting a blank status to begin with.

**Comment by pippinsplugins** [comment]
Found it.

This only happens with WooCommerce. The `add_pending_referral()` method of the WooCommerce integration supports updating an existing referral if there is one for the order record already (as happens when charges are declined after the initial referral is created). The update logic looks like this:
```
if ( $existing ) {

	// Update the previously created referral
	affiliate_wp()->referrals->update_referral( $existing->referral_id, array(
		'amount'       => $amount,
		'reference'    => $order_id,
		'description'  => $description,
		'campaign'     => affiliate_wp()->tracking->get_campaign(),
		'affiliate_id' => $affiliate_id,
		'visit_id'     => $visit_id,
		'products'     => $this->get_products(),
		'context'      => $this->context
	) );

} 
```
Notice that it does NOT pass in a `status` key.

In the `update_referral()` method, we have this:
```
if( $referral->status !== $data['status'] ) {

	affwp_set_referral_status( $referral, $data['status'] );

}
```
That ensures the status passed in to `update_referral()` gets set AND the necessary `do_action()`s are triggered.

When we don't pass in `status`, the `if( $referral->status !== $data['status'] )` statement evaluates to `true`, so `affwp_set_referral_status( $referral, $data['status'] )` runs, but `$data['status']` is blank.

**Comment by pippinsplugins** [comment]
@sumobi ready for testing.

**Comment by michaelbeil** [comment]
@pippinsplugins the initial failed card issue is exactly why that was happening.

**Comment by sumobi** [comment]
@pippinsplugins Aha! excellent find. I don't have any Credit Card extensions for WooCommerce, anyone got one to test with? Stripe would be preferred. Maybe I can just simulate it with PayPal, I'd like to obviously replicate the issue first so I know its been fixed.

**Comment by pippinsplugins** [comment]
Simulating with PayPal works. Click submit to go to PayPal then go back and complete the purchase.

**Comment by sumobi** [comment]
@pippinsplugins kk thanks will test that

**Comment by sumobi** [comment]
@pippinsplugins Replicated + fixed :+1:
