### ISSUE TITLE
Generate a payout for a single affiliate only

### ISSUE THREAD

**Issue by flowdee** [AffiliateWP/AffiliateWP#1046]
PR: #1889

Right now it's possible to filter referrals for a single user. But it's not possible to generate the total amount of referrals and mark them as paid (for a specific date range) for a single user as well. 

With the tools I can export the referrals of a single user but there is no total amount.

**Comment by pippinsplugins** [comment]
This would be nice.

**Comment by pippinsplugins** [comment]
@flowdee While the proposed changes in https://github.com/AffiliateWP/AffiliateWP/pull/1047 are good, we really need to support setting one or more affiliates instead of only permitting a single affiliate.

**Comment by flowdee** [comment]
Indeed @pippinsplugins. This should affect the tools (Export Referrals) too I guess.

**Comment by pippinsplugins** [comment]
It would be nice to add it to both.

**Comment by DrewAPicture** [comment]
Added a PR: #1889

![Affiliate field](https://cl.ly/2a0b0611333E/Screen%20Shot%202017-01-04%20at%205.25.00%20PM.png)

**Comment by pippinsplugins** [comment]
@DrewAPicture This needs to use the batch processor as well from #1707.

**Comment by pippinsplugins** [comment]
To clarify, #1707 already added the batch processor to the payout file generation, we just need to apply the affiliate-specific payouts to the new batch processing instead of the old export method.

**Comment by DrewAPicture** [comment]
Yup, on it :-)

**Comment by DrewAPicture** [comment]
@pippinsplugins Actually, that's already been done in the batch process. I didn't even convert the legacy exporter to support a single affiliate.

**Comment by DrewAPicture** [comment]
@pippinsplugins Single affiliate support has been added to `Generate_Payouts` in the PR: #1889

**Comment by pippinsplugins** [comment]
Excellent!

**Comment by flowdee** [comment]
Awesome 👍

**Comment by pippinsplugins** [comment]
This works well except for a couple of issues that I have noted on #1707

**Comment by DrewAPicture** [comment]
@pippinsplugins I've addressed the issues you raised on #1707.

**Comment by pippinsplugins** [comment]
Good here!

**Comment by pippinsplugins** [comment]
Ready for merge!

**Comment by DrewAPicture** [comment]
Updated following merge of #1156 to use `user_name` only and not rely on `user_id`. Retested and looks good. Waiting for tests to pass.

**Comment by DrewAPicture** [comment]
Merged #1889.
