### ISSUE TITLE
Improve license activation message

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1050]
Quite regularly we get the ol’ “i cant activate my license key” ticket. This is sometimes due to them having a personal/plus license and their licenses have already been activated on the maximum allowed number of sites.

We should improve the message in the admin to say something like “this license key has already activated on xyz.com” and possibly instructions on how to deactivate. If it has been activated on more than one site, it could list them out in a bullet list or similar.

**Comment by pippinsplugins** [comment]
Let's add verbose messages like we did in EDD: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4050

![screen shot 2016-06-14 at 11 37 51 am](https://cloud.githubusercontent.com/assets/1034109/16051220/7308a7b2-3224-11e6-96fe-b959f7ef0a72.png)

**Comment by pippinsplugins** [comment]
This is ready for testing! It will now properly display an error message when activation fails.

**Comment by michaelbeil** [comment]
Works well!
![screen shot 2016-08-31 at 4 01 38 pm](https://cloud.githubusercontent.com/assets/4752949/18146241/4381cf16-6f94-11e6-9c20-c20a5803a4a9.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Merged but leaving open for further testing.

**Comment by sumobi** [comment]
@pippinsplugins Thoughts on removing the `strong` from the notice? I can't find any other examples in core where all the text is bold.

![screen shot 2016-09-01 at 2 19 41 pm](https://cloud.githubusercontent.com/assets/52581/18153122/6ef9c7c8-704f-11e6-87d6-c2484eb69ef6.png)

**Comment by michaelbeil** [comment]
Good point. +1 for removing the `<strong>` from the notice.

**Comment by michaelbeil** [comment]
@sumobi _is_ to blame for this being on line 303 of release/1.9: https://github.com/AffiliateWP/AffiliateWP/blame/release/1.9/includes/admin/class-notices.php#L303.

**Comment by sumobi** [comment]
lol

**Comment by sumobi** [comment]
@pippinsplugins One small issue I noticed (not even sure we should fix it).

1. Enter an invalid license so the notice appears, and the URL is:

`/wp-admin/admin.php?page=affiliate-wp-settings&affwp_notice=license-missing&affwp_success=no`

2. Try and update a field such as the referral variable and then hit `return` on your keyboard (don't click the save changes button, this will work as expected).

3. The referral variable will not save.

If the notice isn't visible, settings can be saved by using the `return` key.

**Comment by pippinsplugins** [comment]
Does this also apply to clicking on the Save Changes button?

**Comment by sumobi** [comment]
No, save changes button works all the time. It's just the return key that doesn't work, but only if there's a notice. I guess it's trying to resubmit the activate license form..

**Comment by pippinsplugins** [comment]
Hmmm, I'm going to vote wontfix for now. We may be able to address it by changing the `Activate License` submit button to just a regular button and then using JS to handle form submission. That could be a good opportunity to ajax the activation process too.

**Comment by sumobi** [comment]
I'm fine with that, it's super minor

**Comment by michaelbeil** [comment]
Should we add the above to a new ticket? Re https://github.com/AffiliateWP/AffiliateWP/issues/1050#issuecomment-244834920

**Comment by pippinsplugins** [comment]
No, stays in this one.

**Comment by michaelbeil** [comment]
Ok. 

Also, do we want to remove the `<strong>` from the notice?

**Comment by sumobi** [comment]
I think we should, @pippinsplugins do you agree? https://github.com/AffiliateWP/AffiliateWP/issues/1050#issuecomment-243958022

**Comment by pippinsplugins** [comment]
Bold removed.
