### ISSUE TITLE
Easily show or remove affiliate registration & affiliate login forms on affiliate area page

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1051]
It would be awesome to make this incredibly easy to do within the core plugin without code snippets - show or hide the affiliate registration form and the affiliate login form from the Affiliate Area page. @sumobi reminded me that EDD does something similar with a drop-down menu:

<img width="757" alt="screen shot 2016-01-13 at 8 19 23 pm" src="https://cloud.githubusercontent.com/assets/11830108/12288086/0ac96134-ba36-11e5-84d0-03ad1f489755.png">

What do you guys think? I think the drop-down is amazing if it's specifically for the Affiliate Area page.

**Comment by pippinsplugins** [comment]
I like this.

**Comment by sumobi** [comment]
:+1: It's a ticket we get often for sure

**Comment by michaelbeil** [comment]
How would we want to account for this when either a Gravity or a Ninja form are used for the registration form?

**Comment by michaelbeil** [comment]
I suppose we could just add the filter proposed in 1443 to the add-ons.

**Comment by pippinsplugins** [comment]
Moving to 2.0.

**Comment by michaelbeil** [comment]
request here: https://secure.helpscout.net/conversation/269106465/45384/?folderId=634609

**Comment by michaelbeil** [comment]
It might be nice to have an option to select the order of the registration and login forms as they display on the affiliate area page.

**Comment by sumobi** [comment]
Currently adding this to the "General" tab at the very bottom, under a "Affiliate Registration Settings" section. We can talk about adding this to its own tab if necessary. We should also move other affiliate registration options to this new section such as:

1. Allow Affiliate Registration
2. Require Approval 
3. Auto Register New Users

<img width="632" alt="screen shot 2016-12-11 at 3 57 35 pm" src="https://cloud.githubusercontent.com/assets/52581/21083263/a1924b00-bfba-11e6-8d43-037cd85f5041.png">

**Comment by sumobi** [comment]
After discussing this with @wordmaid we came up with this revised version. Primarily because the select menu will only affect the `[affiliate_area]` shortcode.

<img width="646" alt="screen shot 2016-12-11 at 4 38 14 pm" src="https://cloud.githubusercontent.com/assets/52581/21083521/49017690-bfc0-11e6-82b4-5a8ef2f559cd.png">

<img width="642" alt="screen shot 2016-12-11 at 4 38 18 pm" src="https://cloud.githubusercontent.com/assets/52581/21083520/48ffc21e-bfc0-11e6-8ac5-5b4c217b4267.png">

**Comment by pippinsplugins** [comment]
When set to `None`, what kind of options do site admins have for customizing the display of the page?

**Comment by sumobi** [comment]
When set to `none`, there will be no forms shown on the Affiliate Area page at all. What options are you referring to?

**Comment by pippinsplugins** [comment]
I was just trying to think about what a site admin would do when it's set to `None`. Wouldn't that result in a completely blank page?

**Comment by sumobi** [comment]
The PR for this will be https://github.com/AffiliateWP/AffiliateWP/pull/1855. The filters added in https://github.com/AffiliateWP/AffiliateWP/issues/1443 and the changes here go hand in hand.

**Comment by sumobi** [comment]
@pippinsplugins Yeah, there would be no content. I would imagine some users would want it that way so they can populate the page with their own text (they would need to use the [affiliate_non_content] shortcodes. 

They might for example want no forms, but rather buttons that link off to the login and registration forms, similar to our page at https://affiliatewp.com/affiliates where it has all the information about the affiliate program.

**Comment by pippinsplugins** [comment]
Ok that makes sense :+1:

**Comment by sumobi** [comment]
@pippinsplugins Happy if some of the settings from the Misc tab are now moved over to this new section? https://github.com/AffiliateWP/AffiliateWP/issues/1051#issuecomment-266307505

**Comment by pippinsplugins** [comment]
I'm fine with that.

**Comment by sumobi** [comment]
Actually, none of those settings I mentioned fit under this new section since it's only for form specific settings. This would be however a place to make the website URL field not required etc and perhaps other fields as per https://github.com/AffiliateWP/AffiliateWP/issues/931#issuecomment-253976874

**Comment by sumobi** [comment]
Closed in favour of https://github.com/AffiliateWP/AffiliateWP/issues/1443
