### ISSUE TITLE
Possible plugin conflict with WP All Import

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#1052]
Have yet to replicate

Customer experienced some kind of error and could not install AffiliateWP. It would bring down their admin (possibly a fatal error) and they had to restore via FTP. After deactivating WP All Import they were able to activate AffiliateWP.

https://secure.helpscout.net/conversation/160285320/25246/?folderId=205531

**Comment by pippinsplugins** [comment]
Hasn't been seen in more than two years, closing.
