### ISSUE TITLE
Cache flushing on referral insertion

### ISSUE THREAD

**Issue by mindctrl** [AffiliateWP/AffiliateWP#1062]
In the `add()` method of the `Affiliate_WP_Referrals_DB` class, the cache gets flushed after calling the `insert()` method in `Affiliate_WP_DB`. The latter already flushes the cache and there isn't a need to flush it again, is there?

Also the `insert()` method doesn't check for a successful insertion before flushing the cache. If it fails it'll still be flushed. Necessary?

https://github.com/AffiliateWP/AffiliateWP/blob/1.7.14/includes/class-referrals-db.php#L97

https://github.com/AffiliateWP/AffiliateWP/blob/1.7.14/includes/class-db.php#L85

**Comment by pippinsplugins** [comment]
Whoops, that does seem wrong.

**Comment by DrewAPicture** [comment]
PR: #1169

**Comment by pippinsplugins** [comment]
Looks good!
