### ISSUE TITLE
Better debug tools for referral tracking

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1063]
We should build a debugging system for referral tracking. Ideally this would allow us to enable debug mode for a site and then test the referral tracking. At each point in the referral tracking processing, a debug message will be logged. By viewing the log and seeing where the debug messages fail to be logged, we will be able to more easily identify at which point the system failed.

**Comment by michaelbeil** [comment]
huge :+1:

**Comment by sumobi** [comment]
@pippinsplugins Absolutely superb, completely forgot you built this while you were here. I've only tested a few scenarios with EDD but worked great. I think we should get this in and then re-iterate as needed.

My only feedback is consistent type case, Eg `affiliate` vs `Affiliate`

<img width="1004" alt="screen shot 2016-03-02 at 9 53 28 pm" src="https://cloud.githubusercontent.com/assets/52581/13455323/7fe9ecc0-e0c1-11e5-8a25-39484ebfc6cb.png">

**Comment by pippinsplugins** [comment]
Merged!
