### ISSUE TITLE
Add new user status hook on the dashboard

### ISSUE THREAD

**Issue by crissoca** [AffiliateWP/AffiliateWP#1068]
Do you think it will be possible to add a new set of hooks on the dashboard template that depends on user status?

For example:

`<?php do_action( 'affwp_affiliate_dashboard_'.$status , affwp_get_affiliate_id() ); ?>`

Where status can be: ['pending', 'inactive', 'rejected', 'active'] that way devs can hook stuff conditionally without changing the dashboard template.

I noticed that there are only hooks under the *active* section of the dashboard I think is useful to have at least a hook for every status.

**Comment by pippinsplugins** [comment]
I don't think this is necessary because it's already trivial to determine the affiliate's status with `affwp_get_affiliate_status()`

**Comment by DrewAPicture** [comment]
I agree with @pippinsplugins that the current status can easily be determined with `affwp_get_affiliate_status()`.
