### ISSUE TITLE
Yesterday graph shows last month as yesterday

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1069]
A user found a bug when selecting "yesterday" to filter the graph. The graph selects December instead of January.

The issue lies here: https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/class-graph.php#L471.

A suggested change from the user, who happens to be a dev and was kind enough to share the fix is as follows:

``` php  
$month = date( 'n', $current_time ) == 1 ? 12 : date( 'n', $current_time );
```

to

``` php  
$month = date( 'n', $current_time ) == 1 && date( 'd', $current_time ) == 1 ? 12 : date( 'n', $current_time );
```

Ticket: https://secure.helpscout.net/conversation/163621996/26079/?folderId=634609

**Comment by pippinsplugins** [comment]
Good catch and fix.
