### ISSUE TITLE
Improve affwp_integration_create_referral filter

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1071]
We should improve the `affwp_integration_create_referral` filter so it's more useful. Context is pretty useless, so let's provide the filter with affiliate ID and reference.

**Comment by sumobi** [comment]
Related: https://github.com/AffiliateWP/AffiliateWP/issues/317

**Comment by sumobi** [comment]
@pippinsplugins anything else we need to do on this?

**Comment by pippinsplugins** [comment]
Merged into master.

@sumobi could you do one last round of testing? I had some merge conflicts and would like to confirm I didn't break anything.

**Comment by sumobi** [comment]
@pippinsplugins will do

**Comment by sumobi** [comment]
@pippinsplugins Tested a normal EDD referral, and a referral using the filter so it was blocked. Both worked fine, can't see any issues.

**Comment by sumobi** [comment]
Oh that log message works fine too when it's blocked :D
