### ISSUE TITLE
Add affwp_update_affiliate hook to save custom fields when editing affiliates

### ISSUE THREAD

**Issue by flowdee** [AffiliateWP/AffiliateWP#1073]
In order to save custom fields when editing an affiliate it's necessary to add a hook for the affwp_update_affiliate function.

```
do_action( 'affwp_update_affiliate', $data );
```

The affwp_post_update_ hook doesn't work because the custom fields added before to the page, won't be forwarded to this hook.

**Comment by DrewAPicture** [comment]
PR: #1168

**Comment by pippinsplugins** [comment]
@DrewAPicture Let's go ahead and add one before and one after the update call, that way we can have `update` and `updated`.

**Comment by DrewAPicture** [comment]
@pippinsplugins I've added a second hook following the update. I also reordered the params on the first hook to promote parity between the before and after hooks.

**Comment by pippinsplugins** [comment]
Looks great.

**Comment by DrewAPicture** [comment]
Looks like we have hit a naming conflict with introducing the new 'affwp_update_affiliate' action. It conflicts with the existing 'affwp_ . $_REQUEST['affwp_action']` dynamic hook fired on form submission for updating an affiliate.

Discovered when I kept getting memory exhaustion errors trying to update individual affiliates in #1184.

**Comment by DrewAPicture** [comment]
Let's open a new issue. Reclosing.
