### ISSUE TITLE
RCP: Disable referrals on a per-membership level

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1075]
PR: #1426

Just like EDD/WooCommerce etc, RCP should have a "disable referrals for this membership level" or similar. Currently you can only set the rate per membership level.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Once RCP 2.6 is live (a few weeks from now), we can use the Subscription Meta table for this.

**Comment by pippinsplugins** [comment]
https://github.com/restrictcontentpro/restrict-content-pro/issues/533

**Comment by pippinsplugins** [comment]
Ready for testing!

Note: this depends on RCP 2.6.

**Comment by pippinsplugins** [comment]
@michaelbeil could I get a test on this?

**Comment by michaelbeil** [comment]
This works great!

**Comment by michaelbeil** [comment]
Actually, this is not working. Referrals are still being created, and the disable referrals option is not saving.

**Comment by pippinsplugins** [comment]
@michaelbeil 2.6+ of RCP?

**Comment by michaelbeil** [comment]
@pippinsplugins Yes.

**Comment by pippinsplugins** [comment]
Ok I'll try again.

**Comment by pippinsplugins** [comment]
@michaelbeil ready for new round of testing.

**Comment by pippinsplugins** [comment]
Merging but leaving open for final testing.

**Comment by sumobi** [comment]
@pippinsplugins works great for me!
