### ISSUE TITLE
Mark referral as unpaid when payment declines the first time, but is then corrected

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1077]
When a payment is made in WooCommerce using Stripe, and the payment is declined, the referral is marked as `rejected` (as expected). However when the correct details are entered and the payment is accepted, the referral should be then marked as `unpaid`. Currently nothing happens.

**Comment by pippinsplugins** [comment]
Ready for testing @sumobi

**Comment by sumobi** [comment]
:+1:
