### ISSUE TITLE
Add linked Affiliate ID in WooCommerce/EDD order/payment details

### ISSUE THREAD

**Issue by lisag** [AffiliateWP/AffiliateWP#1080]
A customer has suggested it would be useful to show the Affiliate ID in the order details on the order page. I think this would be incredibly useful and could link to the affiliate's details, or even to the Referrals screen and filter all referrals for that affiliate. It would be cool to do this for WooCommerce and EDD at the least. What do you guys think?

Ref: https://secure.helpscout.net/conversation/164769918/26380/?folderId=205524

**Comment by pippinsplugins** [comment]
Yes. Let's do it.

**Comment by michaelbeil** [comment]
Yes.

**Comment by pippinsplugins** [comment]
It's on our todo list for 1.9, though that's still a ways out.

**Comment by EricMoiroud** [comment]
Thansk. I've found a way to do it myself in the meantime.

**Comment by DrewAPicture** [comment]
@pippinsplugins Do we have a mockup somewhere for exactly how and where we'd like the affiliate ID to be conveyed?

**Comment by pippinsplugins** [comment]
I do not. Perhaps a link in order notes?

**Comment by DrewAPicture** [comment]
I've started a PR: #1768, it's a work in progress.

Since many integrations use basically the same string and structure, the PR currently adds the ID only (link to come later) for the following:

* EDD
* Formidable Pro
* Gravity Forms
* Jigoshop
* Paid Memberships Pro
* Shopp
* Sprout Invoices
* WooCommerce
* Zippy Courses

**Comment by michaelbeil** [comment]
On a first look, things are looking nice: 
![screen shot 2016-10-27 at 6 58 48 pm](https://cloud.githubusercontent.com/assets/4752949/19807389/29caa0de-9d20-11e6-98a3-015012a2a297.png)

It may be good to change `(ID: X)` to `(Affiliate ID: X)`. Then the link could be added to only the ID, so if x = 2, then 2 would be linked to the affiliate page.

Thinking about this, we should add a link to the referral number. Thoughts everyone? I can open a new issue for that.

**Comment by michaelbeil** [comment]
We should add a period at the end of the note.

**Comment by pippinsplugins** [comment]
@DrewAPicture I'd like to see a `get_order_note()` method added to the base class to remove some of the duplication.

**Comment by pippinsplugins** [comment]
This should go hand-in-hand with https://github.com/AffiliateWP/AffiliateWP/issues/1430

**Comment by DrewAPicture** [comment]
Since #1430 got punted to 2.1, this should probably go with it.

**Comment by pippinsplugins** [comment]
I agree.

**Comment by pippinsplugins** [comment]
Moving this to 2.2 along with #1430

**Comment by puternutt** [comment]
Any News on this enhancement? it keeps being pushed to the next version, I mean EricMoiroud already created a mock up a year ago. It'd be nice to have it integrated. Keep up the good work!

**Comment by michaelbeil** [comment]
There is no ETA at this time. You might be able to hire someone to build this out for you: https://affiliatewp.com/consultants/.

**Comment by michaelbeil** [comment]
It does not appear like the affiliate ID is linked in this PR.

**Comment by michaelbeil** [comment]
This works perfectly now - the affiliate ID is linked in this PR.
