### ISSUE TITLE
Text field in Creatives

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1082]
Currently we have a description that states "Text for this creative." I am wondering if this should be more dynamic. I noticed that after updating, with between 250-260 characters in the text field, all creative fields are blank. Seems like a bug: https://cloudup.com/cKYLnzQipDZ.
![slack-imgs com](https://cloud.githubusercontent.com/assets/4752949/12600750/909e7076-c461-11e5-85be-275e8b0b5e62.png)

**Comment by sumobi** [comment]
Good find, I've replicated the issue. Here's the errors I see when I save the creative after entering some lorem ipsum:

    PHP Notice:  Undefined index: creative_id in /wp-content/plugins/AffiliateWP/includes/admin/creatives/edit.php on line 2

PHP Notice:  Trying to get property of non-object in /wp-content/plugins/AffiliateWP/includes/admin/creatives/edit.php on line 34 (x4 on different line numbers)

**Comment by sumobi** [comment]
Looks like `255` characters is the limit

**Comment by pippinsplugins** [comment]
Ah yes, we probably should.

**Comment by pippinsplugins** [comment]
For now, let's add some validation. We can consider changing column type later.

**Comment by michaelbeil** [comment]
I entered 255 characters and all had worked well in my tests. But anything beyond that seemed to cause issues. I thought there must've been a maximum input and behold there is.

**Comment by sumobi** [comment]
We could always add a `maxlength` attribute to the input field and cap it at 255.

**Comment by pippinsplugins** [comment]
That could work nicely.
