### ISSUE TITLE
Add woocommerce order status on referral tab and dashboard refferal page

### ISSUE THREAD

**Issue by ngrudev** [AffiliateWP/AffiliateWP#1084]
Hi,

I have a multisite. Affiliates register on subsite, but gets refferals when client buy a product from the main site. Affiliate dashborad is on subsite. I need to upgrade a little bit the plugin adding new column with the woocommerce order status. I want to put this information on affiliate dashboard Refferal tab and on admin dashboard Referral page.

I know how to add the columns, but I don't know how to get the order status from the database table on main site.

Can you support me with a solution?

Thank you,

**Comment by pippinsplugins** [comment]
@ngrudev This is in the realm of custom development and is not something that we can assist you with. Also, please open support tickets through http://affiliatewp.com/support - Github is for our development tracking only.
