### ISSUE TITLE
Migration assistant for user accounts not adding new affiliate accounts

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1085]
Have tested this myself on local install with new users, and a customer is having the same problem - migrating existing users to affiliate accounts isn't working. I (and they) have the most recent version installed, and tried deactivating all plugins, to no avail. It also still shows the success message. Is anyone else able to replicate? Potential bug?

Ref: https://secure.helpscout.net/conversation/166230989/26728/?folderId=414056

**Comment by pippinsplugins** [comment]
Definitely a bug somewhere. I'll test and fix for 1.8.

**Comment by sumobi** [comment]
Adding for reference: https://secure.helpscout.net/conversation/165477058/26575/?folderId=205527

**Comment by pippinsplugins** [comment]
@sumobi @wordmaid Could you test the `issue/1085` branch for me?

**Comment by sumobi** [comment]
@pippinsplugins worked for me!

**Comment by wordmaid** [comment]
@pippinsplugins worked for me too! :ok_hand:

**Comment by pippinsplugins** [comment]
Yay!

Doesn't work on customer site. Boo.

**Comment by pippinsplugins** [comment]
How many users did you each test with?

**Comment by wordmaid** [comment]
Just a handful for me - 4 or 5 or so.

**Comment by sumobi** [comment]
I had 46 affiliates already there, and after the migration I had 80.

**Comment by pippinsplugins** [comment]
@sumobi good. Multiple user roles?

**Comment by sumobi** [comment]
Admin and subscriber, but there probably weren't any admins

**Comment by michaelbeil** [comment]
Works for me.

**Comment by pippinsplugins** [comment]
This still doesn't work for the customer. No idea why.

**Comment by michaelbeil** [comment]
Is this in reference to the user that has 150 users they are attempting to migrate?

**Comment by pippinsplugins** [comment]
They have around 600

**Comment by michaelbeil** [comment]
Ah, yes, that one. Hmm ... ok, we need to create 600 users quick and test. Anyone got a script for that?

**Comment by michaelbeil** [comment]
`wp user create bob bob@example.com --role=author`, but that is one user a time.

**Comment by wordmaid** [comment]
Another customer experiencing this issue: https://secure.helpscout.net/conversation/178345624/29366/

**Comment by michaelbeil** [comment]
Another ticket: https://secure.helpscout.net/conversation/185677881/30802/?folderId=634609

**Comment by pippinsplugins** [comment]
If @DrewAPicture can test the PR above and confirm it works for him too, we'll merge this in and hopefully have it resolved for good for 1.8.

**Comment by michaelbeil** [comment]
When I tested this on Saturday, on branch `issue/1085`, user migration was not working. All checks out fine on a different WP instance.

**Comment by pippinsplugins** [comment]
@michaelbeil significant any differences between those two instances?

**Comment by michaelbeil** [comment]
one was a MAMP sub-domain MS, and the one that worked was a VVV instance.

**Comment by pippinsplugins** [comment]
Was the VVV instance also multisite?

**Comment by michaelbeil** [comment]
Yes. A sub-domain MS, working on `wordpress-default`.

**Comment by DrewAPicture** [comment]
Looks good in my testing before and after.

**Comment by pippinsplugins** [comment]
@DrewAPicture Great. Could you and @michaelbeil work together to try and track down why it fails for him?

**Comment by michaelbeil** [comment]
Ok. All checks on a new instance. This is good to go.

**Comment by pippinsplugins** [comment]
Good! Merging.

**Comment by pippinsplugins** [comment]
I apparently submitted this against master, so I've re-milestoned for 1.7.17. For the best really, since we've seen this hit a lot of customers recently.

**Comment by JustinSainton** [comment]
@pippinsplugins Re: 284246b5e552bc80f2a743e7fed395e3a3247bec, does it matter that `role__in` is only available as of WP 4.4? I had a hard time finding any minimum version of WordPress for AffWP...

**Comment by michaelbeil** [comment]
Our minimum requirement for WordPress is 3.9, but that is a good point @JustinSainton re `role__in`. We may have to rethink this.

**Comment by pippinsplugins** [comment]
I have no qualms with requiring 4.4.

**Comment by michaelbeil** [comment]
Since we are requiring 4.4 for this tool, I was thinking that we should add a notice when a user attempts to use the migration tool and is running any version of WP < 4.4 that is thrown on the migration assistant screen. 

It could look something like this: "WordPress 4.4. or above is required to use the tool"

Thoughts @pippinsplugins @DrewAPicture @sumobi @wordmaid?

**Comment by pippinsplugins** [comment]
If we do not make the entire plugin require 4.4, yes I agree.

**Comment by DrewAPicture** [comment]
I've replaced the contents of the User Accounts section with a notice for <= 4.3. If the user has the 'update_core' cap, it shows a link to update.

Message:
> **NOTE:** WordPress 4.4 or newer is required to use the User Accounts migration tool.

**Comment by pippinsplugins** [comment]
Looks good to me!

**Comment by pippinsplugins** [comment]
I'm going to merge and close!
