### ISSUE TITLE
License keys kill sites if affiliatewp.com goes down

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1086]
We saw affiliatewp.com's performance degrade severely this morning due to some option overloading. I resolved it but apparently during the time that the site's performance was poor, it also killed several customer's sites. I believe it happened due to our license checks timing out.

We need to make sure that our server going down does not severely impact customer sites.

**Comment by michaelbeil** [comment]
Agreed. Was gonna put something up about this.

**Comment by sumobi** [comment]
:+1:

**Comment by pippinsplugins** [comment]
@sumobi Can you test this? Just make sure that license key activates, admin notice goes away, updates show up, etc.

**Comment by sumobi** [comment]
Will do

**Comment by sumobi** [comment]
@pippinsplugins seems fine to me
