### ISSUE TITLE
Set protocol to https in license checks and activations

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1088]
We've moved https://affiliatewp.com over to pure `https` and this resulted in license activations failing.

Our activation / verification checks point to `http://affiliatewp.com`. Forcing all requests to `https` has broken the requests.

I've put in a temporary hack in our `wp-config.php` that allows license requests to go over `http://` but we'll want to update the source code to send them to `https://`.

**Comment by michaelbeil** [comment]
So, all we need to change is this line https://github.com/AffiliateWP/AffiliateWP/blob/master/affiliate-wp.php#L393 from 

```php
$affwp_updater = new AFFWP_Plugin_Updater( 'http://affiliatewp.com', __FILE__, array(
```

to

```php
$affwp_updater = new AFFWP_Plugin_Updater( 'https://affiliatewp.com', __FILE__, array(
```
