### ISSUE TITLE
Creative description field should stripslashes

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#1089]
The "Description" field in affwp creatives does not stripslashes in output.

Example output:
![slashes example](https://cldup.com/wnVwmeLMHP.png "slashes visibility example")

**Comment by sumobi** [comment]
:+1:

**Comment by ramiabraham** [comment]
(related: https://secure.helpscout.net/conversation/166981174/26860/?folderId=205529)

**Comment by DrewAPicture** [comment]
This was indirectly fixed in 1.8.2 when we ensured that all core objects get updated or inserted with unslashed data. The fix for the customer would be to make sure they're on at least 1.8.2 and then re-save any items currently outputting slashed data.
