### ISSUE TITLE
Show affiliate name on affiliate edit screen

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1091]
The affiliate's name is currently not shown in the affiliate edit screen, though it can be seen on the main Affiliates page. It would be cool to carry this through to the edit screen, so site admins know whose details they are looking at.

**Comment by DrewAPicture** [comment]
Related to #433.

**Comment by DrewAPicture** [comment]
This feature was included in #1254 and shipped with 1.8.
