### ISSUE TITLE
Commission on a $0.00 product is shown as $0.00, when using a flat-rate commission amount

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1092]
If you have a flat rate commission set and a $0.00 product is purchased in WooCommerce (or a coupon is used to make it $0.00), the commission is recorded at $0.00, instead of the flat rate amount.

To replicate in WooCommerce:

1. Set the global commission rate to a flat amount, eg `15`
2. Add a new WooCommerce product and set its price to $0.00
3. Buy the product using an affiliate's referral link
4. Commission will be recorded at $0.00, instead of the expected amount of `15.00`

EDD is fine, the commission will be recorded correctly at `$15.00`

**Comment by pippinsplugins** [comment]
What a weird situation. Who sells a free product but awards a commission?

**Comment by michaelbeil** [comment]
It's all the rage now @pippinsplugins.

**Comment by sumobi** [comment]
I've seen customers who just want to know who referred the customer of the free product, for tracking purposes. Perhaps they reward that affiliate in the future, or just want to know which affiliates are active. Having a referral generated for free products allows this. Though it seems silly that the affiliate will receive a $0.00 referral email, I can see it being useful for the affiliates also. Even though they received a $0.00 referral they know that they were close in making a real commission. Perhaps Lifetime Commissions is installed so they'll make a commission on the next purchase by the customer. If Order Details for Affiliates is installed the affiliate could reach out to the customer (if the email is provided) and try and up-sell them to a paid product, knowing that they have the free version.

I think having https://github.com/AffiliateWP/AffiliateWP/issues/505 will help, perhaps a new custom status where the affiliate doesn't get notified, and the referrals don't show at all for the affiliate, but they are shown in the admin.

**Comment by pippinsplugins** [comment]
Makes sense

**Comment by sumobi** [comment]
https://secure.helpscout.net/conversation/179558960/29642/?folderId=205531

**Comment by pippinsplugins** [comment]
Merged and milestoned for 1.7.16.
