### ISSUE TITLE
Change column titles in Most Valuable Affiliate table on Overview screen

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1096]
Currently the Most Valuable Affiliate table in _Affiliates > Overview_ shows "Earnings" and "Referrals" but it isn't noted anywhere that the Earnings and Referrals shown are only _paid_ earnings and _paid_ referrals: https://cloudup.com/cJ_8VgSw5EB 

It would be good to clear up any confusion by changing this to "Paid Earnings" and "Paid Referrals" like in the **Totals** overview table.

Ref: https://secure.helpscout.net/conversation/169872006/27551/?folderId=205524

PR: #1460

**Comment by pippinsplugins** [comment]
:+1:

**Comment by michaelbeil** [comment]
Great idea!

**Comment by DrewAPicture** [comment]
Tests passed, merged #1460.
