### ISSUE TITLE
Affiliate Payout via Stripe Connect

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#11]
Probably not for version 1.0, but allowing affiliates to be paid out via Stripe Connect would be excellent.

It should allow:

- affiliates to be paid instantly (when a referral is set to unpaid)
- affiliates to be paid out in bulk via an admin action

**Comment by DrewAPicture** [comment]
@pippinsplugins So is this a no-go then?

**Comment by pippinsplugins** [comment]
It is a no go and, if we do at any point, it will be done in the payouts repo: https://github.com/AffiliateWP/affiliate-wp-stripe-payouts
