### ISSUE TITLE
Add API for Custom Referral Statuses

### ISSUE THREAD

**Issue by JustinSainton** [AffiliateWP/AffiliateWP#1100]
I'm willing to concede that my use case may be ridiculous - but I think the concept makes good sense.

I have a client who wants to use AffiliateWP to manage all of their payouts to different types of users (multiple types of affiliates, merchants within a marketplace, etc.).  They want special types of referrals with different business logic to be recorded. For example, one commission would be the shipping amount of a sale that goes to a merchant, and it would go to them immediately - while the full product amount would be sent to them 14 days after they ship their product to their customer (yes, seriously).

So - thinking through all the types of commissions they really want, I was thinking it would sure be nice to have custom referral statuses.  Looking through the lower-level API for statuses and the data model used - there's nothing preventing it at the database abstraction level.  We simply have some assumptions throughout core that we'll only have our core post statuses.  Anyone familiar with [#12706](https://core.trac.wordpress.org/ticket/12706) is probably trembling at this point.  Thankfully, we're saved from much of the complexity there.

So - I just wanted to open this ticket as a discussion starter - is this something that would be welcomed as a PR, something that others could envision different use cases for?

**Comment by pippinsplugins** [comment]
@JustinSainton I klove the idea of supporting custom referral statuses and we've talked about it a few times here. See #505 #484

**Comment by sumobi** [comment]
Closing in favor of https://github.com/AffiliateWP/AffiliateWP/issues/2198
