### ISSUE TITLE
Limit how many characters you can use for affiliate username

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1104]
We should consider limiting the number of characters in an affiliate username. If you enter too many on the registration form you'll get a WSOD:

    PHP Notice:  Object of class WP_Error could not be converted to int in /affwp/wordpress/wp-includes/user.php on line 1603

The WordPress registration form is `60` characters long according to the maxlength of the input field. Although 60 is far too long for an affiliate username, we should probably just mimic core, since it's possible there.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by DrewAPicture** [comment]
Added a PR: #1274

**Comment by pippinsplugins** [comment]
Looks good to me, merged.
