### ISSUE TITLE
Ninja Forms 3.0 compatibility 

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1106]
PR: #1421

We'll need to do some testing with v3.0 of Ninja Forms. Referrals aren't working for me. @pippinsplugins want to give it a test also?

**Comment by sumobi** [comment]
Looks like the `nf_save_sub` action hook has been deprecated but I can't see what replaces it.

**Comment by pippinsplugins** [comment]
@sumobi I reached out to @kstover and he mentioned that they are still working on adding in the backwards compatibility layers. We'll just need to wait until it's ready for the next level of beta testing.

**Comment by pippinsplugins** [comment]
@sumobi they've put the hook back in to the `3.0-beta` branch. Try again?

**Comment by pippinsplugins** [comment]
There is also a new hook (for going forward) called `ninja_forms_save_sub`

**Comment by pippinsplugins** [comment]
PR from @kjohnson https://github.com/AffiliateWP/AffiliateWP/pull/1110

**Comment by sumobi** [comment]
Thanks @kjohnson!

It generated a referral once but having trouble generating any new referrals. Will have to dig into it later. @pippinsplugins work ok for you?

**Comment by kjohnson** [comment]
@sumobi Are you using a published form? If the form is not published, then the submission does not get saved. If the submission does not get saved, then there is not reference (post id). And empty reference can only be created once, as `null` seems to be treated as a unique value.

**Comment by kjohnson** [comment]
@sumobi I had originally added a timestamp if the submission was not saved. However, the `referral` column seems to expect a `post_id` to create the hyperlink. Anything other than a `post_id` just creates a broken link, which comes across as bad data.

Not sure how ya'll would want to handle referrals for not-saved submissions.

**Comment by sumobi** [comment]
@kjohnson Yep, was using a published form on a page

**Comment by sumobi** [comment]
Ok weird, works now after trying a fresh set up. A few things we'll need to do for this:

1. Referral amounts are no longer calculated based on the total of the form. If you set the total field to $100, the referral is calculated at $100.

2. If you don't specify a description under the `advanced` section of the add referral action, the referral comes through with a blank description. This should default to the form title as before.

3. When using a product field, the referral doesn't use the field name as the description. As above it will just be blank if not entered

**Comment by kjohnson** [comment]
Ok, I can make those changes.

**Comment by michaelbeil** [comment]
Excellent @kjohnson :smiley:.

**Comment by sumobi** [comment]
Thanks @kjohnson!

**Comment by ramiabraham** [comment]
@kjohnson We're revisiting this and are continuing with the full rewrite of the _Affiliate Forms for Ninja Forms_ add-on, as well as some related AffiliateWP core items. Would you mind confirming the correct branch from which we should be testing Ninja Forms? 

Would it be [3.0-beta](https://github.com/wpninjas/ninja-forms/tree/3.0-beta) or [3.0-beta-1](https://github.com/wpninjas/ninja-forms/tree/3.0-beta-1)?

Thanks

**Comment by ramiabraham** [comment]
related #1110, https://github.com/AffiliateWP/affiliatewp-affiliate-forms-ninja-forms/issues/13

**Comment by kjohnson** [comment]
@ramiabraham you can now use the [master branch](https://github.com/wpninjas/ninja-forms) of Ninja Forms. You will need to [activate the THREE codebase](http://developer.ninjaforms.com/access-ninja-forms-three-today/).

**Comment by ramiabraham** [comment]
Great, thanks @kjohnson

**Comment by ramiabraham** [comment]
Should be good; someone mind checking out the new PR? https://github.com/AffiliateWP/AffiliateWP/pull/1421/

**Comment by pippinsplugins** [comment]
@ramiabraham Is there a particular reason there are so many language files changed with this PR?

**Comment by DrewAPicture** [comment]
@pippinsplugins @ramiabraham Should be fixed now in terms of files changed. Updated from `master`.

**Comment by pippinsplugins** [comment]
There we go! Thanks @DrewAPicture

**Comment by pippinsplugins** [comment]
@ramiabraham A couple of suggestions:

1. Let's put `class-ninja-forms-action-add-referral.php` inside of the `integrations/extras/` folder so it follows the same structure as other integrations that load more than just the main integration class. iThemes Exchange is an example of one.

2. `@since` tags should be updated from `1.8.4` to `1.8.6`.

3. `class-ninja-forms-action-add-referral.php` has some incorrect and missing text domains.

4. In the integration class, `extract( $args );` is an evil function, let's nix it ;)

5. We need to maintain the debug logging. Looks like it has all been removed.

**Comment by ramiabraham** [comment]
@pippinsplugins 💯, Updated as noted.

**Comment by pippinsplugins** [comment]
I still have not been able to get upgraded to NF 3.0. Once I do, I can test this.

**Comment by pippinsplugins** [comment]
@ramiabraham Finally got upgraded to 3 so I was able to test this.

Appears to work fine except for the referral description:
![screen shot 2016-07-13 at 1 46 33 pm](https://cloud.githubusercontent.com/assets/1034109/16815651/48e3ebf2-4900-11e6-9123-fc48c8b161ed.png)

**Comment by ramiabraham** [comment]
@pippinsplugins NF3 does not provide a default form description or fallback, this field has to be manually filled out in Emails & Actions -> Add Referral -> Advanced:

![NF3](http://i.imgur.com/J3FbCVp.png "NF3")


Idea: could fallback to form title, since NF requires that to be filled out?

**Comment by pippinsplugins** [comment]
Can we make the field support field variables? For example: {field:product}

**Comment by kjohnson** [comment]
You can enable Merge Tags for the description, like the total and email settings. https://github.com/AffiliateWP/AffiliateWP/blob/issue/1110/includes/integrations/extras/class-ninja-forms-action-add-referral.php#L61

**Comment by pippinsplugins** [comment]
Thanks @kjohnson!

@ramiabraham could you get that added please?

**Comment by ramiabraham** [comment]
@pippinsplugins Added as noted in https://github.com/AffiliateWP/AffiliateWP/pull/1421/commits/2ecaeaa5d440e91e516dd27c412b816e7aef9a44.


Note: You may need to temporarily switch the `group` name to `primary`, then back to `advanced` to get the merge tags to show in NF. Not sure why.

**Comment by pippinsplugins** [comment]
Fields work just fine in the description field now!

**Comment by pippinsplugins** [comment]
Looks like everything works fine now! I'm going to do a bit more testing then will merge and close.

**Comment by pippinsplugins** [comment]
I'm happy with this.

@sumobi ready to merge?

**Comment by sumobi** [comment]
@ramiabraham @pippinsplugins Not quite, looks like it isn't respecting the total field. 

Total was $500, affiliate's commission is 20%. Affiliate only received $20. Should have received $100.

![screen shot 2016-07-18 at 12 29 33 pm](https://cloud.githubusercontent.com/assets/52581/16904093/7ac89d48-4ce3-11e6-896c-a1a45570dbf7.png)

![screen shot 2016-07-18 at 12 30 03 pm](https://cloud.githubusercontent.com/assets/52581/16904092/7ac7fc4e-4ce3-11e6-82a1-918a87136a6b.png)

![screen shot 2016-07-18 at 12 30 13 pm](https://cloud.githubusercontent.com/assets/52581/16904094/7ac8df24-4ce3-11e6-9d0f-baff2ca3ea64.png)

**Comment by pippinsplugins** [comment]
So probably just need to take quantity into account.

**Comment by kjohnson** [comment]
@sumobi are you mapping the product field, or the total field to the total setting?

**Comment by sumobi** [comment]
Oops! I had `100` entered as total, not mapped at all. Forgot it's not automatic as it used to be.
Now that I've mapped it to `{field:total}` it works fine.

If I map it to `{field:product}` it comes out as $0.00 as expected since it's not a total field

**Comment by ramiabraham** [comment]
Merged. Thanks for your help, @kjohnson!
