### ISSUE TITLE
Update Exchange Coupon Integration to use tabbed interface

### ISSUE THREAD

**Issue by TimothyBJacobs** [AffiliateWP/AffiliateWP#1107]
In version 1.33 of Exchange, we added a tabbed interface for coupons. Currently the Affiliate field appears at the end of the form, but should be moved to the General tab.
![affiliate wp exchange coupon](https://cloud.githubusercontent.com/assets/3460448/13134682/33aedd92-d5d7-11e5-932f-9a85a59592a2.png)

**Comment by pippinsplugins** [comment]
Love it, thanks!

**Comment by TimothyBJacobs** [comment]
👍

**Comment by pippinsplugins** [comment]
Works great!

**Comment by pippinsplugins** [comment]
This can be merged once unit tests pass.
