### ISSUE TITLE
Add new default referral URL setting

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1111]
We should move this code snippet into core since it's requested many times
http://docs.affiliatewp.com/article/834-change-the-urls-shown-in-the-affiliate-urls-tab-of-the-affiliate-area

**Comment by sumobi** [comment]
First pass: https://github.com/AffiliateWP/AffiliateWP/tree/issue/1111

Made a new `url` callback which could come in handy later on. The only difference between the `text` field is the URL type so uses the browser's validation for now.

<img width="968" alt="screen shot 2016-03-02 at 11 03 51 pm" src="https://cloud.githubusercontent.com/assets/52581/13457100/2b4acf36-e0cb-11e5-831e-67bda8472ce4.png">
<img width="754" alt="screen shot 2016-03-02 at 11 04 13 pm" src="https://cloud.githubusercontent.com/assets/52581/13457099/2b4a379c-e0cb-11e5-93bc-90f33922c502.png">

@pippinsplugins 1.7.15?

**Comment by michaelbeil** [comment]
Seems like a good fit for 1.7.15.

**Comment by pippinsplugins** [comment]
I like it.
