### ISSUE TITLE
Referrals not generating for free membership levels

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1117]
Referrals aren't being generated for free membership levels in Paid Memberships Pro. This is because `$order->membership_name` cannot be found for a free membership level. It's set fine for a non-paid level: https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-pmp.php#L51

related: https://secure.helpscout.net/conversation/174089601/28432/?folderId=205527

**Comment by pippinsplugins** [comment]
@sumobi small change on PR then this is good.

**Comment by sumobi** [comment]
@pippinsplugins done
