### ISSUE TITLE
LifterLMS Integration

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1119]
Proposal: add LifterLMS integration.

Some info: 208 `do_action`s and 268 `apply_filters` are available.

**Comment by pippinsplugins** [comment]
Milestoned for 1.5.8.

**Comment by pippinsplugins** [comment]
1.8.3 actually.

**Comment by pippinsplugins** [comment]
@ramiabraham could you please test this integration tomorrow? If all is working, please also go ahead and write up the documentation page for it.

**Comment by ramiabraham** [comment]
Looks good here.

- LifterLMS coupons are attributed to the correct AffiliateWP affiliate. 
- Aside from the noted js-related adjustment made in https://github.com/AffiliateWP/AffiliateWP/commit/89a0895d2fccee6c95750c9c4bfb737ab9ebec9a, there were no other required adjustments.

Will update when doc is completed for review.

**Comment by michaelbeil** [comment]
Looking good. Just made a few comments on the latest commit.

**Comment by pippinsplugins** [comment]
Just pushed a couple of minor changes to https://github.com/AffiliateWP/AffiliateWP/pull/1368. Once tests pass, we can merge.

**Comment by michaelbeil** [comment]
Looks good.

**Comment by michaelbeil** [comment]
New PR: #1368
