### ISSUE TITLE
Integration for s2Member

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#112]

**Comment by jaswsinc** [comment]
@pippinsplugins I'm the lead at s2Member. I was just about to write an article you guys, when I came across this issue. Anything that we can do to help you out here?

**Comment by pippinsplugins** [comment]
@jaswsinc do you have a list of hooks that would make this possible? Last time I looked I couldn't find any of the necessary hooks for tying into the purchase process.

**Comment by jaswsinc** [comment]
@pippinsplugins Sure :-) Here is my suggestion, because this will work for all types of transactions that s2Member processes, and it will also allow you to track recurring payments too—across both the lite and pro versions of s2Member.

```php
<?php
add_action('ws_plugin__s2member_loaded', 's2_affiliatewp_integration');

function s2_affiliatewp_integration(){
  $s2_options = &$GLOBALS['WS_PLUGIN__']['s2member']['o'];
  // ↑ Array of all s2Member plugin config. options.
  
  $s2_payment_notification_urls = &$s2_options['payment_notification_urls'];
  // ↑ Line-delimited list of URLs to notify. See: `Dashboard → s2Member → API Notifications → Payment Notifications`
  
  // Create your payment notification URL for affiliate commission tracking.
  // See: `Dashboard → s2Member → API Notifications → Payment Notifications` for a full list of all %%Replacement Codes%%
  $affiliatewp_url = home_url('/?affiliatewp_notify=yes&amount=%%amount%%&txn_id=%%txn_id%%&item_name=%%item_name%%&&ip=%%user_ip%%');
  
  // Add your notification URL to the list dynamically.
  if(stripos($s2_payment_notification_urls, 'affiliatewp') === FALSE)
    $s2_payment_notification_urls .= trim("\n".$affiliatewp_url);
}
```

---

Here is a screenshot of the panel in s2Member (this is in the [free version](https://wordpress.org/plugins/s2member/) too), where you will find a list of all of the `%%` replacement codes that we make available to affiliate software applications whenever a payment is processed.

See: **Dashboard → s2Member → API / Notifications → Payment Notifications**

_**Note:** the code snippet I provided above is simply adding a URL that you can use to receive information you need; i.e., adding it to this list dynamically, so that your users don't need to do that on their own. So all that's left is for you to build a script (maybe you already have one) that receives this information and creates a commission based on the user's IP address. In the screenshot below you will see an example URL that iDevAffiliate uses ([more info here](http://s2member.com/kb-article/idevaffiliate-commission-tracking/))._

![2015-06-05_10-31-52](https://cloud.githubusercontent.com/assets/1563559/8012706/eeab0a4a-0b6f-11e5-845e-a5849f30ee7f.png)

---

Also, here is a coupon code (good for you only), where you can grab a copy of the pro version for testing. Please complete checkout here for any version you like: http://s2member.com/prices/ ~ COUPON: `PIPPIN` ... if you have any problem with any of this just let me know :-)

_You can also contact us privately if you need to: http://www.websharks-inc.com/bizdev/_

---

Finally, I'm happy to help you test this once you get to that point. Just reply back here if you like.

**Comment by jaswsinc** [comment]
cc @raamdev ~ my partner who works on s2Member also.
Just an FYI. Isn't is great to see this! :-)

**Comment by tubiz** [comment]
@pippinsplugins was also stuck initially with the integration for s2member because I didn't know which action to hook into.
Now that a s2member lead has given some pointers, will like to know if I can work on it if you haven't started working on it.

**Comment by raamdev** [comment]
> Just an FYI. Isn't it great to see this! :-)

Awesome! Looking forward to this integration. Thanks for the cc @jaswsinc.  :-)

**Comment by pippinsplugins** [comment]
Thanks guys. We'll look into this for v1.7.

**Comment by tubiz** [comment]
@pippinsplugins @sumobi hope this is still available. Will like to continue with it.

**Comment by pippinsplugins** [comment]
@tubiz all yours!

**Comment by tubiz** [comment]
@pippinsplugins which action should be used when marking a referral as complete. Have tried using wp, init and template redirect in my s2member integration class but the affwp_ref cookie isn't available. Therefore the was_referred function always returns false.

**Comment by pippinsplugins** [comment]
@tubiz I don't know s2member well enough to say for sure, sorry. What action do they hook into?

**Comment by tubiz** [comment]
@pippinsplugins am hooking into the init action to mark a referral as complete but ```$_COOKIE['affwp_ref'];``` and  ```$_COOKIE['affwp_ref_visit_id'];``` are always empty.

**Comment by pippinsplugins** [comment]
@tubiz Could you show me an example of how you're trying to do it?

**Comment by tubiz** [comment]
@pippinsplugins here is the link to a gist of my work so far. https://gist.github.com/tubiz/96a952e15e9a21f659b7

**Comment by pippinsplugins** [comment]
@tubiz Does the line below tell s2Member where to send a POST notification after a purchase?

https://gist.github.com/tubiz/96a952e15e9a21f659b7#file-class-s2member-php-L24

**Comment by tubiz** [comment]
Yes. That what it does.

**Comment by pippinsplugins** [comment]
If you remove the `$this->was_referred()` check, does it work?

**Comment by tubiz** [comment]
Removing ```$this->was_referred()``` still doesn't work.
Also ```affiliate_wp()->tracking->get_affiliate_id()``` always return 0.

**Comment by pippinsplugins** [comment]
Oh I know why it's failing. The POST request sent by s2Member doesn't contain the same cookies. It's not the same as the site visitor loading the page so the tracking variable isn't set.

Can the URL that the POST is sent to be modified via a filter before it is sent?

**Comment by jaswsinc** [comment]
> Can the URL that the POST is sent to be modified via a filter before it is sent?

Yes. Here's an example:

```php
<?php
add_action('ws_plugin__s2member_before_wp_remote_request', function($vars){
  $url = &$vars['__refs']['url']; // A PHP reference to the URL.
  if (strpos($url, '/something-identifying-affiliate-wp/') !== false) {
    $url = str_replace('this', 'that', $url); // Filter by reference.
  }
});
```

Referencing: https://github.com/websharks/s2member/blob/150722/s2member/includes/classes/utils-urls.inc.php#L222

**Comment by pippinsplugins** [comment]
@tubiz That looks like it should work.

**Comment by tubiz** [comment]
@pippinsplugins what will be added to the modified URL.

**Comment by pippinsplugins** [comment]
@tubiz modify the URL to include the affiliate's referral variable / ID.

**Comment by tubiz** [comment]
@jaswsinc I am almost done with the s2Member integration for AffiliateWP but I have some clarifications.
I am adding the Affiliate ID if set using the action 
```ws_plugin__s2member_before_sc_paypal_button_after_shortcode_atts``` that I saw in the free version  of s2Member plugin.
Is the action the same for the paypal gateway in the pro version and for other payment gateways that the pro version supports.

**Comment by jaswsinc** [comment]
> ws_plugin__s2member_before_sc_paypal_button_after_shortcode_atts that I saw in the free version of s2Member plugin.
> Is the action the same for the paypal gateway in the pro version and for other payment gateways that the pro version supports.

No, that is PayPal-specific, and Button-specific.
See: https://github.com/affiliatewp/AffiliateWP/issues/112#issuecomment-109396799

**Comment by pippinsplugins** [comment]
@tubiz is there anything I can help with on this?

**Comment by tubiz** [comment]
@pippinsplugins actually I got it to work.
But there are some important notes. I am using s2Member custom replacement codes to pass the affiliate id if it set to the gateway, so this is sent back with the payment notification that is received.
For this to work s2member payment shortcode has to be used. 

In the free version of the plugin am using 
```ws_plugin__s2member_before_sc_paypal_button_after_shortcode_atts``` to pass the affiliate id to the shortcode, and it worked perfectly, I was able to insert and mark a referral as complete from the payment notification that I got.

I will like to know if the pro version which has many payment options uses the same action or one that is similar.
Also can i use the promo code that was created for you to get the pro version?

The gist I created initially https://gist.github.com/tubiz/96a952e15e9a21f659b7 has been updated with the working version for the paypal gateway that comes with the free version.

Will appreciate if @jaswsinc can help clarify this.
Also when is the best way to mark a referral as cancelled when a subscriber cancel his subscription from the gateway.

**Comment by pippinsplugins** [comment]
@tubiz Awesome, great work.

**Comment by jaswsinc** [comment]
@tubiz writes...

> In the free version of the plugin am using 
> ws_plugin__s2member_before_sc_paypal_button_after_shortcode_atts to pass the affiliate id to the shortcode, and it worked perfectly, I was able to insert and mark a referral as complete from the payment notification that I got.

I see. Thanks for explaining. Here are the others that you requested. This will cover the pro version shortcodes for the remaining payment gateway integrations.

- [`ws_plugin__s2member_pro_before_sc_stripe_form_after_shortcode_atts`](https://github.com/websharks/s2member-pro/blob/150722/s2member-pro/includes/classes/gateways/stripe/stripe-form-in.inc.php#L150)
- [`ws_plugin__s2member_pro_before_sc_authnet_form_after_shortcode_atts `](https://github.com/websharks/s2member-pro/blob/150722/s2member-pro/includes/classes/gateways/authnet/authnet-form-in.inc.php#L140)
- [`ws_plugin__s2member_pro_before_sc_paypal_form_after_shortcode_atts `](https://github.com/websharks/s2member-pro/blob/150722/s2member-pro/includes/classes/gateways/paypal/paypal-form-in.inc.php#L145)

**Comment by tubiz** [comment]
@jaswsinc thanks.
Just one last question, to cancel a referral when a subscription is cancelled, guess I have to create a cancellation notification url.

@pippinsplugins is there need for a referral to be revoked when a subscription is cancelled. I think it should be when a refund is issued.

**Comment by pippinsplugins** [comment]
@tubiz only during refund.

@jaswsinc It would be great if there was a single filter that applied to all short codes along with the unique ones.

**Comment by jaswsinc** [comment]
@tubiz writes...

> Just one last question, to cancel a referral when a subscription is cancelled, guess I have to create a cancellation notification url.

Exactly! :-) Here's another example. Not much different from the [example I gave previously](https://github.com/affiliatewp/AffiliateWP/issues/112#issuecomment-109396799), which was for the Payment Notification. However, this example is for Cancellation Notifications.

```php
<?php
add_action('ws_plugin__s2member_loaded', 's2_affiliatewp_integration');

function s2_affiliatewp_integration(){
  $s2_options = &$GLOBALS['WS_PLUGIN__']['s2member']['o'];
  // ↑ Array of all s2Member plugin config. options.

  $s2_cancellation_notification_urls = &$s2_options['cancellation_notification_urls'];
  // ↑ Line-delimited list of URLs to notify. See: `Dashboard → s2Member → API Notifications → Cancellation Notifications`

  // Create your cancellation notification URL for affiliate commission removal.
  // See: `Dashboard → s2Member → API Notifications → Cancellation Notifications` for a full list of all %%Replacement Codes%%
  $affiliatewp_url = home_url('/?affiliatewp_notify=yes&subscr_id=%%subscr_id%%&item_name=%%item_name%%&&ip=%%user_ip%%');

  // Add your notification URL to the list dynamically.
  if(stripos($s2_cancellation_notification_urls, 'affiliatewp') === FALSE)
    $s2_cancellation_notification_urls .= "\n".$affiliatewp_url;
}
```

See also: **Dashboard → s2Member → API / Notifications → Cancellation Notifications**

![2015-08-26_00-27-45](https://cloud.githubusercontent.com/assets/1563559/9488925/bd6985a6-4b89-11e5-95c7-7923e5c12df6.png)

**Comment by jaswsinc** [comment]
@pippinsplugins writes...

> It would be great if there was a single filter that applied to all short codes along with the unique ones.

Noted. Will do :-)

**Comment by tubiz** [comment]
@jaswsinc thanks for the help so far. Does s2Member have a after refund action?

**Comment by pippinsplugins** [comment]
@tubiz Could you open a PR for this in the next day or two so @sumobi  and I can help test it? I'd love to get it included with version 1.7

**Comment by tubiz** [comment]
@pippinsplugins will send a PR later today. The only thing left is just an action for the refund still waiting for a response from @jaswsinc

**Comment by pippinsplugins** [comment]
Great!

**Comment by jaswsinc** [comment]
> Does s2Member have a after refund action?

Yes. This covers both refunds and reversals (i.e., chargebacks).

```php
<?php
add_action('ws_plugin__s2member_loaded', 's2_affiliatewp_integration');

function s2_affiliatewp_integration(){
  $s2_options = &$GLOBALS['WS_PLUGIN__']['s2member']['o'];
  // ↑ Array of all s2Member plugin config. options.

  $s2_ref_rev_notification_urls = &$s2_options['ref_rev_notification_urls'];
  // ↑ Line-delimited list of URLs to notify. See: `Dashboard → s2Member → API Notifications → Refund/Reversal Notifications`

  // Create your refund/reversal notification URL for affiliate commission removal.
  // See: `Dashboard → s2Member → API Notifications → Refund/Reversal Notifications` for a full list of all %%Replacement Codes%%
  $affiliatewp_url = home_url('/?affiliatewp_notify=yes&subscr_id=%%subscr_id%%&item_name=%%item_name%%&&ip=%%user_ip%%');

  // Add your notification URL to the list dynamically.
  if(stripos($s2_ref_rev_notification_urls, 'affiliatewp') === FALSE)
    $s2_ref_rev_notification_urls .= "\n".$affiliatewp_url;
}
```

See also: **Dashboard → s2Member → API / Notifications → Refund/Reversal Notifications**

![2015-08-31_13-15-31](https://cloud.githubusercontent.com/assets/1563559/9590646/723ca81c-4fe2-11e5-8c5e-8ae32914baf3.png)

**Comment by tubiz** [comment]
@jaswsinc thanks so much. Does s2member has a way of getting the tax amount for a payment

**Comment by jaswsinc** [comment]
@tubiz writes...

> Does s2member has a way of getting the tax amount for a payment

No. Not yet. The `%%amount%%` includes the tax, but we don't have a separate `%%tax%%` replacement code in there yet. I'll let you know whenever we have one available.

**Comment by tubiz** [comment]
@jaswsinc thanks so much for the help provided so far.
I noticed that refund notification doesn't work for Stripe but it does for Paypal.

**Comment by pippinsplugins** [comment]
@jaswsinc Is there an MD5 hash includ in the POST notifications or anything similar that we could use to verify that the notification is legitimate? Right now anyone running the s2Member integration could be susceptible to fraudulent referrals. If I wanted to fake a referral, all I'd need to do is send a POST request with the necessary data.

**Comment by jaswsinc** [comment]
@pippinsplugins writes...

> Is there an MD5 hash includ in the POST notifications or anything similar that we could use to verify that the notification is legitimate?

No, I'm afraid not. However, there is nothing to stop you from including a secret key in the URL in order to verify the origin of the request; e.g., `?affiliatewp_site_key=xxxxxxxxxxxxxxxxx`

**Comment by jaswsinc** [comment]
@tubiz writes...

> I noticed that refund notification doesn't work for Stripe but it does for Paypal.

Thank you for reporting this. It looks like a bug. I'm opening an issue here so that we can track this. https://github.com/websharks/s2member/issues/706

**Comment by pippinsplugins** [comment]
@tubiz Could you add in a verification system? Do an MD5 on the WP salts in wp-config.php and verify it matches before processing the post request.

**Comment by tubiz** [comment]
@pippinsplugins so I should concatenate all the WP Salts (AUTH_SALT, SECURE_AUTH_SALT, LOGGED_IN_SALT & NONCE_SALT) and perform an MD5 hash on it.

**Comment by pippinsplugins** [comment]
I wouldn't worry about using all of them. Something like this: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/api/class-edd-api.php#L1861

**Comment by tubiz** [comment]
@pippinsplugins verification check has been added.

**Comment by pippinsplugins** [comment]
@tubiz thank you so much for your work on this! I made a few small tweaks but otherwise it's working great!

**Comment by pippinsplugins** [comment]
@sumobi I've merged this into `release/1.7`. Could you give it a test (pro version is in Dropbox).

If you are testing on a local host, you will need to use Buy Now buttons (use Stripe). If you are on a live server, make sure your IPN / webhooks are configured as they are required for referral tracking to work.

**Comment by pippinsplugins** [comment]
@sumobi integration doc draft created too: https://secure.helpscout.net/docs/5463d15be4b0f639418397d0/article/55ec5839c69791431cfbad11

**Comment by tubiz** [comment]
@pippinsplugins am glad I could help out with it.

**Comment by pippinsplugins** [comment]
My signup shortcode:
![screen shot 2015-09-15 at 7 06 48 am](https://cloud.githubusercontent.com/assets/1034109/9876002/5c51cbee-5b78-11e5-9b8b-f143b6857598.png)

Referral after signing up:
![screen shot 2015-09-15 at 7 10 39 am](https://cloud.githubusercontent.com/assets/1034109/9876080/e5fe2a22-5b78-11e5-8226-44c7de45349d.png)

**Comment by pippinsplugins** [comment]
Everything is working perfectly for me :+1:

**Comment by pippinsplugins** [comment]
@jaswsinc this is completely unrelated but I have a small piece of feedback for you. The admin menu is _way_ to big. On an 11inch Macbook Air, I can't even see all items in the admin menu because it's so incredibly tall: https://cloudup.com/curVnqDbBGK It would be nice to see those consolidated.

**Comment by claudiosw** [comment]
@pippinsplugins I would like to have this integration. When can I have it?
I'm already a AffiliateWP client.
Thanks everyone for making it work!

**Comment by pippinsplugins** [comment]
It will be available as soon as v1.7 is released.

**Comment by claudiosw** [comment]
@pippinsplugins thanks for the quick response!
May I have an estimate when the v1.7 will be released?

**Comment by pippinsplugins** [comment]
We're aiming for later this week.

**Comment by claudiosw** [comment]
@pippinsplugins wonderful! Looking forward for it.
Many thanks!
