### ISSUE TITLE
Per-affiliate Referral Rate Type isn't respected

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1132]
If an affiliate's `Referral Rate Type` is set to `Flat` and no `Referral Rate` is set, the affiliate's rate should be set to a flat amount. In the following scenario the affiliate's rate should be set to `$15`:

![screen shot 2016-03-10 at 7 39 07 pm](https://cloud.githubusercontent.com/assets/52581/13661474/cd912f7e-e6f7-11e5-870a-5cf8f77c781c.png)

Instead it is set to `15%` as % is selected as the global referral rate type.

![screen shot 2016-03-10 at 7 40 09 pm](https://cloud.githubusercontent.com/assets/52581/13661494/f3e6c6b6-e6f7-11e5-8850-f5dcefe649c9.png)

___

Global settings:
![screen shot 2016-03-10 at 7 40 41 pm](https://cloud.githubusercontent.com/assets/52581/13661503/027854b0-e6f8-11e5-98e1-ba4daf4accf0.png)
___
In order to get the affiliate's rate to show correctly as `$15` the Referral Rate must also be set:

![screen shot 2016-03-10 at 7 41 55 pm](https://cloud.githubusercontent.com/assets/52581/13661530/2d0c76e8-e6f8-11e5-9fe1-710d31cd3999.png)
___
![screen shot 2016-03-10 at 7 42 16 pm](https://cloud.githubusercontent.com/assets/52581/13661536/39ce33da-e6f8-11e5-948e-c30b4d7c455d.png)

**Comment by pippinsplugins** [comment]
@sumobi give that a try.

**Comment by sumobi** [comment]
@pippinsplugins works great for me

**Comment by pippinsplugins** [comment]
Looks like we're not merged in.
