### ISSUE TITLE
Visits page - filter issues

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1137]
When testing the visits page I noticed a few issues:

1. When you enter an affiliate's name into the search field it disappears between each search.
2. If you select `Converted` when performing a search, you can also see unconverted visits.  
3. If you select `Unconverted` when performing a search, you can also see converted visits.

Steps to reproduce:

1. Go to visits 
2. Type in an affiliate 
3. Select a date range (or none at all)
4. Select converted/unconverted
5. Click filter

![global slack-imgs](https://cloud.githubusercontent.com/assets/4752949/13693639/b24ae05a-e712-11e5-875d-7e351cdd3e63.png)

It'd be nice to make this a better experience :sunglasses:.

**Comment by pippinsplugins** [comment]
Let's see if we can get this fixed up shortly after 1.8

**Comment by michaelbeil** [comment]
Got a status update request from a customer about this: https://secure.helpscout.net/conversation/177023023/29070/?folderId=634609. 

Should we think about adding this to 1.8.2 or .3?

**Comment by pippinsplugins** [comment]
Milestone updated!

**Comment by michaelbeil** [comment]
Perfect!

**Comment by DrewAPicture** [comment]
Added a PR that fixes all three issues as described: #1324

**Comment by pippinsplugins** [comment]
@michaelbeil Could you test this?

**Comment by michaelbeil** [comment]
All gravy here.
