### ISSUE TITLE
Show integration context/name on the referral edit page

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1139]
For customers who have multiple integrations, it would be great to be able to easily distinguish which integration a referral was generated from. A potential way we could do this is by showing the integration's context (e.g. `gravityforms`, `it-exchange`) as a _non-editable_ value/text (e.g. Gravity Forms, iThemes Exchange) on the referral edit screen.

Another place this may be useful to show is in the CSV export file for referrals - great for reporting purposes at year-end (or in general) and to see where (the majority) of referrals are coming from - for example, seeing that more referrals are coming from product sales than a membership, or more referrals are coming from submissions than product sales.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
:+1: Would be useful

**Comment by michaelbeil** [comment]
This would be very helpful to site owners.

**Comment by DrewAPicture** [comment]
We already show the context in an *editable* field in Edit Referral:

![Context](https://cl.ly/332E273q3y3P/Screen%20Shot%202016-07-29%20at%203.56.40%20PM.png)

As well as include it in the referrals CSV export:

![CSV](https://cl.ly/0e3y2l3e0L0W/Screen%20Shot%202016-07-29%20at%203.58.45%20PM.png)

So maybe close this as fixed?

**Comment by ramiabraham** [comment]
I'd consider this implemented already, but Lisa raises a good debugging tool potential of adding _another_ field that _can't_ be changed; possibly even a hidden one. 

If _that's_ something we're into, perhaps better to punt to `.7`?

**Comment by DrewAPicture** [comment]
@ramiabraham I was kind of thinking that maybe we should only make it readonly if it's not empty. It makes sense to want to *add* context if there isn't any, but not so much to remove it.

**Comment by pippinsplugins** [comment]
I vote we make it a read only field if it has a value.

**Comment by DrewAPicture** [comment]
Added a PR: #1492 

If the 'context' field is not empty, set to readonly, otherwise editable.

**If 'context' is empty in Referral > Edit:**
![empty](https://cl.ly/2M3u1J0R0O1L/1139_empty.png)

**If 'context' is not empty in Referral > Edit:**
![not empty](https://cl.ly/2l3x3d372S1l/1139_not_empty.png)

**Comment by pippinsplugins** [comment]
PR looks good.

**Comment by DrewAPicture** [comment]
Tests passed, merged #1492.
