### ISSUE TITLE
EDD: PHP notices when manually adding renewal paymen

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1151]
When manually adding a renewal payment in EDD Recurring 2.4+:

Warning: Missing argument 4 for Affiliate_WP_Recurring_EDD::record_referral_on_payment() in wp-content/plugins/affiliate-wp-recurring-referrals/integrations/class-edd.php on line 26

Warning: Missing argument 5 for Affiliate_WP_Recurring_EDD::record_referral_on_payment() in wp-content/plugins/affiliate-wp-recurring-referrals/integrations/class-edd.php on line 26

Warning: Cannot modify header information - headers already sent by (output started at wp-content/plugins/affiliate-wp-recurring-referrals/integrations/class-edd.php:26) in wp-includes/pluggable.php on line 1228

**Comment by DrewAPicture** [comment]
Moved to [AffiliateWP_Recurring_Referrals/30](https://github.com/AffiliateWP/affiliate-wp-recurring-referrals/issues/30) with an attached PR.
