### ISSUE TITLE
Admin Query Hooks

### ISSUE THREAD

**Issue by clickstudio** [AffiliateWP/AffiliateWP#1152]
I have a client who requires affiliates to be managed by their affiliate manager.

I can handle the code to link an affiliate with another user however I can't see any hooks in any of the db functions/queries.

Any advice on the best way forward ?

**Comment by michaelbeil** [comment]
Hey @clickstudio,

This GitHub repository is used for AffiliateWP core development purposes. Could you please send any support requests here: https://affiliatewp.com/support.

**Comment by clickstudio** [comment]
Hi Michael,

I had planned on adding some pull requests and just wanted to discuss the best approach.
Not sure that's a support question.

**Comment by michaelbeil** [comment]
Oh ok, well you can feel free to submit a PR so we can see what exactly you are wanting to change/add.

**Comment by clickstudio** [comment]
Sure thing Michael. Will do!

Cheers

**Comment by michaelbeil** [comment]
You can leave this open and reference this issue number in your PR :smile:.

**Comment by michaelbeil** [comment]
Hey @clickstudio,

Just wondering if you wanted to submit a PR for this still.

**Comment by clickstudio** [comment]
Hi @michaelbeil 

The client who's needs required this hook, decided on a different direction so it's not required now.

Thanks

**Comment by michaelbeil** [comment]
Alrighty.

Cheers!
