### ISSUE TITLE
Store user ID from posted username, rather than hidden input field

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1156]
Related: https://github.com/AffiliateWP/AffiliateWP/issues/1116

AffiliateWP provides a popup when searching for an affiliate. If you click an affiliate in the search popup, it stores the affiliate's user ID in a hidden input field. This will not correctly store the affiliate's user ID in some instances. Here's a couple:
1. When the site admin manually types in the affiliate's username, sees the affiliate they want, and finishes off typing without selecting the affiliate from the popup search box.
2. When there's already an affiliate entered and the site admin deletes it then enters a new username, again without using the affiliate search.

I propose we always work out the user ID based on the posted username, and not rely on the user ID posted along with the user_id field. This means the user ID will be always be correct, when the affiliate username is typed in by the site admin, or the username is selected from the search popup. It's an extra small step but much better IMO, unless I'm missing something obvious.

**Comment by pippinsplugins** [comment]
I agree.

**Comment by michaelbeil** [comment]
This would be an excellent change. I have come across it on several occasions.

**Comment by DrewAPicture** [comment]
Once #1184/#1301 land, retrieving affiliates via username will be possible, and this should be fairly trivial to implement.

**Comment by DrewAPicture** [comment]
Started a PR: #1893

**Comment by DrewAPicture** [comment]
Note that the PR touches every place in core where we use the affiliate autocomplete form, including within integrations. The PR is "in progress" but only insofar as testing.

**Comment by DrewAPicture** [comment]
Added unit tests.

**Comment by pippinsplugins** [comment]
Lost the code duplication this removes.

**Comment by pippinsplugins** [comment]
@DrewAPicture I've started to test this. It works perfectly for adding new affiliates for existing user accounts. It does not work, however, for adding new referrals.

I tried to add a referral for affiliate `leslie` but `Pippin 1` is the affiliate that received it.
![screen shot 2017-01-06 at 12 16 01 pm](https://cloud.githubusercontent.com/assets/1034109/21728104/0a92a164-d40a-11e6-989a-2dc0d21d3900.png)
![screen shot 2017-01-06 at 12 17 10 pm](https://cloud.githubusercontent.com/assets/1034109/21728112/1408813c-d40a-11e6-805b-e4e9df2e82bc.png)

`Leslie` and `Pippin 1` are definitely different affiliate accounts.

**Comment by DrewAPicture** [comment]
@pippinsplugins Hmm. I just tried manually adding a referral with two different affiliates and it worked just fine.

**Comment by DrewAPicture** [comment]
Nevermind, I reproduced it.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by DrewAPicture** [comment]
@pippinsplugins OK, should work now as expected. The code made an assumption that if a `$new_key` value was supplied that the value passed to it would also match, which of course is poppycock. So, we were passing `affiliate_id` as the `$new_key` value but it was returning the user ID under the `affiliate_id` key. It's been removed and simplified.

**Comment by pippinsplugins** [comment]
Works now!

**Comment by DrewAPicture** [comment]
Merged #1893.
