### ISSUE TITLE
Add new hook to dashboard-tab-urls.php

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1157]
The custom affiliate slugs add-on will need to output the custom slug similarly to how the ID and username are shown here: https://github.com/AffiliateWP/AffiliateWP/blob/master/templates/dashboard-tab-urls.php#L5-L9

We'll need a new hook, I'm proposing:

`<?php do_action( 'affwp_affiliate_dashboard_urls_top', affwp_get_affiliate_id() ); ?>`

We should also try and keep the same consistency in our hook names, I'm seeing quite a few get out of sync. For dashboard hooks I vote we follow the same as above, where `urls` would be replaced with the current tab, eg `visits`, `stats`, or `referrals`. Then `top` or `bottom`, `before` or `after`.

**Comment by pippinsplugins** [comment]
:+1:
