### ISSUE TITLE
AffiliateWP and Mandrill causes line-breaks in emails

### ISSUE THREAD

**Issue by DevinWalker** [AffiliateWP/AffiliateWP#1164]
AffiliateWP and Mandrill adds linebreaks when sending WP emails through Mandrill - same thing that was on EDD until fixed by this: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/plugin-compatibility.php#L136

**Comment by michaelbeil** [comment]
Thanks for notifying us. This seems like a quick and easy fix and the PR looks good. 

@pippinsplugins ?

**Comment by pippinsplugins** [comment]
Thanks!
