### ISSUE TITLE
Standardize setting and saving settings on the fly

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1171]
In #999 I've added a `Affiliate_WP_Settings::set()` method to better facilitate testing, and @pippinsplugins suggested pairing that with a `save()` method on the related PR. After some discussion, we decided this should be its own task.

Much like `EDD_Payments`, which uses a `$pending` property to effectively queue settings changes, we can do the same thing for AWP settings, which will help us reduce code duplication in various places, while simultaneously simplifying and standardizing best-practice for saving AWP settings.

In [install.php](../blob/master/includes/install.php#L38), for instance, here's what that might look like:

**Current:**
```php
$options = $affiliate_wp_install->settings->get_all();
$options['affiliates_page'] = $affiliate_area;
update_option( 'affwp_settings', $options );
```

**Queuing via `set()` and saving via `save()`:**
```php
$affiliate_wp_install->settings->set( 'affiliates_page', $affiliate_area );
$affiliate_wp_install->settings->save();
```

**Queuing via `set()` and saving in the same step with an optional third parameter:**
```php
$affiliate_wp_install->settings->set( 'affiliates_page', $affiliate_area, $save = true );
```

**A third option would be to allow chaining with the `set()` method, e.g.:**
```php
$affiliate_wp_install->settings->set( 'affiliates_page', $affiliate_area )->save();
```

Either way, the addition of the `set()` method in #999 only works in memory. A `save()` method obviously has the ability to literally save that value, so we'd probably want to implement a whitelist based on register setting keys or similar to prevent misuse.

**Comment by pippinsplugins** [comment]
I prefer this option:
```php
$affiliate_wp_install->settings->set( 'affiliates_page', $affiliate_area, $save = true );
```

**Comment by DrewAPicture** [comment]
Added a PR: #1172 

Tests incoming.

**Comment by pippinsplugins** [comment]
This is really excellent. Merging as is.

**Comment by pippinsplugins** [comment]
I've tested this quite a bit. @sumobi @michaelbeil could you guys run through some quick tests too just to make sure no edge case was missed? It's merged into `release/1.8`.

**Comment by michaelbeil** [comment]
This is great. Did a once over and the settings area still works :smile:. Saving settings is super speedy!

**Comment by sumobi** [comment]
All looks good to me
