### ISSUE TITLE
Generate payout csv for single affiliate

### ISSUE THREAD

**Issue by flowdee** [AffiliateWP/AffiliateWP#1173]
Tried to generate a payout csv and mark unpaid referrals as paid for specific affiliate. Therefore I navigated to referrals, clicked on the affiliate name and filtered for unpaid earnings. 

Due to the fact that the url included the affiliate id i thought when I create a csv on this page, only the active affiliate will be taken.

But sadly ALL unpaid earnings were marked as paid.

Shouldn't this be better working like I expected?

**Comment by pippinsplugins** [comment]
I've seen a few requests for this. We should definitely build it.

**Comment by wordmaid** [comment]
Another request for this here: https://secure.helpscout.net/conversation/274402777/46272/?folderId=205524

**Comment by DrewAPicture** [comment]
Closing in favor of #1046.
