### ISSUE TITLE
Our PHP tests coverage can be improved

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1175]
@pippinsplugins has given me the :+1: to push forward with improving our test coverage.

Note: This work is reliant on 1.8-milestoned test coverage already added.

I've started this effort by mildly changing how our tests are organized to be more predictable.
PR: #1174 (also covers some misc-functions.php tests)

I have a feeling this issue will probably just stay open and serve as a tracker for the inevitable multitude of PRs that will be attached to it.

The overall goal would be to extend test coverage to as much of the existing code base as possible. The work done in #1171 helps us out in a big way toward those goals.

**Comment by pippinsplugins** [comment]
:+1: x 1000

Initial improvements in #1174 merged in.

**Comment by DrewAPicture** [comment]
Let's close this in favor of targeted tests issues.
