### ISSUE TITLE
Add default statement to notices class

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1182]
Related: https://github.com/AffiliateWP/AffiliateWP/issues/1078

Any reason why we can't add a `default` statement here?
https://github.com/AffiliateWP/AffiliateWP/blob/release/1.8/includes/admin/class-notices.php#L226

I've just added an admin notice to the `Allowed Products` add-on but it won't be able to save the user meta once 1.8 is released, since it doesn't match any of the notices allowed.

**Comment by pippinsplugins** [comment]
@sumobi Nope. Let's add a `default` with a `do_action`.

**Comment by DrewAPicture** [comment]
Added a PR: #1212

**Comment by pippinsplugins** [comment]
Merged.
