### ISSUE TITLE
Core objects for affiliates, referrals, creatives, and visits

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1184]
In preparation for a possible REST endpoints in 1.9, we should switch to using a legitimate objects for affiliates, referrals, creatives, and visits over `stdClass`. This would vastly simplify any testing we have in place as well as code leveraging IDs or objects everywhere.

The other upside of having predictably-structured objects is exposure via REST endpoints or WP-CLI command support down the line would be instantly reflected without having to do things twice.

**Comment by DrewAPicture** [comment]
Related: #1267

**Comment by DrewAPicture** [comment]
For some perspective on what this looks like in memcached, here's the hit/miss table. Hint: it's working:
![Memcached hit/miss](http://cl.ly/1O1F0Y100u2Q/Screen%20Shot%202016-05-21%20at%209.31.16%20AM.png)

In monitoring the live stats when loading queries such the Affiliates > Affiliates screen et al or performing CRUD operations, we're consistently seeing SETs spiking as expected at the time of change then cratering out on the second load along with high HIT percentages. All good signs :)

**Comment by DrewAPicture** [comment]
I've split implementation into a new issue/PR pair, #1301 and #1302 respectively.

**Comment by pippinsplugins** [comment]
Looking really good so far. Love seeing the `set()` and `save()` methods.

I did just notice that the `custom` is doc'ed with the wrong data type:
```php
/**
 * Custom referral data.
 *
 * @since 1.9
 * @access public
 * @var string
 */
public $custom;
```

It's mixed. It can be a string, int, or array depending on what the integration chooses to do with it.

**Comment by pippinsplugins** [comment]
```php
/**
 * Products associated with the referral.
 *
 * @since 1.9
 * @access public
 * @var string
 */
public $products;
```
It's an array, not a string.

**Comment by pippinsplugins** [comment]
I'm also seeing a strict standards notice:

```
Strict standards: Static function AffWP_Object::sanitize_field() should not be abstract in /Users/pippinwilliamson/Sites/trunk/wp-content/plugins/affiliate-wp/includes/objects/class-affwp-object.php on line 230
```

**Comment by pippinsplugins** [comment]
Something else weird I'm seeing is that retrieving objects isn't working. All values remain default instead of being filled from the values in the DB.

**Comment by DrewAPicture** [comment]
@pippinsplugins Can you supply some sample object retrieval code so I can try to reproduce?

**Comment by pippinsplugins** [comment]
All I did was this:
```php
$a = new AffWP_Affiliate( 1 );
var_dump( $a );
```

There was definitely an affiliate with an ID of 1. I did the same thing with a referral and got the same results.

**Comment by DrewAPicture** [comment]
@pippinsplugins The objects are currently designed as effectively singletons and should be accessed (in order to preserve caching) via the standard wrappers rather than instantiating new objects to build them.
```php
$a = affwp_get_affiliate( 1 );
var_dump( $a );
```

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Merged into `release/2.6` :)

**Comment by pippinsplugins** [comment]
@sumobi @michaelbeil @ramiabraham could we get some testing on this to look for any issues? Everything is in `release/1.9`.

**Comment by pippinsplugins** [comment]
We have a small bug. These referrals were for 20% on a $10 purchase:
![screen shot 2016-06-12 at 9 12 29 pm](https://cloud.githubusercontent.com/assets/1034109/15995527/6daa0600-30e2-11e6-80b4-d706f80f959b.png)

**Comment by DrewAPicture** [comment]
Note: the referral rate bug was the result of some code getting missed when @pippinsplugins was fixing merge conflicts. Should be working as expected now.

**Comment by sumobi** [comment]
float rather than string for `earnings`?

<img width="694" alt="screen shot 2016-06-14 at 11 37 54 am" src="https://cloud.githubusercontent.com/assets/52581/16026715/80bbf0e4-3224-11e6-8b84-3760d03e381c.png">

**Comment by pippinsplugins** [comment]
Yeah, I think `earnings` should be a float.

**Comment by DrewAPicture** [comment]
Tests passed, merged #1358 which converts core objects to use namespaces 🎉 .

**Comment by pippinsplugins** [comment]
We need to add the main account email to the object, similar to how we've added the `user_id`.

**Comment by pippinsplugins** [comment]
Actually, while we're at it, we should really also add first and last name too.

**Comment by pippinsplugins** [comment]
@DrewAPicture quick reminder that we still need to add the following fields:

- email
- first_name
- last_name

**Comment by DrewAPicture** [comment]
#1440 makes it possible to lazy-load the user object with a magic `$user` property. A magic getter in `AffWP\Affiliate` also tacks on the first and last name user meta.

Includes tests.

**Comment by DrewAPicture** [comment]
#1440 also covers ensuring `$earnings` returns a float + test.

**Comment by DrewAPicture** [comment]
Tests passed. Merged #1440.

**Comment by DrewAPicture** [comment]
Tests passed, merged #1447.

**Comment by DrewAPicture** [comment]
Closing this as fixed. We can file new issues for anything else that comes up.

**Comment by pippinsplugins** [comment]
🍻

**Comment by pippinsplugins** [comment]
Found a bug!

`rate()` in the affiliate object returns the account-specific rate if it is set or the default rate in settings if no account rate is set.

This is all well and good except that it breaks how `affwp_get_affiliate_rate()` when using product rates.

Calculation rates are retrieved in this order: `Affiliate > Product > Global`.

Now, however, product rates get ignored because the affiliate rate is _never_ empty.

**Comment by pippinsplugins** [comment]
This can be resolved by checking if the affiliate has a custom rate before skipping over the product rate in `affwp_get_affiliate_rate()`:

```php
$rate = $affiliate->has_custom_rate() ? $rate : $product_rate;
```

**Comment by pippinsplugins** [comment]
Fixed in https://github.com/AffiliateWP/AffiliateWP/commit/765c304ce0d423092d8c73b289d467faac7afc35
