### ISSUE TITLE
Affiliate_WP::below_php_version_notice() should be a static method

### ISSUE THREAD

**Issue by WebFactoryLtd** [AffiliateWP/AffiliateWP#1201]
`below_php_version_notice` method in `affiliate-wp.php:246` is called statically but not declared as such and throws a notice by strict standards.

How to replicate:
* change compared version (5.3) in `affiliate-wp.php:195` to something higher than your PHP version to trigger the `admin_notices` action

**Comment by pippinsplugins** [comment]
Thanks for the heads up, we'll get it fixed!

**Comment by DrewAPicture** [comment]
Merged #1211.
