### ISSUE TITLE
SSL + fallback tracking: port number exposed

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1202]
PR: #1482

*Scenario*:

A customer has an SSL certificate active on siteA.com with fallback tracking enabled. When an affiliate URL like https://siteA.com/shop/product/ref/3 is shared, the URL shows in the admin visits screen and the affiliate dashboard visits tab like this: https://siteA.com:443/shop/product. Note that the URLs do not appear like this in the affiliate dashboard URLs tab where one can generate a URL.

When I asked about his host and SSL certificate:
> Both live and dev site are hosted with Hostpoint, the by far best WordPress hoster I have ever worked with. Including supposed great ones like WPEngine etc.

> For about a year now, they have been offering free SSLs to everyone. On literally hundreds of client sites I have never had any problems. 

The same issue is not coming up on https://siteB.com, which does not have fallback tracking enabled. 

When the customer chatted with a developer, they said the following:
> Actually the problem was the affiliate plugin uses $_POST['server_port '] to get the current page URL. 

> In this function: get_current_page_url() 

> There is a filter to get the current page URL.

> So I have used this filter and placed code in child theme to get the current page URL.

The devs used this piece of code to resolve the issue on https://siteA.com:

```php
<?php

add_filter('affwp_get_current_page_url', 'ww_change_page_url');
 
/* 
* Resolves URL issue at visitor's page 
*/

function ww_change_page_url( $page_url ){
 
global $post;
 
if ( is_front_page() ) {

    $page_url = home_url();
 
} else {
 
    $page_url = 'http';
 
    if ( isset( $_SERVER["HTTPS"] ) && $_SERVER["HTTPS"] == "on" ) {

        $page_url .= "s";

    }

    $page_url .= "://";
    $page_url .= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"]; 
}

return $page_url;

}
```

Perhaps we need to check for SSL better when fallback tracking is enabled.

**Comment by sumobi** [comment]
Here's a ticket where the customer has noticed this: https://secure.helpscout.net/conversation/185650217/30797/?folderId=205527

> However a few of them are nott displayed correctly (domain.com:443/szi) in the visits tab. I attached a screenshot to this E-Mail

**Comment by ramiabraham** [comment]
Fixed in https://github.com/AffiliateWP/AffiliateWP/pull/1482 via removal of port number in url, also added additional ssl check via `is_ssl()`

**Comment by pippinsplugins** [comment]
@ramiabraham could we please add some unit tests for this?

**Comment by ramiabraham** [comment]
_(First pass for coverage added in https://github.com/AffiliateWP/AffiliateWP/pull/1482/commits/288af46d855bdd22699a569be15c806efa6d5028)_

**Comment by pippinsplugins** [comment]
@ramiabraham fatal error in the tests: https://travis-ci.org/AffiliateWP/AffiliateWP/jobs/149001662
