### ISSUE TITLE
Integration with OptimizeMember

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1216]
PR: #1429

I think we should have an integration for OptimizeMember. It's very similar to s2Member which we already have an integration for. I believe OM forked s2.

**Comment by michaelbeil** [comment]
You are correct. I think this is a good idea given the amount of support tickets we receive for OM.

**Comment by pippinsplugins** [comment]
Am I blind or does OptimizeMember not actually exist? Is it just part of OptimizePress?

**Comment by sumobi** [comment]
@pippinsplugins It's an additional plugin for OptimizeMember (see DropBox). It's a fork of S2Member.

**Comment by pippinsplugins** [comment]
@sumobi @michaelbeil ready for testing!

I would recommend testing with Stripe as that can be done locally (does not depend on webhooks for a real test even though their setup docs would indicate it does).

**Comment by sumobi** [comment]
@pippinsplugins Can you outline some step by step instructions to test? I had no luck with my Stripe form, no referral was recorded.

1. Enabled OM integration
2. Set up Stripe in test mode + a payment form on a page
3. Purchased and no referral

![screen shot 2016-07-12 at 8 57 04 pm](https://cloud.githubusercontent.com/assets/52581/16761298/a48b4064-4873-11e6-9a7c-cd40f15824b6.png)

![screen shot 2016-07-12 at 8 57 31 pm](https://cloud.githubusercontent.com/assets/52581/16761299/a48ba0ae-4873-11e6-98e0-3b3e60114e17.png)

![screen shot 2016-07-12 at 8 57 39 pm](https://cloud.githubusercontent.com/assets/52581/16761297/a4884472-4873-11e6-930f-abdc0a40904e.png)

**Comment by sumobi** [comment]
Ok i got one to generate using the `Stripe Capability (Buy Now) Forms`

![screen shot 2016-07-12 at 9 05 57 pm](https://cloud.githubusercontent.com/assets/52581/16761499/80b5221c-4874-11e6-82bb-ad9c12487387.png)

Is that the only way to generate referrals with Stripe?

**Comment by pippinsplugins** [comment]
When it worked for me, I used the regular Stripe forms.

Now neither are working for me. Trying to track it down.

**Comment by pippinsplugins** [comment]
Well I can't make it work at all now. The payment notification simply is not processed. I've added additional debugging steps and they show very clearly why it's not working, I just can't find why it's not working yet.

@michaelbeil can you test it to see what behavior you get?

**Comment by sumobi** [comment]
Dang

**Comment by michaelbeil** [comment]
I cannot even seem to set up a registration form for testing.

**Comment by pippinsplugins** [comment]
@michaelbeil what part is failing for you?

**Comment by michaelbeil** [comment]
All the parts? 😄

**Comment by michaelbeil** [comment]
Getting a `Network communication failure with Stripe; please try again.` notice.

**Comment by sumobi** [comment]
Tested again, can generate a referral with:

1. Stripe Capability (Buy Now) Forms
2. Stripe Forms For Level Bronze Member Access (**did not** test silver, gold, platinum, level 5 - 10)

Couldn't get it working with:

1. Stripe Specific Post/Page (Buy Now) Forms

**Comment by pippinsplugins** [comment]
@sumobi looks like we needed to register sale notification URLs for post/pages too:
![screen shot 2016-08-31 at 2 22 51 pm](https://cloud.githubusercontent.com/assets/1034109/18143183/9e7a73c2-6f86-11e6-9de4-73d36b34012b.png)

Try Post/Page buy now forms again please.

**Comment by pippinsplugins** [comment]
It's working for me now.

I've set up a testing site here: http://s14890.p27.sites.pressdns.com/optimize-press/

**Comment by michaelbeil** [comment]
I cannot get the gold member signup page to create a referral.

**Comment by pippinsplugins** [comment]
@michaelbeil did you use my existing page with the signup form or did you make your own?

**Comment by michaelbeil** [comment]
the existing page.

**Comment by pippinsplugins** [comment]
It worked for me . . trying again.

**Comment by pippinsplugins** [comment]
Hmm, not working for me either now. @michaelbeil can you make a new form and then try again?

**Comment by pippinsplugins** [comment]
It's failing because the affiliate ID is missing during notification processing:
```
2016-8-31 20:48:33 - OptimizeMember referral validation failed. Missing affiliate ID.
```

**Comment by michaelbeil** [comment]
That is odd. The affiliate id was stored in a cookie. Ideas?

**Comment by michaelbeil** [comment]
Never mind. Creating a new form.

**Comment by michaelbeil** [comment]
I am still getting the `OptimizeMember referral validation failed. Missing affiliate ID.` error. 

@pippinsplugins mentioned:
> That means it's missing from the POST notification sent by OptimizeMember

**Comment by sumobi** [comment]
Tested again with `Stripe Specific Post/Page (Buy Now) Forms` and it now works 👍

**Comment by sumobi** [comment]
@pippinsplugins where did you find the `Specific Post/Page ~ Sale Notifications` section? Not seeing it anywhere on my local set up.

**Comment by pippinsplugins** [comment]
Under the main API Notifications.

**Comment by sumobi** [comment]
Level up!

**Comment by pippinsplugins** [comment]
@michaelbeil could you test again? Maybe letting it sit for 6 days fixes it :D

**Comment by sumobi** [comment]
lol

**Comment by pippinsplugins** [comment]
I just replicated @michaelbeil's issue.

**Comment by pippinsplugins** [comment]
Looks like it's a problem with there being two payment notifications processed (at least for Stripe), one for `invoice.payment_succeeded` and one for `charge.succeeded`. The `charge.succeeded` is processed properly but `invoice.payment_succeeded` fails because a referral has already been created.

**Comment by pippinsplugins** [comment]
Ok that's a nuance of OptimizeMember and not something we can fix.

**Comment by pippinsplugins** [comment]
This is all working properly for me so I'm merging and closing. We can tweak more later is necessary.

**Comment by michaelbeil** [comment]
👍
