### ISSUE TITLE
Open Graph issue with pretty affiliate links

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1219]
Got an edge case OG meta issue that only happens with a pretty affiliate link without a trailing slash.

Example: http://yoursite.com/store/products/product-a/ref/1.

The image attached to the product page (can be a blog page too) is not scraped when entered into the dev tools here: https://developers.facebook.com/tools/debug/sharing.  

Warnings that should be fixed:

> Inferred Property: The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.
> Missing Required Property: The 'og:type' property is required, but not present.
> Inferred Property: The 'og:url' property should be explicitly provided, even if a value can be inferred from other tags. 

Whereas all of the following affiliate links work fine: 

Pretty affiliate link with a trailing slash:
- http://yoursite.com/store/products/product-a/ref/1/ 

Non-pretty affiliate link with a trailing slash:
- http://yoursite.com/store/products/product-a/?ref=1/ 

Non-pretty affiliate link without a trailing slash:
- http://yoursite.com/store/products/product-a/?ref=1 

Note that when you enter the other links into the dev tool, the following warning is present:

```
Share App ID Missing: The 'fb:app_id' property should be explicitly provided, Specify the app ID so that stories shared to Facebook will be properly attributed to the app. Alternatively, app_id can be set in url when open the share dialog.
```

The referral URL generator strips the trailing slash. Perhaps we should add this back in, or simply support pretty affiliate links that do not have a trailing slash with FB OG.

**Comment by DrewAPicture** [comment]
I played around with this a little bit over the weekend. It really stems from Facebook treating trailing-slashed URLs vs non as separate pages. Saw some discussion over on WPSEO about messing with the canonical URL and/or forcing redirects based on the lack of trailing slash (like many browsers already do). I'm not sure this is something we can tackle for 1.8 considering the lack of documentation.

**Comment by pippinsplugins** [comment]
Let's go ahead and punt for now then.

**Comment by sumobi** [comment]
For now we should simply educate via a doc about sharing URLs on Facebook. @wordmaid

**Comment by michaelbeil** [comment]
That is rather strange @DrewAPicture. Perhaps more documentation will come out on this over the next several months.

**Comment by DrewAPicture** [comment]
Closing this after some discussion as it's not a high priority and has only been reported once.
