### ISSUE TITLE
'affwp_update_affiliate' hook name conflict causes a fatal when updating an affiliate

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1222]
Looks like we have hit a naming conflict with introducing the new 'affwp_update_affiliate' action. It conflicts with the existing affwp_ . $_REQUEST['affwp_action'] dynamic hook fired on form submission for updating an affiliate. The offending form action is update_affiliate, thus affwp_update_affiliate.

The new 'affwp_update_affiliate' hook was introduced in #1073.

**Comment by DrewAPicture** [comment]
Added a PR: #1223.

**Comment by sumobi** [comment]
Looks good to me. Not sure how else we can get around that without renaming the action
