### ISSUE TITLE
Unable to sort "Unpaid Referrals" column correctly

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1224]
To replicate:

1. Go to Affiliates -> Affiliates.

2. Click on the `Unpaid Referrals` column title to try and sort the unpaid referrals.

3. Expected result: to have the referrals show in order. What it's actually doing is sorting the `Affiliate ID` column, instead of the unpaid referrals.

**Comment by DrewAPicture** [comment]
Added a PR: #1230

**Comment by DrewAPicture** [comment]
Note: #1230 also fixes similar incorrect sorting behavior for the Name column. See the PR for more on that.

**Comment by pippinsplugins** [comment]
@DrewAPicture Everything looks good here, though we could avoid the count query when ordering by visits since we keep a count in the `visits` column of the affiliates table already.

**Comment by DrewAPicture** [comment]
I've removed the extra visits logic. Good to know.

**Comment by michaelbeil** [comment]
Confirmed fix on branch `issue/1224`.
