### ISSUE TITLE
Specify a date when manually adding a new referral

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1227]
It would be nice to specify a referral's creation date when manually added. We could say something like "leave blank for today's date, or select a date". This would be great for historical referrals, where you need to go in and add a referral that occurred before a certain date.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by DrewAPicture** [comment]
Added a PR: #1364.

Adds date fields to the new- and edit-referral forms. Defaults to the current date on the new-referral form.

**New Referral**:

![New Referral](http://cl.ly/3Y0u0e0g3X1S/Screen%20Shot%202016-06-20%20at%2011.39.24%20PM.png)

![New Referral datepicker](http://cl.ly/35291E05143o/Screen%20Shot%202016-06-20%20at%2011.40.32%20PM.png)

**Edit Referral**:

![Edit Referral](http://cl.ly/432N1g440t3p/Screen%20Shot%202016-06-20%20at%2011.41.16%20PM.png)

![Edit Referral datepicker](http://cl.ly/1J1a3H1C0y12/Screen%20Shot%202016-06-20%20at%2011.42.56%20PM.png)

**Comment by sumobi** [comment]
@DrewAPicture perfect! 

> My thinking is that if they have an auto-pay addons or anything related to reporting, that changing referral dates after the fact might not be a fantastic idea.

I absolutely agree with that

**Comment by pippinsplugins** [comment]
I agree as well.

**Comment by michaelbeil** [comment]
This looks great!
