### ISSUE TITLE
Can't pass array of contexts to the get_referrals method

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1231]
Passing an array of contexts doesn't seem to work with the `get_referrals` method:
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/class-referrals-db.php#L350 

Passing a single context works great.

For example:

    $referrals = affiliate_wp()->referrals->get_referrals( array( 'context' => array( 'edd', 'woocommerce' ) ) );

Result:

    WordPress database error Unknown column 'edd' in 'where clause' for query SELECT * FROM wp_4_affiliate_wp_referrals  WHERE `context` IN(edd,woocommerce)  ORDER BY referral_id DESC LIMIT 0, 20; made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), call_user_func_array, affwp_leaderboard_show_custom_data, Affiliate_WP_Referrals_DB->get_referrals

Can anyone else replicate this?

**Comment by pippinsplugins** [comment]
This is failing because the values need to be wrapped in quotes. Right now it is `IN(edd,woocommerce)` while it should be `IN('edd','woocommerce')`.

**Comment by sumobi** [comment]
Ready for testing
