### ISSUE TITLE
Misc option to add logout link to Affiliate Area

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1234]
A request that we see often is "how can I add a logout link to the affiliate area"? 

I'd like to discuss the possibility of adding a new checkbox option in our Misc settings that does this automatically. Anyone agree or disagree?

I've updated our code snippet doc with a second example on how to add this to the pre-existing Affiliate Area links: http://docs.affiliatewp.com/article/784-add-a-logout-link-to-the-affiliate-area

**Comment by michaelbeil** [comment]
I agree 100% to add this to core as it would allow customers to easily display a logout link with the click of a checkbox.

**Comment by sumobi** [comment]
The other option for this is to include this in the Affiliate Area Tabs add-on, since that will soon control the visibility of the existing Affiliate Area tabs.

**Comment by pippinsplugins** [comment]
Nah, I think core is right.

**Comment by sumobi** [comment]
+1 for this from survey

**Comment by sumobi** [comment]
Sorry @ramiabraham, stole this off you.

@AffiliateWP/core I think we need a filter for defining the log out URL as some people might want to redirect them to a separate login page. Include filter directly in template file or create a function? leaning towards function atm.

**Comment by pippinsplugins** [comment]
I vote for a `affwp_get_logout_url()` function that calls `wp_logout_url()` with an `affwp_logout_url` filter. It should also include a filter on the redirect URL.

**Comment by michaelbeil** [comment]
This works great.  
![screen shot 2016-08-10 at 2 30 31 pm](https://cloud.githubusercontent.com/assets/4752949/17567932/036e71f6-5f07-11e6-91c2-6db52761c50e.png)

All that is needed is the aforementioned additions by @pippinsplugins and this should be set.

**Comment by sumobi** [comment]
Looks like we're good to go on this

**Comment by pippinsplugins** [comment]
Needs unit tests :)
