### ISSUE TITLE
Add get_columns() method to Affiliate_WP_Affiliate_Meta_DB

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1235]
We need to add a `get_columns()` method to the `Affiliate_WP_Affiliate_Meta_DB` class so that we can have a proper whitelist of column names. This is required in order to `get_column_by()` methods to work since https://github.com/AffiliateWP/AffiliateWP/pull/1198/files

**Comment by sumobi** [comment]
@pippinsplugins Great, that gets us past the first conditional. Just need to work out why the prepare method is preventing it from working now

This is how it is now:

    return $wpdb->get_var( $wpdb->prepare( "SELECT $column FROM $this->table_name WHERE $column_where = %s LIMIT 1;", $column_value ) );

This is how it was before (which works):

    return $wpdb->get_var( "SELECT $column FROM $this->table_name WHERE $column_where = $column_value LIMIT 1;" );

**Comment by pippinsplugins** [comment]
The issue mentioned by @sumobi above was resolved through a change in the custom slugs add-on. All good here.
