### ISSUE TITLE
"No integration enabled" and "Enter/activate license key" admin notices are visible to logged-in affiliates

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1237]
If there are no integrations enabled, or the license key has not been entered/activated, a logged-in affiliate can see these admin notices on the WordPress admin dashboard. These notices should probably only be visible to admins.

<img width="1510" alt="screen shot 2016-04-27 at 11 49 57 am" src="https://cloud.githubusercontent.com/assets/11830108/14837735/0fa4a2aa-0c6f-11e6-8e4b-811080f59198.png">

**Comment by DrewAPicture** [comment]
Added a PR: #1350

**Comment by michaelbeil** [comment]
PR looks good!

**Comment by pippinsplugins** [comment]
@DrewAPicture PR looks good minus one minor detail. The `@since` tag has the wrong version on it.

**Comment by DrewAPicture** [comment]
@pippinsplugins The code in question was added on the 0.2 tag, which is where that came from. If you have a different version you'd like me to use, I'm all eyes ;)

**Comment by pippinsplugins** [comment]
Ah! I forgot we had taged pre 1.0 versions.

Let's use 1.0 please.

**Comment by DrewAPicture** [comment]
Tests passed. Merged #1350.
