### ISSUE TITLE
Support removal of Affiliate Area tabs

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1243]
https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/issues/1

**Comment by sumobi** [comment]
First pass. Looks like we might be able to clean up the template file a bit more.

**Comment by pippinsplugins** [comment]
I'm not a huge fan of calling the same filter over and over. How about a helper function instead? Something like `affwp_should_show_tab( $tab )`? That can include a filter.

**Comment by sumobi** [comment]
Good idea

**Comment by sumobi** [comment]
@pippinsplugins check latest commit. Simplified the overall `dashboard.php` template and introduced some new helper functions. Winning.

**Comment by pippinsplugins** [comment]
@sumobi Can we move this to 1.8? Tentatively looking at a 1.8 release next week.

**Comment by sumobi** [comment]
Yep, I'll resubmit against 1.8

**Comment by sumobi** [comment]
@pippinsplugins Nice, I was not aware of the new functions in 1.8 for getting the page ID and URL of the affiliate area.

Any reason why we've added this variable? Going to remove it otherwise
https://github.com/AffiliateWP/AffiliateWP/blob/release/1.8/templates/dashboard.php#L4

**Comment by pippinsplugins** [comment]
@sumobi none that I see. Kill it.

**Comment by pippinsplugins** [comment]
@sumobi I'd like to see `affwp_affiliate_area_tab( $tab )` renamed to `affwp_affiliate_area_show_tab( $tab )` to make it easier to grok what the function does.

**Comment by DrewAPicture** [comment]
FWIW, I think the `$affiliates_page_id = affwp_get_affiliate_area_page_id();` line was leftover from before we introduced `affwp_get_affiliate_area_page_url()`. So yeah, kill it :+1:

**Comment by sumobi** [comment]
Ok think we're good to go on this

**Comment by pippinsplugins** [comment]
Looks good to me.
