### ISSUE TITLE
Add 'campaign' to shortcode attributes in Affiliate_WP_Shortcodes::conversion_script

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#1246]
Adding 'campaign' as a shortcode attribute in `Affiliate_WP_Shortcodes::conversion_script` would allow customers to define additional traffic sources when the conversion script shortcode is used.

**Comment by pippinsplugins** [comment]
Turns out this is already supported. I did find a couple of tweaks to make, however, so PR: #1556

**Comment by michaelbeil** [comment]
Looks good.
