### ISSUE TITLE
Show message to admin viewing the affiliate area as a non-affiliate

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1251]
A common support request we receive is "I can't see the Affiliate Area". After general troubleshooting we eventually discover that the customer simply isn't viewing the affiliate area as an actual affiliate. This seems very obvious to us but it's something we should try and improve.

I think a simple solution would be to show a message on the affiliate area page for a logged in admin. Something like "If you cannot see the Affiliate Area, please log in as an affiliate, or add your own account as an affiliate from the Affiliates -> Affiliates -> Add new affiliate page".

**Comment by pippinsplugins** [comment]
Another way around this would be to auto register the admin that activates the plugin as an affiliate, as proposed in #425

**Comment by sumobi** [comment]
@pippinsplugins It's a tough one. I like that idea though I don't think we should do anything automatically, at least not without giving them the "why" first. Some site owners won't appreciate their affiliate IDs getting "out of order" (incrementing by 1), or wondering why their user account is also an affiliate. At least if we explain why, they can choose how they fix it; either adding themselves as an affiliate, or logging in as an affiliate. Thoughts?

**Comment by pippinsplugins** [comment]
I think what we have now is correct for most cases. I vote for adding a message to logged in affiliates on the affiliate area.

**Comment by sumobi** [comment]
I don't quite understand, why would we add a message for logged-in affiliates? If they are logged in, they will already see the Affiliate Area.

**Comment by pippinsplugins** [comment]
I meant logged-in admins.

**Comment by michaelbeil** [comment]
I think adding a message to the affiliate area for a logged-in admin would be top notch over auto registering admins as affiliates. We could avoid some confusion with this implementation.

**Comment by sumobi** [comment]
👍

**Comment by DrewAPicture** [comment]
What would you like the message to say? How should the page be displayed for non-affiliate admins?

**Comment by michaelbeil** [comment]
For site admins only, it could be:

"To see the Affiliate Area, please log in as an affiliate, or add your own account as an affiliate here." 

`[here] => (Affiliates -> Affiliates -> Add new affiliate page admin URL)`

**Comment by sumobi** [comment]
A slight tweak on the above, I'm not a fan of using words like "here". We should just link the text that spells out the action:

To see the Affiliate Area, log in as an existing affiliate, or [add your account as an affiliate](http://thelink.com).

**Comment by michaelbeil** [comment]
:+1:

**Comment by ramiabraham** [comment]
PR looks good here.

**Comment by pippinsplugins** [comment]
@sumobi happy with this too?
