### ISSUE TITLE
User with all capabilities cannot update settings page.

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1252]
PR: #1553

Even if you assign all capabilities available in AffiliateWP to a user, when that user tries to update the settings page they get the `Cheatin’ uh?` screen.

![screen shot 2016-05-02 at 11 13 45 am](https://cloud.githubusercontent.com/assets/52581/14944923/27dec300-1057-11e6-84b2-56a4a3aa817a.png)

**Comment by DrewAPicture** [comment]
@sumobi Can you provide steps to reproduce? The way this is written currently is that *nobody* can update the settings page, because all users currently have some form of capability ;)

**Comment by sumobi** [comment]
An admin can update the settings page. 

Steps to reproduce:

1. Add all our current 7 AffiliateWP capabilities to a user
2. As that user, go to the Affiliates -> Settings page and try and save the settings

The capabilities grant the user to see the settings page, but does not allow them to save.

**Comment by michaelbeil** [comment]
This seems to be due to the user not having the `manage_options` capability. 

User should have the following capabilities: 
`export_affiliate_data`
`manage_affiliate_options`
`manage_affiliates`
`manage_referrals`
`manage_options`
`manage_visits`
`manage_creatives` 
`read`
`view_affiliate_reports`

**Comment by sumobi** [comment]
Giving a user `manage_options` is granting them administrator capabilities. Not something we would want to do since they could do a whole lot more on the site.

**Comment by michaelbeil** [comment]
Ah yes, so perhaps we just need to extend `manage_affiliate_options` on save.

**Comment by sumobi** [comment]
Here's one workaround:
https://gist.github.com/sumobi/0e2639ff4b7eb6e723b4360b1016de44

We could simply hook into `option_page_capability_affwp_settings` and change the capability to `manage_affiliate_options`. 

Defaults to `manage_options`:
https://developer.wordpress.org/reference/hooks/option_page_capability_option_page/

**Comment by pippinsplugins** [comment]
@sumobi ready for testing.

**Comment by DrewAPicture** [comment]
@pippinsplugins Looks good. Needs unit tests :)

**Comment by pippinsplugins** [comment]
@DrewAPicture I have no clue how to add unit tests for an options' page save routine. Care to educate me?

**Comment by DrewAPicture** [comment]
@pippinsplugins Looks like we already have a test for the capability. I couldn't find a good (see: any) way to test the cap on options.php. Hmm, disappointing. No unit tests for us.

**Comment by pippinsplugins** [comment]
Damn, I was hoping for magic.

**Comment by sumobi** [comment]
@pippinsplugins works great 👍
