### ISSUE TITLE
Select characters in translatable strings should be expressed as entities

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1255]
On or about WordPress 3.4, core [started using](https://core.trac.wordpress.org/changeset/19795) entities in translatable strings for some characters, including single and double quotes, apostrophes, en/em dashes, etc. This was due to some locales needing the ability to translate the aforementioned characters inside of `wp_texturize()`.

One common case for this change would be anywhere `affiliate\'s` falls in translatable strings currently. This would become `affiliate&#8217;s`, for instance. Display would be unchanged in any locales not choosing to translate characters in this way.

**Comment by DrewAPicture** [comment]
Added a PR: #1269

**Comment by pippinsplugins** [comment]
Looks good!
