### ISSUE TITLE
Reports Overview graphs

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#1256]
Presently, the following data is planned to be added into the `Affiliate_WP_Graph` instance on `affiliate-wp-reports?tab=overview`:

- Unpaid Referrals
- Pending Referrals
- Rejected Referrals
- Paid Referrals
- Affiliate Registrations
- Visits
- Campaigns
- Creatives (when we hit https://github.com/AffiliateWP/AffiliateWP/issues/1210)
- Conversion Rates (may be redundant, since conversions are implicit in referrals)
- Contexts
- References

with visibility filterable on each by some ui component (show/hide checkboxes/buttons, most likely).

_Questions_:

- Should any data above be removed?
- Any additional data to add?
- What are some good examples of data correlation we might explore (either in 1.9, or later) that may help customers define positive trends, and other performance information? Some things that come to mind are _milestones_:
    - "New (daily, weekly, monthly, etc) record for affiliate registrations"
    - "This was your best-performing week ever for (product name) referrals/visits"
    - "New highest referral amount record (amount, link to referral)"

**Comment by michaelbeil** [comment]
Should we have a way to hide the legend on the graph?

**Comment by ramiabraham** [comment]
@michaelbeil I like this idea. Even if it's a very minor component, because zooming and panning is a feature from #1076 on, there will likely be some cases in which the legend obstructs the view of some plot points.

**Comment by worldtravlr** [comment]
Love the milestones idea and cool about creatives being added to the graph!  Maybe A/B testing could be introduced for creative in the future and then that could be graphed out as well :-)

**Comment by ramiabraham** [comment]
Closing in favor of #1525
