### ISSUE TITLE
Make tests in test-affiliate-functions.php more efficient

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1258]

**Comment by DrewAPicture** [comment]
@pippinsplugins Might taking a look here?

**Comment by pippinsplugins** [comment]
@DrewAPicture Awesome improvement! Now just need the tests to pass still :) Travis is showing a lot of undefined indexes: https://travis-ci.org/AffiliateWP/AffiliateWP/jobs/127686773

**Comment by DrewAPicture** [comment]
@pippinsplugins After some experimentation, I'm still unable to get this to work consistently. Let's try again in 1.9.

**Comment by DrewAPicture** [comment]
Closing in favor of #1520.
