### ISSUE TITLE
If `Affiliate URLs` tab is removed, clicking Affiliate Area results in blank tab

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1266]
Now that Affiliate Area Tabs allows you to remove the default Affiliate Area tabs there's a slight issue:

If the `Affiliate URLs` tab is removed, and you click to go to the Affiliate Area, you'll see no content under the tabs. This is because the `urls` tab was set to be the active tab when no query string is used.

https://github.com/AffiliateWP/AffiliateWP/blob/master/templates/dashboard.php#L2

![screen shot 2016-05-06 at 3 34 25 pm](https://cloud.githubusercontent.com/assets/52581/15063657/0fe9da04-13a0-11e6-940e-33ca1a6be95b.png)

Somehow we need to make `$active_tab` fallback to the first tab being shown, since it might not always be `urls`.

The other option is to just write up a doc and tell them how to update the template file if they remove the Affiliate URLs tab.

**Comment by pippinsplugins** [comment]
Let's fallback to the next active tab.

**Comment by DrewAPicture** [comment]
Added a PR: #1296

**Comment by DrewAPicture** [comment]
Added a PR for the Affiliate Area Tabs add-on: [Affiliate-Area-Tabs/#11](https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/issues/11)

**Comment by pippinsplugins** [comment]
Looks good!
