### ISSUE TITLE
WP-CLI commands in Core

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1267]

**Comment by pippinsplugins** [comment]
Some of the commands we could have:

- Affiliates
 - get affiliate
 - create affiliate
 - update affiliate
 - delete affiliate
- Referrals
 - add referral
 - get referral
 - update referral
 - delete referral
- Visits
 - get visits
 - add visit
 - update visit
 - delete visit
- Reports
 - unpaid earnings
 - paid earnings
 - revoked earnings
 - pending earnings
 - top affiliates
 - earnings from date X to date Y
- Payouts
 - generate payout file
 - process Stripe payout (command registered in add-on)
 - process PayPal payout (command registered in add-on)
- Export/Import
 - export referrals
 - export affiliates
 - import affiliates
 - import referrals

I don't expect we'll get all of these in for the first version but eventually it'd be great to have near 100% coverage of functionality.

**Comment by pippinsplugins** [comment]
Looking good so far!

**Comment by pippinsplugins** [comment]
Yes please. Let's introduce an `update()` method to go along with it.

**Comment by DrewAPicture** [comment]
@pippinsplugins Went with `update_visit()`.

**Comment by DrewAPicture** [comment]
@pippinsplugins This is ready for review. #1270 implements a top level `affwp` command, two utility sub-commands, and CRUD sub-commands for the four core objects. Oh, and it's namespaced ;)

**Comment by pippinsplugins** [comment]
@DrewAPicture PR looks good! I will do further testing tomorrow.

**Comment by pippinsplugins** [comment]
@DrewAPicture in preparing to test this, I've realized a problem and am not sure how to get around it.

My test site is a multisite network with AffiliateWP activated on just some sites. This means that the `affwp` command is not registered unless it is network activated. That's not too big of a problem, so I went ahead and network activated it. Now I'm posed with a new issue: how do I define which site's DB to pull from?

I guess this is really a WP CLI issue inherently, not so much AffiliateWP's.

Do you know of any way to get around it?

**Comment by pippinsplugins** [comment]
Nevermind! I just learned about the `--url` parameter.

**Comment by pippinsplugins** [comment]
I'm slowly working through all commands and will list items as I find them.

First with the `affiliate` command. The `list` option should display all fields for the affiliate. Right now it is only `ID`, `user_login`, `earnings`, `referrals`, and `status`. We need to include payment email, name, visit count, and registration date.

**Comment by pippinsplugins** [comment]
With the `list` option, can we either make `ID` supported as a `--<field>=<value>` or show it as `affiliate_id` instead? Showing `ID` makes it appear that using ID would work, but it doesn't.
![screen shot 2016-06-22 at 9 43 40 am](https://cloud.githubusercontent.com/assets/1034109/16271028/fc3bcc28-385d-11e6-9962-437c703cdd51.png)

**Comment by pippinsplugins** [comment]
Passing `--format=ids` to `list` triggers a fatal error:

Catchable fatal error: Object of class AffWP\Affiliate could not be converted to string in phar:///usr/local/bin/wp/php/WP_CLI/Formatter.php on line 127

**Comment by pippinsplugins** [comment]
Regarding my [comment above](https://github.com/AffiliateWP/AffiliateWP/issues/1267#issuecomment-227766267) about the fields displayed, I just realized the other fields are optional. I'd like to make them all shown by default. It's more likely that someone will want to have all fields by default but still have support for just some fields, just like most queries in WordPress.

**Comment by pippinsplugins** [comment]
`wp affwp affiliate create test --payment_email=test@tester.com --rate=30 --status=active` triggers an undefined offset:

Notice: Undefined offset: 4 in phar:///usr/local/bin/wp/php/WP_CLI/DocParser.php on line 124

**Comment by DrewAPicture** [comment]
@pippinsplugins What version of wp-cli are you running?

**Comment by pippinsplugins** [comment]
Latest, 0.23.1

**Comment by DrewAPicture** [comment]
@pippinsplugins OK, following up here, mid-thread.

> First with the `affiliate` command. The list option should display all fields for the affiliate. Right now it is only `ID`, `user_login`, `earnings`, `referrals`, and `status`. We need to include `payment email`, `name`, `visit count`, and `registration date`.

and

> Regarding my comment above about the fields displayed, I just realized the other fields are optional. I'd like to make them all shown by default. It's more likely that someone will want to have all fields by default but still have support for just some fields, just like most queries in WordPress.

I'll start working on both of these for !#allthethings

> With the list option, can we either make ID supported as a `--<field>=<value>` or show it as `affiliate_id` instead? Showing `ID` makes it appear that using `ID` would work, but it doesn't.

`--ID=#` should work now for all four.

> Passing `--format=ids` to list triggers a fatal error:

This should work now for listing all four. No fatal even.

> `wp affwp affiliate create test --payment_email=test@tester.com --rate=30 --status=active` triggers an undefined offset:

I fixed a typo in the command docs, can you retest to see if you still get that notice?

**Comment by DrewAPicture** [comment]
@pippinsplugins : Per your “I want all the fields” comment(s), that’s doable with some things, but kinda ¯\_(ツ)_/¯ with others. IMO, some information is more relevant to general use. For instance:

* **Affiliates:** It’s inherently more informative to list the `user_login` than the `user_id`. Easy enough to accomplish for display.
* **Creatives:** We can show all fields.
* **Referrals:** I’ve exposed all of the fields displayed in the admin currently. `currency`, `custom`, `campaign`, and `visit_id` are still optional. Just like `user_login`, `affiliate_name` is inherently more informative than `affiliate_id`. Also worth noting that we're formatting `amount` on display so also listing currency is kind of moot.
* **Visits:** I’ve additionally exposed `affiliate_name`, `referral_id`, `IP` and `converted`, but left `campaign` and `affiliate_id` as optional – again, mimicking what we’re displaying in the admin currently. `affiliate_name` is probably more informative than `affiliate_id`.

**Comment by pippinsplugins** [comment]
Creatives: I'm fine not showing all fields for this one.

**Comment by DrewAPicture** [comment]
@pippinsplugins I went ahead and made the `description` and `text` fields optional for listing creatives. I've addressed all of your other feedback, fixed a broken test, and aliased `WP_CLI\Utils` to make the `get_flag_value()` calls slightly shorter.

**Comment by pippinsplugins** [comment]
Looks like the `details` command has not been finished yet. Just noting it to make sure it's not forgotten:
```
Charless-iMac:edd pippin$ wp affwp details
AffiliateWP version: 1
```

**Comment by pippinsplugins** [comment]
@DrewAPicture The `list` command is giving me an `Invalid field: ID` error for all command types.
```
Charless-iMac:edd pippin$ wp affwp creative list
Error: Invalid field: ID.
Charless-iMac:edd pippin$ wp affwp affiliate list
Error: Invalid field: ID.
Charless-iMac:edd pippin$ wp affwp affiliate list --status=active
Error: Invalid field: ID.
```

**Comment by DrewAPicture** [comment]
@pippinsplugins Listing is fixed in the latest commit. Had to do with removing the non-magic-magic `ID` properties previously. I'll work on the `details` command.

**Comment by pippinsplugins** [comment]
@DrewAPicture working now.

Only thing I see missing now is the name of affiliates in the affiliate command. It shows in the `referral` command but not `affiliate`.

**Comment by DrewAPicture** [comment]
`name` support was added for `wp affwp affiliate list` in 982ac82.

**Comment by DrewAPicture** [comment]
9940a8a fleshed out the `wp affwp details` command:

![details command](http://cl.ly/0P1N14460r3O/Screen%20Shot%202016-07-05%20at%201.58.41%20PM.png)

**Comment by pippinsplugins** [comment]
@DrewAPicture the `details` command doesn't seem to be working for me. It shows some settings but most are always blank. 
![screen shot 2016-07-05 at 4 57 58 pm](https://cloud.githubusercontent.com/assets/1034109/16601351/acae2cfe-42d1-11e6-92d4-f6305d1ea022.png)

This is in a multisite instance but it doesn't seem to matter which URL I specify.

**Comment by DrewAPicture** [comment]
@pippinsplugins Hmm, that's really weird, cause we aren't doing anything special, just pulling directly from settings. Here's my output specifying a site:

![sub-site output](http://cl.ly/2703393n3N0x/Screen%20Shot%202016-07-05%20at%204.06.58%20PM.png)

**Comment by DrewAPicture** [comment]
Also worth noting that several of those have fallbacks so at the very least it should be showing the fallbacks. Could you possibly try also passing `--debug` to the call and pasting the log?

**Comment by pippinsplugins** [comment]
This is all working fine for me now. Going to chalk it up to ghosts in the machine.

**Comment by pippinsplugins** [comment]
I'm going to merge this into `release/1.9` then we can continue testing and making minor adjustments.

@ramiabraham @sumobi could you both give the commands a test before we close this out? See `wp affwp` for a list of commands.

**Comment by pippinsplugins** [comment]
Actually here's a command that doesn't seem to work right: ` wp affwp affiliate update 1 --status=inactive`

The status never changes.

**Comment by pippinsplugins** [comment]
Looks like it's actually due to `affwp_update_affiliate()` not supporting `status`.

**Comment by DrewAPicture** [comment]
@pippinsplugins 4182868 adds status support to `affwp_update_affiliate()`

**Comment by DrewAPicture** [comment]
#1433 Proposes a command to dump out the contents of the debug log.

**Comment by TimothyBJacobs** [comment]
Since the DB layer expects slashed data, the insert commands are going to need to manually add slashes.

**Comment by DrewAPicture** [comment]
@TimothyBJacobs I don't think the DB layer necessarily _expects_ slashed data so much as it handles unslashing if it _is_ slashed, which I consider to be mutually exclusive concepts.

**Comment by TimothyBJacobs** [comment]
They aren't really mutually exclusive, because there is no way to detect if data is slashed. See https://github.com/wp-cli/wp-cli/issues/3152 in the main CLI repo.

**Comment by pippinsplugins** [comment]
@DrewAPicture anything left on here?

**Comment by DrewAPicture** [comment]
Nope. New issues for new features/fixes.

**Comment by pippinsplugins** [comment]
:)
