### ISSUE TITLE
Add Disable Affiliate Email option to Edit User screen

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1271]
For consistency, I think it would be great to include the **Disable Affiliate Email** option on the Edit User screen under the AffiliateWP section - currently it only exists on the Add New User screen.

<img width="676" alt="screen shot 2016-05-07 at 11 17 08 am" src="https://cloud.githubusercontent.com/assets/11830108/15088278/9964a4bc-1445-11e6-9730-0d5c1b29becb.png">

**Comment by pippinsplugins** [comment]
@wordmaid For when registering an existing user as an affiliate?

**Comment by wordmaid** [comment]
@pippinsplugins yep!

**Comment by DrewAPicture** [comment]
I think we should map out exactly what the flow here would be. For instance, would we still hide this if emails are disabled as we do on the new user form? This is specifically for the purposes of adding existing users as affiliates, correct?

**Comment by wordmaid** [comment]
Yes, I think it should still be hidden if all emails are disabled, and yes this is for the purpose of adding existing users as affiliates. This will just give the admin the option to not send an existing user an email notifying them they have been accepted as an affiliate.

**Comment by DrewAPicture** [comment]
OK. In the interest of time (and because I've been a slacker) I'll start prepping this for 1.9.5. Just want to make sure the user data is saving and retrieving correctly in alltheplaces.

**Comment by wordmaid** [comment]
Sweet! It's not a major issue by any means, but rather a UX consistency thang.

**Comment by DrewAPicture** [comment]
Added a PR: #1785

**Comment by pippinsplugins** [comment]
I don't think the option should show unless the status of the affiliate is anything other than `active` or `inactive`. Doesn't make sense to show it for active or inactive affiliates.
![screen shot 2016-11-02 at 9 23 18 pm](https://cloud.githubusercontent.com/assets/1034109/19954076/c6a04726-a142-11e6-8cc1-d567ab57a25a.png)

**Comment by DrewAPicture** [comment]
Yeah, thought about that. "Hide it" it is.

**Comment by DrewAPicture** [comment]
OK, hidden for Active and Inactive affiliates.
