### ISSUE TITLE
affwp_version option name isn't updated when updating AffiliateWP

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1272]
The `affwp_version` option name (as far as I can see) does not update when a user updates their existing copy of AffiliateWP. 

It only updates when:

1. There's an upgrade routine (for v1.8 there wasn't one)
2. When AffiliateWP is installed for the first time
3. When AffiliateWP is deactivated, and then activated again

Because of this, customers will not see the checkboxes in Affiliate Area Tabs to remove the existing tabs, unless they deactivate and reactivate AffiliateWP.

I think we should update the `affwp_version` option name when a customer upgrades from one version to the next, regardless of if there is an upgrade routine.

**Comment by pippinsplugins** [comment]
Good catch!

**Comment by DrewAPicture** [comment]
Added a PR: #1294

**Comment by DrewAPicture** [comment]
@pippinsplugins Added a new commit to the PR that uses `version_compare()` with `<>` as an operator. Also supplies an empty fallback value on the `get_option()` call. Waiting for tests to pass.

**Comment by pippinsplugins** [comment]
Looks good to me, merge once tests pass please.

**Comment by DrewAPicture** [comment]
Merged #1294
