### ISSUE TITLE
WC product category pagination links revert to shop pagination links in some cases

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1277]
Reported in https://secure.helpscout.net/conversation/201751509/33988/?folderId=835878

Looks like we introduced a bug with WooCommerce product pagination when we forced shop pagination links to remove pretty referral URLs in 7f8530f76 for 1.8.

PR coming up.

**Comment by DrewAPicture** [comment]
Added a PR: #1278

**Comment by pippinsplugins** [comment]
PR looks good, let's merge once unit tests pass.
