### ISSUE TITLE
Affiliate visit counts aren't decreased when visits are deleted

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1283]
Affiliate visit counts aren't being properly decreased when visits are deleted because we're passing the `$visit_id` instead of the `affiliate_id` to `affwp_decrease_affiliate_visit_count()`.

It's apparently been around since `affwp_delete_visit()` was introduced in 4ad3a3a3 for v1.2.

PR and tests coming up.

**Comment by pippinsplugins** [comment]
Whoops!

**Comment by DrewAPicture** [comment]
Added a PR: #1284
