### ISSUE TITLE
Bump WordPress minimum compatibility in tests to 4.4 💥

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1285]
This is in preparation for merging REST endpoints in 1.9, which require the infrastructure merged in WP 4.4. :)

**Comment by DrewAPicture** [comment]
Added a PR: #1286

**Comment by DrewAPicture** [comment]
Merged #1286

**Comment by pippinsplugins** [comment]
Let's make sure that we add an admin notice for sites running less than 4.4.

**Comment by DrewAPicture** [comment]
@pippinsplugins Yeah, I've been thinking about approach a little bit. I think we'd actually do well to start showing an admin notice a few minor updates before the 1.9 target date to sort of give customers advance notice.

There's also nothing saying that we couldn't do a soft-launch of sorts – make 1.9 still work down to 3.9 or whatever but just not load the REST stuff, maybe with more assertive warnings about the minimum compatibility up until 1.9.3 or whatever. Lots of options.

In the end it mostly matters what kind of experience we're giving our customers and how we can make it as painless as possible :)

**Comment by pippinsplugins** [comment]
Let's soft-launch it by just disabling the REST API if not on 4.4.
