### ISSUE TITLE
Fix WC shop pagination links for tags, searches, and any other possible cases

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1291]
Related: #955, #1277, #1290

When we "fixed" stripping pretty referral URLs in WooCommerce shop pagination for #955, we inadvertently exposed more bugs in other places where the shop paginates, such as with product categories (#1277), tag categories (#1289), and also searches ([HS#33988](www.goldendentalsolutions.com)).

I thought it best to bring all reported issues together into a single issue for tracking, so nothing gets missed and everything gets tested.

**Comment by DrewAPicture** [comment]
Added a PR: #1292

**Comment by DrewAPicture** [comment]
Switched to checking `is_product_taxonomy()` for future-compat with any other taxonomies WooCommerce might add. Also skipped rewriting pagination links for searches.

**Comment by michaelbeil** [comment]
Makes perfect sense @drewapicture.
