### ISSUE TITLE
Please add Ukrainian Hryvnia to the list of currencies

### ISSUE THREAD

**Issue by alexfilatov** [AffiliateWP/AffiliateWP#1298]
Name: `Ukrainian Hryvnia`
Code: `UAH`
Symbol: `₴`
Wiki: https://en.wikipedia.org/wiki/Ukrainian_hryvnia

Thank you!

**Comment by michaelbeil** [comment]
That is a great idea @alexfilatov. 

Would you mind sending a PR to us here? https://github.com/AffiliateWP/AffiliateWP/compare/master...alexfilatov:alexfilatov-patch-uah

**Comment by alexfilatov** [comment]
done! thanks a lot!

**Comment by michaelbeil** [comment]
One last thing @alexfilatov, can you change `₴` to the HTML entity `&#8372;`?

https://en.wikipedia.org/wiki/Hryvnia_sign#Description

**Comment by michaelbeil** [comment]
Thanks @alexfilatov!
