### ISSUE TITLE
Add Screen Options to Adjust Admin List Table Column Views

### ISSUE THREAD

**Issue by lukemcdonald** [affiliatewp/AffiliateWP#130]
In the admin list table views (e.g. Affiliates page), there are multiple data columns (Name, ID, Earnings, Rate, etc.). Typically, there are screen options to enable/disable columns from showing in the table. These options are provided via the Screen Options tab.

I noticed there are not any options to disable columns, in particular, on the Affiliates page. For me, I'm likely just going to be interested in name, paid referrals, visits, and maybe earnings.

Somewhat related, because of number of columns, the table view starts to "break" at about 1180px do to the action links; it's worse if you haven't accepted an application because there are more link options. I wok on a 13" Macbook air, so it's noticeable more often than when I'm on my 20" iMac.

I have a few other thoughts on this page, but I'll open different tickets with those ideas.

![admin-affiliates-table-layout](https://cloud.githubusercontent.com/assets/299173/2627365/299152f0-be04-11e3-905d-14a45aab0a45.png)

**Comment by pippinsplugins** [comment]
Looks like we've finished this in 1.7 but forgot to update here.
