### ISSUE TITLE
Implement Core objects

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1301]
This is the integration/implementation for #1184.

**Comment by DrewAPicture** [comment]
I think we're ready to go here. As discussed with Pippin on a walkthrough call last week this basically introduces:

* Dependable caching wrappers for the four core objects: affiliates, referrals, creatives, and visits: `AffWP_Affiliate`, `AffWP_Referral`, `AffWP_Creative`, and `AffWP_Visit` routed through their respective `affwp_get_*()` counterparts
* Introduces several new methods and capabilities to retrieving said objects or related properties, including a new `ID` property alias, e.g. no more typing `$referral->referral_id`, just `$referral->ID` :-p
* Puts us well on our way toward implementing REST endpoints (!)

Next steps: We should first merge #1184 to introduce the actual object code, and then this one to introduce the implementation.

**Comment by pippinsplugins** [comment]
This is merged into `release/1.9`.

I'm going to close this but leave #1184 open for a bit longer in case any problems are discovered. Any further discussion needed can happen on #1184
