### ISSUE TITLE
Remove PHP7 from the failures list for Travis

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1303]
We should not allow PHP7 tests to fail.

Also, we've specified testing against WordPress trunk for PHP7. Except Travis trips up on "trunk" because our plugin tests were scaffolded with an older version of wp-cli that didn't support trunk or nightly testing at the time. So the PR updates install-wp-tests.sh as well.

**Comment by DrewAPicture** [comment]
Added a PR: #1304

**Comment by pippinsplugins** [comment]
Looks good, thanks!
