### ISSUE TITLE
Add $active_tab to affwp_affiliate_dashboard_bottom hook

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1306]
We should pass `$active_tab` to the `affwp_affiliate_dashboard_bottom` action hook so it makes it very easy to prevent the content of the new tab from showing on any other tab.

One _could_ simply use  `affwp_get_active_affiliate_area_tab()` in their code, but I would argue that since we already pass it to the `affwp_affiliate_dashboard_tabs` hook, and the `get_template_part` call we should do the same for `affwp_affiliate_dashboard_bottom`.

**Comment by sumobi** [comment]
While we're at it, how about we pass $active_tab to the `affwp_affiliate_dashboard_top` and `affwp_affiliate_dashboard_notices` hooks? This would allow for some more interesting customizations, based on the currently active tab.

**Comment by michaelbeil** [comment]
I was just gonna suggest that we also pass `$active_tab` to `affwp_affiliate_dashboard_top`. All seems great and it makes sense to add this to `affwp_affiliate_dashboard_notices` as well.

**Comment by DrewAPicture** [comment]
In the PR, I've added `$active_tab` to the other two hooks, and added hook docs for all three including changelog entries for the new parameters.

**Comment by michaelbeil** [comment]
Nice addition @DrewAPicture.

**Comment by DrewAPicture** [comment]
Merged #1307
