### ISSUE TITLE
EDD: edd_sl_disable_on_upgrades

### ISSUE THREAD

**Issue by flowdee** [AffiliateWP/AffiliateWP#1308]
PR: #1425

Would be very helpful to get a new checkbox on the integration settings which allows you to disable affiliate commissions when a customer processes upgrades via EDD Software Licensing

**Comment by pippinsplugins** [comment]
That is a great idea!

**Comment by flowdee** [comment]
And really necessary in my opinion: Today again 10 EUR commission for a license upgrade after I supported the customer, and not the affiliate ;-)

**Comment by pippinsplugins** [comment]
Ready for testing!

**Comment by pippinsplugins** [comment]
Works great. Merging.

**Comment by flowdee** [comment]
amazing, thanks @pippinsplugins ! Sorry I haven't found time to test it 😢
