### ISSUE TITLE
Bring jquery.flot.resize.js up to date

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1309]
There is a newer version of the `jquery.flot.resize.js` plugin available that fixes an issue we've seen a few times that results in `Uncaught TypeError: Cannot set property 'w' of undefined`.

**Comment by michaelbeil** [comment]
All looks good here. Graph shows as expected with no errors.

**Comment by ramiabraham** [comment]
Looks good here up to latest at https://github.com/AffiliateWP/AffiliateWP/commit/5dce5e05d6adf8f30a8312fd2cad63f40db5fc86. Also testing successfully against #1076 flot graph related enhancements in progress for 1.9.

**Comment by pippinsplugins** [comment]
Merging.
