### ISSUE TITLE
Referrals: Add batch processor

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1311]
**Issue**:

Let's say there is a site that gets several thousand referrals per day. If an affiliate were to request a payout, and the referrals are being paid manually, the site admin would need to click `mark as paid` for all referrals of that specific affiliate. Of course, one can edit the "screen option" on the referrals page, and edit "Number of referrals per page" to 999, and select all and mark 999 referrals as paid. However, an error is thrown when attempting to mark all 999 referrals as paid, because the URL query becomes so long. About 500 referrals can be marked as paid at the same time before the process times out.

**Solution**:

Let's add batch processing for referrals of a specific affiliate and also for all referrals.

**Comment by pippinsplugins** [comment]
I'd love to see the batch processor from EDD brought over. See https://github.com/easydigitaldownloads/easy-digital-downloads/issues/2999 for some of the initial work that was done on it, along with the import version https://github.com/easydigitaldownloads/easy-Digital-Downloads/issues/3620.

**Comment by DrewAPicture** [comment]
Closing in favor of #1046, batch processor was added in #1707.
