### ISSUE TITLE
New status_count() method for Referrals DB layer

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1318]
PR: #1484 

In the Tiered Affiliate Rates add-on issue/6 I had to add a new method for retrieving the number of *paid* referrals for a given time period. We might do well to make a `status_count()` method that can check against a whitelist of statuses. `unpaid_count()` would be converted to a wrapper, and it might come in handy later for reports, etc.

**Comment by DrewAPicture** [comment]
Added a PR including tests: #1484

**Comment by pippinsplugins** [comment]
PR looks good to me.

**Comment by DrewAPicture** [comment]
Tests passed, merged #1484.
