### ISSUE TITLE
Extendable core drag-and-drop functionality

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#1321]
We're starting to get drag-and-drop functionality into more add-ons, as well as some interest for a core addition:
- https://github.com/AffiliateWP/AffiliateWP/issues/343
- https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/issues/8
- (initially suggested, later dropped) https://github.com/AffiliateWP/affiliatewp-tiered-affiliate-rates/issues/16
- Am I missing any?

This could be a great opportunity to get something into core, and keep things _dry_, and may be a good fit for inclusion into https://github.com/AffiliateWP/AffiliateWP/issues/1288

---
#1288 in general is going to be a significant re-working of many components. `1.9` is already a full house, so this may be better for `1.9.x` or even `2.0`.

**Comment by pippinsplugins** [comment]
Those are the only three I can think of right now.
