### ISSUE TITLE
Decimal counts are not showing properly with affwp_get_decimal_count

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1322]
We introduced `affwp_get_decimal_count` in https://github.com/AffiliateWP/AffiliateWP/commit/dcb774f2bfa9bbeb7c8cdd3fe3372f4bd1507969, but there seems to be an issue with displaying two decimal places with US $ as we currently only show one from the stats tab: 
![screen-shot-2016-05-29-at-1 29 46-pm](https://cloud.githubusercontent.com/assets/4752949/15692688/7c725c82-2755-11e6-8f5e-50c52e322367.png)

**Comment by DrewAPicture** [comment]
Added a PR: #1323

**Comment by michaelbeil** [comment]
The fix works well.

**Comment by pippinsplugins** [comment]
Once unit tests are adjusted, it can be merged in.
