### ISSUE TITLE
Add a {campaign_name} email template tag

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1325]
In the event that an affiliate wants to know what campaign brought in a referring purchase, we should add a {campaign_name} email template tag so that site admins can add this tag to the referral notification email that is sent to the referring affiliate.

**Comment by pippinsplugins** [comment]
I like this idea.

**Comment by worldtravlr** [comment]
Awesome!  Thanks @michaelbeil!

**Comment by chimbaweb** [comment]
Totally agree. This would be a very helpful feature so affiliate can focus more on what really drives sales.

I would also like the idea of using this tag within GravityForm email notifications ( or even using the email ID of the affiliate ) so the affiliate could get in touch with the customer or take some actions or get notified about order data etc.

This way, you dont need to develop everything yourself, but you could actually use the whole GravityForm notification system to realize that.

**Comment by michaelbeil** [comment]
@chimbaweb not every user will have Gravity Forms, so we want to make it possible in AffiliateWP core.

**Comment by chimbaweb** [comment]
I see. Not sure how many of your customers use GravityForms, but that was a major reason for me to get it. And it works really great.
Maybe it would be a nice addon to make the same email tags available within GravityForm.

It would be very valueable to play with this available data within email notification of GF.

**Comment by sumobi** [comment]
Since we refer to this as a campaign name I'd like to suggest the email tag be **{campaign_name}**

![screen shot 2016-08-20 at 11 55 53 am](https://cloud.githubusercontent.com/assets/52581/17827195/1e75cc7e-66cd-11e6-860b-70ebb97d4b89.png)

**Comment by michaelbeil** [comment]
Sounds good to me. I've changed the tag accordingly.

**Comment by DrewAPicture** [comment]
Added a PR: #1737 with the new tag.

**Comment by pippinsplugins** [comment]
PR looks good.
