### ISSUE TITLE
Shiny Updates-style add-on authentication and installation for add-ons

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#1337]
It would be cool if AffiliateWP add-ons could be installed in a manner similar to the [Shiny Updates](https://make.wordpress.org/core/2016/06/02/proposal-more-shiny-updates/) proposal in WordPress 4.6.
- The free add-ons would (ideally) leverage WordPress internals for shiny updates.
- We may need to introduce some manner of auth (yay) for Pro add-ons to authenticate the site/license (perhaps similar to how it's implemented in Gravity Forms).
- Here's a fictional but _tantalizing_ mockup:

![mockup of shiny updates in AffiliateWP](https://cldup.com/FVZzuqCx7R.gif)

**Comment by ramiabraham** [comment]
_Unrelated: I just noticed this is issue #1337_ 🎉

**Comment by pippinsplugins** [comment]
Related: https://github.com/AffiliateWP/AffiliateWP/issues/1261

**Comment by michaelbeil** [comment]
That GIF makes me want to see this released now.

**Comment by pippinsplugins** [comment]
Closing as a duplicate of #1261
