### ISSUE TITLE
Empty status in affwp_set_referral_status Hook

### ISSUE THREAD

**Issue by iMojtaba** [AffiliateWP/AffiliateWP#1339]
hi, 
I write this code: 

```
add_action('affwp_set_referral_status', 'update_user_cash_meta');
function update_user_cash_meta($referral_id, $new_status, $old_status) {
    $parameters = array($referral_id, $new_status, $old_status);
    update_option( 'affwp_parameters', $parameters );
}

```
and the output is:

```
Array
(
    [0] => 1
    [1] => 
    [2] => 
)
```

as you can see new_status and old_status is empty.
what is the problem? is it my fault or something else?

**Comment by pippinsplugins** [comment]
Change `add_action('affwp_set_referral_status', 'update_user_cash_meta');` to `add_action('affwp_set_referral_status', 'update_user_cash_meta', 10, 3);`.

That will resolve it.

**Comment by iMojtaba** [comment]
yes! It's resolved.
Thank you so much
