### ISSUE TITLE
MemberPress: Referral incorrect with a trial period

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1342]
When an affiliate coupon with a trial period is used by a visitor, the referral is calculated by the full membership price instead of calculating off of the trial period total. Let us say there is a coupon that is for 0% off on a $50 membership, and has a trial period which overrides the membership for 30 days at $40. This coupon is attached to an affiliate with a referral rate of 10%. The total would be $40 after applying the coupon at checkout. This also happens when a membership has a trial period set.  
  
![screen shot 2016-06-21 at 4 35 28 pm](https://cloud.githubusercontent.com/assets/4752949/16247179/3cd700e4-37ce-11e6-9e7a-b308f35e77ea.png)
 
Expected referral amount: $4 
Actual referral amount: $5 

To replicate with an affiliate coupon:
1. Create a membership
2. Create a coupon that is 0%, has a trial period, and is associated with an affiliate
3. Make a purchase of aforementioned membership with the affiliate coupon

To replicate with an affiliate link:
1. Create a membership that has a trial period
2. Navigate to the membership via an affiliate link
3. Make a purchase of aforementioned membership 

 **Update**: this happens with any trial period, whether set in a membership or overridden in a coupon

**Comment by michaelbeil** [comment]
It seems to be only bugging out on a customer site.

**Comment by michaelbeil** [comment]
Seems to be connected to https://github.com/AffiliateWP/affiliate-wp-recurring-referrals/issues/37

**Comment by michaelbeil** [comment]
I am reopening this issue as I have noticed that referrals created through purchases that have used affiliate coupons with trial periods are incorrectly calculated.

**Comment by DrewAPicture** [comment]
Added a PR: #1366 

@michaelbeil Let me know if this is the behavior you're looking for. I was having trouble getting the referrals to record which I think is something janky on my end. The amounts should line up though.

**Comment by michaelbeil** [comment]
This looks like it should be what is desired. Need to test further once a license key is available.

**Comment by pippinsplugins** [comment]
@michaelbeil I've just deactivated the key so you can test it now.

**Comment by michaelbeil** [comment]
I cannot create a referral that is calculated based off of the trial period when using an affiliate coupon.

We should also account for trials being used within a membership as well. 

Any good news on your end @DrewAPicture?

**Comment by DrewAPicture** [comment]
@michaelbeil Took me a while to track down what was ultimately a missing `!` in the `is_valid_affiliate()` check for retrieving the affiliate ID for the coupon used.

I've pushed up the fix for the reversed logic and managed to successfully generate referrals at the expected amounts for trial coupons, regular coupons, and regular non-coupon sales. Please re-test!

**Comment by michaelbeil** [comment]
Oh, this works wonderfully, by the way. I tested several times earlier. 

Testing on a customer site now.

**Comment by pippinsplugins** [comment]
Excellent. Once it's confirmed on the customer site, let's merge.

**Comment by DrewAPicture** [comment]
@michaelbeil Any update on the customer confirmation?

**Comment by michaelbeil** [comment]
@DrewAPicture mentioned:
 > If a membership is purchased with:
1. Affiliate URL + coupon, a visit will be generated, a pending referral will be generated on initial form, unpaid on completion. Referral will use coupon amount to calc commission.
2. Coupon, a visit ​_will not_​ be generated, a pending referral will be generated on initial form, unpaid on completion. Referral will use coupon amount to calc commission
3. Affiliate URL, a visit will be generated, a pending referral will be generated on initial form, unpaid on completion, Referral will use full amount to calc commission.

It looks like affiliate URL-only commissions do not work for recurring memberships, but they do work for non-recurring memberships.

**Comment by michaelbeil** [comment]
I am going to create a new issue per my last comment.

See #1375.

**Comment by michaelbeil** [comment]
The current implementation in `issue/1342` fixes the trial period issue.

**Comment by DrewAPicture** [comment]
Merged #1366 for 1.8.3.
