### ISSUE TITLE
Add 'affwp_insert_pending_referral' filter to RCP integration

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1343]
PR: #1338

**Comment by pippinsplugins** [comment]
@michaelbeil Can you please go ahead and test this?

**Comment by michaelbeil** [comment]
Yep. I can test in the morning.

**Comment by michaelbeil** [comment]
This seems to have broken the RCP integration.

**Comment by michaelbeil** [comment]
All works well on `master`.

**Comment by DrewAPicture** [comment]
Added #1483 as a continuation of #1338.

**Comment by DrewAPicture** [comment]
Once tests pass, we can merge.

**Comment by DrewAPicture** [comment]
Tests passed, merged #1483.
