### ISSUE TITLE
Fix skipping the amount floatval test

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1351]
Since 1.8, we've skipped the `test_format_amount_floatval_remains_floatval_with_comma_thousands_seperator()` test because of lexical variable errors. Let's try to not skip that one.

**Comment by DrewAPicture** [comment]
Added a PR: #1352

**Comment by pippinsplugins** [comment]
Looks good. Let's merge once tests pass.

**Comment by DrewAPicture** [comment]
Tests passing.

Merged #1352.
