### ISSUE TITLE
Users can register as affiliates when affiliate registration is not enabled

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1367]
Users can register as affiliates when affiliate registration is not enabled. Cause of issue is the new button we added to the user profile screen.

![screen shot 2016-06-22 at 1 55 37 pm](https://cloud.githubusercontent.com/assets/52581/16252368/98fdf7ca-3881-11e6-8b02-81e49ef96cb6.png)

**Comment by pippinsplugins** [comment]
I vote that we don't show the field unless current user can manage affiliates.

**Comment by sumobi** [comment]
Yep that entire "AffiliateWP" section should be hidden to a normal user

**Comment by michaelbeil** [comment]
Sounds good to me.

**Comment by michaelbeil** [comment]
Works perfectly.
