### ISSUE TITLE
Global debug mode

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1370]
It would be nice if we could set a constant to globally-enable debug mode. Simplest way to accomplish this with full back-compat would be to usurp the value of the `debug_mode` setting when it's retrieved.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by DrewAPicture** [comment]
Added a PR: #1371 

* Usurps the value of the `debug_mode` value when retrieved
* Disables the setting in the 'Misc' tab with a helpful message:

![Disabled setting](http://cl.ly/0W3I0e252O0f/Screen%20Shot%202016-06-24%20at%2012.41.28%20PM.png)

* Introduces a new setting argument, 'disabled' that might be reused in the future (see #1229)
* Introduces a helper method: `is_setting_disabled()` for use in setting callbacks

**Comment by DrewAPicture** [comment]
Added a unit test.

**Comment by michaelbeil** [comment]
This is nice.

**Comment by pippinsplugins** [comment]
Works perfectly!
