### ISSUE TITLE
MemberPress: Affiliate URL-only commissions do not work when a membership is set to recurring

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1375]
If a membership is purchased with:

1. Affiliate URL + coupon, a visit will be generated, a pending referral will be generated on initial form, unpaid on completion. Referral will use coupon amount to calc commission.
2. Coupon, a visit ​will not​ be generated, a pending referral will be generated on initial form, unpaid on completion. Referral will use coupon amount to calc commission
3. Affiliate URL, a visit will be generated, a pending referral will be generated on initial form, unpaid on completion, Referral will use full amount to calc commission.

It looks like affiliate URL-only commissions do not show as converted and the referral is still pending for recurring memberships, but they do work for non-recurring memberships.

**Comment by DrewAPicture** [comment]
Added a PR: #1394 

@michaelbeil If you have a few minutes, could you please test all the permutations of recurring memberships, including with trials (at the membership level) and coupons and such?
