### ISSUE TITLE
Show affiliates payout information in Affiliate Area

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1376]
It would be nice for affiliates to see their payouts from within the Affiliate Area somewhere.

- Amount
- Payment Type
- Date transferred
- Status

**Comment by sumobi** [comment]
Related: https://github.com/AffiliateWP/AffiliateWP/issues/471

**Comment by pippinsplugins** [comment]
This is being done as part of #471 so I'm going to close.
![screen shot 2016-08-22 at 4 08 48 pm](https://cloud.githubusercontent.com/assets/1034109/17871806/c3c3b766-6882-11e6-9052-60a2de2190c0.png)
