### ISSUE TITLE
Rename affwp-affiliate-dashbaord-visits 

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1378]
In #872 we introduced a new column to the visits table and thus added some CSS to style the column appropriately. However, the id selector should be #affwp-affiliate-dashboard-visits  as opposed to #affwp-affiliate-dashbaord-visits.

**Comment by pippinsplugins** [comment]
Fixed in https://github.com/AffiliateWP/AffiliateWP/pull/1377
