### ISSUE TITLE
Integration with WPForms

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1380]
WPForms is an up and coming forms plugin that would seem befitting for AffiliateWP to support: https://wpforms.com. 

We could then create an Affiliate Forms for WPForms add-on that would allow users to use a WPForm for affiliate registration.

**Comment by sumobi** [comment]
We should definitely check it out and look into a proper integration.

**Comment by michaelbeil** [comment]
Request: https://secure.helpscout.net/conversation/249242675/41980/?folderId=634609

**Comment by jaredatch** [comment]
👍 😎 

Obviously I'd love this!

Payments with WPForms right now are rather basic. But we are slowly expanding and adding more capabilities and payment fields.

If there are certain things that need to be done or added to support an integration just  let me know. Really just depends on how fancy and complex the integration needs to be I suspect.

**Comment by michaelbeil** [comment]
😄 

@jaredatch Would you be able to gather some resources on what is available in WPForms? Could be das simple as links to documentation, hooks, filters, etc.

**Comment by michaelbeil** [comment]
Main docs: https://wpforms.com/docs/

**Comment by jaredatch** [comment]
Developer docs right now are non-existent, so I'll have to help with that. Something that's on my list to do, but admittedly towards the bottom just due to my current workload.

I guess maybe the best thing would be for me to learn more about how an typical AffWP integration works, then I'll have an idea of what needs to be done (or can be done). 

Are they all similar from a functionality/feature standpoint, or are the integrations different depending on the capabilities of the plugin being integrated?

Maybe you can give me a super high level overview/pseudocode on how an integration works at the most basic level? 😀

**Comment by pippinsplugins** [comment]
Any / all of the existing integrations would be good to look at. Some of the simpler ones:

https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-shopp.php
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-wpec.php
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-formidablepro.php
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-gravityforms.php

**Comment by jaredatch** [comment]
Perfect, I'll give those a look this week and get a feel for what you guys typically need/do.

**Comment by pippinsplugins** [comment]
WP Forms and the main add-ons are all in dropbox now for anyone that wants to jump on this.

**Comment by jaredatch** [comment]
As I mentioned to Pippin, if you guys find you need hooks/filters in place for things, just let me know.

The Stripe addon specifically is going to be expanded on quite a bit next year to include more robust functionality, but that probably wont be until Q2 or Q3.

**Comment by sumobi** [comment]
Stolen from @ramiabraham, sorry buddy.

@AffiliateWP/core Added basic WIP that generates referrals. More to come.

@jaredatch We need a `do_action` for the PayPal and Stripe add-ons so we know when the payment was successfully created. All I can see is `wpforms_process_complete` which runs for both the `wpforms` and `wpforms-lite` plugins.

Similar to:
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-edd.php#L18

and

https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-gravityforms.php#L20

Looks like we'll need a refund hook also.

**Comment by sumobi** [comment]
@jaredatch Oh and please send me a vector version of the WPForms logo (.ai, .svg, .eps) if you can so we can get it ready on the website. Thanks!

**Comment by jaredatch** [comment]
Much appreciated @sumobi, will get back to you on this stuff :)

**Comment by sumobi** [comment]
Thanks Jared!

**Comment by pippinsplugins** [comment]
@jaredatch any chance the new hooks will be added soon? We're hoping to include this in the beta for 2.0, which goes out on Tuesday of next week.

**Comment by jaredatch** [comment]
[wpforms-paypal-standard.zip](https://github.com/AffiliateWP/AffiliateWP/files/696400/wpforms-paypal-standard.zip)
[wpforms-stripe.zip](https://github.com/AffiliateWP/AffiliateWP/files/696399/wpforms-stripe.zip)

Here are the two addons with some hooks that fire after transactions - I think this might do this trick.

In PayPal, `class-paypal-standard.php` L508

In Stripe, `class-stripe.php` L304

Let me know how those look. If good I can push those updates out this week :)

**Comment by pippinsplugins** [comment]
@jaredatch that looks like it should work just fine!

**Comment by pippinsplugins** [comment]
I've added in handling for the new hooks and they work great!

Merging once tests pass.

**Comment by pippinsplugins** [comment]
Merged.
