### ISSUE TITLE
Add referral URL to edit affiliate screen

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1382]
It can be difficult for some site owners to work out what a specific affiliate's referral URL is. 

Adding a `Referral URL` row to the edit affiliate screen could be a good idea. This will allow the admin to quickly copy and paste it if they need to give it to the affiliate.

The Referral URL could simply be a text link (a disabled input field doesn't allow for copy and paste) and it would be constructed based on the current admin settings:  Referral Variable, Default Referral Format, Pretty Affiliate URLs, and the Default Referral URL.

The description could say:

>  The affiliate’s referral URL, based on the current admin settings.

**Comment by DrewAPicture** [comment]
Added a PR: #1683 

Looks like this:
![Affiliate URL](https://cl.ly/3y0j3w2L0L2e/Screen%20Shot%202016-10-02%20at%203.23.11%20PM.jpg)

**Comment by pippinsplugins** [comment]
Merged.

In the future it may be worthwhile adding an additional note to explain that affiliates can generate URLs for any page of the site and this is only the default URL.

**Comment by sumobi** [comment]
I agree.
