### ISSUE TITLE
wp_affiliate_wp_campaigns DB error on Export/Import

### ISSUE THREAD

**Issue by neilgee** [AffiliateWP/AffiliateWP#1384]
Am getting a db error when importing a db with some AffiliateWP tables...

![screen shot 2016-06-30 at 2 03 44 pm](https://cloud.githubusercontent.com/assets/2056045/16476537/aa152d1c-3ecb-11e6-8b5f-d9496c6d6424.png)

db has been repaired and optimised - plugins are up to date, latest WP.

Any thoughts

**Comment by pippinsplugins** [comment]
@neilgee That's happening because the `campaigns` "table" is not a table, it's a [view](http://dev.mysql.com/doc/refman/5.7/en/create-view.html). Since it's a view, the user that is performing the import needs to have super privileges in order to create it.

Give your user super privileges and the issue should go away.

**Comment by neilgee** [comment]
@pippinsplugins ok thanks, so if you don't have root access to the account this will be an issue.

**Comment by michaelbeil** [comment]
@neilgee You do not necessarily need root access, but you will need to add the privileges to create a view like `Create_view_priv` and `Super_priv ` as shown here: [Privileges Provided by MySQL](http://dev.mysql.com/doc/refman/5.7/en/privileges-provided.html).

Here's a paragraph that might help bring some guidance from the above doc @pippinsplugins mentioned called [CREATE VIEW Syntax](http://dev.mysql.com/doc/refman/5.7/en/create-view.html):
```The CREATE VIEW statement requires the CREATE VIEW privilege for the view, and some privilege for each column selected by the SELECT statement. For columns used elsewhere in the SELECT statement, you must have the SELECT privilege. If the OR REPLACE clause is present, you must also have the DROP privilege for the view. CREATE VIEW might also require the SUPER privilege, depending on the DEFINER value, as described later in this section.```

**Comment by neilgee** [comment]
@michaelbeil thanks for the input

**Comment by michaelbeil** [comment]
You bet!
