### ISSUE TITLE
Table aligment in Affiliate area in visits tab

### ISSUE THREAD

**Issue by AiratHalitov** [AffiliateWP/AffiliateWP#1385]
That screenshot in page EXAMPLE.COM/affiliate-area/?tab=visits
https://yadi.sk/i/8HZWTuPlsuG7r

That screenshot in BuddyPress member affiliate tab in page EXAMPLE.COM/members/USERNAME/affiliate-area/affiliate-visits/ (AffiliateWP BuddyPress plugin)
https://yadi.sk/i/YnhqNHrdsuGET

Wordpress 4.5.3
BuddyPress 2.6.1
Boss theme 2.2.0
AffiliateWP 1.8.3
AffiliateWP BuddyPress 1.3

**Comment by pippinsplugins** [comment]
@AiratHalitov what's your screen resolution? I believe that's an issue with the size of the screen and lack of responsiveness.

**Comment by AiratHalitov** [comment]
1366*768.
On first screenshot i zoom out page. 
That is not lack of responsiveness, that is bug with table html code.
I think that i don't seen this bug in previous versions of AffiliateWP (meybe 2 or 3 update before)

**Comment by AiratHalitov** [comment]
@pippinsplugins that the same bug https://github.com/AffiliateWP/AffiliateWP/issues/1390

**Comment by pippinsplugins** [comment]
Ah! We'll get that fixed.

**Comment by pippinsplugins** [comment]
I'm going to close this issue. We'll fix in #1390
