### ISSUE TITLE
{review_url} or similar

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1388]
PR: #1424

I'd like to propose a new email tag that would be used only in the admin notification email. 

This email tag would provide a link in the email that the admin can click on, and will take them directly to the "review" screen of the affiliate that is pending approval. 

It could be called {review_url} or similar and only show if affiliate approval is enabled.

**Comment by michaelbeil** [comment]
Seems pretty handy to me.1

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by michaelbeil** [comment]
We should remove the `{review_url}` tag from the descriptions under the `Application Accepted Email` and the `New Referral Email`.

**Comment by pippinsplugins** [comment]
At the moment we do not have support for showing specific tags under specific fields. That will need to be a new issue.
