### ISSUE TITLE
Incorrect colspan on Affiliate Dashboard visits when no visits present

### ISSUE THREAD

**Issue by cklosowski** [AffiliateWP/AffiliateWP#1390]
Currently when no visits are present for an affiliate in their dashboard the table is off by 1 column:
![screen shot 2016-07-01 at 1 02 22 am](https://cloud.githubusercontent.com/assets/1390124/16515596/c0de99dc-3f27-11e6-8b22-afbc836b945b.png)

Just needs to have an updated `colspan` attribute here. It's set to `3` but there are `4` columns:
`<td colspan="3">You have not received any visits yet.</td>`

**Comment by DrewAPicture** [comment]
Added a PR: #1393 

Will merge once tests pass.
