### ISSUE TITLE
Storefront add-on

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#1391]
This thread tracks activity relating to the store-front add-on, in the interest of gauging a minimum threshold for development consideration.

**Comment by ramiabraham** [comment]
https://secure.helpscout.net/conversation/221967641/37256/?folderId=205524

**Comment by michaelbeil** [comment]
Closing this in favor of this Trello card: https://trello.com/c/m20EWzzT/149-storefront.
