### ISSUE TITLE
MarketPress: Reference link in 3.x

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1403]
This is how the order screen was being shown before:

@DrewAPicture: 
> Basically, they were explicitly passing the `post_type` and `page` previously which set the `$typenow` and `$plugin_page` globals in admin.php, respectively. 

We need to account for the new admin URL, which uses the default post editor for MarketPress orders when linking a reference ID from the referrals screen. 

Old:
`$url = admin_url( 'edit.php?post_type=product&page=marketpress-orders&order_id=' . $reference );`

Proposed:  
`$url = admin_url( 'post.php?post=' . $reference . '&action=edit' );`

**Comment by pippinsplugins** [comment]
PR looks good once unit tests pass.
