### ISSUE TITLE
MarketPress: `mp_order_trashed` causes a fatal when `revoke_referral_on_delete` is enabled

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1404]
`mp_order_trashed` throws a fatal when `revoke_referral_on_delete` is enabled and any post (not just an order or a product) is trashed.

Current:
`add_action( 'trash_mp_order', array( $this, 'revoke_referral_on_delete' ), 10, 2 );`

Proposed: 
`add_action( 'trash_mp_order', array( $this, 'revoke_referral_on_delete' ) );`

**Comment by DrewAPicture** [comment]
Added a PR: #1406
