### ISSUE TITLE
MarketPress 3.x: Product descriptions don't carry through

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1407]
With the introduction of objects in the 3.0 rewrite, product descriptions are now stored differently than previously, thus we need to account for that.

**Comment by DrewAPicture** [comment]
Added a PR: #1408

**Comment by pippinsplugins** [comment]
Looks good once tests pass.

**Comment by DrewAPicture** [comment]
Tests passed. Merged #1408.
