### ISSUE TITLE
Missing class "visit-date" in file AffiliateWP-master/assets/css/forms.min.css

### ISSUE THREAD

**Issue by AiratHalitov** [AffiliateWP/AffiliateWP#1410]
Missing class "visit-date" in file AffiliateWP-master/assets/css/forms.min.css

https://yadi.sk/i/1udBgi-Qt4J6v (visits tab)

For example problem solved after replacing class "visit-date" on "referral-status" 
https://yadi.sk/i/hhERGjpZt4J8e

**Comment by michaelbeil** [comment]
That is odd, the class `visit-date` is in /assets/css/forms.min.css.

What version of AffiliateWP are you using?

**Comment by AiratHalitov** [comment]
AffiliateWP 1.8.4 
https://airat.biz/wp-content/plugins/AffiliateWP-master/assets/css/forms.min.css?ver=4.5.3

**Comment by AiratHalitov** [comment]
Where is class `visit-date`?
https://github.com/AffiliateWP/AffiliateWP/blob/master/assets/css/forms.min.css

**Comment by michaelbeil** [comment]
Ah, I see we missed minifying the new class in #1374.
