### ISSUE TITLE
Add system info report to help with tech support

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1413]
Like we have in EDD and [RCP](https://github.com/restrictcontentpro/restrict-content-pro/issues/330), it would be nice to have a system info report to help with troubleshooting issues. Items that would be useful (feel free to add any I miss):

- Site info (URLs under Settings > General, and whether it's multisite)
- WP config (version, language, permalink structure, memory limit, multisite, etc.)
- AffWP settings (page configs, ref variable, referral rate type, referral rate, exclude shippping and tax options, currency, integrations, misc settings)
- Installed plugins, broken down by mu-plugins, active, inactive
- Web server config (apache/nginx, PHP version, PHP config, etc.)
- Any others?

**Comment by DrewAPicture** [comment]
Started a PR: #1497 

Initially it just sets up the internals and adds the base WP info, nothing AffWP-specific yet. Will circle back around.

**Comment by pippinsplugins** [comment]
Looking good so far!

**Comment by DrewAPicture** [comment]
Added AffiliateWP-specific info in 433b39d.

**Comment by pippinsplugins** [comment]
Looks good here! Let's merge once tests pass.

**Comment by sumobi** [comment]
@AffiliateWP/core Does it look like this by default for anyone else? Let's make it a tad taller and wider

![screen shot 2016-08-10 at 5 22 53 pm](https://cloud.githubusercontent.com/assets/52581/17542679/22cdf00e-5f1f-11e6-9919-c5a1fd6d226c.png)

**Comment by DrewAPicture** [comment]
@sumobi Try updating `master` with the newly-minified admin CSS.

**Comment by sumobi** [comment]
Looks like a caching issue, fixed! 👍

**Comment by sumobi** [comment]
@DrewAPicture can we increase the default width by a cat's whisker or two? It looks like the post statuses will be the longest line.

Default (800px)

![screen shot 2016-08-10 at 5 44 42 pm](https://cloud.githubusercontent.com/assets/52581/17543136/79907f12-5f22-11e6-8cca-1f34035d7029.png)

840px:

![screen shot 2016-08-10 at 5 45 42 pm](https://cloud.githubusercontent.com/assets/52581/17543135/798fc70c-5f22-11e6-9cc3-ddbf4e9386e7.png)

**Comment by sumobi** [comment]
Actually, nevermind. Someone is bound to have a longer file path, I'm just secretly wanting it to look ok on my set up. OCD anyone?
