### ISSUE TITLE
Improve build script

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1414]
We should include both admin.css and forms.css when running the `grunt cssmin` command. It would also be good to add `cssmin` to the `grunt build` task.

**Comment by sumobi** [comment]
👍

**Comment by DrewAPicture** [comment]
@pippinsplugins Mind giving this a look? I'm not sure how to go about testing that this works as expected.

**Comment by fxbenard** [comment]
@DrewAPicture in case you want: `grunt build` to check it out. Just check files are minified. The previous grunt task was working fine.

**Comment by DrewAPicture** [comment]
@fxbenard I meant in terms of testing the external build process in the context of packaging for release. But thanks for the suggestion ;)

**Comment by pippinsplugins** [comment]
Looks good.

Note: it still does not cover JS min.

**Comment by ramiabraham** [comment]
JS min added in https://github.com/AffiliateWP/AffiliateWP/commit/e775811654a3e0df2610e5ebad748832372553f4

**Comment by DrewAPicture** [comment]
Tests passed, merged #1493.

**Comment by pippinsplugins** [comment]
This works really nicely.
