### ISSUE TITLE
Author name has an extra comma in the plugins dashboard

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1418]
![screen shot 2016-07-06 at 6 24 42 pm](https://cloud.githubusercontent.com/assets/4752949/16637781/f830f2da-43a6-11e6-8d75-37ac8e9637f0.png)

**Comment by sumobi** [comment]
Hmm I'm not seeing this on latest master

![screen shot 2016-07-07 at 7 05 31 pm](https://cloud.githubusercontent.com/assets/52581/16645119/cc02ef22-4475-11e6-8ae6-332f5e2923f3.png)

**Comment by michaelbeil** [comment]
Strange. All good here now.
