### ISSUE TITLE
WooCommerce: Move product rates to dedicated tab

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1427]
PR: #1428

WooCommerce 2.6 removed the `General` tab for variable products: https://github.com/woothemes/woocommerce/issues/11262

This has resulted in our product rate settings not being displayed when using variable products.

To resolve this and prevent possible future issues, I vote we move the settings to dedicated product tab.

**Comment by michaelbeil** [comment]
Agreed.

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by michaelbeil** [comment]
PR works great.
![screen shot on 2016-07-11 at 13-32-40](https://cloud.githubusercontent.com/assets/4752949/16742134/fc869f38-476b-11e6-86d8-78d225e4d568.png)

**Comment by DrewAPicture** [comment]
Works great here too.

**Comment by DrewAPicture** [comment]
Merged #1428.
