### ISSUE TITLE
Call to undefined function affwp_get_pages

### ISSUE THREAD

**Issue by nhadsall** [AffiliateWP/AffiliateWP#1431]
Using ManageWP, we are getting this error when it tries to sync with the site. I assume it is similar to issue #1038

**Comment by michaelbeil** [comment]
Do you have any custom code to modify AffiliateWP that you are using?

**Comment by nhadsall** [comment]
Yes, two hooks:
remove_action( 'affwp_set_affiliate_status', 'affwp_notify_on_approval',
10, 3 );
add_filter( 'affwp_calc_referral_amount', array( $this,
'affwp_custom_per_product_per_affiliate_referral_amount'), 10, 5 );

*Nathan Hadsall*
President, Montessori By Mom
MontessoriByMom.com <http://www.montessoribymom.com/>
Cell: 408-239-6485
Work: 210-901-9210

Leadership Consultant and Speaker
LinkedIn (http://linkedin.com/in/nhadsall)
Sleight of Mind (http://sofmind.com)

**Comment by pippinsplugins** [comment]
See https://github.com/AffiliateWP/AffiliateWP/issues/1038

**Comment by nhadsall** [comment]
I have been working with ManageWP on this issue, but they put the blame on AffiliateWP. If neither side can resolve the issue, I am going to have to stop using one service or the other. It looks like ManageWP does not totally understand the problem. Any change I could get some information to point them in the right direction? Thanks!

**Comment by pippinsplugins** [comment]
@nhadsall it basically comes down to ManageWP loading pieces of WordPress (but not others) in a non-standard way. Because they're using non-standard methods, it should be entirely up to them to ensure they are not breaking plugin compatibility (which they are).

Now, that being said, I would rather we put a shim in on our side to prevent the problem. We've seen it happen twice so it will likely happen again.

**Comment by pippinsplugins** [comment]
@nhadsall can you please get me the exact error message so that I can see which file it's occurring in?

**Comment by nhadsall** [comment]
@pippinsplugins This is what makes your products so great: "Bad code breaks our code... sure we can make our code even better." Sadly, ManageWP's response was, "Uh, we are kinda busy and you are just one client... plus this isn't really our fault."

The error is:
Fatal Error (E_ERROR): Call to undefined function affwp_get_pages() occurred in wp-content/plugins/affiliate-wp/includes/admin/settings/class-settings.php on line 401

**Comment by pippinsplugins** [comment]
I really hope that wasn't an exact copy-paste of their reply . . . . Shameful.

**Comment by nhadsall** [comment]
No, not copy/paste so I probably should not have put it in quotes, but that was the sentiment behind the words. They are going through some major growing pains right now, so I can give them a little slack, but I was still disappointed in the support. I appreciate your help!

**Comment by pippinsplugins** [comment]
Patch submitted that will resolve it.

We'll include this in the next point release.
