### ISSUE TITLE
MemberPress: Free trial period should award a $0 referral

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1441]
PR: #1481

At this time, a free trial for a subscription purchase awards a referral (based on the full product price instead of the $0 free trial transaction) to the referring affiliate. I think we should adjust the referral awarded when there is a free trial period so that it becomes a $0 referral if a referral rate type of percentage is selected.

**Comment by pippinsplugins** [comment]
Doing this would also make `Recurring Referrals` automatically pick up the subscription once it changes from a free trial to a paid one.

**Comment by DrewAPicture** [comment]
Added a PR: #1481

**Comment by DrewAPicture** [comment]
To test:

1. Create a recurring membership level with a free trial
2. Ensure the affiliate rate type is percentage
3. Purchase the recurring membership on a referral URL (without a coupon)
4. The referral commission should be 0 based on the free trial

1. Edit the new recurring membership level and remove the trial.
2. Purchase the recurring membership on a referral URL (without a coupon)
3. The referral commission should be reflected based on the rate, rate type, and membership cost as usual.

**Comment by pippinsplugins** [comment]
I will test later today.

**Comment by pippinsplugins** [comment]
Works perfectly.
