### ISSUE TITLE
Affiliate Form Settings

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1443]
This issue has been a combined with 2 other issues which go hand in hand. The other issues have been closed for clarity. All discussion will be held here.

The old Issues that have been combined with this one:

https://github.com/AffiliateWP/AffiliateWP/issues/931 - Add Forms tab to settings
https://github.com/AffiliateWP/AffiliateWP/issues/1051 - Easily show or remove affiliate registration & affiliate login forms on affiliate area page

This issue covers:

- A filter to hide the registration and login form from the [affiliate_area] shortcode
- A new select menu in the admin settings to allow the user to control what forms are shown on the Affiliate Area page
- New checkbox options for selecting which affiliate registration fields should be required or not.

![screen shot 2016-12-27 at 4 25 21 pm](https://cloud.githubusercontent.com/assets/52581/21489573/18300f66-cc51-11e6-9eec-98b2d7f92702.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
Oh check that out https://github.com/AffiliateWP/AffiliateWP/issues/1051. A filter to programmatically hide it and an admin dropdown would be helpful.

**Comment by DrewAPicture** [comment]
I like #1051 as well. I think we should focus our attention there on the 1.9 milestone. @AffiliateWP/core  Any objections?

**Comment by pippinsplugins** [comment]
No objections here.

**Comment by pippinsplugins** [comment]
#1051 was moved to 2.0 so moving this as well.

**Comment by sumobi** [comment]
@AffiliateWP/core Ready for review. I'd love to hear any thoughts on how to make it cleaner.

**Comment by sumobi** [comment]
To test you can either play with the filters directly, setting them individually to `false` which will hide each form, or you can now change the select menu from the bottom of the Affiliates -> Settings -> General tab (location to be discussed).

**Comment by sumobi** [comment]
### The "Affiliate Area Forms" select menu
Previous discussion was here: https://github.com/AffiliateWP/AffiliateWP/issues/1051
___

![screen shot 2016-12-27 at 3 57 01 pm](https://cloud.githubusercontent.com/assets/52581/21489263/3d1b28fa-cc4d-11e6-9662-bef35dc42480.png)

![screen shot 2016-12-27 at 3 57 08 pm](https://cloud.githubusercontent.com/assets/52581/21489262/3d1a9de0-cc4d-11e6-99ec-a75d5fdcba1c.png)

**Comment by sumobi** [comment]
### New checkbox options for selecting which affiliate registration fields should be required (or not).

These new checkbox options will not show until `Allow Affiliate Registration` is enabled, and will also live under the "Affiliate Form Settings" section.
___

When AffiliateWP is first installed, 2 of the 4 checkbox options will be selected by default, the "Your Name" and "Website URL" fields. This is because these are the fields that have always been required by default.

![screen shot 2016-12-27 at 4 01 56 pm](https://cloud.githubusercontent.com/assets/52581/21489305/d0b87b58-cc4d-11e6-973f-e500f2e324b9.png)
___

Customers will now be able to make some of these fields required, all of them required, or none required. This was primarily built since not requiring the website URL field is a very common support ticket we get. See the previous discussion on these options here: https://github.com/AffiliateWP/AffiliateWP/issues/931

**Comment by sumobi** [comment]
@pippinsplugins @DrewAPicture 

See above, I've merged 2 other issues into this one and updated the title/description of this ticket. I'd appreciate your help on finishing this one off.

PR is https://github.com/AffiliateWP/AffiliateWP/pull/1855

For the checkbox options (https://github.com/AffiliateWP/AffiliateWP/issues/1443#issuecomment-269262818) I've introduced a new `affwp_update_settings()` function. I know this is less than ideal, so this is what I need help with. I spotted the `$affiliate_wp_install->settings->set()` method but it doesn't look like it can help with arrays.

The point of this new function is so the checkbox options are enabled when AffiliateWP is first installed. I've called it so far in the installation script here (tested and works): https://github.com/AffiliateWP/AffiliateWP/blob/issue/1443/includes/install.php#L46

I need:

- A tidy up of this function if there's a better way to do it
- An upgrade routine built that also enables these 2 form fields. Perhaps you can rewrite the function to do both for the install and upgrade
- The function renamed and moved  to a different location if there's a better place to put it/better name for it.

**Comment by DrewAPicture** [comment]
> I spotted the $affiliate_wp_install->settings->set() method but it
doesn't look like it can help with arrays

`$affiliate_wp_install->settings` is just a hard-instantiated instance of
the settings class, and the `set()` method actually only accepts an array
as the first argument anyway, so there shouldn't be a need to introduce a
new function. You'd just want to make sure the second argument (`$save`) is
passed as true.

However, for our purposes, these new settings should get set inside the
upgrade routine for 2.0.

**Comment by DrewAPicture** [comment]
> I spotted the `$affiliate_wp_install->settings->set()` method but it doesn't look like it can help with arrays

`$affiliate_wp_install->settings` is just a hard-instantiated instance of the settings class, and the `set()` method actually only accepts an array as the first argument anyway, so there shouldn't be a need to introduce a new function. You'd just want to make sure the second argument (`$save`) is
passed as true.

However, for our purposes, these new settings should get set inside the upgrade routine for 2.0.

**Comment by sumobi** [comment]
Oh yeah nice 👍, wasn't thinking 1 level deeper. I can do this instead:

    $affiliate_wp_install->settings->set(
        array(
	        'required_registration_fields' => array(
	            'your_name'   => 'Your Name',
		    'website_url' => 'Website URL'
		)
        ),
        $save = true
    );

**Comment by sumobi** [comment]
Updated PR. Can I get someone to double-check the upgrade routine? look ok?

**Comment by sumobi** [comment]
Updated PR, upgrade routine look ok? seems to work fine.

**Comment by DrewAPicture** [comment]
I'll take a look at this tonight.

**Comment by pippinsplugins** [comment]
@sumobi this seems to work really well. Have you had a chance to test and confirm it doesn't cause any issues with the registration form add-ons for Gravity Forms or Ninja Forms.

**Comment by sumobi** [comment]
@pippinsplugins I have not but will do. I can't test Ninja Forms (due to that quirk with the action being blank) so hopefully someone else can test that, @AffiliateWP/core pretty please?

I'll hit Gravity Forms

**Comment by sumobi** [comment]
AFGF works fine since it replaces the entire form with the Gravity Form and has it's own registration class. AFNF should be the same.

**Comment by pippinsplugins** [comment]
Great! Let's get a review from @DrewAPicture then finish this up.

**Comment by DrewAPicture** [comment]
Left some notes on the PR: #1855

**Comment by sumobi** [comment]
I think we're good here, fixed up some things as per @DrewAPicture's notes.

**Comment by DrewAPicture** [comment]
Merged #1855.
