### ISSUE TITLE
Multiple Email Notifications

### ISSUE THREAD

**Issue by sujaypawar** [AffiliateWP/AffiliateWP#1444]
PR: #1491.
Previously: #1445

If the user is already accepted as an affiliate and admin approves him again from bulk action, user gets an email. 

Here's a video - http://www.youtube.com/watch?v=DFZMU43EiKg

**Comment by michaelbeil** [comment]
Thanks for the report! We will look into fixing this in a future release.

**Comment by DrewAPicture** [comment]
Merged #1445 and #1446.

**Comment by DrewAPicture** [comment]
Whoops. Looks like the conditionals change broke acceptance emails for all new affiliates.

**Comment by DrewAPicture** [comment]
Added a PR: #1490 

Note that the logic is essentially backward. If *not* these conditionals, bail. Makes it hard to wrap your head around, but there is really a great alternative since `continue` outside of `foreach()` is now a no-no.

**Comment by DrewAPicture** [comment]
@pippinsplugins This is ready for testing at your leisure.

**Comment by pippinsplugins** [comment]
@DrewAPicture I don't get any emails when manually adding affiliates now. Email is sent fine on `master`.

**Comment by DrewAPicture** [comment]
@pippinsplugins Can you please retest following 9b37e7cc3?

**Comment by pippinsplugins** [comment]
@DrewAPicture getting closer but not quite.

Emails were sent properly when registering a user as an affiliate.

The `active` email was sent improperly when deactivating an affiliate.

To replicate:

1. Register affiliate. Welcome email will be sent. This is correct.
2. Deactivate affiliate. Welcome email will be sent again. This is incorrect.
3. Activate affiliate. Welcome email is _not_ sent. This is correct.

**Comment by DrewAPicture** [comment]
@pippinsplugins OK, I think I've got the last problem covered (hopefully). I also clarified the inline comments to try to explain the cases where an acceptance email wouldn't be sent. Let me know if it's still not there.

**Comment by pippinsplugins** [comment]
@DrewAPicture I think you got it!

@sumobi could you give it a once over to confirm?

**Comment by sumobi** [comment]
@pippinsplugins @DrewAPicture All emails working for me 👍
