### ISSUE TITLE
Redirect to blog page

### ISSUE THREAD

**Issue by AiratHalitov** [AffiliateWP/AffiliateWP#1454]
That URL https://airat.biz/?ref=airathalitov is opening blog page https://airat.biz/blog/ for logged out users instead main page (https://airat.biz/)

For logged in users this URL https://airat.biz/?ref=airathalitov is opening site main page (It's normal behaviour).

AffiliateWP 1.8.5
Wordpress 4.5.3
BuddyPress 2.6.1.1

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
