### ISSUE TITLE
Add a third column on the overview screen for large screen resolutions

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1459]
It may be nice to allow the overview columns to extend into a third column when a browser window is 1500px or greater. 

1499px:
![screen shot 2016-07-21 at 5 39 40 pm](https://cloud.githubusercontent.com/assets/4752949/17041212/31542b76-4f6a-11e6-8913-e94191587a0d.png)
 
1500px:
![screen shot 2016-07-21 at 5 30 08 pm](https://cloud.githubusercontent.com/assets/4752949/17041213/3515082a-4f6a-11e6-8249-1a4cea3f0d4b.png)

**Comment by pippinsplugins** [comment]
This is already done as part of #1420

**Comment by michaelbeil** [comment]
Great!
