### ISSUE TITLE
Inactive affiliates can still earn a referral

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1465]
Steps to replicate:

1. Deactivate an affiliate
2. Navigate to the site with the inactive affiliate's link
3. Make a purchase
4. Referral is created

Related: #282, #554

**Comment by sumobi** [comment]
@michaelbeil What integration are you testing with?

So far I've only tested EDD but I'm not able to replicate. Tried deactivating the affiliate first then purchasing, and also storing the cookies first, then deactivating and purchasing.

**Comment by worldtravlr** [comment]
@sumobi this was with Woocommerce for me.

**Comment by sumobi** [comment]
@worldtravlr thanks for the confirmation. Does @michaelbeil's steps to replicate above look accurate to you? Can you list the specific steps that you took if different?

I haven't been able to replicate with WooCommerce. Tried deactivating the affiliate while the cookies exist in the browser, and before the cookies are stored, but each time no referral is created.

**Comment by worldtravlr** [comment]
Yes.  Those are accurate.  For example, I just visited an inactive affiliates link and it registered a visit. 

1.  /ref/UserName
2. AffiliateWP - Version 1.8.5 | WooCommerce Version 2.6.2 ( Latest is 2.6.3 )

Positive number

![screen shot 2016-07-25 at 8 00 44 pm](https://cloud.githubusercontent.com/assets/6686642/17099351/ce888014-52a2-11e6-90b5-b0bb0387046d.jpg)
![screen shot 2016-07-25 at 7 59 50 pm](https://cloud.githubusercontent.com/assets/6686642/17099354/ceda9796-52a2-11e6-9135-0915b5409de8.jpg)
![screen shot 2016-07-25 at 7 59 35 pm](https://cloud.githubusercontent.com/assets/6686642/17099355/cedb8fca-52a2-11e6-8fa9-54fc681b966a.jpg)

**Comment by sumobi** [comment]
Interesting, will try again. The visit is `-2` every time for me which is correct. Are you testing with only AffiliateWP active?

@AffiliateWP/core can anyone else replicate apart from @michaelbeil?

**Comment by worldtravlr** [comment]
I am on a live site with a bunch of plugins.  Here are the affiliteWP related ones:

> AffiliateWP
> General Settings | Deactivate
> Affiliate Plugin for WordPress
> 
> Version 1.8.5 | By AffiliateWP, LLC | Visit plugin site | Getting Started
> Select AffiliateWP - Affiliate Area Shortcakes	
> AffiliateWP - Affiliate Area Shortcakes
> Deactivate
> Provides shortcodes for each tab of the Affiliate Area + other useful shortcodes
> 
> Version 1.1.3 | By Pippin Williamson and Andrew Munro | View details | More add-ons
> Select AffiliateWP - Allow Own Referrals	
> AffiliateWP - Allow Own Referrals
> Deactivate
> Allows an affiliate to earn commission on their own referrals
> 
> Version 1.0.1 | By Pippin Williamson and Andrew Munro | View details
> Select AffiliateWP - Order Details For Affiliates	
> AffiliateWP - Order Details For Affiliates
> Deactivate
> Share customer purchase information with the affiliate who referred them
> 
> Version 1.1.2 | By Pippin Williamson and Andrew Munro | View details | Get add-ons
> Select AffiliateWP - Show Banner By Referral URL	
> AffiliateWP - Show Banner By Referral URL
> Deactivate
> Show an image banner based on the affiliate referral URL used
> 
> Version 1.0 | By Andrew Munro, Sumobi | Visit plugin site
> Select AffiliateWP - WooCommerce Redirect Affiliates	
> AffiliateWP - WooCommerce Redirect Affiliates
> Deactivate
> Redirect affiliates to their affiliate area when they login via WooCommerce's /my-account page
> 
> Version 1.0 | By Pippin Williamson and Andrew Munro | View details

Will send you a link via Help Scout to try in case it helps.

**Comment by sumobi** [comment]
@worldtravlr Thanks for the plugin list. With the Allow Own Referrals add-on installed I can replicate the cookies being stored for an inactive affiliate. @michaelbeil do you also have that add-on installed on your test set up?

**Comment by sumobi** [comment]
Issue is being caused by the `affwp_tracking_is_valid_affiliate` filter. It's returning `true` so would explain why visits are stored for inactive affiliates, thus leading to a referral being created.

**Comment by sumobi** [comment]
Will push out an update for the Allow Own Referrals add-on soon that blocks inactive affiliates. Leaving this ticket open until we get confirmation from @michaelbeil that he had Allow Own Referrals active.

**Comment by sumobi** [comment]
v1.0.2 update out for Allow Own Referrals in case anyone else has this issue:
https://wordpress.org/plugins/affiliatewp-allow-own-referrals/

**Comment by worldtravlr** [comment]
It takes you so long to fix issues.  You development cycle really needs to be sped up a lot :-)

Updated and getting -2 now.  Thanks!

**Comment by michaelbeil** [comment]
All gravy here with v1.0.2 of Allow Own Referrals active or inactive.
