### ISSUE TITLE
Allow site admins to see affiliate's submitted "Website URL" in Edit Affiliate screen

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1466]
PR: #1496 

I'm going through our own affiliates and there are a couple of things I've noticed regarding affiliate registration and the affiliate's submitted website URL:

1. The affiliate's website URL is not visible to the admin anywhere. I'm going through each affiliate and searching for them/their business, or using their email addresses to (hopefully) find their site where they have promoted/will promote our product. I know this is saved in the database somewhere, but it would be incredibly useful if this URL was visible on the affiliate's Edit screen. It could save admins a significant amount of time searching for affiliates' websites. This should be an editable field in case any spelling mistakes were made during the initial submission, or in case the URL where the site is promoted changes in the future. The website URL should also be able to be edited by the affiliate from the Affiliate Area, which then updates in the admin (again, in case it is correct or it changes).
2. Similarly, the website URL should be able to be entered when manually adding a new affiliate from the Add New Affiliate screen. If a site owner were to approach potential affiliates, or for some reason a new affiliate doesn't register through the registration form (they meet them offline for example), there is nowhere to capture where they will be promoting the product/site online.

It would allow site owners to be able to easily find their affiliates' websites. What do people think?

**Comment by michaelbeil** [comment]
Great idea! Currently, the website field is under **Contact Info** which is within the affiliate's WordPress user profile. 

Shouldn't be too hard to expose this on the affiliate edit screen and also add the website URL field to the Add New Affiliate screen.

**Comment by wordmaid** [comment]
Would definitely help to collect more affiliate website URLs! And if they haven't provided a URL initially, and we find them another way, it would be useful to be able to enter it against their affiliate info in the Edit Affiliate screen.

**Comment by michaelbeil** [comment]
Agreed.

**Comment by DrewAPicture** [comment]
Related: #873

**Comment by DrewAPicture** [comment]
Added a PR: #1496

**Comment by DrewAPicture** [comment]
With the new field:

![Website](https://cl.ly/3V0N1B352H40/1466_after.png)

**Comment by michaelbeil** [comment]
All checks out well. This PR can be merged.
