### ISSUE TITLE
Show "How will you promote us?" response from affiliate registration form in Edit Affiliate screen

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1467]
Similar to https://github.com/AffiliateWP/AffiliateWP/issues/1466, it could be useful to show the "How will you promote us?" field response from the affiliate registration form in the Edit Affiliate screen. This would help admins follow up on affiliates' website/social media efforts, personalize check-ins with affiliates, and purely allow admins to see and remember how an affiliate is going to promote their site. 

To keep the Edit screen tidy, it could be an expandable option titled "Promotion method(s)" or something similar, with a "Click to view" link that then displays the affiliate's submitted promotion methods. If the field isn't required (which it isn't by default), nothing would be saved in this field and nothing would show in the Edit screen. I don't think this should be able to be edited by affiliates, but perhaps can be changed by admins.

Thoughts from the team?

**Comment by pippinsplugins** [comment]
Yes, I've wanted to see it before too. Right now it's only visible on the review screen and if you want to go back and look at an account after it's approved, the info is not accessible.

Let's add it.

**Comment by DrewAPicture** [comment]
I think initially, simply displaying the value of the field should suffice. If we later want to make it editable, that's simple enough.

Added a PR: #1731.

Screenshot:
![new field](https://cl.ly/000e0t1C3c11/Screen%20Shot%202016-10-20%20at%2010.11.35%20AM.png)

**Comment by pippinsplugins** [comment]
Looks good to me.

**Comment by wordmaid** [comment]
🙀 Yay!!
