### ISSUE TITLE
Ability to add Notes against affiliates

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1468]
It would be great to be able to store notes against affiilates which are only visible to site admins. This could be a simple text area in the Edit Affiliate screen titled "Notes".

This could be used for: 
1. Promotion methods if the affiliate has been manually added
2. To store any specific payout information
3. Storing additional website URLs where the affiliate promotes the site owner's website, other than the primary URL
4. Storing links to social media accounts
5. Storing the affiliate's private contact details, such as phone number
6. Making notes regarding the affiliate for other site admins to be aware of
7. Making personal notes regarding the affiliate.

The possible uses are almost endless!

**Comment by pippinsplugins** [comment]
This would be especially great for hands-on affiliate managers.

We could easily store notes in the meta table with one note per row.

**Comment by sumobi** [comment]
@AffiliateWP/core Ready for testing (I have tested)

**Comment by sumobi** [comment]
Oops, forgot to add it to the add affiliate screen

**Comment by sumobi** [comment]
Reduced the height of the textarea by half.

<img width="1197" alt="screen shot 2016-12-10 at 5 38 17 pm" src="https://cloud.githubusercontent.com/assets/52581/21076682/d2c2574e-beff-11e6-9344-2a3171a1d55c.png">

**Comment by pippinsplugins** [comment]
All works well here!

**Comment by pippinsplugins** [comment]
The `test_add_affiliate_with_notes()` test is failing but I can't see why. Notes definitely get recorded during the affiliate creation (at least in the UI).

**Comment by DrewAPicture** [comment]
@pippinsplugins I don't see any logic in `affwp_add_affiliate()` for actually setting the `notes` data in meta. Only in `affwp_update_affiliate()`. I think the test is failing because the data is actually never getting written.

**Comment by pippinsplugins** [comment]
@DrewAPicture it's done by hooking into `affwp_insert_affiliate`. See `affwp_process_add_affiliate_meta()`

**Comment by DrewAPicture** [comment]
In that case, the action is never firing because admin/affiliates/actions.php is never loaded during the test run (it's only loaded on the affiliates admin screens. So we'll have to bring in the file for that action to fire.

**Comment by DrewAPicture** [comment]
1eb62c0 should fix it.

**Comment by pippinsplugins** [comment]
Ah!
