### ISSUE TITLE
Debug assistant constantly shows messages about utf8mb4

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1469]
Latest master branch.

Every time I reload the page while in the Debug assistant I see these same lines being repeated which quickly fills up the logs:

2016-7-24 00:55:33 - The character set for the wp_77_affiliate_wp_affiliatemeta table was successfully upgraded to utf8mb4.
2016-7-24 00:55:33 - The character set for the wp_77_affiliate_wp_affiliates table was successfully upgraded to utf8mb4.
2016-7-24 00:55:33 - The character set for the wp_77_affiliate_wp_creatives table was successfully upgraded to utf8mb4.
2016-7-24 00:55:33 - The character set for the wp_77_affiliate_wp_referrals table was successfully upgraded to utf8mb4.
2016-7-24 00:55:33 - The character set for the wp_77_affiliate_wp_visits table was successfully upgraded to utf8mb4.

![screen shot 2016-07-24 at 12 57 58 pm](https://cloud.githubusercontent.com/assets/52581/17081093/4e718114-519e-11e6-9da1-05a6a152f095.png)

**Comment by DrewAPicture** [comment]
@sumobi This is due to the upgrade routine continually being triggered because the plugin version is still 1.8.5. In the short term before we release 1.8.6, you can simply change the `$version` string to 1.8.6 to avoid this.

**Comment by DrewAPicture** [comment]
Per #1479, we're going to revert the schema change for 1.8.6. Let's centralize any related stuff in the other issue.
