### ISSUE TITLE
Visits/cookies not being stored with fallback tracking/pretty URLs/campaigns

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1470]
To replicate:

- Master branch
- Enable "Use Fallback Referral Tracking Method?" option in Settings -> Misc

## Issue 1: 

PR: #1472 

When fallback tracking is enabled & pretty affiliate URLs are used, referral links generated within the Affiliate Area that include a "campaign" do not work. They don't store any cookies, which means no visit stored.

The pretty URLs generated in the Affiliate Area when using a campaign look like this:

http://mysite.com/ref/john?campaign=test

However, this URL works (note the forward slash after john):

http://mysite.com/ref/john/?campaign=test

With fallback tracking **disabled**, both variations work as expected:

http://mysite.com/ref/john?campaign=test
http://mysite.com/ref/john/?campaign=test

Clue:

If you turn on debugging you'll see this error log message when using the URL above that doesn't store a visit:

> No user account found for given affiliate ID or login during get_fallback_affiliate_id()

https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/class-tracking.php#L440

## Issue 2 (related)

When a custom slug is used (via the Custom Affiliate Slugs add-on) with a pretty URL, and with fallback tracking enabled, visits are not being stored. 

E.g. http://mysite.com/ref/mycustomslug

Same log message:

> No user account found for given affiliate ID or login during get_fallback_affiliate_id()

I suspect it's related to the same issue. Without a pretty URL, it stores a visit + cookies fine.

E.g. http://mysite.com/?ref=mycustomslug

@pippinsplugins @DrewAPicture Can we please give this some attention as soon as possible?

**Comment by pippinsplugins** [comment]
`http://mysite.com/ref/john?campaign=test` fails because we split the URL on `/`:
```
var path = window.location.pathname.split( '/' );
$.each( path, function( key, value ) {
	if( AFFWP.referral_var == value ) {
		ref = path[ key + 1 ];
	}
});
```
Since there is no `/` after the referral var, `ref` is never found.

**Comment by sumobi** [comment]
👍

**Comment by DrewAPicture** [comment]
Added a PR for the first part: #1472. I think since we need to be able to reliably split on `/`, the best option is to just ensure that a trailing slash is present after the referral var value in generated links.

**Comment by sumobi** [comment]
@DrewAPicture 👍 

That fixes the immediate problem of URLs being generated but I feel we still need to tackle the issue somehow. Not everyone is going to use the URL generator, or might have links posted around the web that are still going to be broken.

**Comment by DrewAPicture** [comment]
@sumobi Fair enough. The complexity of parsing URLs in JS certainly leaves something to be desired. We've seen this problem other places where visits aren't tracking (and therefore referrals not being created) because of an omitted trailing slash.

**Comment by sumobi** [comment]
@DrewAPicture Yeah, sounds like a challenge for sure 👍 

>  We've seen this problem other places where visits aren't tracking (and therefore referrals not being created) because of an omitted trailing slash.

Issue link? I haven't seen this before I don't think

IMO it's a bit sad if we provide customers with this magical "fallback tracking" option because their site has JS errors, but have them discover that fallback tracking itself is crippled in some way with certain URL structures. If URLs work without fallback tracking, they should also work with fallback tracking. Hopefully we can find a way :)

**Comment by DrewAPicture** [comment]
> Issue link? I haven't seen this before I don't think

I can't pinpoint one right now. I know there's been one or two related to fault regex patterns expecting trailing slashes.

**Comment by DrewAPicture** [comment]
@sumobi Your second issue seems to work fine and generate cookies/visits just fine. Can you please retest?

**Comment by pippinsplugins** [comment]
I've found a simple (if kind of dirty) approach that resolves the issue with `/ref/jimbo?campaign=test`: https://github.com/AffiliateWP/AffiliateWP/pull/1472/commits/b385d7c1d832da7cd391a05aea213fa1c88a2527

**Comment by michaelbeil** [comment]
That works well.

**Comment by pippinsplugins** [comment]
@sumobi could you test as well please?

@DrewAPicture any issues with this method?

**Comment by sumobi** [comment]
@pippinsplugins works great for me. I'm a bit nervous about the "dirty" approach. Desperately awaiting @DrewAPicture's feedback :)

**Comment by pippinsplugins** [comment]
Nah it's pretty simple really.

**Comment by DrewAPicture** [comment]
It's definitely clever. Short of rewriting `wp_parse_url` in JS this could work pretty well. Do we have tests that show this won't break anything?

**Comment by pippinsplugins** [comment]
Nothing but manual tests at the moment. So far I haven't found any problems.

**Comment by pippinsplugins** [comment]
Merged into `release/1.9`.

**Comment by sumobi** [comment]
Haven't found any issues either so far.

**Comment by pippinsplugins** [comment]
Going to close.

**Comment by michaelbeil** [comment]
Retested in `release/1.9` and all is still gravy.
