### ISSUE TITLE
Pretty affiliate URLs don't work with Ultimate Member

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1471]
Pretty affiliate URLs don't seem to work with Ultimate Member member pages: https://ultimatemember.com

Normal profile URL
http://mysite.com/user/john/

Affiliate Link (does not work)
http://mysite.com/user/john/ref/admin

Affiliate link with non-pretty URL (works)
http://mysite.com/user/john/?ref=admin

Flushing permalinks via Settings -> permalinks screen, re-saving the first tab of the AffiliateWP settings page, or deactivating/activating any plugins has no effect.

**Comment by DrewAPicture** [comment]
@sumobi I don't think we have an integration for Ultimate Member. Do we?

**Comment by pippinsplugins** [comment]
We support it through the Signup Referrals add-on (I think) and through the generic tracking script.

It's also pretty common for Ultimate Member to be used on a site along with WooCommerce or another membership plugin.

**Comment by sumobi** [comment]
@DrewAPicture Correct, no full integration but definitely something we should support.
@pippinsplugins Correct, signup referrals supports it.

**Comment by DrewAPicture** [comment]
@sumobi Oh I see what you're saying. On my first read I was under the impression that we weren't tracking on an Ultimate Member-specific URL so I was confused about how we'd add a special case in lieu of an integration. I'll work getting User pages to work.

**Comment by DrewAPicture** [comment]
@AffiliateWP/core OK, so we want to handle a special case for /user/username pages in lieu of an integration for Ultimate Member. Do we have a protocol for where to handle special cases if there's no integration?

**Comment by sumobi** [comment]
We could add it here? All in favor?
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/plugin-compatibility.php

**Comment by pippinsplugins** [comment]
I cannot for the life of me make this work.

**Comment by pippinsplugins** [comment]
@DrewAPicture and I spent some time on this while he was in KS and both decided it's simply too much work to get resolved right now. Best approach for now is to probably open a bug report with Ultimate Member to see if they can help address it in any way. Our endpoints _should_ work every where but they're getting stomped out.

**Comment by jdiaz1302** [comment]
I know this one is old, but did it come to work? can I use both plugins? with Ultimate Member I have disabled the profile pages for users because my only interest is using the account page so I was going to create a tab with the affiliate shortcodes I was looking for more information between both products but I guess that this is a dead end... Any advice?

**Comment by pippinsplugins** [comment]
@jdiaz1302 we did not find a resolution for this conflict.

You can still use both plugins you just can't use pretty affiliate URLs on the profile pages.

For example, this URL will not work: members/profile/member-name/ref/1

This URL will work: members/profile/member-name/?ref=1
