### ISSUE TITLE
Referrals export: Commas within description cell cause column misalignment

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#1473]
If there are comma-separated strings in the `description` column cells, this causes some applications to interpret those commas as column breaks, which messes up formatting.

For example, adding multiple WooCommerce product references to a referral `description` causes this issue.

The misalignment can be seen in the OSX `Numbers` app, but I'm guessing it's in others as well.

While not specific to the `description` column alone, it's the only one reported at this time as being a cause of issues for customers. Because of this, I'll restrict this adjustment to `description`.

_(PR forthcoming)_

Related: https://secure.helpscout.net/conversation/231335406/38793/?folderId=297160

**Comment by ramiabraham** [comment]
PR: #1474

**Comment by ramiabraham** [comment]
Re-opening as I acutually fixed a symptom here, not the cause. The root cause can be a variety of html entities. Most recently, any `<span>` within a csv cell will break formatting in _Google Sheets_ and _Apple Numbers_.

**Comment by ramiabraham** [comment]
Related: https://secure.helpscout.net/conversation/265645932/0/

**Comment by pippinsplugins** [comment]
Here's what we do in EDD core for each column:
```php
$row_data .= '"' . addslashes( preg_replace( "/\"/","'", $column ) ) . '"';
```

**Comment by DrewAPicture** [comment]
@pippinsplugins So would you like to add slashing for all the columns in this use-case or just the description? PR #1867 simply adds slashing for the description only.

**Comment by pippinsplugins** [comment]
@DrewAPicture let's do all columns.

**Comment by DrewAPicture** [comment]
@pippinsplugins Updated the PR to slash all columns.
