### ISSUE TITLE
Emails not sending to admin or affiliate when new user/affiliate is added

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1489]
Emails don't appear to be sending to either admin or affiliate when a new user/affiliate is added:

![screen shot 2016-08-01 at 4 28 07 pm](https://cloud.githubusercontent.com/assets/52581/17283482/27b24f82-5805-11e6-8b32-fb2f395270fb.png)

I could have sworn these used to work, we even have the option to disable the email sent to the affiliate

**Comment by sumobi** [comment]
Customer reports that the issue is fixed now, they were checking the option to disable email. However, I still can't see the emails. Leaving open until I can do some more testing. Working for everyone else? @AffiliateWP/core

**Comment by sumobi** [comment]
It looks like emails are semi-broken in `master`. The admin email sends but not the affiliate's registration email. Switching to the official 1.8.5 release sends the email.

**Comment by DrewAPicture** [comment]
Introduced in and readdressing in #1444. Closing in favor of that.
