### ISSUE TITLE
"affiliate referral rate" email tag

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1490]
I'd like to propose an "affiliate referral rate" email tag as suggested by a customer:

https://github.com/AffiliateWP/affiliatewp-code-snippet-library/blob/master/emails/email-tag-affiliate-referral-rate.php

An affiliate's referral rate could obviously change based on **many** factors (Tiered Affiliate Rates, per-product per-affiliate rates etc) however showing an affiliate their initial "base referral rate" could be very beneficial when sending the affiliate registration "accepted" email. Similar to how when advertising your affiliate program initially you should always show potential affiliates how much they could earn.

**Comment by michaelbeil** [comment]
I like this.

**Comment by sumobi** [comment]
@AffiliateWP/core Ready for testing

Tested with percentage and flat rate. Decided to shorten email tag to {referral_rate} so it's consistent with the existing {referral_url} email tag.

![screen shot 2016-08-08 at 10 43 59 am](https://cloud.githubusercontent.com/assets/52581/17465870/704daa20-5d55-11e6-87e4-cf6a500f9e5a.png)

![screen shot 2016-08-08 at 10 42 13 am](https://cloud.githubusercontent.com/assets/52581/17465869/704ae2fe-5d55-11e6-94cb-f02497bf9ad7.png)

**Comment by michaelbeil** [comment]
Looks good here!
