### ISSUE TITLE
Refreshing admin page sends affiliate another email

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1494]
Testing with latest master. Multiple emails can be sent via the admin by refreshing the page after performing an action.

Example: 

1. Turn on affiliate approval
2. Accept an affiliate
3. Reload the page 

After each reload it will send an affiliate accepted email to the affiliate.

URL shown:

    http://affiliate-forms-ninja-forms.affwp.dev/wp-admin/admin.php?page=affiliate-wp-affiliates&affwp_notice=affiliate_accepted&action=accept&affiliate_id=35&_wpnonce=5b2ed247c4

**Comment by DrewAPicture** [comment]
Added a PR: #1495 

![Magic](https://cl.ly/2P430P1e1M3k/magic.gif)

**Comment by sumobi** [comment]
@DrewAPicture Works great. I especially like how the query arg disappears after clicking an action link.
