### ISSUE TITLE
Collect usage information

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1498]
We talked about this during a recent meeting though I can't find an issue on it. 

Similar to EDD's opt-in, we could ask customers to "opt-in and help make AffiliateWP better". We would collect useful information such as integrations enabled etc.  

This could be included during the on-boarding process (https://github.com/AffiliateWP/AffiliateWP/issues/1381) or available to opt-in to from another location.

**Comment by pippinsplugins** [comment]
Started building the plugin to collect the data: https://github.com/AffiliateWP/affwp-usage-tracking

**Comment by michaelbeil** [comment]
👍

**Comment by pippinsplugins** [comment]
We need to add payout counts and rest consumer counts to the site_data array.

**Comment by pippinsplugins** [comment]
@DrewAPicture Let me know if I can assist with getting this on the dev site.

**Comment by pippinsplugins** [comment]
I've installed the usage tracking plugin on the dev site and this is ready for further testing. To test:

1. checkout `issue/1498`
2. Enter `70263a0aec20acf459e28fc79e117121` for your license key
3. Install [Transient Manager](https://wordpress.org/plugins/transients-manager/)
3. Navigate to `Tools` > `Transients` and delete the transient called `affwp_license_check`. This will trigger the check in.
4. Go to http://dev.affiliatewp.com/wp-admin/edit.php?post_type=download&page=affwp-usage-tracking&tab=general and see if your check in was reported successfully.
5. Now go to Plugins and activate or deactivate a plugin.
6. Go back to Tools > Transients and delete `affwp_check_license` to trigger another transient.
7. Go to http://dev.affiliatewp.com/wp-admin/edit.php?post_type=download&page=affwp-usage-tracking&tab=sites and confirm your site data was updated with the new plugin count.
8. Go to the `Logs` page for your site and confirm the log entries are there.

**Comment by ramiabraham** [comment]
Performed for affwp.dev; data confirmed

**Comment by michaelbeil** [comment]
Everything works well!

**Comment by pippinsplugins** [comment]
Thanks for testing! I'm going to merge and close.
