### ISSUE TITLE
&action=edit being stripped from post edit links

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1504]
The changes made on https://github.com/AffiliateWP/AffiliateWP/issues/1494 are affecting other areas of the admin. E.g. when editing a post or page `/post.php?post=1&action=edit` the `&action=edit` is being stripped off the end.

Related ticket:
https://secure.helpscout.net/conversation/234455207/39306/?folderId=205524

**Comment by DrewAPicture** [comment]
PR: #1505 

PR takes a much more conservative approach to stripping query args, namely only stripping admin notices and _wpnonce, and only on admin.php (which all AffWP admin files live within). The various AffWP admin screens rely on the `_wpnonce` value to proceed, so removing it following successful execution should properly address the original problem reported in #1494
