### ISSUE TITLE
Remove extra plugins list table inline update row in 4.6+

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1507]
Noticed yesterday that the "There is a new version of AffiliateWP" inline message in the plugins list table was being displayed twice. Once, unstyled, by AffWP, and again styled by core. Turns out, this is handled now as part of Shiny Updates so we can essentially skip adding the extra table row in 4.6+.

This part specifically can be skipped:
```php
		if ( ! empty( $update_cache->response[ $this->name ] ) && version_compare( $this->version, $version_info->new_version, '<' ) ) {

			// build a plugin list row, with update notification
			$wp_list_table = _get_list_table( 'WP_Plugins_List_Table' );
			echo '<tr class="plugin-update-tr"><td colspan="' . $wp_list_table->get_column_count() . '" class="plugin-update colspanchange"><div class="update-message">';

			$changelog_link = self_admin_url( 'index.php?edd_sl_action=view_plugin_changelog&plugin=' . $this->name . '&slug=' . $this->slug . '&TB_iframe=true&width=772&height=911' );

			if ( empty( $version_info->download_link ) ) {
				printf(
					__( 'There is a new version of %1$s available. %2$sView version %3$s details%4$s.', 'affiliate-wp' ),
					esc_html( $version_info->name ),
					'<a target="_blank" class="thickbox" href="' . esc_url( $changelog_link ) . '">',
					esc_html( $version_info->new_version ),
					'</a>'
				);
			} else {
				printf(
					__( 'There is a new version of %1$s available. %2$sView version %3$s details%4$s or %5$supdate now%6$s.', 'affiliate-wp' ),
					esc_html( $version_info->name ),
					'<a target="_blank" class="thickbox" href="' . esc_url( $changelog_link ) . '">',
					esc_html( $version_info->new_version ),
					'</a>',
					'<a href="' . esc_url( wp_nonce_url( self_admin_url( 'update.php?action=upgrade-plugin&plugin=' ) . $this->name, 'upgrade-plugin_' . $this->name ) ) .'">',
					'</a>'
				);
			}

			do_action( "in_plugin_update_message-{$file}", $plugin, $version_info );

			echo '</div></td></tr>';
		}
```

I didn't look too deeply into the `show_update_notification()` method, but there's probably even more unnecessary.

**Current view in 4.6 RC 2:**

![RC2](https://cl.ly/2b26241n1n0e/1507_rc2.png)

**With [core patch](https://core.trac.wordpress.org/ticket/37504) that fixes styling:**

![Patch](https://cl.ly/1x0h1I0M0N04/1507_with_patch.png)

**With the skipped extra table row:**

![Skipped code](https://cl.ly/2k1m1u172i21/1507_skipped.png)

**Comment by michaelbeil** [comment]
Related: https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/271

**Comment by michaelbeil** [comment]
Also related: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4830

**Comment by pippinsplugins** [comment]
Along with this, some styling is missing from our add-on update notices:
![screen shot 2016-09-02 at 9 47 48 am](https://cloud.githubusercontent.com/assets/1034109/18207824/5f87a3fc-70f2-11e6-9e70-ac50cb1e0413.png)

**Comment by pippinsplugins** [comment]
Fixed:
![screen shot 2016-09-02 at 9 52 15 am](https://cloud.githubusercontent.com/assets/1034109/18207951/f6687404-70f2-11e6-9dba-73ad029dbf48.png)

**Comment by ramiabraham** [comment]
Looks good, identical appearance here.

**Comment by michaelbeil** [comment]
Looks as expected.
