### ISSUE TITLE
AFFILIATE_WP_LICENSE_KEY -> AFFILIATEWP_LICENSE_KEY

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1514]
PR: #1515

Let's change `AFFILIATE_WP_LICENSE_KEY` to `AFFILIATEWP_LICENSE_KEY`. 

Internal functions/classes are ok with the space but front-facing text (shown in admin settings) should be consistent and reflect the real company/product name.

**Comment by DrewAPicture** [comment]
PR: #1515
