### ISSUE TITLE
Implement factory methods and static fixtures for all the tests

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1520]
Using the factories implemented in #1516, implement said referral factory in referral tests.

**Comment by pippinsplugins** [comment]
Fantastic!

**Comment by DrewAPicture** [comment]
@pippinsplugins I think we're ready to go here.

Note to self: I'll need to update the payout tests on #471 to match once this is merged to release/1.9.

**Comment by pippinsplugins** [comment]
Looks great, merged!
