### ISSUE TITLE
revoke_referral_on_void method missing from Sprout Invoices integration

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1526]
There's a `revoke_referral_on_void` method being referenced from the action, but no method present in the integration file.

https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-sproutinvoices.php

**Comment by sumobi** [comment]
Looks like should be `revoke_referral_on_void ` should be `revoke_referral_on_refund`

**Comment by DrewAPicture** [comment]
Looks good.
