### ISSUE TITLE
Make admin copy consistent

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1531]
@AffiliateWP/core 

I'd like to see a full audit of AffiliateWP's current admin copy for consistency. We have some settings that ask questions, and some that don't. We should do it one way or the other (and match it for future settings)

Examples:

![screen shot 2016-08-10 at 6 26 49 pm](https://cloud.githubusercontent.com/assets/52581/17543936/36d9aa62-5f28-11e6-9d44-23f615e07ea6.png)

![screen shot 2016-08-10 at 6 28 54 pm](https://cloud.githubusercontent.com/assets/52581/17543959/5429a0c2-5f28-11e6-81a4-042c69b45dbe.png)

IMO I've never seen the WordPress UI ask a question so I think they should not be questions also.

Examples:

Old:
Should affiliates be able to register accounts for themselves?

New:
Affiliates will be able to register accounts

Old:
Require that site admins approve affiliates before they can begin earning referrals?

New:
Require that site admins approve affiliates before they can begin earning referrals

Old:
Automatically register new users as affiliates?

New:
Automatically register new users as affiliates

Old:
Should taxes be excluded from referral calculations?

New:
Exclude tax from referral calculations

@wordmaid interested?

**Comment by fxbenard** [comment]
+1

**Comment by pippinsplugins** [comment]
:+1:

**Comment by michaelbeil** [comment]
@sumobi did you mean to remove the `?` here?
 
New:
Exclude tax from referral calculations`?`

New:
Exclude tax from referral calculations` `

**Comment by sumobi** [comment]
@michaelbeil Yep yep :) Updated

**Comment by michaelbeil** [comment]
👍

**Comment by wordmaid** [comment]
@sumobi Absolutely!

**Comment by pippinsplugins** [comment]
@wordmaid think you could add this to your todo list for later this week or next?

**Comment by wordmaid** [comment]
Yep, can do

**Comment by DrewAPicture** [comment]
@wordmaid What's the status here? Punting to 1.9.6.

**Comment by wordmaid** [comment]
Mostly done but not completed yet - can have it done sooner if needed, otherwise will ensure it is ready for 1.9.6.

**Comment by wordmaid** [comment]
Added PR, if someone could please check it that would be great!

**Comment by pippinsplugins** [comment]
Pr looks great to me! Merging.
