### ISSUE TITLE
Switch out the Iranian Toman for the Rial

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1534]
We added the Iranian Toman in  #1486. 

I think we should switch out the Toman for the Rial which is the official currency of Iran and has a Unicode entity of `&#65020;`.

**Comment by michaelbeil** [comment]
Related: #718

**Comment by DrewAPicture** [comment]
See also https://github.com/AffiliateWP/AffiliateWP/issues/718#issuecomment-236308877

**Comment by michaelbeil** [comment]
Right, I saw that. Technically the Rial is the currency of Iran. The Toman is talked about in conversation, but the actual national currency is the Rial.

**Comment by DrewAPicture** [comment]
@michaelbeil Looks good.

**Comment by michaelbeil** [comment]
Alrighty then 😎
