### ISSUE TITLE
Use a friendlier date + time format in the visits tab.

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1536]
PR: #1537

**Before:**
![Before](https://cl.ly/310U1t03062u/Screen%20Shot%202016-08-10%20at%205.00.50%20PM.png)

**After:**
![After](https://cl.ly/1W3Q0u3e2E0a/Screen%20Shot%202016-08-10%20at%205.00.02%20PM.png)

**Comment by DrewAPicture** [comment]
Added a PR: #1537

**Comment by pippinsplugins** [comment]
Looks good.

**Comment by michaelbeil** [comment]
This is great!
