### ISSUE TITLE
Remove fixed-width labels from forms

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1538]
We should remove fixed-width `label`'s from AffiliateWP's front-end forms. Similar to https://github.com/restrictcontentpro/restrict-content-pro/issues/251

We can provide a CSS code snippet if anyone feels like it breaks their site.

**Comment by sumobi** [comment]
CSS hasn't been minified so make sure you have `SCRIPT_DEBUG` set to `true`

Ahhhh, so much better :D

<img width="903" alt="screen shot 2016-12-08 at 9 27 28 pm" src="https://cloud.githubusercontent.com/assets/52581/21035482/72a14942-bd8d-11e6-9f80-9245c329e7ad.png">

___

As we know WP 4.7 has the CSS editor so if anyone wants it back the way it was they can add these lines to the customizer (we should document this):

```
.affwp-form textarea,
.affwp-form input[type="text"],
.affwp-form input[type="password"],
.affwp-form input[type="email"],
.affwp-form input[type="url"] {
	display: inline-block;
	width: 200px;
}

.affwp-form label {
	display: inline-block;
	width: 200px;
}
```

**Comment by sumobi** [comment]
@AffiliateWP/core anyone want to test?

**Comment by pippinsplugins** [comment]
I'm good with this.

**Comment by pippinsplugins** [comment]
Looks great to me.
