### ISSUE TITLE
Amount Sanitize function not correct

### ISSUE THREAD

**Issue by jaredatch** [AffiliateWP/AffiliateWP#1543]
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/misc-functions.php#L109

The regex is incorrect and removes any commas, which then makes most of the logic after it useless ;)

Not sure why, but this function is different than EDD's version (which works correctly)

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/formatting.php#L24

**Comment by DrewAPicture** [comment]
@jaredatch Can you possibly provide more information about input and output and your expectations for how that should work? I'm asking because tests for all covered cases appear to pass whether we change the function or not. Either way, comma removal happens both in the AffiliateWP and EDD versions alike.

**Comment by DrewAPicture** [comment]
See #1567 for tests.

**Comment by jaredatch** [comment]
I think it's because the unit testing isn't doing non-USD formatted currencies, which is when I started running into the issues.

EDD runs the preg replace after sep logic runs. AffWP runs it before the sep logic, which then invalidates that logic. The logic is looking for commas, but they will never be found since they are stripped already.

`edd_sanitize_amount( '77,00' )` returns `77.00` which is correct.

`affwp_sanitize_amount( '77,00' )` returns `7700.00` which is incorrect.

Let me know if this makes sense. I ran into this when testing those functions on the EURO which have the thousand/decimal sep switched.

**Comment by pippinsplugins** [comment]
I don't think `77,00` should come back as `77.00` when the thousands separator is `,`. The `,` would indicate a thousand so `7700.00` would be correct.

Opinions?

**Comment by michaelbeil** [comment]
If the thousands separator is set to `,` then the way `affwp_sanitize_amount()` seems to be working just fine IMHO.

**Comment by jaredatch** [comment]
I'm referring to when it's setup so for currency to support XX.XXX,XX format (revered separators of USD).

If the decimal sep is `,` and the thousands sep is `.` then the sanitized value of `77,00` should be `77.00`?

**Comment by pippinsplugins** [comment]
>>>If the decimal sep is , and the thousands sep is . then the sanitized value of 77,00 should be 77.00?

I agree.

**Comment by michaelbeil** [comment]
PR looks good.
