### ISSUE TITLE
User migration tool only migrates the first 100 users

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1545]
To better debug this class, we should add some logging.

**Comment by DrewAPicture** [comment]
This needs testing. An easy way to do it is to use WP-CLI to generate some users for migration:

```bash
wp user generate --count=250
```

Then run the migration script and ensure the selected users were migrated. It needs to be more than 100 users to confirm the fix.

**Comment by DrewAPicture** [comment]
For anybody following the original issue, it was converted to a bug fix for the user migration script.

**Comment by michaelbeil** [comment]
All fixed.

**Comment by michaelbeil** [comment]
Works well here. Seems good to merge.

**Comment by ramiabraham** [comment]
_(Possibly related: https://secure.helpscout.net/conversation/243212169/0/)_
