### ISSUE TITLE
Major spike (+/-100) in database queries

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1548]
> I also noticed a similar spike (+/-100) when using `if( ! ( affwp_is_affiliate() && affwp_is_active_affiliate() )` a while back that I haven't reported yet.

Reported here: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4873.

**Comment by DrewAPicture** [comment]
For what it's worth, in 1.9+, the `affwp_is_affiliate()` call can be skipped altogether since `$affiliate` was made optional in `affwp_get_affiliate()`, defaulting to the current affiliate.

**Comment by pippinsplugins** [comment]
@DrewAPicture could you review this to determine if the spike is indeed there?

**Comment by DrewAPicture** [comment]
I tested a whole bunch of front end and back end flows with extensive numbers of core objects (and no caching) and I wasn't seeing anything spiking outside the norm. Happy to continue investigation, but I don't see anything in the immediate vicinity.
