### ISSUE TITLE
Add {landing_page} email tag

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1552]
I'd like to propose a {landing_page} (any suggestions on name?) email tag. 

This is for the referral notification email so the affiliate can see where the original point of entry was by the customer, before the referral was awarded to them which is quite useful.

This is the URL we show in the `URL` column of the `Visits` tab of the Affiliate Area:

![screen shot 2016-08-20 at 12 41 19 pm](https://cloud.githubusercontent.com/assets/52581/17827593/7a27772e-66d3-11e6-82c4-1351a801abd6.png)

In the admin we call this the `Landing Page`.

![screen shot 2016-08-20 at 12 44 04 pm](https://cloud.githubusercontent.com/assets/52581/17827611/d62ed36e-66d3-11e6-92af-9852ccdfccfb.png)

Working code snippet to test:

    /**
     * Add a new {landing_page} email tag.
     * This is the URL that the customer landed on before a referral was created
     */
    function affwp_email_tag_landing_page( $email_tags, $this ) {

       $email_tags[] = array(
           'tag'         => 'landing_page',
           'description' => 'The landing page',
           'function'    => 'affwp_email_tag_get_landing_page'
       );

       return $email_tags;

    }
    add_filter( 'affwp_email_tags', 'affwp_email_tag_landing_page', 10, 2 );

    /**
     * Get the landing page of the referral
     */
    function affwp_email_tag_get_landing_page( $affiliate_id = 0, $referral ) {
	    return esc_url( affiliate_wp()->visits->get_column_by( 'url', 'visit_id', $referral->visit_id ) );
    }

**Comment by pippinsplugins** [comment]
I love this idea.

**Comment by pippinsplugins** [comment]
@sumobi ready for testing.

**Comment by pippinsplugins** [comment]
Merging for beta but leaving open in case @sumobi or @michaelbeil find an issue with it.

**Comment by sumobi** [comment]
Just one minor thing so far ^

**Comment by sumobi** [comment]
@pippinsplugins works great here

**Comment by pippinsplugins** [comment]
Good change

**Comment by michaelbeil** [comment]
Looks good after the description change.
