### ISSUE TITLE
Restrict Content Pro: Referral amounts don't take coupons into account

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1555]
When a sale is made with a coupon (regular code or affiliate discount code), the referral amount is calculated off of the subscription price (before coupons). It should definitely be after coupons, until we add an option to specify which should be used. 

Restrict Content Pro 2.6.6
AffiliateWP 1.8.7

Steps to reproduce:
1. Set up a new subscription in RCP and set its price to $199.
2. Set the subscription's referral rate to 25%
3. Create a coupon code in RCP for 30% off 
## Expected result - $34.75 referral

199 - (199 \* .3) = $139.30 total
25% of $139.30 = $34.75 referral
## Actual result - $49.75 referral

This is what is happening:

25% of $199 = $49.75

`$amount = $this->calculate_referral_amount( $price, $key, absint( $_POST['rcp_level'] ) );`

The referral isn't being based on the subscription price minus the discount. I can replicate this locally.

**Comment by michaelbeil** [comment]
This seems to be fixed in a recent branch on RCP' side: https://github.com/restrictcontentpro/restrict-content-pro/issues/668

**Comment by michaelbeil** [comment]
After running further tests, the referral is calculated off of the discounted total as expected.

**Comment by pippinsplugins** [comment]
Sweet, closing as fixed then!

**Comment by michaelbeil** [comment]
Should we remove the milestone?

**Comment by pippinsplugins** [comment]
Yep

**Comment by michaelbeil** [comment]
Ok. Removed from 1.9.

**Comment by gspice** [comment]
This is still happening, or is re-broken, not sure.  Reported by Paul Jarvis originally, he sent it again on another ticket: 
https://secure.helpscout.net/conversation/355061275/58052/?folderId=1170842

Restrict Content Pro 2.8.5
AffiliateWP 2.0.7

Steps to reproduce using values from Paul's ticket, used the sandbox site for RCP:  http://s14890.p27.sites.pressdns.com/rcp/

1. Set affiliate's rate to 50%
2. Created a coupon code for flat amount of $50.
3. Left the subscription's referral rate to default.
4. Purchased the Gold $100 membership using the $50 discount

## Expected result - $25.00 referral

100 - 50 = $50.00 total
50% of $50.00 = $25.00 referral
## Actual result - $50.00 referral

I tested this against WooCommerce and EDD using the same setup and they correctly generated a $25.00 referral.

**Comment by pippinsplugins** [comment]
I've resolved this through the PR for #2194.
