### ISSUE TITLE
Bug in affwp_calc_referral_amount filter call

### ISSUE THREAD

**Issue by Tigzy** [AffiliateWP/AffiliateWP#1560]
Hello, 
in referral-functions.php, you have an extra parameter '$amount' that needs to be removed (commented here).

Also, it's missing the $rate value (added here)

```php
/**
 * Calculate the referral amount
 *
 * @param  string  $amount
 * @param  int     $affiliate_id
 * @param  int     $reference
 * @param  string  $rate
 * @param  int     $product_id
 * @return float
 */
function affwp_calc_referral_amount( $amount = '', $affiliate_id = 0, $reference = 0, $rate = '', $product_id = 0 ) {

	$rate     = affwp_get_affiliate_rate( $affiliate_id, false, $rate, $reference );
	$type     = affwp_get_affiliate_rate_type( $affiliate_id );
	$decimals = affwp_get_decimal_count();

	$referral_amount = ( 'percentage' === $type ) ? round( $amount * $rate, $decimals ) : $rate;

	if ( $referral_amount < 0 ) {
		$referral_amount = 0;
	}

	return (string) apply_filters( 'affwp_calc_referral_amount', $referral_amount, $affiliate_id, /*$amount,*/ $reference, /*added*/ $rate, $product_id );

}
```

**Comment by Tigzy** [comment]
Also I found another bug in class-woocommerce.php (includes/integrations): 
in add_pending_referral : 
2 get_products call are missing the order id arg, this breaks the affwp_calc_referral_amount filter later in the chain.

`$this->get_products( $order_id ),`

**Comment by michaelbeil** [comment]
@Tigzy sent this in a support ticket for usage reference:

```php
// Multi-currency support
add_filter( 'affwp_calc_referral_amount', 'affiliate_multi_currency', 10, 5 );

function affiliate_multi_currency($amount = '', $affiliate_id = 0,
        $reference = 0, $rate = '', $product_id = 0) {
        $order = new WC_Order($reference);

    // Get conversion rate for the order currency
    // We assume the affiliation currency is set to the default WooCommerce currency

        $currency_rate = '';
        $wcml_settings = get_option('_wcml_settings');

        if ( isset( $wcml_settings['currency_options'][$order->get_order_currency()] ) ) {
            $currency_rate = $wcml_settings['currency_options'][$order->get_order_currency()]['rate'];
        }
    
// Apply conversion rate
        if ( ! empty( $currency_rate ) ) {
                $amount = $amount / $currency_rate;
            }
            return $amount;
}
```

**Comment by Tigzy** [comment]
Yes, it's the code I'm using for multi currency support with WPML and that revealed the bugs above.

**Comment by pippinsplugins** [comment]
`$amount` isn't unused. It's the original amount passed to the function.

**Comment by Tigzy** [comment]
Please don't close, this is real bug. I'll give you more details for the first part.
Also, have you noticed the 2nd bug?

**Comment by Tigzy** [comment]
Ok, so I dont' remember why I wanted to remove the "amount" parameter, maybe I thought the prototype needed to be the same. The filter looks good, I'll change my implementation.

However could you look at the 2nd issue? The order id isn't passed down to the chain.

**Comment by pippinsplugins** [comment]
@Tigzy I'll look at the second bug but I"m going to open a new issue. Please keep github issues limited to 1 bug / enhancement per issue.

**Comment by pippinsplugins** [comment]
There's not a bug here. The `$order_id` parameter is ignored and only there to prevent PHP notices.

The order is set up inside of `add_pending_referral()` like this:
```php
$this->order = apply_filters( 'affwp_get_woocommerce_order', new WC_Order( $order_id ) );
```
`get_products()` then retrieves the items from the order like so:
```php
$items     = $this->order->get_items();
```
