### ISSUE TITLE
Remove What's New screen and redirect

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1562]
## Update: we've chosen to remove the page instead of updating it.

Primary items I believe should be highlighted:

- Better Reports
- Payout Logs
- REST API
- WooCommerce rates per variation
- PayPal integration
- WP CLI
- "Email Improvements" and list the new {referral_rate} and {review_url} email tags.
- "Affiliate registration improvements" which would list a summary of: #1008 and #947
- Development docs
- WP 4.4 required
- Gravity Forms Coupon tracking
- OptimizeMember integration

Add any you'd like covered.

**Comment by sumobi** [comment]
I'll list them here for now, but if we have room we could include a small section on "Email Improvements" and list the new {referral_rate} and {review_url} email tags.

**Comment by sumobi** [comment]
Another one "Affiliate registration improvements" which would list a summary of: https://github.com/AffiliateWP/AffiliateWP/issues/1008 and https://github.com/AffiliateWP/AffiliateWP/issues/947

**Comment by wordmaid** [comment]
I'd love to help by reviewing this when it's done!

**Comment by pippinsplugins** [comment]
Great!

**Comment by michaelbeil** [comment]
added @sumobi's suggestions to the list above for ease of groking.

**Comment by pippinsplugins** [comment]
Spent some time thinking on this today and I actually feel we should remove the welcome screen all together. I've seen a lot of feedback, especially from the WP development community, that the overall opinion of welcome screens that take over the plugin activation process is unwelcomed.

For that reason, I'm thinking we should remove this entirely.

The on-boarding benefits that this provides can still be handled (and greatly improved) through #1381 

Opinions?

**Comment by sumobi** [comment]
I'm not opposed to removing it. 

Any thoughts on how we could show existing customers who have just upgraded what's new? 

Are there any good examples of other plugins who don't show a what's new screen? If so, what do they do?

Perhaps it's as simple as adding a "changelog" link to the plugin screen links?

**Comment by sumobi** [comment]
Does that mean we also lose the credits and the other tab? Another option is to keep the what's new screen, but only show it when a link is clicked, rather than taking over the user's screen on upgrade etc.

**Comment by sumobi** [comment]
Crazy thought, a "what's new" link in the admin links under "affiliates" and then it disappears after you've visited the page.

**Comment by pippinsplugins** [comment]
I was thinking we'd remove the entire page, welcome and what's new, and I guess credits.

**Comment by michaelbeil** [comment]
I can the onboardinh process being more valuable than the What's new / welcome / credits screen, but what should we show instead? Do we not want to link the user to docs or our site in some shape or form? 

Well, I guess users can go to our site via the plugins screen.

**Comment by pippinsplugins** [comment]
My proposal is that we don't show anything, just like the majority of plugins behave.

**Comment by michaelbeil** [comment]
👌

**Comment by pippinsplugins** [comment]
PR #1624 removes it. We'll discuss showing anything on the Overview page during meeting today.

**Comment by michaelbeil** [comment]
🎉 👍

**Comment by pippinsplugins** [comment]
As discussed in meeting, we're going to add a `Changelog` link to the plugin action links.

**Comment by pippinsplugins** [comment]
Ready for testing:
![screen shot 2016-09-20 at 4 03 49 pm](https://cloud.githubusercontent.com/assets/1034109/18688866/daba063e-7f4b-11e6-8cc6-4184a9340d84.png)

**Comment by sumobi** [comment]
Oh yeah I like that

**Comment by michaelbeil** [comment]
Excellent!
