### ISSUE TITLE
Tracking ticket for updating addons to use Payouts

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1565]
* [x] Parent issue: #471
* [x] PayPal add-on: [paypal/#17](https://github.com/AffiliateWP/affiliate-wp-paypal-payouts/issues/17)
* [x] Stripe add-on [stripe/#17](https://github.com/AffiliateWP/affiliate-wp-stripe-payouts/issues/17)

**Comment by DrewAPicture** [comment]
Added a PR to the Paypal compatibility issue.

**Comment by DrewAPicture** [comment]
Added a PR to the Stripe compatibility issue.

**Comment by pippinsplugins** [comment]
PayPal is done and released.

**Comment by pippinsplugins** [comment]
Stripe tested and deployed.

**Comment by michaelbeil** [comment]
🙌
