### ISSUE TITLE
Link affiliate's name to edit affiliate screen rather than WP profile

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1573]
How many times does a site owner realistically need to edit the affiliate's WP user account by clicking on their name and going to WP profile screen? Since a site admin is on the "affiliates" screen we should only be showing actions related to affiliates.

How about we link the affiliate's name to the edit affiliate screen as per above and also leave the "edit" link in the actions menu (sometimes it's easier having more than 1 link). This is much more likely since there are many options that the admin might need to change. We can then show a link to the affiliate's WP user profile from the edit affiliate screen.

**Comment by pippinsplugins** [comment]
I agree.

**Comment by DrewAPicture** [comment]
I could see value in an 'Edit User' action link (especially if/when we relocate actions, but otherwise agree.

**Comment by DrewAPicture** [comment]
Added a PR: #1684 

It links the affiliate name to the edit URL and swaps the 'Edit' row action for an 'Edit User' row action link.

Looks like this:
![Edit User](https://cl.ly/1f2M1k1U0R0z/Screen%20Shot%202016-10-02%20at%203.57.40%20PM.png)

Let's pick this up in 1.9.3.
