### ISSUE TITLE
Add core object deletion actions

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#1574]
In `includes/class-db.php`, we could provide a do_action for object deletion. Presently, we have actions for `pre` and `post` `update` and `create`.

**Comment by pippinsplugins** [comment]
PR looks good.

**Comment by ramiabraham** [comment]
Adjusted the `affwp_pre_delete_` action to fire _after_ the core `$object` check has occurred in https://github.com/AffiliateWP/AffiliateWP/commit/e9187e52bad70dbc33674e757ab7112354ee8144.

**Comment by michaelbeil** [comment]
Looks good.
