### ISSUE TITLE
Error notice when wp user has been deleted

### ISSUE THREAD

**Issue by mdorchain** [AffiliateWP/AffiliateWP#1580]
Hi,

Nothing major, but I notice a small error in the affiliate list page when the wp user has been deleted.
It seems that it's trying to fetch data from a user that doesn't exist anymore.
It doesn't seem to cause much trouble.

`
Notice: Trying to get property of non-object in /home/30206-39807.cloudwaysapps.com/sevjjqjvas/public_html/wp-content/plugins/affiliate-wp/includes/admin/affiliates/affiliates.php on line 315
`

![image](https://cloud.githubusercontent.com/assets/11390079/18201525/3fca0366-713d-11e6-91de-0c82c2bbe39f.png)

Thanks

Michael

**Comment by ramiabraham** [comment]
Thanks @mdorchain, we'll get this in the next release!

**Comment by pippinsplugins** [comment]
PR looks good. Will merge once tests pass.

**Comment by mdorchain** [comment]
Thanks for the really lightning fast feedback :)
