### ISSUE TITLE
Adding referral var to static home page with Simple Page Tester plugin active causes blog posts to load

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1586]
When the [Simple Page Tester](https://wordpress.org/plugins/simple-page-tester/) plugin is activated, adding a referral variable to the home page (set to a static page) causes the blog index to be loaded instead.

**Comment by pippinsplugins** [comment]
Reported [here](https://secure.helpscout.net/conversation/245833895/41267/?folderId=205530) and replicated locally.

**Comment by michaelbeil** [comment]
👍

**Comment by pippinsplugins** [comment]
This is causing a fatal error on plugin activation:
```

Fatal error: Uncaught Error: Call to a member function was_referred() on null in /app/public/wp-content/plugins/affiliate-wp/includes/plugin-compatibility.php on line 77
```

**Comment by pippinsplugins** [comment]
Fixed.
