### ISSUE TITLE
Can't use the word "join" as the referral variable

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1589]
Steps to replicate:

1. AffiliateWP latest master installed (no other plugins)
2. Set the referral variable to **join**
3. Refresh the site and there should be a JS error:

Firefox:
```TypeError: can't convert undefined to object```

Chrome:
```Uncaught TypeError: Array.prototype.join called on null or undefined```

Safari
```TypeError: undefined is not an object (evaluating 'b()')```

![screen shot 2016-09-06 at 10 44 18 am](https://cloud.githubusercontent.com/assets/52581/18257862/e6b58eb4-741e-11e6-9615-4d36da1bab36.png)

Related tickets:
https://secure.helpscout.net/conversation/247180820/41479/?folderId=205531
https://secure.helpscout.net/conversation/244587910/41053/?folderId=205531

**Comment by sumobi** [comment]
Tested back to v1.6 and the issue was still present. Didn't go back any further.

**Comment by pippinsplugins** [comment]
Heh, that's fun . . .

**Comment by pippinsplugins** [comment]
Hmm, I cannot replicate this is 1.9.

**Comment by pippinsplugins** [comment]
Nevermind. Happens on master and 1.9 but it requires you use a pretty referral link.

**Comment by sumobi** [comment]
Finally confirmed with the 2nd customer that they also had "join".

**Comment by sumobi** [comment]
Ahh, interesting

**Comment by pippinsplugins** [comment]
it's failing due to a problem in `affwp_get_query_vars()`

**Comment by pippinsplugins** [comment]
OK found a way to fix it. It's more of a work around than a true fix, but it does resolve it.

**Comment by sumobi** [comment]
@pippinsplugins Sadly it didn't work. I cleared cache and made sure I could see your changes in tracking.js.

**Comment by sumobi** [comment]
It works with a referral link though

Works: 
issues.affwp.dev/?join=70

Does not work: 
issues.affwp.dev

**Comment by sumobi** [comment]
@pippinsplugins B I N G _ 

Would you like to buy a vowel?

**Comment by pippinsplugins** [comment]
It's not the cleanest fix but will do for now. We'll refactor the function later on to truly solve the problem.
