### ISSUE TITLE
Change referral rate if discount is used

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1597]
I am not too sure that this is something we would want to add to core, but perhaps it could be an add-on. A customer suggested that it could be great to dynamically change the referral rate based on whether or not a discount has been applied to the cart/purchase total. 

Currently, a referral will be calculated on the discounted total, so a 20% referral rate would still be 20% but on a lesser amount. If a site owner wants to give a referring affiliate a 10% referral rate when a referred visitor uses a discount (affiliate coupon or otherwise) instead of 20%, this is not possible. 

Any thoughts on this idea?

**Comment by pippinsplugins** [comment]
Cool idea. Could fit well in a `Referral Rate Conditions` add-on or something like that. Other possible conditions:

- affiliate account is X days old
- order total is greater than X
- order contains coupon
- order contains greater than X items

Has some overlap with Tiered Rates and Product Rates too.

**Comment by michaelbeil** [comment]
This may be better as an add-on. Should we start a card in Trello?

**Comment by pippinsplugins** [comment]
Yeah I think so.
