### ISSUE TITLE
1.9 Beta: Date-based Campaigns report tiles should actually reflect date-based data

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1606]
PR: #1622

The Campaigns view doesn't currently store any date information, so passing date query arguments to `get_campaigns()` has no effect.

We should leverage the referrals and/or visits tabs to fix the date filtering for the "Most Active Campaign" and "Best Converting Campaign" tiles.

**Comment by DrewAPicture** [comment]
The PR, #1622, is ready for testing.

**Comment by pippinsplugins** [comment]
@DrewAPicture would it be possible for the visits graph to only display visits that included a campaign?

**Comment by DrewAPicture** [comment]
@pippinsplugins I've updated the visits graph on the campaigns page to only show visits with a non-empty campaign value.

**Comment by pippinsplugins** [comment]
Woot

**Comment by pippinsplugins** [comment]
Looks great!
