### ISSUE TITLE
1.9 Beta: Add "Reports" buttons to management screen headers

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1607]
PR: #1628 

Let's tie the management screens with their corresponding reports screens (where possible).

The idea would be to add a "Reports" button next to "Add New" for Affiliates, Referrals, and Visits.

**Comment by DrewAPicture** [comment]
Added a PR: #1628

**Comment by pippinsplugins** [comment]
This looks great.

@DrewAPicture could you go ahead and do a PR for PayPal Payouts to make the buttons match?
![screen shot 2016-09-21 at 8 59 24 am](https://cloud.githubusercontent.com/assets/1034109/18713957/c3e83e4c-7fd9-11e6-8255-939c3e66b159.png)

**Comment by pippinsplugins** [comment]
Merged.
