### ISSUE TITLE
Improve the user accounts migration assistant tool

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1609]
PR: #1610

The current iteration of our user account migration tool needs to be improved as it is causing issues again.  

From @DrewAPicture: 
> I’m kinda thinking maybe instead of looping through all users (and doing umpteen number of db queries to determine if they’re affiliates) we should just retrieve all affiliate user IDs in one query and specifically exclude those users in the users query.  

> The only problem is, that the migration script does only 100 at a time, so I’ll need to find a way to persist the data so we aren’t doing the queries over and over. 

> I’m kinda thinking maybe cache it in a transient for an hour or something. Pretty rarely gonna be used so I’m not really concerned about new users being added.

**Comment by DrewAPicture** [comment]
Added a PR: #1610

**Comment by michaelbeil** [comment]
This was sent to a customer to test.

**Comment by DrewAPicture** [comment]
@michaelbeil I know we're waiting on confirmation from the customer. Did you also test this to confirm?

**Comment by michaelbeil** [comment]
No word from the customer but this looks good.

**Comment by DrewAPicture** [comment]
Tests passed, merged #1610.
