### ISSUE TITLE
Change "Earnings" column title in Affiliates screen to "Paid Earnings"

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1611]
I've been sitting in the Affiliates screen looking at the list table for a bit now, and I feel confused when I look at the `Earnings` column. I now know that it is only showing me **Paid earnings**, and does not include _Unpaid earnings_, so I wonder if it is worth clarifying that and calling the column `Paid Earnings`. 

Of course, it would be amazing to show `Unpaid Earnings` data on this screen as well, but it could be useful to at least specify that the column only shows **Paid earnings** for now.

Thoughts from the team?

**Comment by pippinsplugins** [comment]
I'd like to show both if we can make them fit.

**Comment by wordmaid** [comment]
👍 👍 Would be awesome!

**Comment by DrewAPicture** [comment]
Fitting is a much more fluid concept now that we have the ability to hide or show list table columns. Let's hit this for 1.9.3.

**Comment by DrewAPicture** [comment]
Opened #1730 as a start to change the 'Earnings' column label to 'Paid Earnings'.

**Comment by pippinsplugins** [comment]
Looks good.

**Comment by DrewAPicture** [comment]
Merged #1730.

**Comment by DrewAPicture** [comment]
Closing this one as fixed with merging of #1730. @wordmaid feel free to start a separate issue to add Unpaid Earnings.
