### ISSUE TITLE
Enable column show/hide controls in screen options for core list tables

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1612]
PR: #1613 

I think I may have found a way to trick WordPress screen options into displaying the show/hide controls for list table columns. The basic gist for why this wasn't possible previously is that our core list tables are instantiated too late for `WP_Screen` to pick up the list of columns needed to display said controls.

We can get around this by effectively instantiating (but not displaying) core list tables on their respective `load-{$hook_suffix}` actions hooked in the screen-options.php files.

**Comment by DrewAPicture** [comment]
Added a PR: #1613

**Comment by pippinsplugins** [comment]
Works great here!

**Comment by michaelbeil** [comment]
This works great!
