### ISSUE TITLE
1.9 Beta: Paypal integration broke Ajax on the registration form

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1616]
PR: #1617 

It looks like the JS printed via `wp_footer` is relying on a localized value to supply the ajaxurl, execpt in class-paypal.php, the script isn't enqueued (and therefore can't be localized) and neither are any other scripts enqueued on the registration page that would define `affwp_scripts` on the page either.

Best suggestion would be to simply drop the ajax URL into the script directly, as we already do in class-tracking.php.

PR attached.

**Comment by DrewAPicture** [comment]
PR: #1617 

To test:

1. Check out latest `release/1.9`.
2. Visit the affiliate registration/login form while logged out (with the console open)
3. Try to login
4. Note the notice thrown for `affwp_scripts.ajaxurl` being undefined

To confirm the fix, check out `issue/1616`, repeat steps above, noting that no notice is thrown and login/registration are successful

**Comment by pippinsplugins** [comment]
Good catch!
