### ISSUE TITLE
Affiliate name should be shown on Visits page when filtering by affiliate

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1623]
When appending the `affiliate=#` parameter to the Visits page, only visits of that affiliate are shown, but the `Affiliate name` field is still blank.

![screen shot 2016-09-20 at 9 21 51 am](https://cloud.githubusercontent.com/assets/1034109/18674146/d1a2271c-7f13-11e6-9772-55e572cb9c81.png)

Let's improve this by pre-filling the Affiliate name field when an affiliate ID is specified in the URL.

**Comment by michaelbeil** [comment]
Works splendidly!

**Comment by pippinsplugins** [comment]
Looks good, merge once tests pass.
