### ISSUE TITLE
Add more robust JavaScript debug info if AFFILIATE_WP_DEBUG is active

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#1630]
If `AFFILIATE_WP_DEBUG` is active, we could add an array of localized data and print it directly to the console, with something like:

``` javascript
console.affwp( the debug info );
```

which could be added via an extension of `console.error`:

``` javascript

function affwpDebug() {
  return affwp.localizedDataArray;
}

console.affwp = function() {

        Array.prototype.unshift.call(

            arguments,
            affwpDebug() );

        console.error.apply( console, arguments );
    };
```

We could also organize the data so it's more readily accessible, using `console.table`.

---

Ideas for the sort of data to show:
- Valid visit ID (or if no visit was set
- Cookie exists
- Referral var valid
- Referring affiliate valid
- affwp version
- currency
- Active integrations

---

JavaScript debug info could:
- Assist in debugging JS-heavy integrations
- Potentially reduce resolution time for customer support requests.

**Comment by pippinsplugins** [comment]
I love this idea.

**Comment by DrewAPicture** [comment]
@ramiabraham What are the odds we can get this for 2.0?

**Comment by ramiabraham** [comment]
@DrewAPicture 100%

@AffiliateWP/core Ready for review. PR: https://github.com/AffiliateWP/AffiliateWP/pull/1896

**Comment by ramiabraham** [comment]
Anything in there that's missing that'd be good to have?

**Comment by pippinsplugins** [comment]
@ramiabraham could we please go ahead and add in calls to the new debug function in our tracking scripts? That way, if debug is enabled, we can go to a site via an affiliate URL and see the debug results int he console?

**Comment by ramiabraham** [comment]
@pippinsplugins It's in there but I just discovered that something is causing the `affwp_debug_utility` object to get cached after the initial output, which then causes it to print nothing. I'm in the process of tracking that down...

For now, dumping the browser cache will allow adequate testing.

**Comment by ramiabraham** [comment]
The object can also be accessed directly in (Firefox) `DOM -> affwp_debug_utility`

**Comment by pippinsplugins** [comment]
@ramiabraham I don't see the debug utility utilized anywhere. Quick thoughts on places I'd like to see it:

1. When the campaign is retrieved
2. When the aff ID is retrieved
3. When the query vars are retrieved
4. When responses from back for ajax requests
5. When ajax requests are sent

Basically I want to be able to see _everything_ that is happening in the JS in the console. If we're introducing a debug utility, we need to use said tool in our own code.

**Comment by pippinsplugins** [comment]
@ramiabraham this gives a `tracking.js?ver=2.0:7 Uncaught ReferenceError: AFFWP is not defined` error if debug mode is disabled.

**Comment by pippinsplugins** [comment]
Found and fixed that error.

**Comment by pippinsplugins** [comment]
@ramiabraham This is working well now!

Anything else you wish to add to it?

Also did you see my comment above? https://github.com/AffiliateWP/AffiliateWP/issues/1630#issuecomment-271028132

**Comment by ramiabraham** [comment]
@pippinsplugins I think I'm good - been putting it through its paces. @sumobi Mind testing?

**Comment by pippinsplugins** [comment]
Looking good here! Will merge once tests pass.
