### ISSUE TITLE
Add campaign to the request URI in fallback tracking

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1639]
Currently we get the full URL with tracking.js directly from `document.URL` whereas in fallback tracking we simply grab `'http://' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI']`.

Per @DrewAPicture: 

> Except I don’t think the campaign and such are in the request URI at this point, so it must be getting stripped somewhere.  

Related: https://github.com/AffiliateWP/AffiliateWP/issues/1470

**Comment by pippinsplugins** [comment]
Moved to 1.9.1. We need to get 1.9 out the door, even if we end up following it up with a few point releases.

**Comment by DrewAPicture** [comment]
Punting this to 1.9.5 mostly because I never was able to pinpoint where the request URI was getting stripped and that knowledge is central to fixing this.

**Comment by DrewAPicture** [comment]
@pippinsplugins Do you want to proceed with this one? IIRC, I was having trouble tracking down where we could pull the campaign value from the `$_SERVER` superglobal.

**Comment by pippinsplugins** [comment]
@DrewAPicture please go ahead and take another stab at it please.

**Comment by gspice** [comment]
Got this on a ticket:
https://secure.helpscout.net/conversation/362603838/58970/?folderId=1170842

**Comment by DrewAPicture** [comment]
After some discussion and rigorous testing in several environments, we've determined this isn't enough of a widespread issue to investigate further.
