### ISSUE TITLE
Add export option to Payouts

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1650]
It could be useful to export Payout logs for bookkeeping purposes. All the data shown in a payout would be exported to CSV, and can simply be filtered by date (as per our other date select menus).

Thoughts?

**Comment by pippinsplugins** [comment]
Definitely!

**Comment by DrewAPicture** [comment]
I'd like to keep this one on 2.0.

**Comment by DrewAPicture** [comment]
Added a PR branched off of and dependent on  `issue1707`: #1886

**Comment by pippinsplugins** [comment]
@DrewAPicture works great except the affiliate filter doesn't properly limit payouts. I entered an affiliate's userlogin but the export still contained payouts for all affiliates.

**Comment by pippinsplugins** [comment]
Can we please include the affiliate's name in the payout export as well? Also the "Owner" column label should should be changed to `Generated By` to match the UI.

**Comment by DrewAPicture** [comment]
@pippinsplugins I've adjusted the output so you get an "Affiliate" column, e.g. "Drew (#1)", and owner has been switched to "Generated By" with "Drew (#1)". Also as pointed out in Slack, I think I've got the use of multiple affiliate autocomplete forms on one page working now.

**Comment by DrewAPicture** [comment]
@pippinsplugins Note that `issue/1650` branches off of and requires #1707 to be merged first since it leverages batch processing ;)

**Comment by pippinsplugins** [comment]
Works perfectly. Nice work.
