### ISSUE TITLE
Payouts log showing other affiliate's referrals

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1651]
Example:
https://affiliatewp.com/wp-admin/admin.php?page=affiliate-wp-payouts&payout_id=9&action=view_payout

It should only show 3 referrals for this affiliate.

**Comment by pippinsplugins** [comment]
@sumobi I cannot replicate this. Can you replicate locally?

**Comment by pippinsplugins** [comment]
Nevermind, just replicated it.

**Comment by sumobi** [comment]
@pippinsplugins works for me
