### ISSUE TITLE
Bail early from affwp_get_affiliate_rate() if invalid affiliate

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1656]
For reference: https://secure.helpscout.net/conversation/256741597/43380/?folderId=205524

While bailing early from `affwp_get_affiliate_rate()` it doesn't address the root of the problem – why affiliate_id is being sent as 0 and later evaluated as false, it should effectively allow for graceful failure.

**Comment by DrewAPicture** [comment]
PR: #1657

**Comment by DrewAPicture** [comment]
New PR: #1659

**Comment by pippinsplugins** [comment]
Another instance of this: https://secure.helpscout.net/conversation/245833895/41267/?folderId=205530

**Comment by pippinsplugins** [comment]
@DrewAPicture New PR won't quite work.

Pre 1.9, the `$product_rate` can be passed to the function and be taken into account even if no affiliate is retrieved. This could be important for compatibility if anyone was passing product rates without an affiliate.

**Comment by pippinsplugins** [comment]
Third ticket https://secure.helpscout.net/conversation/256597147/43350/?folderId=205530

**Comment by pippinsplugins** [comment]
PR looks good now.

@sumobi @michaelbeil could both of you please test this with Lifetime Commissions?

**Comment by pippinsplugins** [comment]
At least one of the tickets that has reported this found that the fatal error only happened when Lifetime Commissions was active.

**Comment by sumobi** [comment]
@pippinsplugins @DrewAPicture Are you able to replicate the fatal error? Trying to replicate before testing the patch but with Lifetime Commissions and AffWP v1.9.0.1 orders with WooCommerce and EDD are working fine.

**Comment by pippinsplugins** [comment]
@sumobi I have not yet but have now seen it on three separate sites.

**Comment by sumobi** [comment]
@pippinsplugins Yeah, I'd prefer to replicate first and then test the patch so I know it's working.
