### ISSUE TITLE
Permalinks issue with WooCommerce and WooCommerce Bookings

### ISSUE THREAD

**Issue by fernandotellado** [AffiliateWP/AffiliateWP#1658]
Since the 1.9.x update there's a problem with permalinks and edits with WooCommerce products and orders and with WooCommerce Bookings reservations.

Woo orders and Woo Bookings respond with 404 errors and Woo products doesn't show the content of WP editor

**Comment by pippinsplugins** [comment]
@fernandotellado do you have a page that has a slug with the same value as the referral variable? See #1660

**Comment by fernandotellado** [comment]
No, I don't. The issue occurs with any product/reservation/order.

I've just downgraded the plugin to 1.8.7 and everything works again

**Comment by pippinsplugins** [comment]
Which of the WooCommerce Bookings plugins are you using? This one? https://woocommerce.com/products/woocommerce-bookings/

**Comment by fernandotellado** [comment]
Yes, the official one

**Comment by fernandotellado** [comment]
Just upgraded to 1.9.1 and same issue :(

**Comment by pippinsplugins** [comment]
@fernandotellado would you be willing to give us admin access to your site so we can look into it further for you? If so, please send the credentials via our support page: https://affiliatewp.com/support

**Comment by fernandotellado** [comment]
Sure, I'll give you the details next Monday 'cause I'm currently on a travel :)

**Comment by fernandotellado** [comment]
Issue has resolved with 1.9.2 👍

**Comment by pippinsplugins** [comment]
Glad to hear it!
