### ISSUE TITLE
Show flat rate from the statistics tab when used as default referral rate type

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1669]
If the default referral rate type is set to flat rate, the commission rate that is shown from the front end affiliate area statistic tab is a percentage.

![screen shot 2016-09-29 at 4 25 38 pm](https://cloud.githubusercontent.com/assets/4752949/18973056/638eb010-8661-11e6-971b-7de622fba8e3.png)

Let's show the actual default referral rate here: 
![screen shot 2016-09-29 at 4 24 45 pm](https://cloud.githubusercontent.com/assets/4752949/18973036/41f86e50-8661-11e6-880f-c6f927edc629.png)

**Comment by DrewAPicture** [comment]
Added a PR: #1682

**Comment by DrewAPicture** [comment]
With the PR:

*Global default*:
![Flat rate type](https://cl.ly/3u0N1J0b3o2G/Screen%20Shot%202016-10-02%20at%204.13.49%20PM.png)

*Affiliate overriding global flat with percentage*:
![Percentage rate type](https://cl.ly/182m0p102r3c/Screen%20Shot%202016-10-02%20at%204.13.05%20PM.png)

**Comment by pippinsplugins** [comment]
Merged.
