### ISSUE TITLE
Remove unnecessary wp_enqueue_style() 

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1672]
This `wp_enqueue_style()` isn't required:
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/class-shortcodes.php#L138

It's already enqueued here:
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/scripts.php#L132

**Comment by DrewAPicture** [comment]
FWIW, there isn't really a downside in enqueuing the script multiple times – WordPress will only enqueue it once on a given page regardless of how many times `wp_enqueue_script()` is called.

It's also worth mentioning that abstracting all of the logic in that conditional and then conditionally enqueuing the scripts when the shortcodes are actually rendered would be vastly more performant ... `has_shortcode()` essentially runs a RegEx against the content which can be very slow, and we're running it _twice_ here.

**Comment by DrewAPicture** [comment]
It would be much cleaner to do something like this inside of a wrapper for all of those enqueues:
```php
if ( ! wp_script_is( 'affwp-forms', 'enqueued' ) ) {
    wp_enqueue_script( 'affwp-forms' );
}
```

Then call the wrapper within the shortcode callbacks.

**Comment by sumobi** [comment]
@DrewAPicture All for a cleaner/better way of doing it, just as long as the scripts from the shortcode can be dequeued, which was the issue with both the registration and login shortcodes.

For reference:

https://github.com/AffiliateWP/AffiliateWP/issues/1026
https://github.com/AffiliateWP/AffiliateWP/issues/1670

**Comment by DrewAPicture** [comment]
I've pushed my suggestion for how to approach selectively enqueuing for certain shortcodes.

**Comment by pippinsplugins** [comment]
@sumobi Does that work for you?

**Comment by sumobi** [comment]
testing now

**Comment by sumobi** [comment]
@DrewAPicture Can you show me how you would remove just the `affwp-forms` CSS file? 

Dequeuing or deregistering it has no effect since it's still being enqueued inside the `affiliate_login` shortcode.

```
function affwp_dequeue_styles() {
    wp_dequeue_style( 'affwp-forms' );
    wp_deregister_style( 'affwp-forms' );
}
add_action( 'wp_enqueue_scripts', 'affwp_dequeue_styles' );
```

**Comment by sumobi** [comment]
The other issue on https://github.com/AffiliateWP/AffiliateWP/issues/1670 is that the forms.css file is still being outputted just before the closing body tag. This causes a flash of unstyled content where you see the unstyled form, and then the styled one. If we load it in the `<head>` (where CSS files should ideally be loaded) this would be solved.

**Comment by DrewAPicture** [comment]
See the second PR on #1670 for what may be ultimately a better all-around approach.

**Comment by DrewAPicture** [comment]
Closing in favor of #1670 and its PR: #1748.

**Comment by sumobi** [comment]
@DrewAPicture that last commit prevents the `admin.css` file from loading within the admin. If it can't load, the plugin icon won't show:

<img width="177" alt="screen shot 2016-11-11 at 6 42 44 pm" src="https://cloud.githubusercontent.com/assets/52581/20235142/ec3d701e-a83e-11e6-91d4-bfac93f59613.png">
