### ISSUE TITLE
Fatal error on reports page (using $this in a closure) for PHP 5.3

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1674]
Customer reported getting a fatal on the Reports screen, due to use of `$this` inside a closure. Classic oversight.

**Comment by DrewAPicture** [comment]
Note: This only affects customers running PHP 5.3. Support [was added](http://php.net/manual/en/functions.anonymous.php) for accessing `$this` inside of anonymous functions in PHP 5.4.

**Comment by DrewAPicture** [comment]
Added a PR: #1675

**Comment by pippinsplugins** [comment]
Merged. Let's plan to deploy 1.9.2 early next week.
