### ISSUE TITLE
Exported Referrals and Affiliates from Tools page is duplicated in output CSV file

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1678]
When exporting Referrals from the `Tools` page, I have noticed the report has duplicated the referrals included in the report a **_huge_** number of times. 

Here are the steps I took:

1. In the `Referrals` screen, I selected referrals with an **Unpaid** status, (as I only wanted to see Unpaid referrals.) The total on the WordPress screen for Unpaid referrals is **161**. 
2. I wanted to run a report on Unpaid referrals, which should have generated 161 results/rows in the exported CSV file (plus one row for the column titles = 162 total)
3. The file took some time to download, and I noticed it was very large: **213.6mb** to be exact
4. When I opened the file, not only did it crash my Numbers app a couple of times, but I noticed there were **65,535** rows of data (instead of 162 rows of data; 161 referrals + 1 row of column titles)
5. After looking more closely at the specific data I ran, it seems the exported data has been duplicated (almost infinitely) in the CSV file. My spreadsheet happened to stop at 65,535 rows.

Fun fact: 65,535/162 = 404(.5). Lol?

I then attempted to export all Referrals for all time, with no affiliates selected. Again, a huge report was generated, stopping again at 65,535 rows with duplicated results (which is still too many, given our Total Referral count, across all statuses).

For fun, I ran a report for active Affiliates and had a similar result. Given our amount of Active affiliates isn't particularly huge, the export file took a significant amount of time to download, was very large (67.9mb), and again the results were duplicated multiple times to a huge row number (65,535 again).

Additionally (potentially related or not related?), a customer has experienced a fatal error when trying to export either Affiliates or Referrals data from the `Tools` screen. Perhaps this is occurring due to the huge amount of data trying to be exported (as per my issue above): https://secure.helpscout.net/conversation/258627598/43701/?folderId=205524

Error message: https://affiliatewp.com/index.php?gf-download=2016%2F10%2Faffiliate-wp-export-referrals-10-02-2016.txt&form-id=2&field-id=14&hash=49b9ee7f1acc317167a5c5bbe89e0f91df82bd28e9ac3ee30037cfd40f95cf55

Anyway, this seems like a pretty major bug - is anyone else able to replicate?

**Comment by DrewAPicture** [comment]
@wordmaid You're correct, it _is_ a major bug. In 1.9 we accidentally introduced a hook conflict that causes the exporter processes to recurse on themselves endlessly, which eventually causes PHP to run out of memory. We'll be shipping a fix for this in 1.9.2, probably tomorrow (on Monday).

**Comment by DrewAPicture** [comment]
Added a PR: #1681

Please test!

**Comment by DrewAPicture** [comment]
Sent a patched version to two customers.

**Comment by pippinsplugins** [comment]
Good catch. Merged.
