### ISSUE TITLE
Add Referral ID column to View Payout screen

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1686]
In each individual Payout, the referrals are listed, but their referral IDs are not. There are links to the related orders, but no link to the actual individual referrals. We already see them on the main Payouts screen - perhaps we could consider adding a Referral ID column on this screen that links to the actual referral?

**Comment by pippinsplugins** [comment]
I vote we add the IDs and link to the edit screen.

**Comment by DrewAPicture** [comment]
What about simply _not hiding_ the Actions column for the referrals table on View Payout screen?

Correct me if I'm wrong, but it seems like the problem we're trying to solve has less to do with the referral ID not being exposed – it also isn't exposed anywhere in the main Referrals table either – it's that there's no way to navigate to the Edit Referral screen for individual referral records, right?

So we could simply show the Actions column (which we're currently deliberately hiding), providing access to the individual referral edit screens.

See the attached PR: #1703

Before: 
![No Actions](https://cl.ly/3Y283T1U401q/Screen%20Shot%202016-10-09%20at%204.09.02%20PM.png)

After:
![With Actions](https://cl.ly/3n2p2C0n1l1f/Screen%20Shot%202016-10-09%20at%204.17.17%20PM.png)

**Comment by pippinsplugins** [comment]
I'm fine with showing the actions column.

**Comment by pippinsplugins** [comment]
Merged.
