### ISSUE TITLE
Coupons being linked to admin affiliate by default

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1689]
When you create a new coupon it is being linked automatically to the admin affiliate. So far it has been reported in EDD and WooCommerce but could be other integrations also.

It's not possible to get rid of the admin user and save, since it just reappears again.

**Comment by pippinsplugins** [comment]
This is happening because `affwp_get_affiliate_id()` returns the ID of the affiliate account of the currently logged in user.

```php
/**
 * Retrieves the affiliate ID of the specified user
 *
 * If no user ID is given, it will check the currently logged in user
 *
 * @since 1.0
 *
 * @param int $user_id Optional. User ID. Default is the ID of the current user.
 * @return int|false Affiliate ID, or false if the current user isn't logged-in or `$user_id` is empty.
 */
function affwp_get_affiliate_id( $user_id = 0 ) {

	if ( ! is_user_logged_in() && empty( $user_id ) ) {
		return false;
	}

	if ( empty( $user_id ) ) {
		$user_id = get_current_user_id();
	}

	$cache_key    = md5( 'affwp_get_affiliate_id' . $user_id );
	$affiliate_id = wp_cache_get( $cache_key, 'affiliates' );

	if( false === $affiliate_id ) {

		$affiliate_id = affiliate_wp()->affiliates->get_column_by( 'affiliate_id', 'user_id', $user_id );

	}

	return $affiliate_id;
}
```

**Comment by pippinsplugins** [comment]
PR ready for testing.

**Comment by ramiabraham** [comment]
Working here - coupons are now generated for the correct affiliate. Tested integrations:

- EDD
- RCP
- iThemes Exchange
- MemberPress
-WooCommerce

**Comment by sumobi** [comment]
Looks like LifterLMS has the same issue:

https://github.com/AffiliateWP/AffiliateWP/issues/1781#issuecomment-260107812

**Comment by michaelbeil** [comment]
Commit https://github.com/AffiliateWP/AffiliateWP/commit/70a0dc11161f4d48e90bd985a8131b3118e4e42f should fix the LifterLMS coupon issue.

**Comment by michaelbeil** [comment]
Everything is working well here.

**Comment by DrewAPicture** [comment]
@michaelbeil So are we done here then? If so, feel free to close it.
