### ISSUE TITLE
Space in campaign name triggers "Please enter a valid URL for this site" notice

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1690]
If you use a space in the campaign name on the Affiliate URLs tab, then click to generate a URL, it triggers the "Please enter a valid URL for this site" message below the Page URL field. Technically this is correct since the URL shouldn't have a space in it, but it's confusing to the user, since it seems the error is related to the Page URL field. 

We should show an error message directly underneath the campaign name field if there's a space in the name.

space in campaign name:

![screen shot 2016-10-05 at 2 05 31 pm](https://cloud.githubusercontent.com/assets/52581/19097873/d16f577c-8b04-11e6-8a96-cce4c4d94356.png)

space removed:

![screen shot 2016-10-05 at 2 05 37 pm](https://cloud.githubusercontent.com/assets/52581/19097880/dfb1f8a8-8b04-11e6-8077-bcc70cea992a.png)

**Comment by ramiabraham** [comment]
Related https://secure.helpscout.net/conversation/265093294/0/

**Comment by DrewAPicture** [comment]
Added a PR: #1735 

Strips whitespace from the campaign when focus of the input field is lost, such as by tabbing through the form or clicking on the generate button.
