### ISSUE TITLE
Several strings aren't translated

### ISSUE THREAD

**Issue by fernandotellado** [AffiliateWP/AffiliateWP#1694]
There're several strings that aren't translated in Spanish (I don't know if it happens in other languages). 

The first problem that I've seen is that the .mo file doesn't correspond with the .po. If I generate the .mo in Poedit and uploaded to languages folder then the payouts part is translated ok, but there are other strings that aren't translated even thought all the strings appear translated in the .po file (poedit). The strings that don't get translation are the summary admin page headers (totals, most valuable affiliates, and so on) while in poedit and .po file appear fully translated.

I've clear all caches, of course

Page without translation capture:
https://postimg.org/image/kv7co39yl/

Strings appear fully translated in .po file capture:
https://postimg.org/image/jp6zjeuvh/

Thanks for this great plugin 👍

**Comment by DrewAPicture** [comment]
I think this is related to `_ex()` not being parsed correctly in the build script.

**Comment by fxbenard** [comment]
IMHO: As the strings are in the po and don't think there is nothing to do with the build script.

**Comment by DrewAPicture** [comment]
Added a PR. Please test! #1732
