### ISSUE TITLE
Wrong affiliate ID/username shown on edit affiliate screen

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1701]
The `Affiliate URL` on the affiliate edit screen is showing the ID or username (depending on settings) of the currently logged in affiliate, not the affiliate being edited.

Just needs the affiliate ID passed into the `affwp_get_affiliate_referral_url()` function.

**Comment by DrewAPicture** [comment]
Looks good.

**Comment by michaelbeil** [comment]
Confirm fixed.
