### ISSUE TITLE
Affiliate autocomplete doesn't scale beyond 9,999 affiliates 

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1704]
As a couple of customers have reported, including [this one](https://secure.helpscout.net/conversation/255979754/43249/?folderId=205529), the affiliate autocomplete field pretty much fails hard with affiliate numbers higher than 9,999. Let's see if we can't make this a bit more efficient.

**Comment by DrewAPicture** [comment]
Added a PR: #1705 

Covers:
* [x] Don't limit affiliate user ID queries to 9,999 results
* [x] Only query for the user IDs instead of full affiliate objects
* [x] Only display the user email in autocomplete results if there is one 

To test, you'll need to generate > 10,000 _active_ affiliates. Note: This process will also generate a requisite number of user accounts, one for each affiliate.
```sh
wp affwp affiliate generate --count=11000 --status=active
```
1. Once your test affiliates have finished generating, visit Affiliates > Referrals > New
2. Attempt to type an affiliate name. Note: generated affiliate usernames follow the pattern affwp_user_#_#####, so the more specific you can be, the faster the autocomplete should return results.
3. You should see affiliate usernames display based on your criteria.

**Comment by wordmaid** [comment]
The customer has submitted a new specific ticket regarding this bug: https://secure.helpscout.net/mailbox/7c3a9e4da50293a7/414056/

**Comment by DrewAPicture** [comment]
@AffiliateWP/core looking for testers for this for 1.9.4.

**Comment by pippinsplugins** [comment]
Will test tonight.

**Comment by pippinsplugins** [comment]
@DrewAPicture I get `Error: 'generate' is not a registered subcommand of 'affwp affiliate'. See 'wp help affwp affiliate'.` when trying.

I recall you putting the generate command somewhere but now do not remember where.

**Comment by michaelbeil** [comment]
@pippinsplugins https://github.com/AffiliateWP/affiliatewp-wp-cli-generator

**Comment by michaelbeil** [comment]
Can confirm this PR fixes the autocomplete issue.

**Comment by pippinsplugins** [comment]
Works well here too!
