### ISSUE TITLE
Integration: Paid Member Subscriptions

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1710]
There have been some requests to add an integration for [Paid Member Subscriptions](https://wordpress.org/plugins/paid-member-subscriptions/). Looks like a really nice plugin. I think we should consider it.

**Comment by pippinsplugins** [comment]
This could also include an integration with the `Recurring Referrals` add-on.

**Comment by michaelbeil** [comment]
+1 here. Looks like a stellar plugin.

**Comment by IovaMihai** [comment]
Hey guys, I will start working on this integration. Will let you know when I have something.

**Comment by michaelbeil** [comment]
Sounds great!

**Comment by IovaMihai** [comment]
Back with details. I have finished the integration and also prepared a documentation page: https://www.cozmoslabs.com/docs/paid-member-subscriptions/integration-with-other-plugins/affiliatewp-integration/

In order for the integration to work properly the latest version of Paid Member Subscriptions is needed, which you can clone from: https://bitbucket.org/cozmoslabs/paid-member-subscriptions

It seems I do not have permission to push the changes made in AffiliateWP, please advise on this.

Thank you!

**Comment by pippinsplugins** [comment]
@IovaMihai Awesome! You can submit the changes as a pull request from a fork.

**Comment by michaelbeil** [comment]
PR: https://github.com/AffiliateWP/AffiliateWP/pull/1765

**Comment by pippinsplugins** [comment]
@michaelbeil think you could get this tested this week?

**Comment by IovaMihai** [comment]
Hey guys, did you have the chance to test this out?

**Comment by pippinsplugins** [comment]
Sorry we haven't let. 

I'm going to milestone it for 1.9.6 so we that we can get it tested and included.

**Comment by IovaMihai** [comment]
Okay. Looking forward to it! Thanks for letting me know.

**Comment by sumobi** [comment]
@AffiliateWP/core Works great for me. Anyone else want to test?

@IovaMihai Can I have access to your discount add-on so I can also test the affiliate discount functionality?

**Comment by sumobi** [comment]
@IovaMihai Thanks for the PR, it's been merged into release/2.0

**Comment by IovaMihai** [comment]
Hey @sumobi, is it okay if I send you the Discount Codes Add-On and the vector logo to the email address you have displayed on your GitHub profile?

**Comment by pippinsplugins** [comment]
@IovaMihai send it to andrew@affiliatewp.com

**Comment by IovaMihai** [comment]
@pippinsplugins Done. Thanks for the reply.

**Comment by sumobi** [comment]
@IovaMihai Got it, thanks!

**Comment by sumobi** [comment]
@AffiliateWP/core Discount add-on works great. We're good to go on this.

**Comment by pippinsplugins** [comment]
Great!

**Comment by IovaMihai** [comment]
Awesome! Looking forward for the release.
