### ISSUE TITLE
Allow campaign query caches to be invalidated by core object CRUD operations

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1714]
Likely the reason why stats in the Affiliate Area are now delayed is due to changes in our caching scheme for _queries_ following the 1.9 release. In 1.9, we introduced passive cache invalidation which allows core object queries to be refreshed when CRUD operations occur against their member objects.

However, the campaign queries are not subject to this same cache invalidation scheme because it represents a VIEW of aggregated core object data. Because of this, stats in the Affiliate Area appear on a delay because the only way those caches are invalidate are by core, once an hour.

It may be possible to display nearly-real-time results by allow core object CRUD operations to passively invalidate campaign caches. This would have the effect of still caching query results in between operations while reflecting vastly more current stats.

**Comment by DrewAPicture** [comment]
Related: #1712 

See also https://secure.helpscout.net/conversation/262682199/44528/?folderId=205527

**Comment by DrewAPicture** [comment]
Added a PR: #1715.

Please test!

**Comment by DrewAPicture** [comment]
@AffiliateWP/core looking for testers for this for 1.9.4.

**Comment by pippinsplugins** [comment]
I can test tonight.

**Comment by pippinsplugins** [comment]
Works great!
