### ISSUE TITLE
Remove a redundant existing affiliate check in affwp_add_affiliate()

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1727]
`affwp_add_affiliate()` performs a simple `user_id` check to find out if an affiliate exists with the given user ID. However, `affwp_add_affiliate()` is largely a wrapper for the `->add()` method in the Affiliates DB layer, which _also_ does the same check. We could realize a minor performance gain by skipping an unnecessary query in `affwp_add_affiliate()`.

**Comment by DrewAPicture** [comment]
Added a PR: #1728

**Comment by michaelbeil** [comment]
Works well.
