### ISSUE TITLE
Set minimum cart total before affiliate discount coupon can be used/referral awarded

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1738]
Interesting idea from a pre-sale customer - supporting a minimum amount of spend/minimum cart total before an affiliate discount code can be used.

A customer has asked if it is possible to set a minimum cart amount before an affiliate discount code can be used. They don't want the customer to receive a discount or the affiliate to be awarded a referral unless the cart total meets a spend threshold.

This could potentially integrate with EDD Prevent Checkout and WooCommerce Min/Max Quantities.

**Comment by sumobi** [comment]
Here's a start (for WooCommerce)
https://github.com/AffiliateWP/affiliatewp-code-snippet-library/edit/master/integrations/woocommerce/block-affiliate-coupon-minimum-amount.php

**Comment by sumobi** [comment]
I feel like this could be achieved best via a pro add-on (https://trello.com/c/jp0BvhQN/72-restrict-referrals) but interested to hear anyone's thoughts on why this should be core functionality.

**Comment by pippinsplugins** [comment]
I'd be fine putting it in the pro add-on, so long as that is not the only feature in the pro addd on.

**Comment by sumobi** [comment]
👍 Not the only feature, the Trello card outlines other functionality

**Comment by michaelbeil** [comment]
I would agree on the pro add-on instead of core.

**Comment by michaelbeil** [comment]
Closing in favor of Trello card.
