### ISSUE TITLE
Set reasonable default limits on core object REST requests

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1740]
Welp, turns out our core listing endpoints don't scale beyond a certain point, resulting in the server to send back 500 errors.

We should set common-sense default limits on the `affiliates`, `creatives`, `payouts`, `referrals`, and `visits` endpoints. Maybe 20 or 30?

**Comment by michaelbeil** [comment]
20 seems fine to me.

**Comment by DrewAPicture** [comment]
Added a PR: #1741

**Comment by pippinsplugins** [comment]
20 is fine by me. PR looks good.
