### ISSUE TITLE
Amount in Generate Payout File shows single number after decimal

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1743]
The CSV file generated from the referrals does not add an amount with two decimal places when the integer is any tenth.

31.9 is shown instead of 31.90.

**Comment by DrewAPicture** [comment]
@michaelbeil OK. And is that only for currencies with two decimal places or any currency?

**Comment by michaelbeil** [comment]
As far as I know only currencies with two decimal places. US dollars were tested.

**Comment by DrewAPicture** [comment]
OK, I'll take a look.

**Comment by DrewAPicture** [comment]
@michaelbeil I'm unable to reproduce this. Here's what I used to test:

1. Creates some referrals with `wp affwp referral generate --count=5 --status=unpaid affiliate_id=###`
2. Generated a payout file and opened the CSV
3. Amount showed as ##.##

**Comment by michaelbeil** [comment]
Replicated again with an amount of 54.7.

**Comment by michaelbeil** [comment]
Hmm, now I cannot replicate on a different test site. All fixed here.
