### ISSUE TITLE
Pass $row_id values to update hooks in class-db.php

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1749]
The usefulness of hooks like `affwp_post_update_{$type}`, e.g. `affwp_post_update_referral` would be substantially greater if we actually passed the `$row_id` for the item being updated.

**Comment by DrewAPicture** [comment]
Added a PR: #1754

**Comment by ramiabraham** [comment]
PR looks good, confirmed here!
