### ISSUE TITLE
All core object delete wrappers should pass the object type to the delete() method

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1750]
In lieu of passing the type, the type thereby does not get passed to the dynamic hooks inside of `Affiliate_WP_DB::delete()` and the hooks fire, but they fire as `affwp_post_delete_` instead of `affwp_post_delete_referral|affiliate|payout|etc`.

**Comment by DrewAPicture** [comment]
Added a PR: #1751 

To test, try firing a callback against the `affwp_post_delete_{$type}` hook, where `$type` is `affiliate`, `creative`, `payout`, `referral`, or `visit`.

**Comment by ramiabraham** [comment]
Tested and confirmed working here!

**Comment by DrewAPicture** [comment]
#1751 was merged.
