### ISSUE TITLE
Block self-pings in usage tracking check ins

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1759]
We need to ensure that the usage tracking class cannot try and ping our own site. Fairly certain that has been the culprit in several server melt downs we've seen recently immediately following an EDD core update.

**Comment by DrewAPicture** [comment]
Added a PR: #1760 

@pippinsplugins Let me know if that will work.

**Comment by pippinsplugins** [comment]
Looks good. Merged.
