### ISSUE TITLE
Author for Affiliate Area page not set to correct user

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1761]
When AffiliateWP is activated for the first time, the author of the "Affiliate Area" page is not set to the admin who activated the plugin. In the customer's example, the author was actually `wpengine` who have an admin account on your site by default if you are hosted with them. 

We should make it so the author is the admin who activated AffiliateWP.

**Comment by DrewAPicture** [comment]
Added a PR: #1762

**Comment by sumobi** [comment]
Might have to start calling you Flash Gordon 👍
