### ISSUE TITLE
DRY up outputting navigation tabs

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1763]
As [pointed out](https://scrutinizer-ci.com/g/AffiliateWP/AffiliateWP/indices/1490116/duplications/942941) by Scrutinizer, we have essentially duplicated the same nav-tab output markup four different places in AffWP core. We should DRY this up.

> _In software engineering, don't repeat yourself (DRY) is a principle of software development, aimed at reducing repetition of information of all kinds, especially useful in multi-tier architectures._

**Comment by DrewAPicture** [comment]
Added a PR: #1764 

Introduces `affwp_navigation_tabs()` and implements it in all 4 places.

Please test that the tabs are output as expected on:
1. Affiliates > Reports
2. Affiliates > Tools
3. Affiliates > Settings
4. Affiliates > Add-ons

**Comment by pippinsplugins** [comment]
Some minor changes requested on PR.

**Comment by DrewAPicture** [comment]
@pippinsplugins I've updated the PR with changes addressing your feedback.

**Comment by pippinsplugins** [comment]
Looks and works great, merged!
