### ISSUE TITLE
Introduce a standardized method for building admin URLs

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1770]
Upon reflection working on #1080 and generally throughout the code base, it seems like we could benefit from adding a generic function or group of functions for generating admin URLs. For instance, we almost always pass a `page` query argument, we're almost always linking to admin.php and there's some other consistencies.

I think probably the most useful approach would be to introduce something like this as a base, either at the top level or under `affiliate_wp()`:

``` php
affwp_admin_url( $type, $query_args = array() );
// or
affiliate_wp()->admin_url( $type, $query_args = array() );
```

And then have object-specific wrappers for it at the top level, e.g.

``` php
affwp_admin_referrals_url( $query_args = array() );

// Example
$link = sprintf( '<a href="%1$s">%2$s</a>',
    affwp_admin_referrals_url( array(
        'affiliate_id' => $affiliate_id
    ) ),
    __( 'View Affiliate Referrals', 'affiliate-wp' )
);

// Which essentially replaces
$link = sprintf( '<a href="%1$s">%2$s</a>',
    esc_url( add_query_arg( array(
        'page' => 'affiliate-wp-referrals',
        'affiliate_id' => $affiliate_id
    ), admin_url( 'admin.php' ) ),
    __( 'View Affiliate Referrals', 'affiliate-wp' )
);
```

Doing this would allow us to drastically reduce code duplication in a whole bunch of places. And it would be simple work to add object-specific wrappers for affiliates, creatives, payouts, referrals, and visits since we already have standards in place for how our admin URLs are formed.

**Comment by ramiabraham** [comment]
Love this idea.

**Comment by DrewAPicture** [comment]
Started a PR: #1821 that introduces `affwp_admin_url()` and `affwp_admin_link()`.

**Comment by pippinsplugins** [comment]
This looks great!

**Comment by DrewAPicture** [comment]
@AffiliateWP/core This is ready for review.

It introduces `affwp_admin_url()` and `affwp_admin_link`() and implements it in ~28 files throughout core. To test, find pretty much any link in the AffWP admin that's supposed to link to another AffWP admin url and check it. Redirect URLs are also affected in this PR so testing some of the various routines that redirect would be helpful too. Note that this is largely a semantic change, the logic is simply wrapped in a new helper function, but it helps us standardize and cut down on duplication.

**Comment by pippinsplugins** [comment]
I can't break it! All looks good to me.

**Comment by DrewAPicture** [comment]
Gonna wait to merge this until after #1713 is in for #1707. Probably easier to merge that way than the other way around ;)

**Comment by DrewAPicture** [comment]
#1821 was merged.
