### ISSUE TITLE
Reports: Current month wrongly determined in last or first day of the month, depending of timezone

### ISSUE THREAD

**Issue by davefx** [AffiliateWP/AffiliateWP#1773]
I've detected that, depending on the local timezone, the current month could be wrongly determined the last day of the month, or the first day of the month.

**Comment by DrewAPicture** [comment]
This fix is going to need accompanying unit tests.

**Comment by davefx** [comment]
Unit tests added

**Comment by DrewAPicture** [comment]
@davefx Can you do me a favor and test out this simple change on your setup? https://cloudup.com/chnN8OrVViw

**Comment by davefx** [comment]
#1774 doesn't fix the problem: `$dates['m_start']`, in my configuration, keeps getting the wrong month, because of the `gmt_offset` wordpress option used in current_time function returns a value different than 0.

Remember that `date` expects a correct Unix time (in gmt), not a localized Unix time. Wordpress `current_time` function, depending on the `gmt_offset` option, is able to return a localized Unix time unless we add the `$gmt=1` parameter. 

If this is the case, all the dates calculated by `date` will be displaced as many hours as `gmt_offset` says.

I've discovered that the test cases I had created yesterday didn't actually test the problem. I've just uploaded two more test cases that make the problem to show up when calling `current_time` without `$gmt=1`. I've also included the patch from #1774, as in some cases the end of the month could be calculated in a wrong way.

**Comment by DrewAPicture** [comment]
Hi @davefx, so, the initial objection is absolutely going to be to avoiding globals, even if they're just for testing. We very explicitly avoid them in this code base. ;)

To that end, I wonder if something like this would produce similarly passing results in your setup: https://github.com/AffiliateWP/AffiliateWP/compare/master...davefx-patch-7

The new optional parameter in `affwp_get_report_dates()` should be enough to override the value of `$current_time` with whatever dates we want in terms of testing, and not introduce globals. Looking forward to your feedback.

**Comment by davefx** [comment]
These changes work perfectly.

The only objection would be that, in the current status, the line from which we have removed the error (the call to `current_time`) is still not tested in the unit tests, and reverting it to its prior status wouldn't make the tests to fail, so the unit tests are not testing what they should...

**Comment by davefx** [comment]
I've just uploaded a correction for the unit tests to #1772, where no globals are involved at all.
