### ISSUE TITLE
Improve performance of reports screen

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1775]
Semi-related: #1641

An oversight on my part when we refreshed the Reports screen in 1.9 was not properly segregating registration of the stats tiles and their corresponding queries. Right now, all tabs' tiles are registered, and therefore all of the underlying queries are run for the tiles in those tabs, whether they're in the active tab or not. _Yikes_.

As a corollary to this issue, some legacy code is causing the `get_data()` methods in the Graph sub-classes to _also_ run when each of the tabs is registered, which happens on every.

Let's fix this so there aren't multi-hundreds of extra queries running on every page load, shall we?

**Comment by DrewAPicture** [comment]
Attached a PR: #1776

**Comment by pippinsplugins** [comment]
@DrewAPicture PR #1776 breaks the report tiles for the referrals tab.

On `master`:
![screen shot 2016-11-01 at 10 20 29 am](https://cloud.githubusercontent.com/assets/1034109/19894954/e2867608-a01c-11e6-91ea-f43acea03d30.png)

On `issue/1775`:
![screen shot 2016-11-01 at 10 21 18 am](https://cloud.githubusercontent.com/assets/1034109/19894973/f18bdd50-a01c-11e6-9e0e-f542d41fd03e.png)

Interestingly, if you load the referrals reports (no tiles are shown), then load the affiliates tab and _then_ switch back to the referrals tab, the tiles show.

**Comment by DrewAPicture** [comment]
@pippinsplugins The issue you reported was due the Referrals tab being the default the `tab` not being set in the query string. I've changed course and only registered the tiles for the tab currently being displayed regardless of whether `tab` is set or not. Please retest and merge at will :-)

**Comment by pippinsplugins** [comment]
Looks good!
