### ISSUE TITLE
Move log out link to end of tabs

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1778]
There are add-ons that use the `affwp_affiliate_dashboard_tabs` action hook to insert a new tab into the Affiliate Area. Since the log out link is added before this hook, the add-on tabs will always appear after the log out link.

I propose we move the log out link after the hook so it's always the last tab of the Affiliate Area.

**Comment by michaelbeil** [comment]
Looks good here!
