### ISSUE TITLE
Update LifterLMS integration

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1781]
It appears like LifterLMS v3+ broke our integration, so we need to assess the situation to see what we need in order to get the integration working. 

v3 was released just 28 days ago, but we were not aware of all of these changes: https://github.com/gocodebox/lifterlms/releases

**Comment by pippinsplugins** [comment]
What exactly broke? Does it fatal error? Does it not track sales? Need a bit more information please :)

**Comment by michaelbeil** [comment]
I did get a fatal error, but I think that was due to the version I cloned down from their repo. The AffiliateWP tab no longer shows on a course.

**Comment by thomasplevy** [comment]
@michaelbeil please see pull #1790, should resolve any issues you might be seeing

**Comment by michaelbeil** [comment]
Works great @thomasplevy! Thanks.

**Comment by thomasplevy** [comment]
thank you all @michaelbeil

**Comment by pippinsplugins** [comment]
@sumobi able to test this as well?

**Comment by sumobi** [comment]
The AffiliateWP tab is now correctly shown on a course page. I am however having trouble purchasing a course on my local set up so I haven't been able to test an actual referral. 

Using PayPal (the only gateway I can see that's availble) I get:

> There was an error connecting to the payment gateway.

@michaelbeil Can you confirm referrals are working ok and at the correct amount? Is it working locally for you?

**Comment by sumobi** [comment]
@thomasplevy When creating a new coupon, the `admin` affiliate is automatically assigned, which means all coupons created will be attributed to this affiliate. It should be blank by default.

**Comment by sumobi** [comment]
Ok, tested live and all looks good (minus the coupon issue)

**Comment by michaelbeil** [comment]
Just added https://github.com/AffiliateWP/AffiliateWP/commit/70a0dc11161f4d48e90bd985a8131b3118e4e42f to fix the LifterLMS coupon issue.

**Comment by michaelbeil** [comment]
I think we are good to merge here.
