### ISSUE TITLE
Sort the affiliate column alphabetically

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1788]
​The affiliate column sorting on the admin referrals screen is done by the affiliate ID associated with that affiliate currently. I wonder if it might be worthwhile to look into sorting that affiliate column alphabetically in the future.

**Comment by DrewAPicture** [comment]
I actually referenced this problem in another issue but I don't remember which one it was. It was something related to either column sorting on one of the list tables or showing different information. Sorry for the vagueness. I'll look around.
