### ISSUE TITLE
Slow: Affiliate_WP_Settings::check_license

### ISSUE THREAD

**Issue by nhadsall** [AffiliateWP/AffiliateWP#1789]
Hi,
I totally get the need to check license requirements, but a current client has a very slow backend. One of the contributors is AffiliateWP. The Affiliate_WP_Settings::check_license function runs twice on each page load and adds an additional 0.6ms to each page load. That may not seem like a lot, but if each of her 20 plugins did that, we would have to wait 10 seconds to get the backend of the site.

Can we perhaps cache this in the DB to check once a day?

**Comment by pippinsplugins** [comment]
It is cached in a transient for a week at a time. Sounds like the site's
object caching is getting in the way. Temporarily deactivate OC let us know
if that resolves it.

**Comment by nhadsall** [comment]
@pippinsplugins The level of support you guys give is a bit crazy :) You are absolutely right! They are using memcached, through Total Cache. I bet the VPS just doesn't have enough ram. Thanks!

**Comment by pippinsplugins** [comment]
No problem, happy to help! Going to close this but feel free to reopen if you continue to run into issues!
