### ISSUE TITLE
www.domain.com or domain.com not accepted as a valid URL

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1792]
You can't use `www.domain.com` or even `domain.com` as a valid URL on the affiliate registration form (tested in firefox and chrome)

You will see:

> Please enter a valid website URL

I've seen 3 or more tickets on this so far. This is significant barrier for those signing up to become affiliates, and most won't know to add the domain protocol (e.g.http://). WP core allows both `www.domain.com` and `domain.com` as valid URLs when editing a user profile so we should also allow this.

**Comment by sumobi** [comment]
Ready for testing

**Comment by pippinsplugins** [comment]
See feedback on PR.

**Comment by pippinsplugins** [comment]
Ok I'm happy with PR.

**Comment by sumobi** [comment]
@michaelbeil want to give it a test?

**Comment by DrewAPicture** [comment]
Looks good to me.
