### ISSUE TITLE
License keys not activating

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1794]
Every day there seems to be at least one ticket where the customer cannot activate their license key. 

The current steps to resolve the issue (works every time in my experience) are:

1. On the Affiliates -> Settings -> General screen, remove the license key from the License Key field
2. Click Save Changes at the bottom of the screen
3. Enter the license key again into the License Key field
4. Click the Activate License button to activate the key

Current causes of a license key not activating are:

1. Caching
2. Something (i.e. plugin) blocking the connection to the AffiliateWP site

When testing locally I can replicate some kind of issue. If I enter the license key and click activate, the license key field is cleared out and it doesn't show as activated. Upon entering the license key again and clicking activate, it works. Perhaps the customer doesn't try the second time and thus opens up a support ticket.

After the initial activation, clicking "Deactivate License" and "Activate License" works every time. To replicate the issue I experienced above you have to:

1. Click "Deactivate license"
2. Remove the license key from the input field entirely
3. Click "Save changes"
4. Enter license key and click "Activate License"

What can we do to improve license key activation? I feel like it used to work flawlessly, a license key not activating correctly isn't the best first impression.

**Comment by pippinsplugins** [comment]
Sounds like the activation function is pulling from settings instead of pulling from `$_POST`.

**Comment by pippinsplugins** [comment]
Hmm, no, it should be pulling from post properly.

@sumobi do you have `AFFILIATEWP_LICENSE_KEY` defined?

**Comment by sumobi** [comment]
@pippinsplugins No I don't have `AFFILIATEWP_LICENSE_KEY ` defined. 

I actually just ran into the same problem I was facing on a customer's site. Had to activate the license key twice. First time was blank and nothing happened, second time it worked fine.

**Comment by DrewAPicture** [comment]
I'm going to take a look at this (again). I have a feeling this has to do with not explicitly relying on `$_POST` data every step of the way.

How it _should_ work:

* Input the license key in the box manually or populate it via the constant
* Submit the form to activate and solely use the `$_POST` data to determine activation

**Comment by pippinsplugins** [comment]
PR looks good at first glance.

@sumobi please test to confirm that it still works with the key defined in wp-config. It should but just to be thorough.

**Comment by michaelbeil** [comment]
All works well here with license activation as well as with the AFFILIATEWP_LICENSE_KEY constant.

**Comment by sumobi** [comment]
It seems to activate the license key ok now 👍 

One small thing, you now cannot remove the license key. If you remove it and save the settings, the license key is still there.

**Comment by sumobi** [comment]
One more thing and I can't recall how it used to work, but when using the constant it says this:

> Your license key is globally defined via AFFILIATEWP_LICENSE_KEY set in wp-config.php. It cannot be modified from this screen.

However I can still deactivate and activate the license key. So we need to either:

1. Change the text 
2. Make it so when the constant is defined there's no button. The input is correctly set to readonly.
3. Make it so when the constant is defined it doesn't even show the license key at all (no input, no button). 

I prefer the third option. This will be useful when a site owner wants to enter the license key once (via the wp-config.php file) and also does not want anyone seeing what the key is. For instance, they might be running a network of sites, offering an affiliate system to each sub-site.

**Comment by DrewAPicture** [comment]
@sumobi 
> One small thing, you now cannot remove the license key. If you remove it and save the settings, the license key is still there.

I was able to remove it and save the settings and it wasn't there when the page refreshed. This is obviously only possible when the constant isn't set.

> However I can still deactivate and activate the license key.

I think you're conflating the key being present in the input with activation. They are intentionally different workflows. The key will always be populated, activated or not, if the constant is defined.

**Comment by DrewAPicture** [comment]
> and also does not want anyone seeing what the key is

I could be in favor of obfuscating the key once entered as a password-ish field.

**Comment by DrewAPicture** [comment]
See #1402 for the suggestion to auto-activate (thereby merging the entry and activation workflows present when the constant is defined).

**Comment by sumobi** [comment]
@DrewAPicture 

> I was able to remove it and save the settings and it wasn't there when the page refreshed. This is obviously only possible when the constant isn't set.

Constant is not set, I can't remove the key on save. 

>  They are intentionally different workflows. The key will always be populated, activated or not, if the constant is defined.

If the text says "It cannot be modified from this screen." then something is wrong since I can modify the key by activating or deactivating it.

> I could be in favor of obfuscating the key once entered as a password-ish field.

I don't think we need to keep the field at all. What would be the point if the key is entered in wp-config.php? We allow the constant so a site-owner can network activate the license. @AffiliateWP/core thoughts?

**Comment by sumobi** [comment]
Oh right, I see, forgot how it worked. So the license key doesn't actually auto activate, heh. In that case it works as intended.

**Comment by DrewAPicture** [comment]
> I don't think we need to keep the field at all. What would be the point if the key is entered in wp-config.php? We allow the constant so a site-owner can network activate the license. 

We need to keep the field because core needs to rely on using the value passed from `$_POST`, which is what caused the bug reported in this ticket in the first place. We could certainly obfuscate it though or even completely hide the field, but we should keep the field regardless ;)

**Comment by sumobi** [comment]
👍
