### ISSUE TITLE
Revenue of product author 

### ISSUE THREAD

**Issue by AiratHalitov** [AffiliateWP/AffiliateWP#1797]
Can you add support of revenue of author in product settings? 
I mean that one partner (author of product) who will get persent of sales by default.

I think it will be usefull feature for your plugin.

**Comment by pippinsplugins** [comment]
That kind of feature is best handled through a "vendor commissions" plugin, such as WooCommerce Product Vendors or Easy Digital Downloads Commissions.

Vendor commissions are not the same thing as affiliate commissions.
