### ISSUE TITLE
REST API: add support for including affiliate metadata

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#1801]
This data is a required field for an upcoming pro add-on feature ([issue link](https://github.com/AffiliateWP/affiliatewp-zapier/issues/17)). 

Implementing this would avoid us having to define custom queries for core object REST API polling responses.

**Comment by ramiabraham** [comment]
(Updated title to reflect that _all_ available object meta should be present in core objects endpoints).

**Comment by pippinsplugins** [comment]
Per discussion in Slack, we're going to leave the name out. If name needs to be retrieved, add `?user=1` to the query. That will result in the user data being returned:
```
{
  "affiliate_id": 1,
  "user_id": 2,
  "rate": "",
  "rate_type": "percentage",
  "payment_email": "pippin@pippinspages.com",
  "status": "active",
  "earnings": 379,
  "referrals": 15,
  "visits": 28,
  "date_registered": "2014-12-14 23:47:28",
  "user": {
    "ID": "2",
    "user_login": "jimbo",
    "user_nicename": "jimbo",
    "user_url": "",
    "user_registered": "2014-12-12 02:25:40",
    "user_status": "0",
    "display_name": "jimbo",
    "spam": "0",
    "deleted": "0",
    "first_name": "Jimbo",
    "last_name": "John"
  },
  "id": 1
},
```

For meta data, it will be best to avoid automatically adding metadata to response objects as that requires additional queries. Let's add an option for including meta via the API query, just like `user=1`. I propose `meta=1` to instruct the API to return metadata.

Zapier can then append `?user=1&meta=1` to the affiliate queries in order to get this data.

**Comment by DrewAPicture** [comment]
Added a PR that adds `?meta=1` support to retrieve affiliate meta: #1802

**Comment by pippinsplugins** [comment]
@ramiabraham Can you test this with Zapier please?

**Comment by ramiabraham** [comment]
@pippinsplugins Tested and implemented in Zapier app - added to latest build when relevant

**Comment by pippinsplugins** [comment]
PR looks good! Let's leave it open until fully confirmed as working on live site.

**Comment by DrewAPicture** [comment]
In the process of switching from a filter to a method that's forward-compatible with `register_rest_field()` or similar.

**Comment by DrewAPicture** [comment]
Currently forward-compatible with `register_rest_field()`. To test:

```php
add_action( 'plugins_loaded', function() {
	affwp_register_rest_field( 'affiliate', 'better_believe', array(
		'get_callback' => function( $object, $field_name, $request, $object_type ) {
			return "it's working!";
		}
	) );

	register_rest_field( 'affwp_affiliate', 'better_believe_this', array(
		'get_callback' => function( $object, $field_name, $request, $object_type ) {
			return "one works too!";
		}
	) );
} );
```

**Comment by pippinsplugins** [comment]
PR looks great to me.

@ramiabraham could you get Zapier updated for this? Once it's confirmed to work as expected, we can merge this into core.

**Comment by ramiabraham** [comment]
@pippinsplugins 

I get an `undefined $request` error when adding the following to affwp-zapier with AffiliateWP at `issue/1801`:

```php
function affwp_zapier_add_affiliate_name() {

    affwp_register_rest_field( 'affiliate', 'affiliate_name', array(
	        'get_callback' => function( $object, $field_name, $request, $object_type ) {
	        	$affiliate_name = affwp_get_affiliate_name( $object->affiliate_id );
	            return $affiliate_name;
	        }
    	)
    );
}

add_action( 'plugins_loaded', 'affwp_zapier_add_affiliate_name' );
```

The field is not appended to the affiliate object:

![ALT_TEXT](https://cldup.com/diUiqZ7Vgi.png "TITLE")

**Comment by ramiabraham** [comment]
I also tried using the same anonymous function implementation above, as well as both tests with `referral` objects, which behaved the same. The returned `referral` object is:

```json
{
    "referral_id": 13224,
    "affiliate_id": 38,
    "visit_id": 0,
    "description": "desco inferno",
    "status": "paid",
    "amount": "5.00",
    "currency": "USD",
    "custom": "",
    "context": "testing",
    "campaign": "",
    "reference": "",
    "products": "",
    "date": "2016-09-10 22:01:35",
    "payout_id": "49",
    "id": 13
  }
```

**Comment by DrewAPicture** [comment]
@ramiabraham I just dropped your code it and it appended the field. No other changes.

![affiliate_name](https://cl.ly/0I2v402k1z45/Screen%20Shot%202016-11-10%20at%208.06.15%20PM.png)

Hmm.

**Comment by ramiabraham** [comment]
@DrewAPicture Thanks - I'm sure it's my error somewhere the line.

@pippinsplugins Added to Zapier add-on in https://github.com/AffiliateWP/affiliatewp-zapier/commit/549b3f036d488ca918d9fbe41d52660578a0f21d.

**Comment by pippinsplugins** [comment]
@ramiabraham I'm not seeing Affiliate Name as an option in the Zap.

Updated to `master` on the live site.

**Comment by DrewAPicture** [comment]
As discussed in Slack, the problem is that the field is being registered on `plugins_loaded`, which has already fired by the time the file containing the `add_action()` call is loaded. The solution would be to hook to `rest_api_init` or another action that fires after `plugins_loaded`.
