### ISSUE TITLE
404 and memory error messages in product pages and orders after update to 1.9.4

### ISSUE THREAD

**Issue by fernandotellado** [AffiliateWP/AffiliateWP#1803]
I've need to downgrade to 1.8.8 in order to edit products in my woocommerce because when I update to the last version every time I click on a product to edit it resolves an 404 error.

Also, if I try to view or edit an order the system shows only an ugly error like this one:

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 2611340136448 bytes) in /xxxx/xxxx/public_html/servicios/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-assets.php on line 215

:(

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://affiliatewp.com/support. We will be happy to hel.

we use GitHub for development tracking only.
