### ISSUE TITLE
Add " Unpaid Earnings" column to Affiliates screen 

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1804]
Per the implementation of https://github.com/AffiliateWP/AffiliateWP/issues/1611, it would be nice to also show an `Unpaid Earnings` column on the affiliates screen. 

After https://github.com/AffiliateWP/AffiliateWP/issues/1228 is done, this data will be easier to retrieve.

**Comment by DrewAPicture** [comment]
Closing in favor of #1228, where this is being included.
