### ISSUE TITLE
Reduce unnecessary settings queries in the admin

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1805]
As reported by a customer, there are several extra queries that run in the admin that don't need to run on every page. Let's clean up a little bit.

**Comment by DrewAPicture** [comment]
PR: #1806

**Comment by michaelbeil** [comment]
Looks good here when I view the queries in QM. Are there specific queries to watch out for?

**Comment by pippinsplugins** [comment]
@DrewAPicture this breaks settings save and triggers a wp_die() with `ERROR: options page not found.`

**Comment by DrewAPicture** [comment]
I've removed the code that bails early after not being able to find a way to have it both ways. Tracking other options in [AFGF/21](https://github.com/AffiliateWP/affiliatewp-affiliate-forms-gravity-forms/issues/21).

**Comment by DrewAPicture** [comment]
@michaelbeil See the AFGF issue for more information on specific queries.
