### ISSUE TITLE
affwp_referral_action_links filter accidentally removed

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1810]
We used to have a filter called `affwp_referral_action_links` on the referrals list table. This has been accidentally renamed to `affwp_referral_row_actions`.

I suspect this happened with https://github.com/AffiliateWP/AffiliateWP/issues/1528

**Comment by pippinsplugins** [comment]
This has resulted in row actions added by the payout add-ons no longer showing up. It could be causing issues with other add-ons as well that relied on the `affwp_referral_action_links` filter.

I suspect we've lost the filter for all list tables.

**Comment by DrewAPicture** [comment]
Looking at 1.8.8, the previous action names for affiliates and creatives were `affwp_affiliate_row_actions`, `affwp_creative_row_actions`, respectively. Visits had no action links and Payouts didn't exist. So I think the referral hook is the only one affected.

**Comment by DrewAPicture** [comment]
Added a PR: #1811
