### ISSUE TITLE
Unable to remove coupon code affiliate discount

### ISSUE THREAD

**Issue by michaeltieso** [AffiliateWP/AffiliateWP#1813]
It won't let me remove the association of a coupon code in WooCommerce tied to the admin user creating the coupon code. Admin is also an affiliate.

![screenshot](http://cld.wthms.co/YETj/AzJLuxWn+)

**Comment by DrewAPicture** [comment]
Hi @michaeltieso, thanks for the report. We're already tracking this issue over in #1689.
