### ISSUE TITLE
Referral not moving from Rejected to Unpaid

### ISSUE THREAD

**Issue by michaeltieso** [AffiliateWP/AffiliateWP#1814]
Using WooCommerce if a credit card is rejected, the status of the order is moved to Rejected. This results in the referral being rejected. In this instance however the customer later resolves the order and moves to Completed. The referral stays rejected and doesn't move to Unpaid.

Email was also fired even though the card was declined.

![screenshot](http://cld.wthms.co/HSs1/1PrqvaEk+)

**Comment by pippinsplugins** [comment]
@michaelbeil do you have the option enabled to auto reject referrals? It's in the Misc tab,

Related https://github.com/AffiliateWP/AffiliateWP/issues/1752

**Comment by michaeltieso** [comment]
@pippinsplugins Yes, it's enabled. Looks like it is related to that the issue you pointed out. Second issue I've reported that already had an issue that I couldn't find :(. I suppose we can close?

**Comment by pippinsplugins** [comment]
@michaelbeil Not a problem :) We'll close this one and track the other.
