### ISSUE TITLE
Affiliate link styles / Custom link formats

### ISSUE THREAD

**Issue by zackkatz** [AffiliateWP/AffiliateWP#182]
Instead of having all links use the same format, defined by the admin, allow affiliates to choose their own link structure:

* Default (query parameter): `example.com/buy/?ref=123`
* Rewrite (WP_Rewrite): `example.com/buy/123/`
* Anchor links (JS required): `example.com/buy/#ref=123`

See http://www.postaffiliatepro.com/features/affiliate-link-styles/

**Comment by sumobi** [comment]
Closing this since we have query string affiliate links, pretty affiliate links, custom slugs and now direct link tracking
