### ISSUE TITLE
Google reCAPTCHA

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1822]
Looks like v1.9.5 accidentally broke Google reCAPTCHA, the required .js file is no longer being enqueued (only registered).

@DrewAPicture can you make this top priority and push out a point release as soon as possible? Since the .js file isn't being loaded, a lot of affiliate registration forms will no longer work (validation will say nopeee).

v1.9.4
https://github.com/AffiliateWP/AffiliateWP/blob/1.9.4/includes/scripts.php#L135-L137

vs 

v1.9.5
https://github.com/AffiliateWP/AffiliateWP/blob/1.9.5/includes/scripts.php

**Comment by sumobi** [comment]
Are we all in agreement that we'll enqueue the Google reCAPTCHA JS on every page when enabled like the forms JS? (see PR). Apart from loading an extra .js file, I don't think it will cause a JS error on other pages.

@DrewAPicture What does this do? https://github.com/AffiliateWP/AffiliateWP/blob/1.9.5/includes/scripts.php#L145

**Comment by michaelbeil** [comment]
I would be more prone towards not loaded our forms JS nor the Google reCAPTCHA JS on every page when enabled. Although, I suppose herein lies that issue, we do not know which pages will have the forms or reCAPTCHA added to them.
