### ISSUE TITLE
Affiliate added notice is incorrect when manually adding an affiliate in 1.9.5+

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1824]
Looks like the notice modifications made in #397 for the migration scripts introduced a bug when adding affiliates manually in the admin. It appears to be be caused by making an assumption that the count will only come from a migration script. Whoops!

This is the notice shown after adding an affiliate manually.
> 0 affiliates were added successfully

**Comment by sumobi** [comment]
Just ran into this 👍 

<img width="1108" alt="screen shot 2016-12-11 at 10 13 48 pm" src="https://cloud.githubusercontent.com/assets/52581/21086943/2e7ad5a8-bfef-11e6-9844-4413157ce493.png">

**Comment by DrewAPicture** [comment]
Added a PR: #1866 

*To test:*
1. Create a new user account (do NOT add them as an affiliate at this point).
2. Navigate to Affiliates > Affiliates.
3. Click Add New
4. Enter the username of your new user account
5. Click the *Add Affiliate* button.
6. Note that the admin notice at the top reflects the following text: "1 affiliate was added successfully."

**Comment by pippinsplugins** [comment]
Works great.
