### ISSUE TITLE
Add schema support to core REST routes and endpoints

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1825]
This is a companion project to the pro REST API add-on currently in development. The new writeable and editable endpoints require schema support to build their respective argument lists. We _could_ do it as a shim in the add-on, but I think the best route forward would be to add the schema support to core, and then simply require 1.9.x or 2.x for the add-on to operate.

My best suggestion would be to continue in the v1 namespace regardless of the pending 4.7 release. And then when we're ready (and tested) we can do a v2 leveraging the core controller and API.

Must haves:

* [x] `get_endpoint_args_for_item_schema()` method shim in the controller
* [x] `add_additional_fields_schema()`
* `get_item_schema()` methods in the core endpoint classes (and thereby reuseable by add-ons extending the core endpoints
* [x] `get_item_schema()` Affiliates
* [x] `get_item_schema()` Creatives
* [x] `get_item_schema()` Payouts
* [x] `get_item_schema()` Referrals
* [x] `get_item_schema()` Visits
* will update as other stuff comes up

**Comment by DrewAPicture** [comment]
Started a PR: #1826

**Comment by pippinsplugins** [comment]
:+1:

**Comment by DrewAPicture** [comment]
@pippinsplugins The PR: #1826 is ready for review. All v1 create/edit/delete endpoints have been [implemented](https://github.com/AffiliateWP/affiliatewp-rest-api/issues/3) in the pro add-on and rely on these item schema.

**Comment by pippinsplugins** [comment]
Noticed a few errors in the text strings. See PR.

**Comment by DrewAPicture** [comment]
All feedback has been addressed.

**Comment by pippinsplugins** [comment]
@DrewAPicture where exactly can I see the schema output? At the top level REST endpoint?

**Comment by DrewAPicture** [comment]
Answered in Slack, but for posterity, you can either use the main discovery endpoint at /affwp/v1 or send an `OPTIONS` request to the endpoint for a single core object, e.g. `affwp/v1/affiliate/###` where `###` is an actual affiliate ID.

**Comment by pippinsplugins** [comment]
Excellent. Looks great here!

**Comment by pippinsplugins** [comment]
Just gave this another look. Everything looks great!

**Comment by DrewAPicture** [comment]
This is done.

**Comment by pippinsplugins** [comment]
Woot!
