### ISSUE TITLE
affwp_add_creative() should return the new creative ID on success

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1827]
PR: #1827

For reasons, it would be helpful for `affwp_add_creative()` to operate the same way as `affwp_add_affiliate()` et al in returning the newly-created creative ID rather than simply true.

Attached PR includes a test showing the old test still passes based on the truthy return.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
PR looks good.
