### ISSUE TITLE
Add support for user-defined locales

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#1834]
WordPress 4.7 introduces `get_user_locale` ([changeset](https://core.trac.wordpress.org/changeset/38705)), which falls back to the standard `get_locale`.

Let's update our `load_textdomain()` loader method ([link to proposed affected line](https://github.com/AffiliateWP/AffiliateWP/blob/master/affiliate-wp.php#L504)) to support user locales.

**Comment by ramiabraham** [comment]
Added a PR: https://github.com/AffiliateWP/AffiliateWP/pull/1835

**Comment by pippinsplugins** [comment]
Looks good!

**Comment by michaelbeil** [comment]
Celebrate good times now.

**Comment by ramiabraham** [comment]
Cool cool, merged.

**Comment by ramiabraham** [comment]
New PR with small adjustment: https://github.com/AffiliateWP/AffiliateWP/pull/1836

**Comment by DrewAPicture** [comment]
Let's punt #1836 to 2.0. There's a whole bunch of other places we could use the helper:

* `affiliate-wp.php`
* `affiliatewp/includes/class-affiliates-db.php`
* `affiliatewp/includes/class-creatives-db.php`
* `affiliatewp/includes/class-payouts-db.php`
* `affiliatewp/includes/class-referrals-db.php`
* `affiliatewp/includes/class-visits-db.php`
* `affiliatewp/includes/admin/AFFWP_Plugin_Updater.php`
* `affiliatewp/includes/admin/class-addon-updater.php`
* `affiliatewp/includes/admin/tools/tools.php`
* `affiliatewp/tests/test-rest.php`
