### ISSUE TITLE
Send admin email when new referral is generated

### ISSUE THREAD

**Issue by lisag** [AffiliateWP/AffiliateWP#1839]
We do have a code snippet for this, but I think it would be a great feature for core: https://github.com/AffiliateWP/affiliatewp-code-snippet-library/blob/master/emails/admin-referral-sale-email.php

**Comment by wordmaid** [comment]
Another request: https://secure.helpscout.net/conversation/285048243/48257/?folderId=205524

**Comment by gspice** [comment]
Another asking about it, would be a great checkbox to have in the Settings => Email tab.  I know this gal is not savvy enough to handle a code snippet. 

https://secure.helpscout.net/conversation/313940261/52268/?folderId=1170842

**Comment by pippinsplugins** [comment]
Note: this could be easily done with the Zapier add-on.

**Comment by gspice** [comment]
Another for this: 
https://secure.helpscout.net/conversation/354886064/58018/?folderId=1170842

**Comment by puternutt** [comment]
It'd be nice to add another function in this code to send the referring affiliate the email if their affiliate ID received a referral to inform them of the same. Admins are not typically the affiliate program owner, they are the website administrator. So we have to send the owner the email once we receive it. Or just delete it. So sending it to the admin is useless in most cases for a nonOneMan Shop.

**Comment by gspice** [comment]
@puternutt You can do this now if the setting is enabled in the affiliate area under the **Settings** tab.  The affiliate has to opt-in to receive the email notifications.

**Comment by puternutt** [comment]
where in the AffiliateWP Dashboard settings do I ensure that this is capable of being shown to them in the affiliate area?

**Comment by gspice** [comment]
@puternutt There is a screenshot of the Settings page at the bottom of this page in our docs:  
http://docs.affiliatewp.com/article/54-creating-the-affiliate-area

**Comment by puternutt** [comment]
got it, thanks,

**Comment by pippinsplugins** [comment]
PR ready for testing.

**Comment by amdrew** [comment]
@pippinsplugins 👍 Works great, left a couple of small things on PR.
