### ISSUE TITLE
Add conversion rate to admin affiliate reports

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1841]
We don't currently show the conversion rates for affiliates when viewing individual affiliate reports. We should show it to site admins.

**Comment by sumobi** [comment]
Added to the top right of the individual affiliate reports screen:

<img width="1366" alt="screen shot 2016-12-12 at 11 37 49 am" src="https://cloud.githubusercontent.com/assets/52581/21107368/6faae7f0-c05f-11e6-997f-5e23104db2af.png">

**Comment by sumobi** [comment]
@AffiliateWP/core ready for testing

**Comment by sumobi** [comment]
@pippinsplugins I think we should also show in on the exported affiliates .csv file, do you agree?

**Comment by pippinsplugins** [comment]
>>> I think we should also show in on the exported affiliates .csv file, anyone agree/disagree?

I agree.

**Comment by sumobi** [comment]
Done
