### ISSUE TITLE
Only 20 campaigns are shown on the affiliate area

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1842]
We're only showing 20 campaigns on the statistics tab of the Affiliate Area:
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/class-campaigns-db.php#L85

Related: pagination https://github.com/AffiliateWP/AffiliateWP/issues/1720

@AffiliateWP/core Thoughts on making this show all campaigns, at least until we get pagination?

**Comment by DrewAPicture** [comment]
@sumobi I think we can look at a happy medium. I don't really want to run into a scaling situation by showing them _all_ without pagination, so I've added a PR that bumps the count to 100.

PR: #2010 includes a test.

**Comment by pippinsplugins** [comment]
100 seems like a decent compromise for the time being, at least until we get some form of pagination in for campaigns.
