### ISSUE TITLE
Referrals cannot be filtered when using specific languages

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1845]
A customer has reported that when their language is set to German, and they try to filter Referrals for a specific date period, they are unable to, even though referrals do exist within that date period. https://secure.helpscout.net/conversation/287085822/48541/?folderId=414056

I have replicated this on a local installation of AffiliateWP as well, after changing the language to German. I get the error `NaN, undefined` when trying to filter by specific dates.

Is anyone else able to replicate this, and could it be an error with the translation file?

**Comment by sumobi** [comment]
Haven't been able to replicate this (tried WP 4.6 and 4.7)

**Comment by sumobi** [comment]
I was only testing the calendar to try and replicate the `NAN` error but yes I can replicate the referrals not being filtered correctly when using other languages. 

If you select French, German or Italian, the referrals are not filtered correctly. For example, try using the first calendar to choose a date at the time when you know there were referrals. If you then filter, it will show referrals that were before the start date. If you also add an end date, no referrals are found.

Switch back to English and the issues are gone.

**Comment by wordmaid** [comment]
Ok, I have now tried this with German, French, Spanish and Italian, and replicated the issue each time. Referrals cannot be filtered by date when the language has been changed from English. 

To replicate:
- I chose a period that I knew I had several Unpaid referrals (30+)
- I changed my language in General -> Settings to German, French, Spanish and Italian each time whilst testing
- I went to the Referrals screen and entered the date period which had Unpaid referrals
- No referrals are visible.

When in English, the referrals are shown correctly.

The `NaN undefined` error now appears to be random, sometimes it shows and sometimes it does not.

**Comment by wordmaid** [comment]
It appears this might be a bit more serious than I initially thought. I have tried testing this with several additional languages on top of the original four I tried, and it appears that anyone who is using AffiliateWP in a different language _cannot_ generate a CSV payout file when they define specific dates in the CSV date filter. As it does not export any referrals into a CSV file, it does not change the status of the referrals either (they are not marked as Paid).

As per the original issue, the date filter to search for referrals within a set period (to then use the bulk actions menu) also does not work. This will be an issue for PayPal Payouts users with the Pay Now bulk action. 

@pippinsplugins @DrewAPicture I noticed this has been re-milestoned for 2.0.2, and there is obviously a long list of things to do between now and then, but it seems like this might be quite a major bug that may be worth looking into sooner. Over to you!

**Comment by pippinsplugins** [comment]
I'm going to look at this further today.

**Comment by pippinsplugins** [comment]
I've replicated the problem as well.

**Comment by pippinsplugins** [comment]
Looks like it is failing due to localized dates:
```
[date] => Array
        (
            [start] => Dezember 1, 2016
            [end] => Dezember 8, 2016 23:59:59
        )
```
