### ISSUE TITLE
Membermouse: Incorrect affiliate awarded commission

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1846]
I've been troubleshooting a customer's site running AffliateWP v1.8.8 whereby the referral isn't being created for non-free products. Decided to upgrade them to 1.9.5.1 and the referral seems to be created, however it awards it to the wrong affiliate.

`/ref/16` should award the commission to the Affiliate with an ID of `16`. It actually awarded it to the Affiliate with an ID of `8`. Upon looking at the affiliate's edit screen I noticed they have a user ID of `16`. I'd say this is the issue.

**Comment by sumobi** [comment]
Had this happen again but this time the referral was assigned to the previous affiliate (ID of 13, not 8) which makes me think there's some kind of caching issue. I checked the affiliate ID in the browser cookies all the way to purchase and credit last referrer is turned off. Definitely something happening here.

**Comment by sumobi** [comment]
Super hard to replicate, only replicated each outcome twice, it could be related to the customer's server and cookie creation. Going to sit on this for a while.

**Comment by pippinsplugins** [comment]
@sumobi what do the MM cookies look like? Do they include the correct affiliate ID?

**Comment by sumobi** [comment]
@pippinsplugins I can't recall sorry, If I run into the issue again I'll be sure to check that out.

**Comment by pippinsplugins** [comment]
My money is on the MM cookie being incorrect, which would perfectly explain the behavior we see here.

**Comment by sumobi** [comment]
It could even have been that I deleted the affwp cookies when testing, but forgot to clear the MM cookie. Happy to close this for now until the issue crops up again.
