### ISSUE TITLE
Enqueue dashicons only when necessary?

### ISSUE THREAD

**Issue by mgibbs189** [AffiliateWP/AffiliateWP#1847]
includes/scripts.php:117

```php
wp_register_style( 'affwp-forms', AFFILIATEWP_PLUGIN_URL . 'assets/css/forms' . $suffix . '.css', array( 'dashicons' ), AFFILIATEWP_VERSION );
```

Is it absolutely necessary to enqueue `dashicons` on every page?

Thanks

**Comment by pippinsplugins** [comment]
We should be able to improve that. No reason that I can think of to load it everywhere.

Related #1670

**Comment by DrewAPicture** [comment]
Added a PR: #1865
