### ISSUE TITLE
Promotion Methods textarea improvements

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1851]
The textarea for the promotion methods on the edit affiliate screen is too small in my opinion, both vertically and horizontally.

<img width="734" alt="screen shot 2016-12-10 at 4 42 22 pm" src="https://cloud.githubusercontent.com/assets/52581/21076387/f955f62a-bef7-11e6-88db-6911d34f38ab.png">

I vote we made this consistent with WP core and also the new notes textarea field in #1468 

<img width="1206" alt="screen shot 2016-12-10 at 4 45 37 pm" src="https://cloud.githubusercontent.com/assets/52581/21076396/1b8463da-bef8-11e6-9b03-2204121940b1.png">

___

@AffiliateWP/core If there's no promotion method entered by the affiliate, it seems pointless having the field at all since it will be blank and isn't editable. Anyone agree/disagree?

**Comment by sumobi** [comment]
<img width="1192" alt="screen shot 2016-12-10 at 5 52 49 pm" src="https://cloud.githubusercontent.com/assets/52581/21076760/bf06047e-bf01-11e6-879a-79d13fd09de3.png">

**Comment by pippinsplugins** [comment]
Merged.
