### ISSUE TITLE
Conflict with Gravity Forms Recaptcha field

### ISSUE THREAD

**Issue by fxbenard** [AffiliateWP/AffiliateWP#1854]
Both plugins activated: The ReCaptcha field doesn't show on the site
AffiliateWP deactivated: Recaptcha is showing
FYI: it shows it the form preview

**Comment by sumobi** [comment]
Just ran into this on our affiliate registration form. Once I disabled `Enable reCAPTCHA` from Affiliates -> Settings -> Misc the reCAPTCHA field for the Gravity Form appeared fine.

**Comment by pippinsplugins** [comment]
JS errors?

**Comment by sumobi** [comment]
None that I can see. Looks like there may be a script (or possibly other stuff) that isn't loaded at all.

**Comment by sumobi** [comment]
I haven't dug into why this isn't working but here's what a customer found out:
 
> It looks like the problem is that both plugins enqueue https://www.google.com/recaptcha/api.js , but with different GET parameters. The AffiliateWP version is included in the HTML first, so api.js never gets called with the GET parameters Gravity Forms needs.

**Comment by DrewAPicture** [comment]
Added a PR that attempts to address the problem in two ways: #1873 

1. Enqueues the recaptcha script directly where it's needed (only)
2. Even then, only enqueues if `gform-recaptcha` hasn't been enqueued yet.

Both a standalone Gravity Form with a CAPTCHA field and the affiliate registration from with a reCAPTCHA appear to be working now.

_Added the i:GravityForms tag even though that isn't strictly accurate_.

**Comment by pippinsplugins** [comment]
Cool, I really like this solution.

@sumobi mind doing a quick test please?

**Comment by pippinsplugins** [comment]
Moved this to `2.0`.

**Comment by sumobi** [comment]
Works for me 👍

**Comment by pippinsplugins** [comment]
Merged into `release/2.0`.
