### ISSUE TITLE
Pagination breaks when referral variable is same as site's tld

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1863]
According to a customer:

>>>when using the TLD as the "referral variable" ('de' in our case), the pagination URLs break. (We get `https://www.siteurl.page/2/` instead of `https://www.siteurl.de/shop/page/2/`)

PR https://github.com/AffiliateWP/AffiliateWP/pull/1862

**Comment by DrewAPicture** [comment]
@pippinsplugins Did you actually manage to reproduce this pre-PR? I can't seem to do it.

**Comment by pippinsplugins** [comment]
I haven't yet but will try again.

**Comment by pippinsplugins** [comment]
I've replicated it!

**Comment by pippinsplugins** [comment]
PR works as well. Merged into `release/2.0`.

**Comment by jsphpl** [comment]
Thank you guys!
