### ISSUE TITLE
Fix error in ID display when listing creatives via wp-cli

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1870]
Missed a typo in the `array_map()` callback for listing creatives.

s/`$affiliate->creative_id`/`$creative->creative_id`.

**Comment by DrewAPicture** [comment]
PR: #1871

**Comment by DrewAPicture** [comment]
**To Test:**

1. In the command line, run `wp affwp creative create --name=Test`
2. Run `wp affwp creative list`
3. Note that the creative ID(s) are not all displayed with a value of `0`.

**Comment by pippinsplugins** [comment]
Looks good.
