### ISSUE TITLE
Make Referral ID in Visits screen link through to corresponding referral

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1874]
In the Visits screen there is a column called `Referral ID`, but it doesn't link through to the corresponding referral that was generated.

Similarly, no referral IDs are shown on the Referrals page (in its own column), nor is the referral ID shown on the Edit Referral page.

Proposed ideas:
- It would be useful to be able to click on the Referral ID shown in the Visits screen and be taken directly to the Edit Referral screen for the corresponding referral.

- Similarly, the Referral ID should be visible on the Edit Referral screen at the very least, and we should consider adding it in a column to the main Referrals screen.

**Comment by sumobi** [comment]
I think this would help with the confusion over the Referral ID column on the visits screen. Many customers think this is supposed to be the affiliate ID. 

It would be slick to be able to click the ID and go through to the actual referral.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by DrewAPicture** [comment]
Added a PR for linking the referral ID if set: #2009 

For visibility of the Referral ID on the Edit Referral screen, see #1906.

**Comment by pippinsplugins** [comment]
PR looks good to me!
