### ISSUE TITLE
Gravity Forms: Block referral if affiliate's email is used

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1878]
Currently the Gravity Forms integration does not check the submitted email address(es) to see if it could be the affiliate's. We should block the referral much like our other integrations if this is the case.

**Comment by sumobi** [comment]
@AffiliateWP/core Ready for testing (I have tested)

**Comment by pippinsplugins** [comment]
@sumobi looks good. One small change on the PR please.

**Comment by sumobi** [comment]
@pippinsplugins updated
