### ISSUE TITLE
Add unpaid earnings to exported affiliate .csv file

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1880]
Once https://github.com/AffiliateWP/AffiliateWP/issues/1804 is complete, let's also add this to the exported affiliates .csv file

**Comment by pippinsplugins** [comment]
Moved to 2.1 since #1804 is also set for 2.1.

**Comment by DrewAPicture** [comment]
Closing in favor of #1228, where this is included.
