### ISSUE TITLE
$affiliate_id = affwp_get_affiliate_id(); added 3 times

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1882]
We seem to now have `$affiliate_id = affwp_get_affiliate_id();` added 3 times to this template, and the rest of the template still uses `affwp_get_affiliate_id()`.

https://github.com/AffiliateWP/AffiliateWP/blob/release/2.0/templates/dashboard-tab-stats.php

Let's call `$affiliate_id = affwp_get_affiliate_id();` once at the top and then replace all instances of `affwp_get_affiliate_id()` with `$affiliate_id`.

Edit: there's some other files which are also affected.

**Comment by pippinsplugins** [comment]
Looks good, merged.
