### ISSUE TITLE
AffiliateWP PayPal integration causes conflict with LifterLMS PayPal gateway add-on, OptimizeMember, possibly others

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1884]
A customer experienced an issue when they were using LifterLMS and Lifter's PayPal payment gateway add-on. The customer had enabled both LifterLMS and PayPal Buttons integrations in AffiliateWP, even though they weren't using the PayPal Buttons integration. 

When the PayPal Buttons integration is enabled in AffiliateWP (though not necessary), along with LifterLMS and Lifter's PayPal add-on, the checkout hangs - likely due to a conflict between the PayPal integration in AffiliateWP, and Lifter's PayPal add-on.

When the PayPal Buttons integration is disabled in AffiliateWP, everything works just fine.

Just a little quirky bug that might be worth ironing out so customers don't experience this in the future.

Ticket ref: https://secure.helpscout.net/conversation/298906345/50038/?folderId=205529

**Comment by pippinsplugins** [comment]
Let's get this resolved shortly after 2.0.

**Comment by sumobi** [comment]
I can confirm that this also breaks OptimizeMember's PayPal integration when our "PayPal" integration is enabled: https://secure.helpscout.net/conversation/300263505/50223/?folderId=205531

Customer saw "PayPal" in our integrations list and thought they needed to enable it.

@AffiliateWP/core Thoughts on changing `PayPal` to `PayPal buttons` in our integrations list? Our doc is already called `PayPal Buttons`: http://docs.affiliatewp.com/article/1428-paypal-buttons

In the mean time I'm going to add a note to the top of the PayPal documentation.

> In technical description, after you click the button POST variables are being send to PayPal for processing the payment and one of the most important is variable named "custom" which should contain domain name. In OptimizePress we are filling this information correctly, but "AffiliateWP" plugin also gets into the code and at the end adds another "custom" variable where it says "undefined" and this is a reason for the error. Basically two variables "custom" are send and only last take place which is from "AffiliateWP" and basically our is discarded. The same thing is happening with the "notify_url" variable but so far we don't know if it affects functionality but I would say it does."

**Comment by pippinsplugins** [comment]
I'm good with changing it to PayPal Buttons.

**Comment by pippinsplugins** [comment]
Integration was renamed to PayPal buttons. Closing as fixed.
