### ISSUE TITLE
Tweak debug log description

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1904]
Since the debug log is used for more than just referral tracking (i.e. upgrades), we should tweak the description so it's more generic.

![screen shot 2017-01-11 at 12 31 03 pm](https://cloud.githubusercontent.com/assets/52581/21829244/e2147b56-d7f9-11e6-9208-ad0dc28ae7cf.png)

**Comment by DrewAPicture** [comment]
Added a PR: #2008 

Changes the text from:

> Use this tool to help debug referral tracking.

to

> Use this tool to help debug various operations in AffiliateWP.
