### ISSUE TITLE
Improve Edit Referral screen

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1906]
There are a few things that could potentially make the Edit Referral screen more useful to site owners:
- Add Referral ID #1874 (perhaps move Affiliate ID further down the page)
- Would it be possible to pull the corresponding visit data (Visit ID, visit time, landing page) through to the Edit Referral screen so everything relating to that referral is shown from the Edit Referral screen (read-only)?
- Add Affiliate Name (currently only has Affiliate ID, but Affiliate Name is shown on Visits screen)
- Perhaps make the Affiliate ID a link that links to all referrals generated by that affiliate

**Comment by DrewAPicture** [comment]
@wordmaid:

> Add Referral ID #1874 (perhaps move Affiliate ID further down the page)

This would bring consistency with the other objects where we show their IDs. 👍 

> Would it be possible to pull the corresponding visit data (Visit ID, visit time, landing page) through to the Edit Referral screen so everything relating to that referral is shown from the Edit Referral screen (read-only)?

Seems reasonable, would just need to figure out how you want that data expressed, e.g. all in one line somehow, or separate pieces of visit information on each line, etc.

> Add Affiliate Name (currently only has Affiliate ID, but Affiliate Name is shown on Visits screen)

Rather than add an _additional_ piece of affiliate info here I'd be more tempted to the combination "Name (#ID)" type presentation if that makes sense.

> Perhaps make the Affiliate ID a link that links to all referrals generated by that affiliate

Yep, absolutely.

**Comment by DrewAPicture** [comment]
Added a PR: #2001 

The PR includes:

* [x] Add affiliate name and link it
* [x] Add referral ID
* [x] Add visit information

Similarly, I've also adjusted the output for payout information to be more consistent with how the affiliate and visit information are now formatted. The payout field has three states:

**1. When the referral is pending or unpaid, you can now pay it out from this screen:**
![Pay Out link](https://cl.ly/39113e1D1z3n/Screen%20Shot%202017-02-09%20at%2013.05.22-fullpage.png)

**2. When the referral is paid and has a corresponding payout, link it:**
![Linked payout](https://cl.ly/2D1d021T2z3x/Screen%20Shot%202017-02-09%20at%2013.06.53-fullpage.png)

**3. "None" when the referral is rejected:**
![None](https://cl.ly/1B3J1Z1S160T/Screen%20Shot%202017-02-09%20at%2013.08.45-fullpage.png)

@AffiliateWP/core Please test :)

**Comment by pippinsplugins** [comment]
Excellent improvement.

Pr looks good to me as well.
