### ISSUE TITLE
Filter referrals on a per-affiliate basis for specific date range

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1907]
PR: #1924

Currently it’s not possible to filter referrals on a per-affiliate basis for a specific date range. Thoughts on allowing this somehow, such as adding an auto-complete search box to search for an affiliate's name next to the date range filter?

**Comment by DrewAPicture** [comment]
Added a PR: #1907

**Comment by pippinsplugins** [comment]
PR works great. Ready to merge once tests pass.
