### ISSUE TITLE
Reorder Visits screen columns

### ISSUE THREAD

**Issue by lisag** [AffiliateWP/AffiliateWP#1908]
I'd like to propose a reorganization of the Visits screen columns. This would introduce a new column which would show the Visit ID. In order, from left to right:

1. Visit ID _(new)_
2. Landing Page
3. Referring URL
4. IP
5. Converted
6. Referral ID (links to Edit Referral screen #1874)
7. Affiliate
8. Date

**Comment by pippinsplugins** [comment]
I like this.

I've actually needed the visit ID numerous times so would love to see that included.

**Comment by pippinsplugins** [comment]
Ready for testing.
