### ISSUE TITLE
Add support for excluding shipping costs from referrals

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#191]
We should add support for excluding shipping costs from referral calculations. This would be done on a per-integration basis and would primarily be for the main e-commerce plugins, such as WooCommerce, WP e-Commerce, Jigoshop, Shopp, etc.

Requested here: https://secure.helpscout.net/conversation/28175345/313/

**Comment by pippinsplugins** [comment]
- [x]  WooCommerce
- [ ] WPeC
- [ ] Shopp
- [ ] Jigoshop
- [ ] iThemes Exchange
- [ ] EDD

**Comment by pippinsplugins** [comment]
@sumobi Ready for testing with all plugins listed above!

**Comment by sumobi** [comment]
@pippinsplugins Excellent, will test today :+1:

**Comment by sumobi** [comment]
@pippinsplugins Tested with EDD and a $15 download. Shipping was $10.00. Commission set to 20%. Before enabling the option in settings the commission was $5.00 (correct) but after enabling the option the commission was only $1.00. It should have been $3.00.

**Comment by sumobi** [comment]
With WooCommerce the product was $50.00 and the shipping was a flat rate of $10.00. The commission should have been $10.00 (205 commission) but came through as $8.00.

**Comment by pippinsplugins** [comment]
@sumobi Are EDD and WooCommerce the only ones that you've tested or just the only two with issues?

**Comment by pippinsplugins** [comment]
EDD should be fixed now.

**Comment by pippinsplugins** [comment]
Woo is fixed now too.

**Comment by pippinsplugins** [comment]
Merged into release/1.5

**Comment by sumobi** [comment]
@pippinsplugins I only tested with EDD and WC as I noticed an emerging pattern. Will give some of the others a test now.

**Comment by sumobi** [comment]
@pippinsplugins Tested with the above and all is working, good enough for me!
