### ISSUE TITLE
Remove "No reason provided" copy from rejection email if no rejection reason provided

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1912]
When rejecting an affiliate, if no rejection reason is provided the email says "No reason provided". I think we should remove this copy, as the rejection email copy is sufficient if an admin does not wish to provide a rejection reason. 

<img width="743" alt="screen shot 2017-01-12 at 1 06 29 pm" src="https://cloud.githubusercontent.com/assets/11830108/21871634/4e05f8f2-d8c8-11e6-9ac3-2118e2bb4d04.png">

**Comment by DrewAPicture** [comment]
Added a PR with tests: #2055

**Comment by pippinsplugins** [comment]
Merged!
