### ISSUE TITLE
Improve message or show error when entering new affiliate that is not a WP user

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#1913]
Had a few tickets on this - new users go to add an affiliate, they enter something in the User field and payment email and click the Add Affiliate button.  It appears something is happening but the new affiliate is not added.   Not sure if an error message is the answer or an enhanced message round the User input?  Currently it has "Begin typing the name of the affiliate to perform a search for their associated user account."   But its not connecting with them in some cases.

**Comment by sumobi** [comment]
Yeah, I'd love to see this improved. You can enter anything into the "user" field, fill out the rest of the information and click add affiliate only to discover it does not work. It does show an error message on the main affiliates screen but that's too late.

Ideally we add a check to the user field and throw an error if the account is not valid. Perhaps we also block the form from being submitted by disabling the `Add Affiliate` button until a valid user has been entered.

**Comment by pippinsplugins** [comment]
I've played with this a bit and feel I have a pretty good solution. It's not polished yet but shows the direction.

When the `Add Affiliate` screen is loaded, all input fields are disabled, save for the user search field. Once a search is entered, an ajax request is fired that validates the username/email entered actually belongs to a user account. If it does not belong to a user, an error is shown and the remaining fields stay disabled. If a valid user is found, the fields are enabled and the account can be created.

<img width="1077" alt="screen shot 2017-08-22 at 3 50 55 pm" src="https://user-images.githubusercontent.com/1034109/29586858-b3e37f04-8751-11e7-8db8-148571298a3c.png">

<img width="1132" alt="screen shot 2017-08-22 at 3 52 49 pm" src="https://user-images.githubusercontent.com/1034109/29586921-f832642c-8751-11e7-8af4-451bfbcbf842.png">

Thoughts?

**Comment by pippinsplugins** [comment]
Note to self: when a user account doesn't exist, let's show the option to create the account on the fly.

**Comment by pippinsplugins** [comment]
This is ready for testing!

<img width="1306" alt="screen shot 2017-08-25 at 2 26 12 pm" src="https://user-images.githubusercontent.com/1034109/29729346-66bd1f9e-89a1-11e7-8dd3-7d3d00b23bd7.png">
<img width="1302" alt="screen shot 2017-08-25 at 2 26 20 pm" src="https://user-images.githubusercontent.com/1034109/29729347-66d09880-89a1-11e7-9489-146f2f85b6a9.png">

**Comment by gspice** [comment]
* I entered a bogus username
* Message displays as expected. 
* Clicking the **Click Here** link refreshes the same New Affiliate page, would expect it to take me to the WP Add User page?

![new-affiliate-1913](https://user-images.githubusercontent.com/3018245/29732962-e1b6472c-899f-11e7-82ca-24d46836e281.png)

**Comment by DrewAPicture** [comment]
As of 713008aea0972a982c2b47b99d44a18581e7ce6e, the info notice shown for an existing affiliate now includes a "View Affiliate" link that points to the edit screen for that affiliate.

**Comment by pippinsplugins** [comment]
Looks good! This is a definite improvement over the existing UI so I'm going to merge and get this update live.
