### ISSUE TITLE
Small tweaks to login/register forms

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1917]
The login and register forms can be tweaked ever so slightly to be more consistent with core, and just better copy in general. Below is a list enhancements that I have run past @wordmaid:

___

Exhibit A - The WordPress login screen

![screen shot 2017-01-13 at 2 11 18 pm](https://cloud.githubusercontent.com/assets/52581/21914754/2f1d74e2-d99a-11e6-9eb1-e3f36c53bc4d.png)

___

Exhibit B - The AffiliateWP login and register forms

![screen shot 2017-01-13 at 2 11 12 pm](https://cloud.githubusercontent.com/assets/52581/21914755/2f1e29c8-d99a-11e6-8707-0b30a403cc67.png)

___

## Proposed enhancements

1. Change `Login` to `Log In`
2. Change `Register a New Affiliate Account` to `Register a new affiliate account`
3. Change `Log into Your Account` to `Log into your account`
4. Change `Lost Password?` to `Lost your password?`

**Comment by DrewAPicture** [comment]
Seems solid.

**Comment by pippinsplugins** [comment]
Merged.
