### ISSUE TITLE
Options to disable each email 

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#1923]
We should include checkboxes so a site admin can choose which email/s can be disabled. Currently, only _all_ emails can be disabled.

Related: https://github.com/AffiliateWP/AffiliateWP/issues/659

**Comment by ramiabraham** [comment]
@AffiliateWP/core 

- [PR ready for review](https://github.com/AffiliateWP/AffiliateWP/pull/2373)
- Options to disable were added for the emails that have template content settings (_application accepted_, and _new referral_ were added, as well as the two that don't, _pending_ and _rejected_ registrations.

**Comment by pippinsplugins** [comment]
@ramiabraham need one small change

**Comment by ramiabraham** [comment]
@pippinsplugins Corrected!

**Comment by pippinsplugins** [comment]
@ramiabraham Another small change request on the PR.

**Comment by ramiabraham** [comment]
@pippinsplugins Updated in PR.

**Comment by pippinsplugins** [comment]
Merged.

**Comment by gspice** [comment]
Question: While testing I noticed the new /Emails settings no longer include the email subject and content sections for `Pending` and `Accepted` affiliate registrations.  Shouldn't we add these back before release?

**Comment by pippinsplugins** [comment]
@gspice that was unintended, good catch!

**Comment by gspice** [comment]
@pippinsplugins  Well, I'm embarrassed....there is no issue here. I didn't realize that the `Pending` and `Rejected` sections of the **Emails** tab are only visible if you have the **Require Approval** option checked under the **Misc** tab.   Pretty clever setup actually!   This works as designed on the beta.

**Comment by pippinsplugins** [comment]
Oh . . . hehe, I missed it too :)
