### ISSUE TITLE
2.1: Make admin notices testable and then test allthethings, yo

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1928]
Let's make admin notices testable. After some experimentation with various approaches, I think the best bet is to actually change how notices are output by adding an optional `$echo` parameter to `show_notices()`.

I played around with simply using output buffering but the monstrous performance hit on our test suite would hard to swallow. The attached PR makes a couple of very specific changes to class-notices.php:

* Adds an optional `$echo` parameter to `show_notices()`, making it possible to retrieve or output the generated markup. Default will of course be to echo by default.
* Splits up some of the various notice types into separate methods, all hooked to `admin_notices`. This separation helps keep things simple
* Added a helper method for preparing messages for output as notices

Coming up:
* Tests for the new `prepare_message_for_output()` helper
* Tests for each of the new `integration_notices()` and `license_notices()` callbacks as well as full coverage for the existing logic in `show_notices()`.

**Comment by DrewAPicture** [comment]
Added a PR: #1929

**Comment by pippinsplugins** [comment]
This looks good. I approve!

**Comment by pippinsplugins** [comment]
@DrewAPicture do you remember why the PR was closed?

**Comment by DrewAPicture** [comment]
I don't remember the history, but looking at the commits my guess is that I determined it was nearly impossible to make notices testable (with that approach). I'd have to revisit it to find out.

**Comment by pippinsplugins** [comment]
Re-visit and then close as wontfix if they're still not testable.

**Comment by DrewAPicture** [comment]
OK, after some poking around I think I've finally got the original tests passing (capabilities are hard). PR is back open.

**Comment by DrewAPicture** [comment]
@pippinsplugins The 36 tests in the PR are now ready for review :)

**Comment by pippinsplugins** [comment]
Sweet! Will test tomorrow!

**Comment by pippinsplugins** [comment]
@DrewAPicture just tested and everything here seems to work well!

**Comment by DrewAPicture** [comment]
Merged #1929.
