### ISSUE TITLE
JS error for graphs

### ISSUE THREAD

**Issue by danieliser** [AffiliateWP/AffiliateWP#1931]
Uncaught SyntaxError: missing ) after argument list

The error is related to this line, I believe due to use of " inside "" breaking the strings.

`$("<div id="affwp-flot-tooltip">" + contents + "</div>").css( {`

Which I believe should be:

`$('<div id="affwp-flot-tooltip">' + contents + "</div>").css( {`

**Comment by pippinsplugins** [comment]
@danieliser where do you see that error, on all pages with graphs?

**Comment by pippinsplugins** [comment]
I have not seen any other reports of this. Closing as invalid but feel free to re-open if it re-appears.
