### ISSUE TITLE
Unpaid Referrals Today stat is wrong

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1940]
In the affiliates overview page, the `Unpaid Referrals Today` stat is wrong.
![screen shot 2017-01-19 at 1 45 03 pm](https://cloud.githubusercontent.com/assets/1034109/22122447/a0339e24-de4d-11e6-8e08-d5c0f3f43e21.png)

Notice that it shows the same value as the unpaid for all time.

**Comment by DrewAPicture** [comment]
Added a PR, including a new test: #1946

**Comment by pippinsplugins** [comment]
Works great!
