### ISSUE TITLE
Missing argument for affwp_decrease_affiliate_unpaid_earnings()

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1943]
This appears to have been introduced somewhere in 2.0 release cycle.

PHP Warning: Missing argument 2 for affwp_decrease_affiliate_unpaid_earnings(), called in /Users/pippin/Sites/edd/wp-content/plugins/affiliate-wp/includes/class-referrals-db.php on line 228 and defined in /Users/pippin/Sites/edd/wp-content/plugins/affiliate-wp/includes/affiliate-functions.php on line 793

**Comment by DrewAPicture** [comment]
Added a PR: #1944
