### ISSUE TITLE
WPForms: Extra referrals created by refreshing confirmation page

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1949]
When you submit a basic form with WPForms (no CC field) and see the confirmation message it creates a referral as expected. However you can then refresh the page again a new referral is created. 

My first thought was to check against the referral in the DB with the matching entry ID and prevent a new referral from being created but WPForms seems to be creating a new entry with each page refresh. 

All other form plugins I've seen prevent a new entry from being created if the page is refreshed. It seems like something that should be fixed with WPForms but open to any ideas in the meantime on how to prevent extra referrals from being created, without a brand new form submission (I don't think we should block referrals like the conversion script shortcode).

**Comment by jaredatch** [comment]
If you refresh the confirmation page that's basically triggering the form to submit - assuming browser warning is ignored and the user chooses to continue.

To my knowledge this is standard with most form processing and this can be duplicated with most other form solutions, including GF (https://cl.ly/1i0A461E421I).

I'm up for suggestion on the best way to prevent that, but it hasn't really been an issue in support, so it isn't something I have given much thought about to be honest :)

**Comment by chriscct7** [comment]
> All other form plugins I've seen prevent a new entry from being created if the page is refreshed

I don't think that's true of any plugin that allows for logged out form submissions unless they're only allowing 1 submission per email or something, but I'd be really interested to know if you can remember one that can to see how they're doing it. How would you know without being able to use nonces (non-starter for cached, logged out users)? The only thing is you'd have to have an arbitrary limit that's user identifiable, like once per email, or reCAPTCHA

**Comment by sumobi** [comment]
@jaredatch @chriscct7 

Ahh yeah I am totally wrong. GF _does_ create an additional entry when refreshed (and thus referrals are generated on each page load). I'm going to play with some others but I suspect you're right in that they all do the same thing.

A non-issue then :)

**Comment by sumobi** [comment]
I'm going to close this issue but if anyone has any magical ideas on how to prevent repeat referrals for repeat form submissions I'd love to hear them.

**Comment by pippinsplugins** [comment]
Note for @jaredatch: this is really easy to fix/avoid by simply adding a `wp_redirect()` after the form is submitted.

The resubmit only happens when you reload a page after a form is submitted _without_ redirecting somewhere else. If you redirect to another page (even the exact same page), the re-submission will not happen.

**Comment by chriscct7** [comment]
Refreshing the page would also re-fire any JS event that's tied to the page, which isn't ideal, particularly if you're using something like Google Analytics enhanced ecommerce tracking, that will spawn a whole new checkout flow session, skewing cart funnel data. Ideally WPforms should implement a server/client challenge nonce which is cachable, but that might be difficult to imlpement

**Comment by chriscct7** [comment]
As for the repeat referral, why wouldn't the referral be rewarded on the repeat? If the payment is submitted twice, just because it's a duplicate doesn't mean that the referral shouldn't be awarded. It would seem you would want to record the referral on both submissions and if they revoke the second submission, you'd revoke the referral for the second one via the same refund hooks you already use

**Comment by sumobi** [comment]
Repeat referrals for repeat payments are fine (and appreciated by the site owner :)), that wasn't the initial issue. The issue was for forms without a CC field, where refreshing the page after submission generated a new $0.00 referral.
