### ISSUE TITLE
WooCommerce coupon metaboxes cannot be expanded/collapsed when AffiliateWP is active

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1952]
When AffiliateWP (2.0 or earlier) and WooCommerce are active, you cannot expand or collapse the `Coupon Data` or `Publish` metaboxes on the WooCommerce's coupon screen, using the arrows. No JS errors outputted. Deactivating AffiliateWP allows these metaboxes to work as usual.

Switching between the WooCommerce coupon sections work as normal.

![screen shot 2017-01-25 at 11 24 22 am](https://cloud.githubusercontent.com/assets/52581/22269570/d99ff1a6-e2f0-11e6-967b-5c625dd12426.png)

**Comment by grayayer** [comment]
Essentially, the javascript that removes or adds the class of "hidden" to those divs isn't firing for some reason.

**Comment by DrewAPicture** [comment]
Introduced in 1.9 with the meta boxes feature. Added a PR: #1956, please test.

**Comment by sumobi** [comment]
@DrewAPicture 👍  Works here
