### ISSUE TITLE
Add export option for Debug Assistant

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1953]
The information in the Debug Assistant shows useful information for the referral tracking process, as well as version update info. It may be useful to be able to export this if any potential issues arise with referrals or updates.

**Comment by DrewAPicture** [comment]
Added a PR: #1962

Looks like this:

![Download button](https://cl.ly/1l1y1B0o1Z44/Screen%20Shot%202017-01-27%20at%204.50.36%20PM.png)

**Comment by DrewAPicture** [comment]
Merged #1962.
