### ISSUE TITLE
Edit referral amount on existing referral disassociates it from the affiliate.

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#1955]
Beta bug report form this ticket - I confirmed it on my test site using 2.0 released version.

https://secure.helpscout.net/conversation/309619819/51624/?folderId=205529

Steps to recreate:

Edit an existing referral amount, click to save changes and it appears to get separated from the affiliate. The status for my referral was Unpaid but not sure that is pertinent.   

Screen shot from the user:

![affiliate-connection-gone](https://cloud.githubusercontent.com/assets/3018245/22300014/f0c23698-e2da-11e6-8594-21f005636b46.png)

**Comment by DrewAPicture** [comment]
Whoops! Good catch. Added a PR with tests: #1957

**Comment by sumobi** [comment]
Had a report of this issue this morning

**Comment by mindctrl** [comment]
Just saw this issue on version 2.0.1.1 on the RCP site. Referral (which may be fixed by the time you see this): https://restrictcontentpro.com/wp-admin/admin.php?page=affiliate-wp-referrals&referral_id=295&action=edit_referral

**Comment by pippinsplugins** [comment]
Re-opening.

**Comment by mindctrl** [comment]
Just edited another one that did **not** disassociate the ID.

**Comment by DrewAPicture** [comment]
@mindctrl Have you seen this issue pop up again? I don't have access to the RCP back-end.

**Comment by mindctrl** [comment]
@DrewAPicture only saw the one, which I fixed manually with Debug Bar Console. Not sure why one did it and another didn't.
