### ISSUE TITLE
Conflict with plugin Encyclopedia Pro mangles the Creatives HTML block

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#1958]
With this plugin activated, it shows this in the Creative copy/paste HTML block area:

 {STRINGCACHE:MD5:796257f8f6e84e4c952c65d9e1dd51a4}

Link on WP plugin repo for light version:
https://wordpress.org/plugins/encyclopedia-lexicon-glossary-wiki-dictionary/

From this HS ticket:
https://secure.helpscout.net/conversation/309257602/51562/?folderId=1170842

Also @sumobi encountered on this ticket:
https://secure.helpscout.net/search/?query=mailbox:AffiliateWP%20Encyclopedia

Andrew wrote plugin to solve , attaching here.  I used this plugin on the customer's ticket to solve and sent her some CSS.   

[affiliatewp-creatives.zip](https://github.com/AffiliateWP/AffiliateWP/files/732834/affiliatewp-creatives.zip)

<img width="1358" alt="creative-html-block" src="https://cloud.githubusercontent.com/assets/3018245/22340204/72fc4d3a-e3a1-11e6-9264-d3857b4a40c8.png">

**Comment by DrewAPicture** [comment]
I played around with this a little bit and we can do this in a much more simplified way. Rebuilding the creatives HTML in this way is a reasonable stop-gap but unsustainable as a fix because we'd constantly have to make sure it stays in sync with the current core output.

So after some experimentation, I currently I have this working with two (more) different approaches:

Removing the filters on the content for the creatives tab:
```php
function affwp_creatives_affiliate_area_shim( $affiliate_id, $active_tab ) {
	if ( 'creatives' === $active_tab ) {
		// Variable priorities based on settings.
		remove_filter( 'the_content', array( 'WordPress\Plugin\Encyclopedia\Content_Filter', 'addCrossLinks' ), 10.5 );
		remove_filter( 'the_content', array( 'WordPress\Plugin\Encyclopedia\Content_Filter', 'addCrossLinks' ), 15   );
	}
}
add_action( 'affwp_affiliate_dashboard_top', 'affwp_creatives_affiliate_area_shim', 10, 2 );
```
Or by filtering per-post:
```php
function affwp_creatives_affiliate_area_shim( $affiliate_id, $active_tab ) {
	if ( 'creatives' === $active_tab ) {
		add_filter( 'encyclopedia_link_terms_in_post', '__return_false' );
	}
}
add_action( 'affwp_affiliate_dashboard_top', 'affwp_creatives_affiliate_area_shim', 10, 2 );
```

**Comment by pippinsplugins** [comment]
I like version two.

**Comment by DrewAPicture** [comment]
Added a PR: #1961

**Comment by DrewAPicture** [comment]
@AffiliateWP/core this needs testing :)

**Comment by pippinsplugins** [comment]
PR is good here! Merged.
