### ISSUE TITLE
Referral Area - Settings: request for affiliate area setting to enable/disable New Referral Notifications per affiliate

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#1960]
Requested by a few users so each affiliate doesn't have to go to Settings and check the box:  "Enable New Referral Notifications".

**Comment by wordmaid** [comment]
This is more and more frequently requested in support. Have just had another one today. It would be awesome to see this implemented soon if possible.

When this option is globally enabled from the admin, the affiliate should then be able to go to their _Settings_ tab in the Affiliate Area and simply uncheck the option, and click `Save Profile Settings` to no longer receive **New Referral Notification** emails.

**Comment by ckaklamanos** [comment]
This is a feature that I would like to see in AffialiateWP as well. It would be great to be able to make this a global setting. This is because when this is needed for all affiliates, admins should ask them explicitly to make this enabled in their Affiliate Area.

**Comment by ramiabraham** [comment]
Related #1923

**Comment by michaelbeil** [comment]
I believe so.

**Comment by gspice** [comment]
I don't believe this is related to #1923 , rather, this is referring to the frontend  _Affiliate Area > Settings_ tab where affiliates have to opt-in to receive email notifications that a referral has been created for them.   Also, there are some privacy issues with this, meaning the admin would be opt-ing in for the affiliate on their behalf.

**Comment by pippinsplugins** [comment]
@ramiabraham No it is not. What @gspice just said is correct.

**Comment by ramiabraham** [comment]
@AffiliateWP/core PR ready for review https://github.com/AffiliateWP/AffiliateWP/pull/2379

**Comment by michaelbeil** [comment]
Ticket: https://secure.helpscout.net/conversation/467597177/0/?folderId=205529.

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/483973806/72220?folderId=634609

**Comment by pippinsplugins** [comment]
Attached PR is no longer valid. Will need to be re-done differently.

**Comment by amdrew** [comment]
Working on this issue over in https://github.com/AffiliateWP/AffiliateWP/issues/948. 

All email notifications are now listed in a checkbox group, including the global option for allowing new referral notifications for affiliates. When enabled, the affiliate will see the option to enable new referral notifications in their affiliate area. They can also disable the email if they choose to, unless the admin deselects the global setting. In this instance, the checkbox option is removed from the affiliate area altogether.

Finally, all new affiliate registrations going forward will have new referral notifications enabled by default in the affiliate area.

**Comment by pippinsplugins** [comment]
#948 was merged so this can now be closed!
