### ISSUE TITLE
Edit affiliate URL with ID of 0 shows on edit affiliate screen

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1963]
1. Edit an affiliate
2. Change their ID to `0` in the URL
3. You'll see your own edit affiliate screen (if you're also an affiliate)

![screen shot 2017-01-28 at 4 21 43 pm](https://cloud.githubusercontent.com/assets/52581/22393891/f2e955f8-e575-11e6-9fd4-b7baca1782fc.png)

**Comment by DrewAPicture** [comment]
This is likely happening because affwp_get_affiliate_id() is used and it
defaults to the current affiliate. Would you expect the page to instead
show am error for invalid affiliate?

**Comment by sumobi** [comment]
Yeah I would expect it to show a "not found" page like WordPress core. Or maybe we can redirect them back to the main affiliates screen?

Related, you can also change the ID to something that doesn't exist (say a higher ID) and you'll get a variation of the edit screen with blank fields:

![screen shot 2017-01-28 at 4 43 01 pm](https://cloud.githubusercontent.com/assets/52581/22393996/de83e79c-e578-11e6-8677-ebf50a26422f.png)

**Comment by DrewAPicture** [comment]
Punting as this was not behavior introduced in 2.0, rather has been a longstanding bug.

**Comment by DrewAPicture** [comment]
FWIW, following #2048, edit_affiliate no longer shows your own edit affiliate screen if you're also an affiliate.

**Comment by DrewAPicture** [comment]
Added a PR: #2127

If there is an `affiliate_id` value passed, it simply checks to see if it's valid, and if not, the templates triggered by the `action` values concerning existing affiliates will not be loaded.

This approach is not quite like the core flow that simply dies if the user ID is invalid. It just keeps the user on the current screen (though it's worth noting that the query vars remain intact, no way to get around that really).

**Comment by pippinsplugins** [comment]
PR looks good.
