### ISSUE TITLE
JS error being outputted from new JS debugger

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1965]
We're receiving multiple reports of the new JS debugging causing a JS error on the front-end. <strike>The quick fix is to have the customer disable debug mode from the Misc tab.</strike> I've only been able to see the error in Safari (which is what the customers also report).

![image 2017-01-29 at 9 04 11 pm](https://cloud.githubusercontent.com/assets/52581/22408245/fc1c0ea2-e6da-11e6-9fbc-ef35623bfc1a.png)

Tickets so far:

https://secure.helpscout.net/conversation/311721488/51926/?folderId=205531
https://secure.helpscout.net/conversation/311544100/51910/?folderId=205527
https://secure.helpscout.net/conversation/311159906/51855?folderId=205527
https://secure.helpscout.net/conversation/311336660/51879/?folderId=205527
https://secure.helpscout.net/conversation/309665947/51633/?folderId=205531
https://secure.helpscout.net/conversation/311612018/51915/?folderId=205524

**Comment by sumobi** [comment]
Have another customer with this issue (added above) however disabling debug mode doesn't resolve the JS issue. Same error as above.

**Comment by ramiabraham** [comment]
@AffiliateWP/core Created a PR: https://github.com/AffiliateWP/AffiliateWP/pull/1966.

**Comment by sumobi** [comment]
Works for me
