### ISSUE TITLE
Add "context" column in visits table

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1967]
It would be helpful to have a new column in the visits DB table called `context`.

Original conversation:
https://github.com/AffiliateWP/affiliatewp-direct-link-tracking/issues/38#issuecomment-275898471

**Comment by DrewAPicture** [comment]
Added a PR: #1969, which includes support for:

* [x] A new `context` field in the `AffWP\Visit` object
* [x] New `context` argument in `add()` and `update()`
* [x] New `context` and `context_compare` arguments in `get_visits()` + tests
* [x] A 2.0.2 upgrade routine to add the column

**Comment by sumobi** [comment]
yeehaw, will test today 👍

**Comment by DrewAPicture** [comment]
Still needed:

* [ ] Add `context` support to queries performed for the Visits list table
* [ ] WP-CLI support
* [ ] Tests for `add()` in regard to the `context` argument
* [ ] Tests for `update()` in regard to the `context` argument

**Comment by sumobi** [comment]
Works great  👍

**Comment by DrewAPicture** [comment]
I'll follow up here before the end of the week on the [remaining items](https://github.com/AffiliateWP/AffiliateWP/issues/1967#issuecomment-276211210).

**Comment by DrewAPicture** [comment]
As of c757e4e7febed8e5c62594f99a9e22e25e32bf34, list table and wp-cli support has been added.

**Comment by DrewAPicture** [comment]
And 4d3941f4497ebfbdc7e8ca9fa7bef069ee1b3e53 adds tests for `add()` and `update()` for `context`.

@AffiliateWP/core This is ready for final testing.

**Comment by pippinsplugins** [comment]
@DrewAPicture noticed a couple of small items. See the PR review please.

**Comment by DrewAPicture** [comment]
@pippinsplugins I've addressed your two points of feedback.

**Comment by pippinsplugins** [comment]
Should we automatically set `context` to the value of `$_REQUEST['context']` if it is present?
