### ISSUE TITLE
Batch processing registry doesn't work for IIS servers

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1973]
Problem: Clicking the button to upgrade the database sends back the following error:
```
recount-affiliate-stats-upgrade is an invalid batch process ID.
```

The reason the batch ID is determined to be invalid, is that the `register_process()` call is ultimately failing due to a previously unexpected return value from `validate_file()`.

In `validate_file()`, we explicitly check for a return value of `0`, however, Windows file paths will always have `:` in them, which causes `validate_file()` to return `2`.

See attached PR.

**Comment by DrewAPicture** [comment]
PR: #1974

**Comment by DrewAPicture** [comment]
Can definitely confirm this fixed batch processing on at least one customer site running IIS. Have dispatched patched copies to the other 2 customers.

**Comment by pippinsplugins** [comment]
PR looks good to me.

Let's get one more confirmation then merge and deploy.

**Comment by DrewAPicture** [comment]
We have confirmation from a second customer: https://secure.helpscout.net/conversation/312229448/51991/
