### ISSUE TITLE
Manipulating final payout amount / adding tax

### ISSUE THREAD

**Issue by flowdee** [AffiliateWP/AffiliateWP#1979]
I want to manipulate the final payout amount which will be stored in the database as well as shown in export files etc. Is there a way right now to do this? 

The reason: Adding tax on top of the basic payout amount.

<img width="694" alt="bildschirmfoto 2017-02-02 um 12 18 29" src="https://cloud.githubusercontent.com/assets/2278756/22537988/c8c1d56e-e941-11e6-8251-3480c7af6109.png">

Can't find a well placed filter for this, thinking about if this area in _class-payouts-db.php_ might be a good place for adding one?

Alternatively the payout amount could stay as it is and saving the amount of tax extra (which must be added later in the final export file or fowarded to the payout processor like paypal).

In general isn't this something worth implementing as well?

**Comment by DrewAPicture** [comment]
Hmm.

You could modify the payout amount on the [`affwp_insert_payout`](fhttps://github.com/AffiliateWP/AffiliateWP/blob/master/includes/admin/tools/export/class-batch-generate-payouts.php#L240) action after it's been added, but that won't help you for the actual generation step which adds the payout and returns the hard-coded data all in one step in [`class-batch-generate-payouts.php`](https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/admin/tools/export/class-batch-generate-payouts.php#L240).

**Comment by DrewAPicture** [comment]
Since the batch generator for payouts only processes one affiliate (payout) at a time, I could see putting a filter on either the `$data` value before return in `Generate_Payouts::get_data()`.

**Comment by DrewAPicture** [comment]
Actually, another possibility springs to mind that could be a very powerful solution depending on how robust you'd like your payout logs to be. As implied in my previous comment, the payout generation form actually uses a batch processor now, which means that you could, if so inclined, actually extend `Generate_Payouts` with your own implementation and then register your own `generate-payouts` batch process over the top of the core one. They are deliberately pluggable in that way ;)

Obviously this approach would be overkill for something as straightforward as wanting to modify a value in an existing column, just thought it would be good to give you all the options.

**Comment by flowdee** [comment]
Thanks for your thoughts @DrewAPicture 👍 

Well basically of course I want to touch as little of the core files as possible. Personally I think it would be fine when holding one the one hand the payout amount, on the other hand my calculated tax amount and simply adding the amounts for the generating of the payout file (or processing it via any gateway). So I could show the tax amount separately on the payouts overview/detail screens as well and it would be possible to disable the feature whenever you want.

### But speaking about generally

Wouldn't this be a great feature for the core as well? A lot of my customers (of my affwp addons) asked for this, which basically needs only few things:

1. Selecting / storing a percentage of tax for every single affiliate
2. When generating payout files / processing payouts the tax must be added to the final sum

In order to avoid abuse, only admins should be able to assign/enable tax calculation for affiliates. In other words: as an affiliate program owner you can invite your affiliates to get in contact with you for tax calculation, otherwise the raw amount will be taken for every payout.

The implementation of this feature is no big deal and if not interesting for the core, I'm going to create an addon for this (or adding it to one of my existing addons). All we need would be a hook before the final amounts will be written down in exports / forwarded to payout gateways.

**Comment by DrewAPicture** [comment]
PR: #1980 adds two filters:

1. `affwp_batch_generate_payouts_csv_cols` makes `csv_cols()` filterable (this will be needed to add additional columns
2. `affwp_batch_generate_payouts_get_data` makes `get_data()` filterable.

**Comment by pippinsplugins** [comment]
PR looks good to me.

**Comment by flowdee** [comment]
Thanks for the filters so far Drew.

Anyway I would be very interested in hearing your guys opinions about my feedback "But speaking about generally".

**Comment by DrewAPicture** [comment]
@flowdee Let's open a new issue for the feature request. The new hooks will ship with 2.0.2.

**Comment by flowdee** [comment]
Okay, see https://github.com/AffiliateWP/AffiliateWP/issues/2023
