### ISSUE TITLE
View Referral screen

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1987]
We should add a page for viewing single referrals. At its base this is useful to have simply because of the sheer amount of information associated with any given referral that can't effectively be expressed in a list table. This information includes product information (if available), correlating visit, affiliate, and payout information, and more. It would also be good to create a secondary jumping off point for referral reports.

**Comment by DrewAPicture** [comment]
Started a PR: #1988

**Comment by pippinsplugins** [comment]
In early RCP versions we had `view` and `edit` displays for members. Eventually we decided it was silly to separate edit and view onto different screens so we combined them into a single `edit` screen instead.

Is there a good reason for making `view` and `edit` separate here?

**Comment by DrewAPicture** [comment]
Bumping this to future release for future consideration.

**Comment by pippinsplugins** [comment]
After a discussion with @amdrew, I'm closing this as a wontfix since it's really not necessary to separate view and edit screens.
