### ISSUE TITLE
Help Commission to VALUE OF SALE

### ISSUE THREAD

**Issue by pancado** [AffiliateWP/AffiliateWP#1989]
I wonder if the ranking system can be measured by the total amount sold and not by the commission amount. 

Example:
VALUE OF SALE: 1500$ 
COMMISSION VALUE: 450$ 
Total sale ...................... % Commission
R$ 99,00 —-—-—-—-—-—- 10%
R$ 100,00 a R$ 199,00 ——15%
R$ 200,00 a R$ 299,00 ——20%
R$ 300,00 a R$ 399,00 ——25%
R$ 400,00 a R$ 499,00 ——30%
R$ 500,00 a R$ 599,00 ——35%
R$ 600,00 or more —-——- 40%

or

And if it is to upgrade all the commissions according to the level advance? 

Example: Earned 10% on the sale of the 100$ product
Ranking of 20% for sale of the product of 120$
But it changes the 10% commission on the sale of the product from 100$ to 20% commission

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://affiliatewp.com/support

we use GitHub for development tracking only.
