### ISSUE TITLE
Filter Referrals, Visits, and Campaigns reports by a single affiliate

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1991]
From some discussion in Slack:
> Right now, the "Reports" link for a single affiliate is basically a report for a single affiliate. Rather than have that be its own thing, I'd do the expandable/collapsible pane from the Affiliates list table, and if you want to see "reports", simply link to the Referrals tab in Reports, auto-filtered to show only one affiliate (or something).
>
> Sort of a move to unify the idea that if you want to look at "report-like" data, the place to always see that is in the Reports tabs.

Starting an issue to have some place to push code against.

**Comment by DrewAPicture** [comment]
Started a PR: #1992

**Comment by DrewAPicture** [comment]
Current progress in making the Reports tab filterable for a single affiliate:

* [x] Added an affiliate autocomplete input
* [x] Graph data now can reflect data only for a single affiliate
* [x] Registered 6 affiliate-only reports tiles shown when viewing the filtered view
* [ ] Switch the "Reports" link URL from affiliates list table

Current filtered view in Reports > Referrals:

![Filtered by affiliate](https://cl.ly/3k2M1Q453K2W/Screen%20Shot%202017-02-08%20at%2012.47.17-fullpage.png)

**Comment by DrewAPicture** [comment]
Thinking the Payouts tile could show all Payouts count rather than filtering by date and then rather than showing the date comparison label, simply link to list of all payouts for this affiliate.

**Comment by pippinsplugins** [comment]
This is looking great!

**Comment by pippinsplugins** [comment]
Ready for testing?

**Comment by DrewAPicture** [comment]
@pippinsplugins Yeah, give it a shot.

**Comment by pippinsplugins** [comment]
The reports page works _really_ well. Love it!

The `Reports` link from the affiliates list, however, does not work. It takes me to a screen like this:
![screen shot 2017-02-10 at 3 09 00 pm](https://cloud.githubusercontent.com/assets/1034109/22844258/ee5d26fe-efa2-11e6-9522-7442ff76e3a2.png)

**Comment by DrewAPicture** [comment]
As of 3d6a422d355c35582664a30dccbefd44e825c42e, the Reports links in the Affiliates list table should be hooked up correctly.

**Comment by pippinsplugins** [comment]
@DrewAPicture :+1:

Affiliate's that do not have a first name set end up without any name showing at all on the report tiles:
<img width="2011" alt="screen shot 2017-02-13 at 1 06 32 pm" src="https://cloud.githubusercontent.com/assets/1034109/22898585/727ca698-f1ed-11e6-9f0f-dbce5e30b692.png">
Once a name is added to their user account, it shows fine. We'll need to fallback to the user name.

**Comment by DrewAPicture** [comment]
@pippinsplugins 96e4f5a4759f8d291a6791316c6f9152d36ea073 updates the affiliate name to fall back to the username if no name is set.

**Comment by pippinsplugins** [comment]
That looks good.

**Comment by DrewAPicture** [comment]
@AffiliateWP/core this is ready for testing.

Originally, this was intended to simply add a single affiliate filter to the Reports > Referrals tab, but it was simple enough work to make that single affiliate filter work for the Visits and Campaigns tabs as well.

Things to look for:
* That setting the single affiliate filter persists (just like the date or custom date range) does when clicking through the various tabs.
* That links for affiliates with no names set fall-back to using the username
* That affiliate name/username labels show at the bottom of relevant tiles when a valid affiliate has been filtered

![Filtered Referrals](https://cl.ly/3k0w032c2B0I/Screen%20Shot%202017-03-21%20at%2017.48.24-fullpage.png)

![Filtered Visits](https://cl.ly/1N2L2W2J0i1F/Screen%20Shot%202017-03-21%20at%2017.49.32-fullpage.png)

![Filtered Campaigns](https://cl.ly/3U2J0Z3h2j2D/Screen%20Shot%202017-03-21%20at%2017.51.06-fullpage.png)

**Comment by DrewAPicture** [comment]
In essence, the addition of the single affiliate filters on these tabs effectively replaces the View Affiliate screen, rather pushing the user to the reports screen which is fully modularized for date ranges.

**Comment by pippinsplugins** [comment]
@DrewAPicture just ran through all the screens and it appears to all be correct! Looks great too!

**Comment by DrewAPicture** [comment]
Merged #1992.

**Comment by wordmaid** [comment]
🙌 🙌 🙌
