### ISSUE TITLE
affwp_get_affiliate_conversion_rate() should use affwp_format_rate()

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1994]
Currently, `affwp_get_affiliate_conversion_rate()` simply hard-concatenates the `%` sign onto the end of the conversion rate. We should probably be using `affwp_format_rate()` here instead.

**Comment by DrewAPicture** [comment]
Added a PR: #1995 

Existing tests still pass.

**Comment by pippinsplugins** [comment]
Looks good.
