### ISSUE TITLE
Show "Total" for payouts within a date range

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1996]
I'm not sure how this would work, but it would be great to easily see the total amount paid out over a date range on the Payouts screen.

For example, I pay affiliates once a month, it would be awesome to be able to easily see the total of all of those payouts automatically. I could filter the dates to the month I paid my affiliates in, and see a total of how much I paid my affiliates in that month.

Thoughts? :)

Related: #1997

**Comment by DrewAPicture** [comment]
Easy enough to accomplish with our current codebase. Where would you want to put this information?
```php
$total = array_sum( affiliate_wp()->affiliates->payouts->get_payouts( array(
    'number' => -1,
    'fields' => 'amount',
    'date' => array(
        'start' => beginning date,
        'end' => ending date
    )
) ) );
```

**Comment by wordmaid** [comment]
Hmm, not sure, perhaps it lives on the main Payouts screen, or perhaps it lives in Reports (#1997) but it in any case would be good to show the detailed payout info included in that date period...

**Comment by pippinsplugins** [comment]
How about a `Payouts` tab added to the reports screen?

**Comment by DrewAPicture** [comment]
I'm not against adding a tab, I'm just asking what we information we envision living there? Pretty much all of the other existing Reports tabs offer a wealth of calculation and correlation to other objects, and all I see here is a suggestion to display one metric of data.

What other data can we show on a tab that isn't already displayed in the others? :-)

**Comment by DrewAPicture** [comment]
Closing in favor of #1997.
