### ISSUE TITLE
Incorrect referral URL generated when extra space added

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1998]
On the `Page URL` input field, it's possible for an affiliate to add a space to the end of the URL, after the trailing slash. This isn't an issue when there is no slash since the URL validation catches the extra space and shows the validation notice.

When `Generate URL` is then clicked the `Referral URL` shown is incorrect, since it adds `%20` to the URL: `http://issues.affwp.dev/%20/?ref=16`.

We'll need to update the URL validation to also catch the extra space after the trailing slash. Another option is to just `trim` the `#affwp-url` input field but it seems like a better idea to update the validation for consistency.

![screen shot 2017-02-09 at 12 08 08 pm](https://cloud.githubusercontent.com/assets/52581/22761689/be78f59a-eec0-11e6-92d5-8b8bbb25ff93.png)

**Comment by DrewAPicture** [comment]
Well, to be fair, if you're adding a space at the end, getting a result with an encoded space on the end would seem to be expected, no? :-P

**Comment by DrewAPicture** [comment]
`trim()` should do it.

**Comment by sumobi** [comment]
@DrewAPicture Yes, however we already account for this without the slash. So if that was the case, then adding a space to the end of the URL with no slash would also allow the generator to create the URL with `%20` in it. I think we should do one or the other, I prefer the validation so it's consistent with adding a space to the URL with no slash.

**Comment by DrewAPicture** [comment]
Added a PR: #2000

**Comment by DrewAPicture** [comment]
Validation can be educational, but it can also be extremely frustration to the point of feeling pedantic. If the user is pasting in a link or even adds spaces before or after, I think there's value in silently stripping those extra characters without giving the user extra steps.

**Comment by DrewAPicture** [comment]
Case in point: We run `trim()` on API keys for reCaptcha in the admin when saving. We don't show a validation error, we just take care of it. I don't see this experience as needing to be any different.

**Comment by sumobi** [comment]
@DrewAPicture 👍 Thanks, that makes sense

**Comment by DrewAPicture** [comment]
Sure, we can do that.

**Comment by DrewAPicture** [comment]
I think we're covered here if I'm not mistaken. Extra spaces (before and/or after) should _always_ be stripped with this PR regardless of whether there's a trailing slash or not.

**Comment by sumobi** [comment]
Yep all good on this!
