### ISSUE TITLE
Contact Form 7: PayPal redirect not working when item price is left blank

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1999]
A customer has reported that their Contact Form 7 payment form no longer redirects to PayPal. When the Contact Form 7 integration is disabled in AffiliateWP, the form now correctly redirects to PayPal. 

The redirect to PayPal doesn't work because the item price field from the supported PayPal add-on is blank:

![screen shot 2017-02-09 at 3 13 47 pm](https://cloud.githubusercontent.com/assets/52581/22766463/700c766a-eeda-11e6-86b3-bcdc94e5064c.png)

As soon as an item price is entered the redirect works and the form takes you to PayPal on submission. As noted by the PayPal add-on, the item price field is optional.

> (Optional, if left blank customer will be able to enter their own price at checkout. Format: for $2.99, enter 2.99)

And as per our docs (http://docs.affiliatewp.com/article/657-contact-form-7):

> Optionally, enter an  Item Description, Item Price, or Item ID / Sku:

So it seems we don't support a blank item price ($0.00 works by the looks of it but then you see $0.00 on PayPal, not a blank value). @ramiabraham is generating referrals based on a blank item field something we can support? That is, allowing the customer to enter their own amount at PayPal, and generating the referral based on that amount.

Confirmed the above locally.

**Comment by ramiabraham** [comment]
@AffiliateWP/core  I tried replicating this locally and could not; could someone else try pretty please? 

Screencast of transaction process:

![ALT_TEXT](https://cldup.com/y-OTdHFruN.mp4 "TITLE")

PayPal settings:

![ALT_TEXT](https://cldup.com/RuBSkGQjpw.png "TITLE")

**Comment by pippinsplugins** [comment]
Why would someone else want to go to paypal for a 0.00 submission? Seems like we should just auto disable the redirect to PayPal if it's 0.00.

**Comment by sumobi** [comment]
@ramiabraham weird, I replicated first go, did you try creating a brand new form?

@pippinsplugins Leaving off the item price allows the customer to define their own price, it may not always be $0.00.

**Comment by pippinsplugins** [comment]
Ah, didn't realize it allowed them to enter their own price.

**Comment by sumobi** [comment]
I set this all up on our live dev site but can't replicate. So that leaves

Customer - can replicate
Andrew - can replicate locally
Rami - cannot replicate
Live dev site - cannot replicate

@AffiliateWP/core If someone else can test that would be appreciated.

**Comment by sumobi** [comment]
And suddenly both my test forms are now working without making any changes. I suspect I've triggered something, perhaps by saving a specific page or such. @ramiabraham When you tested, did you set up a brand new form?

**Comment by wordmaid** [comment]
I can replicate the issue as well (on a brand new sub-site of my multisite installation) and the item price left blank.

With the CF7 integration enabled:

<img width="717" alt="screen shot 2017-02-10 at 5 42 46 pm" src="https://cloud.githubusercontent.com/assets/11830108/22814520/29f705ac-efb9-11e6-8cd7-8521b6bbe350.png">

With the CF7 integration disabled it redirected me to PayPal:

<img width="1001" alt="screen shot 2017-02-10 at 5 45 42 pm" src="https://cloud.githubusercontent.com/assets/11830108/22814528/3b791e14-efb9-11e6-9c6c-e23f99db34ec.png">

**Comment by sumobi** [comment]
And now mine is broken again after wiping the forms and adding a new one. @ramiabraham It's possible you might be able to replicate by setting up a brand new install.

**Comment by ramiabraham** [comment]
@sumobi Will try that. I did create a new form yes

**Comment by sumobi** [comment]
@ramiabraham Finally found it. When no affiliate is being tracked, the redirect to PayPal doesn't occur. When you're tracking an affiliate it works fine.

**Comment by ramiabraham** [comment]
Added a PR: https://github.com/AffiliateWP/AffiliateWP/pull/2032 (WIP)

**Comment by ramiabraham** [comment]
@AffiliateWP/core Ready for review ([PR](https://github.com/AffiliateWP/AffiliateWP/pull/2032)).

**Comment by sumobi** [comment]
@ramiabraham It's still not redirecting to PayPal for me (while not tracking an affiliate). Confirmed I'm on correct branch etc.

**Comment by ramiabraham** [comment]
Strange...working here. Will check and see what my local issue is.

**Comment by ramiabraham** [comment]
@AffiliateWP/core Fixed and ready for review.

**Comment by sumobi** [comment]
@ramiabraham Works for me 👍
