### ISSUE TITLE
Support Stripe subscriptions

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2003]
It would appear that our Stripe Checkout (through WP Simple Pay) does not support subscriptions.

**Comment by pippinsplugins** [comment]
@sumobi when you were testing it, was there an initial non-zero payment processed or was it a free trial?

**Comment by pippinsplugins** [comment]
Looks like the subscriptions add-on doesn't fire the `simpay_charge_created` hook, nor does it have a similar hook for us to use.

@pderkson could a hook be added please?

**Comment by pippinsplugins** [comment]
@pderksen could a hook be added please?

**Comment by sumobi** [comment]
@pippinsplugins No initial referral created for a subscription with free trial, or subscription without free trial.

**Comment by pderksen** [comment]
@pippinsplugins @sumobi Not a problem. A few things...

1) We neglected to add in the `simpay_charge_created` hook for subscriptions as Stripe automatically creates a charge right then (if necessary) after calling `\Stripe\Subscription::create` if it's _not_ a free trial nor has a setup fee associated with it.

2) I think we'll also add a `simpay_subscription_created' hook as in the case of a free trial where a charge is not created immediately. Of course both of these hooks would fire at the same time in the other scenarios in above point (no free trial or initial setup fee charge). Sound good?

3) What email can I send a license to WP Simple Pay Pro & the Subscriptions add-on in case you guys would like to test it further (I don't think I've done this yet)?

4) Again I will make sure WP Simple Pay Pro 3.0 (a rewrite and in beta currently) will be compatible in the same way.

**Comment by sumobi** [comment]
@pderksen support@affiliatewp.com would be great, thanks!

**Comment by pippinsplugins** [comment]
A `simpay_subscription_created` action would be perfect!

**Comment by pderksen** [comment]
Just pushed an update to our Subscriptions add-on (1.3.5) with the 2 hooks `simpay_charge_created`and `simpay_subscription_created` as described above.

Sent a business license of WP Simple Pay Pro (including Subscriptions) to support@affiliatewp.com as well.

Let me know if you need anything else.

**Comment by pippinsplugins** [comment]
This is ready for testing! I've tested it with one time charges, subscription purchases, and subscription purchases that include a free trial.

**Comment by sumobi** [comment]
Nice, works perfectly
