### ISSUE TITLE
Add new Affiliate Form Settings to the system info file

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2011]
Would be good to know what they have set for these added with 2.0x

![affiliate-form-settings](https://cloud.githubusercontent.com/assets/3018245/22841762/9cfa7df4-ef87-11e6-9e43-57f2b41e859d.png)

**Comment by DrewAPicture** [comment]
Good catch. We'll make sure to get this in with 2.0.2.

**Comment by DrewAPicture** [comment]
PR: #2020 

Decided to consolidate all registration settings into a new section. Looks like this:
```txt
-- AffiliateWP Registration Settings

Allow Affiliate Registrations:    True
Require Approval:                 False
Auto Register New Users:          False
Required Registration Fields:     Your Name, Website URL
```

**Comment by pippinsplugins** [comment]
Merged!
