### ISSUE TITLE
Add core object counts to system info log

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2012]
An issue came up the other day when we were attempting to troubleshoot what ultimately was a scaling problem on a customer site. We didn't have accurate counts of the core objects without being able to login to the admin dashboard, and though it might be useful to include those counts in this log.

**Comment by DrewAPicture** [comment]
Added a PR: #2013 

I ended up adding a `count()` method to the campaigns db class + tests as well.

**Comment by DrewAPicture** [comment]
Output looks like this:
```txt
-- AffiliateWP Object Counts

Affiliates:                       137,015
Campaigns:                        70
Creatives:                        17
Payouts:                          6,745
Referrals:                        35,866
REST Consumers:                   4
Visits:                           541
```

**Comment by pippinsplugins** [comment]
You have a lot of affiliates . . . :D

**Comment by pippinsplugins** [comment]
Merged!
