### ISSUE TITLE
Add action hook to process_bulk_action() method in affiliates list table class

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2016]
We should add an action hook in the `process_bulk_action()` method of the affiliates list table class like we do for the referrals list table class: https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/admin/referrals/class-list-table.php#L678

**Comment by sumobi** [comment]
Added PR: https://github.com/AffiliateWP/AffiliateWP/pull/2017

**Comment by pippinsplugins** [comment]
I don't see any issues with this :+1:
