### ISSUE TITLE
Add filter so a custom affiliate view is possible

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2025]
It would be nice to be able to add a custom view. The `$views` array here would need to be filterable: https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/admin/affiliates/class-list-table.php#L145

I.e. although not a "status" we could add a custom view of "flagged" and show a link such as this: 
![screen shot 2017-02-15 at 3 29 50 pm](https://cloud.githubusercontent.com/assets/52581/22958345/9dbed9aa-f393-11e6-83c5-a6b7b69ea305.png)

The new filter would allow this custom view to be added, and when clicked we can then filter the affiliates list: https://github.com/AffiliateWP/AffiliateWP/issues/2024

The only negative about this that I can see is that the `All` count only refers to the statuses. The extra `Flagged` view count is not any particular status.

**Comment by pippinsplugins** [comment]
@sumobi it's already filterable. See line 400 of `WP_List_Table` https://developer.wordpress.org/reference/classes/wp_list_table/

**Comment by sumobi** [comment]
@pippinsplugins Nice!
