### ISSUE TITLE
get_fallback_affiliate_id() duplicates code

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2026]
The `get_fallback_affiliate_id()` method has some duplicate code that's already handled by `get_affiliate_id_from_login()`.

Specifically https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/class-tracking.php#L492-L497

We can swap this out for https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/class-tracking.php#L632

As a bonus this will fix https://github.com/AffiliateWP/affiliatewp-custom-affiliate-slugs/issues/30 since we'll now be able to retrieve the correct affiliate ID when fallback tracking and custom affiliate slugs are used together.

I'd really ❤️  if this could make it into v2.0.2.

🙏

**Comment by sumobi** [comment]
Added PR https://github.com/AffiliateWP/AffiliateWP/pull/2027

**Comment by pippinsplugins** [comment]
Looks good, merged!
