### ISSUE TITLE
Referral link on homepage shows WooCommerce product message when Polylang is active

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2028]
When Polylang is used with WooCommerce, and a pretty affiliate URL is used on the homepage, it shows a `No products were found matching your selection.` message. Non-pretty URLs work fine. As soon as you take away the `/ref/123` portion of the URL, the homepage is shown correctly. Disabling Polylang also makes the homepage show as expected.

![screen shot 2017-02-15 at 10 29 04 pm](https://cloud.githubusercontent.com/assets/52581/22968159/3135b3d6-f3ce-11e6-88d4-8ada1d3f55ea.png)

Setting a static front page doesn't seem to matter. So far I've only replicated on the customer's site, I'm having trouble actually setting up Polylang with WooCommerce.

Support ticket: https://secure.helpscout.net/conversation/319283450/52987/?folderId=205531
Related: https://github.com/AffiliateWP/AffiliateWP/issues/1192

**Comment by sumobi** [comment]
Managed to replicate the issue finally. Here's some different scenarios that I tested to see how Polylang (2.1.3), AffiliateWP (2.0.7.1) and WooCommerce (3.x) play together.

___

- Plugins active: `AffiliateWP`, `Polylang`, `WooCommerce`
- Affiliate link: `http://woocommerce.affwp.dev/ref/6/`
- Front page displays: `Static page`

**Expected outcome:**
Show the custom front page.

**Actual outcome:**
- Homepage shows the WooCommerce "No products were found matching your selection." This is the issue the customer is experiencing. 
- Disabling Polylang makes it show the custom front page as expected. 
- Cookies are correctly stored by AffiliateWP.

![screen shot 2017-05-05 at 2 46 57 pm](https://cloud.githubusercontent.com/assets/52581/25732265/b5acf320-31a1-11e7-8426-7001f0b2df22.png)


___

- Plugins active: `AffiliateWP`, `Polylang`
- Affiliate link: `http://woocommerce.affwp.dev/ref/6/`
- Front page displays: `Static page`

**Expected outcome:**
Show the custom front page.

**Actual outcome:**
- Homepage shows "Nothing Found". 
- Cookies are correctly stored by AffiliateWP.

![screen shot 2017-05-05 at 2 36 14 pm](https://cloud.githubusercontent.com/assets/52581/25732102/3bc0c39e-31a0-11e7-9cad-b8087e222531.png)
___

**Comment by pippinsplugins** [comment]
That sounds like a Polylang bug rather than an AffiliateWP bug, yes?

**Comment by sumobi** [comment]
@pippinsplugins The original issue only occurs when using Polylang and a pretty affiliate link so I feel it's something we might be able to fix from our end, similar to other issues we have/have had where pretty affiliate links don't show the page's content properly.

There _is_ some funkiness between Polylang and WooCommerce, when AffiliateWP is **not** installed, though it's a slightly different issue as noted in the last test. The entire issue is pretty confusing to say the least, lots of variables involved. Here's a few more tests to try and make things clearer.

- Plugins active: `AffiliateWP`, `Polylang`
- Front page displays: `Static page`

Here's the expected front page (static) of the site when no affiliate link is used. It's also what you see when a non-pretty affiliate link is used. Ignore the fact that the site is called WooCommerce (it's not active).

![screen shot 2017-05-09 at 11 47 29 am](https://cloud.githubusercontent.com/assets/52581/25829897/64803a84-34ad-11e7-9390-905bd1739ba4.png)

And here it is again, with a pretty affiliate link:

![screen shot 2017-05-09 at 11 47 41 am](https://cloud.githubusercontent.com/assets/52581/25829913/7bd9ca60-34ad-11e7-8fde-ce1a4c221a3a.png)

The above is the actual issue in its simplest form. By only activating WooCommerce (and using a pretty affiliate link as per the above) the display changes ever so slightly. This is what the customer is reporting:

![screen shot 2017-05-09 at 11 50 09 am](https://cloud.githubusercontent.com/assets/52581/25829978/d8600132-34ad-11e7-8d64-b20422151883.png)

**Comment by DrewAPicture** [comment]
There's definitely some screwy things going on with some of the rewrites generated by Polylang, such as double ampersands in some cases, which throw off the ability to parse matches.

I think with this combination, our best option is to only recommend using non-pretty affiliate URLs in conjunction with Polylang. I just confirmed that passing a query var will work in this scenario.

**Comment by pippinsplugins** [comment]
How about adding a dynamic notice below the pretty URL settings to give the admin a heads up about the compatibility issue if they have Polylang and Woo both activated?

**Comment by DrewAPicture** [comment]
I'll work on it.

**Comment by DrewAPicture** [comment]
@pippinsplugins How's this?

> Note: Pretty affiliate URLs may not always work as expected when using AffiliateWP in combination with WooCommerce and Polylang.

PR: #2244

**Comment by pippinsplugins** [comment]
Looks good to me!

**Comment by DrewAPicture** [comment]
Merged #2244.
