### ISSUE TITLE
Contact Form 7 tab in Settings - documentation link invalid, 404

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2029]
Its looking for the link:

http://docs.affiliatewp.com/article/TODO

![contact-form-7-settings](https://cloud.githubusercontent.com/assets/3018245/22993036/621ae604-f376-11e6-9bbe-fd1913fc01c8.png)

**Comment by DrewAPicture** [comment]
Duplicate of and fixed in #2005, which will ship with 2.0.2. Thanks for the report though :-)

**Comment by gspice** [comment]
Thanks @DrewAPicture !  I forgot to search "Closed" :-)
