### ISSUE TITLE
Contact Form 7:  referral created when form has validation errors

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2030]
* Testing with NO PayPal integration, just Contact Form 7 integrated in Settings => Integration
* Using default contact form that is there when you first install plugin
* incorrectly entered the email address so form generated an error "The e-mail address entered is invalid."
*  Referral was still created.  When I corrected the email address and click to Send again received a 2nd referral.

**Comment by pippinsplugins** [comment]
I can't say for sure, but it's quite possible this will be an issue we simply cannot resolve and is one of _many_ reasons to encourage people to use an alternative form plugin.

**Comment by sumobi** [comment]
Sounds exactly like #2004. 

It does sound like we can resolve this issue, since it only occurs when an affiliate is being tracked. The form validation works fine when not tracking an affiliate.

**Comment by wordmaid** [comment]
Just want to note on here that I also encountered this issue on a customer's site recently; on form submission, even if the correct information was not provided in the form and an error is shown, a referral is created.

**Comment by amdrew** [comment]
@gspice Are you still able to replicate this issue? I wonder if #2004 fixed it or not.

**Comment by gspice** [comment]
@amdrew  I re-tested and you are correct, it is fixed, form did not create a referral when there were submission errors.

**Comment by amdrew** [comment]
@gspice Sweet!
