### ISSUE TITLE
Refactor get_affiliate_id_from_login() to simply use affwp_get_affiliate()

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2035]
Since 1.9, `affwp_get_affiliate()` can accept an affiliate ID or username, which renders most of the logic in `get_affiliate_id_from_login()` moot.

**Comment by DrewAPicture** [comment]
PR: #2042 (includes full test coverage for `get_affiliate_id_from_login()`)

**Comment by pippinsplugins** [comment]
Looks great, merged!
