### ISSUE TITLE
An affiliate link of /?ref/123 stores a visit when fallback tracking is enabled.

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2037]
When fallback tracking is enabled you can use a referral link in the following format and it will store a visit:

http://site.com/?ref/123

**Comment by pippinsplugins** [comment]
Removing `/` and other non-allowed characters from the `ref` URL parameter should take care of this.

**Comment by pippinsplugins** [comment]
This actually works 100% without any breakage. While it's weird that it works, I think we should leave this as is since it doesn't hurt anything and could potentially be resulting in fewer tickets.

It works because of this logic in `get_fallback_affiliate_id()`:

```
$path = ! empty( $_SERVER['REQUEST_URI' ] ) ? $_SERVER['REQUEST_URI' ] : '';

if ( false !== strpos( $path, $this->get_referral_var() . '/' ) ) {

	$pieces = explode( '/', str_replace( '?', '/', $path ) );
	$pieces = array_map( 'sanitize_key', $pieces );
	$key    = array_search( $this->get_referral_var(), $pieces );

	if ( $key ) {

		$key += 1;
```

**Comment by DrewAPicture** [comment]
If we ever wanted to fix this, doing a `preg_match()` might be a better way to go.
