### ISSUE TITLE
Affiliate name filter on Visits screen not working

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#2039]
When using the filter on the Visits screen to specify an affiliate and date range, visits within specific dates are correctly reported, but the visits for a specific affiliate are not. An example:

1. I have generated 60 visits in total for this dev site:

<img width="1429" alt="screen shot 2017-02-21 at 11 08 28 am" src="https://cloud.githubusercontent.com/assets/11830108/23143518/c2f00964-f826-11e6-8c64-4bb0c78d27ea.png">

2. When I specify my date range from September to October last year, there were 16 visits counted, across all affiliates:

<img width="1464" alt="screen shot 2017-02-21 at 11 09 48 am" src="https://cloud.githubusercontent.com/assets/11830108/23143532/daeb3976-f826-11e6-8b40-ab3d72bd0119.png">

3. However when I specify an affiliate, the visit count doesn't change. It shows total visits in that date range, but not for that affiliate. There should only be 5 visits for my "test16" affiliate, but it is showing all 16 visits from the September-October date range:

<img width="1463" alt="screen shot 2017-02-21 at 11 12 00 am" src="https://cloud.githubusercontent.com/assets/11830108/23143567/fe3e32e8-f826-11e6-91b1-c8f34e3a3db3.png">

4. Even when I search just by the affiliate, the correct visit count is still not shown. It just shows all visits generated by all affiliates for all time (60 total): 

<img width="1442" alt="screen shot 2017-02-21 at 11 17 27 am" src="https://cloud.githubusercontent.com/assets/11830108/23143645/5f767fd4-f827-11e6-85c7-b6163a207748.png">

Is anyone else able to replicate? I've also checked the Referrals page and the filters appear to be working fine there.

**Comment by DrewAPicture** [comment]
I'll look into it.

**Comment by DrewAPicture** [comment]
Confirmed. Broken in 2.0 when we changed how the affiliate autocomplete field worked.

PR: #2043

**Comment by pippinsplugins** [comment]
Confirmed bug on `master` and confirmed fix on `issue/2039`. Merge once tests pass.
