### ISSUE TITLE
WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4.

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2040]
As reported by a customer using PHP 7:

FILE: /wp-content/plugins/affiliate-wp/includes/admin/tools/export/class-export-settings.php
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
47 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4.

FILE: /wp-content/plugins/affiliate-wp/includes/admin/tools/export/class-batch-export.php
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
149 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4.

FILE: /wp-content/plugins/affiliate-wp/includes/admin/tools/export/class-export.php
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
65 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4.

FILE: /wp-content/plugins/affiliate-wp/includes/admin/tools/system-info.php
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
184 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4.

**Comment by pippinsplugins** [comment]
Technically it's a false positive as we do an `ini_get()` call on it to determine if it's available before using it.

This causes enough reports, however, that I vote we remove it.

**Comment by DrewAPicture** [comment]
PR: #2115
