### ISSUE TITLE
Settings - General - Affiliate Area Forms selection, add note applies to default only

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2047]
![settings-general-affiliate-area-forms](https://cloud.githubusercontent.com/assets/3018245/23233034/5ae4c9ea-f902-11e6-9e1f-8fe5b87816d5.png)

When selecting options such as show registration or login only, this does not apply if they are using a Gravity Form or Ninja Form add-on for registrations.   In those cases even when set it will show both registration and login forms. 

Request is to add a note to say this only applies to the default registration forms.  I'm not good with the best, exact wording but that is the general idea of my request :-)

**Comment by sumobi** [comment]
@gspice Provided they are on the latest version of Affiliate Forms for Gravity Forms then it should work fine, released an update for this just after 2.0. Affiliate Forms for Ninja Forms should also be fine, @ramiabraham tested that. 

What versions of each pro add-on is the customer/s using?

**Comment by gspice** [comment]
@sumobi Excellent catch!  My test site doesn't prompt me to update pro add-ons so I will need to stay on top of that, I had 1.0.11.  I loaded 1.0.12 from the Master branch and it is observing the Affiliate Area Forms settings. Closing issue.
