### ISSUE TITLE
Short circuit visit creation

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2049]
We should provide a filter to short circuit the creation of a visit in both tracking methods (standard and fallback). This would be useful for: https://github.com/AffiliateWP/affiliatewp-affiliate-landing-pages/issues/7

**Comment by DrewAPicture** [comment]
Added a PR: #2087

**Comment by pippinsplugins** [comment]
@DrewAPicture I think this filter might be too early. For landing pages, the filter will need to be set to false once we know that it is a landing page, which cannot happen this early (I think).

**Comment by DrewAPicture** [comment]
Yeah, the problem we kind of have is not wanting to navigate the spider's web of hooked actions and things that actually track visits. Because it's not enough to just prevent the visit from being added; there are other variables in play such as setting the current affiliate ID and visit IDs in properties that the rest of the tracking class relies on.

I'll look at an alternative approach, maybe with a new conditional method.

**Comment by DrewAPicture** [comment]
For instance, I could easily see several log entries being written every time a visit is prevented from being created if we just disrupt adding the visit.

**Comment by pippinsplugins** [comment]
As long as it's possible to short circuit the visit creation _after_ determining the page / query vars, I'm happy :)

**Comment by DrewAPicture** [comment]
@pippinsplugins So can we just skip this now that the PR for https://github.com/AffiliateWP/affiliatewp-affiliate-landing-pages/issues/7 has been merged?

**Comment by pippinsplugins** [comment]
I think having the filter to short circuit this is still a good idea. I vote we merge it in.

**Comment by DrewAPicture** [comment]
After some contemplation, I've adjusted the PR to allow short-circuiting closer to the source of creating the visit to allow environmental variables to get set up. I also introduced a second visit for short-circuiting the conversion – the params are similar but slightly different.

@pippinsplugins interested in your opinion on this alternative approach.

**Comment by pippinsplugins** [comment]
@DrewAPicture I really like this approach!

Only thing I see is the `@since` tags need updated since this is going into 2.1.

**Comment by DrewAPicture** [comment]
It should be noted that `$this` is passed to both hooks, so fallback tracking can be determined by checking the property directly. I think there's value in only using a single hook for  bothregular or fallback tracking in the spirit of future compatibility.

Also worth mentioning that the trade-off of short circuiting so much later in the process is that the cookies will be set. This can be viewed as both an upside and downside.

**Comment by DrewAPicture** [comment]
@pippinsplugins Updated versions in 647b3f0bda4b75b6aa58bd47155da836a1fcfd82.

**Comment by pippinsplugins** [comment]
Looks good, let's merge once tests pass.

**Comment by DrewAPicture** [comment]
Merged #2087.
