### ISSUE TITLE
PayPal: Add support for PayPal's IPN Forwarder by disabling our IPN URL

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2053]
Add option to  "Disable IPN URL"  on the PayPal integration.

Ran into problem on this ticket below where the user has a PayPal IPN Forwarder.  They are redirecting the IPN then attempting to Forward to our affwp listener and it does not work.  

https://secure.helpscout.net/conversation/323582666/53721/?folderId=1170842

**Comment by pippinsplugins** [comment]
@gspice until we get it added, you could direct the customer to this line https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-paypal.php#L57

Removing that would resolve the issue.

**Comment by pippinsplugins** [comment]
Related https://github.com/AffiliateWP/AffiliateWP/issues/2245

**Comment by gspice** [comment]
Another one:
https://secure.helpscout.net/conversation/412667024/64717/?folderId=205529

**Comment by pippinsplugins** [comment]
I don't think we need to do this any longer. Customers that wish to use an IPN forwarded can simply add the `AFFILIATEWP_PAYPAL_IPN` constant to their wp-config.php with the proper URL.
