### ISSUE TITLE
Enhance the Affiliate URLs tab

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2054]
Here's the standard `Affiliate URLs` tab:

<img width="602" alt="screen shot 2017-02-24 at 4 16 19 pm" src="https://cloud.githubusercontent.com/assets/52581/23289135/9c2b62b4-faac-11e6-8df5-7fd2a6b20250.png">

I propose we:

1. Move the `Referral URL Generator` header to just above the `Enter any URL...` line since it belongs with the generator tool

2. Add an `Affiliate URLs` heading at the top of the tab since that will match what the tab describes (like the other tabs)

3. Add some more hooks in the template file. It's a bit limiting on where you can place things. In the Affiliate Landing Pages add-on we can only place URLs at the very top of the tab (https://github.com/AffiliateWP/affiliatewp-affiliate-landing-pages/issues/1#issuecomment-282181481)

The revised tab layout might look like this:

<img width="604" alt="screen shot 2017-02-24 at 4 21 56 pm" src="https://cloud.githubusercontent.com/assets/52581/23289252/6d2c3b2c-faad-11e6-9507-f8b46d72649d.png">

**Comment by pippinsplugins** [comment]
Definitely good changes here. Let's do it!

**Comment by DrewAPicture** [comment]
@sumobi I agree, let's get a PR started.

Can we also take down the size of the "Page URL" and "Campaign Name (optional" headers a level? They look like the same size as "Referral URL Generator".

**Comment by sumobi** [comment]
👍 Those are just labels, I'll have a play and test with a few themes to find a good balance.

**Comment by sumobi** [comment]
@AffiliateWP/core Ready for review

PR: https://github.com/AffiliateWP/AffiliateWP/pull/2062

I've opted for a `h5` header for `Referral URL Generator`. Currently each tab header is a `h4`. Shown below are different theme screenshots to see how the heading looks. I've also tightened up the space between the affiliate ID and URL.

There are 2 new hooks:

`affwp_affiliate_dashboard_urls_before_generator`
`affwp_affiliate_dashboard_urls_bottom`
___

## Make:
![screen shot 2017-03-02 at 4 48 21 pm](https://cloud.githubusercontent.com/assets/52581/23492240/1e7ed254-ff68-11e6-91cc-a5e396d2960b.png)

___
## Themedd:
![screen shot 2017-03-02 at 4 46 54 pm](https://cloud.githubusercontent.com/assets/52581/23492241/1e7fe040-ff68-11e6-8164-9a6e2e9ca068.png)
___
## 2013:
![screen shot 2017-03-02 at 4 45 53 pm](https://cloud.githubusercontent.com/assets/52581/23492251/2c89a1d0-ff68-11e6-85c2-0364b10c250d.png)
___
## 2014:
![screen shot 2017-03-02 at 4 45 38 pm](https://cloud.githubusercontent.com/assets/52581/23492249/2c87d0c6-ff68-11e6-9a2c-0b7b7ed36ede.png)
___
## 2015:
![screen shot 2017-03-02 at 4 45 19 pm](https://cloud.githubusercontent.com/assets/52581/23492252/2c8a0512-ff68-11e6-9e92-e34687edf152.png)
___
## 2016:
![screen shot 2017-03-02 at 4 45 01 pm](https://cloud.githubusercontent.com/assets/52581/23492248/2c87358a-ff68-11e6-9226-04fe5212f56e.png)
___
## 2017:
![screen shot 2017-03-02 at 4 44 42 pm](https://cloud.githubusercontent.com/assets/52581/23492250/2c87c176-ff68-11e6-99bb-4feaf7f4cdc5.png)
___

And finally, with the new hooks in place, this is how Affiliate Landing Pages shows the URLs:

![screen shot 2017-03-02 at 4 53 42 pm](https://cloud.githubusercontent.com/assets/52581/23492360/d4f11eac-ff68-11e6-8ecd-c53cbbc6b204.png)

**Comment by pippinsplugins** [comment]
This looks really good to me!

**Comment by DrewAPicture** [comment]
Looks good. Adjusted a couple of minor things and will merge once tests pass.
