### ISSUE TITLE
Add Unpaid Earnings to the Recount Stats tool

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2069]
Customer has an incorrect `Unpaid Earnings` amount but there's no way to perform a recount via the `Recount Affiliate Stats` tool.

<img width="431" alt="screen shot 2017-03-03 at 1 07 08 pm" src="https://cloud.githubusercontent.com/assets/52581/23532821/83035394-0012-11e7-8874-6b57ea12478c.png">

**Comment by pippinsplugins** [comment]
Seems to work great for me!

**Comment by pippinsplugins** [comment]
@sumobi could you test this as well?

**Comment by DrewAPicture** [comment]
Still working out the per-affiliate filtering, but almost there.

**Comment by DrewAPicture** [comment]
OK, per-affiliate filtering seems to work following 38f0055cf16073e91bf055b4d436da357216f12b. It handles the case where an invalid affiliate is entered. Seemed weird to default to thereby processing _all_ affiliates when entering an invalid affiliate.

**Comment by DrewAPicture** [comment]
The PR (#2082) does two things:
1. Adds Unpaid Earnings to the Recount Stats tool
2. Adapts the Recount Stats tool to use batch processing for all four options

Note: The recount stats tool can now efficiently be used to recount stats for _all_ affiliates or a specified one. In the event where an invalid affiliate is entered, the batch process will return an appropriate response.

**Comment by sumobi** [comment]
@DrewAPicture 

To recount stats for _all_ affiliates do you just hit the `Recount` button?

A few things:

1. If I leave the `Affiliate Name` field blank, select `Unpaid Earnings` and then hit `Recount` it says `1 affiliate was successfully processed.`

    <img width="1387" alt="screen shot 2017-03-08 at 12 16 13 pm" src="https://cloud.githubusercontent.com/assets/52581/23682589/7e4ae110-03f9-11e7-8028-118a655abb9b.png">

    If I then do it again, and again, the same message shows regardless. I have 14 active affiliates.

2. Same as above but for `Referrals`. `Visits` however shows 2 affiliates.

3. The icon to dismiss the notice is in a strange location.

**Comment by sumobi** [comment]
Works great to me!

**Comment by DrewAPicture** [comment]
With @sumobi's assistance, we've come up with a better messaging scheme for when the batch process has finished.

The confusion around the number of processed affiliates stems from the processor only performing recounts for affiliates that match the current filter, so if there's only one affiliate that has unpaid referrals currently, it will only recount unpaid earnings for one affiliate.

The new messaging, improved in 2666cb7f56dbec18fc10da2140eb06a6e11c195e, generalizes to "... for all matching affiliates" rather than giving and explicit number.

**Comment by DrewAPicture** [comment]
OK, merging.
