### ISSUE TITLE
Rename the 'affwp_dismiss_notices' action to avoid a dynamic hook conflict

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2070]
**Background:**
In 1.8, we introduced a default case to the `dismiss_notices()` method in #1182, which came with a new hook, `affwp_dismiss_notices`. For some time now, there has been a memory exhaustion issue with being able to dismiss notices in some add-ons, such as [Allowed Products](https://github.com/AffiliateWP/affiliatewp-allowed-products/issues/4).

After some investigation, it looks like the cause is a hook conflict. A common `affwp_action` value is 'dismiss_notices', which translates to the dyhamic `affwp_dismiss_notices` hook. At the same time, we're using 'affwp_dismiss_notices' in the default case. This means anything hooked to affwp_dismiss_notices outside the scope of core has a good possibility of causing recursion and eventually a 500 error.

**Comment by DrewAPicture** [comment]
PR: #2071

**Comment by pippinsplugins** [comment]
Whoops!
