### ISSUE TITLE
Referrals are being calculated at $0.00

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2073]
Since v2.0.3, referrals are being generated at `$0.00`, instead of the correct amount. Reported by customer using WooCommerce, I can also replicate the issue on 2.0.3 using WooCommerce and EDD.

This is the commit that causes $0.00 referrals: https://github.com/AffiliateWP/AffiliateWP/commit/e1aeaf87b5b8038b3b3e4ff229709875434d4271

Ticket: 
https://secure.helpscout.net/conversation/328184301/54436/?folderId=205524

Possibly this one also:
https://secure.helpscout.net/conversation/328179356/54435/?folderId=205524

**Comment by pippinsplugins** [comment]
Reverting fix from #1972 to fix this https://github.com/AffiliateWP/AffiliateWP/pull/2074
