### ISSUE TITLE
WPEC: Affiliate links show wrong page when "Front page displays" is set

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2078]
To replicate:

1. Activate WP eCommerce and AffiliateWP
2. Go to `Settings -> Reading` and set the sample page (or any other page) to be the `Front page`
3. Use either a pretty or non-pretty affiliate link on the homepage

Result:

![screen shot 2017-03-06 at 8 09 22 pm](https://cloud.githubusercontent.com/assets/52581/23599939/e0db4aec-02a8-11e7-8c1f-7820946e72ec.png)

Expected result:

![screen shot 2017-03-06 at 8 10 08 pm](https://cloud.githubusercontent.com/assets/52581/23599944/eb9f8542-02a8-11e7-8d6b-c3fc8f227676.png)

**Comment by pippinsplugins** [comment]
This is caused by the `add_rewrite_endpoint( affiliate_wp()->tracking->get_referral_var(), EP_ALL );` call in `Affiliate_WP_Rewrites::rewrites()`. I'm not immediately sure why but I suspect it's a collision with the WPEC rewrites.

**Comment by pippinsplugins** [comment]
Removing `add_filter( 'pre_get_posts', 'wpsc_split_the_query', 8 );` from WPEC resolves it.

The `wpsc_split_the_query()` function removes itself from `pre_get_posts`, like this:

```
remove_filter( 'pre_get_posts', 'wpsc_split_the_query', 8 );
```

Interestingly, removing that line from `wpsc_split_the_query()` resolves the problem.

@JustinSainton could you lend any feedback here?

**Comment by DrewAPicture** [comment]
Added a PR: #2237

**Comment by pippinsplugins** [comment]
PR fixes it!
