### ISSUE TITLE
Unpaid Earnings column in Affiliates screen not showing correct amount

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#2080]
I'm working with a customer at the moment who has an issue whereby the `Unpaid Earnings` shown on the _Affiliates_ page in the admin are not displaying the correct amount.

Ref: https://secure.helpscout.net/conversation/329488658/54578/?folderId=414056

Here is the issue:

1. _Affiliates_ page in admin is showing incorrect amount in the `Unpaid Earnings` column (~$4,290)
2. _Affiliate Area_ on front end is showing incorrect amount for the `Unpaid Earnings` total (~$4,290)
3. Exported CSV of referrals for affiliate calculates the correct amount (~$5,400)
4. I have manually calculated the referrals in the admin from the _Referrals_ screen for that affiliate and this reflects the correct amount as per the exported CSV of referrals in point 3. (~$5,400)

There is a discrepancy of over $1,100 in this instance.

Note: I have not been able to replicate on our own site with a couple of tests, and the customer is using version 2.0.3.

I know there was another ticket that @gspice was working on the other day where the customer had the same issue. @sumobi suggested to recount the Unpaid Earnings however it was discovered that there was no recount tool for Unpaid Earnings. Ref: https://github.com/AffiliateWP/AffiliateWP/issues/2069

It seems like this could be a bigger problem, and we might have more customers contacting us about discrepancies in their Unpaid Earnings.

@DrewAPicture do you think there could be an issue related to batch processing when customers were upgraded? Is there a way in the interim to manually recount the Unpaid Earnings to help customers with this issue?

**Comment by DrewAPicture** [comment]
> Is there a way in the interim to manually recount the Unpaid Earnings to help customers with this issue?

In lieu of the fix coming in #2069, you can delete the `affwp_completed_upgrades` option on the site (such as via Debug Bar Console) and that will force the upgrade routine notice to show which will expose the batch process UI for recounting unpaid earnings.

**Comment by wordmaid** [comment]
YASSS thank you @DrewAPicture! @sumobi helped me do this, and it worked a treat! The correct number is now showing on the _Affiliates_ screen. 🙌

**Comment by wordmaid** [comment]
@gspice If you want to follow up with your other customer (Ref: https://secure.helpscout.net/conversation/324457302/53854?folderId=205529), the above is how you can fix it in the interim.

**Comment by gspice** [comment]
@wordmaid Woot! Thank ya kindly!

**Comment by DrewAPicture** [comment]
I think we can close this as it can be mitigated with the new recount unpaid earnings option in the Recount Stats tool, merged in #2069.
