### ISSUE TITLE
Improve creatives page

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2081]
Here's our current creatives page. Depending on the size of the creative, some of them get stretched. The text is the middle 3 columns is also not vertically aligned.

![screen shot 2017-03-07 at 2 06 25 pm](https://cloud.githubusercontent.com/assets/52581/23637251/88c846b0-033f-11e7-9b13-c2859a388668.png)

___

Here's what I'm hoping to achieve. Vertically aligned text and nicer looking creative previews.

![screen shot 2017-03-07 at 2 07 30 pm](https://cloud.githubusercontent.com/assets/52581/23637250/88c21376-033f-11e7-9f3b-30dafdd2712b.png)

Will submit PR. Another plugin (Post Promoter Pro) is adding a width to all images within the image column so will open an issue on that repo to make the CSS selector more specific.

**Comment by sumobi** [comment]
PR: https://github.com/AffiliateWP/AffiliateWP/pull/2098

**Comment by pippinsplugins** [comment]
Looks good to me!
