### ISSUE TITLE
Rename "PayPal" to "PayPal Buttons"

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2083]
As per the discussion here: https://github.com/AffiliateWP/AffiliateWP/issues/1884#issuecomment-270497339

**Comment by sumobi** [comment]
And done https://github.com/AffiliateWP/AffiliateWP/commit/a7e0ce147b8a29a12d5230fba993254c93938caa

**Comment by pippinsplugins** [comment]
:+1:
