### ISSUE TITLE
Page set as front page does not show with affiliate link when using BuddyPress docs plugin

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2086]
To replicate:

1. Assign a page as your front page via Settings -> Reading
2. Make sure AffiliateWP, BuddyPress and BuddyPress docs (https://wordpress.org/plugins/buddypress-docs/) are installed and active
3. Visit your site homepage with a referral link (pretty or non-pretty)

Behaviour:
Loads the posts index

Expected behaviour:
Loads the page set as the front page

**Comment by DrewAPicture** [comment]
This _also_ appears to be fixed by #2237.
