### ISSUE TITLE
Warning: affwp_encyclopedia_pro_creatives_affiliate_area_compat

### ISSUE THREAD

**Issue by dancameron** [AffiliateWP/AffiliateWP#2088]
`Warning: Missing argument 2 for affwp_encyclopedia_pro_creatives_affiliate_area_compat(), called in /srv/users/serverpilot/apps/wordpress/public/wp-includes/class-wp-hook.php on line 298 and defined in /srv/users/serverpilot/apps/wordpress/public/wp-content/plugins/affiliate-wp/includes/plugin-compatibility.php on line 104`

**Comment by dancameron** [comment]
I could do a pull request but the solution on a new branch but the solution is too easy... pull 2089

**Comment by DrewAPicture** [comment]
Can you give a little more context for how you generated this error?

Why shouldn't both arguments be trusted to be passed? It's a core hook. This feels like developer error to me.

**Comment by DrewAPicture** [comment]
Custom template that fires the hook but doesn't pass both arguments? If that's the case, I think the onus is on the template developer to pass the values. I can certainly see how it would be a tug of war though.

**Comment by dancameron** [comment]
Ah man, I'm a bit embarrassed. I'll blame my cold 🤧.

However, I think it's legit to add this since the only reason this is coming up is because I'm using one of the original templates, which didn't include a second variable.

**Comment by dancameron** [comment]
https://github.com/AffiliateWP/AffiliateWP/commit/e720590837f8a22d612b57466ad4ecbb80cc2287#diff-0b1a19ff6ee8b3ee5f6854c7059a024d

**Comment by DrewAPicture** [comment]
That's a fair complaint. Need to be backward-compatible in this context.

**Comment by dancameron** [comment]
👍

**Comment by DrewAPicture** [comment]
@dancameron This will ship with 2.0.5. Thanks for catching this :-)
