### ISSUE TITLE
Admin Area: graph doesn't show 

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2091]
https://secure.helpscout.net/conversation/330887495/54727/?folderId=1170842

On the above ticket, any screen in the admin area where the graph should be showing is blank.  

![affiliate-report-view](https://cloud.githubusercontent.com/assets/3018245/23772448/d8c7de3c-04cf-11e7-808c-a701ca354e02.png)

There is an error showing in this location:

https://topspinpro.com/wp-admin/admin.php?page=affiliate-wp-affiliates&affiliate_id=25&action=view_affiliate

![console-error](https://cloud.githubusercontent.com/assets/3018245/23772461/e5526118-04cf-11e7-9e95-1611c4c74182.png)

There is an admin account on the ticket.   Normally I would ask to start deactivating plugins, but they've heavily customized the admin area, I don't see a Plugin list.  He responded and said he will create a staging site tomorrow for further exploration.

**Comment by sumobi** [comment]
Can't seem to replicate this issue on my set up

**Comment by gspice** [comment]
UPDATE:  the customer has created a staging site and removed all the admin restrictions.  Guessing the next step would be to deactivate plugins and see if the graph appears - I will work on this today.

**Comment by gspice** [comment]
Found the culprit, it's a plugin called "Soil".  When this plugin is activated it creates that error and doesn't show our graphs.  It is a premium plugin so I cannot download it, does anyone of access to it or should I just punt and tell the user about the conflict?

https://roots.io/plugins/soil/

**Comment by DrewAPicture** [comment]
For something (Soil) that claims to do markup cleanup on the front-end, it's curious that it's messing with markup in the admin.

**Comment by DrewAPicture** [comment]
Btw, Soil is OSS and on GitHub: https://github.com/roots/soil

Filing an issue.

**Comment by DrewAPicture** [comment]
Reproduced on local and opened a PR on the Soil repo: https://github.com/roots/soil/pull/178

**Comment by DavidSchargel** [comment]
Fixed. Update your roots/soil.

**Comment by DrewAPicture** [comment]
This issue has been fixed in the Soil plugin.
