### ISSUE TITLE
Admin shortcut to add an existing user as a new affiliate

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2093]
Right now there are several different pathways by which an existing user can be added as an affiliate:

1. Add a new affiliate directly via Affiliates  > Add New
2. The user can (if enabled) register themselves via the profile editor
3. Register when logged-in via the affiliate registration form
4. Via the User Migration tool (en masse)

![Add Affiliate link](https://cl.ly/1d34243A2Z1Z/Screen%20Shot%202017-03-10%20at%2010.49.37%20AM.png)

Seems to me that an obvious missing pathway is the so-called "convert this single user to an affiliate" from the admin. I propose that we add an action link to each row in the Users list table to quickly add them as a new affiliate. This would basically follow the pattern of clicking the action link, then auto-filling some values in the New Affiliate form for the given user.

Particularly interested in feedback from @sumobi and @wordmaid here.

**Comment by wordmaid** [comment]
Makes sense. I like it! I'm all about the if-here-then-there. Could definitely make life a bit easier! 😄 

I think it should follow the behaviour of the other ways to add an affiliate, whereby if the **Require Approval** option is enabled in `Affiliates -> Settings -> Misc`, the affiliate goes to a _Pending_ status, and if **Require Approval** is not enabled, the affiliate goes straight to _Active_ status.

Perhaps when the Add Affiliate is successful the admin could be shown a notice notice saying `Affiliate added/created successfully. Click to Edit Affiliate.` The latter sentence could link to the Edit Affiliate screen so they can make any necessary changes (such as setting them to Active if they are set to Pending automatically)?

**Comment by pippinsplugins** [comment]
I'm all for adding a link in the row actions!

**Comment by sumobi** [comment]
👍

**Comment by tubiz** [comment]
PR: #2652 

* Add Affiliate action link
<img width="355" alt="add affiliate action link" src="https://user-images.githubusercontent.com/602184/39518035-8fb733ae-4df9-11e8-8bc8-1be6ed976311.png">

* Add existing user as a new affiliate
![add user as affiliate](https://user-images.githubusercontent.com/602184/39517928-4a1730ce-4df9-11e8-9464-4612adfbf956.png)

**Comment by pippinsplugins** [comment]
PR looks good, we can merge after 2.2 is released.

**Comment by pippinsplugins** [comment]
@michaelbeil could you please test this when back from WCEU?

**Comment by michaelbeil** [comment]
The add affiliate link works well from the WP user screen. An affiliate is added successfully through this shortcut.
