### ISSUE TITLE
Create a simple registry for registering and retrieving upgrade routines and related atts

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2105]
One thing I noticed in forking EDD's upgrade routine API, e.g. `affwp_set_upgrade_complete()`, `affwp_has_upgrade_completed()`, and `affwp_get_completed_upgrades()` is a need for having a central registry somewhere so we can keep track of what could possibly be running and under what context.

See #2104 for where we could abstract the `Registry` created for the batch processor for this purpose.

**Comment by DrewAPicture** [comment]
Added a PR: #2109

**Comment by pippinsplugins** [comment]
This is super slick. Love it.
