### ISSUE TITLE
Add "Affiliate Area" link to WooCommerce's "My Account" page

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2108]
We receive many requests for an `Affiliate Area` link in WooCommerce's `My Account` menu. This would simply link to the Affiliate Area, it would not open the entire Affiliate Area within the My Account page.

We _could_ build a free add-on for this but it would be more beneficial to include it in core since we have a lot of WooCommerce customers. This is also offered out of the box by another WP-based affiliate plugin and seems to be something customers expect when they enable the WooCommerce integration.

Current hack to achieve this:
https://gist.github.com/sumobi/0ce35362d50cccc0eeea6175703ba79c

@wordmaid suggested that this new checkbox option could appear when the WooCommerce integration is enabled, on the `integrations` settings tab. If we ever decide to modify the front-end of any other integration they could also appear in this tab.

I'm not personally a fan of ever changing the front-end UI of another integration, but considering the customer-base, and how easy/safe this would be to include, it could be a good idea to consider.

**Comment by pippinsplugins** [comment]
Let's do it.

**Comment by DrewAPicture** [comment]
Something like this should do it:
```php
add_filter( 'woocommerce_account_menu_items', function( $items ) {
	if ( function_exists( 'affwp_is_affiliate' ) && affwp_is_affiliate() ) {
		$affiliate_area_page = affwp_get_affiliate_area_page_id();

		if ( $affiliate_area_page ) {

			$slug = get_post_field( 'post_name', $affiliate_area_page );

			if ( $slug ) {
				$affiliate_area = array( $slug => __( 'Affiliate Area', 'affiliate-wp' ) );

				$last_link = array();

				if ( array_key_exists( 'customer-logout', $items ) ) {

					// Grab the last link (probably the logout link).
					$last_link = array_slice( $items, count( $items ) - 1, 1, true );
					
					// Pop the last link off the end.
					array_pop( $items );

				}

				// Inject the Affiliate Area link 2nd to last, reinserting the last link.
				$items = array_merge( $items, $affiliate_area, $last_link );
			}
		}

	}

	return $items;

}, 100 );
```
It drops the Affiliate Area link in before logout if it exists, otherwise it drops it on the end.

**Comment by DrewAPicture** [comment]
Looks like this:

![My Account](https://cl.ly/3b311p28332z/Screen%20Shot%202017-03-16%20at%2011.27.58%20AM.png)

**Comment by DrewAPicture** [comment]
Also worth noting that due to how WooCommerce outputs the links, the actual link will have the my-account prefix on it, but WordPress handles the redirect to the correct slug without the prefix.

**Comment by DrewAPicture** [comment]
PR: #2110

**Comment by sumobi** [comment]
@DrewAPicture Nice, will give it a test. 

We should have an admin checkbox option to enable this link. That way, when people upgrade, we aren't suddenly changing the front-end of their site without their permission.

**Comment by sumobi** [comment]
Let's use the title of the page set to be the Affiliate Area instead of `Affiliate Area`. 

```
$affiliate_area = array( $slug => __( 'Affiliate Area', 'affiliate-wp' ) );
```

**Comment by DrewAPicture** [comment]
This isn't actually closed. I just actually processed the revert.

**Comment by worldtravlr** [comment]
This is cool.  Does this only show for affiliates I assume (and not for normal, non-affiliate customers)?

**Comment by DrewAPicture** [comment]
Yes, it would only show for affiliates. Still some massaging left to get it right.

**Comment by pippinsplugins** [comment]
Re-created pending PR https://github.com/AffiliateWP/AffiliateWP/pull/2193

**Comment by DrewAPicture** [comment]
@sumobi As of d71dcb4cb937fe86100520c75665e8826d2de809 the page title is used. I also made it filterable for the case where they want the page title to be something and navigation link something else (such as a verb).

**Comment by DrewAPicture** [comment]
@sumobi Also just implemented a checkbox setting in WooCommerce > Accounts disabled by default in b0e3bd1148017740eb6db470869657e95ccf81a3

This should be ready for re-testing and merge if everything looks good.

![Setting](https://cl.ly/011u303S2T0E/Screen%20Shot%202017-05-12%20at%2012.19.45%20PM.png)

**Comment by DrewAPicture** [comment]
@AffiliateWP/core This is ready for review/testing. The link will only show if enabled via the new setting in WooCommerce > Accounts.

**Comment by pippinsplugins** [comment]
Works perfectly, merged.

**Comment by sumobi** [comment]
@DrewAPicture Never thought to add it to WooCommerce's settings, excellent!

**Comment by coldfusion411** [comment]
When will this be released?

**Comment by pippinsplugins** [comment]
@coldfusion411 it's being included with AffiliateWP 2.1, which is coming sometime in the next 2-5 weeks.

**Comment by BurlesonBrad** [comment]
First: Hoorah & Happy Memorial Day 🎖  you sexy Github Grunt-ing Vagrants 
![serve-memorial-day](https://cloud.githubusercontent.com/assets/6208757/26555564/3b138efe-445b-11e7-931a-b03998be5b4c.jpg)

Ok, let's look at what @sumobi mentioned:
> Never thought to add it to WooCommerce's settings

Now, while he _**did**_ a wonderfully pleasant salutation by adding the word _**"excellent"**_ to his comment 👍 , he's actually onto something else 🤔 

I'd like to argue **very strongly** that this should **NOT** _under **any** circumstances_ be within WooCommerce's settings. This is not WooCommerce, this is AffiliateWP.  While it *_IS_*, indeed modifying a WooCommerce end-point, this is a setting / toggle / modifier / selection / item / .... / which is 100%  _**"having-to-do-with-AffiliateWP"**_

So, the second it gets rolled out, even if @gspice does a detailed post about it, I can almost guarantee that folks are gonna go looking for it over in AffiliateWP's settings and not WooCommerce's settings area.

Perhaps adding the toggle to ```/wp-admin/admin.php?page=affiliate-wp-settings&tab=integrations``` or even ```/wp-admin/admin.php?page=affiliate-wp-settings&tab=misc``` would be better 💯 

.....and maintain lower 'support costs' by keeping settings within the AffWP controlled area _(not WC's settings page)_

**Comment by pippinsplugins** [comment]
I feel strongly that the WooCommerce settings are the correct place for a option that directly modifies the WooCommerce account page, and _only_ the WooCommerce account page. If, however, it turns out to be problematic, we can consider changing it in the future.

**Comment by jose-nunez** [comment]
I think this method works much better as it actually includes the area inside my account, instead of just link it.
https://github.com/AffiliateWP/AffiliateWP/pull/2110

**Comment by francissiono** [comment]
@BurlesonBrad I totally agree with you. 

While I accidentally found adding this via WooCommerce >> Settings while testing on a staging environment,  I already added this following this guide ... https://wpbeaches.com/change-rename-woocommerce-endpoints-accounts-page/

After several minutes of testing, I was ready to push to live then I realized my custom hook in functions.php was no longer needed since that option "Affiliate Area Link" is already available somewhere.  I spent like 15 to 20 minutes trying to find it in the AffiliateWP settings; went back and forth with my staging and live sites.  I just couldn't find it but was pretty sure it was somewhere in the Affiliate WP settings!  Did a google search and found this thread.  The rest was history :)

Please put it under AffiliateWP!

**Comment by onthemovefit** [comment]
Hi - I'm curious, how did the end up? I'm not seeing an option.  I can add it on my own, but a setting would be great.

Thanks!

**Comment by michaelbeil** [comment]
We have implemented a checkbox setting in WooCommerce > Settings > Accounts disabled by default. 

![Setting](https://cl.ly/011u303S2T0E/Screen%20Shot%202017-05-12%20at%2012.19.45%20PM.png)

You can enable this setting there.

**Comment by onthemovefit** [comment]
Thanks!​ I didn't realize the WooCommerce integration had to be turned on,
thought it would be by default.

Dave

*--*

*Dave Brown*

*NSCA Certified Personal Trainer*

*NASM Corrective Exercise Specialist*

*On The Move Fitness*

Life's more fun when we're in shape!  |  onthemovefitness.com
<http://www.onthemovefitness.com/>

Check out our blog  |  blog.onthemovefitness.com

<http://www.facebook.com/onthemovefitness/>
