### ISSUE TITLE
MemberMouse integration: not able to create referrals

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2116]
He can create visits successfully but not referrals.  MemberMouse is showing the referral and the name of the person correctly.  

HS ticket:
https://secure.helpscout.net/conversation/334093816/55285/?folderId=1170842

This user is really good with testing and reporting details.  He has a video on his original ticket showing the steps that he's done.   He's attached a copy of the latest AffiliateWP debug results in his last response.  

UPDATE:
Customer has created an admin account for us now, deets on the ticket.

**Comment by gspice** [comment]
Can anyone take a look at this ?  He has his buy links down in a Divi model and I've not worked with Divi before :-(   I'm asking him also if he has LeadPages installed as well but I can't tell if the MemberMouse purchase area is on an embedded LeadPage.  I'm asking him.

**Comment by pippinsplugins** [comment]
Looking . . .

**Comment by pippinsplugins** [comment]
@gspice I'm not yet sure why it's failing. Going to take over the ticket and see what I can find.
