### ISSUE TITLE
RCP's Prevent Account Sharing option redirecting affiliates when logging in

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2118]
There appears to be a conflict between AffiliateWP and Restrict Content Pro. 

When RCP's `Prevent Account Sharing` option is enabled from the Settings -> Misc tab, and when an affiliate logs in via the `[affiliate_area]` shortcode, they are redirected to the WP login page. The URL becomes `/wp-login.php?loggedout=true`. This also happens when registering via the `[affiliate_area]` shortcode.

The `[affiliate_login]` standalone shortcode works fine, either on the same page as the `[affiliate_area]` shortcode or on another page with the `redirect` arg. I haven't tested, but I'm going to assume the `[affiliate_registration]` shortcode also works fine.

This issue can be seen on the customer's site here: 
https://secure.helpscout.net/conversation/335046423/55421/?folderId=205531

Switching themes and disabling all other plugins does not help. @mindctrl has replicated the issue locally but so far I am unable to.

@AffiliateWP/core Can anyone else replicate?

**Comment by sumobi** [comment]
Just for fun, here's my custom workaround for the customer:

```
[affiliate_area_notices] // This is from the Affiliate Area Shortcodes add-on

[affiliate_content]

[affiliate_area]

[/affiliate_content]

[non_affiliate_content]

[affiliate_registration]

[affiliate_login]

[/non_affiliate_content]
```

**Comment by mindctrl** [comment]
Not sure where the issue is, but just a quick note to say we can probably improve our session detection in RCP with wp_get_all_sessions().

**Comment by pippinsplugins** [comment]
I've replicated the problem and submitted a PR that resolve sit.
