### ISSUE TITLE
Make it possible to add information to the custom field when manually adding a referral

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2132]
Some integrations (such as MemberPress) rely on the `custom` field to store certain meta information about referrals, however, when manually adding referrals for those integrations, it's not currently possible to set values in the `custom` field.

**Comment by DrewAPicture** [comment]
PR: #2133 

Includes tests and adds direct support for storing `custom` values as an array and retrieving that array as unserialized in addition to the standard string handling.

**Comment by DrewAPicture** [comment]
Adding a single custom value when manually adding a referral needs testing.

**Comment by gspice** [comment]
Note to self:  I need to update the customer here:  
https://secure.helpscout.net/conversation/330223379/54646/?folderId=205529

And update MemberPress notation in docs.

**Comment by pippinsplugins** [comment]
PR looks good.
