### ISSUE TITLE
JS conflict between PayPal buttons integration and EDD FES vendor contact form

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2141]
There's a JS conflict that occurs between EDD FES and AffiliateWP's PayPal Buttons integration.

When the `PayPal buttons` integration is enabled, it inserts some code into the page:
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-paypal.php#L30

When FES's vendor contact form (via the `[fes_vendor_contact_form]` shortcode) is submitted, it results in the JS error below and redirects the site visitor to an unintentional location. On a customer's site it was a page not found, in my testing it's the blog index. It also prevents any field on the vendor form from being required so you can submit it without filling in any information. The JS error is:

```
TypeError: action.indexOf is not a function
```

action.indexOf is defined here: https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-paypal.php#L39

Steps to replicate:

1. Install EDD, EDD FES, AffiliateWP
2. Enable the `PayPal buttons` integration in AffiliateWP
3. Add a vendor to FES
4. On the `Vendor` page added by FES, assign it a page template so a form is shown on the vendor's page. Here's a template I quickly ripped out of another theme: https://gist.github.com/sumobi/2fbd11094976d4cd31d02fbbe192e26c
5.Visit the vendor page, it will be a URL like `site.com/vendor/john`
6. Submit the vendor contact form without entering any information. A JS error will appear in the console and it will perform a redirect.

This _may_ also affect sites with other forms, FES's vendor contact form is the only one I've seen that conflicts so far.

**Comment by pippinsplugins** [comment]
I doubt this is specific to FES

**Comment by DrewAPicture** [comment]
Attaching a PR that changes course to use a regex against the `action` attribute: #2448

**Comment by amdrew** [comment]
@DrewAPicture Getting a different error with the PR:

```
TypeError: action.match is not a function
```

**Comment by DrewAPicture** [comment]
@amdrew Can you please re-test with the latest version of the PR?

**Comment by amdrew** [comment]
@DrewAPicture Getting a new JS error:

`TypeError: $(...).hasAttribute is not a function`

**Comment by DrewAPicture** [comment]
Fiddlesticks! I've tried one last ditch effort.

**Comment by amdrew** [comment]
@DrewAPicture Sorry... back to this error:

`TypeError: action.match is not a function`

**Comment by DrewAPicture** [comment]
Followed up with @amdrew in Slack. Turns out that we hit on a rarely-experienced difference between `prop()` and `attr()`, that the `action` attribute was likely still being set when the form tag was rendered in the DOM, thereby causing `prop()` to just return an empty string, whereas `attr()` would return `undefined` if it isn't actually set to something.
