### ISSUE TITLE
Generate Payout File for single affiliate lead into paying out all affiliates

### ISSUE THREAD

**Issue by flowdee** [AffiliateWP/AffiliateWP#2147]
- Clicked on the button "Generate Payout File"
- Clicked into the "affiliate name" field and searched a specific affiliate
- Affiliate name field was prefilled automatically after selecting the right one
- From date was left empty
- To date was set to the 1st of March 2017 (in order to not to payout referrals from the last 30 days)
- Clicked on "Generate CSV file"
- Received a CSV file including 19 (!) instead of the selected one affiliate (which is a real pitty)

<img width="818" alt="bildschirmfoto_2017-04-03_um_08_20_36" src="https://cloud.githubusercontent.com/assets/2278756/24597560/dcc975a6-1846-11e7-942a-42d50128a91a.png">

### Setup
- Multisite
- AffiliateWP is not enabled for multisite but activated on each blog individually

### Irregularities
Your "affiliate name" box seemed to pick the right affiliate and - as you can see on the screenshot - prefilled the affiliate name field with an email address. Afterwards I checked the connected user and was wondering why not his username was taken for the affiliate name field? Additionally I saw that the email which was taken is not (no more?) listed on his user edit page. Maybe he changed the email/username somehow?

**Comment by pippinsplugins** [comment]
@flowdee please test again with all other plugins deactivated. I just tested this and it worked properly for me.

**Comment by pippinsplugins** [comment]
Closing as invalid for now. We can reopen if there are further reports.

**Comment by flowdee** [comment]
Sorry for the missing feedback Pippin. I tested it again without other plugins and same issue. 

As I saw I changed his username a few months before ( [with this plugin](https://de.wordpress.org/plugins/username-changer/) ). I assume that's the reason why the select field picked the old and invalid username.
