### ISSUE TITLE
Referrals not being created - debug log shows "Pending Referral #0 created successfully"

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2148]
Users report visits being created but not referrals.  The integrations vary.  The debug log entry is:

_2017-3-30 21:04:28 - Pending Referral #0 created successfully_

Tickets experiencing this:
https://secure.helpscout.net/conversation/336313550/55680/?folderId=1170842

https://secure.helpscout.net/conversation/334093816/55285/?folderId=205527

**Comment by gspice** [comment]
Got another ticket on this, also using WP Simple Pay:

https://secure.helpscout.net/conversation/348067403/57208/?folderId=1170842

**Comment by gspice** [comment]
So, we just learned this is related to #2003 - expected it to create a referral for the first charge but it does not.   Still sorting this out....

**Comment by pippinsplugins** [comment]
I believe this has been fixed through the changes for #2160

**Comment by pippinsplugins** [comment]
This has been confirmed as fixed through #2160.
