### ISSUE TITLE
Filtering by date range/affiliate in Referrals screen shows the "All" referral count

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#2149]
Currently when filtering the Referrals screen by affiliate and by date range, the item count (number of referrals) does not update - instead it shows the total number as per the _all_ referrals count.

Would it be possible to only show the number of referrals listed based on the selected search parameters?

**Comment by DrewAPicture** [comment]
Added a PR that should fix the counts for _all_ non-status queries for all 5 core objects: #2171

**Comment by DrewAPicture** [comment]
Moved to the 2.1 milestone.

**Comment by pippinsplugins** [comment]
PR works great, merged.
