### ISSUE TITLE
User filter on export/import tab is searching non-affiliates

### ISSUE THREAD

**Issue by DavidAnderson684** [AffiliateWP/AffiliateWP#2150]
Steps to reproduce:

- Go to Tools, and to the Export/Import tab

- In the 'Export Payouts' or 'Export Referrals' sections, begin a search on a user. A list of possible users will appear.

Expected result: Only affiliates are shown on the list of options.
Actual result: All users, whether affiliates or not, can appear on the list.

Version tested on: 2.0.5 (WooCommerce integration, WC 2.6.14, WP 4.7.3)

**Comment by DrewAPicture** [comment]
Confirmed. Looks like the status data attribute was accidentally left off the inputs for those forms. Also found a couple of others in core. Nice catch!

**Comment by DrewAPicture** [comment]
PR: #2157

**Comment by pippinsplugins** [comment]
Works great, merged.
