### ISSUE TITLE
"Required Registration Fields" checkboxes not sticking

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2151]
On some sites (I've seen the issue 3 or more times now) the checkboxes from the `Required Registration Fields` section (under Settings -> General) are not saving correctly, and fallback to what the previous setting is.

Here's an example of the issue:

1. Customer unticks the `Website URL` checkbox and saves the settings
2. Once saved, it appears the option has indeed been disabled.
3. Refresh the settings page again and the `Website URL` checkbox is enabled again.

I replicated this issue locally on 1 site but not the other. Upon looking at the database, the site that had the issue did not have the `affwp_completed_upgrades` option row. After adding that to the database and then deactivating/activating AffiliateWP (this is crucial), the issue went away.

If you can't replicate the issue, simply delete the `affwp_completed_upgrades` option row.

As a workaround on 2 customer sites I've simply added a new option row with a `name` of `affwp_completed_upgrades` and added an `option_value` of `a:1:{i:0;s:35:"upgrade_v20_recount_unpaid_earnings";}` which is what my local site had (not sure if this matters too much).

**Comment by sumobi** [comment]
Another report https://secure.helpscout.net/conversation/347894698/57187/?folderId=205529

**Comment by pippinsplugins** [comment]
Replicated.

**Comment by DrewAPicture** [comment]
I'll take a look.

**Comment by DrewAPicture** [comment]
This should be fixed as of 09e851b18684c5550b9e6c7d405a1eb0dd6c5453. Please test!

**Comment by DrewAPicture** [comment]
The way I tested:
1. Delete the option.
```sh
wp option delete affwp_completed_upgrades
```
2. Navigate to Affiliates > Settings
3. Change the required registration settings
4. Click Save Changes
5. Note the settings change on page refresh
6. Manually refresh the page
7. Note the settings have "stuck"

**Comment by pippinsplugins** [comment]
Fix confirmed though I have a concern with the conditional on the upgrade routine. Discussing via Slack.

**Comment by DrewAPicture** [comment]
PR more directly addressing the conditionals: #2166
