### ISSUE TITLE
Can't bulk delete affiliates

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2152]
Tested on 2 computers with latest master branch. Bulk deleting affiliates doesn't work. The page just reloads.

@AffiliateWP/core Can anyone else replicate?

**Comment by sumobi** [comment]
Works fine for @wordmaid so must be something wrong on my end, will take another look.

**Comment by wordmaid** [comment]
I just tried to do this with a few affiliate accounts on the live EDD site and it didn't work. The affiliates were in Pending status, not sure if that has anything to do with it...

**Comment by DrewAPicture** [comment]
Added a PR: #2156

Please test!

**Comment by pippinsplugins** [comment]
Works great, merged!

**Comment by sumobi** [comment]
That's super weird. @wordmaid could definitely bulk delete on her laptop. Oh well 💯
