### ISSUE TITLE
Icons in Referral URL Visits table

### ISSUE THREAD

**Issue by AiratHalitov** [AffiliateWP/AffiliateWP#2153]
I can't see` \f147` and `\f158` icons from _assets/css/forms.min.css?ver=2.0.5_ file in **Affiliate Area > Visits > Referral URL Visits** Table. 
**CONVERTED** column

Screenshot: 
visits.png
https://yadi.sk/i/IM3MCB6h3GhZUX

**Comment by pippinsplugins** [comment]
See https://github.com/AffiliateWP/AffiliateWP/issues/1947
