### ISSUE TITLE
Missing option rows from uninstall.php

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2159]
It doesn't look like the `uninstall.php` file (https://github.com/AffiliateWP/AffiliateWP/blob/master/uninstall.php) removes the following option rows on plugin deletion (ignore `wp_XX_affiliate_wp_direct_links_db_version`):

![screen shot 2017-04-12 at 9 23 57 pm](https://cloud.githubusercontent.com/assets/52581/24950829/6fb2751c-1fc6-11e7-8711-c57f63854632.png)

**Comment by DrewAPicture** [comment]
I'd intended to circle back around to this after the last round of uninstall.php adjustments and never got to it. Thanks for the reminder.

**Comment by DrewAPicture** [comment]
PR: #2170

**Comment by pippinsplugins** [comment]
@DrewAPicture PR looks good though we still need to add delete calls for the options that are currently left behind.

**Comment by DrewAPicture** [comment]
@pippinsplugins Should be covered in ffaebc2074ee17d602fb8bc6d0c6768e21f0287b.

**Comment by pippinsplugins** [comment]
PR looks now!
