### ISSUE TITLE
Remove $this->debug checks for integration logging

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2165]
In #2160, we're fixing an accidental back-compat break where `$this->debug` wasn't getting set and messages weren't getting logged following the move toward a global logging utility introduced in 2.0.2.

Now that the `log()` method in `class-base.php` directly wraps the global `affiliate_wp()->utils->log()` method, checking the value of `$this->debug` is moot due to the global method doing its own check already.

**Comment by DrewAPicture** [comment]
@pippinsplugins Preference on sticking with using the "local" `$this->log()` within integrations or should we go directly to using `affiliate_wp()->utils->log()` like everywhere else in core?

**Comment by DrewAPicture** [comment]
Either way, we'll still keep both `$this->debug` and `$this->log()` for back-compat, obviously.

**Comment by pippinsplugins** [comment]
I prefer `$this->log()` for brevity.

**Comment by DrewAPicture** [comment]
Roger.

PR: #2167

**Comment by pippinsplugins** [comment]
Merged!
