### ISSUE TITLE
Remove HTML markup from emails when no heading is set

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2168]
Our emails currently have extra space at the top of each email. This is because the email template includes HTML markup for a heading. None of our default emails however set a heading.

We should only include the relevant HTML when a heading has been set.

___

Default emails with no heading causing extra markup and large white space

![screen shot 2017-04-15 at 2 14 44 pm](https://cloud.githubusercontent.com/assets/52581/25060011/2ce11546-21e6-11e7-94ec-0009cf293ddb.png)

___

Fixed:

![screen shot 2017-04-15 at 2 15 05 pm](https://cloud.githubusercontent.com/assets/52581/25060012/3698da88-21e6-11e7-869b-ac81a257b273.png)

___

Email with heading example:

![screen shot 2017-04-15 at 2 16 29 pm](https://cloud.githubusercontent.com/assets/52581/25060014/3f51d51c-21e6-11e7-9336-2b5871323bd7.png)

**Comment by sumobi** [comment]
@AffiliateWP/core Ready for review: https://github.com/AffiliateWP/AffiliateWP/issues/2169

**Comment by pippinsplugins** [comment]
Merged.
