### ISSUE TITLE
Creatives - Admin area: allow formatting in the Description fields

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2173]
PR: #2644

Customer requested , wanting to add line breaks to her description:

https://secure.helpscout.net/conversation/352112756/57664/?folderId=205529

Could allow HTML or add actual editor like in a page/post.

**Comment by pippinsplugins** [comment]
I don't see any reason to not support formatting here. :+1:

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/571142286/81309/?folderId=205529

**Comment by DrewAPicture** [comment]
PR: #2644 replaces the Creative Description field with a WYSIWYG editor:

![Description editor](https://cl.ly/3F2k2u2w1l3M/Screen%20Shot%202018-04-30%20at%203.10.25%20PM.png)

**Comment by DrewAPicture** [comment]
Closed #2643 since that issue is also fixed in the attached PR. 

Support thread to notify: https://secure.helpscout.net/conversation/571142286/81309?folderId=205524.

**Comment by pippinsplugins** [comment]
PR looks good. We can merge it after 2.2 is released.

**Comment by michaelbeil** [comment]
This works wonderfully.

I love that there is a WYSIWYG editor: 
![rzsvgu](https://user-images.githubusercontent.com/4752949/39999655-f073099a-5789-11e8-98ca-2506b3356be1.png)

The description is now displayed above the creative in the affiliate area:
![wqfhb3](https://user-images.githubusercontent.com/4752949/39999667-f52cc098-5789-11e8-8c79-8d38ed53c408.png)
