### ISSUE TITLE
'Custom' field not saving to Database since 2.0.6

### ISSUE THREAD

**Issue by clickstudio** [AffiliateWP/AffiliateWP#2178]
Since 2.0.6 no data is being saved to the referral table in the custom column.

I'm using filter 'affwp_insert_pending_referral' to add an array of data. I just reverted back to 2.0.5 and it's working perfectly with that version.

I'll try and find the bug but wanted to put this out there ASAP as it completely breaks my 'Multi Level Affiliates' add-on.

**Comment by DrewAPicture** [comment]
#2132 added official support for defining a `custom` value in `affwp_add_referral()` for 2.0.6. See 9738f021ad811a5579b30da859ee3c8339fe3fb5.

The data going in gets serialized prior to saving and unserialized on the way back out, but that's the only change to the `referrals->add()` method, which is what gets called directly following all core uses of the `affwp_insert_pending_referral` hook.

Can you please show and example of data you're attempting to pass that isn't getting saved?

**Comment by clickstudio** [comment]
I can see maybe_serialize( $args['custom'] ) in referrals->add() which seems to be the only difference in the entire process but I commented this out and tested and it made no difference.

My function called by the 'affwp_insert_pending_referral' filter is already serializing the 'custom' array prior to returning the args.

The 'custom' serialized array I am passing back is as follows:

a:1:{s:3:"mla";a:5:{s:18:"matrix_order_total";s:6:"8.1818";s:8:"products";a:1:{i:0;a:4:{s:4:"name";s:54:"Advantix Blue for Dogs (over 25kg) (Variation ID 3880)";s:2:"id";s:4:"3877";s:5:"price";d:7.36360000000000081143980423803441226482391357421875;s:15:"referral_amount";s:4:"0.22";}}s:17:"matrix_level_vars";a:3:{s:4:"type";s:10:"percentage";s:12:"total_levels";i:5;s:11:"level_rates";a:5:{i:1;s:2:"20";i:2;s:2:"10";i:3;s:1:"8";i:4;s:2:".5";i:5;s:2:"20";}}s:23:"matrix_level_affiliates";a:3:{i:1;i:126;i:2;s:3:"107";i:3;s:1:"1";}s:9:"referrals";a:3:{i:1;a:2:{s:12:"affiliate_id";i:126;s:14:"referral_total";d:1.636360000000000258779664363828487694263458251953125;}i:2;a:3:{s:12:"affiliate_id";s:3:"107";s:14:"referral_total";d:0.8181800000000001293898321819142438471317291259765625;s:11:"referral_id";i:472;}i:3;a:3:{s:12:"affiliate_id";s:1:"1";s:14:"referral_total";d:0.65454400000000012571632623803452588617801666259765625;s:11:"referral_id";i:473;}}


[http://www.awesomescreenshot.com/image/2415936/1572a1f89c902d2c7ab4037b5af1bfb3](url)

**Comment by DrewAPicture** [comment]
Thank you,

So can you confirm that the `custom` value is in fact empty, or is it just that it's not coming back out in the format you're expecting, e.g. triple serialized and only unserialized twice?

**Comment by clickstudio** [comment]
Yes the custom value is empty the database. 
My function unserializes the custom value on the way back out.

At some point between passing the serialized array back to the filter and the data being saved to the database, it is being removed it seems.

**Comment by clickstudio** [comment]
I also tested passing back just a basic array with 1 key and value. It was also removed.
I ran my tests with no other add-ons active.

**Comment by DrewAPicture** [comment]
Looks like we skipped handling for serialization in `update_referral()` though I'm not sure that would be the culprit.

Would it be possible for you to send a copy of the add-on to drew@affiliatewp.com so I can take a closer look?

**Comment by clickstudio** [comment]
To test, I stored the data in the options table at the following two places:
[http://www.awesomescreenshot.com/image/2416039/3a5abb915fa3a32de97b3059eddacbe7](http://www.awesomescreenshot.com/image/2416039/3a5abb915fa3a32de97b3059eddacbe7)

I just tested passing back an unserialized array,

The first one captured this (seems fine):
[http://www.awesomescreenshot.com/image/2416089/7a2949cd4780ccecbd1d2c0ebe75dadb](http://www.awesomescreenshot.com/image/2416089/7a2949cd4780ccecbd1d2c0ebe75dadb)

The second one captured this (also seems fine and both the products and custom values are serialized as expected.):

[http://www.awesomescreenshot.com/image/2416096/4c32e7b0951ddbe370968ac92e60319c](http://www.awesomescreenshot.com/image/2416096/4c32e7b0951ddbe370968ac92e60319c)

The referral table:
[http://www.awesomescreenshot.com/image/2416099/2853fb138de9dc606e31c47a0c2fc088](http://www.awesomescreenshot.com/image/2416099/2853fb138de9dc606e31c47a0c2fc088)

I'll email you a copy now.

**Comment by DrewAPicture** [comment]
@clickstudio:

@pippinsplugins mentioned that It's possible Gmail will block the email if the attachment includes JS files, so if you could resend the email with an externally hosted copy that would be super helpful. Thanks :)

**Comment by clickstudio** [comment]
@DrewAPicture Yeah it get get returned and flagged as spam.

You should receive a sharing notification from G Drive!

Thanks

**Comment by DrewAPicture** [comment]
Yep, I got it. Thanks for re-sending that.

**Comment by DrewAPicture** [comment]
@clickstudio OK, we've had a chance to take a look and we think the best course of action here is to ask you to move toward using the WP core equivalents of `serialize()` and `unserialize()`, that is `maybe_serialize()` and `maybe_unserialize()` when working with the `custom` referral field, and really any other field you expect to be serialized going it or coming out.

We previously left the `custom` field open to interpretation, and applaud your initiative in handling data serialization operations prior to 2.0.6, however now that serialization has become standard around the `custom` field in core, we'd ask that you follow best practice in working with this data: Any data contained in the `custom` field going in will _always_ be serialized, and coming out via `affwp_get_referral()` will _always_ be unserialized.

Moving to using `maybe_unserialize()` instead of `unserialize()` in two places in class-referral.php should clear the two notices thrown there.

Separately, it's worth noting that you should check that the `custom` key is set (or not empty) in your `affwp_insert_pending_referral` callback because it's not always set via the args array passed to the hook in the various integrations.

If you have any questions, let us know. Thanks for the report :-)

**Comment by clickstudio** [comment]
Thanks @DrewAPicture . I made those suggested changes and it fixed the issue.
Thanks so much for the time spent on this. It's much appreciated!!

**Comment by clickstudio** [comment]
@DrewAPicture I have recently been alerted to the a bug in my MLA add-on which I have tracked down to the custom column not saving through the following method;

affiliate_wp()->referrals->update( $this->referral_id, $data, '', 'referral' );

$data being a serialized array with as previously.

I have checked the AffiliateWP code and I can't see anything obvious that may be causing this. Would you have any suggestions here ?

**Comment by clickstudio** [comment]
@pippinsplugins This is an example of the custom data when the MLA add-on is used in conjunction with my other add-ons (Groups).

a:1:{s:3:"mla";a:10:{s:18:"matrix_order_total";d:9.089999999999999857891452847979962825775146484375;s:8:"products";a:1:{i:0;a:4:{s:4:"name";s:74:"Advantix Blue for Dogs (over 25kg) (Variation ID 3880) (Variation ID 3880)";s:2:"id";i:3877;s:5:"price";d:8.17999999999999971578290569595992565155029296875;s:15:"referral_amount";s:4:"8.18";}}s:17:"matrix_level_vars";a:3:{s:4:"type";s:4:"flat";s:12:"total_levels";i:3;s:11:"level_rates";a:3:{i:1;s:3:"100";i:2;s:2:"99";i:3;s:2:"98";}}s:23:"matrix_level_affiliates";a:3:{i:1;i:196;i:2;s:3:"197";i:3;s:3:"198";}s:9:"referrals";a:4:{i:1;a:2:{s:12:"affiliate_id";i:196;s:14:"referral_total";d:9.089999999999999857891452847979962825775146484375;}i:2;a:3:{s:12:"affiliate_id";s:3:"197";s:14:"referral_total";d:1.72710000000000007958078640513122081756591796875;s:11:"referral_id";i:891;}i:3;a:3:{s:12:"affiliate_id";s:3:"198";s:14:"referral_total";s:2:"98";s:11:"referral_id";i:892;}i:4;a:3:{s:12:"affiliate_id";s:1:"1";s:14:"referral_total";d:2.454299999999999926103555480949580669403076171875;s:11:"referral_id";i:893;}}s:24:"default_referrals_backup";a:3:{i:1;a:2:{s:12:"affiliate_id";i:196;s:14:"referral_total";d:9.089999999999999857891452847979962825775146484375;}i:2;a:2:{s:12:"affiliate_id";s:3:"197";s:14:"referral_total";s:2:"99";}i:3;a:2:{s:12:"affiliate_id";s:3:"198";s:14:"referral_total";s:2:"98";}}s:17:"groups_level_vars";a:3:{i:1;a:4:{s:12:"affiliate_id";i:196;s:8:"group_id";s:20:"affiliate_group_id_1";s:9:"rate_type";s:10:"percentage";s:10:"rate_value";s:2:"10";}i:2;a:4:{s:12:"affiliate_id";s:3:"197";s:8:"group_id";s:20:"affiliate_group_id_2";s:9:"rate_type";s:10:"percentage";s:10:"rate_value";s:2:"19";}i:4;a:4:{s:12:"affiliate_id";s:1:"1";s:8:"group_id";s:20:"affiliate_group_id_6";s:9:"rate_type";s:10:"percentage";s:10:"rate_value";s:2:"27";}}s:16:"team_leader_vars";a:2:{s:4:"type";s:20:"percentage_remainder";s:4:"rate";s:2:"70";}s:17:"steam_leader_vars";a:2:{s:4:"type";s:20:"percentage_remainder";s:4:"rate";s:3:"100";}s:15:"referrals_total";d:111.271399999999999863575794734060764312744140625;}}

**Comment by clickstudio** [comment]
@pippinsplugins I have done some back testing and the issue started with release of AffiliateWP 2.1.8.

**Comment by clickstudio** [comment]
@pippinsplugins 
Below is what's passed into the update method ($data['custom']). 
This worked/works perfectly in AffiliateWP version 2.1.7 but fails in 2.1.8 forward.

$custom_data = maybe_serialize($custom_data);
$data = array( 'custom' => $custom_data);
affiliate_wp()->referrals->update( $this->referral_id, $data, '', 'referral' );

-----------------

a:1:{s:3:"mla";a:10:{s:18:"matrix_order_total";d:9.089999999999999857891452847979962825775146484375;s:8:"products";a:1:{i:0;a:4:{s:4:"name";s:74:"Advantix Blue for Dogs (over 25kg) (Variation ID 3880) (Variation ID 3880)";s:2:"id";i:3877;s:5:"price";d:9.089999999999999857891452847979962825775146484375;s:15:"referral_amount";s:5:"0.909";}}s:17:"matrix_level_vars";a:3:{s:4:"type";s:4:"flat";s:12:"total_levels";i:3;s:11:"level_rates";a:3:{i:1;s:1:"0";i:2;s:1:"2";i:3;s:1:"3";}}s:23:"matrix_level_affiliates";a:3:{i:1;i:197;i:2;s:3:"198";i:3;s:1:"1";}s:9:"referrals";a:5:{i:2;a:3:{s:12:"affiliate_id";s:3:"198";s:14:"referral_total";s:1:"2";s:11:"referral_id";i:927;}i:3;a:3:{s:12:"affiliate_id";s:1:"1";s:14:"referral_total";s:1:"3";s:11:"referral_id";i:928;}i:1;a:2:{s:14:"referral_total";d:0.9090000000000000301980662698042578995227813720703125;s:12:"affiliate_id";i:197;}s:11:"team_leader";a:5:{s:12:"affiliate_id";s:1:"1";s:14:"referral_total";d:0.45399999999999973709918776876293122768402099609375;s:16:"special_referral";s:11:"team_leader";s:9:"reference";s:11:"Team Leader";s:11:"referral_id";i:929;}s:12:"steam_leader";a:5:{s:12:"affiliate_id";s:1:"1";s:14:"referral_total";d:2.727000000000000312638803734444081783294677734375;s:16:"special_referral";s:12:"steam_leader";s:9:"reference";s:17:"Super Team Leader";s:11:"referral_id";i:930;}}s:24:"default_referrals_backup";a:3:{i:2;a:2:{s:12:"affiliate_id";s:3:"198";s:14:"referral_total";s:1:"2";}i:3;a:2:{s:12:"affiliate_id";s:1:"1";s:14:"referral_total";s:1:"3";}i:1;a:1:{s:14:"referral_total";d:0.9090000000000000301980662698042578995227813720703125;}}s:17:"groups_level_vars";a:1:{i:1;a:4:{s:12:"affiliate_id";i:197;s:8:"group_id";s:20:"affiliate_group_id_2";s:9:"rate_type";s:10:"percentage";s:10:"rate_value";s:2:"20";}}s:16:"team_leader_vars";a:2:{s:4:"type";s:20:"percentage_remainder";s:4:"rate";s:2:"70";}s:17:"steam_leader_vars";a:2:{s:4:"type";s:20:"percentage_remainder";s:4:"rate";s:3:"100";}s:15:"referrals_total";d:9.089999999999999857891452847979962825775146484375;}}
)

**Comment by clickstudio** [comment]
@pippinsplugins Interestingly, I just tested AffiliateWP 2.1.16 (just released) and the issue now seems resolved.
