### ISSUE TITLE
WooCommerce 3.0.x compatibility - notices shown

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2182]
There are 3 notices outputted by WooCommerce 3.0.x. As far as I can see, everything works as expected, however not for the customer:

> Please fix this ASAP, it's causing the payment failure.

Ticket: https://secure.helpscout.net/conversation/353649268/57875/?folderId=205524

These first 2 were shown when I used a tracked affiliate coupon at checkout:

<blockquote>
id was called incorrectly. Coupon properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, do_action('woocommerce_checkout_order_processed'), WP_Hook->do_action, WP_Hook->apply_filters, Affiliate_WP_WooCommerce->add_pending_referral, Affiliate_WP_WooCommerce->get_coupon_affiliate_id, WC_Legacy_Coupon->__get, wc_doing_it_wrong. This message was added in version 3.0.
</blockquote>

<blockquote>
billing_email was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, do_action('woocommerce_checkout_order_processed'), WP_Hook->do_action, WP_Hook->apply_filters, Affiliate_WP_WooCommerce->add_pending_referral, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.
</blockquote>

The 3rd is shown when completing the order (used Direct Bank Transfer):

<blockquote>
post_status was called incorrectly. Order properties should not be accessed directly. Backtrace: do_action('wp_ajax_woocommerce_mark_order_status'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::mark_order_status, WC_Order->update_status, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_completed'), WP_Hook->do_action, WP_Hook->apply_filters, Affiliate_WP_WooCommerce->mark_referral_complete, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.
</blockquote>

**Comment by pippinsplugins** [comment]
Looks like we need to update our integration to use the new getters instead of accessing properties directly.

**Comment by DrewAPicture** [comment]
Started a PR: #2185 

I've pored through the release notes and new abstraction layers in WC 3.0 and can't find anything concrete on custom meta handling, which we're definitely going to need if/when they completely drop support for post meta. They've got a pretty tight hold on the ability to set custom data going into the data store.

**Comment by spencerfinnell** [comment]
https://woocommerce.wordpress.com/2017/02/06/wc-2-7-extension-compatibility-examples-3-bookings/ is a good example.

You need to provide your own data store (it will inherit 99% of the current functionality) for products and orders to define your custom meta keys and provide your getter/setters.

Then places like https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-woocommerce.php#L110

You would do

`$product->get_affwp_woocommece_referrals_disabled()` which would reference the `_affwp_woocommerce_referrals_disabled` meta key.

**Comment by spencerfinnell** [comment]
Though I would not do that on this release and just avoid the direct property access like you have. The direct meta calls won't likely ever fail (since they are custom they won't get moved out of the table during an upgrade routine) so you have some room there while things cool down in the 3.0.x branch.

**Comment by DrewAPicture** [comment]
I suppose we could leverage `Data_Storage` and just use it semi-permanently instead of how we use it for temporary storage for batch processing. We'd probably want to add a layer for use by integrations so we could easily pull values for a given integration, .e.g `woocommerce`.

**Comment by DrewAPicture** [comment]
Or maybe just follow a prefixing scheme for keys.

**Comment by pippinsplugins** [comment]
Do the helper methods used in the PR exist prior to WOo 3.0?

**Comment by DrewAPicture** [comment]
I'll have to check, but that's a good point!

**Comment by pippinsplugins** [comment]
PR merged. Doing one last set of tests before closing.

**Comment by pippinsplugins** [comment]
All is well!
