### ISSUE TITLE
WooCommerce integration doesn't call `insert_pending_referral()` method 

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2201]
The WooCommerce integration doesn't call the `insert_pending_referral()` method to insert a pending referral. 

Instead of using `insert_pending_referral()` (like EDD etc):
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-base.php#L85

It uses `affiliate_wp()->referrals->add()`:
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-woocommerce.php#L182

It would be great if we could use the `insert_pending_referral()` method to generate the referral, for consistency with other integrations and so developers can take advantage of the `affwp_integration_create_referral` filter.

**Comment by pippinsplugins** [comment]
I vaguely recall there being a reason for this but it's avoiding me right now.

**Comment by sumobi** [comment]
Yeah I think you're right, has escaped my mind also.

**Comment by pippinsplugins** [comment]
@gspice @michaelbeil could both of you please test this?

**Comment by gspice** [comment]
Did a WC test purchase with these changes.  Assuming all is well since I see  `Pending Referral #228 created successfully.` in the debug log:

```
2018-5-08 20:42:14 - Visit #213 recorded for affiliate #3 in track_visit()
2018-5-08 21:08:39 - Pending Referral #228 created successfully.
2018-5-08 21:08:39 - Referral #228 created successfully.
2018-5-08 21:08:40 - Referral retrieved successfully during complete_referral()
2018-5-08 21:08:40 - Referral #228 set to Unpaid successfully
```

**Comment by pippinsplugins** [comment]
@gspice all amounts are correct?

Please also test with with an affiliate coupon present.

**Comment by gspice** [comment]
Referral amounts are correct on a standard purchase, using a coupon discount but had cookie in browser from an affiliate link.

When I _removed_ the cookie and used a coupon assigned to an affiliate, no referral was created. I tried two different coupon codes assigned to different affiliates.  Debug log has this:

```
2018-5-08 21:53:26 - Pending referral could not be created due to an error.
2018-5-08 21:53:26 - Referral failed to be created.
```

**Comment by tubiz** [comment]
@gspice the PR has been updated to fix the issue with referrals not created when an affiliate coupon is used.

**Comment by michaelbeil** [comment]
Referrals are generated from both an affiliate link and an affiliate coupon correctly.

**Comment by gspice** [comment]
@tubiz Verified the fix! 

* Tested with affiliate coupon without link tracking/cookie
* Also tested with link tracking.  

Meaning, I used an affiliate's link, but then used a coupon assigned to a _different_ affiliate, and the coupon'd affiliate received the referral, which is correct. 👍

**Comment by amdrew** [comment]
👍Will test tomorrow

**Comment by amdrew** [comment]
Tested with:

- Normal product referrals (using global rate)
- Disabling referrals per-product
- Per-product referral rates
- Per-category referral rates
- The `affwp_integration_create_referral` filter
- Affiliate coupons

All working well for me.
