### ISSUE TITLE
Provide base class for add-ons to provide environment data

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#2204]
This would provide a small class in core, or methods to reference, which concisely provide data to add-ons and allow for minimal scaffolding when setting things like add-on constants, getting active integrations etc, instead of each add-on needing to add it explicitly.

This could be useful in a few ways:

- Ensures each add-on is always using the most up-to-date getters for core data.
- Provides predictability when jumping into add-ons in which someone might not have previously contributed. 
- One feature may be to visibly note to the user, within the AffWP settings screen (likely within the add-ons AffWP settings tab) which integration(s) it currently supports.
   - Alternatively, this feature could only show something if one or more integrations are active which the add-on does _not_ support, eg:
   > AffiliateWP Recurring Referrals presently does not support `integration`. [Click here to tell us you want it added!](https://affiliatewp.com/support/)

**Comment by pippinsplugins** [comment]
`Affiliate_WP_Add_On` base class gets my vote! It could make it easier to set up:

- Versions
- Add-on updater
- Required core version checks
- Settings scaffold
