### ISSUE TITLE
"Referral not created because affiliate's own account was used." error incorrectly logged when purchasing with a logged in user that has an affiliate account

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#2206]
While testing a fix for a completely unrelated bug, I noticed referral records were not being created even though they should be. Looking at the debug log showed me this:
>>>Referral not created because affiliate's own account was used.

_But I didn't use my own affiliate ID...._

Oh! I'm logged in an have an affiliate account. Sure enough, when backtracking through all the methods and functions called in the `is_affiliate_email()` method of the base integration class, we get all the way back to `affwp_get_affiliate_id()`, which retrieves the ID from the currently logged in user's account:

```
/**
 * Retrieves the affiliate ID of the specified user
 *
 * If no user ID is given, it will check the currently logged in user
 *
 * @since 1.0
 * @since 2.0.3 The current user is no longer taken into consideration in the admin
 *              or if doing Ajax when `$user_id` is empty.
 *
 * @param int $user_id Optional. User ID. Default is the ID of the current user.
 * @return int|false Affiliate ID, or false if the current user isn't logged-in or `$user_id` is empty.
 */
function affwp_get_affiliate_id( $user_id = 0 ) {

	if ( empty( $user_id ) ) {
		$is_admin_doing_ajax = is_admin() || ( defined( 'DOING_AJAX' ) && DOING_AJAX );

		if ( ! $is_admin_doing_ajax && ! is_user_logged_in() ) {
			return false;
		} elseif ( ! $is_admin_doing_ajax && is_user_logged_in() ) {
			$user_id = get_current_user_id();
		}
	}

	$cache_key    = md5( 'affwp_get_affiliate_id' . $user_id );
	$affiliate_id = wp_cache_get( $cache_key, 'affiliates' );

	if( false === $affiliate_id ) {

		$affiliate_id = affiliate_wp()->affiliates->get_column_by( 'affiliate_id', 'user_id', $user_id );

	}

	return $affiliate_id;
}
```

This is very likely one of the causes of support tickets from site owners that claim referral tracking isn't working. It _is_ working, just not when logged into an account that is an affiliate but using a different affiliate ID for the purchase.

To resolve this, we need to not permit `is_affiliate_email()` to fall back to the currently logged in user.

**Comment by pippinsplugins** [comment]
PR submitted. I've tested it and confirmed it solves the problem.

**Comment by DrewAPicture** [comment]
Looks good.
