### ISSUE TITLE
Can't search for "exact" URL in visits search box

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2210]
While on the _Affiliates -> Visits_ page you can search for visits that contain a specific `Referring URL` by entering the domain in the search box.

As an example, I can search for `http://issues.affwp.dev/direct-link-tracking-test/` and it will show me `126` results which is correct:

<img width="1329" alt="screen shot 2017-05-09 at 5 13 32 pm" src="https://cloud.githubusercontent.com/assets/52581/25836435/e49c1972-34da-11e7-9288-df24533945e1.png">

And when I search for `http://issues.affwp.dev/` there are `145` results:

<img width="1327" alt="screen shot 2017-05-09 at 5 14 50 pm" src="https://cloud.githubusercontent.com/assets/52581/25836455/09316e54-34db-11e7-94ba-35d872b0b5d2.png">

In the database there are actually only `17` visits that have a referring URL of exactly `http://issues.affwp.dev/`.

It would be handy to be able to sort visits by an exact URL. When `http://issues.affwp.dev/` is searched for, I'd like to only show those 17 visits.

**Comment by sumobi** [comment]
See https://github.com/AffiliateWP/affiliatewp-direct-link-tracking/issues/79 for a use-case.

**Comment by DrewAPicture** [comment]
Seems like you're more looking for search by a specific domain than a URL
in this use case. The results are technically correct in that the domain is
contained in those URLs.

If you're looking for something like an option for exact match that could
also cover the domain case, we can probably do it with a keyword prefix in
the search string (like how some other object fields are directly
searchable, e.g. affiliate: ## in the referrals list search box).

**Comment by sumobi** [comment]
@DrewAPicture A keyword would be great for the search box. This would need to work in the browser address bar, so Direct Link Tracking can filter the visits (see link above if you haven't already).

As an example, DLT's link to the visits page looks like:

`http://direct-link-tracking.affwp.dev/wp-admin/admin.php?page=affiliate-wp-visits&s=issues.affwp.dev&context=direct-link`

Perhaps something like

`http://direct-link-tracking.affwp.dev/wp-admin/admin.php?page=affiliate-wp-visits&s=issues.affwp.dev&context=direct-link&url=exact`

**Comment by tubiz** [comment]
@amdrew I am working on this, I will need access to the Direct Link Tracking plugin.

**Comment by amdrew** [comment]
@tubiz There you go!

**Comment by tubiz** [comment]
PR: #2645 

To search for exact URL the `url:` keyword prefix can be used.

E.g. `url: http://issues.affwp.dev/direct-link-tracking-test/` 

I have tested it with the Direct Link Tracking plugin and it works.

**Comment by pippinsplugins** [comment]
@gspice @michaelbeil ready for testing.

**Comment by michaelbeil** [comment]
When you search for an exact URL within the visits page, only the number of visits that specific URL are displayed. No matter what URL I use, the exact number of visits are shown.

This is working good for me!

**Comment by gspice** [comment]
Its working for me as well.  Af first I wasn't sure, then I realized previously `url:` did not work in the search on the **Visits** page and now it does with the change. 👍
