### ISSUE TITLE
Ensure back-compat for get_data() filters in exporters that leverage batch processing

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2211]
A customer has pointed out that it's currently impossible to implement custom columns in the affiliates exporter because the `affwp_export_get_data_affiliates` filter is no longer attached to the `get_data()` call in exporters that leverage batch processing – which is all of our exporters now.

Probably should make sure the exporters have filterable data methods.

https://secure.helpscout.net/conversation/360303796/58694/

**Comment by DrewAPicture** [comment]
@michaelbeil PR: #2212

**Comment by pippinsplugins** [comment]
Merged.
