### ISSUE TITLE
auto-registration requests

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2215]
https://secure.helpscout.net/conversation/364443442/59147/?folderId=1170842

User requests the ability for customer to be registered as affiliate automatically when buying a particular product.

**Comment by pippinsplugins** [comment]
Affiliate accounts require they also have a user account.

We already have an option to auto register new users as affiliates, so I think that'd suffice. They just need to set up their eCommerce / membership system to auto create user accounts.
