### ISSUE TITLE
MemberPress paid trial period is not added to referral calculation

### ISSUE THREAD

**Issue by lisag** [AffiliateWP/AffiliateWP#2224]
I had a quick look at this ticket (https://secure.helpscout.net/conversation/363906885/59112/?folderId=205527) regarding MemberPress, and it sounds like there might be an issue with the trial period cost + membership price not generating a "correct" referral amount.

Similar to https://github.com/AffiliateWP/AffiliateWP/issues/1342 and https://github.com/AffiliateWP/AffiliateWP/issues/1441

Basically, the referral is generated, but it’s based on the price of the membership, and does not take into account the trial if it is a _paid_ trial.

Example:
- Referral rate is 50%
- Membership is $50, trial period is $100, and both are paid up front.
- Referral should be $75, which is 50% of $150, but referral is $25 (50% of $50).
 
I tested this on client’s site, and also tried setting a per-membership rate, but it still came through at percentage of the membership, not percentage of trial & membership together. I have replicated this on our testing site.

One could argue that this is expected behavior, however perhaps there needs to be an option that includes the trial period (if paid) in the referral calculation.

**Comment by pippinsplugins** [comment]
I don't think this expected. The referral should reflect the actual amount paid for the signup, so that'd include the trial amount.

**Comment by pippinsplugins** [comment]
@lisag I've tried to replicate this but I'm seeing different results. In MemberPress, my trial period does not get added to the main membership cost, it's separate, so a $20 trial period for a $10 membership costs $20 to purchase, not $30.

**Comment by lisag** [comment]
@pippinsplugins Did you require payment up front for the membership cost, as well as the trial period? So both paid trial and (monthly) membership cost are paid at the same time?

What was the referral rate and referral amount that was generated? That was the issue - the referral was only being calculated on the membership cost, and not on the trial period (if paid).

**Comment by pippinsplugins** [comment]
I had it configured like this:
<img width="770" alt="screen shot 2017-11-13 at 1 50 42 pm" src="https://user-images.githubusercontent.com/1034109/32745873-a8fe3dcc-c879-11e7-9c96-6d5e76424d4c.png">

Referral was done on my other computer so cannot say what it was just now.

**Comment by tubiz** [comment]
@pippinsplugins I will need a copy of the MemberPress plugin.

**Comment by pippinsplugins** [comment]
@tubiz emailed you a link.

**Comment by tubiz** [comment]
@pippinsplugins I got the email. Thanks.

**Comment by tubiz** [comment]
@lisag I was able to replicate this issue, if a membership has a paid trial the referral is being calculated based on the price of the membership and not on the paid trial amount.

Example:
 
- Referral rate if `20%`
- Membership price is `$50`
- Paid Trial amount is `$100`
- Referral amount should be `$20` but `$10` is being calculated based on the membership price.

> @pippinsplugins Did you require payment up front for the membership cost, as well as the trial period? So both paid trial and (monthly) membership cost are paid at the same time?
I can't see an option in MemberPress to require payment up front for the membership as well as the trial period. Using Stripe as the gateway the paid trial `$100` is charged immediately and a future invoice is created for the membership price `$50`

So to confirm the referral rate is to be calculated based on the paid trial amount and not on the sum of the membership price and paid trial amount or the membership price.

**Comment by pippinsplugins** [comment]
>>>So to confirm the referral rate is to be calculated based on the paid trial amount and not on the sum of the membership price and paid trial amount or the membership price.

Correct, it should be based on the paid trial amount.

**Comment by tubiz** [comment]
@pippinsplugins @DrewAPicture I have tested different membership terms with the fix I am working on and the right referral amount is calculated.

I have a question as regard free trial and flat rate referral amount, should the flat rate be applied to a free trial or the referral rate set to 0.

Example:

- Referral Rate Type: Flat USD
- Referral Amount: $20.00
- Membership Term: 1 day for free then $50 / month

In the case should the referral amount be `$0.00` because the first payment is `$0.00` due to the free trial or `$20.00` the flat referral amount.

**Comment by pippinsplugins** [comment]
Yes I think flat rate should apply to free trials, so $20 would be the referral amount.

**Comment by tubiz** [comment]
PR: #2529 

Fixed

- If a membership has a paid trial, the referral amount will be calculated based on the trial amount and not on the membership price
- If a membership has a free trial and the referral rate type is Flat USD, the referral amount will be the flat rate set.

I also tested to make sure other MemberPress related issues #1375, #1441, #1342 didn't reoccur in the PR submitted.

**Comment by pippinsplugins** [comment]
Excellent, thanks @tubiz!

@gspice could you do a round of tests on this please?

**Comment by gspice** [comment]
@tubiz 

### Did first round of tests using our sandbox MemberPress site:
* If Recurring Referrals is **not** installed, it worked correctly - it created a referral for the correct percentage based on the trial amount paid and the description was correct, it was the name of the membership.
* If Recurring Referrals **is** installed and enabled, it created a referral based on a subscription payment and used the description "Subscription payment for..."  which was incorrect.  So using the same numbers as your example above - with a recurring referral rate of 50%, it created a referral for $25.  It took 50% of the monthly membership rate of $50.

**Comment by tubiz** [comment]
Thanks @gspice. The referral that was created when the Recurring Referrals plugin was active was it for subsequent renewal payment or the first membership payment. 

Based on the example above the recurring referral rate will be $25 and the description "Subscription payment for..." while the first referral rate will be $50 which is calculated based on the trial amount of $100. 

@pippinsplugins I will need a copy of the Recurring Referrals plugin to test.

**Comment by pippinsplugins** [comment]
@tubiz I've just added you to the private repo.

**Comment by tubiz** [comment]
@pippinsplugins I got the the invite. Thanks.

**Comment by gspice** [comment]
@tubiz 

> The referral that was created when the Recurring Referrals plugin was active was it for subsequent renewal payment or the first membership payment.

It was for the first membership payment.  My Recurring Referrals rate was 50% (different from the site default rate of 20%) so with the $50 membership amount, it created a referral for $25.00.

The expected behavior would have been a referral for $20 for the $100 paid trial amount that was charged, behaving the same as if the recurring referral add-on wasn't installed/active.  When the trial expires, and the first recurring referral payment is created, at that time the $25.00 referral should be created.  Does that make sense?

**Comment by tubiz** [comment]
@gspice yes it does, thanks.

**Comment by tubiz** [comment]
@gspice I have tested this with the AffiliateWP Recurring Referrals add-on and the right recurring referral is being created.

> If Recurring Referrals is installed and enabled, it created a referral based on a subscription payment and used the description "Subscription payment for..." which was incorrect. So using the same numbers as your example above - with a recurring referral rate of 50%, it created a referral for $25. It took 50% of the monthly membership rate of $50.

From the test you carried out the right recurring referral was created as a recurring referral can only be created only if the parent referral is present, it's for a subscription and it has a status of `paid` or `unpaid`.
So a recurring referral of `$25` was created based on the `50%` recurring referral rate on the `$50` monthly membership rate.

@pippinsplugins I have tested the PR with the AffiliateWP Recurring Referrals add-on and there is no issue with it. The correct recurring referral amount is being calculated.

**Comment by pippinsplugins** [comment]
@gspice could you test once more to confirm you and @tubiz get the same behavior?

**Comment by gspice** [comment]
@tubiz The first referral should be for the $100 trial fee for the 5 day trial that was charged at the default site rate of 20% for the initial purchase.  I'm retesting this again shortly.

**Comment by gspice** [comment]
@tubiz @pippinsplugins My mistake, this is working correctly.  I tested again with production, then with the changes in this pull request.  It creates the $20 referral based on the $100 trial payment, then subsequent subscription payments it uses the referral recurring rate for those subscription payments with the  correct description.

**Comment by pippinsplugins** [comment]
Great! Merging.
