### ISSUE TITLE
Don't apply the GMT offset when adding affiliates with a specific registration date

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2225]
In #2218 we added the ability to actually set the `date_registered` value when adding new affiliates.

After some discussion related to #338, we've decided not to enforce applying the `gmt_offset` value against  specified dates when adding affiliates. The thinking is that if you're specifying a date, you're expecting that date on the other end and applying a GMT offset might adjust the date/time in unexpected ways.

**Comment by DrewAPicture** [comment]
PR: #2226 

I discovered in adjusting the tests that the `gmt_offset` value is actually never set anywhere so even removing the offset logic from our functions meant that the test outcomes were unchanged.

Ultimately, I added 2 additional tests that specifically test for the _absence_ of the `gmt_offset` value when adding affiliates with a given `date_registered` value.

**Comment by pippinsplugins** [comment]
Looks good here. Merged.
