### ISSUE TITLE
Make it possible to set a user's website URL when adding an affiliate

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2227]
As raised in #338, affiliate website URLs were not being importer. This was due to there not actually being logic in core to handle this outside of the registration process.

The attached PR adds a `website_url` argument to `affwp_add_affiliate()` and `affiliate_wp()->affiliates->add()` that works in much the same way as the `notes` argument – hook into the `affwp_insert_affiliate` action and handle saving the user data with a separate callback.

Context: https://github.com/AffiliateWP/AffiliateWP/issues/338#issuecomment-302188894

**Comment by DrewAPicture** [comment]
PR: #2228 (includes 4 new tests).

**Comment by pippinsplugins** [comment]
PR looks good.

**Comment by DrewAPicture** [comment]
Merged #2228.
