### ISSUE TITLE
Some affiliate registration emails are no longer sending

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2232]
Introduced when the initialization for `$status` was removed in #2196. The emails API relies on the `$status` parameter passed to the `affwp_register_user` hook.

**Comment by DrewAPicture** [comment]
PR: #2233 

@AffiliateWP/core please test so we can get this fix pushed out asap.

**Comment by sumobi** [comment]
PR not working for me, testing again

**Comment by DrewAPicture** [comment]
Confirmed by @gspice and @sumobi.
