### ISSUE TITLE
PayPal  Buttons: add method to define the IPN URL

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#2245]
Occasionally customers need to set the IPN URL that AffiliateWP sets for the PayPal Buttons integration.

Example: https://secure.helpscout.net/conversation/336313550/55680/?folderId=205530

I'd like to add the option to define a constant that lets this URL be changed. An option in the settings screen would work but since it's pretty rare someone needs to do this, that would probably result in more support tickets due to people changing it without knowing what they're changing.

**Comment by DrewAPicture** [comment]
PR: #2274 – `AFFILIATEWP_PAYPAL_IPN` constant

**Comment by pippinsplugins** [comment]
Perfect, let's merge once tests pass.

**Comment by DrewAPicture** [comment]
Merged #2274.
