### ISSUE TITLE
UI: Empty referral amount show empty on Overview - Recent Referrals view

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2247]
If the _Amount_ field is empty in a referral, when saved it still shows as **$0.00** on the Referral screen.  However, on the Overview - Recent Referrals block it shows as  **$**       I guess it should always literally store a zero amount?  When it does it shows correctly on the Overview screen.

![overview-recentreferrals-empty](https://cloud.githubusercontent.com/assets/3018245/26701983/f056fd0e-46d7-11e7-9ae6-fc70c3a82ced.png)

![referrals-screen](https://cloud.githubusercontent.com/assets/3018245/26701990/f3372af8-46d7-11e7-8c92-b5fd98ef7b0b.png)

**Comment by DrewAPicture** [comment]
PR: #2276 

Screenshot:
![formatted](https://cl.ly/281j2D3b253s/Screen%20Shot%202017-06-12%20at%2012.56.13%20PM.png)

**Comment by pippinsplugins** [comment]
PR looks good, merge once tests pass.

**Comment by DrewAPicture** [comment]
Merged #2276.
