### ISSUE TITLE
Convert the Reports tabs API to extend the Registry API

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2248]
Currently, there's an internal API for reports tiles that "registers" and "unregisters" tiles.

The reports tab API was introduced in 1.9 – pre-dating the Registry API introduced in 2.0 – but since we're now extending the Registry API for both batch processing and upgrade routines, it would be nice to use it here as well.

**Comment by DrewAPicture** [comment]
PR: #2250

**Comment by pippinsplugins** [comment]
@DrewAPicture this is working great for me.

**Comment by DrewAPicture** [comment]
Merged #2250.
