### ISSUE TITLE
Add copy to New Creative page to clarify text-only creatives are possible

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#2249]
Some customers don't realize that they can create a text-only creative by simply not uploading an image. We should make this a little more clear on the `New Creative` page.

Currently the text at the top of this page reads:

`Use this screen to add a new creative, such as a text link or image banner.`

I think we could add the following, or something similar, to make it clear that creating a text link is as simple as not uploading an image:

`If you wish to create a text-only creative, simply do not add an image below.`

**Comment by DrewAPicture** [comment]
PR: #2269 

I opted to supplement the Text field description since it directly precedes the image input:

![text description](https://cl.ly/0V2R163s1C12/Screen%20Shot%202017-06-10%20at%2012.29.48%20PM.png)

@wordmaid If you could please review this, I'd appreciate it :-)

**Comment by wordmaid** [comment]
If we could change it slightly to the following I would be OK with it:

`To make this a text-only creative, do not add an image below.`

I think we should also add it to the Image description for ultimate clarity:

`Leave blank if you wish to create a text-only creative.`

**Comment by DrewAPicture** [comment]
@wordmaid Done.

**Comment by DrewAPicture** [comment]
Merged #2269.
