### ISSUE TITLE
Make it possible to query by two or more fields

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2254]
In an earlier release, we introduced the `fields` argument to the query classes that allowed for querying by ids only (`ids`), or a single field. There's a bunch of places in core where we really only need a couple of fields but with the current code base we're required to query for the full objects.

I would propose that we enhance the `fields` argument to accept an array of fields. Related: #1997.

For some initial benchmarking sugar: page load time on the new Reports > Payouts tab being introduced in #1997 is almost 67 percent faster than any of the others. (500ms vs 1800ms).

PR with unit tests incoming.

**Comment by DrewAPicture** [comment]
Started a PR with the base logic. TODO: Tests: #2255

**Comment by DrewAPicture** [comment]
Full test coverage has been added for the `parse_fields()` method. We'll handle full query test coverage in a separate PR.

**Comment by pippinsplugins** [comment]
@DrewAPicture this is working great for me. Merge at will.

**Comment by DrewAPicture** [comment]
Merged #2255.

Opened #2256 to track test coverage for the query classes.
