### ISSUE TITLE
Add tests coverage for the object query classes for multiple fields

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2256]
Pasing multiple fields was introduced to the base and all query classes in #2254. This is the second item in the todo list for #2255 – writing tests for each of the query classes.

**Comment by DrewAPicture** [comment]
Started a PR: #2258

**Comment by pippinsplugins** [comment]
Merged then realized you may have wanted to add more. Close if done or continue adding :)

**Comment by DrewAPicture** [comment]
Started a new PR that's a WIP: #2260

**Comment by DrewAPicture** [comment]
@pippinsplugins This is now ready for review.

We already covered a lot of the moving parts tests in #2263, just needed to add tests for the _substance_ of the query results here.

**Comment by DrewAPicture** [comment]
@pippinsplugins Note the discrepancy in the branch name on the new PR: `issue/2254-tests`. Should've been `issue/2256`, but I decided not to fix it.

**Comment by pippinsplugins** [comment]
@DrewAPicture Everything looks fine here! Nice work!

**Comment by DrewAPicture** [comment]
Merged #2260.
