### ISSUE TITLE
Earnings adjustments are sometimes skipped in update_referral()

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2257]
Ticket: https://secure.helpscout.net/conversation/377070344/60643/

Call stack for referrals/edit.php:
* `affwp_process_update_referral()`
* `affiliate_wp()->referrals->update_referral()`
* `$this->update()`
* `affwp_set_referral_status()`

I'm working on some tests that prove the bug, but the basic gist is that we fire the `$this->update()` call then if the update is successful, _then_ adjust the earnings using `affwp_set_referral_status()`.

The problem lies in passing the referral ID to `affwp_set_referral_status()` and then retrieving the already-updated referral to check for status changes – the status has already been changed so the earnings don't get adjusted.

If I can definitively prove it with tests, we should probably include this one with 2.1.

**Comment by DrewAPicture** [comment]
Here's how it goes currently
* New status passed to `update_referral()`
* We parse the args, and fall back to the current status
* Then update the referral (including the new status in the args)
* If the update is successful and the new status doesn't equal the old status, we call `affwp_set_referral_status()`
* in `affwp_set_referral_status()` we re-retrieve the already-updated referral by its ID
* And check the "old status" except that it's not really the old status, it's now the new status
* If the new status equals the "old" status, we bail
^ that's the bug

If, in whatever circumstance the new status doesn't equal the "old" status:
* We then update the referral _again_ with `update()` and the new status (which the referral is already on)
* _Then_ trigger earnings adjustments if the update is successful and the old status was one of the choices

Seems like if we skipped updating the status in `update_referral()` along with passing an `$old_status` param to `affwp_set_referral_status()`, we'd avoid updating it more than once.

**Comment by pippinsplugins** [comment]
Good catch!

Milestoning for 2.1 to ensure we don't lose track of it.

**Comment by DrewAPicture** [comment]
Still needs unit tests. Just leaving a note for myself.

**Comment by DrewAPicture** [comment]
I've written six (failing) status change tests that almost directly mirror tests for `affwp_set_referral_status()` (that are passing) to prove the bug.

**Comment by DrewAPicture** [comment]
PR: #2267

**Comment by DrewAPicture** [comment]
PR is ready for review. (tests are now passing!)

**Comment by pippinsplugins** [comment]
@DrewAPicture nice work. I can't break it. Earnings are always updated properly for me.

**Comment by pippinsplugins** [comment]
Merged, closing.

**Comment by DrewAPicture** [comment]
Backported to `master` via e749ea653235c3060358537dbd548954da9721ac. Milestone adjusted to 2.0.10.

**Comment by DrewAPicture** [comment]
Backported to `master` via e749ea653235c3060358537dbd548954da9721ac. Milestone adjusted to 2.0.10.
