### ISSUE TITLE
Null insert error if no description specified in WP Simple Pay Pro 2.5 (Stripe) shortcode.

### ISSUE THREAD

**Issue by pderksen** [AffiliateWP/AffiliateWP#2261]
The description attribute in the Stripe Checkout forms produced by WP Simple Pay Pro 2.5 is optional. In fact, all attributes are for one-time (non-subscriptions) payment forms.

If it's left out you'll get a null insert error.

WordPress database error: [Column 'description' cannot be null]
INSERT INTO `b5c_affiliate_wp_referrals` (`affiliate_id`, `date`, `currency`, `status`, `amount`, `reference`, `description`, `campaign`, `visit_id`, `products`, `custom`, `context`) VALUES (1, '2017-06-08 17:26:59', 'USD', 'pending', '0.20', 'ch_1ASUPPLwNybmtfEYzXS6r6IX', NULL, '', 1, '', 's:25:\"a:1:{s:8:\"livemode\";b:0;}\";', 'stripe')

Test WP Simple Pay shortcode:

`[stripe amount="100"]`

**Comment by pippinsplugins** [comment]
Thanks @pderksen, we'll get this PR from @nickyoung87 merged in!

**Comment by pippinsplugins** [comment]
PR looks good, merged!

**Comment by DrewAPicture** [comment]
Backported to `master` via 0763e76c509b841bc0bba9e02d01acdc5e20b6e0. Milestone adjusted to 2.0.10.
