### ISSUE TITLE
Make referral description and amount fields searchable

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2265]
Using Search on the Referrals screen under Affiliates > Referrals in the Dashboard area.  

* Searching on part of a **Description** returns all rows
* Search on a number in the **Reference** column to look for an order returns empty results
* Searching on some dollar amounts work....for example, 5.00 worked but 50.00 did not, returns empty results.

**Comment by DrewAPicture** [comment]
This is more of an enhancement request than a bug. Searching these fields isn't currently supported.

You can check out the list of supported searches in the Help tab:
![Help Tab](https://cl.ly/3C200B473t3B/Screen%20Shot%202017-06-09%20at%2012.42.58%20PM.png)

**Comment by gspice** [comment]
The Reference column (usually an order #) is supported and works great!  Thanks.

**Comment by DrewAPicture** [comment]
Added amount and description search support in a PR: #2275

**Comment by DrewAPicture** [comment]
PR includes tests because querying for referrals by description wasn't previously supported.

**Comment by pippinsplugins** [comment]
@DrewAPicture PR looks good to me. Let's merge once tests pass.

**Comment by DrewAPicture** [comment]
Merged #2275
