### ISSUE TITLE
2.1 Changelog

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2268]
Thought it might be interesting to triage the changelog for 2.1 in advance of the release. This is partially so we have it prepared for the blog post, but also so we can sort out the internal vs external changes for the benefit of the changelog. This list will be updated periodically (collaborators: feel free to update the list in this description as needed when more issues are completed).

Note: I'd imagine we'll want to remove the issue numbers before publishing. They're only included here for cross-referencing where issue descriptions have been adjusted.

## Version 2.1, July 10, 2017
* New: Import affiliates and referrals from a CSV file (#338)
* New: Export Visits to a CSV file (#2270)
* New: Filter referrals, visits, campaigns, and payouts Reports tab by a single affiliate (#1991)
* New: Add a download option for the Debug Log (#1953)
* New: Payouts tab in the Reports screen (#1997)
* Tweak: Leverage HTML5 validation on the affiliate registration form (#1919)
* Tweak: Make it possible to short-circuit visit creation via a new `affwp_tracking_skip_track_visit` filter (#2049)
* Tweak: Bump the required WordPress minimum version to 4.5. (#2128)
* Tweak: Add "Affiliate Area" link to WooCommerce's "My Account" page (#2108)
* Tweak: Improved debug logging throughout (#2165)
* Tweak: Make it possible to set the registration date and website URL fields when adding an affiliate (#2218, #2227)
* Tweak: Add the ability to query for two or more fields for all core objects (#2254, #2256, #2263) 
* Tweak: Override the PayPal IPN URL with a new `AFFILIATEWP_PAYPAL_IPN` constant (#2245)
* Tweak: Making Referrals searchable by amount or description (#2265)
* Tweak: Improve contextual help for adding text-only creatives (#2249)
* Fix: Referrals less than 1.00 using a comma decimal separator create 0.00 referral amounts (#1972)
* Fix: Strings on login/registration not being localized/translated (#1993)
* Fix: Adding a new form in Contact Form 7 overrides the previous one (#2007)
* Fix: Contact Form 7 bypasses required fields when integration enabled (#2004)
* Fix: Referral link on homepage shows WooCommerce product message when Polylang is active (#2028)
* Fix: Credit Last Referrer does not work when fallback tracking is enabled (#2038)
* Fix: Fatal error/page not found depending on affiliate link structure with WP e-Commerce (#2077)
* Fix: Affiliate links show wrong page when "Front page displays" is set in WP e-Commerce( #2078)
* Fix: Page set as front page does not show with affiliate link when using BuddyPress Docs (#2086)
* Fix: Upgrade database notice appears on fresh installs (#2101)
* Fix: Restrict Content Pro's Prevent Account Sharing option is redirecting affiliates when logging in (#2118)
* Fix: Filtering date range/affiliate in Affiliates, Creatives, Payouts, Referrals, and Visits screens displays the entire "All" count (#2149)
* Fix: Some options rows are not being cleaned up during uninstall (#2159)
* Fix: The username is being escaped twice in `affwp_get_affiliate_username()` (#2188)
* Fix: The Totals meta box on the Overview screen sometimes times out (#2202)
* Fix: Empty referral amounts in the Recent Referrals meta box don't display properly (#2247)
* Fix: Rejected referrals not updated to Unpaid if associated order is completed (#1752)
* Fix: Integration code can cause fatal error if integration plugin is not activated (#2291)

**Comment by DrewAPicture** [comment]
Added #2270.

**Comment by pippinsplugins** [comment]
Looking great so far!

**Comment by DrewAPicture** [comment]
Added #2245 (PayPal IPN).

**Comment by DrewAPicture** [comment]
Added #2265 (searchable referral amount and description fields).

**Comment by DrewAPicture** [comment]
Added #2247 (fix empty referral amounts display in Recent Referrals meta box.

**Comment by DrewAPicture** [comment]
Added #2249: improved help text for text-only creatives

**Comment by DrewAPicture** [comment]
Added #2282 – Reiteration on #955 (WooCommerce shop page + pretty affiliate URLs)

**Comment by DrewAPicture** [comment]
Removed #2281, #2282, #2257, and #2031 as they're now milestoned for 2.0.10.

**Comment by pippinsplugins** [comment]
Added #2291 and #1752.

**Comment by pippinsplugins** [comment]
Final 2.1 PR https://github.com/AffiliateWP/AffiliateWP/pull/2295
