### ISSUE TITLE
Referral not created when affiliate coupon is used, unless an affiliate link is used first

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2278]
Gravity Forms + the coupons add-on.

Using a tracked affiliate coupon tied to an affiliate does not create a referral, unless an affiliate is being tracked via a standard referral link.

Related: https://github.com/AffiliateWP/AffiliateWP/issues/378

**Comment by sumobi** [comment]
@pippinsplugins Perfecto 👍
