### ISSUE TITLE
WooCommerce - Orders - add column noting a referral was created

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2288]
In the admin:  _WooCommerce > Orders_ screen, would be great to have a column noting that the order created a referral, just a single character notation, nothing fancy.   Requested from this ticket that includes a screen video:

https://secure.helpscout.net/conversation/385407835/61566/?folderId=1170842

Similar requests for adding affiliate/referral data to the Products and Coupons screens in these issues that could perhaps be implemented together?     #909 #2287

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/mailbox/7c3a9e4da50293a7/634609/

**Comment by gspice** [comment]
Updated conversation link above:
https://secure.helpscout.net/conversation/460747973/69744/?folderId=205527

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/460747973/69744?folderId=634609

**Comment by pippinsplugins** [comment]
@gspice PR ready for testing.

**Comment by gspice** [comment]
YAY!  Works great.  This is a beautiful thing, will save so much time searching Woo orders:

![woo-orders-ref-column](https://user-images.githubusercontent.com/3018245/34457029-16b7da94-ed5a-11e7-89fa-fb180b09dd02.png)
