### ISSUE TITLE
Upgrading to 2.0.10 causes a fatal for undefined function wc_get_page_id()

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2289]
Getting some reports in support that some customers are getting fatals when upgrading to 2.0.10 with the WooCommerce integration enabled but without WooCommerce active.

We should probably just put function/class exists calls on all of the integration class instantiations.

**Comment by DrewAPicture** [comment]
PR: #2290  – Covers only WooCommerce. We should put function/class exists checks in place for the others separately in 2.1.

**Comment by DrewAPicture** [comment]
For what it's worth, this surfaced after #2282, where we introduce a callback that fires against `init`, thus running all the time regardless of whether WooCommerce is actually active.

**Comment by amdrew** [comment]
Fixed for me. Tested first by being on 2.0.10, not having WooCommerce activated, and then enabling the WC integration and saving which also fatal errors.
