### ISSUE TITLE
Check for existence of integration plugins before instantiating integration classes

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2291]
Related: #2289 

Integrations that need to be covered to prevent future issues:
* [x] Contact Form 7
* [x] Easy Digital Downloads
* [x] Caldera Forms
* [x] Formidable Pro
* [x] Give
* [x] Gravity Forms
* [x] iThemes Exchange
* [x] Jigoshop
* [x] LifterLMS
* [x] MarketPress
* [x] MemberMouse
* [x] MemberPress
* [x] Ninja Forms
* [x] OptimizeMember
* [x] Paid Memberships Pro
* [x] Paid Member Subscriptions
* [x] Restrict Content Pro
* [x] s2Member
* [x] Shopp
* [x] Sprout Invoices
* [x] Stripe Checkout (through WP Simple Pay)
* [x] WooCommerce
* [x] WP EasyCart
* [x] WP eCommerce
* [x] WPForms
* [x] WP-Invoice
* [x] Zippy Courses

**Comment by DrewAPicture** [comment]
PR: #2292 

See the checklist in the issue description for which integrations are covered in the PR and which ones aren't (yet). For the ones not included ... it just wasn't obvious which function or method to check, or I didn't have a copy of the plugin to snoop around in.

**Comment by pippinsplugins** [comment]
@DrewAPicture some of the missing plugins are in our Dropbox folder's `Plugins` folder.

**Comment by DrewAPicture** [comment]
@pippinsplugins The PR is now ready for review, all integrations are covered.

**Comment by pippinsplugins** [comment]
Merged!
