### ISSUE TITLE
Require SUPER privilege to import DB dump

### ISSUE THREAD

**Issue by bgturner** [AffiliateWP/AffiliateWP#2298]
While setting up a dev site and migrating the DB using `wp-cli`, I receive an error during the import of the dump into the dev DB:

```
ERROR 1227 (42000) at line 1965: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
```

Line 1965 of the dump is : 
```
/*!50001 CREATE ALGORITHM=UNDEFINED */ 
```

Which is contained within this larger block:

```
--
-- Final view structure for view `wp_affiliate_wp_campaigns`
--

/*!50001 DROP VIEW IF EXISTS `wp_affiliate_wp_campaigns`*/;
/*!50001 SET @saved_cs_client          = @@character_set_client */;
/*!50001 SET @saved_cs_results         = @@character_set_results */;
/*!50001 SET @saved_col_connection     = @@collation_connection */;
/*!50001 SET character_set_client      = utf8mb4 */;
/*!50001 SET character_set_results     = utf8mb4 */;
/*!50001 SET collation_connection      = utf8mb4_unicode_520_ci */;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`xxxxxxxxxxxxxxxx`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `wp_affiliate_wp_campaigns` AS select `wp_affiliate_wp_visits`.`affiliate_id` AS `affiliate_id`,`wp_affiliate_wp_visits`.`campaign` AS `campaign`,count(`wp_affiliate_wp_visits`.`url`) AS `visits`,count(distinct `wp_affiliate_wp_visits`.`url`) AS `unique_visits`,sum(if((`wp_affiliate_wp_visits`.`referral_id` <> 0),1,0)) AS `referrals`,round(((sum(if((`wp_affiliate_wp_visits`.`referral_id` <> 0),1,0)) / count(`wp_affiliate_wp_visits`.`url`)) * 100),2) AS `conversion_rate` from `wp_affiliate_wp_visits` group by `wp_affiliate_wp_visits`.`affiliate_id`,`wp_affiliate_wp_visits`.`campaign` */;
/*!50001 SET character_set_client      = @saved_cs_client */;
/*!50001 SET character_set_results     = @saved_cs_results */;
/*!50001 SET collation_connection      = @saved_col_connection */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

```

I find it odd that this block is commented out, and yet is still throwing an error.

If I delete these lines from the the dump and then retry the import everything seems to work fine. 

This issue seems to be similar to this issue: https://github.com/AffiliateWP/AffiliateWP/issues/1688

So am I correct in thinking that there is no harm in deleting these lines and then importing into the new DB?

Secondarily -- if indeed these lines in the dump are not necessary and can be rebuilt -- is there a way that I can prevent these lines from being included as a part of the dump? 

Part of what makes `wp-cli` so awesome is the ease of which I can script things, but having to wrangle a post-dump cleanup using sed or some other processing utility seems like an unnecessary pain.

**Comment by bgturner** [comment]
I did a little more generalized searching and found this SO question: https://stackoverflow.com/questions/25924796/mysqldump-without-create-algorithm-and-definer

Which led me to this blog post : https://dbperf.wordpress.com/2010/04/12/removing-definer-from-mysql-dump/

I changed my wp-cli workflow a bit with the result being a cleaner DB dump which I'm able to import other places:

```
wp db export - | grep -v "50013 DEFINER" > db_backup.sql
```
This pipes the export through grep which ignores any line it matches with `50013 DEFINER`. The result is one less line in the dump, and something that I can import successfully. 

I'm mostly posting this as a work around, with my other questions still standing:

- Does removing this `DEFINER` affect any functionality?
- Is there a way to have the plugin not export this by default so that the dumps have greater portability without resorting to filtering things out with grep?

**Comment by pippinsplugins** [comment]
@bgturner please see https://github.com/AffiliateWP/AffiliateWP/issues/2273 and https://github.com/AffiliateWP/AffiliateWP/issues/2117

I don't believe removing the `DEFINER` will cause any issues so long as it successfully creates the view.

Between #2273 and #2117, we're going to address this in one way or another but it's not yet decided exactly how.

**Comment by bgturner** [comment]
Thanks for the feedback @pippinsplugins  -- I'll be interested to see how this plays out. I'll close this in favor of those other issues.

To wrap up this collection of thoughts (working with wp-cli, db exports, and AffiliateWP) -- It appears that the view has been correctly created. For anyone else that doesn't know how to verify (I had to tinker and search a bit) -- you can inspect your DB using `wp-cli` and some SQL:

```
$wp db cli
mysql> show full tables;
```
Which should output something like:
```
+-------------------------------------------------+------------+
| Tables_in_db_name                               | Table_type |
+-------------------------------------------------+------------+
| wp_affiliate_wp_affiliatemeta                   | BASE TABLE |
| wp_affiliate_wp_affiliates                      | BASE TABLE |
| wp_affiliate_wp_campaigns                       | VIEW       |
| wp_affiliate_wp_creatives                       | BASE TABLE |
...
```
