### ISSUE TITLE
WooCommerce - show pretty aff links & custom blog permalinks strip affiliate ids, does not create cookie when blog url shared with affiliate id

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2302]
Applies to this ticket:
https://secure.helpscout.net/conversation/387884596/61801/?folderId=1170842

**Integration**: WooCommerce
**AffiliateWP Settings**:  Pretty Affiliate URLs enabled
**WP Settings > Permalinks**: Custom Structure:   /article/%postname%/

**Steps to reproduce**:  
* Add an affiliate id to a post's URL, use in a different browser
**Results**:
* Affiliate id is stripped and the cookie is not created 

Reproduced locally.  If you uncheck Pretty Affiliate URLs , it works correctly.  Only appears to happen when WooCommerce integration is enabled.

**Comment by pippinsplugins** [comment]
Note: using `%post_id%` instead of `%postname% works properly.

**Comment by pippinsplugins** [comment]
Punting this to 2.1.5.

**Comment by amdrew** [comment]
@gspice Tried to replicate this issue but tripped on permalinks. I changed my custom structure to `/article/%postname%/` and I just get page not founds. Are you still able to add the `article` in your URLs?

No plugins active, just WP 4.9.2.

<img width="1064" alt="screenshot 2018-01-20 12 50 24" src="https://user-images.githubusercontent.com/52581/35176854-7fa2ab6a-fde0-11e7-80e5-876def7cd152.png">

<img width="624" alt="screenshot 2018-01-20 12 50 36" src="https://user-images.githubusercontent.com/52581/35176857-85e47af8-fde0-11e7-8e81-1a9e9edc0edf.png">

**Comment by amdrew** [comment]
@gspice I can't replicate this, works fine for me. Can you still replicate?


<img width="550" alt="screenshot 2018-01-20 12 56 47" src="https://user-images.githubusercontent.com/52581/35176997-66cca32e-fde1-11e7-90d9-174ad789df77.png">

<img width="957" alt="screenshot 2018-01-20 12 56 39" src="https://user-images.githubusercontent.com/52581/35176999-67019228-fde1-11e7-93e3-60b1919dc60a.png">

<img width="1062" alt="screenshot 2018-01-20 12 56 27" src="https://user-images.githubusercontent.com/52581/35177000-6732d0f4-fde1-11e7-807d-a6390671af14.png">

<img width="1129" alt="screenshot 2018-01-20 12 57 48" src="https://user-images.githubusercontent.com/52581/35177022-8d381282-fde1-11e7-8372-0121df7fc2e7.png">

**Comment by gspice** [comment]
@amdrew This is still broken for me.  In your testing, use a "pretty" affiliate link and that's when it breaks.  It strips the affiliate link and does not create the cookie.  

woocommerce.affwp.dev/article/hello-world/ref/3/

**Comment by amdrew** [comment]
@gspice Oh duh, totally missed that

**Comment by tubiz** [comment]
@pippinsplugins I am working on this.

**Comment by tubiz** [comment]
PR: #2626 

The issue was from the `EP_ATTACHMENT` endpoint mask. 
The only fix was to remove it from the list of endpoint masks used when creating the referral variable endpoint. 
With the `EP_ATTACHMENT` removed the referral cookie was still created for attachment links with the referral variable.

**Comment by tubiz** [comment]
I think this is also the issue with #2324. So this PR should fix that too.

**Comment by gspice** [comment]
Excellent job @tubiz !  I tested this and it is working for me, the "pretty" link no longer strips the affiliate name/id when using a custom permalink setting like: `http://woo.local/article/%postname%/` when wanting to share a blog post with affiliate info added.
