### ISSUE TITLE
Pagination does not work if Affiliate Area is set to be the "front page"

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2303]
If the affiliate area is set to be the "front page" (Setting -> Reading) then the pagination on the visits or referrals tab does not work. Clicking the page numbers reloads the page and does not show the correct results.

**Comment by pippinsplugins** [comment]
@tubiz Would be great if this could be tackled as well.

**Comment by tubiz** [comment]
PR: #2542
