### ISSUE TITLE
Average Referrals Per Payout shows nan

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2307]
When there are no payouts I see `nan` for `Average Referrals Per Payout` on the new `Payouts` tab:

```
Warning: Division by zero in /wp-content/plugins/AffiliateWP/includes/admin/reports/tabs/class-payouts-reports-tab.php on line 317
```

<img width="1647" alt="screenshot 2017-07-11 14 52 20" src="https://user-images.githubusercontent.com/52581/28049032-bbd083ee-6648-11e7-88ad-0f66d14298e1.png">

**Comment by DrewAPicture** [comment]
PR: #2308 

Skips registering the average-based tiles if there's nothing to average, for the others, normalize the number passed via the `data` argument to zero if there's no data.

**Comment by amdrew** [comment]
@DrewAPicture Perfecto 👍
