### ISSUE TITLE
Paid Memberships Pro coupon tracking

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#231]
Paid Memberships Pro needs coupon tracking.

Related #93

**Comment by michaelbeil** [comment]
another for coupons in PMP: https://secure.helpscout.net/conversation/127963487/18302/

**Comment by pippinsplugins** [comment]
Ready for testing!

**Comment by pippinsplugins** [comment]
Tracking isn't working properly yet.
