### ISSUE TITLE
Autocomplete when adding an affiliate manually does not work unless 1 affiliate already exists

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2334]
On a freshly created sub-site (might also affect single site installs) with AffiliateWP, you cannot add a user as an affiliate via the `Affiliates -> Affiliates -> Add new` screen (with autocomplete) unless there is at least 1 affiliate already created. Typing the username manually does work however.

While searching for the username in the `User` Input field, the spinner appears and disappers, with no users shown. There are no errors in the PHP error log, nor in the browser's debug console.

Once you have created 1 affiliate via the add new user screen (skipping email confirmation and adding as affiliate) you can then see the user accounts on the new affiliate screen.

To replicate:

1. Set up fresh sub-site
2. Install and activate AffiliateWP (latest master)
3. Go to `Affiliates -> Affiliates -> Add new` and try and add your admin account as an affiliate. No users should show in the `User` input field.
4. Add a new user in WordPress, skip confirmation email, and add them as an affiliate.
5. Go back to the new affiliate screen and type in your admin username, it will then show.

Tested a couple of times on 2 brand new installs, can someone else give this a test to replicate?

**Comment by DrewAPicture** [comment]
This is due to this change: 91e304f25703fc158d35278893ab34e97abd7854. 

I think this report might be slightly misleading. It's more that the autocomplete won't find any users unless you already have an affiliate. Supplying a valid, available username to the form should still work.

**Comment by amdrew** [comment]
^ that's correct, it's just the autocomplete

**Comment by DrewAPicture** [comment]
PR: #2337 

@amdrew please test

**Comment by amdrew** [comment]
@DrewAPicture Works great!
