### ISSUE TITLE
Autocomplete not working for API Keys

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2335]
Autocomplete is not working for API Keys when searching for a username:

<img width="661" alt="screen shot 2017-08-01 at 2 12 59 pm" src="https://user-images.githubusercontent.com/52581/28806347-8db70934-76c3-11e7-9255-f1a36c9d15fd.png">

Possibly related to https://github.com/AffiliateWP/AffiliateWP/issues/2334

You can also replicate this on our live site.

**Comment by DrewAPicture** [comment]
PR: #2338

**Comment by amdrew** [comment]
@DrewAPicture Still not working for me, tried on brand new install, searching for my `admin` username.

**Comment by pippinsplugins** [comment]
Works perfectly for me, merging.
