### ISSUE TITLE
Affiliate autocomplete doesn't work for the Generate Payout File form on the Referrals screen

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2336]
> Looks like we aren't passing a `status` value in the Generate Payout File form, which is preventing the autocomplete from being able to search affiliates. This is likely due to [91e304f](https://github.com/AffiliateWP/AffiliateWP/commit/91e304f25703fc158d35278893ab34e97abd7854), where `get_users()` is only called if there are users to search.

Related to: #2329.

Discovered here: https://secure.helpscout.net/conversation/402804894/63628/?folderId=835878.

**Comment by DrewAPicture** [comment]
@michaelbeil This should already be fixed as of d7486de39ecb1e74aa242381fbb982cd8c342090 (also on the 2.1.4 milestone).

**Comment by amdrew** [comment]
Can confirm this is now working

**Comment by DrewAPicture** [comment]
Closing as a duplicate.
