### ISSUE TITLE
Affiliate Area: Add Reference id column to Referrals tab

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2340]
Add a Reference column to the Referrals tab/page in the Affiliate Area so affiliates can see the order/etc that created the referral.

![aff-area-referrals](https://user-images.githubusercontent.com/3018245/29091226-1817f9da-7c37-11e7-8dd7-7b7241f59906.png)

**Comment by pippinsplugins** [comment]
PR ready for testing.

**Comment by amdrew** [comment]
@pippinsplugins Works for me. Also looks good with the responsive additions.
