### ISSUE TITLE
Export Affiliates report: Split "Name" column into "First Name" and "Last Name" columns

### ISSUE THREAD

**Issue by lisag** [AffiliateWP/AffiliateWP#2341]
Currently when affiliates are exported from the Tools screen there is just the one `Name` column which includes both the first and last name. 

<img width="776" alt="screen shot 2017-08-09 at 8 02 54 am" src="https://user-images.githubusercontent.com/11830108/29092120-4b6f11c2-7cd9-11e7-9ab3-4b678aef9b76.png">

It would be awesome to split the first and last name into two separate columns for easier sorting, importing into other services, and any other uses.

<img width="878" alt="screen shot 2017-08-09 at 8 03 25 am" src="https://user-images.githubusercontent.com/11830108/29092134-53ab8e38-7cd9-11e7-91c0-40acd9a33419.png">

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by amdrew** [comment]
@pippinsplugins Works for me!
