### ISSUE TITLE
Renewed license keys showing as expired

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2342]
When a customer's license key is renewed it shows as expired for a random period of time, sometimes up to a few hours or more. This results in premature support tickets.

Pippin is kindly going to fix this:

> I'm going to fix it by forcing settings to recheck the key anytime the license field is loaded

**Comment by pippinsplugins** [comment]
I don't know if I love this but it does work.

Note, it requires two page loads to fully update.

@amdrew test and give me your opinion?

**Comment by amdrew** [comment]
@pippinsplugins I don't think I'm testing correctly since it seems to work fine even on master, can you confirm the best way to test to first replicate the issue?

This is what I'm doing:

1. On AffiliateWP.com: Created a new purchase to get a fresh license key
2. On local site: Activated license key
3. On AffiliateWP.com: Set the expiration of license key to 2016 so it's expired
4. On local site: Confirmed that the license key had expired since it shows a notice.
5. On AffiliateWP.com: Edited the license key to a valid date so the key is no longer expired. The "renew" button doesn't seem to have any affect
6. On local site: With master branch, tried to activate the license key. It then correctly shows as active.

**Comment by pippinsplugins** [comment]
@amdrew yep those steps are right. Testing again.

**Comment by pippinsplugins** [comment]
@amdrew I've adjusted this a little. Could you try again now?

**Comment by amdrew** [comment]
@pippinsplugins What I meant from my last comment is that I'm not actually able to first replicate the issue. Can you post steps so I can replicate the issue before I test the PR? Using the steps I provided above, I can activate a license key that have been "renewed" just fine. Also works fine with the PR.

Example (on master branch):

This is what shows when `Activate License` is clicked. The weird license notice is covered in https://github.com/AffiliateWP/AffiliateWP/issues/2346
<img width="955" alt="screenshot 2017-08-23 15 51 50" src="https://user-images.githubusercontent.com/52581/29598126-0209d826-881b-11e7-899d-ac031a84da4e.png">

Now that the license is expired, I set the license key's date to something valid in the future:

<img width="522" alt="screenshot 2017-08-23 15 54 24" src="https://user-images.githubusercontent.com/52581/29598175-58e67550-881b-11e7-82c4-19a45800cc4f.png">

That's how I'm testing the subscription essentially being "renewed". Now that the subscription
has been renewed, I try and activate the key again. This should fail, as it does with customers, and the point of this issue:

<img width="888" alt="screenshot 2017-08-23 15 56 14" src="https://user-images.githubusercontent.com/52581/29598219-9d72f66c-881b-11e7-8fe3-542d1d46b6ff.png">

As you can see, it works, and without a page reload or anything. I still think I'm testing incorrectly. What are your steps to replicate the issue?

**Comment by pippinsplugins** [comment]
Weird, that's not the behavior I'm seeing. My testing steps:

1. Activate valid license
2. Go to affiliatewp.com and change the expiration date on the license to something in the past
3. Go back to the site using the license and reload the settings screen (might have to reload twice)
4. You should see the error message
5. Go back to affiliatewp.com and change the date to in the future
6. Repeat 3 but now it should show as valid again

**Comment by michaelbeil** [comment]
I was able to replicate this using the steps listed above.

**Comment by pippinsplugins** [comment]
Replicate the bug and confirm fix or only replicate bug?

**Comment by michaelbeil** [comment]
Replicate the bug and confirm the fix.

**Comment by gspice** [comment]
* Verified issue of _not_ updating using production version.  
* Change license key to future date, removed all data with plugin
* Installed branch issue-2342, validated license key
* Changed license key to past date, showed on website with 2 refreshes with change in label, etc
* Changed license key to future date,  showed validate after 2 refreshes, did not have to click the activate button.

**Comment by pippinsplugins** [comment]
That's good enough for me and is an improvement! I'm going to merge and close.
