### ISSUE TITLE
License expiration notice shown in wrong location, without styling

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2346]
The license expiration notice shows in the wrong location.

<img width="683" alt="screenshot 2017-08-12 13 27 01" src="https://user-images.githubusercontent.com/52581/29236674-01647500-7f62-11e7-8b80-a52a52d2a7bb.png">

To replicate:

1. On master branch, try activating an expired license key on the Settings -> General tab

**Comment by DrewAPicture** [comment]
I think the problem here is just that we aren't including one of the core notice classes so that's why it's coming in unstyled. Adding 'error' to the `$class` value should work. Working on a PR.

**Comment by DrewAPicture** [comment]
Added a PR: #2376

You can test with this license key: `ce7ed578255a3a9c53281ee7bafdf88e`

![Preview](https://cl.ly/1d1e1R2R081F/Screen%20Shot%202017-09-07%20at%2011.43.15%20AM.png)

**Comment by pippinsplugins** [comment]
PR looks good
