### ISSUE TITLE
Affiliate Area is not responsive

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2349]
The Affiliate Area is not responsive, well some of the tables are not. 

For example, the statistics page is too wide. 

Here is a GIF: http://beil.io/p51lxG.

Ticket: https://secure.helpscout.net/conversation/416268715/65060.

**Comment by amdrew** [comment]
Unless we move away from actual HTML tables it will never be responsive.

**Comment by pippinsplugins** [comment]
Sure we can. Responsive tables are a thing :) We did it in RCP https://github.com/restrictcontentpro/restrict-content-pro/issues/492

**Comment by amdrew** [comment]
Wow, did not know you could do that, going to dig into it some more :)

**Comment by michaelbeil** [comment]
Ticket: https://secure.helpscout.net/conversation/434161588/66951/?folderId=634609

**Comment by amdrew** [comment]
Some progress on this:

### Desktop resolution:

<img width="904" alt="screenshot 2017-09-25 16 39 53" src="https://user-images.githubusercontent.com/52581/30791646-693176d0-a210-11e7-94a1-b0f789ac8d38.png">

___

### Mobile resolution:

Note, this only shows the first table as responsive for demo purposes.

<img width="313" alt="screenshot 2017-09-25 16 40 09" src="https://user-images.githubusercontent.com/52581/30791644-691d57d6-a210-11e7-9479-9368ff56b325.png">

___

I propose we add a new class to the tables in addition to `affwp-table`. Something like `affwp-table-responsive`. If we don't, then all tables with the `affwp-table` and without the `data-th` attribute on the `td`'s will look like the 2nd and 3rd table in this screenshot:

<img width="299" alt="screenshot 2017-09-25 16 40 55" src="https://user-images.githubusercontent.com/52581/30791645-692f6200-a210-11e7-9315-a61612df900e.png">

This will cause issues with any third party add-on that adds a table (and using the `affwp-table` class) and any of our existing add-ons that add a table. By using a new CSS class we can safely include responsive tables and also give time to 3rd party developers (and ourselves) in updating.

___

### All tables responsive:

Desktop:

<img width="315" alt="screenshot 2017-09-25 16 52 39" src="https://user-images.githubusercontent.com/52581/30791837-01a7fe06-a212-11e7-9f38-537dd696b0f7.png">

___

iOS:

<img width="545" alt="screenshot 2017-09-25 16 52 22" src="https://user-images.githubusercontent.com/52581/30791838-01a962c8-a212-11e7-8eb7-1d9e60493569.png">

**Comment by amdrew** [comment]
Another layout we should consider is having the values underneath like the below. It might "fit" better in regards to the different translations etc:

<img width="308" alt="screenshot 2017-09-25 16 57 13" src="https://user-images.githubusercontent.com/52581/30791911-b5a814a4-a212-11e7-8692-8675d250a01e.png">

**Comment by amdrew** [comment]
PR, will need some additional testing: https://github.com/AffiliateWP/AffiliateWP/pull/2394

**Comment by amdrew** [comment]
There are some instances where if there is no data, the `td` has a colspan applied to it to stretch the text across the columns. E.g. the `Referrals` table:

<img width="740" alt="screenshot 2017-09-25 21 16 59" src="https://user-images.githubusercontent.com/52581/30798672-f37825b6-a236-11e7-804f-e58029cbc26f.png">

For tables like this, I've added a `affwp-table-no-data` CSS class to the `td`. This allows us to then hide the pseudo header like so at mobile resolutions:

<img width="434" alt="screenshot 2017-09-25 21 04 40" src="https://user-images.githubusercontent.com/52581/30798704-0fae7ce4-a237-11e7-9614-b1543cc451b8.png">

I'm open to suggestions on a better class name.

And here are some other examples:

Visits:

<img width="442" alt="screenshot 2017-09-25 21 04 49" src="https://user-images.githubusercontent.com/52581/30798762-3c647a9a-a237-11e7-9860-283b3d910092.png">

___

Referral Payouts:

<img width="439" alt="screenshot 2017-09-25 21 04 44" src="https://user-images.githubusercontent.com/52581/30798783-45f503a4-a237-11e7-87d9-8785cfc012cc.png">

___

Campaigns:

This one is a little bit different. I decided to leave a title, `Campaigns:`, so it is clear what the table relates to:
<img width="441" alt="screenshot 2017-09-25 21 04 30" src="https://user-images.githubusercontent.com/52581/30798809-5b7bd932-a237-11e7-8735-d62f79de3041.png">

**Comment by amdrew** [comment]
There are also elements that need to repeat, e.g. campaigns. In these cases the last `td` has a bottom margin to separate each campaign:

<img width="362" alt="screenshot 2017-09-25 20 15 44" src="https://user-images.githubusercontent.com/52581/30798986-dafe0770-a237-11e7-9699-e262649926ee.png">

___

Same with `Referral payouts`:

<img width="420" alt="screenshot 2017-09-25 20 16 01" src="https://user-images.githubusercontent.com/52581/30798998-e3782890-a237-11e7-8ea9-3741ef0cf6a4.png">

___

And Referrals"

<img width="457" alt="screenshot 2017-09-25 21 25 14" src="https://user-images.githubusercontent.com/52581/30799039-0e3b1088-a238-11e7-88e6-9db41bf52510.png">

___

And Visits:

<img width="462" alt="screenshot 2017-09-25 21 25 41" src="https://user-images.githubusercontent.com/52581/30799071-1f44f4d4-a238-11e7-9a84-abda0e425579.png">

**Comment by amdrew** [comment]
@AffiliateWP/core ^ That's all for now, I'd appreciate any help with testing. Going to give it another run tomorrow in case I've missed anything.

Tabs to test (the ones with tables):

1. Statistics
2. Referrals
3. Payouts
4. Visits

Test each tab at:

1. Desktop resolution (to make sure it looks the same as before)
2. Mobile to tablet resolutions (to see the new responsive tables)
3. With data for each table
4. Without data for each table

Additional notes

- The CSS uses a `@media (max-width: 767px)` rule so the tables can be responsive for tablets etc. 
- Make sure `SCRIPT_DEBUG` is set to true
- Test in various browsers if possible. It's quite a simple technique for faking the responsiveness (hides the `th`'s and shows new headings inside the `td`'s that are inserted on the `:before` pseudo element) so should be compatible in IE11 and all modern browsers.

**Comment by pippinsplugins** [comment]
This looks awesome!

Is there a reason you've added a `affwp-table-responsive` class instead of just assuming all `affwp-table`s are responsive?

**Comment by amdrew** [comment]
@pippinsplugins Yep there sure was

> I propose we add a new class to the tables in addition to affwp-table. Something like affwp-table-responsive. If we don't, then all tables with the affwp-table and without the data-th attribute on the td's will look like the 2nd and 3rd table in this screenshot:

> This will cause issues with any third party add-on that adds a table (and using the affwp-table class) and any of our existing add-ons that add a table. By using a new CSS class we can safely include responsive tables and also give time to 3rd party developers (and ourselves) in updating.

**Comment by amdrew** [comment]
The class name on that is up for discussion if anyone can think of a better one. Perhaps `affwp-table-mobile`? meaning all mobile devices, phones/tablets etc

**Comment by pippinsplugins** [comment]
Ah yep, makes perfect sense and I like `affwp-table-responsive` better than `affwp-table-mobile`.

I'm 100% happy with this!

**Comment by gspice** [comment]
Tested on multiple phone sizes using two different Genesis child themes, looks great!

Also added tickets for adding the same styling to:

*  Order Details for Affiliates
https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/issues/34
*  Show Affiliate Coupons
https://github.com/AffiliateWP/affiliatewp-show-affiliate-coupons/issues/9

**Comment by ramiabraham** [comment]
- Added the same as gpsice above for RR ([link](https://github.com/AffiliateWP/affiliatewp-tiered-affiliate-rates/issues/36)).
- I have literally no constructive feedback to offer.
- Looks great.
- Looks awesome.
- Functions as expected.
- I like it.

**Comment by amdrew** [comment]
@ramiabraham They cannot since the new CSS styling in forms.css is only loaded on the front-end. That's ok though, we should definitely create new (and separate) styling for any admin tables. We could keep the class names the same.
