### ISSUE TITLE
Change Pound Sterling to Great British Pound

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2350]
British folks don't really call it the Pound Sterling, but commonly refer to it as Great British Pound.

Ticket: https://secure.helpscout.net/conversation/416373549/65074/?folderId=634609.

**Comment by pippinsplugins** [comment]
WooCommerce uses `Pound Sterling`, as does EDD. I have never heard of anyone claiming that's wrong until now.

I vote that we leave it as `Pound Sterling` in order to be consistent with our largest integration: WooCommerce.
