### ISSUE TITLE
WooCommerce integration: Add rate type option to product rate options

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2352]
In WooCommerce - Products:  currently you can adjust the referral rate amount on a per-product basis.  Would be nice to also have the ability to adjust the referral rate type:

![woo-product-aff-rate](https://user-images.githubusercontent.com/3018245/29469712-52630b1a-83fe-11e7-840b-c2d66e522545.png)

You can do this using the Affiliate Product Rates add-on however you have to set it per-product, per-affiliate even if it is the same amount on every affiliate.

**Comment by amdrew** [comment]
Related: https://github.com/AffiliateWP/AffiliateWP/issues/354

**Comment by lisag** [comment]
Another request: https://secure.helpscout.net/conversation/475060539/71330/?folderId=414056

**Comment by pippinsplugins** [comment]
@tubiz would you like to work on this?

**Comment by tubiz** [comment]
@pippinsplugins yes.

**Comment by tubiz** [comment]
PR: #2580 

* Simple product
<img width="737" alt="simple product rate type" src="https://user-images.githubusercontent.com/602184/36429515-30eba31a-1653-11e8-9b08-01d5c36b720e.png">

* Variable product
<img width="738" alt="variation rate type" src="https://user-images.githubusercontent.com/602184/36429521-3325f450-1653-11e8-816f-ee9761540bc0.png">

**Comment by pippinsplugins** [comment]
@tubiz variations aren't quite working for me. If I add variations to a product, I'm unable to set the rate and rate type separately fro each variation. They all get set to the same value.

**Comment by tubiz** [comment]
@pippinsplugins oops. It is working for me. Let me recheck.

**Comment by tubiz** [comment]
@pippinsplugins what version of the WooCommerce plugin are you using?

**Comment by pippinsplugins** [comment]
@tubiz sorry, my mistake. It is all working great!

@amdrew could you please give this a test too?

**Comment by amdrew** [comment]
@tubiz @pippinsplugins Working so far in all my testing. 

@gspice Tag! Could you also please do some testing on this? Want to make sure we don't miss anything.

**Comment by amdrew** [comment]
@tubiz While you're working on product variations, could you have a go at improving the UI?

<img width="677" alt="screen shot 2018-02-21 at 12 01 43 pm" src="https://user-images.githubusercontent.com/52581/36454026-1c87d6bc-16ff-11e8-9ab7-2cdb1d1d42ff.png">

Feels a bit bunched up. Comparing our HTML to WooCommerce, it appears at though we should place each setting in its own `p` tag. 

Theirs (in its own p tag):

<img width="1264" alt="screen shot 2018-02-21 at 12 05 53 pm" src="https://user-images.githubusercontent.com/52581/36454151-a3f25bcc-16ff-11e8-95f7-754e875be97e.png">

Ours (all in one p tag)

<img width="1242" alt="screen shot 2018-02-21 at 12 06 12 pm" src="https://user-images.githubusercontent.com/52581/36454149-a3c52328-16ff-11e8-8ae2-4c30f8e39034.png">




The first two settings (rate type and rate) also need an id to the `label`.

**Comment by amdrew** [comment]
Working well for me, can't fault it 👍

**Comment by tubiz** [comment]
@amdrew PR updated with the UI improvements changes.

<img width="771" alt="product variation ui improvements" src="https://user-images.githubusercontent.com/602184/36456549-c1d6b58e-16a5-11e8-8952-5a273bb44dae.png">

**Comment by gspice** [comment]
Works good for me -- tested with rates set in other areas and it behaved as expected.

**Comment by amdrew** [comment]
@tubiz

Let's:

1. Add `id`'s to the fields that match each label's `for` attribute. That way the input gains focus when the label is clicked.
2. Remove the `options` class from the `Configure affiliate...` line since it isn't an option. Looks a bit weird with the double line.
3. Remove the extra div shown here if possible: 
    <img width="564" alt="screen shot 2018-02-23 at 2 39 18 pm" src="https://user-images.githubusercontent.com/52581/36573798-87c24170-18a7-11e8-88b1-8ad50fcdf79d.png">

    WooCommerce have `div`'s and then `p`'s inside. It seems we have a `div`, another `div`, and then the `p`'s.

**Comment by tubiz** [comment]
@amdrew PR updated with the requested changes.

**Comment by amdrew** [comment]
@tubiz Thanks! Looks great

**Comment by pippinsplugins** [comment]
@tubiz looks like we have a merge conflict now. Could you resolve it please?

**Comment by tubiz** [comment]
@pippinsplugins the merge conflict has been fixed.

**Comment by pippinsplugins** [comment]
Thanks!
