### ISSUE TITLE
Users updating core from an old version getting database error: unknown column unpaid_earnings in field list

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2353]
Users updating the core AffiliateWP from an older version (so far it's been 1.94 and 1.9.5.1) after they update the plugin, when they click on the **Update database** button are receiving the error:

`WordPress database error: Unknown column unpaid_earnings in field list`

Currently affecting two tickets:

https://secure.helpscout.net/conversation/416532901/65101/?folderId=1170842
https://secure.helpscout.net/conversation/413994823/64813/?folderId=205529

**Comment by DrewAPicture** [comment]
@gspice After some investigation, I think what's happening is sort of a race condition: The upgrade routine for 2.0 is showing the upgrade database form, but the affiliates table was only recreated (which is what adds the new column) for the 2.0 upgrade.

This means that the form is showing but for anything newer than 2.0, the table isn't _also_ being recreated. I think we can solve this by simply adding a call to recreate the affiliates table to the batch process _before_ the processor starts.

**Comment by DrewAPicture** [comment]
PR: #2354

**Comment by DrewAPicture** [comment]
@gspice This has been merged. Please feel free to send a copy of latest master to any of the affected customers for confirmation.
