### ISSUE TITLE
Reports - Referrals - Total Unpaid Earnings showing total for All Time and not filtered date range

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2355]
Using sandbox site:  http://s14890.p27.sites.pressdns.com/woo/

1. Go to _Affiliates > Reports > Referrals_ tab
2. Filter by **Custom** date, July 1 to July 5 for the affiliate  ```affilgsc```, click **Filter**
3. Notice **Total Unpaid Earnings** shows $1043.41 which is the total of _all_ that affiliate's unpaid earnings.   Total should show $142.50 for those 5 days. 

Reports screen:
![reports-referrals-july1-5](https://user-images.githubusercontent.com/3018245/29584800-bc1af020-8739-11e7-8c83-827927b52f7f.png)

Referrals screen:
![referrals-july1-5](https://user-images.githubusercontent.com/3018245/29584824-d33982e4-8739-11e7-9ca0-dcc23ebabc23.png)

Notify customer on ticket when fixed:
https://secure.helpscout.net/conversation/418439273/65313/?folderId=205529

**Comment by Kyzcreig** [comment]
Agreed this has been a problem for years, it's so dumb. It's so easy to fix. Makes me think we shouldn't use the plugin anymore

**Comment by pippinsplugins** [comment]
@Kyzcreig the feature that this bugs effects was introduced in version 2.1, which was released on July 10, 2017. While yes we appreciate that it's a highly important bug that we need to fix, let's not use such extreme hyperbole here.

**Comment by ramiabraham** [comment]
@AffiliateWP/core Added a PR: https://github.com/AffiliateWP/AffiliateWP/pull/2404

**Comment by Kyzcreig** [comment]
Thanks guys :)

**Comment by amdrew** [comment]
@ramiabraham I'm getting a weird result.

Here's my referrals list, note how there are no referrals from 2017:

<img width="1489" alt="screenshot 2017-10-05 10 30 18" src="https://user-images.githubusercontent.com/52581/31200721-8d6e56f8-a9b8-11e7-966c-31db60639607.png">

___

Here's the screen on master for comparison:

<img width="1348" alt="screenshot 2017-10-05 10 29 52" src="https://user-images.githubusercontent.com/52581/31200703-792ba3f8-a9b8-11e7-9d70-5fb70a4aeb0d.png">

___

Here's the same screen with the PR:

<img width="1491" alt="screenshot 2017-10-05 10 30 46" src="https://user-images.githubusercontent.com/52581/31200709-7f285cf6-a9b8-11e7-80fe-cc28970a0390.png">

I've filtered it from February 1st 2017 till now but it's showing `$15.00` in total unpaid earnings. As per my first screenshot, there are no unpaid referrals this year. Where is the $15 coming from? 

@gspice Mind giving this a test also?

**Comment by ramiabraham** [comment]
@amdrew Weird! Testing as well.

**Comment by amdrew** [comment]
Ok found the issue, there's a $15 referral in the database from `2017-03-04 05:23:58`, however it doesn't below to my admin affiliate (ID of 1). This particular referral belongs to an affiliate with an ID of `20`. Once I change the date on that referral to something further in the past, it shows correctly:

<img width="1470" alt="screenshot 2017-10-05 10 45 40" src="https://user-images.githubusercontent.com/52581/31201213-59db7f94-a9ba-11e7-80b7-ef18bf3dc6bb.png">

So somehow it's not correctly showing only the referrals from the filtered affiliate.

**Comment by gspice** [comment]
My totals match for the date range July 1 - 5 for `affilgsc`:
![reports-referrals](https://user-images.githubusercontent.com/3018245/31201355-3ccc6c12-a913-11e7-85e5-bc8c677fd30d.png)

**Comment by amdrew** [comment]
Get this on the above screen:

```
PHP Notice:  Undefined variable: affiliate_id in /wp-content/plugins/AffiliateWP/includes/admin/reports/tabs/class-referrals-reports-tab.php on line 70
```

last line in stack:

```
AffWP\Referral\Admin\Reports\Tab->register_tiles() /wp-content/plugins/AffiliateWP/includes/abstracts/class-affwp-reports-tab.php:317
```

**Comment by ramiabraham** [comment]
@amdrew Thanks, corrected

**Comment by amdrew** [comment]
@ramiabraham Great, it's fixed!
