### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by zeromajstor** [AffiliateWP/AffiliateWP#2357]
Hi,
in my log error file I see this error:

PHP Notice:  Trying to get property of non-object in wp-content/plugins/affiliatewp-custom-affiliate-slugs/includes/class-base.php on line 734

on line 734 I see this:

```
if ( ! ( has_shortcode( $post->post_content, 'affiliate_area' ) && isset( $_GET['tab'] ) && $_GET['tab'] == 'settings' ) ) {
			return;
		}
```
Do you maybe know what to do?
Regards

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://affiliatewp.com/support

we use GitHub for development tracking only.
