### ISSUE TITLE
Use a better strategy for garbage collecting  temporary data for batch processes 

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2358]
In testing (and eventually fixing) [this](https://secure.helpscout.net/conversation/402804894/63628/) customer ticket, it came to light that the problem was that the payout generation process had likely been interrupted mid-process, and that ultimately prevented garbage collection of the temporary data associated with it – for that and all subsequent runs.

So I would propose that we do a couple of things to ensure garbage collection is handled every time a batch process is run:

1. Run the `finish()` method at the start of the `init()` method for every batch process (clear the decks before we begin)
2. Introduce a new `delete_by_match()` method to the `Data_Storage` class to allow for deleting all keys prefixed with a batch ID, and then leverage it in the top-level `finish()` methods.

**Comment by DrewAPicture** [comment]
PR: #2359

**Comment by pippinsplugins** [comment]
Wonderful, thanks for tracking that down @DrewAPicture!
