### ISSUE TITLE
Add an option to delete payouts from the Payouts screen 

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2362]
Sometimes site administrators make a mistake when creating a payout. It would be great to have an option to delete certain payouts. 

Related ticket: https://secure.helpscout.net/conversation/394643515/62583/?folderId=634609.

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/498950424/73483?folderId=205524

**Comment by tubiz** [comment]
PR : #2507

**Comment by DrewAPicture** [comment]
Are we planning to also reverse the referrals that were marked paid when the payout was generated?

I think that the referrals being marked paid is probably the greater concern when somebody wants to reverse a payout being generated.

**Comment by michaelbeil** [comment]
I think that would be ideal.

**Comment by tubiz** [comment]
If a payout is deleted all the referrals in the payout that were marked paid will be marked unpaid.
