### ISSUE TITLE
Apple Pay support in WooCommerce Stripe Gateway add-on

### ISSUE THREAD

**Issue by yangkennyk** [AffiliateWP/AffiliateWP#2363]
Currently the plugin doesn't register referrals when apple pay is used with woo commerce.

**Comment by michaelbeil** [comment]
Hi @yangkennyk,

We are looking further into this issue. 

Feel free to open a support ticket here: https://AffiliateWP.com/support.

**Comment by michaelbeil** [comment]
Ticket link: https://secure.helpscout.net/conversation/419565909/0/?folderId=205527.

**Comment by gspice** [comment]
A test site has been setup for this.  Verified a referral is not created when using an affiliate link and a purchase is completed on Safari via Apple Pay.  Currently the AffiliateWP log shows:

```
2017-9-25 19:13:07 - Visit #2 recorded for affiliate #1 in track_visit()
2017-9-25 19:15:46 - Referral could not be retrieved during complete_referral(). Value given: 114
```

Please see this HS ticket for testing prep details and log in credentials to the test site:
https://secure.helpscout.net/conversation/422726950/65727/?folderId=1170842

**Comment by gspice** [comment]
another one:
https://secure.helpscout.net/conversation/444383606/68031?folderId=1170842

**Comment by yangkennyk** [comment]
is there any update on this?

**Comment by pippinsplugins** [comment]
@amdrew this is merged into `master`. Before I close it, though, could you please give `master` a quick test to confirm there are no issues introduced?

**Comment by amdrew** [comment]
Works for me!
