### ISSUE TITLE
Payout generation problems if database not in perfect condition

### ISSUE THREAD

**Issue by davefx** [AffiliateWP/AffiliateWP#2369]
We've detected problems while trying to generate payouts with the last version of AffiliateWP, in which the process never finished. 

After debugging them, we found the following problems:
- If the database has any referral assigned to affiliate_id=0, the process will never finish.
- If the database loses the current_count in the middle of the process, the step count will never be recovered.

**Comment by tubiz** [comment]
PR: #2667

**Comment by michaelbeil** [comment]
@tubiz what is the best way to test this? I guess, how do I make sure that this fixes the problem?

**Comment by tubiz** [comment]
@michaelbeil 

#### To Replicate
* Edit any unpaid referral in the database and set the `affiliate_id` to `0`
* Click on the `Generate Payout File` on the Referrals page
* The batch process to generate the payout file will never finish.

The fix will ensure that the generate payout batch process finish and not to generate any payout for any referral with the `afffiliate_id` set to `0`

**Comment by pippinsplugins** [comment]
Merged into 2.2!
