### ISSUE TITLE
Actually enforce only running pre_fetch() for batch processors on the first step

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2371]
Because of the changes made in #2358, we're now garbage collecting batch processes in the `init()` methods of each batch process. Except, I misremembered the logic and `init()` is actually run on every step. The whole "only on the first step" thing is actually what happens in the `pre_fetch()` method, and only if the pre-fetch data is already stored – it isn't enforced anywhere.

See #2367 for where this was reported against `Generate_Payouts`, but it applies to all of them.

**Comment by pippinsplugins** [comment]
@DrewAPicture let's go ahead and deploy 2.1.4.1 as soon as it's fixed.

**Comment by DrewAPicture** [comment]
PR: #2372
