### ISSUE TITLE
Integration: OptimizeMember - referral not created on paid membership level

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2374]
Support ticket that prompted my test:
https://secure.helpscout.net/conversation/426443907/66135/?folderId=1170842

Using our sandbox site that is already configured:
http://s14890.p27.sites.pressdns.com/optimize-press

Purchased the bronze level here:
http://s14890.p27.sites.pressdns.com/optimize-press/bronze-level-stripe-form/

Using affiliate id 3:
http://s14890.p27.sites.pressdns.com/optimize-press/bronze-level-stripe-form/?ref=3

Entered Stripe test credit card, account was created and 20.00 was charged but referral was not created.   Contents of the debug log:
```
2017-9-06 18:54:20 - Visit #8 recorded for affiliate #3 in track_visit()
2017-9-06 18:55:28 - OptimizeMember payment notification.
2017-9-06 18:55:28 - OptimizeMember hash verified.
2017-9-06 18:55:28 - OptimizeMember referral validation failed. Missing affiliate ID.
2017-9-06 18:55:29 - OptimizeMember set_referral_variable() ran.
2017-9-06 18:55:29 - OptimizeMember affiliate ID was found.
2017-9-06 18:55:29 - OptimizeMember custom variable set to s14890.p27.sites.pressdns.com|3
2017-9-06 18:55:42 - OptimizeMember payment notification.
2017-9-06 18:55:42 - OptimizeMember hash verified.
2017-9-06 18:55:42 - OptimizeMember referral validation failed. Missing affiliate ID.

**Comment by gspice** [comment]
Was able to test on the user's site.  They had Fallback Tracking enable , not sure why, I didn't see any jquery errors. I tested with that on a subscription and it created a referral, actually it created two - one at a zero amount and one at the correct amount.  Here are the log entries from that testing session:
```
2017-9-06 20:33:24 - OptimizeMember set_referral_variable() ran.
2017-9-06 20:33:24 - OptimizeMember set_referral_variable() ran.
2017-9-06 20:35:11 - OptimizeMember set_referral_variable() ran.
2017-9-06 20:35:11 - OptimizeMember affiliate ID was found.
2017-9-06 20:35:11 - OptimizeMember custom variable set to www.modestycouture.com|18
2017-9-06 20:35:11 - OptimizeMember set_referral_variable() ran.
2017-9-06 20:35:11 - OptimizeMember affiliate ID was found.
2017-9-06 20:35:11 - OptimizeMember custom variable set to www.modestycouture.com|18
2017-9-06 20:35:20 - OptimizeMember set_referral_variable() ran.
2017-9-06 20:35:20 - OptimizeMember set_referral_variable() ran.
2017-9-06 20:36:41 - OptimizeMember payment notification.
2017-9-06 20:36:41 - OptimizeMember hash invalid.
2017-9-06 20:36:42 - OptimizeMember payment notification.
2017-9-06 20:36:42 - OptimizeMember hash invalid.
2017-9-06 20:36:42 - OptimizeMember payment notification.
2017-9-06 20:36:42 - OptimizeMember hash invalid.
2017-9-06 20:36:43 - OptimizeMember payment notification.
2017-9-06 20:36:43 - OptimizeMember hash verified.
2017-9-06 20:36:43 - OptimizeMember referral validation passed.
2017-9-06 20:36:43 - Pending Referral #10 created successfully.
2017-9-06 20:36:43 - OptimizeMember pending referral created.
2017-9-06 20:36:43 - Referral retrieved successfully during complete_referral()
2017-9-06 20:36:43 - Referral #10 set to Unpaid successfully
2017-9-06 20:36:43 - OptimizeMember referral completed.
2017-9-06 20:36:43 - OptimizeMember referral validation failed. Missing affiliate ID.
2017-9-06 20:36:46 - OptimizeMember payment notification.
2017-9-06 20:36:46 - OptimizeMember hash invalid.
2017-9-06 20:36:47 - OptimizeMember payment notification.
2017-9-06 20:36:47 - OptimizeMember hash invalid.
2017-9-06 20:36:48 - OptimizeMember payment notification.
2017-9-06 20:36:48 - OptimizeMember hash verified.
2017-9-06 20:36:48 - OptimizeMember referral validation passed.
2017-9-06 20:36:48 - Pending Referral #11 created successfully.
2017-9-06 20:36:48 - OptimizeMember pending referral created.
2017-9-06 20:36:48 - Referral retrieved successfully during complete_referral()
2017-9-06 20:36:48 - Referral #11 set to Unpaid successfully
2017-9-06 20:36:48 - OptimizeMember referral completed.
2017-9-06 20:36:48 - OptimizeMember referral validation failed. Missing affiliate ID.

**Comment by pippinsplugins** [comment]
@ramiabraham could you dig into this?

**Comment by pippinsplugins** [comment]
@tubiz could you please look into this one?

**Comment by tubiz** [comment]
@pippinsplugins I will need a copy of the OptimizeMember plugin

**Comment by pippinsplugins** [comment]
https://www.dropbox.com/s/gs95100ic2dm4iq/optimizeMember.1.2.6.zip?dl=1

**Comment by tubiz** [comment]
Seen. Thanks.

**Comment by tubiz** [comment]
@pippinsplugins I will also need the OptimizePress plugin.

**Comment by amdrew** [comment]
@tubiz Sent you an email with link

**Comment by tubiz** [comment]
@amdrew I got the email. Thanks.

**Comment by tubiz** [comment]
PR: #2611 

`affiliate_wp()->tracking->get_affiliate_id()` always return false when a signup url with the referral variable `http://affwpdev.local/optimizepress/bronze-level-plan/?ref=2` is visited directed when the fallback referral tracking method is enabled.

The OptimizeMember custom variable (affiliate id) is set `set_referral_variable()` when the signup form is displayed but `$_COOKIE['affwp_ref']` isn't available until the next request (page load) so `affiliate_wp()->tracking->get_affiliate_id()` will return false. So the referral won't be created using the `generate_referral()` as the affiliate id isn't set.

This will also be the case in the s2Member integration as they both use the same approach to track referrals.

Also I am not sure if it is a good idea to access a cookie value immediately after setting it.

**Comment by pippinsplugins** [comment]
Well done tracking that down @tubiz! I would like to see this tackled in a slightly different manner though.

The base integration class should not ever have any code in it specific to any integration. It is base functionality only and all integration-specific functionality needs to be in the integration classes.

Let's do this:

1. Update the base class with `do_action` calls in in `set_visit_id()`, `set_affiliate_id()`, and `set_campaign()`. We can name this accordingly, like `do_action( 'affwp_tracking_set_visit_id`, $visit_id, $this )`
2. Update `optimizemember` and `s2member` integrations to include an `add_action` on each of the new actions, i.e. `affwp_tracking_set_visit_id` that handles setting the cookie value.

**Comment by pippinsplugins** [comment]
@tubiz thanks for the changes.

@gspice could you give this a test please?

**Comment by gspice** [comment]
OptimizeMember tests were successful with **Fallback Tracking** off and also turned on - a referral was created correctly in each instance.  

I'm still trying to test s2Member but since that was not part of the bug, I would say this can be closed.

**Comment by pippinsplugins** [comment]
@gspice They work the same way so I'd say it's safe to assume both are fixed, thanks!
