### ISSUE TITLE
EDD Integration: Add price option to referral description

### ISSUE THREAD

**Issue by flowdee** [AffiliateWP/AffiliateWP#2380]
Right now only the download title will be taken for the referral description. 

It would be very handy, if (in case EDD SL is being used) the price option would be added to the description as well. e.g:

- My download - Option 1
- My download (Option 1)

This way affilates get better understanding, about where the referral amount comes from.

**Comment by pippinsplugins** [comment]
PR ready for testing.

**Comment by amdrew** [comment]
@pippinsplugins It works!
