### ISSUE TITLE
Add Bitcoin currency

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2382]
A user has requested we support the Bitcoin currency.

**Comment by pippinsplugins** [comment]
This requires more than just registering the currency code. We also have to account for 8 decimal places in our sanitization and formatting functions since BitCoin goes to 8 decimal places.

**Comment by michaelbeil** [comment]
I thought we already resolved that here? https://github.com/AffiliateWP/AffiliateWP/issues/1083

**Comment by pippinsplugins** [comment]
@michaelbeil we made it possible to add decimal places. Now we need to actually set the decimal places to `8` through `affwp_decimal_count` when `BitCoin` is selected as the currency

**Comment by michaelbeil** [comment]
Oh, alright.

**Comment by jabaco** [comment]
Hello, is the bitcoin integration completed? I recently purchase the plugin but it seems I cannot chose bitcoin as the currency.. Thanks

**Comment by michaelbeil** [comment]
It is not, yet.

**Comment by jabaco** [comment]
Any estimated time? I really need this functionality since my business is based on Bitcoin... Also, is it possible to show referral amount with more than 2 decimals right now with other currencies?

**Comment by michaelbeil** [comment]
We do not have a current ETA. We made it possible to add decimal places. This would require custom development to implement, currently: http://affiliatewp.com/​consultants​. See #1083.

**Comment by jabaco** [comment]
That url is not working...

**Comment by jabaco** [comment]
Is it possible that you point me to the files and code I have to modify in order to add 8 decimals? Please I just purchase the pro version of the plugin and would not be happy to pay for custom development for something that you already have done and can share the code.

**Comment by michaelbeil** [comment]
As I mentioned before, the changes are in this link: https://github.com/AffiliateWP/AffiliateWP/issues/1083.

**Comment by jabaco** [comment]
my bad... I just saw them, applied them to my site and it is working!

**Comment by michaelbeil** [comment]
Okay, great!

**Comment by jabaco** [comment]
hello, it has been another whole month, 3 updates and I do not see the implementation of bitcoin decimals... This is very frustrating since every time there is an update, I have to manually update core files. This is a really basic milestone for you to implement and will be of great benefit to all your customers like me that are using bitcoin as payment gateway.

**Comment by DrewAPicture** [comment]
Hi @jabaco, this issue milestoned for the next major release, 2.2, which we don't have an ETA for yet, but we anticipate that happening in the next few months.

That said, we may be able to get to it sooner, but 2.2 is the current goal. Thanks for your patience.

**Comment by djcrypto75** [comment]
I hope this will be in this release. I agree with @jabaco here.

**Comment by tubiz** [comment]
PR: #2497

**Comment by pippinsplugins** [comment]
PR looks good at first glance!

@tubiz would you be able to add a unit test for it?

**Comment by tubiz** [comment]
@pippinsplugins my unit testing skill is not up to par 🙈 but I will try.

**Comment by pippinsplugins** [comment]
@tubiz here's a guide I wrote: https://pippinsplugins.com/series/unit-tests-wordpress-plugins/

Tests are not required, just really nice to have :)

**Comment by tubiz** [comment]
Thanks, I will read the guide. I guess it is time for me to learn unit testing.

**Comment by DrewAPicture** [comment]
@tubiz If it helps, take a look at the two tests we already have for `affwp_get_decimal_count()`, particularly `test_filtered_get_decimal_count_should_return_filtered()`.

To test the bitcoin case, you'll just want to temporarily filter `affwp_currency` with the bitcoin slug inside the test method and then remove the filter again after. Happy to help you out if you get stuck!

**Comment by tubiz** [comment]
Unit test added.

**Comment by pippinsplugins** [comment]
Tests are passing, merging!
