### ISSUE TITLE
Invalid affiliate link should throw a notice 

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2390]
As brought up here: https://secure.helpscout.net/conversation/435482089/67089/?folderId=634609, if anyone enters an affiliate that doesn't exist onto the end of the referral variable, no notice is given. I think it would be good to 404 or give a notice that the affiliate doesn't exist.

**Comment by pippinsplugins** [comment]
I disagree. There's really very little value in that and it simply provides a potential information disclosure issue that would allow someone to brute force a site to determine all of the valid affiliate IDs.

**Comment by michaelbeil** [comment]
I didn't think of that.That is very true.
