### ISSUE TITLE
AffiliateWP metabox does not show on a Give donation form 

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2393]
When testing Give locally, I don't see the AffiliateWP metabox when I go to edit the donation form. It appears like we need to update our Give integration.

**Comment by DrewAPicture** [comment]
Looks like this has been broken since Give 1.8. They [deprecated use of CMB2](https://givewp.com/give-version-1-8/) in favor of their own settings API. Example here: https://github.com/WordImpress/Give-Settings-API-Example

**Comment by michaelbeil** [comment]
Should we release a fix for this in an upcoming release?

**Comment by pippinsplugins** [comment]
Yes let's go ahead and fix this for 2.1.6.

**Comment by ramiabraham** [comment]
Added a PR: https://github.com/AffiliateWP/AffiliateWP/pull/2400

Presently finishing up the rate calc. Can we add a param for the rate in the base class `calculate_referral_amount` method? It'd add a param for `$rate`, then just a ternary or something:

```php
if ( ! empty( $product_id ) ) {
			$rate = ! empty( $rate ) ? $rate : $this->get_product_rate( $product_id, $args = array( 'reference' => $reference, 'affiliate_id' => $affiliate_id ) );
		}
```

**Comment by pippinsplugins** [comment]
@ramiabraham one minor change needed. See review on PR>

**Comment by pippinsplugins** [comment]
@amdrew could you give this a test today?

**Comment by michaelbeil** [comment]
This PR fixes the metabox box issue for me.

**Comment by amdrew** [comment]
@pippinsplugins Works for me too
