### ISSUE TITLE
Import affiliates from Affwp exported affiliates csv file hangs, database not accessible afterwards.

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2395]
Reported on HS ticket:
https://secure.helpscout.net/conversation/438301151/67355/?folderId=205527

## Steps to reproduce:

* Export by going to:  _Affiliates > Tools > Export/Import > Export Affiliates_
* Went to another site with AffiliateWP:  _Affiliates > Tools > Export/Import > Import Affiliates_, select the exported file you created in first step, click **Import CSV**
* The file loads showing the field mapping, accept the default mapping, click on **Process Import** button.

It never appears to complete, processing spinner keeps going:
![process-import-spinning](https://user-images.githubusercontent.com/3018245/30890528-61835d7c-a2e2-11e7-9b12-68b287bee99c.png)

If I close out of the browser, when I try to access the site receive error  **Error establishing a database connection.**

**Comment by ramiabraham** [comment]
Confirmed here on an export of randomly-generated affiliates, as well as the customer-provided .csv file. 

Logs indicate MySQL a syntax error in `Affiliate_WP_DB::update()` when updating the `wp_affiliate_wp_affiliates` table, called via the `wp_ajax_process_batch_request` action, by `AffWP\Utils\Batch_Process\Import_Affiliates->process_step()`:

```php
WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `affiliate_id` = '7'' at line 1 for query UPDATE `wp_affiliate_wp_affiliates` SET  WHERE `affiliate_id` = '7' made by do_action('wp_ajax_process_batch_request'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, affwp_process_batch_request, AffWP\Utils\Batch_Process\Import_Affiliates->process_step, Affiliate_WP_DB->update
```

- Presently, I can see no syntax error in that method 😞

**Comment by michaelbeil** [comment]
Another user with this issue: https://secure.helpscout.net/conversation/443448559/67906/?folderId=205524.

**Comment by DrewAPicture** [comment]
PR: #2403 

Looks like the issue was that in some cases, `$this->batch_id` wasn't set, and in lieu of checking that it was set, we were globally deleting options. Baddddd idea. I've gone ahead and adjusted all batch processes to directly pass the batch ID via the Ajax handler, as well as double check that the REGEXP pattern contains a batch ID before proceeding.

**Comment by ramiabraham** [comment]
@AffiliateWP/core Works great here, import completed successfully.

**Comment by gspice** [comment]
Tested with user's CSV file and it imported successfully!
