### ISSUE TITLE
Performance: 260KB of autoloaded options data for available plugin updates

### ISSUE THREAD

**Issue by DavidAnderson684** [AffiliateWP/AffiliateWP#2399]
I did an analysis on updraftplus.com, as to how much data is autoloaded from the options table, using this query:

```
SELECT 'autoloaded data in KiB' as name, ROUND(SUM(LENGTH(option_value))/ 1024) as value FROM wp_options WHERE autoload='yes' UNION SELECT 'autoloaded data count', count(*) FROM wp_options WHERE autoload='yes' UNION (SELECT option_name, length(option_value) FROM wp_options WHERE autoload='yes' ORDER BY length(option_value) DESC LIMIT 10);
```

The result was that there's just over 1.0MB of it.... but around 25% of that is information about available AffiliateWP updates. That is to say, about 250KB of auto-loaded information on updates to the Affiliates-WP plugin for every page load.

The two option names, and number of bytes for this are:

```
f48ee71c3793521b9e36eefeebf9aab1                 139014
edd_api_request_f48ee71c3793521b9e36eefeebf9aab1 137670 
```

The first chunk of data for the first of those is:

```
a:2:{s:7:"timeout";i:1506514910;s:5:"value";s:138957:"{"new_version":"2.1.5","stable_version":"2.1.5","name":"AffiliateWP","slug":"affiliate-wp","url":"https:\\/\\/affiliatewp.com\\/add-ons\\/%download_category%\\/affiliatewp\\/?changelog=1","last_updated":"2017-09-22 15:50:14","homepage":"https:\\/\\/affiliatewp.com\\/add-ons\\/%download_category%\\/affiliatewp\\/","package":"","download_link":"","sections":{"description":"<p>AffiliateWP aims to be the easiest and best affiliate management plugin for WordPress.<br \\/>\\nHigher Visibility<br \\/>\\nAffiliates constantly promoting your products drastically improves yo
```

The other looks to be identical, on a quick look.

Given the nature of this data, there's no need for it to be auto-loaded, and at 250KB for every WP load, it'd be good to be rid of it.

**Comment by DavidAnderson684** [comment]
Just to be clear - I manually set the autoload column for these rows to `no` on this particular site. But it'd be nice to know it won't come back, and for everyone else to have the same benefit!

**Comment by pippinsplugins** [comment]
@DavidAnderson684 You're absolutely right!

We need to be setting `autoload` to `no` in `set_version_info_cache()`.

**Comment by DrewAPicture** [comment]
This should be mitigated by #2412, going out in 2.1.6.1.
