### ISSUE TITLE
Use rel="nofollow" on affiliate links

### ISSUE THREAD

**Issue by dustinatx** [AffiliateWP/AffiliateWP#2401]
To meet Google's quality guidelines the "copy and paste" links in the Creatives section of the Affiliate Area should use the rel="nofollow" attribute. It is possible for both the linked and linking site to be penalized by Google for using affiliate links without the rel="nofollow" attribute.

https://support.google.com/webmasters/answer/66356?hl=en&rd=1

**Comment by amdrew** [comment]
Thanks @dustinatx! I'm going to close this since we already have an open issue for this: https://github.com/AffiliateWP/AffiliateWP/issues/1155
