### ISSUE TITLE
Improve UI for disabling specific email notifications

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2405]
In 2.2 we're adding options to disable specific emails (https://github.com/AffiliateWP/AffiliateWP/issues/1923). 

Currently it looks like the following:

<img width="859" alt="screenshot 2017-10-05 11 30 07" src="https://user-images.githubusercontent.com/52581/31202956-6ae94788-a9c1-11e7-9f9a-fe11b2b63656.png">

Since all these checkbox options are related, it would make more sense to group them like we have done for the `Integrations` tab and also the "Required Registration Fields" options on the `General` tab.

It look more like this, taking up far less space.

<img width="858" alt="screenshot 2017-10-05 11 35 00" src="https://user-images.githubusercontent.com/52581/31203034-b15a2dcc-a9c1-11e7-8a19-5e6fa18802d3.png">

The descriptions could also be improved. As an example, "Emails" Vs "Email Notifications" and als the description below the checkboxes, this was just a quick example.

Additionally, when the `Disable All Emails` checkbox is enabled above, these options should not be shown. There would never be an instance where you would disable all emails, and then disable each specific email.

**Comment by michaelbeil** [comment]
Ticket: https://secure.helpscout.net/conversation/469092602/70582?folderId=205529.

**Comment by amdrew** [comment]
@pippinsplugins Do you agree on the above?

**Comment by pippinsplugins** [comment]
Yes.

**Comment by amdrew** [comment]
@AffiliateWP/core Ready for testing. PR: https://github.com/AffiliateWP/AffiliateWP/pull/2522

**Comment by pippinsplugins** [comment]
Oops, need to go a bit further.

`New referral emails` currently refers to email notifications to affiliates, but we also need to have an option for disabling new referral notifications to site admins, sent through `affwp_notify_admin_on_new_referral()`.

We also need to go a bit further and remove the profile field in the Affiliate Area settings tab that permits affiliates to enable/disable email notifications. If notifications are disabled in the admin, affiliates should not see the option to enable emails.

**Comment by pippinsplugins** [comment]
Oh one more. We already have an option for enabling / disabling referral notifications for admins, `admin_referral_notifications`. This will need to be moved into the multi-check list and an upgrade routine added to migrate the stored value.

**Comment by amdrew** [comment]
Closing this in favor of #948, where the work has been carried out.
