### ISSUE TITLE
Load required scripts for "Graphs" tab when it is the "active" tab

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2408]
This issue was originally opened on Affiliate Area Tabs (https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/issues/45), though it's really a core issue now since tabs will have priorities. It will need to be fixed at the same time as #1693.

We need to update our conditional check to make sure the required scripts for the "graphs" tab are loaded when it is the active tab: https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/scripts.php#L158-L161

If not it will produce a JS error:

```
TypeError: $(...).datepicker is not a function  frontend.js:
```

**Comment by ramiabraham** [comment]
@amdrew The datepicker is loading for me on #1693 and `master`, no js errors generated. Should we restrict `jquery-ui-datepicker` and `jquery-ui-css` to load only for the graphs tab, when active?

**Comment by pippinsplugins** [comment]
@ramiabraham yeah I think limiting to the graphs tab will be fine.

**Comment by amdrew** [comment]
@ramiabraham Sorry, I should have clarified from the previous issue (https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/issues/45), it's when it is the first tab. In any case, as long as we only load the scripts required for the graphs tab, when the graphs tab is active, we should be fine.

**Comment by ramiabraham** [comment]
@amdrew Added a PR: https://github.com/AffiliateWP/AffiliateWP/pull/2409

**Comment by amdrew** [comment]
@ramiabraham This is perfect

**Comment by ramiabraham** [comment]
@amdrew Ok to merge?

**Comment by amdrew** [comment]
@ramiabraham Can you merge the patch for this into #1693 so we can test it altogether? Should be good to go but want to test everything together all at once that's related to tabs before merging into master.

**Comment by ramiabraham** [comment]
Done!

**Comment by amdrew** [comment]
This can be closed
