### ISSUE TITLE
WooCommerce:  add link in order detail to go directly to Referral edit screen

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2411]
From support ticket:
https://secure.helpscout.net/conversation/450483126/68651?folderId=1170842

>Not sure if this possible with Woocommerce order notes, but if you could make the referral number clickable to take you right into the referral edit screen that would be awesome.

>If that is not possible, maybe if somewhere in the order info near the top you could add link to edit the referral that would be helpful when that is needed to save copying it, going to the referrals section and then pasting it while remembering to enter the correct search variable like "ref:", etc.

**Comment by pippinsplugins** [comment]
PR is ready for testing from @tubiz!

**Comment by tubiz** [comment]
PR: #2498

![woocommerce order note](https://user-images.githubusercontent.com/602184/34546498-a5edcf96-f10d-11e7-9f28-7a998077149b.png)

**Comment by pippinsplugins** [comment]
Works great, merged!
