### ISSUE TITLE
Update to v1.6.15 of the EDD_SL_Plugin_Updater class

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2412]
Customer has reported a very large autoloaded option stemming from AffWP (the largest in his `wp_options` table). https://secure.helpscout.net/conversation/452120717/68799/

Turns out it's the response from SL and contains basically most of the changelog. @cklosowski has filed a ticket to slim down the response ([#SL1189](https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1189)), and he also mentioned that updating to the latest version of the updater class would result in no longer autoloading the option in question.

Attached PR updates the `EDD_SLI_Plugin_Updater` class (renamed to `AffWP_Plugin_Updater` in AffiliateWP) to v1.6.15.

**Comment by DrewAPicture** [comment]
PR: #2413

**Comment by pippinsplugins** [comment]
PR looks good.
