### ISSUE TITLE
AffiliateWP panel empty on WooCommerce product page

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2414]
When the `Facebook for WooCommerce` plugin (https://woocommerce.com/products/facebook/) is installed and configured, the AffiliateWP panel on a WooCommerce product's screen is empty:

<img width="987" alt="screenshot 2017-10-20 11 17 56" src="https://user-images.githubusercontent.com/52581/31796967-5afccb56-b588-11e7-8c2e-7cdc55adf607.png">

I don't see anything wrong with the way that plugin is adding its panel:

```
add_action('woocommerce_product_data_panels',
          array($this, 'fb_new_product_tab_content' ));
```

We however add ours with a priority of `100`:
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-woocommerce.php#L46

```
add_action( 'woocommerce_product_data_panels', array( $this, 'product_settings' ), 100 );
```

I can't see why we ever needed to use a high priority so I propose we simply remove it to get our panel showing again. 

<img width="987" alt="screenshot 2017-10-20 11 17 35" src="https://user-images.githubusercontent.com/52581/31797079-e701e9ba-b588-11e7-9ec9-2cda316e01d6.png">

<img width="975" alt="screenshot 2017-10-20 11 22 09" src="https://user-images.githubusercontent.com/52581/31797085-ed5c56c4-b588-11e7-9b3c-ddbea4344ed6.png">

**Comment by DrewAPicture** [comment]
Let's include this with 2.1.6.1.
