### ISSUE TITLE
After uninstall database tables is not removed

### ISSUE THREAD

**Issue by macagoraga** [AffiliateWP/AffiliateWP#2418]
It's a WP Multisite, the plugin was activated for 1 site.
After delete the plugin, the database table was not removed.

**Comment by DrewAPicture** [comment]
Hi @macagoraga, thanks for the report. What version of AffiliateWP did you have installed?

**Comment by macagoraga** [comment]
Last version just downloaded from here an hour ago, I see that it's 2.1.6.1
Also latest WP version, 4.8.2

**Comment by pippinsplugins** [comment]
@macagoraga in Affiliates > Settings > Misc, did you have the option to remove data enabled? The data will only be deleted if that option is checked.

**Comment by macagoraga** [comment]
I got the point.
I did not change that setting. So if default settings it's disabled, then most probably for this reason it's not deleted.
Thanks
