### ISSUE TITLE
reference of hooks

### ISSUE THREAD

**Issue by kamov** [AffiliateWP/AffiliateWP#2422]
Where I can find reference of hooks?

**Comment by michaelbeil** [comment]
There are hooks interspersed throughout our source code. What particular hook are you looking for?

**Comment by kamov** [comment]
Thanks for reply.
I need to hook when specific referral ID it's saved on cookie.
I can give more details if required.

**Comment by michaelbeil** [comment]
Have you searched here? https://github.com/AffiliateWP/AffiliateWP/search?utf8=%E2%9C%93&q=hook&type=

**Comment by kamov** [comment]
Nope... Let me check.
It would be useful to have something like
https://docs.woocommerce.com/wc-apidocs/hook-docs.html

**Comment by michaelbeil** [comment]
Thanks for the suggestion. We do hope to have a reference in the future.
