### ISSUE TITLE
Admin - Referrals - WooCommerce: referral reference entry shows actual order # and not sequential if WC Sequential Order Numbers is active

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2424]
Testing with:
AffiliateWP core:  2.1.6.1
WooCommerce: 3.2.1
WooCommerce Sequential Order Numbers:  1.8.2

Referrals created will contain the "real" order number and not the sequential WooCommerce order number in the referral's _reference_ column.  This makes it tricky when adding referrals manually. 
 
Would prefer to support the sequential order number/redirect.

**Comment by pippinsplugins** [comment]
@gspice ready for testing!

This should work properly with the free and pro version of Sequential Order Numbers.

**Comment by gspice** [comment]
@pippinsplugins  Works great!  Corrects all previous referrals as well, meaning those that showed the incorrect order number show the correct, sequential order number when the updated AffiliateWP is installed.

**Comment by djcrypto75** [comment]
This shows perfectly fine in backend of affiliatewp under "referrals" and Reference. 
In Frontend it do not show correct. It shows the Order ID and not Order Number.
