### ISSUE TITLE
WooCommerce: when a referral gets updated, no note is generated

### ISSUE THREAD

**Issue by davefx** [AffiliateWP/AffiliateWP#2426]
When a referral gets updated, no note gets generated, showing apparently wrong information in the order.

**Comment by DrewAPicture** [comment]
@davefx I've submitted an alternative PR that I think provides the solution you're looking for: #2482.

In your PR, you were only generating an order note in a set of very specific circumstances in a place that would only fire while updating an existing referral in an existing order _during checkout_.

**Comment by amdrew** [comment]
@DrewAPicture Works for me! 👍 

old referral

<img width="287" alt="screenshot 2017-12-14 11 45 37" src="https://user-images.githubusercontent.com/52581/33966403-5a4b6dd6-e0c4-11e7-98b1-b3b6b175d6f2.png">


after updating amount on referral


<img width="297" alt="screenshot 2017-12-14 11 43 35" src="https://user-images.githubusercontent.com/52581/33966379-43f3a6f2-e0c4-11e7-89e5-5bcf23e4c54d.png">
