### ISSUE TITLE
Add filter to affwp_add_affiliate() to make it easier to add a new WP user account

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2442]
`affwp_add_affiliate()` creates a new WordPress user account when an email is passed in. 

I propose we add a filter here:
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/affiliate-functions.php#L1167-L1170

This would allow a developer greater flexibility over what gets added to the new user's account. To achieve this currently you'd have to update the new WP user account _after_ it has been created using `do_action( 'affwp_insert_affiliate', $add, $args );`. This seems like an unneccessary step.

**Comment by pippinsplugins** [comment]
No objections here!

**Comment by DrewAPicture** [comment]
I'm on board with this, maybe just a filter on the args for `wp_insert_user()`?

**Comment by amdrew** [comment]
Yep

**Comment by DrewAPicture** [comment]
PR: #2445

**Comment by amdrew** [comment]
@DrewAPicture Looks great
