### ISSUE TITLE
Consider changing description for {name} email tag

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2443]
The current description for the `{name}` email tag is

> {name} - The full name of the affiliate

As we know, this is actually the WP display name which could be anything, not necessarily the full name of the affiliate.

We should make it clearer, something like:

> {name} - The display name of the affiliate. This can be configured by the affiliate from the "Display name publicly as" setting of their WordPress user profile

^ perhaps a bit too long.

**Comment by pippinsplugins** [comment]
How about:

>>>{name} - The display name of the affiliate, as set on the affiliate's user profile.

**Comment by amdrew** [comment]
👍
