### ISSUE TITLE
Direct link tracking

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#245]
A customer has expressed interest in this feature that post affiliate pro has called direct linking:

http://support.qualityunit.com/991472-DirectLink-tracking

**Comment by ehrig** [comment]
Thanks @sumobi for making this public. I would love to switch to AffiliateWP, as PAP is a real pain to look at and interact with, but their Direct Links feature is amazing. Any chance that you can add this to AffiliateWP? I am happy to chip in, if that helps.

**Comment by kefrengg** [comment]
I'm looking for a plugin and this is the only feature that make me think twice…otherwise I would have bought it right now! Is this feature added already? I'm looking for a way to have affiliates link to any page + SEO.

**Comment by sumobi** [comment]
@ehrig @kefrengg We're definitely considering it! :+1:

**Comment by ehrig** [comment]
thanks @sumobi, please let us know here once this feature is part of AffiliateWP.

**Comment by sumobi** [comment]
https://secure.helpscout.net/conversation/216924676/36477/?folderId=205531

**Comment by sumobi** [comment]
@ehrig @kefrengg We now have a Direct Link Tracking pro add-on for AffiliateWP: https://affiliatewp.com/addons/direct-link-tracking/
