### ISSUE TITLE
Create an administrative option to automatically turn on referral notifications

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2457]
It was brought up by customer to create an administrative option that automatically turns on referral notifications for all affiliates.

Ticket: https://secure.helpscout.net/conversation/467597177/0/?folderId=205529.

**Comment by amdrew** [comment]
@michaelbeil Like https://github.com/AffiliateWP/AffiliateWP/issues/1960?

**Comment by michaelbeil** [comment]
Yes, I totally did not see that. Closing in favor of #1960.
