### ISSUE TITLE
Visit recount tool not working

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#2458]
At some point recently the recount stats tool for visits has stopped working. Actually, all of the recount tools are broken because the search fields isn't working.

Even when the search field is working, the actual recount fails to properly set the visits count on the affiliate.

When attempting to search for an affiliate, no results are found (affects all recount types). When processing a recount (if manually entering a username or email), the recount appears to succeed but no stats are updated.

**Comment by DrewAPicture** [comment]
The attached PR: #2461 fixes two bugs:

1. No status was being passed with the autocomplete so no affiliate users were being pulled
2. There was a problem with how affiliate totals were being compiled for recounting visits

I tested all four recount options on a single affiliate (finding and fixing the issue with recounting visits in the process), as well as for global recounts and things seems to be working as expected, at least in my testing.

The way I tested single affiliate was to generate a new affiliate with visits and referrals and then manually modify the `amount` column for a referral or two for paid earnings, changed referral `status` from paid to unpaid for unpaid earnings, deleted a couple of referrals for referrals, and deleted a couple of visits for visits.

```sh
wp affwp affiliate generate --count=1 --visits=10 --referrals=10
```

For testing globally, I basically did the above for multiple affiliates.

```sh
wp affwp affiliate generate --count=5 --visits=5 --referrals=5
```

**Comment by DrewAPicture** [comment]
The attached PR: #2461 fixes two bugs:

1. No status was being passed with the autocomplete so no affiliate users were being pulled
2. There was a problem with how affiliate totals were being compiled for recounting visits

I tested all four recount options on a single affiliate (finding and fixing the issue with recounting visits in the process), as well as for global recounts and things seems to be working as expected, at least in my testing.

The way I tested single affiliate was to generate a new affiliate with visits and referrals and then:
* manually modify the `amount` column for a referral or two for paid earnings
* manually changed referral `status` from paid to unpaid for unpaid earnings
* manually deleted a couple of referrals for referrals
* manually deleted a couple of visits for visits.

Note that these "change" operations need to happen manually to prevent core from updating totals during CRUD operations through AffWP APIs. If you don't have Sequel Pro or phpmyadmin or some other db software, you can do it via the mysql command line but you should really invest in something to make your life a whole lot easier ;-)

**Generate a single affiliate with visits and referrals** ([affiliatewp-wp-cli-generator](http://github.com/AffiliateWP/affiliatewp-wp-cli-generator))

```sh
$ wp affwp affiliate generate --count=1 --visits=10 --referrals=10
Generating 1 user(s) for affiliates  100% [====================================================================================================================================================] 0:00 / 0:00
Generating 1 affiliate(s)  100% [==============================================================================================================================================================] 0:00 / 0:00
Generating 10 referral(s) for affiliate #145408  100% [========================================================================================================================================] 0:00 / 0:00
Generating 10 unconverted visit(s) for affiliate #145408  100% [===============================================================================================================================] 0:00 / 0:00
```

**Retrieve the user_login**

You can use the affiliate ID from the command response to retrieve the username (for autocomplete testing):

```sh
$ wp affwp affiliate list --affiliate_id=145408
+--------+------+-----------------------+---------+------+------------+--------+----------+-----------------+-----------+--------+-----------------+
| ID     | name | user_login            | user_id | rate | rate_type  | status | earnings | unpaid_earnings | referrals | visits | date_registered |
+--------+------+-----------------------+---------+------+------------+--------+----------+-----------------+-----------+--------+-----------------+
| 145408 |      | affwp_user_3626_56792 | 63860   | 20%  | percentage | active | $80.25   | 0               | 10        | 10     | Nov 18, 2017    |
+--------+------+-----------------------+---------+------+------------+--------+----------+-----------------+-----------+--------+-----------------+
```

For testing globally, I basically did the above for multiple affiliates before running the recount tool for all four options again.
