### ISSUE TITLE
Integration with ninja form doesnt send referrals to the referral area in the plugin

### ISSUE THREAD

**Issue by felipevc13** [AffiliateWP/AffiliateWP#2464]
Integration with ninja form doesnt send referrals to the referral area in the plugin. The affiliate complete and submit the form but no referral appears on the referral list.

**Comment by felipevc13** [comment]
![add referral](https://user-images.githubusercontent.com/25945473/33129625-a993e430-cf77-11e7-9f10-a210dc5a9491.PNG)

**Comment by felipevc13** [comment]
i Add Referral but nothing happened

**Comment by felipevc13** [comment]
I've already tried with the contact 7 plugin and nothing too. The referrals doesnt appears in the referral area.

Im testing before buying the plugin, i need to buy first to have this functionality?

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://affiliatewp.com/support

we use GitHub for development tracking only.

Note: we can only provide support to paying customers.
