### ISSUE TITLE
EDD: Referral amounts do not take negative fees into consideration

### ISSUE THREAD

**Issue by cklosowski** [AffiliateWP/AffiliateWP#2466]
When using EDD with Discounts Pro, if a purchase occurs with a discount provided via Discounts Pro (applied as a negative fee), the affiliate referral is based off the item base price and discounts via codes, but not negative fees.

This hit me on Post Promoter Pro.

Payment Items:
<img width="955" alt="screen shot 2017-11-27 at 6 32 23 pm" src="https://user-images.githubusercontent.com/1390124/33298093-b559c4e6-d3a1-11e7-8352-744530e87c52.png">

Discounts (25% BFCM2017) code:
<img width="283" alt="screen shot 2017-11-27 at 6 32 29 pm" src="https://user-images.githubusercontent.com/1390124/33298098-bb096252-d3a1-11e7-99e3-9a3cd151640c.png">

AffiliateWP awarded a `$64.35` referral, based on the item total of `$321.75`, but really the end result of the purchase was a total of `$221.75` and an expected referral of `$44.35`

**Comment by tubiz** [comment]
PR: #2502

**Comment by pippinsplugins** [comment]
PR looks good, merged.
