### ISSUE TITLE
RCP: Free trial period should award a $0 referral

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2467]
At this time, a free trial for a subscription purchase awards a referral (based on the full product price instead of the $0 free trial transaction) to the referring affiliate. I think we should adjust the referral awarded when there is a free trial period, so that it becomes a $0 referral if a referral rate type of percentage is selected.

**Comment by pippinsplugins** [comment]
@mindctrl or @nosegraze could one of you assist in resolving this?

**Comment by gspice** [comment]
Above from HS ticket:  
https://secure.helpscout.net/conversation/476110902/71528?folderId=205527

Confirmed the issue using sandbox RCP site: http://s14890.p27.sites.pressdns.com/rcp
* RCP version: 2.9.6
* Affwp version:  2.1.8
* Created subscription with a 5 day free trial for 20.00 for 60 days duration.
* Referral was created for $10.00 (50% default ref rate on site) when I expected it to create a 0.00 amount referral. 

http://s14890.p27.sites.pressdns.com/rcp/wp-admin/admin.php?page=affiliate-wp-referrals

**Comment by nosegraze** [comment]
I'll look into this.

**Comment by nosegraze** [comment]
Haven't tested this yet but I think it should do the trick: #2468

**Comment by mindctrl** [comment]
That looks right for the initial referral, but I _think_ this means referring affiliates will not get credit when trial memberships go paid unless the site is running the Recurring Referrals add-on. Is that right?

**Comment by michaelbeil** [comment]
The initial referral was recorded correctly:http://beil.io/QKSOu.

John, when a trial membership goes paid unless the site is running the Recurring Referrals add-on, the affiliate will not get credit.

**Comment by pippinsplugins** [comment]
@mindctrl while it is perhaps unexpected behavior, that's the consistent behavior across all integrations at the moment.

**Comment by pippinsplugins** [comment]
@gspice merged into `master`. Would you please give it a quick test before we close this out?

**Comment by gspice** [comment]
Re-tested on RCP sandbox site: http://s14890.p27.sites.pressdns.com/rcp and it correctly created a zero amount referral for the affiliate tracked 👍

**Comment by pippinsplugins** [comment]
:+1:
