### ISSUE TITLE
Add rest_id fields to core objects, date and status to REST consumers

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2470]
I'd like to propose that we introduce a new `rest_id` field for each of the core objects, as well as `date` and `status` fields for the REST Consumer object. The `rest_id` field would be of type string and leveraged by as-yet undeveloped REST API-based pro-addons. I've attached a PR that implements these fields and their corresponding tests, targeted at the 2.2 release.

This would also cover the proposed consumer `date` field in #2455

**Comment by DrewAPicture** [comment]
It should be noted that the PR also actively locks down payout-related actions and screens if the current user doesn't have the `manage_payouts` capability – something we should realistically do for the other capabilities at some point.

**Comment by pippinsplugins** [comment]
@DrewAPicture could you take a few moments to resolve the merge conflicts here?

**Comment by DrewAPicture** [comment]
@pippinsplugins Fixed merge conflicts in 7 files and updated versions for stuff getting introduced from 2.2 to 2.2.2. Also renamed what _was_ `v22_upgrades()` in the PR to `v222_upgrades()` and added the new conditional to fire it.

**Comment by DrewAPicture** [comment]
Oh, and I also updated the base branch for the PR to `master` from `release/2.2`.

**Comment by pippinsplugins** [comment]
@DrewAPicture looking at this now I don't think I understand the use case for it. Could you tell me a hypothetical use case?

**Comment by DrewAPicture** [comment]
The intention was to have a ID-like field set aside for use over REST
between external sites/APIs to interact with core AffiliateWP objects and
have a place to store 1:1 or even 1:many connections, which is why they are
defined as strings.

I anticipated the need to store more than just a remote object id, perhaps
also contextual pointers to tie that id to a specific external site or API
identifier.

**Comment by DrewAPicture** [comment]
For example, say you have a remote API that you want to "tie" a local object to, you might update the rest_id for the local object to include the remote ID and some contextual information about that remote service, i.e. "1:SomeRegisteredAPI".

**Comment by DrewAPicture** [comment]
The addition of the new field doesn't do anything on it's own, but it certainly opens the door for some interesting first-hand or third-party add-ons to build out their own "registries" to interact with local objects. AffWP would simply provide a connection point and minimal API for interacting with that information.

**Comment by pippinsplugins** [comment]
Whoops, this triggers a fatal error on non-multisites:

[08-Jun-2018 12:48:49 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function switch_to_blog() in /dom7386/wp-content/plugins/affiliate-wp/includes/admin/class-upgrades.php:870
Stack trace:
#0 /dom7386/wp-content/plugins/affiliate-wp/includes/admin/class-upgrades.php(796): Affiliate_WP_Upgrades->get_sites_for_upgrade()
#1 /dom7386/wp-content/plugins/affiliate-wp/includes/admin/class-upgrades.php(155): Affiliate_WP_Upgrades->v222_upgrade()
#2 /wordpress-4.9.6/wp-includes/class-wp-hook.php(286): Affiliate_WP_Upgrades->init('')
#3 /wordpress-4.9.6/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#4 /wordpress-4.9.6/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /wordpress-4.9.6/wp-admin/admin.php(156): do_action('admin_init')
#6 {main}
  thrown in /dom7386/wp-content/plugins/affiliate-wp/includes/admin/class-upgrades.php on line 870
