### ISSUE TITLE
Cannot find filter to avoid payout generation

### ISSUE THREAD

**Issue by davefx** [AffiliateWP/AffiliateWP#2474]
In the site I'm working on, my client has asked me to avoid the generation of payouts for inactive affiliates. 
I already have located filters that allow me to avoid the generation of referrals for these affiliates, but I cannot find any filter to avoid the generation of payouts once the referrals have been created.

**Comment by DrewAPicture** [comment]
After some back and forth on the original PR, I've submitted an alternative: #2479, which introduces a new dynamic `affwp_pre_insert_$type_data` filter in `db->insert()`. Passing a falsey value back via a filter callback will cause `insert()` to bail. Includes 5 tests on a variety of falsey values.

```php
add_filter( 'affwp_pre_insert_payout_data', '__return_false' );
```
