### ISSUE TITLE
Ninja Forms integration ignores affiliate referral rate settings

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#2485]
The Ninja Forms integration does not properly calculate referral totals because it at no point calculates what the referral commission should be based on the affiliate's rates.

This is because we do not call the `calculate_referral_amount()` anywhere in the integration.

**Comment by gspice** [comment]
@pippinsplugins Success!  Created referrals based on referral rate settings elsewhere correctly.
