### ISSUE TITLE
Wrong decimal separator in the export file

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2487]
A user reported this:

>When generating the referrals payouts file, the dot is set for the decimal separator, even though we have the comma set in the settings. I've tried using the filter below to set the comma, but it gets stuck in an infinite loop and the file never gets generated.

>Here is the filter I used:
```
add_filter( 'affwp_batch_generate_payouts_get_data', function( $data ) {
$data['amount'] = affwp_format_amount($data['amount']);
return $data;
});
```

>If I try to add the affwp_format_amount() in the includes/admin/tools/export/class-batch-generate-payouts.php file in the get_data() function on the 'amount' it works ok (I get the exported file with decimal separator), but as soon as I use the filter it doesn't work - it gets stuck.

Ticket: https://secure.helpscout.net/conversation/494345841/73001?folderId=634609.

**Comment by tubiz** [comment]
PR: #2500 

A multidimensional array was being passed to the `affwp_batch_generate_payouts_get_data` filter instead of an associative array.

What Was Being Passed
```
Array
(
    [0] => Array
        (
            [email] => affiliate2@affwpdev.local
            [amount] => 18
            [currency] => USD
        )

)
```

What Was Expected
```
Array
(
    [email] => affiliate2@affwpdev.local
    [amount] => 18
    [currency] => USD
)
```

**Comment by pippinsplugins** [comment]
@tubiz the PR fixes the infinite loop but it doesn't fix the decimal / thousands separator. To fix that it needs to include a call to `affwp_currency_filter()`.

**Comment by tubiz** [comment]
@pippinsplugins updated. The `affwp_format_amount()` was used.
