### ISSUE TITLE
Add filter for the Contact Form 7 description

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2496]
Received from user on this support ticket:

https://secure.helpscout.net/conversation/498191326/73417?folderId=1170842

>I suggest the following change:
>n line 507 of class-contactform7.php you do the following:

`$description` `= get_the_title( $form_id );`

>please change this to:

`$description = apply_filter("afwp_cf7_referral_description", get_the_title( $form_id ), $contactform, $result);`

>The variables $contactform and $result are parameters of the action function this is called in anyway.

**Comment by tubiz** [comment]
PR: #2503

**Comment by DrewAPicture** [comment]
@amdrew Do we want to do this with only one request on the books?

**Comment by pippinsplugins** [comment]
We should make the filter apply for both paypal and non paypal referrals. Right now it's only running on the non-paypal referrals.

**Comment by amdrew** [comment]
@DrewAPicture I think we should

**Comment by kroeberk** [comment]
Just wanna say thanks for implementing this :)
