### ISSUE TITLE
Affiliates can be created with username fewer than four characters

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2501]
An affiliate can be created with a username that is fewer than four characters. WordPress requires usernames to have at least four characters. This seems to be an inconsistency. 

Steps to replicate:
1. Navigate to AffiliateWP > Affiliates > Add New
2. Click on the "Create one" hyperlink
3. Add an affiliate and give it a username of fewer than 4 characters

Result: Affiliate is added.
Expected Result: Affiliates should not be allowed with usernames of fewer than 4 characters.

**Comment by DrewAPicture** [comment]
Good catch. Milestoned for 2.1.11.

**Comment by pippinsplugins** [comment]
Moved to 2.1.12.

**Comment by tubiz** [comment]
I was able to create user accounts with usernames lower than four characters. WordPress only checks if the username is empty or the length is more than 60 characters.

Should we still go ahead and implement this check for usernames lower than four characters in AffiliateWP?

**Comment by pippinsplugins** [comment]
Yes I think so. Let's prevent creating accounts with less than four characters.

**Comment by tubiz** [comment]
There are two different scenarios we need to consider

- If an existing user account with fewer than four characters that was created in WP is selected should the affiliate account be created
- If a new user and affiliate account is created for a new user entirely this is when the username has to be 4 characters or more

**Comment by pippinsplugins** [comment]
Let's not affect nor change any existing accounts.

**Comment by pippinsplugins** [comment]
@gspice could you please give this a quick test?

**Comment by gspice** [comment]
@pippinsplugins How can I get a build with these changes to test with?  I don't see a branch for it which is what I usually download from.

**Comment by tubiz** [comment]
@gspice you can download this branch here https://github.com/tubiz/AffiliateWP/archive/issue/2501.zip

**Comment by gspice** [comment]
@tubiz Thank you!

Works great, prevents any new accounts unless 4 or more characters.   That said, you can still add less than 4 character usernames for an affiliate when adding a new WordPress user, and checking the box to make them an affiliate.

**Comment by tubiz** [comment]
@gspice the username characters check was not implemented on the WP Add New User page it was only implemented for the Add New Affiliate page.

@pippinsplugins should we also check for the username characters if the `Add as Affiliate` checkbox is chosen on the WP Add New User page

**Comment by pippinsplugins** [comment]
@tubiz no because that page is validated by WordPress itself.
