### ISSUE TITLE
Force 100% width on form fields

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2508]
Sometimes we get tickets where the customer's registration and login forms look like this:

<img width="616" alt="screen shot 2018-01-11 at 11 59 19 am" src="https://user-images.githubusercontent.com/52581/34800301-02289e48-f6c8-11e7-8382-9994cab35eec.png">

___

As a comparison, here's how it appears with a default WP theme:

<img width="453" alt="screen shot 2018-01-11 at 12 10 24 pm" src="https://user-images.githubusercontent.com/52581/34800406-6fa16734-f6c8-11e7-93ac-cdab3f336c70.png">

___

I think we can at least solve the positioning of fields with a line of CSS in core, to help those themes that don't have nice form styling.

One solution that comes to mind is to set a 100% width on the input and textarea fields. 

<img width="786" alt="screen shot 2018-01-11 at 12 16 44 pm" src="https://user-images.githubusercontent.com/52581/34800585-571abda4-f6c9-11e7-83c4-7877fc45e763.png">

It won't fix the button or actual input styling (the theme should style these) but at least it would be a small step closer in the right direction.
___

Customer ticket (though there have been many others): 
https://secure.helpscout.net/conversation/502940072/73858?folderId=205529

___

Sidenote, if a customer doesn't like the "look" of full-width input fields, they can always add a width to the `.`affwp-form` class.

**Comment by amdrew** [comment]
As a quick simulation, here's what Twenty Sixteen looks like, without 100% widths on fields

<img width="522" alt="screen shot 2018-01-11 at 12 29 23 pm" src="https://user-images.githubusercontent.com/52581/34801096-96177d10-f6cb-11e7-9eea-93aed453ddbf.png">

**Comment by amdrew** [comment]
@AffiliateWP/core Ready for testing: https://github.com/AffiliateWP/AffiliateWP/pull/2509

We could used a selector such as:

```
.affwp-form label + * {
    width: 100%;
}
```

But I went with:

```
.affwp-form label + input,
.affwp-form label + textarea {
 	width: 100%;
 }
```

It may be possible that the form is modified and an element is placed after a label which isn't meant to be 100% width.

Tested on a customer's site but will need to be tested on other themes that we know look "broken" or at least simulated first by removing any widths on fields and then using the PR to test.

**Comment by pippinsplugins** [comment]
@tubiz could you test this on a number of different themes to confirm all is well?

**Comment by tubiz** [comment]
@pippinsplugins okay, I will do that.

**Comment by tubiz** [comment]
I have tested this on 36 themes from the WP.org theme directory and it works on all themes apart from a theme that was setting the width of input element to 40% with an `!important` rule

```
select, input[type="text"], input[type="email"], input[type="url"], input[type="tel"], input[type="number"], input[type="color"], input[type="password"], .mu_register input[type="submit"] {
    width: 40% !important;
}
```

**Comment by amdrew** [comment]
@tubiz Thanks, that was very thorough :)

**Comment by pippinsplugins** [comment]
@amdrew anything else here or ready to merge?

**Comment by amdrew** [comment]
@pippinsplugins Ready to roll
