### ISSUE TITLE
0.00 transactions do not complete referrals in iThemes Exchanges

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#251]
iThemes Exchanges apparently treats 0.00 sales a little differently because pending referrals do not get updated to `unpaid`.

We have an option in Misc to disable 0.00 referrals. If that is disabled, 0.00 transactions should still work.

**Comment by tubiz** [comment]
@pippinsplugins 

The iThemes exchange plugin https://wordpress.org/plugins/ithemes-exchange/ is no longer available for download on WP.org.

Also there is no download link to the plugin on the plugin site https://exchangewp.com

**Comment by amdrew** [comment]
Related: https://github.com/AffiliateWP/AffiliateWP/issues/2504

**Comment by tubiz** [comment]
I wasn't able to replicate this issue on ExchangeWP version 1.36.6 as all 0.00 sales referrals were created and their statuses get updated to unpaid.

Bur I noticed that if any non affiliate coupon is used no referral is created for that sale.

Should I create another issue for that or that is related to this issue?

**Comment by pippinsplugins** [comment]
Great!

Please go ahead and create a new issue for that and we'll close this one.
