### ISSUE TITLE
Provide a way for affiliate to set password after being approved

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2516]
When adding an affiliate via the **Affiliates -> Affiliates -> Add New** screen, and adding a new WordPress user account at the same time, the affiliate does not receive a link to set their password in the affiliate approved email. 

This means the affiliate cannot log in to the Affiliate Area after being accepted.

<img width="706" alt="screen shot 2018-01-13 at 7 02 45 pm" src="https://user-images.githubusercontent.com/52581/34903358-624be0c8-f894-11e7-8090-424a2ae474b9.png">

They would need to first go to the Affiliate Area, click the forgot password link, receive the WordPress email to reset, click the link, generate a password and then log in. That's if they make it that far.

<img width="1316" alt="screen shot 2018-01-13 at 12 15 49 pm" src="https://user-images.githubusercontent.com/52581/34903110-58f6bd36-f88f-11e7-8b71-34e549ad5809.png">

The text does suggest the user can reset the password, however only if they click the link on the affiliate area page to reset the password:

> The password will be auto-generated and can be reset by the user or an administrator after the account is created.
___

If however you add a new affiliate via the **Users -> Add New** page, WordPress sends a separate email to the affiliate to set the password instantly. 

<img width="943" alt="screen shot 2018-01-13 at 12 10 37 pm" src="https://user-images.githubusercontent.com/52581/34903111-59307b7a-f88f-11e7-8730-ec61497bea5c.png">

<img width="735" alt="screen shot 2018-01-13 at 6 29 41 pm" src="https://user-images.githubusercontent.com/52581/34903122-be53217e-f88f-11e7-8629-8a636fb36ca4.png">

___

To allow an affiliate to login after being approved, and for consistency with WP core, we should provide a link for the affiliate to set their password in the affiliate approved email. 

This link should only appear in the email if the affiliate is added via the new affiliate admin screen, and if the user did not exist, as per the first screenshot above.

___

Related ticket: https://secure.helpscout.net/conversation/503651498/73968?folderId=205531

**Comment by amdrew** [comment]
PR: https://github.com/AffiliateWP/AffiliateWP/pull/2518

**Comment by amdrew** [comment]
@gspice @michaelbeil Could you please test this?

**Comment by gspice** [comment]
Verified email is sent and set password link functions as expected.

**Comment by michaelbeil** [comment]
Works wonderfully.
