### ISSUE TITLE
Jigoshop integration does not work with new Jigoshop eCommerce

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#2525]
The original [Jigoshopo plugin](https://wordpress.org/plugins/jigoshop/) has been discontinued and replaced with [Jigoshop eCommerce](https://wordpress.org/plugins/jigoshop-ecommerce/).

Unfortunately it appears that the original action hooks we relied on have been removed or changed.

At some point we should consider updating the Jigoshop integration to support the new version.

**Comment by tubiz** [comment]
@pippinsplugins I am working on this.

**Comment by tubiz** [comment]
PR: #2621
