### ISSUE TITLE
Referral not linked to related visit

### ISSUE THREAD

**Issue by flowdee** [AffiliateWP/AffiliateWP#2526]
Experienced a case where a referral is not linked to the related visit.

An affiliate was wondering why - in this case - he has 2 referrals but only 1 converted visit.

<img width="1085" alt="bildschirmfoto_2018-01-17_um_12_06_21" src="https://user-images.githubusercontent.com/2278756/35026764-7f65136c-fb7f-11e7-9925-42241775de22.png">
<img width="632" alt="bildschirmfoto_2018-01-17_um_12_06_32" src="https://user-images.githubusercontent.com/2278756/35026765-7fc4ffa2-fb7f-11e7-857f-8a9bd88218a9.png">

Debugged the visit object, but it seems like the referral was simply not assigned to the visit:

`(AffWP\Visit Object (     [visit_id] => 24370     [affiliate_id] => 25     [referral_id] => 0     [url] => https://website.de/     [referrer] => https://domain.com/not-needed/     [campaign] =>      [context] =>      [ip] => 91.19.103.251     [date] => 2018-01-13 17:55:14     [filled:protected] => 1 )`

Let me know if you need any further information.

**Comment by pippinsplugins** [comment]
@tubiz could you try and replicate this?

**Comment by tubiz** [comment]
@flowdee which of the integration are you using and what was the order status changes in the payment/order notes?

**Comment by flowdee** [comment]
Using the EDD integration.

The payment status changed was from "pending" to "published" (completed), if you meant this.

**Comment by tubiz** [comment]
@flowdee I haven't been able to replicate this issue yet.

The referral is linked to the visit when the referral status changes from `pending` or `rejected` to `unpaid` and for all referral that was created when I tested it was linked to the related visit.

**Comment by flowdee** [comment]
No problem. I'll observe it and see if it happens again
