### ISSUE TITLE
PayPal Buttons JS error: TypeError: action is undefined

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2527]
A customer's site is generating a JavaScript error when the PayPal Buttons integration is enabled. 

```
TypeError: action is undefined
```

This is appearing when a modal window is being launched after adding a WooCommerce product to the cart, provided by another WooCommerce related plugin: 

<img width="939" alt="screenshot 2018-01-20 14 41 06" src="https://user-images.githubusercontent.com/52581/35178684-46979022-fdf1-11e7-90f1-452516d1b52e.png">

Because of the JS error, the "no thanks" and `x` links cannot be clicked.

The specific line referenced in the HTML source is coming from our PayPal integration:

```
`if ( ! action.match( paypalMatch ) ) {`
```

Ticket: https://secure.helpscout.net/conversation/508945591/74456?folderId=205527

**Comment by tubiz** [comment]
@pippinsplugins on it.

**Comment by amdrew** [comment]
👍 This is causing another customer's checkout page to break: https://secure.helpscout.net/conversation/513545519/74968?folderId=205527

**Comment by amdrew** [comment]
Another report. This time an "update your payment form".

**Comment by tubiz** [comment]
@amdrew can you send the sites url so I can check.

**Comment by amdrew** [comment]
@tubiz Here's how you can replicate the issue, based on the most recent report:

1. Install WooCommerce
2. Install this plugin: https://wordpress.org/plugins/woocommerce-gateway-paypal-powered-by-braintree/
3. Enable the `Braintree (Credit Card)`. 
4. Enable sandbox mode and enter any details. If you want, sign up to braintree and put in some real test API credentials. You'll then see a real form instead of the error shown below.

    <img width="678" alt="screenshot 2018-02-03 12 01 59" src="https://user-images.githubusercontent.com/52581/35758693-24d29c9a-08da-11e8-814b-11fdc2252f0f.png">
5. Go to `/my-account` on the front-end
6. You'll then see a `Payment Methods` section
    <img width="894" alt="screenshot 2018-02-03 12 03 39" src="https://user-images.githubusercontent.com/52581/35758753-5c757dca-08da-11e8-9d91-ee8bfc5fc169.png">
7. Click `Add Payment Method` and you'll see the JS error in the console. Make sure you have the PayPal Buttons integrations enabled in AffWP's settings to see this.
    <img width="1079" alt="screenshot 2018-02-03 12 03 51" src="https://user-images.githubusercontent.com/52581/35758793-983ca14e-08da-11e8-8089-9d18d5e599ef.png">

If the PayPal Buttons integration is not enabled, there's no error. The above is just one example of how this is causing issues, but they are all related to some kind of conflict with another form.

**Comment by amdrew** [comment]
PR merged into master, fixes the issue above and PayPal Buttons integration still works as expected. @tubiz Can you please also test?

**Comment by tubiz** [comment]
@amdrew I was able to replicate the issue using the steps you outlined. 
With the PR, after testing the issue has been fixed.
