### ISSUE TITLE
Adjust CSS on the affiliate column on the WC orders page

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2531]
>On the latest AffiliateWP Update, I like the additional column on the orders page showing the affiliate ID, however, it is incredibly large and seems to waste valuable space. Can this be adjusted?

![screen shot 2018-01-22 at 15 35 03](https://user-images.githubusercontent.com/4752949/35245736-e205990c-ff89-11e7-9f71-f5e6d64d8383.png)

https://secure.helpscout.net/conversation/510362801/74590?folderId=634609

**Comment by amdrew** [comment]
If we give it a width of 110px (like the actions column beside it), it definitely performs a lot better:

<img width="477" alt="screen shot 2018-01-23 at 12 08 30 pm" src="https://user-images.githubusercontent.com/52581/35249278-3ea406c4-0036-11e8-969a-cdbe6cc4498f.png">

**Comment by amdrew** [comment]
Something else we should tackle for this:

<img width="316" alt="screenshot 2018-01-24 12 19 51" src="https://user-images.githubusercontent.com/52581/35306061-e7f0f7da-0100-11e8-882f-52b386769226.png">

If you make the browser very narrow the `Affiliate Ref...` overlaps onto the next row.

**Comment by amdrew** [comment]
@AffiliateWP/core Ready for testing.

PR: https://github.com/AffiliateWP/AffiliateWP/pull/2536

This:

1. Sets the column width to `110px`, the same as the actions column beside it.
2. Adds a `–` to the column when there is no referral. This makes it consistent with how WooCommerce shows other columns:

<img width="717" alt="screenshot 2018-01-24 13 16 48" src="https://user-images.githubusercontent.com/52581/35307696-d6d79cb2-0108-11e8-8e26-23158b4adbf0.png">

It also fixes the aforementioned issue with the overlapping text at smaller browser widths:

<img width="317" alt="screenshot 2018-01-24 13 13 44" src="https://user-images.githubusercontent.com/52581/35307714-f8f9137a-0108-11e8-87e6-9b3f8eb3ba71.png">

**Comment by JJJ** [comment]
Works as expected. I like it.

We could go a step farther and increase the padding on the action buttons on mobile. They're maybe hard to target as is. This isn't specific to AFFWP (WordPress isn't great at this either) but we have some room to bump it up if we wanted.

**Comment by michaelbeil** [comment]
Looks good to me @amdrew.

**Comment by amdrew** [comment]
Here's how it looks with `&mdash;` so it is consistent with WP core, as opposed to WooCommerce:

<img width="311" alt="screenshot 2018-01-24 15 28 42" src="https://user-images.githubusercontent.com/52581/35311430-5b5c16a4-011b-11e8-967e-dd6db63ff741.png">

<img width="698" alt="screenshot 2018-01-24 15 27 28" src="https://user-images.githubusercontent.com/52581/35311431-5b8c837a-011b-11e8-8dd6-fe78a6bf42b3.png">

**Comment by amdrew** [comment]
Also added the `aria-hidden` attribute as WP does on the `pages` page.

**Comment by pippinsplugins** [comment]
Looks good!
