### ISSUE TITLE
Visit/cookie not created in browser if affiliate username is email address and fallback tracking is enabled.

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2539]
Discovered on support ticket:
https://secure.helpscout.net/conversation/511477820/74698?folderId=205529

Setup:

* Enable **Use Fallback Referral Tracking Method** under _Affiliates > Settings > Misc_.
* Create or use an affiliate's link who has an email address as their username.
* Use the link as standard or "pretty" link in a browser, the cookie/visit will not be created.

Workaround:
* Turn off Fallback tracking and the cookie/visit is created successfully.

**Comment by pippinsplugins** [comment]
@tubiz this is another one for you.

**Comment by tubiz** [comment]
PR: #2549
