### ISSUE TITLE
Cookie/visit not being created with fallback tracking and usernames with periods

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2540]
Similar to https://github.com/AffiliateWP/AffiliateWP/issues/2539

If Fallback Tracking is enabled, referral links with a period in the username do not generate a cookie/visit. Non-pretty referral links work however.

### Works and generates a visit
https://issues.affwp.dev/?ref=test.user

### Does not generate a visit
https://issues.affwp.dev/ref/test.user

### To replicate:

1. Enable `Use Fallback Referral Tracking Method` from _Affiliates > Settings > Misc_.
2. Create or use an affiliate's link who has a period in their username.
3. Use the pretty version of the affiliate link, e.g. `https://issues.affwp.dev/ref/test.user`. The cookie/visit will not be created.

Disabling fallback tracking allows the same referral link to store a cookie/visit.

Ticket:
https://secure.helpscout.net/conversation/512934442/74899?folderId=205529

**Comment by amdrew** [comment]
@tubiz Could you please also tackle this one, similar to #2539 so possibly related.

**Comment by tubiz** [comment]
PR: #2549
