### ISSUE TITLE
Make affiliate registration password fields optional

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2541]
It might be worth exploring the idea of allowing the password fields on the affiliate registration form to be optional. This could reduce a bit of friction by making the form faster/easier to submit.

A link to set a password would be sent to the affiliate if their affiliate application is accepted. Like https://github.com/AffiliateWP/affiliatewp-affiliate-forms-gravity-forms/issues/27 and https://github.com/AffiliateWP/AffiliateWP/issues/2516.

Form with fields removed:

<img width="662" alt="screen shot 2018-01-30 at 11 50 08 am" src="https://user-images.githubusercontent.com/52581/35538738-c5efa48a-05b3-11e8-863f-cd31eb7b33c0.png">

Would love to hear any thoughts

**Comment by tubiz** [comment]
PR: #2648 

* Required registration fields
<img width="1171" alt="required fields" src="https://user-images.githubusercontent.com/602184/39458388-0621d6e8-4cec-11e8-8dde-b712e0746711.png">

* The password field will be removed from the registration page, if it isn't required.
<img width="1005" alt="no password registration form" src="https://user-images.githubusercontent.com/602184/39458450-7b1da9f4-4cec-11e8-97fe-b4bbb7fd7aba.png">

* Pending afffiliate review email
<img width="720" alt="pending review welcome email" src="https://user-images.githubusercontent.com/602184/39458469-b04a02f8-4cec-11e8-82d6-290ab5958222.png">

* New affiliate acceptance email
<img width="696" alt="new affiliate set password" src="https://user-images.githubusercontent.com/602184/39459003-87716200-4cf0-11e8-9d27-9599ca626855.png">

**Comment by pippinsplugins** [comment]
@tubiz Could you update the description to indicate that the field will be removed if not required?

**Comment by tubiz** [comment]
@pippinsplugins PR updated.

<img width="1242" alt="affwp 2541" src="https://user-images.githubusercontent.com/602184/39789166-32120594-5326-11e8-9c05-f3bb4fd9bd9b.png">
