### ISSUE TITLE
Refreshing user edit screen after registering affiliate could accidentally re-register if they are deleted

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2543]
After approving an affiliate from the user edit screen, deleting them in another window, and then refreshing the user edit screen, it's possible that affiliate could become re-registered.

#### Steps to replicate:

1. Register an affiliate from the edit user screen
 
    <img width="355" alt="screenshot 2018-01-30 14 15 29" src="https://user-images.githubusercontent.com/52581/35543107-247d4f3e-05c8-11e8-82cb-bf0c17ea346e.png">

2. Leave the screen open and note the `register_affiliate=1` in the URL: `/wp-admin/user-edit.php?user_id=860&register_affiliate=1`
3. In a new tab, delete the affiliate from the Affiliates -> Affiliates screen (don't delete their user account).
4. Back on the edit user screen, refresh the page.
5. The affiliate is then registered again

We should prevent this from happening by stripping `register_affiliate=1` from the URL. We do something similar on other admin screens.

**Comment by amdrew** [comment]
@AffiliateWP/core Ready for testing: https://github.com/AffiliateWP/AffiliateWP/pull/2544

**Comment by michaelbeil** [comment]
Fixes the issue.
