### ISSUE TITLE
Possible bug in referral amount calculation for EDD payments

### ISSUE THREAD

**Issue by brashrebel** [AffiliateWP/AffiliateWP#2559]
Discovered on easydigitaldownloads.com when looking at payment records for an unrelated reason.

[This payment](https://easydigitaldownloads.com/wp-admin/edit.php?post_type=download&page=edd-payment-history&view=view-order-details&id=1159192) resulted in a referral amount which I don't understand.

The affiliate [_should_ be getting 20%](https://easydigitaldownloads.com/wp-admin/admin.php?s=atkinson&page=affiliate-wp-affiliates&_wp_http_referer=%2Fwp-admin%2Fadmin.php%3Fpage%3Daffiliate-wp-affiliates&action=edit_affiliate&paged=1&action2=-1&affiliate_id=4600). But they're getting something at least twice as much. I don't know what number is being used to base the calculation off of.

The product price is $199 and the total after a discount code was $169.15. The affiliate was paid $87.22. That is 44% of the product price and 52% of the payment total. $87.22 x 5 = $436.10 so if the payment was that much, the commission amount would be correct. But it ain't so it's bogus.

What gives? Isolated incident? Hope so. Pippin and I discussed in #edd-support this morning for more context.

**Comment by michaelbeil** [comment]
This seems to have also come up here: https://secure.helpscout.net/conversation/520977277/75824?folderId=205529.

**Comment by michaelbeil** [comment]
I have not been able to replicate this issue.

**Comment by pippinsplugins** [comment]
@tubiz could you look into this?

To replicate:

1. Add two items to the cart
2. Go to checkout and purchase with PayPal Standard (do not complete purchase)
3. After being redirected to PayPal, click the browser's back button to return to the checkout screen
4. Remove one item from the cart
5. Complete the purchase with the Test Payment gateway
6. Referral amount will be wrong.

**Comment by tubiz** [comment]
@pippinsplugins will do.

**Comment by michaelbeil** [comment]
PR fixes the issue.

**Comment by amdrew** [comment]
Works for me 👍

**Comment by pippinsplugins** [comment]
Re-opening in order to put into a point release instead of waiting until 2.2.
