### ISSUE TITLE
EDD: add link in Payment Notes to go directly to referral edit screen

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2560]
>When refunding an EDD purchase in the Payment Notes there is a link to the EDD Commission so I can go there and revoke it.

>Can AffWP add a similar link to the referral to make it quicker to find and revoke the referral?
 
![link](https://user-images.githubusercontent.com/4752949/36041719-bae7cc34-0dc9-11e8-93e8-0a210ef2e68a.png)
 
Related to #2411.

**Comment by pippinsplugins** [comment]
@tubiz could you work on this?

**Comment by tubiz** [comment]
@pippinsplugins will do.

**Comment by tubiz** [comment]
PR: #2562

**Comment by pippinsplugins** [comment]
How about linking the referral ID (i.e. `#49`) instead of adding a new `View` link?

**Comment by tubiz** [comment]
Ok. I will update the PR now.

**Comment by tubiz** [comment]
PR updated. 

<img width="947" alt="2018-02-13_1631" src="https://user-images.githubusercontent.com/602184/36157973-6c5241e8-10db-11e8-894b-e315b6515962.png">

**Comment by pippinsplugins** [comment]
@tubiz we're going to put this in 2.2. Could you update your branch with the latest changes from `release/2.2`/

**Comment by tubiz** [comment]
@pippinsplugins I will do that.

**Comment by tubiz** [comment]
@pippinsplugins I have updated my branch with the latest changes from `release/2.2`

**Comment by michaelbeil** [comment]
This PR works great.
