### ISSUE TITLE
Creatives are not displaying in AffiliateWP 2.1.12

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2563]
It seems like creatives are not displaying in AffiliateWP 2.1.12. I've been able to replicate this locally.
 
![screen shot 2018-02-13 at 15 03 20](https://user-images.githubusercontent.com/4752949/36153605-1f90a676-10cf-11e8-866e-c1254c057f85.png)
![screen shot on 2018-02-13 at 15_02_31](https://user-images.githubusercontent.com/4752949/36153606-1faa5328-10cf-11e8-8037-6c6b79c5158d.png) 

Tickets: 
https://secure.helpscout.net/conversation/523127486/76031?folderId=634609
https://secure.helpscout.net/conversation/523182330/76040?folderId=205524

**Comment by michaelbeil** [comment]
PR fixes the issue.

**Comment by pippinsplugins** [comment]
Merging and deploying.
