### ISSUE TITLE
Add PayPal email to review page

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2568]
>Is it possible for me to see on the review page that the person filled in their PayPal email which I'd like to be a required field. 

Ticket: https://secure.helpscout.net/conversation/524606441/76246?folderId=205529.

**Comment by tubiz** [comment]
PR: #2646 

Display the PayPal email on the affiliate review page if it is filled.

<img width="1244" alt="affiliate review page" src="https://user-images.githubusercontent.com/602184/39456489-9fefb762-4cde-11e8-9180-4b8e13f9f6be.png">

**Comment by pippinsplugins** [comment]
Looks good. We can merge this after 2.2 is released.
