### ISSUE TITLE
Switch payment email to Your PayPal payment email

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2569]
>People are asked to enter their PayPal email. Because of Stripe and other payment services it is not clear anymore that this field is for PayPal only. I recommend that you make it perfectly clear by renaming the word "payment email" into Your PayPal payment email. and I would even use the PayPal logo instead of writing it.
 
Ticket: https://secure.helpscout.net/conversation/524641044/76248?folderId=205529.

**Comment by amdrew** [comment]
The `Your payment email` field on the Affiliate Area could be used for other systems such as Moneybookers, not just PayPal. Changing to say "Your PayPal payment email` in this instance would not make sense. 

The input's description can be changed if need be via the `dashboard-tab-settings.php` template file, or with a plugin such as "SayWhat?".
