### ISSUE TITLE
Admin:  Adding new referral manually doesn't display an error if the affiliate selection is not completed.

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2570]
When manually adding a new referral, if the Affiliate is not selected, when you click **Add Referral**, it appears to save and you are returned to the Referral list, but nothing has been saved.   Desired behavior is an error of some sort as displayed on the Add Affiliate screen when the User login name has not been found.

**Steps to reproduce:**
* WooCommerce 3.3.1
* AffiliateWP 2.1.13
* _Affiliates > Referrals > Add New_
*  Enter anything in the _Affiliates_ entry and continue filling in the referral values.  Click to **Add Referral** and nothing is saved, you are returned to the Referrals list.

**Comment by pippinsplugins** [comment]
@tubiz could you look into adding improved handling here?

**Comment by tubiz** [comment]
@pippinsplugins will do.

**Comment by tubiz** [comment]
PR: #2577 

<img width="1271" alt="referral not created" src="https://user-images.githubusercontent.com/602184/36371644-07f49430-1563-11e8-8dbc-6208037ab771.png">
