### ISSUE TITLE
Fallback Tracking affwp_campaign cookie is not being generated

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2578]
To reproduce:

1. Enable Fallback Tracking in Misc settings
2. Clear all browser cookies
3. Visit an affiliate URL like site.com/?ref=1&campaign=test
4. Check your cookies and the affwp_campaign cookie is not present 

Ticket: https://secure.helpscout.net/conversation/525270292/76324?folderId=205527.

**Comment by amdrew** [comment]
Replicated the issue.

@tubiz Could you please look at this one?

**Comment by tubiz** [comment]
@amdrew will do.

**Comment by tubiz** [comment]
PR: #2579
