### ISSUE TITLE
Add filters to get_sortable_columns() methods

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2583]
Each of our `class-list-table.php` files should have a filter included for the `get_sortable_columns()` method.

This will allow add-ons such as Store Credit to have a filterable column: https://github.com/AffiliateWP/affiliatewp-store-credit/issues/10#issuecomment-367179713

**Comment by tubiz** [comment]
PR: #2649

**Comment by pippinsplugins** [comment]
@tubiz we should also add filters to the other list tables, that way each object type's sortable columns are filterable.

**Comment by tubiz** [comment]
@pippinsplugins filters has been added to all the list tables (affiliate, creative, payout, referral and visits).
Are there other list tables the filter need to be added to?
