### ISSUE TITLE
Add further organization to the creatives tab 

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2586]
Request from a customer:
>I have uploaded some banners and text links in the create area. Functionally it works great, but I was wondering if there is a way to display them more organized, now they are listed one underneath the other and it does not look too nice. Not sure maybe there are Tabs for text links, banners, special promotions, etc. Could you please help me out here?

Should we add further organization to the creatives tab?

Perhaps creative categories?

Related issue: https://github.com/AffiliateWP/AffiliateWP/issues/343.

Ticket: https://secure.helpscout.net/conversation/528749285/76708?folderId=634609.

**Comment by pippinsplugins** [comment]
Closing as duplicate in favor https://github.com/AffiliateWP/AffiliateWP/issues/411
