### ISSUE TITLE
Admin: Affiliates > Settings > General > Cookie Sharing: change wording for subdomain cookie sharing

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2590]
https://github.com/AffiliateWP/AffiliateWP/blob/7f909b35681f39c3f1ffbf73cfa17ec29e9d6402/includes/admin/settings/class-settings.php#L554

Can we change this to add that this is for multisite when using subdomains vs previously not supporting subdomains?  We've had a few tickets where users are confused, asking if they should check this or not in lieu of having to use the External Referral Links add-on.

**Comment by pippinsplugins** [comment]
@gspice how's that wording?

**Comment by gspice** [comment]
@pippinsplugins That works!  I'll make sure the docs have a note as well.
