### ISSUE TITLE
Possible broken links in emails using certain email services

### ISSUE THREAD

**Issue by mindctrl** [AffiliateWP/AffiliateWP#2592]
In the URLs, things like `&` get converted to `#038;`, which can break some links when passed through some link tracking services.

We experienced a similar thing in [RCP #1585](https://github.com/restrictcontentpro/restrict-content-pro/issues/1585). Our fix was to search/replace those occurrences of `#038` with `&amp;` in the `text_to_html()` method of the email class. https://github.com/restrictcontentpro/restrict-content-pro/pull/1708/files

The difference I see is in RCP we use `make_clickable()`, which may make a difference here. We'll need to test and confirm.

EDD saw this in [#3998](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/3998), which is now being tracked in [#6413](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6413) there.

**Comment by tubiz** [comment]
PR: #2654

**Comment by pippinsplugins** [comment]
PR looks good, will merge after 2.2 is released.
