### ISSUE TITLE
Ninja Forms integration - Wrong referral amount calculated

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/AffiliateWP#2594]
The wrong referral amount is calculated in the Ninja Forms integration.

Referral rate: `20%`
Order Total: `$500`
Referral Amount: `$20` instead of `$100`

<img width="1246" alt="ninjaform referral" src="https://user-images.githubusercontent.com/602184/37031705-1719e88c-2140-11e8-95ed-68e4dc723d8f.png">
<img width="961" alt="ninja forms referral details" src="https://user-images.githubusercontent.com/602184/37031706-1770f37a-2140-11e8-9029-afa5481515ce.png">

AffiliateWP: 2.1.15
Ninja Forms: 3.2.16

**Comment by tubiz** [comment]
PR: #2595

**Comment by gspice** [comment]
@tubiz   Tested using your same values but still received `$20` referral and was expecting `$100`.  Can you export your Ninja form so I can test with the same one please?

**Comment by tubiz** [comment]
@gspice can you retest using this https://github.com/tubiz/AffiliateWP/archive/issue/2594.zip

**Comment by gspice** [comment]
@tubiz Thank you, that works, referral amount now `$100`.
