### ISSUE TITLE
Integration: Formidable Forms creating php error when submitted

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2598]
Reported on this ticket:
https://secure.helpscout.net/conversation/535426079/77508?folderId=1170842

> I stripped everything else away (disabled all other plugins and reverted back to Twenty Seventeen theme) and it still happens - but only in Chrome. I've narrowed it down to only happen when I have both FForms and AffiliateWP plugins enabled. If JUST Formidable is enabled, the Submit Hang issue goes away. But just turning on AffiliateWP makes it hang.

He's not using the forms to generate referrals.  By chance he searched his php logs and found this:

``
[Tue Mar 06 23:27:22.212120 2018] [:error] [pid 21779] [client 96.252.14.95:65527] PHP Fatal error: Call to a member function getOne() on null in /nas/content/live/editdiva/wp-content/plugins/affiliate-wp/includes/integrations/class-formidablepro.php on line 166, referer: https://www.writing.ninja/plain-test-page/``

Formidable Forms support told him this:

>This is a problem with outdated code in their plugin. Can you please contact them to fix the issue?

I cannot reproduce it locally, however, I tried on our sandbox site and it fails and goes to a Pagely error page, but does not report the exact error.  I suspect it's generating the same error on our hosting account's php logs.

**Comment by gspice** [comment]
* Tested this branch.
* Testing with free version `3.0.06`, enabled integration.
* Forms with AffiliateWP fields populated for **Referral Description** and **Purchase Amount** create a referral successfully, no errors.
* If you leave those description and amount fields not set (which seems to be the only way to not enable the form for referrals) so they look like this:

![formidable-affwp-settings](https://user-images.githubusercontent.com/3018245/37173765-52858464-22c9-11e8-8b8e-5c1b7292e854.png)

...then I receive the following php errors:
![local-php-errors](https://user-images.githubusercontent.com/3018245/37173775-5c0ed7d8-22c9-11e8-9f93-19e78388625d.png)

**Comment by amdrew** [comment]
Ahh, thanks @gspice, will check it out

**Comment by amdrew** [comment]
@gspice Ready for another test

**Comment by gspice** [comment]
@amdrew 

Tested successfully with `3.0.06` and `2.03.09`

* Leaving `Referral Description` and `Purchase amount` unset submits successfully, no more errors. It does, however, create a zero-amount referral.   Should it?  Probably a different ticket, but should there be a checkbox to enable the form to create referrals like we do in Gravity Forms?  Otherwise, every form created will create a referral if the integration is enabled in AffiliateWP.

**Comment by amdrew** [comment]
@gspice That's a good point. We can either:

1. Create a checkbox as you've mentioned to enable referrals

or

2. If the amount select menu isn't mapped to a field, don't create a referral at all.

**Comment by amdrew** [comment]
@gspice From our existing Formidable Forms doc:

> Second, go to the Settings page for the form you wish to track conversions on and click the AffiliateWP tab. Here, select the fields for the referral description and the amount the referral should be calculated by to enable affiliate tracking.

> Once both options are enabled, AffiliateWP will automatically generate a referral each time the customer is referred by an affiliate and submits a form.

Looks like there's definitely a bug here. I left the 2 options unselected and only entered an email address on my test form. That generated a $0.00 referral even though no fields are mapped. As per the above the referral should _only_ be generated once both options are configured. It's likely been this way for quite some time.

I'm going to fix it so those 2 options must be first configured, before any referral can be generated. We can open a new issue for the checkbox to improve the flow, but we'll need to add some kind of upgrade routine and make sure the checkbox is enabled for those already generating referrals from their forms.

**Comment by amdrew** [comment]
@gspice Ready for some more testing. A referral should now only be generated if _both_ options are set, i.e: 

<img width="540" alt="screen shot 2018-03-12 at 2 22 53 pm" src="https://user-images.githubusercontent.com/52581/37261381-e40f4b9c-2600-11e8-8ff9-9fc6582c0b81.png">

Sidenote: in the issue we create for improving the Formidable Forms integration, let's add descriptions to the form fields above, and attempt to line up the logo. perhaps removing the logo mark might be better, and just leave the `AffiliateWP`. We don't include the logo mark on any of our other integrations.

**Comment by amdrew** [comment]
@gspice Oops, fixed!

**Comment by gspice** [comment]
@amdrew 

Tested:
* Only description set, no referral created
* Only amount set, no referral created
* Both not set, no referral created. 
* Both set, referral created.

All tests were successful!

**Comment by amdrew** [comment]
@gspice Excellent!

**Comment by amdrew** [comment]
Merged into master
