### ISSUE TITLE
RCP: Revoke referrals when payments are refunded or abandoned

### ISSUE THREAD

**Issue by mindctrl** [AffiliateWP/AffiliateWP#2602]
The RCP integration revokes referrals on payment deletions, but not on refunds or abandonments.

In [this ticket](https://secure.helpscout.net/conversation/536235069/77619?folderId=545071) unpaid referrals remained after a payment was marked as abandoned.

**Comment by mindctrl** [comment]
To clarify the refund thing. The `Reject Unpaid Referrals on Refund` setting doesn't work quite as expected, because the integration code hooks into `rcp_delete_payment` which only triggers when a payment is deleted, not refunded or abandoned.

I think we should update this code so that deletions, refunds, and abandoned payments are all treated the same, according to the settings option.

**Comment by mindctrl** [comment]
Thinking about this a bit more, I would think we'd always want to revoke on abandoned, regardless of the setting, since no payment was ever completed at all, but I'd like to hear AffWP team feedback on that.

**Comment by michaelbeil** [comment]
To revoke the referral that has been generated from an abandoned purchase makes sense to me.

**Comment by mindctrl** [comment]
Updated to always revoke abandoned payments.

PR: https://github.com/AffiliateWP/AffiliateWP/pull/2603

**Comment by michaelbeil** [comment]
Excellent!

**Comment by michaelbeil** [comment]
This works as expected!
