### ISSUE TITLE
Contact Form 7 error  

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2608]
This is coming up in debug assistant of affiliate WP:

>CF7 integration: The form ID or referral ID could not be determined.

Ticket: https://secure.helpscout.net/conversation/541709089/78183?folderId=205524.

**Comment by amdrew** [comment]
That line _should_ only be appearing in the logs if no `form_id` or `referral_id` is found in PayPal's return URL: https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-contactform7.php#L473

The customer in the linked ticket however does not have the "Contact Form 7 PayPal" Add-on installed (see https://docs.affiliatewp.com/article/657-contact-form-7) so should not be seeing these log notices at all.

The `mark_referral_complete()` and `revoke()` methods are both firing on `wp_footer`, so it seems (I have not yet tested) the notices will be logged on _every_ page load:

https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-contactform7.php#L65

https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-contactform7.php#L523

The customer has over `12,000` of these notices logged.

@tubiz Want to tackle this?

**Comment by tubiz** [comment]
@amdrew Yes.

**Comment by tubiz** [comment]
PR: #2609 

Fixes
* Logging of messages if the Contact Form 7 PayPal add-on is not enabled
* Referrals not marked as complete after payment is made

**Comment by amdrew** [comment]
Great! PR fixes the log issue, all looks good to me.

@tubiz Was the referrals not being marked as complete something you found while fixing this issue?

**Comment by amdrew** [comment]
Great!

**Comment by amdrew** [comment]
@pippinsplugins Unless you can spot anything, this looks good to go
