### ISSUE TITLE
EDD: Improve payments notes for referrals

### ISSUE THREAD

**Issue by mindctrl** [AffiliateWP/AffiliateWP#2610]
Right now when a referral is made, a note is added to the payment in EDD. It looks something like this:

```
EDD Bot – March 20, 2018, 11:54 am
Referral #838 for $89.82 recorded for xxxxxx – Delete
```

I think the usability of this could be improved. Since AffWP does not show the referral ID number on the Affiliates > Referrals page, it's harder and unintuitive to find the referral in question. You have to go about it backwards, and find it by payment ID, or you can copy the referral ID from the payment note and search by that. Neither of those is smooth and fluid.

Ideally the note would be linked to the referral record, but EDD strips HTML in notes so that's a showstopper for that idea unless/until we update EDD to allow better notes.

I don't know what a good solution is here, as I feel like showing the ID on the list page will just clutter things up, but I think it's worth considering some kind of improvement.

**Comment by pippinsplugins** [comment]
@mindctrl we have linked the referral for upcoming 2.2. See #2560

**Comment by mindctrl** [comment]
Doh! My search-fu failed me. Nice!
