### ISSUE TITLE
SQL error when using the campaign keyword prefix to search on the Visits page

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/AffiliateWP#2632]
On the *Affiliates -> Visits* page perform a search using the `campaign:` keyword prefix (`campaign: instagram`)  doesn't return any result instead the error below is shown.

<img width="1266" alt="visit search error" src="https://user-images.githubusercontent.com/602184/39127893-3bd51078-46fe-11e8-9f0b-3613733aee2d.png">

**Comment by tubiz** [comment]
PR: #2633

**Comment by michaelbeil** [comment]
Is there anything more that you have within the search field? I just tested with `campaign: instagram`, and could not replicate this issue.

**Comment by tubiz** [comment]
That's strange. I just tested again with `campaign: instagram` and I can still replicate the issue.

**Comment by michaelbeil** [comment]
What is your current WordPress setup? What version of WordPress, PHP, and MySQL are you using?

**Comment by tubiz** [comment]
WordPress: `4.9.5`
PHP: `5.6.20` and `7.2.0` ( I was able to replicate on both version)
MySQL: `5.6.34`

**Comment by michaelbeil** [comment]
I see the errors now within Query Monitor. Screenshot: http://beil.io/8TuuPB. However, these are not displayed on the page. 

Your PR fixes the errors from being displayed within Query Monitor.

**Comment by tubiz** [comment]
Yes. The PR fixes the error and the results will be displayed if there are any visits for the campaign.
