### ISSUE TITLE
Change agreement string if affiliate program is in the EU - GDPR

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2637]
We already have an option for a checkbox that is added to the affiliate registration form with the existing option we provide for Terms of Use. This particular checkbox can be enabled in the General settings tab: 
![a7ewx7](https://user-images.githubusercontent.com/4752949/39247885-e9c11df6-489a-11e8-9b53-21d20954bc42.png) 

We should add support to change the verbiage of this string from:

_"Agree to our Terms of Use"_ to _"You agree to our terms of use and grant us permission to store this data.”_ 

This would better line up with GDPR.

Ticket: https://secure.helpscout.net/conversation/567700976/80955?folderId=634609.

**Comment by amdrew** [comment]
@pippinsplugins I think if we're going to allow the label to be changed, it should also be possible to change the "Agree to our" text. I see why it's not included but perhaps there's a better way. 

The description of the input clearly says "Enter the label you would like shown for the terms of use checkbox". A customer may enter some additional text in front such as "Accept our" without realizing there is already text on the front-end (which they would need to log out to see).

Perhaps we could do something similar to email tags and use curly braces to specify which text gets linked, then update the description so it's clear? Something like:

`Agree to our {Terms of use and privacy policy}`

**Comment by pippinsplugins** [comment]
I didn't do that because it caused problems with auto linking to the terms page, which we have defined in an option above. We could always allow custom HTML but then the terms page selection has no value.

**Comment by amdrew** [comment]
What was the problem? String replace on the text inside the curly brackets and link to the page set in the select menu above.

Another option is to leave as-is but we need to make it clear in the description that it's addition to the "Agree to our" text already there.

**Comment by pippinsplugins** [comment]
>>>String replace on the text inside the curly brackets and link to the page set in the select menu above.

String replace on what? Are you suggesting we simply have customers enter brackets around the text they want linked to the terms page?

Sorry, not sure I follow your comment.

**Comment by amdrew** [comment]
> Are you suggesting we simply have customers enter brackets around the text they want linked to the terms page?

Yes, we could wrap the text inside the input with curly brackets which would become the actual link. 

Example of how the input could look:

`Agree to our {Terms of use and privacy policy}`

Not sure if there's a nicer way to approach it. Or, we leave as-is but update the description to be more clear.

**Comment by pippinsplugins** [comment]
I feel that would cause confusion.

What if we separated it into two settings fields, one for the `Agree to our` label and one for the `Terms of use and privacy policy` link? I don't love that either but it could work.

**Comment by amdrew** [comment]
Don't love it either but it seems like a good compromise.

**Comment by pippinsplugins** [comment]
@amdrew try that. I don't love it but it does work.
<img width="840" alt="screen shot 2018-05-14 at 3 33 46 pm" src="https://user-images.githubusercontent.com/1034109/40021973-37c52786-578c-11e8-8289-eec58df59d5b.png">

**Comment by amdrew** [comment]
@pippinsplugins Let's remove the terms of use label from the front-end when it's been cleared out in the settings. A user may like to make the whole line linked like this:

<img width="816" alt="screen shot 2018-05-15 at 9 21 43 am" src="https://user-images.githubusercontent.com/52581/40024146-7c28fdcc-5821-11e8-8f64-6aa3e2fc47d8.png">

<img width="553" alt="screen shot 2018-05-15 at 9 23 34 am" src="https://user-images.githubusercontent.com/52581/40024238-b8431f5e-5821-11e8-8bb4-c78bd0fc6703.png">

**Comment by pippinsplugins** [comment]
Maybe we should just make the entire text a link and have one setting? That's better than two settings that create a single sentence.

Okay with that?

**Comment by amdrew** [comment]
@pippinsplugins Yeah, let's do that 👍

**Comment by pippinsplugins** [comment]
Ready for re-review!

**Comment by amdrew** [comment]
@pippinsplugins 

I think the default text in `class-settings.php` and `register.php` should be changed to:

`Agree to our Terms of Use and Privacy Policy`

vs

`Agree to our terms of use and privacy policy`

Just looking at other pages such as https://www.apple.com/nz/legal/internet-services/terms/site.html and https://policies.google.com/privacy

While you're in there, can you add a `.` to the end of `Select the page that shows the terms of use for Affiliate Registration` for consistency with the other descriptions:

<img width="716" alt="screen shot 2018-05-19 at 11 49 42 am" src="https://user-images.githubusercontent.com/52581/40262345-c7218538-5b5a-11e8-8b8a-9f136696930b.png">

**Comment by pippinsplugins** [comment]
Done.
