### ISSUE TITLE
Paid Member Subscriptions: integration not loaded any more

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#2638]
The Paid Member Subscriptions integration isn't working at all anymore. Referrals are not created and none of the admin options appear any more.

This is happening because the plugin removed the `pms_get_discount_by_code()` function that we used to detect when the plugin was active.

**Comment by pippinsplugins** [comment]
PR ready for testing.

**Comment by gspice** [comment]
First reported on this HS ticket:
https://secure.helpscout.net/conversation/568522197/81073?folderId=1170842

**Comment by gspice** [comment]
Downloaded the new branch for this issue and tested but referral was not created.

Testing steps:
* Setup a free subscription level for one month, zero cost, set referral amount for 20
* Have to be logged in as a user to subscribe (any user account)
* Made sure I had used a referral link
* Subscribed to the free level, it hangs for a while then receives an error, it's trying to use a secure link it seems?  

http://woo.local:8080/pm-subscriptions/?pms_gateway_payment_action=bmV3X3N1YnNjcmlwdGlvbg=&pmsscscd=c3Vic2NyaXB0aW9uX3BsYW5z

I did not see anything in the settings to bypass this for testing.  I also set the **Default Payment Gateway** to Manual/Offline but the result was the same.

**Comment by pippinsplugins** [comment]
I've just tested and this is working for me. Working with @gspice via Slack to determine the issue.

**Comment by pippinsplugins** [comment]
@gspice I've just pushed a number of additional fixes to this that should resolve the problem.

Can you please retest and send it to the affected customer?

**Comment by gspice** [comment]
@pippinsplugins 

UPDATE:  The issue wasn't with the add-on mentioned above, it is their add-on `Paid Member Subscriptions - Discount Codes Add-on`.     

When it's active, the debug log has this:  

```2018-5-03 20:56:37 - PMS: Referral creation stopped because customer was not referred and no affiliate discount was detected```

Going to test with that locally if I can download it.

**Comment by pippinsplugins** [comment]
@gspice in that case I'm going to go ahead and merge this. We can consider additional compatibility changes for that add-on if needed in another release.

**Comment by gspice** [comment]
After further testing, confirmed that with our *AffiliateWP 2.1.18* update and:

* Paid Member Subscriptions - Discount Codes Add-on 1.2.4 or higher
* Paid Member Subscriptions - Recurring Payments for PayPal Standard 1.1.1 or higher

Referrals are created with and without the recurring PayPal add on and discount codes assigned to affiliates create referrals as expected.
