### ISSUE TITLE
Update Hungarian translation strings

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2640]
A user notified us about this:

>AffiliateWP says: "Affiliate URL-ek" but pretty url means "Szép URL-ek"

>and this is the same with "credit last referrer": it says "Referált Hozzáadása", but that one just mean 'add referral', so that could be better: "Jóváírás a legutóbbi referáltnak".

Ticket: https://secure.helpscout.net/conversation/565424000/80752?folderId=205529.

**Comment by pippinsplugins** [comment]
Will merge after 2.2 is released.
