### ISSUE TITLE
Stay on current referrals page when rejecting or marking a referral as paid

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2650]
A user has sent in this bug on the referrals page: 
>I was noticing last night that when you reject a referral, it will take you back to page 1 instead of just refreshing on your current page.

Ticket: https://secure.helpscout.net/conversation/572255988/81428?folderId=205524.

**Comment by tubiz** [comment]
PR: #2651

**Comment by michaelbeil** [comment]
PR fixes the issue.
