### ISSUE TITLE
OptimizeMember integration with PayPal not working

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2657]
Our OptimizeMember integration with PayPal doesn't appear to be working for me. @tubiz Could you have a look and see if it works for you?

Here's my set up:

AffiliateWP 2.1.17 (also tested with 2.1.16 which is prior to some recent OM changes)
OptimizePress 2.5.13
OptimizeMember 1.2.9

OptmizeMember integration enabled from Affiliates -> Settings.

According to our integration code, these action hooks:

``` php
add_action( 'ws_plugin__optimizemember_before_sc_paypal_button_after_shortcode_atts', array( $this, 'set_referral_variable' ) );
add_action( 'ws_plugin__optimizemember_pro_before_sc_paypal_form_after_shortcode_atts', array( $this, 'set_referral_variable' ) );
```

Relate to the following shortcodes in OM:

`[optimizeMember-Pro-PayPal-Form]`
`[optimizeMember-PayPal-Button]`

I'm testing the `[optimizeMember-PayPal-Button]` shortcode, with the shortcode generated from the  "PayPal Buttons For Level Gold Member Access" section at `/wp-admin/admin.php?page=ws-plugin--optimizemember-paypal-buttons`.

Using a PayPal business account with the IPN URL provided from `/wp-admin/admin.php?page=ws-plugin--optimizemember-paypal-ops`.

Visits are working, but no referral is being generated when purchasing using. Clearly I must be doing something wrong?

**Comment by amdrew** [comment]
Can't seem to get Stripe working either.

**Comment by amdrew** [comment]
Cancel that, it appears to be working fine when PDT is enabled, at least for Pippin. IPN isn't working because our test site doesn't have an SSL cert set up, which PayPal now requires. Not sure why it's not working for me, it seems like I'm being blocked somehow.

**Comment by tubiz** [comment]
@amdrew I just tested the OptimizeMember integration (Stripe and PayPal) and it is working fine. 
The referrals were created and set to unpaid successfully.

**Comment by amdrew** [comment]
@tubiz Thanks for testing!
