### ISSUE TITLE
S2Member reference ID is no longer linked

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2658]
The S2Member reference ID in the reference column is no longer linked, it is just plain text. 
![5vyzaf](https://user-images.githubusercontent.com/4752949/39646911-4c15328c-4fdd-11e8-8e2e-d8610cbf8025.png) 

Ticket: https://secure.helpscout.net/conversation/573972896/81571?folderId=634609.

**Comment by pippinsplugins** [comment]
This has never been linked. S2Member doesn't store transaction records so there isn't anything to link it to.
