### ISSUE TITLE
Email settings are not saved in 2.2 Beta 1

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2659]
It seems like the email settings are not being saved correctly in our current beta version of 2.2. 

When you change the notifications and save the page, these settings do not save.

![tnurue](https://user-images.githubusercontent.com/4752949/39652789-0fbe360a-4fef-11e8-83bd-381a8b8a1f66.png)

However, this does _not_ occur in the `release/2.2` branch: https://github.com/AffiliateWP/AffiliateWP/tree/release/2.2.

Ticket: https://secure.helpscout.net/conversation/573471048/0/?folderId=205529.

**Comment by pippinsplugins** [comment]
@michaelbeil this works fine for me. Could you please test it on the latest `release/2.2` branch?

**Comment by pippinsplugins** [comment]
Michael confirmed in Slack that the settings save properly on latest `release/2.2`.
