### ISSUE TITLE
Application rejection email

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#266]
We currently have a tutorial on how to add a rejection email (http://affiliatewp.com/docs/affiliate-rejection-email/) but I feel like this should be part of core.

Affiliates who register currently have no way of knowing if they have been approved or not, yet the ones who are successful are sent an email.

**Comment by sumobi** [comment]
When we introduce this we should have the option to disable it. We should also allow the admin to specify a reason for the rejection on a case by case basis.

**Comment by pippinsplugins** [comment]
Looks like this is a duplicate.
