### ISSUE TITLE
Integration: Give donation form calculating incorrect referral amounts

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2662]
First reported on this HS ticket:
https://secure.helpscout.net/conversation/576139515/81733?folderId=1170842

AffiliateWP version 2.1.7 or beta 2.2:
Give - donation plugin 2.1.2

I setup a Give donation form test on our sandbox site here
http://s14890.p27.sites.pressdns.com/woo/donations/give-donation/

Donation was $10.00 or $100.00
Referral rate: 10%
Referral amount 0.01 in both cases

**Comment by tubiz** [comment]
PR: #2663

**Comment by gspice** [comment]
Tested and it is working great!   

* If the donation form does not have it's own rate, it uses the global rate. 
* If it _does_ have it's own referral rate, it correctly uses that resulting in the correct calculations.
