### ISSUE TITLE
Referrals not rejected with orders that have a canceled/failed status

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2668]
>The affiliate plugin recently registered successful affiliate payouts for orders that were never paid for in Woo and were ultimately 'Failed' orders. Why would the affiliate system log earnings / payouts for affiliates for orders that were not paid for, and were not successfully fulfilled? 

>The payment gateway used was PayPal.

Referrals screen:
![s51loh](https://user-images.githubusercontent.com/4752949/39943702-310ff8f0-5564-11e8-8748-7bab8057827c.png)
Orders screen:
![vfdwt6](https://user-images.githubusercontent.com/4752949/39943710-356d11bc-5564-11e8-8b4a-46c87bf70d81.png)  
Order details screen:
![qfixas](https://user-images.githubusercontent.com/4752949/39944244-3b20a040-5566-11e8-8ce8-b28d29a0006c.png)

Ticket: https://secure.helpscout.net/conversation/578606470/81964?folderId=205529.

>If an order gets automatically cancelled after staying in pending payment, it still shows "pending" status instead of rejected in referrals section.  

Ticket: https://secure.helpscout.net/conversation/565240795/0/?folderId=205529.

**Comment by pippinsplugins** [comment]
@michaelbeil can you please get a screenshot of the full order details screens?

**Comment by michaelbeil** [comment]
I went ahead and added that screenshot into my description above.

**Comment by tubiz** [comment]
A referral with a pending status can't be rejected.

https://github.com/AffiliateWP/AffiliateWP/blob/1bf0167bdcb77b94f6472e55efe2b8df3aa71b2e/includes/integrations/class-base.php#L262-L266

**Comment by pippinsplugins** [comment]
Leaving an order as pending is okay, I think. The tickets above, however, mention that referrals were marked as Unpaid somehow but then not changed to rejected.

@tubiz could you please test and confirm that unpaid referrals get rejected when an order is marked as failed or cancelled?

**Comment by tubiz** [comment]
@pippinsplugins I have tested this and noticed that unpaid referrals are not rejected for these order statuses transition.

- processing to failed
- completed to failed

I have submitted a PR to fix it.

PR: #2669

**Comment by pippinsplugins** [comment]
Thanks @tubiz! Merged into `release/2.2`.
