### ISSUE TITLE
Flat referral rate type generates a referral above $0 on a $0 subscription trial

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2674]
A flat referral rate type generates a referral that is greater then $0 on a $0 subscription trial.

A $0 referral is calculated correctly with the percentage referral rate type.

Ticket: https://secure.helpscout.net/conversation/582708275/82366?folderId=634609.

**Comment by pippinsplugins** [comment]
This is the correct behavior since a flat rate referral will _always_ come out equal to the amount defined as the "flat rate value".
