### ISSUE TITLE
Disable IP address logging

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2684]
We should add an option to disable IP address logging.  

Ticket: https://secure.helpscout.net/conversation/586272751/82700/.

**Comment by pippinsplugins** [comment]
@tubiz could you put this at the top of your list to finish?

**Comment by tubiz** [comment]
PR: #2690

**Comment by michaelbeil** [comment]
Related #2680.

**Comment by michaelbeil** [comment]
An IP address is not logged with the setting enabled to disable IP address logging in the attached PR.

**Comment by pippinsplugins** [comment]
@tubiz please see the one change request on the PR.
