### ISSUE TITLE
Undefined variable: args when updating a customer record in the Affiliate_WP_Customers_DB class

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/AffiliateWP#2688]
The notice below is shown when updating a customer record using the `update()` method in the `Affiliate_WP_Customers_DB` class

` PHP Notice:  Undefined variable: args in /app/public/wp-content/plugins/affiliate-wp/includes/class-customers-db.php on line 436`

**Comment by pippinsplugins** [comment]
Merged!
