### ISSUE TITLE
A description is not being made for referrals generated through WP Simple Pay

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2692]
For some reason, a description is not being made or referrals generated through WP Simple Pay.

Ticket: https://secure.helpscout.net/conversation/588791585/83007?folderId=205527.

**Comment by pippinsplugins** [comment]
Related https://github.com/AffiliateWP/AffiliateWP/issues/2672

**Comment by pippinsplugins** [comment]
@tubiz let's included this in the 2.2.6 release.

**Comment by tubiz** [comment]
@pippinsplugins working on it.

**Comment by tubiz** [comment]
PR: #2758

For a normal payment form, the referral description is set based on the text entered in the **Item Description** in the **Checkout Overlay Display** tab

<img width="969" alt="description details" src="https://user-images.githubusercontent.com/602184/42717249-5f004f6e-8708-11e8-8231-0006c26cf4ec.png">

For a subscription payment form, the name of the subscription product created in Stripe will be used.

If the **Item Description** is not set, the **Title** of the payment form will now be used.

**Comment by michaelbeil** [comment]
This PR fixes the issue! Here is a screenshot of the description now shown in the referrals page:  


![screen shot on 2018-07-14 at 15_31_20](https://user-images.githubusercontent.com/4752949/42724942-f138a9a8-877b-11e8-8a36-5098803d8812.png)


I had the following text entered in the **Item Description** field in the **Checkout Overlay Display** tab: ![screen shot on 2018-07-14 at 15_34_35](https://user-images.githubusercontent.com/4752949/42724944-fac7661c-877b-11e8-830b-20b6bfe524fd.png)
