### ISSUE TITLE
Password reset URL being sent out on affiliate application acceptance/pending email

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2695]
When the password field is required on an affiliate registration,  the application acceptance email includes a password reset URL:
![screen shot on 2018-05-30 at 13_41_48](https://user-images.githubusercontent.com/4752949/40718175-67703c2a-640f-11e8-8087-426e00336717.png)

Users do not want this password email reset link being sent out.

Tickets: 

- https://secure.helpscout.net/conversation/590892847/83212?folderId=634609
- https://secure.helpscout.net/conversation/589940485/83095?folderId=205529
- https://secure.helpscout.net/conversation/590721372/83198?folderId=205527

**Comment by tubiz** [comment]
PR: #2697

**Comment by michaelbeil** [comment]
PR fixes the issue.

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/595268364/83600/

**Comment by tubiz** [comment]
@michaelbeil this has been fixed and it will be in version 2.2.1

**Comment by michaelbeil** [comment]
Yes, I am well aware. I was simply making a note for a ticket. This user has been affected with this issue.

When 2.2.1 is released, I will send an update to the customer.

**Comment by michaelbeil** [comment]
This issue appears to be coming up again on a customer site: https://secure.helpscout.net/conversation/593642613/83434?folderId=634609.

I installed the latest version, but the password reset URL is still in the affiliate application acceptance email.

**Comment by tubiz** [comment]
PR: #2717

@michaelbeil help test the various affiliate registration process below
- Add registered user as an affiliate on the Add New Affiliate page in the admin
- Enable auto register new users as an affiliate, then add a new user on the Add New User page
- Set the password field to not required on the affiliate registration page then create a new affiliate account
- Set the password field to required on the affiliate registration page then create a new affiliate account
- Enable affiliate account approval and set the password field to not required on the affiliate registration page then create a new affiliate account
- Enable affiliate account approval and set the password field to required on the affiliate registration page then create a new affiliate account

**Comment by michaelbeil** [comment]
This works wonderfully:

![screen shot 2018-06-09 at 12 09 11](https://user-images.githubusercontent.com/4752949/41190400-f8aeef62-6bdd-11e8-9eac-d97d09bf6099.png)

A password reset URL is not included in the application accepted or pending email.

**Comment by michaelbeil** [comment]
Another customer is experiencing this issue: https://secure.helpscout.net/conversation/599762790/84022?folderId=205524.
