### ISSUE TITLE
affiliate_id customermeta not added in WooCommerce integration

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/AffiliateWP#2698]
When a referral is created via the WooCommerce integration the `affiliate_id` customermeta is not added because the WooCommerce integration isn't using the `insert_pending_referral()` method yet, which make sure that the `affiliate_id` is always set.

https://github.com/AffiliateWP/AffiliateWP/blob/677fdab97aa29a30842e04d824af2c062cceffed/includes/integrations/class-base.php#L148-L150

A PR #2647 has already been submitted for the WooCommerce integration  to use the `insert_pending_referral()` method which will fix the issue, alternatively we can add the `affiliate_id` to the `get_customer()` method in the `Affiliate_WP_WooCommerce` class

https://github.com/AffiliateWP/AffiliateWP/blob/677fdab97aa29a30842e04d824af2c062cceffed/includes/integrations/class-woocommerce.php#L353-L373

- N.B
This need to be fixed for the WooCommerce integration in the Lifetime Commissions add-on to work properly.

**Comment by pippinsplugins** [comment]
Let's take care of this through #2647
