### ISSUE TITLE
WooCommerce: Leaving "Affiliate Rate" field blank doesn't use default rate

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2704]
Tested with latest AffiliateWP master and WooCommerce 3.4.1. 

On a WooCommerce product, when `Affiliate Rate` is left blank, it's generating $0.00 referrals. Like the help tooltip suggests next to the input field, leaving the field blank should use the default rate. In my case that should be `20%`, which is the global referral rate.

### Example 1:
$100 product
Global referral rate of 20%
`Affiliate Rate Type` on product set from `Site Default` to `Percentage`
Expected referral rate: $20 (20% of $100)
Actual referral rate: $0.00 

<img width="787" alt="screen shot 2018-06-01 at 11 42 16 am" src="https://user-images.githubusercontent.com/52581/40813886-42c336ec-6591-11e8-8599-47d407a44e27.png">

### Example 2:
$100 product
Global referral rate of 20%
`Affiliate Rate Type` on product set from `Site Default` to `Flat USD`
Expected referral rate: $20 (flat amount)
Actual referral rate: $0.00 

<img width="786" alt="screen shot 2018-06-01 at 12 23 47 pm" src="https://user-images.githubusercontent.com/52581/40814809-a75b9f4a-6596-11e8-8d5e-5226529f8274.png">

<img width="556" alt="screen shot 2018-06-01 at 11 42 23 am" src="https://user-images.githubusercontent.com/52581/40814815-adfbb038-6596-11e8-8e50-0de0024d4927.png">

<img width="1075" alt="screen shot 2018-06-01 at 12 24 10 pm" src="https://user-images.githubusercontent.com/52581/40814820-b73df944-6596-11e8-9cb1-a67c238dcddb.png">

**Comment by tubiz** [comment]
PR: #2707

**Comment by amdrew** [comment]
@tubiz @pippinsplugins Works for me. Tested with the Referral Rate Type set to Percentage and Flat, and both referrals were generated at the correct amounts.
