### ISSUE TITLE
WooCommerce: Referral should not be created when product has referrals disabled

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2705]
Tested with latest AffiliateWP master and WooCommerce 3.4.1.

If you disable referrals on a WooCommerce product, the referral is generated without a description.

<img width="778" alt="screen shot 2018-06-01 at 12 50 18 pm" src="https://user-images.githubusercontent.com/52581/40815470-d824f7c6-659a-11e8-9fbc-cce9ac5173b3.png">

<img width="1078" alt="screen shot 2018-06-01 at 12 54 00 pm" src="https://user-images.githubusercontent.com/52581/40815476-e158dae2-659a-11e8-8384-45568366ea60.png">

___

Errors:

```
PHP Notice:  Undefined variable: args in /wp-content/plugins/AffiliateWP/includes/class-customers-db.php on line 427
```

And again:

```
PHP Notice:  Undefined variable: args in /wordpress/wp-content/plugins/AffiliateWP/includes/class-customers-db.php on line 429
```

```
PHP Notice:  wpdb::prepare was called <strong>incorrectly</strong>. Unsupported value type (array). Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 4.8.2.) in /wordpress/wp-includes/functions.php on line 4148
```

```
PHP Warning:  mysqli_real_escape_string() expects parameter 2 to be string, array given in /wordpress/wp-includes/wp-db.php on line 1102
```

**Comment by tubiz** [comment]
@amdrew the PHP notice has been fixed in this PR: #2647 which was merged into master after you tested.

For the empty referral description, the default AffiliateWP behaviour is not to generate the description for any product that is disabled for referrals.

**Comment by amdrew** [comment]
@tubiz I think the actual issue here is not that the description is blank, but rather there's a referral generated at all. If a product is blocked from generating referrals, a referral should _not_ be created. 

Here's the relevant setting in WooCommerce:

<img width="743" alt="screen shot 2018-06-04 at 11 29 53 am" src="https://user-images.githubusercontent.com/52581/40892388-9fef66aa-67ea-11e8-9cc2-9de83b682c8f.png">

> This will prevent orders of this product from generating referral commissions for affiliates.

It should _prevent_ the referral being generated, not create it without a description.

As an affiliate, the following is unhelpful and irrelevant:

<img width="898" alt="screen shot 2018-06-04 at 11 26 50 am" src="https://user-images.githubusercontent.com/52581/40892393-c4038f30-67ea-11e8-837e-4b104b3df309.png">

Testing with Easy Digital Downloads, when a download is blocked from generating referrals, a referral is never created, for free or paid downloads. This is how it should work.

Do you agree?

**Comment by tubiz** [comment]
@amdrew yes I totally agree, a referral is not to be created. I was able to replicate the issue.

**Comment by tubiz** [comment]
@andrew if the disable referrals checkbox is checked for a product in WooCommerce and a customer purchase that product and two other products, a referral is generated based on the two other products.

Testing with Easy Digital Downloads, if two downloads are purchased one with referrals disabled, a referral is generated based on the other download.

We need to make sure that if a single product with referral disabled is purchased no referral should be created for it.

We might need to change this text `This will prevent orders of this product from generating referral commissions for affiliates.` to `This will prevent this product from generating referral commissions for affiliates.`

Related #2552

**Comment by pippinsplugins** [comment]
>>>We need to make sure that if a single product with referral disabled is purchased no referral should be created for it.

@tubiz please go ahead and make this change.

**Comment by amdrew** [comment]
@tubiz The text change sounds good

**Comment by tubiz** [comment]
PR: #2712

**Comment by amdrew** [comment]
Ta, will test

**Comment by amdrew** [comment]
@tubiz @pippinsplugins This looks good to me.

One small note, but I feel it deserves its own issue so ignore for now:

The error being logged is `Referral not created due to empty description`. This could lead to a support ticket: "Why does my referral have an empty description"?

That error is misleading since the actual reason is the product had it's referrals disabled.

If we agree, I'll open a new issue for this since the PR on this issue is simply being consistent with the other integrations that log the same error.
