### ISSUE TITLE
When cancelling PayPal order, referral should move to rejected status if misc option is enabled

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2706]
Tested with latest AffiliateWP master and WooCommerce 3.4.1.

When completing checkout with the PayPal payment gateway and cancelling the order from the PayPal screen, I would expect the `Pending` referral to then have a `Rejected` status, if `Reject Unpaid Referrals on Refund` is enabled from the Misc settings. This doesn't seem to be the case. The order is cancelled, but the referral remains at Pending.

Shouldn't this match the behavior of going to a WooCommerce order (or EDD etc) and cancelling it, which does update the status of the linked referral to Rejected?

**Comment by tubiz** [comment]
@amdrew you are right, the referral is meant to be cancelled when a transaction is refunded on PayPal and the "Reject Unpaid Referrals on Refund" checkbox is checked on the AffiliateWP settings page.

I was able to trace this issue to WooCommerce, as an order isn't set to refunded in WooCommerce when the transaction for the order is fully refunded on PayPal.

I have submitted a new issue for this on the WooCommere repository https://github.com/woocommerce/woocommerce/issues/20551, so once it is fixed, that should fix this issue.

**Comment by amdrew** [comment]
Great 👍

**Comment by tubiz** [comment]
WooCommerce 3.4.3 has been released to fix the issue with order status not set to refunded when a PayPal transaction is refunded.

I have tested it and a referral is now set to rejected when a PayPal order is refunded.

This issue can be closed.

**Comment by pippinsplugins** [comment]
:100:
