### ISSUE TITLE
Error when viewing affiliate's payout

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2709]
Reported by customer here:
https://secure.helpscout.net/conversation/592914428/83390?folderId=205527

I have replicated the issue on both the customer's site and my own test site (using latest master branch).

### To replicate:

1. View the payouts screen (`/wp-admin/admin.php?page=affiliate-wp-payouts`) and then click on a payout to view it. Take note the URL:

    `/wp-admin/admin.php?page=affiliate-wp-payouts&payout_id=20&action=view_payout`

2. In a new tab, open the same payouts screen (`/wp-admin/admin.php?page=affiliate-wp-payouts`) but this time click on an affiliate's name in the third column to view only payouts for that specific affiliate.

3. Find the same payout from step 1 and click "view" in the far right column. You'll get this error (and more):

    ```

    WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE `payout_id` IN( 20 ) AND `status` = 'paid'' at line 1 for query SELECT COUNT(referral_id) FROM wp_77_affiliate_wp_referrals WHERE `affiliate_id` IN( 16 ) WHERE `payout_id` IN( 20 ) AND `status` = 'paid' ; made by do_action('affiliates_page_affiliate-wp-payouts'), WP_Hook->do_action, WP_Hook->apply_filters, affwp_payouts_admin, include('/plugins/AffiliateWP/includes/admin/payouts/view.php'), AffWP_Referrals_Table->__construct, AffWP_Referrals_Table->get_referral_counts, Affiliate_WP_Referrals_DB->count, Affiliate_WP_Referrals_DB->get_referrals, Affiliate_WP_DB->get_results
    ```
    Compare the URL to the first URL above:

    `/wp-admin/admin.php?page=affiliate-wp-payouts&action=view_payout&affiliate_id=16&payout_id=20`

Same page, different URL, one with errors that can prevent the data from being shown.

**Comment by tubiz** [comment]
PR: #2710
