### ISSUE TITLE
WooCommerce integration - internal error displayed when users go to checkout page

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2715]
First reported on this HS ticket:
https://secure.helpscout.net/conversation/596202241/83699?folderId=1170842

AffiliateWP: 2.2.1
WooCommerce: 2.6.8

User receives `Internal Error` when going to the WC checkout page when AffiliateWP is active.  In the error logs it lists:  

```
PHP Fatal error: Call to undefined method WC_order::get_billing_email() 
in /affiliate-wp/includes/integrations/class-woocommerce.php on line 363
```

**Comment by tubiz** [comment]
PR: #2716

**Comment by DrewAPicture** [comment]
At some point, it might not be a bad idea to add a WooCommerce version check helper into AffiliateWP core. We added one awhile back in the Order Details for Affiliates add-on: https://github.com/AffiliateWP/affiliatewp-order-details-for-affiliates/blob/master/affiliatewp-order-details-for-affiliates.php#L407-L423

**Comment by michaelbeil** [comment]
Another user reported this issue: https://secure.helpscout.net/conversation/597410916/83820?folderId=205524.
