### ISSUE TITLE
Customer with Kinsta hosting and WP Rocket unable to register new affiliates

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2720]
Reported on customer HS ticket:
https://secure.helpscout.net/conversation/567035939/80890?folderId=1170842

AffiliateWP: 2.2.2
Host: Kinsta
Plugin conflict: WP Rocket

_Customer has login credentials to a staging site on the HS ticket, free to do anything you need to on that site._ 

* To reproduce from the frontend, go to https://staging-avalonking.kinsta.com/ambassadors/join/ and register as an affiliate, you will receive a white screen.  Behind the scenes, the WP user is created but it fails when attempting to make the new user an affiliate. 

* When logged in as an admin, go to _Affiliates -> Affiliates -> Add New_, select an existing WP user or create a new one, you will receive a `HTTP 500` error.  Same result, WP user is created, but not the affiliate entry.

* On the flip side, you can create a new WP user, and tick the box to make an affiliate, that works correctly.

Site's php error log contents for this fatal error:

```
2018/06/11 18:14:30 [error] 2536#2536: *7776 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function purge_complete_caches() on null in /www/avalonking_290/public/wp-content/plugins/wp-rocket/inc/3rd-party/hosting/kinsta.php:22
Stack trace:
#0 /www/avalonking_290/public/wp-includes/class-wp-hook.php(288): rocket_clean_kinsta_cache('/www/avalonking...')
#1 /www/avalonking_290/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /www/avalonking_290/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /www/avalonking_290/public/wp-content/plugins/wp-rocket/inc/functions/files.php(700): do_action('after_rocket_cl...', '/www/avalonking...', 259, 'https://staging...')
#4 /www/avalonking_290/public/wp-includes/class-wp-hook.php(286): rocket_clean_domain(259)
#5 /www/avalonking_290/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /www/avalonking_290/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#7 /www/avalonking_290/public/wp-includes/user.php(1773):" while reading response header from upstream, client: 68.118.73.226, server: staging-avalonking.kinsta.com, request: "POST /wp-admin/admin.php?page=affiliate-wp-affiliates&action=add_affiliate HTTP/1.0", upstream: "fastcgi://unix:/var/run/php7.2-fpm-avalonking.sock:", host: "staging-avalonking.kinsta.com", referrer: "https://staging-avalonking.kinsta.com/wp-admin/admin.php?page=affiliate-wp-affiliates&action=add_affiliate"
```

**Comment by michaelbeil** [comment]
The same customer with this issue is contacting us again from a different ticket: https://secure.helpscout.net/conversation/599774326/84025/?folderId=634609.

**Comment by michaelbeil** [comment]
>Thanks for updating. When I asked Kinsta about it, they found out that it was recently fixed from WP Rocket' side. 

https://github.com/wp-media/wp-rocket/commit/c355151aa19ba278ef03df4b0f78ec378dd8ead3#diff-873b14d655f43cfb9aebeb4215498318
>So thank you! :-)
