### ISSUE TITLE
Customer not linked to the affiliate in PayPal integration

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/AffiliateWP#2721]
A customer is never linked to the affiliate in the PayPal integration as the customer email is not available when the pending referral is created when the PayPal button is clicked.

The customer will have to be linked when the referral is mark as complete when the IPN is sent.

Related: https://github.com/AffiliateWP/affiliate-wp-lifetime-commissions/issues/47

**Comment by tubiz** [comment]
PR: #2724

**Comment by pippinsplugins** [comment]
PR looks good here.

@amdrew could you please test it along with https://github.com/AffiliateWP/affiliate-wp-lifetime-commissions/issues/47?

**Comment by amdrew** [comment]
@tubiz @pippinsplugins 👍 Tested and it correctly links up the customer with the affiliate.

**Comment by amdrew** [comment]
There seems to be an issue with delinking the customer and affiliate manually, and then re-linking them. Have outlined this on the other issue, seems like it's more of a LC thing.

**Comment by tubiz** [comment]
> There seems to be an issue with delinking the customer and affiliate manually, and then re-linking them. Have outlined this on the other issue, seems like it's more of a LC thing.

I was able to replicate this issue. If an existing customer is unlinked from an affiliate, re-linking the customer to any affiliate doesn't work. I will create an issue for it.

**Comment by pippinsplugins** [comment]
@tubiz ready to go?

**Comment by tubiz** [comment]
@pippinsplugins Yes.
