### ISSUE TITLE
Add hook to the conversion_script() method

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/AffiliateWP#2722]
Add a do_action `affwp_before_track_conversion` to the `conversion_script()` method immediately after `L181` here https://github.com/AffiliateWP/AffiliateWP/blob/c0b566c401a808cdf2029cf50bfd3c45ac2f6b51/includes/class-tracking.php#L141-L227

This will allow the Lifetime Commissions add-on to work with the `[affiliate_conversion_script]` shortcode.

Related: https://github.com/AffiliateWP/affiliate-wp-lifetime-commissions/issues/20

**Comment by tubiz** [comment]
PR: #2723

**Comment by pippinsplugins** [comment]
The hook you've added is great though I think it needs some adjustment.

The name of the hook and the associated docs give the impression that the hook fires when a conversion is tracked, but that's not quite accurate. The hook is firing right before the JS that _maybe_ fires off a conversion creation is triggered. It really should be named something like `affwp_before_conversion_tracking_script`.

**Comment by tubiz** [comment]
PR updated.

**Comment by pippinsplugins** [comment]
Merged.
