### ISSUE TITLE
Clearing out terms label should show default text

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2726]
As discussed in https://github.com/AffiliateWP/AffiliateWP/issues/2713#issuecomment-397908622, clearing out the terms label should not show a blank field. This is confusing, since the text is blank in the admin, yet the front-end shows text:

<img width="1651" alt="screen shot 2018-06-18 at 9 40 51 am" src="https://user-images.githubusercontent.com/52581/41512490-195e7be6-72dd-11e8-8c08-94efd3f2d94d.png">

Instead, when the field is cleared out, it should show the default text specified in the codebase: https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/admin/settings/class-settings.php#L487

This has the added bonus of showing the translated text in another language, if it's available.

<img width="1671" alt="screen shot 2018-06-18 at 9 41 15 am" src="https://user-images.githubusercontent.com/52581/41512493-23bb04d8-72dd-11e8-8d6b-edc530f08a53.png">

**Comment by tubiz** [comment]
PR: #2728

**Comment by gspice** [comment]
Thank you for this change @amdrew and @tubiz .  This makes it a lot easier to understand working with, and creating translation changes.
