### ISSUE TITLE
This error is showing up on the referrals table

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2729]
A customer is experiencing the following error:

>Fatal error: Uncaught Error: Call to a member function type() on boolean in /home/s793/html/wp-content/plugins/AffiliateWP-2.2.3/includes/admin/referrals/class-list-table.php:251 Stack trace: #0 /home/s793/html/wp-admin/includes/class-wp-list-table.php(1254): AffWP_Referrals_Table->column_default(false, 'type') #1 /home/s793/html/wp-admin/includes/class-wp-list-table.php(1192): WP_List_Table->single_row_columns(false) #2 /home/s793/html/wp-admin/includes/class-wp-list-table.php(1180): WP_List_Table->single_row(false) #3 /home/s793/html/wp-admin/includes/class-wp-list-table.php(1165): WP_List_Table->display_rows() #4 /home/s793/html/wp-admin/includes/class-wp-list-table.php(1097): WP_List_Table->display_rows_or_placeholder() #5 /home/s793/html/wp-content/plugins/AffiliateWP-2.2.3/includes/admin/referrals/referrals.php(99): WP_List_Table->display() #6 /home/s793/html/wp-includes/class-wp-hook.php(286): affwp_referrals_admin('') #7 /home/s793/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #8 /home in /home/s793/html/wp-content/plugins/AffiliateWP-2.2.3/includes/admin/referrals/class-list-table.php on line 251

I have not been able to replicate this issue yet.

Ticket: https://secure.helpscout.net/conversation/600924552/84152?folderId=634609.

**Comment by DrewAPicture** [comment]
Probably the result of a referral being deleted or similar. Tracing it back, essentially a single referral is returning `false` during the `get_referrals()` step. I can't actually reproduce it but it's possible in theory. We can probably close this in lieu of more reports.

- `WP_List_Table->column_default()`
- `WP_List_Table->single_row_columns()`
- `WP_List_Table->single_row()`
- `WP_List_Table->display_rows()` iterates over `$items` which is generated via `AffWP_Referrals_Table->get_data()` which uses `get_referrals()`

**Comment by tubiz** [comment]
PR: #2730 

#### To Replicate
- Edit any referral directly in the database and set the `referral_id` field to `0`.
- Visit the referral page, the referral with the `referral_id` set to `0` will display a fatal error

#### Screenshot of how an invalid referral will now be displayed.

<img width="1257" alt="issue-2729" src="https://user-images.githubusercontent.com/602184/41650018-b524a2c2-7485-11e8-8b7a-83107f830abe.png">

**Comment by michaelbeil** [comment]
This PR fixes the issue.

**Comment by DrewAPicture** [comment]
I'm concerned that we're not actually fixing the problem. The PR essentially makes (more) graceful degradation possible by checking if each result of the query is valid before trying to access it, which is all well and good but the actual problem here is that `get_referrals()` is sometimes returning invalid results. We should solve for _that_. This feels like a band-aid.

**Comment by tubiz** [comment]
@DrewAPicture I will update the PR to fix that as well.

**Comment by tubiz** [comment]
@DrewAPicture PR updated

**Comment by pippinsplugins** [comment]
Nice and simple fix. I like it.

**Comment by michaelbeil** [comment]
The customer has gotten into contact with us again to see if this error has been resolved. Is there any chance we can put this into 2.2.4?

**Comment by pippinsplugins** [comment]
It's going into 2.2.4.
