### ISSUE TITLE
Generate a report that shows the total revenue that is generated in a shop from an affiliate

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2732]
>Inside of the admin area, you can view what referrals have been generated and are connected to a specific referred order. This will not generate a report of all the revenue that is generated in your shop, this will just show the total number of referrals an affiliate makes.

Ticket: https://secure.helpscout.net/conversation/604675468/84499?folderId=634609.

**Comment by pippinsplugins** [comment]
Duplicate of https://github.com/AffiliateWP/AffiliateWP/issues/492
