### ISSUE TITLE
Application Accepted Email

### ISSUE THREAD

**Issue by AiratHalitov** [AffiliateWP/AffiliateWP#2735]
Can you send **Application Accepted Email** only after user's email adress will be confirmed?

### Steps:
1. Enable settings in AffiliateWP:
**Auto Register New Users** _Automatically register new users as affiliates._
**Email Notifications** _Notify affiliate when their affiliate application is accepted_
2. Try to register on site (with BuddyPress and AffiliateWP)
3. You will receive **Application Accepted Email** from AffiliateWP before your email adress will be accepted and WordPress account activated.

In this situation email adress can be wrong. Or user can forget activate his account. 

### Configuration:

- AffiliateWP 2.2.3 
- BuddyPress 3.1.0
- WordPress 4.9.6

**Comment by michaelbeil** [comment]
Are you saying that the user's email address has not been confirmed by an administrator?

**Comment by AiratHalitov** [comment]
No. 
User should click on the activation link in first email (double opt-in) and then account will be activated and you can send them your emails.

**Comment by michaelbeil** [comment]
Alright. Can you send a ticket to https://affiliatewp.com/support as we reserve this repository for development purposes? Then I can help you look into this issue.

**Comment by AiratHalitov** [comment]
But it's development issue.

**Comment by AiratHalitov** [comment]
> Alright. Can you send a ticket to https://affiliatewp.com/support as we reserve this repository for development purposes? Then I can help you look into this issue.

Done
