### ISSUE TITLE
Add a notice for an existing WordPress user to login in order to register to be an affiliate 

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2737]
A customer is wanting to make it easier for an existing WordPress user to register to be an affiliate. Perhaps we should display a notice for any existing WordPress user to login, in order to register to be an affiliate.

Here is the document that we have for how an existing WordPress user can register to be an affiliate: https://docs.affiliatewp.com/article/2004-how-can-an-existing-customer-become-an-affiliate-it-tells-them-their-email-is-already-in-use.

Ticket: https://secure.helpscout.net/conversation/590157957/83116?folderId=634609.

**Comment by gspice** [comment]
They can add a note like that to the WP page being used for registration, above or below the shortcode.

**Comment by michaelbeil** [comment]
I thought about that before. Would you make a note of that on the document?

**Comment by michaelbeil** [comment]
I added a note to that document. Feel free to parse it out more.

**Comment by gspice** [comment]
Looks good to me.
