### ISSUE TITLE
Show referral ID column on referrals admin screen

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2738]
I think we should show a `Referral ID` column on the referrals screen in the admin:

1. Consistency with the `Visits` screen. This shows a `Visits ID` column as well as a `Referral ID` column.

2. We can then move the lifetime referrals link icon in Lifetime Commissions from the `Affiliate` column and place it in the `Referral ID` column. Since it's a lifetime referral, it makes more sense to relate this icon to the referral, rather than the name of the affiliate. 

    Issue: https://github.com/AffiliateWP/affiliate-wp-lifetime-commissions/issues/31

3. This would make it easier to flick between the visits and referral screens and match rows of interest, since they would both have the referral ID.

**Comment by tubiz** [comment]
PR: #2739
