### ISSUE TITLE
Add support for HTML 5 banners

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2748]
This is from a presale question:

>Is html5 banners something you plan on implementing since this is now the preferred banner format?

Should we add support for HTML5 banners?

Ticket: https://secure.helpscout.net/conversation/611937931/85148?folderId=634609.

**Comment by amdrew** [comment]
We have an issue open for different creative types (including HTML banners):
https://github.com/AffiliateWP/AffiliateWP/issues/1087
