### ISSUE TITLE
Award commission to selected affiliate when order is manually placed

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/AffiliateWP#2751]
When an order is manually added via an eCommerce system like WooCommerce or EDD, it would be nice if the referral can be awarded to a selected affiliate.

This would be an admin option to enable this feature.

First discussed here: https://github.com/AffiliateWP/affiliate-wp-lifetime-commissions/issues/38

**Comment by amdrew** [comment]
Issue here: https://github.com/AffiliateWP/AffiliateWP/issues/1150
