### ISSUE TITLE
Affiliate hierarchical earnings

### ISSUE THREAD

**Issue by cristan90** [AffiliateWP/AffiliateWP#2753]
Hello! I wanted to know if it was possible to have an affiliate who earns on other affiliates that he brings. For example: I bring two new affiliates on the site and I want to earn on what they receive from their customers. It's possible? is it possible to associate an order with a specific affiliate in backend only for administrator role? Thanks

**Comment by michaelbeil** [comment]
For any support-related questions, we ask that you send a ticket to https://affiliatewp.com/support as we reserve this repository for development purposes. I have sent a response to your ticket.

**Comment by cristan90** [comment]
Great, thanks!
