### ISSUE TITLE
Customer record not created for Opt-In Form referrals.

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/AffiliateWP#2754]
A customer record is not created for any referrals created through the Opt-In Form.

Related: https://github.com/AffiliateWP/affiliate-wp-lifetime-commissions/issues/65

**Comment by pippinsplugins** [comment]
@tubiz let's go ahead and get this fixed up for a point release of 2.2.6.

**Comment by tubiz** [comment]
PR: #2755

**Comment by pippinsplugins** [comment]
@gspice able to test this?

**Comment by gspice** [comment]
Verified!  Testing with MailChimp opt-in settings and the opted-in email created the referral and is connected to my affiliate via Lifetime Commissions now as well.  👍
