### ISSUE TITLE
There's no hook to modify data in referral before its insertion in DB, neither to prevent its creation

### ISSUE THREAD

**Issue by davefx** [AffiliateWP/AffiliateWP#2759]
While developing some complex rules that should modify and/or prevent the creation of referrals, I've found that there are currently no hooks that allow this feature.

**Comment by pippinsplugins** [comment]
@davefx there is a filter for this already in the base DB class: https://github.com/davefx/AffiliateWP/blob/2b7bc7b41b0ad9f6a1e006cc8582c950c2a8b54a/includes/abstracts/class-db.php#L243
