### ISSUE TITLE
Guest customer not linked to user profile if user account is created later on.

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/AffiliateWP#2765]
If a user account is later created for a guest customer, the customer record is not linked to the user account for the customer.

Related: https://github.com/AffiliateWP/affiliate-wp-lifetime-commissions/issues/103

**Comment by tubiz** [comment]
PR: #2766 

@gspice please help test.

**Comment by gspice** [comment]
Verified fix! Used email addresses that were already linked to my affiliate via LC, but previously did not have WP user accounts. I created an account during the Woo purchase, and the link was updated with a page refresh.
