### ISSUE TITLE
Referrals are not generated with a long campaign name

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2781]
When you use an affiliate link like `http://sitename.com/product/test/ref/1/?campaign=PAScribeCopperplateScriptManual`, a referral will not be generated.

Error log:

> 2018-8-07 18:46:25 - Arguments being sent to DB: array (
 'amount' => 25,
 'reference' => 1328,
 'description' => 'Test',
 'campaign' => 'PAScribeCopperplateScriptManual',
 'affiliate_id' => 1343,
 'visit_id' => 89,
 'products' => 'a:1:{i:0;a:4:{s:4:"name";s:4:"Test";s:2:"id";i:201;s:5:"price";i:100;s:15:"referral_amount";s:2:"25";}}',
 'custom' => 'a:1:{s:12:"affiliate_id";i:1343;}',
 'type' => 'sale',
 'context' => 'woocommerce',
 'customer' =>
 array (
   'user_id' => 0,
   'email' => 'michaelbeil+testcampaign@me.com',
   'first_name' => 'Michael',
   'last_name' => 'Beil',
   'ip' => 'xx.xxx.xxx.xxx',
 ),
)
2018-8-07 18:46:25 - Pending referral could not be created due to an error.
2018-8-07 18:46:25 - Referral failed to be created.
2018-8-07 18:46:26 - Referral could not be retrieved by reference during complete_referral(). Reference value given: 1328`

This was discovered on this ticket: https://secure.helpscout.net/conversation/635512153/87380/.

**Comment by tubiz** [comment]
The length of the `campaign` (VARCHAR) field is `30` characters in the `affiliate_wp_referrals` table while the campaign name the affiliate used `PAScribeCopperplateScriptManual` is `31` characters, the reason the referral wasn't created.

Should we increase the length of the `campaign` field to 50 characters?

**Comment by pippinsplugins** [comment]
Yes, let's increase the campaign name length.

**Comment by tubiz** [comment]
PR: #2782
