### ISSUE TITLE
Stats above graphs should update when graph is filtered

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#313]
When graphs are filtered (affiliate stats etc) we should update the stats above to reflect the custom date ranges the user has chosen. We should also remove the overall totals on the affiliate stats page and leave it to the graphs default date range.

**Comment by sumobi** [comment]
Looks like this could be addressed in 1.8.

**Comment by pippinsplugins** [comment]
This should be coupled with #1076

**Comment by ramiabraham** [comment]
_(Closing in favor of #1525, as it's added there)_
