### ISSUE TITLE
Per-Product, per affiliate referral rates add-on?

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#371]
@pippinsplugins Do you think adding a UI for https://github.com/affiliatewp/AffiliateWP/issues/369 be good (dev) add-on territory? The use-case for something like this is rather low so may not warrant being included in core.

The add-on could simply make it easier to do this without having to resort to using the filter.

**Comment by sumobi** [comment]
https://github.com/sumobi/affiliatewp-affiliate-product-rates

**Comment by pippinsplugins** [comment]
Approved in repo.
