### ISSUE TITLE
Ability to easily track referral links with additional query strings used

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#372]
A customer has suggested they'd like affiliates to be able to use query string parameters to better track their marketing efforts. This is actually already possible but I think we could potentially do something better with the reporting side of things.

So for example, affiliate B decides he's going to run 2 campaigns, one for twitter, and one for facebook. He would use his referral links like this:

`/?ref=123&source=facebook`
`/?ref=123&source=twitter`

The query strings are shown fine in the visits tab of the admin:
![screen shot 2014-09-01 at 8 54 13 pm](https://cloud.githubusercontent.com/assets/52581/4125905/2dddd69c-32e6-11e4-865d-2674068b2346.png)

They are also shown in the affiliate's dashboard
![screen shot 2014-09-01 at 8 53 07 pm](https://cloud.githubusercontent.com/assets/52581/4125906/2df5f47a-32e6-11e4-8736-fe486fdea243.png)

What isn't clear though is how many hits the affiliate received for each query string at a glance, and what the success rate was.

Here is what the customer has suggested:

<blockquote>
here is a quick idea with each unique Refferal URL having an accordion drop down with more information on the referrals and then the ability to custom name those links and, if desired, add them as a graph to the Graphs Page.
</blockquote>

And their mockup:

![affiliatewp-ui-idea](https://cloud.githubusercontent.com/assets/52581/4125957/9bfca77a-32e6-11e4-92f4-a7ad632df36c.jpg)

My first thought it to have a completely separate table, which only shows visits that query strings have been used in. Instead of listing each as a separate row, it simply groups them by count, and shows a percentage indicator, similar to the customer's mockup. I like the idea of not touching the main visits table, but it should still show each query string visit.

As you can see in the screenshot above the customer has also expressed interest in having graphs for these query strings.

Open for discussion!

**Comment by worldtravlr** [comment]
Hi awesome people!  Just wanted to check back on this to see if there are any roadmap dates for this feature or if it is a unique request that not many customers are requesting?  I know about half of our 100 affiliates have specifically asked for this feature so that they can track the different conversion rates for Facebook, Twitter, Newsletter, Website, Good Ads, etc. and then determine where to focus their money and attention.  Thanks for any update and keep up the awesome work!

**Comment by pippinsplugins** [comment]
We haven't worked on it yet, sorry.

It's definitely an awesome feature but, interestingly, not one that many people have requested. That might be because they don't realize they want it.

**Comment by worldtravlr** [comment]
Thanks for the update and totally understand.  Love all the Add-Ons you and the team are making and it is obvious you are busy putting a lot of time and care into the Affiliate WP product and powerful Add-Ons so please know it is all appreciated and keep up the awesome work!

Makes sense that this is may be a feature many may not realize they would like.  Could I suggest the possibility of sending out a survey either to all current members or maybe just top rated ones with the different Add-On Options you are looking to work on and seeing which ones they want the most or first?  Just an idea, but glad to wait as I know you and your team are putting your heart into this amazing product and I am loving every new Add-On you come out with!

Thanks @pippinsplugins and all the best!

**Comment by jetlej** [comment]
+1

**Comment by sumobi** [comment]
Made some progress on this, will submit a PR in the coming week:

I started by supporting Google's campaign tracking parameters (utm_source, utm_campaign, utm_medium etc) but quickly decided against it. An affiliate will likely use whichever query string parameters they want, we can't force them to stick to using one of those parameters. 

Also, according to Google's generator tool, all 3 parameters must be used together. If the affiliate misspelt one of the parameters they wouldn't show in our stat table.

Instead, I like @pippinsplugins` suggestion https://github.com/affiliatewp/AffiliateWP/issues/372#issuecomment-54221253 to simply group each unique URL. This means the affiliate has the freedom to use whichever query string parameter they'd like, and can use more than one in the same URL. Eg:

http://yoursite.com/ref/123/?c=twitter
http://yoursite.com/ref/123/?campaign=facebook
http://yoursite.com/ref/123/?campaign=twitter&date=june2015

If we group each unique URL and keep it simple we end up with something that looks like this:

![screen shot 2015-07-06 at 10 05 25 pm](https://cloud.githubusercontent.com/assets/52581/8520043/271bbad6-242b-11e5-9934-3c067001d5b0.png)

### Visits

Some have mentioned that this is not valuable data. We can either not show it at all or leave it showing by default. I vote we include it - since it's a template file it's very easy to remove the column from the table.

I think the above is sufficient for v1.7, but here's what we should consider going forward:

### Labels/campaign names

An affiliate could label each URL. Perhaps this is done by either clicking an "add campaign label" link or hovering over the URL. Both would show an inline input field and save button. I like the idea of showing a campaign name and URL, perhaps the label can simply sit on top of the URL, adding a new column would take up too much space.

### Coupons

Showing coupons in the tables gets a little messy as outlined in https://github.com/affiliatewp/AffiliateWP/issues/627. I vote we simply create a new table just for showing coupons as @bekarice suggested. It'd be much easier to separate coupons from URLs.

### Total value

As suggested in https://github.com/affiliatewp/AffiliateWP/issues/627 it would nice to have a new column to show the total value of the campaign. This will need to be implemented on a per-integration basis.

**Comment by pippinsplugins** [comment]
I really like this.

We could also potentially add the ability to search/filter these stats. If an affiliate has hundreds of unique URLs, they may want to see only a specific subset of them.

**Comment by sumobi** [comment]
:+1:

**Comment by bekarice** [comment]
@sumobi looks like great :smile_cat: 

> We could also potentially add the ability to search/filter these stats.

love that idea

**Comment by worldtravlr** [comment]
This is awesome @sumobi!  Thanks so much for coding some progress on this idea and bringing it to life a bit.  I think Visits are helpful especially with the other data, I had just meant that we can get them from other sources if needed, but of course the most ideal is to get them all in one place with conversions and conversion %, etc.  Awesome!

Would love to be able to label the campaigns to make a little more sense.  Awesome.  Excited to see this in upcoming versions or Ad-Ons!  Thanks so much and my affiliates will love it!

**Comment by ramiabraham** [comment]
(Related: https://secure.helpscout.net/conversation/115633896/15595/)

**Comment by sumobi** [comment]
The magic is happening over here for this: https://github.com/affiliatewp/AffiliateWP/issues/627

**Comment by sumobi** [comment]
Closing, since this was finished up in https://github.com/AffiliateWP/AffiliateWP/issues/627
