### ISSUE TITLE
Coupon tracking integration for Gravity Forms

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#378]
The Gravity Forms integration should support their coupons add-on.

**Comment by ghost1227** [comment]
Gravity doesn't make things terribly obvious. I spent several hours digging into the Coupons extension and Gravity Forms core, and there doesn't appear to be any way of adding settings to the Coupons pages. While there is a roundabout way to modify form field settings, the plugin settings themselves seem to have been overlooked!

**Comment by wordmaid** [comment]
A customer request for this feature: https://secure.helpscout.net/conversation/189029845/31507/?folderId=414056

**Comment by pippinsplugins** [comment]
@ramiabraham or @DrewAPicture one of you want to jump on this sometime in the next couple of weeks?

**Comment by pippinsplugins** [comment]
I don't believe there is currently a way to add settings to the coupon screen unless we do something _really_ ugly. Going to ask if we can get some action hooks.

**Comment by pippinsplugins** [comment]
Figured out how to add settings fields so we're good to go here! PR coming shortly.

**Comment by pippinsplugins** [comment]
@michaelbeil @sumobi this is ready for testing! Coupons add-on is in Dropbox.

**Comment by michaelbeil** [comment]
All works well.

1. Checked out `issue/378`
2. Created a coupon and associated it with an affiliate
3. Opened an incognito window to the form that the coupon is connected to
4. Applied coupon
5. Submitted form
6. Referral created

Note: Gravity Forms 2.x+ is required for the settings filter.

**Comment by pippinsplugins** [comment]
Merging.
