### ISSUE TITLE
Add filter to enable affiliates to receive commissions on their own purchases

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#387]
We'll add a filter to each integration's conditional so an affiliate can receive commission on their own referral:

    if( $this->get_affiliate_email() == $customer_email ) {
        return; // Customers cannot refer themselves
    }

**Comment by pippinsplugins** [comment]
With #519 done, we can now introduce a simpler filter in the `is_affiliate_email()`
