### ISSUE TITLE
Introduce emails class and template files

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#392]
Just as we recently did for EDD, we should introduce an `AffWP_Emails` class that

**Comment by ghost1227** [comment]
I've got the main class pretty much built, can you tell me what initial template tags you want to support by core?

**Comment by pippinsplugins** [comment]
Don't worry about template tags yet. We will have to decide how best to
handle those since they are not the same as the Easy Digitial Downloads
template tags. We will have several types of tags here.

**Comment by pippinsplugins** [comment]
@sumobi This is ready for testing.

**Comment by sumobi** [comment]
:+1: aye aye captain
