### ISSUE TITLE
Multiple referrals in one sale

### ISSUE THREAD

**Issue by michaeltieso** [affiliatewp/AffiliateWP#403]
We're having many orders in the last few hours record multiple referrals for a single order.

https://www.dropbox.com/s/tbm7l3zpv5te99b/Screenshot%202014-10-02%2017.27.08.png?dl=0

Does not seem to occur every time but it's certainly occurring more often. Not sure what changed that could have caused this. Here's a list of the referral earnings https://www.dropbox.com/s/u7fl5dx5sy25uax/Screenshot%202014-10-02%2017.30.15.png?dl=0. Not sure whether we should delete the duplicates.

**Comment by sumobi** [comment]
@michaeltieso Looks like your reply got missed, sorry about that. A "pending" referral is one that hasn't been completed yet, you can safely delete it. An "unpaid" referral means the order went through fine and the affiliate is then awarded the commission (+ receives email notification). 

Do you still have issues with duplicate referrals? 

I think I discovered why this happens with WooCommerce. This is how I was able to replicate:

1. I used my test affiliates's referral URL, added a product to the cart, proceeded to checkout and purchased.
2. Once landing on the PayPal payment screen I clicked the browser's back button to go back to the checkout screen. Here's the PayPal page I clicked back from: https://cloudup.com/cGATlFnHuyc
3. I then refreshed the checkout screen (as WooCommerce shows a grey spinner icon and blocks payment) so I could click the purchase button and went to PayPal again. After doing so I was left with 2 "pending" referrals in the admin. To simulate the completed purchase via PayPal, I completed the order from WooCommerce's order screen. After doing this one of the referrals turns to "unpaid".

@pippinsplugins My guess is that customers are clicking the browser's back button to double check the details they have entered at checkout. This also explains why it's not every order. EDD on the other hand clears the cart when clicking back to the site.

**Comment by sumobi** [comment]
@pippinsplugins 1 order, unless you complete the order in WooCommerce and then click back again to go to checkout. Once moving forward to PayPal again it will create a new order.

**Comment by pippinsplugins** [comment]
Was the second referral created before reaching PayPal a second time?

**Comment by sumobi** [comment]
@pippinsplugins no, it only gets created one you move from checkout to PayPal. As per the example above you could probably keep hitting back and generate referral after referral until you complete the order, which would then mark one of those referrals as unpaid.

**Comment by pippinsplugins** [comment]
But if it's creating a WooCommerce order each time as well, that seems like
correct behavior. Yes?

**Comment by sumobi** [comment]
@pippinsplugins Not sure what you're asking. It won't create a new WooCommerce order if you go backwards and forwards from checkout -> paypal unless your complete the payment.

**Comment by pippinsplugins** [comment]
Ok apparently I'm confused. I thought you meant the Woo order was created each time as well, not just when completed.

**Comment by sumobi** [comment]
@pippinsplugins no 1 order is created but has multiple referrals
