### ISSUE TITLE
Support limiting referrals

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#41]
@krogsgard asked this:

>Would it be able to be limited? As in, say I charge $50 for a membership, then offer a $10 off "affiliate" referral for every person that customer refers. Could I stop the payouts at 5 referrals?

I'm not sure how to do it, but I love the idea.

**Comment by wordmaid** [comment]
Had another pre-sale customer ask if this is possible for one-time referrals. Interesting idea indeed, and not the first time I've seen it.

Ref: https://secure.helpscout.net/conversation/163883018/26129/?folderId=205524

**Comment by DrewAPicture** [comment]
> I'm not sure how to do it, but I love the idea.

@pippinsplugins What if we did something like referral *coupons*. That would be make limiting simple enough. Might have to pass another value through the URL to make that work, but it could be interesting.

**Comment by DrewAPicture** [comment]
Actually, now that I think about it, we could add some kind of signifier onto the existing referral var value, e.g. `/ref/2_3y2f3f` or something where we tack on a coupon token. Back-compat would be hard to predict.

**Comment by pippinsplugins** [comment]
That might work. Let's let it sit a while longer to see if we get additional requests for it.

**Comment by sumobi** [comment]
Have I misinterpreted the issue? To me it seems like we're wanting to limit the number of referrals an affiliate can be assigned, based on their referral link. For example if the limit is set to `10`, commission can only be generated 10 times for that specific affiliate before they can no longer earn any more.

In which case, this would work:

    function affwp_custom_limit_referrals( $return, $args ) {

	    $limit = 10;

	    // count affiliate's referrals
	    $referral_count = affwp_count_referrals( $args['affiliate_id'], array( 'pending', 'unpaid', 'paid' ) );

	    if ( $referral_count >= $limit ) {
		    return false;
	    }

	    return true;

    }
    add_filter( 'affwp_integration_create_referral', 'affwp_custom_limit_referrals', 10, 2 );

Or is it more like a "refer a friend" situation (we are building a pro add-on for this) whereby the affiliate refers another user and their affiliate link gives the referring customer $10 off the purchase, and the affiliate also receives their normal referral.

**Comment by pippinsplugins** [comment]
Re-reading it makes me think the original suggestion from Brian was the former, Andrew.

**Comment by sumobi** [comment]
That's what I get from it also, especially considering the "Could I stop the payouts at 5 referrals?" portion. The above would make a good code snippet, I've seen it requested before, but not something I believe should go into core. It's more suited towards the refer a friend plugin.

**Comment by pippinsplugins** [comment]
:+1:

Closing as wontfix for core.

**Comment by gspice** [comment]
I know this is closed, but we had another request for this so I wanted to log it.  

https://secure.helpscout.net/conversation/386635367/61686/?folderId=205529

**Comment by gspice** [comment]
Another one, user wants to stop affiliate from getting referrals after a certain amount of time:

https://secure.helpscout.net/conversation/388958226/61945/?folderId=205524
