### ISSUE TITLE
Plugin conflict: Peter's Login Redirect causes issue with registration form

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#415]
There appears to be a conflict with `Peter's Login Redirect` and our registration form processing. I think the plugin is intercepting our user login during registration and causing the registration to appear to be incomplete, as described in [this ticket](https://secure.helpscout.net/conversation/49791900/3043/).

**Comment by ghost1227** [comment]
@pippinsplugins if you want me to dig into this, is there anywhere specific you want me to start? Seems to me this is going to be a 'works for me' ticket if you couldn't even reproduce it...

**Comment by pippinsplugins** [comment]
@ghost1227 Yes please. See if you can replicate it. If you can, see if you can fix it. We've seen it happen several times.

**Comment by ghost1227** [comment]
ok

**Comment by ghost1227** [comment]
@pippinsplugins I haven't been able to replicate it either... Tested every combination that makes any sense and it always works as expected for me.

**Comment by pippinsplugins** [comment]
Closing as invalid then.
