### ISSUE TITLE
Show affiliate other affiliate URL options on affiliate area

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#421]
Now that we support a wide variety of affiliate URLs we should spruce up the affiliate area somehow so the affiliate can see the other variations of links they can use, otherwise they will be oblivious. Any thoughts?

Another option is to simply leave this up to the site owner. Maybe we could make it a bit easier in the template or through some other method where the site owner can select what URL will be shown by default.

**Comment by sumobi** [comment]
After working on some improvements to the affiliate dashboard (see https://github.com/affiliatewp/AffiliateWP/issues/479#issuecomment-73815185) I don't think we should show the other URL options to the affiliate, as it will only cause confuse as to which one will work/to use.

I like the idea of leaving this up to the site admin. Once the site admin changes the 2 options in the settings the URLs will update across the site (unless the [affiliate_referral_url] shortcode is overriding with its new parameters).

@pippinsplugins Do you agree?

**Comment by pippinsplugins** [comment]
I concur.
