### ISSUE TITLE
Automatically enable Fallback Tracking Method if JS fails

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#422]
We should be able to cut down on the number of support requests from customers that have problems with tracking not working by automatically enabling the Fallback Tracking Method if JS fails.

The trick is detecting when JS is failing (usually due to a JS error).

We should be able to use the following method:

1. During install, set an option in the database for `affwp_js_works` = `2`. `2` == JS doesn't work; `1` == JS works.
2. When the site is loaded for the first time (frontend only), fire an ajax request. When this ajax request is processed successfully, we store update the option in the database to `1` to indicate that JS works. 
3. In the tracking class, we automatically use the Fallback Tracking method if it is enabled in Settings or `affwp_js_works` ha a value of `2`.

**Comment by pippinsplugins** [comment]
@sumobi This is ready for testing. Let me know if you'd like a walk through on it.

**Comment by sumobi** [comment]
@pippinsplugins works fine for me but I was expecting the checkbox to become enabled in the Misc tab if the ajax test failed.

**Comment by pippinsplugins** [comment]
@sumobi I opted to not check the box because I want to ensure that it can automatically go back to non-fallback if JS begins working again.

**Comment by sumobi** [comment]
:+1: good point

**Comment by pippinsplugins** [comment]
Cool, anything else here or are we happy with it?

**Comment by sumobi** [comment]
@pippinsplugins I think we're good here
