### ISSUE TITLE
Show an affiliate's registration date and other fields on edit affiliate screen

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#433]
A user on Twitter has suggested that the date an affiliate registered, and other registration fields should be visible on the edit affiliate screen.

Registration date will be handy. Should we add the website URL and the promotion method to the edit screen?

**Comment by ghost1227** [comment]
@sumobi @pippinsplugins What else would you want to show?

**Comment by pippinsplugins** [comment]
Let's start with the date and go from there

**Comment by ghost1227** [comment]
Fail... that was supposed to be an added field, not a replaced field. Fixing.

**Comment by DrewAPicture** [comment]
In the interest of self-documenting code, can we change `$fname`, `$lname`, and `$fname_lname` to `$first_name`, `$last_name`, and `$first_last`, respectively, or similar?

**Comment by DrewAPicture** [comment]
Merged #1254.
