### ISSUE TITLE
Send approval email to affiliate when manually adding

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#442]
If a user registers to become an affiliate and are approved, an approval email is sent to the affiliate. When an affiliate is added manually however, the affiliate is created and set to active but the affiliate does not receive the approval email.

@pippinsplugins Should we add a checkbox to the add affiliate screen to enable the sending of the email? (perhaps off by default)

**Comment by pippinsplugins** [comment]
Oh, I did this without a checkbox. It just sends it. More consistent that way.

**Comment by sumobi** [comment]
Sounds good to me

**Comment by sumobi** [comment]
@pippinsplugins re-opening, looks like an email isn't sent anymore when an affiliate is added via the email. What are your thoughts on the checkbox option now? There will be instances where a site admin might not like to send the emails to the affiliate when added.

**Comment by pippinsplugins** [comment]
Yep, let's add a checkbox.

**Comment by michaelbeil** [comment]
Yes, add a checkbox. Unchecked by default?

**Comment by michaelbeil** [comment]
I did not receive an email when an affiliate was added manually.

**Comment by pippinsplugins** [comment]
I vote checked by default.

**Comment by sumobi** [comment]
:+1: to that, since that's expected behaviour

**Comment by ramiabraham** [comment]
Ditto here; I'd expect support inquiries to increase on this if unchecked by default.

**Comment by wordmaid** [comment]
:+1: for checked - makes sense!

**Comment by michaelbeil** [comment]
- [x] please
