### ISSUE TITLE
Add Referrals tab so affiliates can see a list of their referrals

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#446]
There should really be a `Referrals` tab in the Affiliate Area so that affiliates can see a list of their referrals, including the amount, description, status, and date.

**Comment by pippinsplugins** [comment]
@sumobi Do you think you could give this a text early next week?

**Comment by sumobi** [comment]
@pippinsplugins absolutely

**Comment by sumobi** [comment]
@pippinsplugins Looks great to me. Do you think "pending" referrals should be hidden by default? I think it should only show "unpaid" and "paid" as some customers like to set referrals to "pending" first so they can moderate them.

**Comment by pippinsplugins** [comment]
Yep, I think it makes sense to hide pending. If someone wants to add them, they can edit the template files.

**Comment by pippinsplugins** [comment]
Merged into release/1.5
