### ISSUE TITLE
Add .swf support to creatives

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#448]
We should consider adding support for .swf files. Currently you cannot add a .swf (flash) creative, the .swf file will not load in the browser and the code provided to affiliates will be incorrect. 

A .swf file requires the <object> tag among other things. We should be able to detect if a .swf creative was added, and then output some basic markup to cater for a .swf file.

**Comment by ghost1227** [comment]
@sumobi I think this and #445 should be combined into an overhaul of the creative system. Add a select box to set creative type (image/html/swf/etc), then dynamically populate the page based on the value of that field.

**Comment by sumobi** [comment]
@ghost1227 @pippinsplugins I like that idea.

**Comment by ghost1227** [comment]
@pippinsplugins @sumobi Now that WC Omaha is over, I'd be happy to mock up something.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by ghost1227** [comment]
@pippinsplugins @sumobi A few quick mockups...

![](http://cloud.section214.com/image/1a350H1k0c2u/Image%202015-10-12%20at%2010.49.21%20PM.png)

![](http://cloud.section214.com/image/222k2X2q0t0z/Image%202015-10-12%20at%2011.02.35%20PM.png)

![](http://cloud.section214.com/image/190A3n193316/Image%202015-10-12%20at%2011.05.04%20PM.png)

![](http://cloud.section214.com/image/0I29351t1x2K/Image%202015-10-12%20at%2011.08.03%20PM.png)

**Comment by michaelbeil** [comment]
lookin good @ghost1227.

**Comment by sumobi** [comment]
@ghost1227 awesome! I don't think we need the `Dimensions` fields for an image type. Set widths and heights on images break responsiveness.

**Comment by ghost1227** [comment]
heh.. probably don't need it for HTML either now that i'm thinking about it...

**Comment by pippinsplugins** [comment]
@ghost1227 did you make that as a new post type or just replicated the
screen?

**Comment by ghost1227** [comment]
@pippinsplugins No code yet, that's literally just a mockup.

**Comment by ghost1227** [comment]
That said, the idea was to replicate the standard post type screen.

**Comment by ghost1227** [comment]
@pippinsplugins @sumobi @michaelbeil Here's a REALLY quick rewrite of the creatives page. So far, I've updated the new/edit pages with the exception of the live preview (it updates on save, but haven't done the JS to do live updating). Frontend output hasn't been updated, and I want to add a column to the table to indicate creative type. Please note that after pulling this branch you MUST deactivate/reactivate the plugin as it adds several fields to the creatives database.

https://github.com/Section214/AffiliateWP/tree/feature/creativeupdate

**Comment by ghost1227** [comment]
Oh, I should note that this also includes updates to take care of adding SWF (this issue) and HTML (not sure the issue number offhand) creative types.

**Comment by pippinsplugins** [comment]
@ghost1227 Could you submit that as a PR so we can actually see the changed files?

**Comment by ghost1227** [comment]
@pippinsplugins Has to be updated to merge cleanly... what branch do you want the PR submitted to?

**Comment by DevinWalker** [comment]
Hey guys, I recently read http://www.engadget.com/2016/02/10/googles-killing-off-flash-based-advertising/ ... it seems Flash is all but dead. Why support it? Progressive enhancement for the win!

**Comment by ghost1227** [comment]
@DevinWalker That's still a year in the future, and only one content provider. It's still worth keeping for now.

**Comment by pippinsplugins** [comment]
I personally love the idea of not supporting a dying technology, even if for no reason beyond it helps us push it one step closer to the grave.

**Comment by sumobi** [comment]
100% agree :+1:

**Comment by pippinsplugins** [comment]
Now do we decide to still use the rebuilt creatives page as Dan has built
or not?

**Comment by michaelbeil** [comment]
I was wondering the same thing.

**Comment by michaelbeil** [comment]
I too like the idea of not support a dying tech.

**Comment by sumobi** [comment]
@pippinsplugins yes I believe there is still merit in having a better way of adding creatives with "creative types" as per the screenshots above. It will make things much less confusing and will allow better organisation. We'll need creative types such as:

1. Emails
2. Text
3. Image
4. HTML
5. Twitter
6. Facebook
7. Etc

Depending on what is selected, the settings on the page will change.

**Comment by ghost1227** [comment]
@sumobi @pippinsplugins more than happy to revise my previous update...

**Comment by wordmaid** [comment]
As per @sumobi's comment above, customer has asked about supporting other file types such as docs/.docx, so their affiliates can download them. 

Ref - https://secure.helpscout.net/conversation/195107838/32801/

**Comment by pippinsplugins** [comment]
I agree on adding better support for creative types, but I don't think they're in the scope of this ticket. Let's get a new ticket that's not about SWFs, which we will not add.
