### ISSUE TITLE
Questions/Suggestions: Site Credit Automation, Coupon Codes, and More...

### ISSUE THREAD

**Issue by Rogue23** [AffiliateWP/AffiliateWP#453]
Hello,

I have a new site (in development) and was researching affiliate programs yesterday. I'm almost certain I'm going to go with this one and installed it last night. It's a test site only, so I haven't paid yet, but I promise I will long before going live. :)

I have a few questions/suggestions:

1. I installed the site credit add-on. Ideally, I'd like to be able to set a "Minimum Payout Amount" (say, $50), and have all affiliate earning automatically be available as site credits all the time (automatically). Once an account reaches $50, payouts will be made, but for everyone else, I think it would be very nice for them to be able to use their balance as a site credit immediately, without me having to move their balance to a site credit for them. Further, if their site credit reaches the designated level, I'd like to be able to move it back so it can be paid out to them. Does that make sense?

2. Having affiliate-specific coupon codes is awesome. The problem is, they can get quite expensive, especially when people who are direct referrals (no commission due) see the coupon code field and go searching for coupons at checkout... Say google leads them to one that ends up giving them a 20% discount and the affiliate (who didn't really refer them) a 20% commission (I'm making up numbers). That ends up being a 40% discount that would have been a 0% discount without offering coupon codes, which makes me really rethink if I even want to offer them. What I propose is a way for affiliates to choose the discount amount they want to offer, and it comes out of their own commission. For example, if an affiliate receives a standard 20% commission on all sales, there could be a secondary "max discount" field available that I would set to 25%, for example. Then, the affiliate could generate their own coupon codes that total 25% (including their commission).... so they could offer 10% discounts and receive 15% commission or offer 10% discounts and receive 15% commission or offer no discount and receive their full 20% commission. I realize this is a complex feature, but I think it would be amazing if something like this could be implemented.

3. Much simpler than # 2 - Just a question: Can affiliates generate their own coupon codes, or do I need to do that for them manually?

4. Do you recommend implementing a separate Refer-A-Friend program or using this system for everything? What I don't want to happen is for people to constantly refer each other (I buy through your link and you buy through mine), which I think could definitely happen if all customers are automatically made affiliates, especially if coupon codes are used as described above. So I was thinking having a separate refer-a-friend program that only pays in site credits might be a better way to go. I would love to do that through this plug-in, if at all possible, but this would require the following:

4a. The ability to pay certain affiliates (existing customers) in site credits only.
4b. The ability to ONLY pay these affiliates for generating _new_ customers, and not on every order from repeat customers.

Awesome work, gents. I'm 95% sure I'm going to be purchasing this regardless but figured I'd at least give you my initial feedback. I know these are some big requests, but figured it couldn't hurt to throw some ideas your way.

-Mark

**Comment by michaelbeil** [comment]
Separate issues have been created to account for these enhancements that we are tracking.

**Comment by JamesJosephFinn** [comment]
@amdrew  you're gist linked to above is a broken link, has this code make it into core? Thanks.  I'm researching how to utilize AffiliateWP to implement a simple "refer a friend" program.  It would be nice if there was a way to  segment users as  "referers" and "affiliates". AutomateWoo  handles referrals  nicely by placing a "referrals" tab inside the customers "my account" dashboard by utilizing the woocommerce  "my account" tabs API.  I'm reluctant to use it though because it comes bundled with cart abandonment functionality, for which I'm  already using Jilt.

**Comment by michaelbeil** [comment]
@JamesJosephFinn: https://gist.github.com/amdrew/978267209a8cd0d4d3cd
