### ISSUE TITLE
Allow referrals to be edited

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#459]
I remember we discussed this some time ago but can't find an issue on it. It would be handy to allow a referral to be edited in the admin after its been created. Not sure if there are any implications to this.

**Comment by pippinsplugins** [comment]
@sumobi This is ready for testing.

A couple of key points:

1. Changing the status during edit should trigger the appropriate actions (increasing earnings, firing emails, reducing earnings, etc)
2. If the amount of a referral is changed AND the status is changed, the affiliate's earnings should be reduced or increased by the new amount

**Comment by pippinsplugins** [comment]
Third note:

- If the amount of the referral is changed, the affiliate's earnings should be adjusted according, even if status is not changed. Only happens when referral's original status is paid and status is unchanged.

**Comment by sumobi** [comment]
Woot! this is super handy, will test today

**Comment by sumobi** [comment]
@pippinsplugins the only thing I can see so far is that a couple of query strings were different between `class-notices.php` and the actual query string. See: https://github.com/affiliatewp/AffiliateWP/commit/f48560c09b94be4fcb042fe9118f11efbd476a88

**Comment by pippinsplugins** [comment]
Good catch @sumobi.

**Comment by pippinsplugins** [comment]
Will merge this into `release/1.5` then close it out.

**Comment by sumobi** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Merged into release/1.5
