### ISSUE TITLE
Manual referrals marked as "paid" are not shown in affiliate's earnings

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#460]
Manual referrals that are created with status of "paid" are not reflected in the affiliate's earnings. However if you create a manual referral with a status of "unpaid" then mark it as "paid", it shows up fine.

**Comment by gspice** [comment]
This is happening = reported on this ticket:
https://secure.helpscout.net/conversation/352612295/57725/?folderId=205524

I tested locally and verified what he is seeing.....the payouts are not added to the wp_affiliate_wp_payouts table.

**Comment by DrewAPicture** [comment]
This was indirectly fixed as of 2.0.10 via #2257.
