### ISSUE TITLE
Per-category commission rates

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#465]
I'm not sure if this is something we add to core but including it here anyway for discussion. 

A customer has expressed interest in changing commission rates for product categories (using WooCommerce). They could go to `Category A` for example and enter `40%`. All products within that category would take on 40% commission. This could be a real time saver for people that group products and want the commission rates all the same.

In the meantime I put together this code snippet (untested) which should provide some examples on how to do this for anyone wanting to:

https://gist.github.com/sumobi/c149510eef862f822b1f

**Comment by wordmaid** [comment]
Another question on per-category referral rates: https://secure.helpscout.net/conversation/177516040/29184/?folderId=205524

**Comment by wordmaid** [comment]
Another request for this: https://secure.helpscout.net/conversation/208466659/35171/

**Comment by michaelbeil** [comment]
Another: https://secure.helpscout.net/conversation/219280412/36845/?folderId=205529

**Comment by michaelbeil** [comment]
Another request: https://secure.helpscout.net/conversation/249154826/41959/?folderId=634609

**Comment by michaelbeil** [comment]
Request here: https://secure.helpscout.net/conversation/274305668/46259/?folderId=205524

**Comment by michaelbeil** [comment]
Another request: https://secure.helpscout.net/conversation/425624605/66046/?folderId=205524.

**Comment by amdrew** [comment]
https://wordpress.org/support/topic/per-directory-rate/

**Comment by amdrew** [comment]
WIP PR for a possible EDD integration. Wanted to explore how it could work: https://github.com/AffiliateWP/AffiliateWP/pull/2558

Priority:

1. Affiliate rate if set
2. Product rate if set
3. Category rate if set
4. Default rate

<img width="829" alt="screen shot 2018-02-09 at 8 08 31 pm" src="https://user-images.githubusercontent.com/52581/36015838-18449f46-0dd5-11e8-8e8d-71094b31ad6f.png">

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/521131796/75840?folderId=205529

**Comment by pippinsplugins** [comment]
>>>I think it should take the rate of whichever category is first in the array (using get_the_terms).

I agree.

Where does category rates fall in line when using Tiered Affiliate Rates?

**Comment by amdrew** [comment]
@pippinsplugins Since a per-product rate trumps a per-category rate, it would fit in just before per-product referral rates, also before Tiered Affiliate Rates: http://docs.affiliatewp.com/article/1465-referral-rate-hierarchy

**Comment by pippinsplugins** [comment]
This is looking pretty good to me. We can carry this over to WooCommerce easily too.

**Comment by amdrew** [comment]
@pippinsplugins I agree, was going to suggest slipping this into 2.2. I'm also not against the idea of only supporting EDD and WooCommerce at this point.

**Comment by pippinsplugins** [comment]
I was going to propose EDD and Woo only as well.

**Comment by amdrew** [comment]
@pippinsplugins I can take care of WooCommerce and then we'll get some further testing on both integrations.

**Comment by amdrew** [comment]
Ready for testing with standard referrals on both EDD and WooCommerce integrations (have yet to test coupons). Will write up some proper test instructions soon.

**Comment by amdrew** [comment]
@pippinsplugins 

On a category's Referral Rate field, you cannot enter `0` to effectively disable commission on the entire category. Entering `0` will not save, or wipe out the term meta if already set. You can however enter `0.00`, which will set the rate to `0.00` and disable commission on the entire category.

This is exactly how the referral rate works for a single product so nothing new here. Product screens however have a “Disable referrals on this Download”. Should we introduce a `Disable referrals on this Category` checkbox? I'm not too keen on adding yet another option to a category screen. We either

1. Add it, so its consistent with a product screen
2. Leave it off, and document the fact that entering `0.00` will disable commission on the category level

**Comment by pippinsplugins** [comment]
I'm fine with using 0.00 to disable rates.

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/529566743/76814?folderId=634609

**Comment by michaelbeil** [comment]
1. X
2. X
3. X
4. Everything checks out 
5. X
6. The second category seems to win out. What are your steps to get the first category to win?
9. X
10. X

**Comment by pippinsplugins** [comment]
What do the Xs mean?

**Comment by michaelbeil** [comment]
That everything is working as expected.

**Comment by amdrew** [comment]
@michaelbeil Did 9 and 10 not work for you?

Regarding 6: I re-worded the above text as it didn't make much sense. I talked about products instead of categories 🙈so it was highly confusing. 

Here's the new description:

> Test multiple categories. The per-category commission amount is based on the first category assigned to a product. If Category B has a per-category rate set, and Category A doesn't, and the product purchased is assigned to both category A and B, the winning "commission" will be that of Category A. Since Category A does not have a rate set (the field is blank), the commission will fall back to the global referral rate as defined in the settings.

Can you re-test based on the above and if it still awards the commission to the second category, can you describe your exact set up? I.e what your categories are called, which rate is set for both and anything else that will help me replicate the issue.

**Comment by michaelbeil** [comment]
9 and 10 did work for me. It looks like I missed noting them.

I will re-test based on the above remarks.

**Comment by michaelbeil** [comment]
This works just fine with EDD.

However, it does not work with WC. I have Category A without a category rate set. Category B has a rate set at 25. A referral of $25 dollars was awarded for a product that costs $100. Category A was assigned to this product before Category B. My categories are called Test 1 & Test 2.

**Comment by amdrew** [comment]
@michaelbeil And what was your global referral rate set to?

**Comment by amdrew** [comment]
Tested with WooCommerce and it works for me. I set up two categories, `Test 1` and `Test 2`. 

`Test 1` (I'm assuming this is category A in your previous message) has no rate (it's blank)
`Test 2` has a rate of `25`
Global referral rate is `20%`

The product has a price of $100 and is assigned to both `Test 1` and `Test 2` categories:

<img width="626" alt="screen shot 2018-03-01 at 10 26 23 am" src="https://user-images.githubusercontent.com/52581/36813966-18f0cdf0-1d3b-11e8-8ac0-de45ec0a77a3.png">

Referral is calculated at `$20.00` since the first category, `Test 1` had no rate, and it falls back to the global referral rate of `20%`:

<img width="555" alt="screen shot 2018-03-01 at 10 27 54 am" src="https://user-images.githubusercontent.com/52581/36814039-4e0bc3b4-1d3b-11e8-9cba-d3ba819a664a.png">

Is there anything different about the way I have it set up?

**Comment by michaelbeil** [comment]
Yes, my settings are setup like yours. Category A = Test 1 and Category B = Test 2. 

The only difference is that I have a global rate of 15%. I will give this another test today.

**Comment by michaelbeil** [comment]
A referral was generated at 15%, which is the Global referral rate. All good to go!

**Comment by michaelbeil** [comment]
I performed another test with Test 1 at a referral rate of 50 and Test 2 without a referral rate. A referral was generated correctly at $15.

**Comment by amdrew** [comment]
> A referral was generated at 15% = $15, which is the Global referral rate. All good to go!

Great! 

> I performed another test with Test 1 at a referral rate of 50 and Test 2 without a referral rate. A referral was generated correctly at $15.

Great! How much was the product? $30?

**Comment by gspice** [comment]
I wanted to play so I did a round of testing :-)

List of referral rates set on a single $20 product that belonged to a category were applied in this priority order:

* Affiliate Product Rates 90%  $18.00
* Specific affiliate rate 70%  $14.00
* Product-specific rate in WC product 10% $2.00
* Category rate 50% $10.00
* Global rate 30% $6.00

**Comment by amdrew** [comment]
@gspice Oh please do :) If you haven't seen them, testing notes are here: https://github.com/AffiliateWP/AffiliateWP/issues/465#issuecomment-365452939

That order looks correct!

**Comment by michaelbeil** [comment]
Global rate of 15% with a purchase of a $100 product. Defaulted to global rate since the first category added (Test 2) was blank.

**Comment by amdrew** [comment]
> Global rate of 15% with a purchase of a $100 product. Defaulted to global rate since the first category added (Test 2) was blank.

If you had two categories assigned to the product, and the `Test 1` category had a rate of `50` and `Test 2` did not have a referral rate, then the referral should have been 50% of $100 (since Test 1 should be the first that appears in the categories list like my screenshot here: https://github.com/AffiliateWP/AffiliateWP/issues/465#issuecomment-369389939). 

Can you show me some screenshots of:

1. Each of your categories
2. The WooCommerce products screen so I can see the categories assigned
3. The referral generated
4. Your global rate

**Comment by michaelbeil** [comment]
Test 2 was assigned to the product first - Test 1: referral rate of 50 and Test 2: without a referral rate. A referral was generated correctly at $15 with a 15% global rate.

1. Each of my categories:
![screen shot on 2018-03-02 at 15_25_10](https://user-images.githubusercontent.com/4752949/36903495-2e8e5dc8-1e2e-11e8-9e32-13a5641c7427.png)
![screen shot on 2018-03-02 at 15_26_31](https://user-images.githubusercontent.com/4752949/36903503-32033ee2-1e2e-11e8-95bd-59c61a2ec537.png)


2. WooCommerce products screen:
![screen shot on 2018-03-02 at 15_22_23](https://user-images.githubusercontent.com/4752949/36903369-d37a8baa-1e2d-11e8-8f63-77ed676e9b57.png)


3. The referral generated:
![screen shot on 2018-03-02 at 16_00_18](https://user-images.githubusercontent.com/4752949/36905164-e1077e22-1e32-11e8-89d6-9a8a32461e8e.png)


4. My global rate: 
![screen shot on 2018-03-02 at 15_58_33](https://user-images.githubusercontent.com/4752949/36905104-b8a48cae-1e32-11e8-9063-8a9b7111dbec.png)

**Comment by amdrew** [comment]
@michaelbeil Can you show me a screenshot of the WooCommerce products screen? One similar to the 2nd screenshot I posted here: https://github.com/AffiliateWP/AffiliateWP/issues/465#issuecomment-369389939

**Comment by michaelbeil** [comment]
WooCommerce products screen:
![iwxllp](https://user-images.githubusercontent.com/4752949/37094777-4a226afe-2214-11e8-9d10-58c1d3619e4d.png)

Referrals screen: 
![pzhczc](https://user-images.githubusercontent.com/4752949/37094867-93c147de-2214-11e8-9f60-2b193974f2d6.png)

**Comment by amdrew** [comment]
@michaelbeil That's what I needed to see, thanks. 

Are you on the latest version of WooCommerce? I cannot for the life of me, get `Test 2`, to appear before `Test 1`. Can you outlines some steps on how you did that? 

If I assign `Test 2` before `Test 1`, they still appear as `Test 1, Test 2`. I've tried matching your exact category slugs and also tried creating the `Test 2` category before (and also assigning to product)  before `Test 1`.

**Comment by michaelbeil** [comment]
I simply go to the product page and then select Test 2 and update the product. Then I select Test 1 and update the product. That is all that I did.

**Comment by amdrew** [comment]
@michaelbeil Weird, doesn't work like that for me, Test 1 is always listed first, no matter how I select them. Latest version of WooCommerce?

In any case, the amount is correct. I think we're good to go on this @pippinsplugins

**Comment by pippinsplugins** [comment]
@amdrew looks good here. Could you fix the merge conflict so we can merge it in?

**Comment by amdrew** [comment]
@pippinsplugins 👍 Done

**Comment by michaelbeil** [comment]
Strange. Yea, I’m on the latest version of WooCommerce.

**Comment by pippinsplugins** [comment]
Merged!

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/564535116/80639/?folderId=205529
