### ISSUE TITLE
Allow number of referrals shown on screen to be configurable

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#467]
A customer needed to delete thousands of referrals imported from Affiliates Pro but there's currently no way to increase the number of referrals shown on screen when using bulk delete.  

We should allow this to be configurable in the screen options tab.

**Comment by pippinsplugins** [comment]
How about we go ahead and add this to referrals and creatives at the same time since it's varely any extra work.

Any objections @fjarrett or @sumobi ?

**Comment by fjarrett** [comment]
@pippinsplugins I just added this screen option to the Referrals screen in #781. Did you mean do the same for  _visits_ and creatives?

**Comment by pippinsplugins** [comment]
Whoops.

I think we should add it to all list tables, so Affiliates, Referrals, Creatives, and Visits.

**Comment by sumobi** [comment]
:+1:

**Comment by sumobi** [comment]
Works great for me

**Comment by pippinsplugins** [comment]
@fjarrett This isn't working for me. The number field doesn't save.

**Comment by pippinsplugins** [comment]
Oh interesting, it's actually a conflict with my `Restrict Content Pro` plugin which also uses screen options.

**Comment by pippinsplugins** [comment]
All good, I was doing something dumb in RCP.
