### ISSUE TITLE
Payouts log

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#471]
* [x] PR: #1501
* [x] WP-CLI PR: #1539 

I'd really like to see a payouts log system created that keeps track of all payouts for affiliates. Each time an affiliate receives a payout, it would log it. This would need to be usable with automatic payouts and manual payouts.

This would allow affiliates to see a history of their payments as well.

**Comment by codelion7** [comment]
@pippinsplugins would this entail creating a class and a db functions file for storing and displaying the data? We would probably need an admin interface and a tab in the affiliate area as well.

**Comment by pippinsplugins** [comment]
Yes, it'd be similar to our other database tables / UIs

**Comment by pippinsplugins** [comment]
Thinking about this a bit, I think our database table should contain the following columns:
- payout_id
- affiliate_id
- amount
- referral_ids
- date
- payout_method

Each time a payout is processed, an entry will need to be recorded for each affiliate account separately. For example, if a payout is processed and two affiliate's receive a payment, two payout log entries will be recorded.

We can introduce a new list table UI, much like the referrals table, that displays the complete history of payouts. Payouts should also be made available inside of the affiliate area for affiliates to see.

Along with the database class, I propose that we introduce an `AffWP_Payout` object at the same time.

**Comment by codelion7** [comment]
That sounds perfect @pippinsplugins. The object would allow for further integration and extensibility.

**Comment by pippinsplugins** [comment]
Modified DB structure proposal:

**Payout logs DB:**
- payout_id
- affiliate_id
- amount
- date
- payout_method

**New columns on referrals DB**
- payout_id

**Comment by DrewAPicture** [comment]
Started a PR: #1501 

There's a TODO list in the PR description. Feel free to add anything I missed.

**Comment by pippinsplugins** [comment]
TODO looks good.

**Comment by DrewAPicture** [comment]
**Tuesday progress:**
* Built TODO list
* Stubbed out `AffWP\Affiliate\Payout`

**Wednesday progress:**
* Stubbed out `Affiliate_WP_Payouts_DB`
* Set up compat w/ `AffWP\Object`
* Stubbed out `payout-functions.php` + basic tests for `affwp_get_payout()`
* Got the first round of feedback from @pippinsplugins and @ramiabraham

**Comment by DrewAPicture** [comment]
**Thursday Progress:**

* Added `status` column and renamed `referral_ids` column to `referrals`
* Added first passes of the Payouts page to the menu, Payouts page plus list table view, edit view, screen options
* Started more comprehensive testing of payout actions, edit screen mechanics
* Improved Payouts DB layer methods

**Comment by pippinsplugins** [comment]
@DrewAPicture Looks like recording payouts during payout file generation hasn't been done yet, so any suggestions for how to test it? Just manually add payouts to the DB?

**Comment by DrewAPicture** [comment]
@pippinsplugins That's correct. The only way to populate it current is by adding some payouts manually with the `affiliate_wp()->affiliates->payouts->add()` method.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by DrewAPicture** [comment]
**Friday/Weekend Progress:**

* Full test coverage add for the `add()`, `payout_exists()`, `get_column_defaults()`, `get_columns()`, `get_object()`, and `get_referral_ids()`  DB methods
* Add initial tests for `get_payouts()`, skipping referrals handling which will require a subquery and is not currently usable/testable
* Further completed payouts DB layer, TODO: referrals handling, amount handling, update method
* Added the `payout_id` column to the referrals table, added regenerating the referrals table to the 1.9 upgrade routine
* Added `affwp_delete_payout()` + full test coverage
* Added a first pass for `affwp_add_payout()` (no tests yet, though realistically they'll overlap quite a bit with the `add()` method tests)
* Added logic to add a payout on the "Mark as Paid" action in the referrals list table

**State of Payouts:**

* Referrals (subquery) and amount handling still needs to be added to `get_payouts()`
* Test coverage then needs to be completed for `get_payouts()`
* Decision needs to be made about whether the `payout_id` in the referrals table should be updated via Payouts `add()`, `affwp_add_payout()` or a referrals-specific function
* We have near-complete test coverage for the Payouts DB class, save for remaining `get_payouts()` items
* Checking of referral validity on add is still commented out to enable faster testing. This should be commented out and tests adjusted to actually register affiliates

**Comment by pippinsplugins** [comment]
>>>Decision needs to be made about whether the payout_id in the referrals table should be updated via Payouts add(), affwp_add_payout() or a referrals-specific function

My gut reaction is to handle it in `add()`.

**Comment by DrewAPicture** [comment]
**Monday Progress:**
* Implemented core object unit test factories
* Implemented the payout factory and converted function and DB tests to use it
* Enabled referral checking when adding payouts
* Added multi-referral support to `add()`
* Started updating the `payout_id` column when marking referrals paid (bulk action only currently)
* Added single and multi-referral support + tests to `get_payouts()`
* Added methods to handle splitting referrals by affiliate for batch processing

**State of Payouts:**
* Need to add amount support in `get_payouts()` and finish test coverage
* edit.php needs to be converted to view.php (plus update the table action)
* Need to hook up the payout log to generating payouts
* Other outstanding items on the [checklist](https://github.com/AffiliateWP/AffiliateWP/pull/1501#issue-169027644)

**Comment by pippinsplugins** [comment]
Good work!

**Comment by DrewAPicture** [comment]
Started a separate PR for Payouts WP-CLI commands: #1539 

It has to be merged *after* #1501.

**Comment by pippinsplugins** [comment]
@DrewAPicture I'll be testing this tomorrow.

**Comment by pippinsplugins** [comment]
When a referral has been paid and it has a `payout_id` stored, let's display and link to that payout on the edit referral screen:
![screen shot 2016-08-11 at 9 47 54 am](https://cloud.githubusercontent.com/assets/1034109/17592667/c4a469ec-5fa8-11e6-82f8-dd04fdd0f337.png)

**Comment by pippinsplugins** [comment]
A few things I've found with the cli command:

`wp affwp payout update --url=https://edd.com/woocommerce/` (note the lack of an ID) gives me the an error:

```
Fatal error: Cannot call abstract method AffWP\Object\CLI::update() in /Users/pippin/Sites/edd/wp-content/plugins/affiliate-wp/includes/cli/class-payout-cli.php on line 182
```

The help text is missing for the `update` sub command:
![screen shot 2016-08-11 at 10 18 54 am](https://cloud.githubusercontent.com/assets/1034109/17593910/18e931c8-5fad-11e6-8d52-07eadc70ef1d.png)

The data shown for a single payout is different than the data shown in a list. Maybe that's not an issue but thought I'd mention it:

![screen shot 2016-08-11 at 10 20 42 am](https://cloud.githubusercontent.com/assets/1034109/17593980/480c3b76-5fad-11e6-8334-6caff027c594.png)

**Comment by pippinsplugins** [comment]
Issue found when Lifetime Commissions is active:
![screen shot 2016-08-11 at 10 23 55 am](https://cloud.githubusercontent.com/assets/1034109/17594115/c00375ea-5fad-11e6-81cf-070c05a0c1f8.png)
I suspect one of the action hook names has not been changed since the referrals edit screen was copied.

**Comment by pippinsplugins** [comment]
When invalid affiliate IDs or referral IDs are given to the `create` command, a `Error: The payout could not be added.` error is returned. Would it be possible to include the specific reason it couldn't be created?

**Comment by DrewAPicture** [comment]
@pippinsplugins Following up on your feedback:

* https://github.com/AffiliateWP/AffiliateWP/issues/471#issuecomment-239184155

> When a referral has been paid and it has a payout_id stored, let's display and link to that payout on the edit referral screen

This was added in bb57103a. I also disabled the amount and status fields (with different descriptions if the referral has a payout.

![Edit Referral](https://cl.ly/3c2d090w0E1S/Screen%20Shot%202016-08-17%20at%207.11.28%20PM.png)

**Comment by DrewAPicture** [comment]
@pippinsplugins Followup on your feedback:

* https://github.com/AffiliateWP/AffiliateWP/issues/471#issuecomment-239194255

> `wp affwp payout update --url=https://edd.com/woocommerce/` (note the lack of an ID) gives me the an error
> The help text is missing for the `update` sub command

That would be because there isn't an update command. The reason the command is defined is that the `update()` method is abstract in the base class. The main issue I see with being able to update payouts is the unintended consequences that might go along with that. Pretty much the only use-case I can see for updating a payout would be after retrying a payment on a failed payout – and even then, the update should be happening directly, imo. Note that updating payouts in the UI also isn't possible.

For now, I've removed the `abstract` from the method in the base class which allows us to remove the `update()` subcommand from payouts-cli.

**Comment by DrewAPicture** [comment]
@pippinsplugins Followup on your feedback:

* https://github.com/AffiliateWP/AffiliateWP/issues/471#issuecomment-239194255

The data shown for a single payout is different than the data shown in a list. Maybe that's not an issue but thought I'd mention it:

This actually true for several of the core objects. The single object data is essentially all of the _real_ fields associated with an object, and the list view is an idealized view where we can show other fields that may be helpful but aren't actually real fields.

**Comment by DrewAPicture** [comment]
@pippinsplugins Followup on your feedback:

* https://github.com/AffiliateWP/AffiliateWP/issues/471#issuecomment-239195382

> Issue found when Lifetime Commissions is active

Fixed in fa46ddb6.

**Comment by DrewAPicture** [comment]
@pippinsplugins Followup on your feedback:

* https://github.com/AffiliateWP/AffiliateWP/issues/471#issuecomment-239196140

> When invalid affiliate IDs or referral IDs are given to the create command, a Error: The payout could not be added. error is returned. Would it be possible to include the specific reason it couldn't be created?

I've since rewritten the `payout create` command to directly mimic the experience from the interface. That was done in b4e3246. Obviously I'll be adding the ability to generate payouts specific to referrals and/or affiliates in which case we'd add more specific error messages, sure.

**Comment by pippinsplugins** [comment]
Will give this a test soon!

**Comment by pippinsplugins** [comment]
@DrewAPicture This is working really, really well.

Anything specific left to do besides integrate it with the payout add-ons?

**Comment by pippinsplugins** [comment]
If it's just add-ons left, let's merge this as soon as possible.

**Comment by DrewAPicture** [comment]
Merged #1501. Can haz payout logs? 🎉

**Comment by pippinsplugins** [comment]
Woot!

**Comment by pippinsplugins** [comment]
@DrewAPicture let's please proceed with getting issues and PRs for the Stripe and PayPal add-ons.

**Comment by DrewAPicture** [comment]
Opened #1565 as a tracking ticket for the add-ons. Let's close this one out.
