### ISSUE TITLE
Website URL field and promotion method fields not required when user is already logged in, should they be?

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#478]
When a user is already logged in and they register to become an affiliate, the website URL and promotion method fields are not required. I think these should be required just like when you register as a logged out user. Do you agree @pippinsplugins ?

**Comment by pippinsplugins** [comment]
@tnorthcutt's PR will handle it for most cases. We will still need to adjust the processing function to throw an error if either field is left empty.

**Comment by pippinsplugins** [comment]
I'm going to go ahead and leave this as is. Modifying the additions rules is tricky and not that valuable due to how the `get_required_fields()` method works.
