### ISSUE TITLE
Modify the [affiliate_referral_url] shortcode to show other URL variations

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#479]
The [affiliate_referral_url] currently only outputs the referral URL in the following format:

`site.com/page/?ref=123`

We should modify the shortcode so it can show the other URL variations such as:

`site.com/page/ref/username`

We could implement a default referral URL setting in the admin and then the shortcode could output based on what is selected. Here's where the setting was discussed: https://github.com/affiliatewp/AffiliateWP/issues/421#issuecomment-59323983

**Comment by pippinsplugins** [comment]
A few comments on the PR for you @sumobi

**Comment by sumobi** [comment]
@pippinsplugins I've set up a new branch for this issue. It also covers https://github.com/affiliatewp/AffiliateWP/issues/513

branch:
https://github.com/affiliatewp/AffiliateWP/tree/issue/479

It adds 2 new options to the settings page:

1. Default Referral Format (ID or username)
2. Pretty Affiliate URLs

![screen shot 2015-02-11 at 1 28 42 pm](https://cloud.githubusercontent.com/assets/52581/6139556/fa3f4eac-b1f1-11e4-906b-67f975a9c71b.png)

It also modifies the [affiliate_referral_url] shortcode to use the settings above and adds new parameters to the [affiliate_referral_url] shortcode to allow these to be overridden. The shortcode now has `url`, `format` and `pretty` parameters:

The referral URL generator has been updated to support these new options, eg:

![screen shot 2015-02-11 at 1 32 59 pm](https://cloud.githubusercontent.com/assets/52581/6139632/a7832b9c-b1f2-11e4-907e-a25a22b04da2.png)
![screen shot 2015-02-11 at 1 32 45 pm](https://cloud.githubusercontent.com/assets/52581/6139634/a7884956-b1f2-11e4-9fd1-79bace31c08d.png)

The creatives section now uses the referral format and pretty affiliate URLs settings:

![screen shot 2015-02-11 at 1 35 03 pm](https://cloud.githubusercontent.com/assets/52581/6139647/d5903318-b1f2-11e4-828d-61220b4b5f75.png)

The only thing I'm struggling with is allowing query string support in the referral URL generator. Hoping you have the JS skills, because I don't. For example, an affiliate might like to enter a querystring into the generator and the URL is not generated correctly:

![screen shot 2015-02-11 at 1 36 15 pm](https://cloud.githubusercontent.com/assets/52581/6139678/2aadf59c-b1f3-11e4-9a73-3def461b5b78.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
@pippinsplugins want to merge the /issue/479 branch with release/1.6? then we can test some more.

**Comment by pippinsplugins** [comment]
If you enter a URL that already has an referral variable in it, the ref variable gets duplicated:
![screen shot 2015-03-27 at 11 03 10 am](https://cloud.githubusercontent.com/assets/1034109/6871493/f5312bf0-d470-11e4-9a83-1706a4b3b8d2.png)

**Comment by pippinsplugins** [comment]
I'm not going to worry about the double referral variable for now. The URL still works fine.
