### ISSUE TITLE
1.5 What's New Page

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#481]
Apparently we forgot about our what's new page for 1.3 and 1.4 . . . . 

I'm logging this here just so we don't forget it for 1.5.

**Comment by pippinsplugins** [comment]
@sumobi Could you read over this and let me know what you think?

**Comment by pippinsplugins** [comment]
Change log for 1.5 (to be copied to EDD):

Version 1.5, January 5, 2015

- New: introduced Referrals tab for Affiliate Area
- New: referral records can now be edited
- New: account approval emails now sent when manually adding an affiliate
- New: iThemes Exchange now supports per-product rates
- New: MemberPress integration
- New: support for excluding shipping costs from referral calculations
- Tweak: URL and Promotion methods are now required
- Tweak: better error message during login if password or username is incorrect
- Fix: custom affiliate referral rates not used when per-product rate is set
- Fix: MemberMouse referral description is blank
- Fix: usermeta is now deleted when affiliate is deleted
- Fix: referrals now properly rejected if WooCommerce order is deleted

**Comment by pippinsplugins** [comment]
Todo:

- [ ] Release post
- [ ] MemberPress documentation
- [ ] Update iThemes Exchange doc with per-product rates
- [x] Update docs on referral rate changes for per-affiliate rates

**Comment by pippinsplugins** [comment]
Release post drafted: http://affiliatewp.com/wp-admin/post.php?post=14958&action=edit&message=10

**Comment by pippinsplugins** [comment]
MemberPress doc: http://docs.affiliatewp.com/article/640-memberpress

**Comment by pippinsplugins** [comment]
@sumobi I'm ready to push it as soon as you give me the go ahead on everything above.

**Comment by pippinsplugins** [comment]
MailChimp campaign setup: https://us4.admin.mailchimp.com/campaigns/wizard/confirm?id=733813

**Comment by sumobi** [comment]
@pippinsplugins Excellent so far, just one thin:g

> Tweak: URL and Promotion methods are now required

I think that should be modified to say:

> Tweak: URL and Promotion methods are now required when logged-in user registers as an affiliate

Let's launch this puppy

**Comment by pippinsplugins** [comment]
Alright, pushing it!
