### ISSUE TITLE
Custom referral rates not applied (maybe EDD only?)

### ISSUE THREAD

**Issue by jchristopher** [affiliatewp/AffiliateWP#493]
**NOTE:** I use AffiliateWP alongside EDD so I'm not sure if this issue persists for other integrations as well.

-----

About 6 months ago I changed my affiliate percentage in AffiliateWP but left existing affiliates at the original rate. The other day I noticed that one of the grandfathered affiliates was receiving payments under the new affiliate percentage. After a little digging I think I've uncovered a bug, but if it's intended functionality this Issue can be labeled as a potential place for documentation clarification.

Since I use EDD everything starts here for me: https://github.com/affiliatewp/AffiliateWP/blob/master/includes/integrations/class-base.php#L179-L212

That function is (I believe) retrieving the rate from the meta box on the EDD Download post edit screen. The rate in that meta box is also the same rate I have set in the AffiliateWP options. My grandfathered affiliates have a different rate, which is accurately reflected when viewing their affiliate details in AffiliateWP.

Continuing with the code flow I see that line 208 passes that rate (the one found in the meta box on the EDD Download edit post screen) to `affwp_calc_referral_amount `: https://github.com/affiliatewp/AffiliateWP/blob/master/includes/integrations/class-base.php#L208

Looking at the code for [`affwp_calc_referral_amount`](https://github.com/affiliatewp/AffiliateWP/blob/master/includes/referral-functions.php#L164-L168) we see that if a `$rate` is passed (and it was in this case, the rate defined on the EDD Download post edit screen) that `affwp_get_affiliate_rate()` is never fired, so my custom grandfathered affiliate rate is never actually retrieved.

Therein lies (what I think is) the bug — I'm not very familiar with the AffiliateWP codebase yet, but if someone could let me know if I'm following the wrong trail that'd be awesome!

**Comment by pippinsplugins** [comment]
@mgibbs189 I like that.

@sumobi I think the best way for us to handle existing customers is to just document it clearly and then include a note in the change log, and possibly even do a quick blog post to detail the changes.

**Comment by sumobi** [comment]
@pippinsplugins I don't recall any customer tickets on this. A blog post and solid documentation sounds excellent to me.

@mgibbs189 Great idea

**Comment by pippinsplugins** [comment]
Turns out we do not want to hide the `Referral Rate` field when `Site Default` is selected since the `Site Default` only refers to the type, not the amount.

**Comment by pippinsplugins** [comment]
@sumobi Could you give this a quick test? I've tested with WooCommerce and all numbers look correct.

**Comment by pippinsplugins** [comment]
I've updated the [setting referral rates](http://docs.affiliatewp.com/article/63-setting-referral-rates) doc to reflect these changes.

**Comment by pippinsplugins** [comment]
I'm also going to include notes of this change in the 1.5 release post.

**Comment by jchristopher** [comment]
👍

**Comment by pippinsplugins** [comment]
Version 1.5 going out today or tomorrow at the latest.

**Comment by sumobi** [comment]
@pippinsplugins tested with WC and EDD, looks correct to me
