### ISSUE TITLE
Tracked affiliate coupons do not generate referrals when the "Apply before tax" checkbox is checked

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#497]
Tracked affiliate coupons do not generate referrals when the "Apply before tax" checkbox is checked on the coupon code's edit screen:

![screen shot 2015-01-08 at 1 06 05 pm](https://cloud.githubusercontent.com/assets/52581/5655834/7a337f0e-9738-11e4-8c74-34bf8de487bb.png)

When the checkbox is not checked, the referral is generated just fine.

Here's another interesting observation that might be of important. When "Apply before tax" is checked, and you proceed to PayPal, the order number is missing from the PayPal screen.

![screen shot 2015-01-08 at 12 40 23 pm](https://cloud.githubusercontent.com/assets/52581/5655847/b567b3b0-9738-11e4-9f79-7d4d85fc8918.png)

When it isn't checked, the order number shows and the layout is slightly different:

![screen shot 2015-01-08 at 12 42 31 pm](https://cloud.githubusercontent.com/assets/52581/5655852/d3752374-9738-11e4-975b-e043c40ba2f4.png)

In any case, WooCommerce is removing this checkbox in v2.3 as per http://develop.woothemes.com/woocommerce/2014/12/upcoming-coupon-changes-in-woocommerce-2-3/

Once v2.3 is out (or sooner if beta) we should double check that tracked coupons for WooCommerce work correctly. It seems that because the "Apply before tax" option is being taken out, coupons will always be applied before tax and then referrals might not work.

**Comment by sumobi** [comment]
@pippinsplugins i can confirm tracked coupons work fine in the 2.3 beta 1

**Comment by pippinsplugins** [comment]
Yay!

**Comment by pippinsplugins** [comment]
I vote we close this as wontfix. Any objections?

**Comment by sumobi** [comment]
Nope, close away
