### ISSUE TITLE
Restrict Content Pro - Per-membership commission amounts

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#501]
Like per-product commission amounts, but for membership levels

**Comment by sumobi** [comment]
@pippinsplugins If I go to the PayPal payment screen, click back, proceed again and so forth I can generate multiple referrals. The reference however does change each time

![screen shot 2015-08-26 at 7 02 51 pm](https://cloud.githubusercontent.com/assets/52581/9487372/1405318a-4c25-11e5-9a9c-2247d417ca7c.png)

Other than that it looks good! :+1:

**Comment by pippinsplugins** [comment]
@sumobi That's because the subscription key (used as reference) is generated after hitting submit. That won't be avoidable at this time.

**Comment by sumobi** [comment]
:+1:
