### ISSUE TITLE
MemberPress - Per-membership commission amounts

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#502]
Like per-product commission amounts, but for membership levels

**Comment by pippinsplugins** [comment]
@sumobi ready for testing.

**Comment by sumobi** [comment]
@pippinsplugins First time testing MemberPress. I can't get the per-product rate working, though I can't get the global rate working either. 

- MemberPress integration enabled
- visit is recorded fine
- transactions recorded in MP ok and set to "complete" (using offline payments)

Any ideas?

**Comment by sumobi** [comment]
@pippinsplugins looks like the referral isn't being created since I'm using offline payments and it goes straight to a completed status. mark_referral_complete() runs but there's no pending referral to update to unpaid.

**Comment by sumobi** [comment]
@pippinsplugins can't seem to get PayPal to store a pending referral either. What's the secret? :)

**Comment by sumobi** [comment]
Can you stick v1.2.3 on DropBox?

**Comment by pippinsplugins** [comment]
@sumobi it's there already

**Comment by sumobi** [comment]
Ahh it is indeed, was looking at the extracted folder, will test again

**Comment by sumobi** [comment]
@pippinsplugins Great, all I needed to do was upgrade. Normal referrals and more importantly per-membership referrals are working fine :+1: 

Found an issue with disabling the referral which is now fixed.

**Comment by pippinsplugins** [comment]
Woot!
