### ISSUE TITLE
Support for EDD Recurring Payments signup fee

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#503]
HelpScout ticket: https://secure.helpscout.net/conversation/65178025/4970/

From the customer:

<blockquote>
Just realize the AffiliateWP does not take into account of EDD signup fee. So I have a negative signup fee as the first month free trail for my subscription based service use EDD, and EDD recurring plugin.

So I set the monthly signup fee as $25 a month, but with first month signup fee of (-$24.5). So the first month payment is $0.5 (like a first month free trail with a transaction fee of $0.5). So user are paying $0.5 the first month.

The problem is, Affiliate WP record the affiliate earn (let say rate is 0.3) 30% of the $25 instead of 30% of the $0.5. In theory, I do not want the affiliate earn anything until their referral stay and pay the second month subscription fee of $25.

So I assumed Affiliate WP record the ACTUAL pay of the EDD customer. But it is NOT!! Please help me to fix this. I do not want to pay my affiliate $7.5 (30% of $25) but in fact we just earn $0.5!
</blockquote>

**Comment by michaelbeil** [comment]
Also, we should account for a negative signup fee: https://secure.helpscout.net/conversation/209891344/35445/?folderId=205524

**Comment by pippinsplugins** [comment]
Need to check but I'm pretty sure this is no longer necessary with Recurring Payments 2.4.

**Comment by pippinsplugins** [comment]
Nevermind, it's still a problem.

**Comment by pippinsplugins** [comment]
@sumobi @michaelbeil ready for testing.

**Comment by sumobi** [comment]
@pippinsplugins worked perfectly here for both a negative and positive sign up fee

**Comment by pippinsplugins** [comment]
Merged.
