### ISSUE TITLE
New referral status for opt-in/leads

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#505]
For customers that use our tracking shortcode, the default statuses don't entirely suit. 

For example, we have a customer using the tracking shortcode to generate `$0.00` referrals when a form is completed. They have set the status of the shortcode to be "pending" so they have a record of the referrals, but they don't necessary want to pay the affiliates. The customer is using this for a JV giveaway (Joint Venture) type set up.

If they leave the status as "pending" the referrals aren't reflected on the "Most Valuable Affiliates" table as it only sorts by earnings (default). Filtering this to referrals is fine, but then the referrals still don't show because they are pending. Although you can filter it by status, pending doesn't work and shows nothing. I take it this is because a referral isn't really a successful referral until it's been paid.

The customer has suggested a new status of either `opt-in` or `lead` which would allow them to use the shortcode in their scenario but are still able to see how well the affiliates are performing. "unpaid" isn't suitable as it sends an email to the affiliate saying they just earnt $0.00. It also doesn't sound right because you aren't going to pay them anything. 

The same applies to the "paid" status although this is what I've suggested for the time being to be able to see the referrals on the most valuable affiliates overview. It also doesn't send an email to the affiliate when switching from "pending" to "paid"

**Comment by pippinsplugins** [comment]
This sounds like an ideal situation for a free add-on that changes the
nature of referrals from referrals to leads. It could take care of tweaking
all the filtering and data display to operate more like lead tracking than
referrals.

**Comment by sumobi** [comment]
I agree

**Comment by sumobi** [comment]
I think it shouldn't completely override the statuses as someone might like to use the tracking shortcode in addition to another integration. A free add-on that adds a new status and makes some additional tweaks sounds good.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Related #672

**Comment by sumobi** [comment]
Closing in favor of https://github.com/AffiliateWP/AffiliateWP/issues/2198
