### ISSUE TITLE
Filter needed for get_columns() function

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#507]
@pippinsplugins  I need a filter for the following function: https://github.com/affiliatewp/AffiliateWP/blob/master/includes/class-affiliates-db.php#L30

When my add-on is activated I'm added a new column to the affiliates table in the DB, and want to use all the pre-existing methods we have for adding and updating.

I'd like to propose a `affwp_affiliates_db_get_columns` or similarly named filter like this:

    public function get_columns() {
		return apply_filters( 'affwp_affiliates_db_get_columns', 
			array(
				'affiliate_id'    => '%d',
				'user_id'         => '%d',
				'rate'            => '%s',
				'rate_type'       => '%s',
				'payment_email'   => '%s',
				'status'          => '%s',
				'earnings'        => '%s',
				'referrals'       => '%d',
				'visits'          => '%d',
				'date_registered' => '%s'
			)
		);
	}

**Comment by pippinsplugins** [comment]
Can you elaborate on what you're trying to do?

This is dangerous because it wouldn't actually create the column just by
registering it through the filter.

**Comment by sumobi** [comment]
I've added this new `product_rates` column (far right) though I can't get anything to save unless I add `product_rates` to the get_columns() function.

![screen shot 2015-01-15 at 4 26 02 pm](https://cloud.githubusercontent.com/assets/52581/5752078/5f861590-9cd3-11e4-9404-5b266ef64573.png)

**Comment by pippinsplugins** [comment]
Any reason not to store it in usermeta?

**Comment by sumobi** [comment]
nope, just thought it would look nice and pretty in the existing table :)

**Comment by sumobi** [comment]
But yes, I'll do it that way actually :+1:
