### ISSUE TITLE
Better anti-spam - reCaptcha 2.0 support

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#508]
We had a customer today report that the honey pot field on the registration form is getting bypassed by pesky spammers. We should add an option that lets admins choose whether to add an additional anti-spam type.

**Comment by sumobi** [comment]
:+1:

**Comment by pippinsplugins** [comment]
I vote we add support for the new reCaptcha: https://www.google.com/recaptcha/intro/index.html

**Comment by sumobi** [comment]
@fjarrett @pippinsplugins works great for me
