### ISSUE TITLE
Action hook after an affiliate is added

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#509]
After an affiliate is added I need an action hook somewhere around here:
https://github.com/affiliatewp/AffiliateWP/blob/master/includes/affiliate-functions.php#L693

Something like this:

    do_action( 'affwp_post_add_affiliate', $affiliate_id, $args, $data );

I know there's the `affwp_insert_affiliate` action hook in the add() function of class-affiliates-db.php but I need access to the `affiliate_id` and also the data submitted from the form fields in the `$data` array.

**Comment by pippinsplugins** [comment]
Both data and ID are available: https://github.com/affiliatewp/AffiliateWP/blob/master/includes/class-db.php#L87

**Comment by sumobi** [comment]
Already tried that hook. `$data` unfortunately doesn't include the form fields I'm submitting. Any suggestions? 
![screen shot 2015-01-16 at 9 21 23 am](https://cloud.githubusercontent.com/assets/52581/5765791/371a6cda-9d61-11e4-9670-be7df7aef6f0.png)

**Comment by pippinsplugins** [comment]
The custom fields?

**Comment by sumobi** [comment]
The ones here that I've added to the new affiliate screen

![screen shot 2015-01-16 at 11 11 10 am](https://cloud.githubusercontent.com/assets/52581/5767851/720f68e0-9d70-11e4-87fa-c47444072e20.png)

**Comment by sumobi** [comment]
Made a repo for it. Here's the 2 hooks for adding (this ticket) and updating (https://github.com/affiliatewp/AffiliateWP/issues/506#issuecomment-70036674) which I believe I need actions for based on the above: 

https://github.com/sumobi/affiliatewp-affiliate-product-rates/blob/master/affiliatewp-affiliate-product-rates.php#L181-L182

**Comment by pippinsplugins** [comment]
Since you're saving a form, you can access all of your data in the super global `$_POST`

**Comment by sumobi** [comment]
ooo let me have a play :+1:

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
I'm good on this, closing

**Comment by pippinsplugins** [comment]
:+1:
