### ISSUE TITLE
Referrals with a "paid" status using the [affiliate_conversion_script] shortcode don't increase referral counts

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#510]
When using the [affiliate_conversion_script] shortcode with a status of "paid", the referral count for the affiliate does not increment when the referral is generated.

Eg:

    [affiliate_conversion_script amount="0.00" description="My Description" context="Contact Form" reference="1234" status="paid"]

If you manually create the referral via "Add New Referral" and set the status to paid, it does update the referral count for the affiliate so seems like a bug with the shortcode where the action doesn't fire.

If you first set the status of the shortcode to "pending" and then manually update it to "paid" this also correctly increments the referral count.

**Comment by pippinsplugins** [comment]
Sounds like it's a similar situation as we had with manual referrals. Just need to start with a pending status and then move it to paid.

**Comment by sumobi** [comment]
This also prevents email notifications going out to the admin and the affiliate, doh

**Comment by pippinsplugins** [comment]
Looks like referrals are coming in as `unpaid` even when set to `paid` in `release/1.6`:

![screen shot 2015-04-05 at 6 41 21 pm](https://cloud.githubusercontent.com/assets/1034109/6999141/6ab202e2-dbc3-11e4-83d3-9d703ddabd6d.png)
![screen shot 2015-04-05 at 6 41 50 pm](https://cloud.githubusercontent.com/assets/1034109/6999142/706d7d2e-dbc3-11e4-9ac9-9ff7ee8328db.png)
