### ISSUE TITLE
2 new options for setting a default referral URL

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#513]
As mentioned in https://github.com/affiliatewp/AffiliateWP/issues/479 we should an option in the settings for allowing the site owner to set the default affiliate URL structure. This, in addition to the referral variable URL we already have would affect the default [affiliate_referral_url] shortcode as well as the affiliate dashboard's referral URL generator. 

I'm proposing 2 new options, based on the parameters in this PR: https://github.com/affiliatewp/AffiliateWP/pull/512

1. A `format` select menu that lets the user choose between `id` or `username`
2. A checkbox that enables pretty affiliate URLs

With the 2 new options a user will be able to achieve the following referral URLs:

    site.com/ref/1    // pretty URLs checked, format set to "id"
    site.com/ref/john // pretty URLs enabled, format set to "username"
    site.com/?ref=1   // pretty URLs unchecked, format set to "id"
    site.com/?ref=john // pretty URLs unchecked, format set to "username"

**Comment by sumobi** [comment]
Something like:

![screen shot 2015-01-18 at 8 12 13 pm](https://cloud.githubusercontent.com/assets/52581/5791720/65116ed8-9f4e-11e4-9a09-5fb15b0c6898.png)

**Comment by pippinsplugins** [comment]
Merged in with #598
