### ISSUE TITLE
MemberMouse - Refferals aren't created or created with $0 & no Reference Id or Description

### ISSUE THREAD

**Issue by contemplate** [affiliatewp/AffiliateWP#514]
We have version 1.5 of AlliateWP and the latest MemberMouse.
I followed instructions here: http://affiliatewp.com/docs/membermouse/  
both are using "ref"

I'm seeing Visits to the sales page being tracked per Affiliate but no Referrals records are being created even though we have actual conversions.   

I then added a [affiliate_conversion_script] shortcode to the member Thank You page just in case.  Now a referral record is created after the conversion but the amount is $0 and there is no Reference ID or Description.

Help?

**Comment by sumobi** [comment]
Hi @contemplate, we'd love to help resolve your issue. Please open a support ticket here: http://affiliatewp.com/support/

**Comment by contemplate** [comment]
Done.  Thanks!
