### ISSUE TITLE
Switch div's to p's in affiliate area

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#518]
We should consider switching out the `div`'s on the following pages to paragraph tags inside for more consistent styling across themes. Most theme's wouldn't have bottom margin for our custom divs but would most likely have margin at the bottom of the p tags. 

#### Before (note the spacing below the input fields)
![screen shot 2015-01-21 at 1 31 37 pm](https://cloud.githubusercontent.com/assets/52581/5829103/03727eee-a172-11e4-9c02-33e480ee311b.png)

#### After:
![screen shot 2015-01-21 at 1 31 28 pm](https://cloud.githubusercontent.com/assets/52581/5829104/0374f3e0-a172-11e4-8bed-cdd2e8a39cc0.png)

#### Before:
![screen shot 2015-01-21 at 1 30 17 pm](https://cloud.githubusercontent.com/assets/52581/5829105/0375331e-a172-11e4-8e27-7d9ae80b9f95.png)

#### After
![screen shot 2015-01-21 at 1 30 04 pm](https://cloud.githubusercontent.com/assets/52581/5829106/037554fc-a172-11e4-8cd8-df58d278263f.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
@pippinsplugins Another idea I think I prefer is to keep them as divs and simply make a new CSS class that we can apply to all wrapping divs. This way we still have control over how it looks and don't risk a theme applying unruly margins to p's. And of course the customer can always edit HTML from template files.

Currently there's this rule which is only applied to the inputs on the Affiliate URLs tab:

    .affwp-base-url-wrap, .affwp-referral-url-wrap {
       margin-bottom: 10px;
    }

On the settings tab the inputs don't have bottom margins which is why they look too crammed. 10px also isn't enough on the Affiliate URLs tab.

How about we create 1 CSS class called `affwp-wrap`, give it something like 20px bottom margin, and apply to each div where needed. We can then remove the 10px margin rule.

**Comment by pippinsplugins** [comment]
I like that idea better.
