### ISSUE TITLE
Exported referral .csv is showing blank

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#523]
A customer has reported an issue when exporting referrals as shown here:

![screen shot 2015-01-22 at 9 53 46 am](https://cloud.githubusercontent.com/assets/52581/5844912/ad042700-a21c-11e4-9425-177482b036f7.png)

No matter what the date range, a blank .csv file is exported. I've also tried on our site and noticed the same behaviour. If I leave everything at default (blank) and hit export, I get a .csv for my username which doesn't look right:

![screen shot 2015-01-22 at 9 55 46 am](https://cloud.githubusercontent.com/assets/52581/5844944/dcdc7f2c-a21c-11e4-8389-0e961c54f366.png)

It should have shown me all affiliates

**Comment by pippinsplugins** [comment]
Well that's weird.

**Comment by pippinsplugins** [comment]
I'll try and get it fixed during Pressnomics or on Monday just after.

**Comment by sumobi** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Works fine for me.
![screen shot 2015-01-26 at 10 27 52 pm](https://cloud.githubusercontent.com/assets/1034109/5913487/9bf4bd58-a5aa-11e4-92b9-fd5da0defbf6.png)

**Comment by pippinsplugins** [comment]
I've tested this with every variation I can think of and it never fails.
