### ISSUE TITLE
Multiple referrals recorded for same order

### ISSUE THREAD

**Issue by renegadesk** [affiliatewp/AffiliateWP#527]
Using version 1.5.1
Add-ons:
AffiliateWP - Lifetime Commissions
AffiliateWP - Order Details For Affiliates
AffiliateWP - Recurring Referrals	
AffiliateWP - Store Credit

Three referrals are recorded for this order, all a few minutes apart as per the orders notes in the screenshot. On the referral screen, just one of the referrals is marked as paid, the other two are still pending. 

The customer is new, so I don't think any of the add-ons would affect this.

![edit_order_ _goodmix_superfoods_ _wordpress](https://cloud.githubusercontent.com/assets/507331/5868484/546d6060-a2fe-11e4-9075-289820018ad0.jpg)

**Comment by sumobi** [comment]
Hey @renegadesk, see this issue: https://github.com/affiliatewp/AffiliateWP/issues/403#issuecomment-69124279

Does that sound like what is happening? Is it only for this 1 order?

**Comment by renegadesk** [comment]
@sumobi that looks about right, apologies for the duplicate. It's not just this order, I've attached a screenshot for another one. 

![307eee70-d309-4510-8c0f-974f2541d484](https://cloud.githubusercontent.com/assets/507331/5912943/38307642-a62f-11e4-9dca-a9609ed60ca1.jpg)

**Comment by pippinsplugins** [comment]
That appears to be creating a referral each time the charge is attempted. Odd indeed.
