### ISSUE TITLE
LeadPages integration

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#529]
We have quite a few customers wanting to use AffiliateWP with LeadPages (https://www.leadpages.net/). Since LeadPages generates static HTML, AffiliateWP tracking will not work.

We've discussed the possibility of making a small JavaScript snippet that takes the affiliate ID from the URL and stores it as the `affwp_ref` cookie which AffiliateWP uses. When a customer lands on the page generated from LeadPages using an affiliate's referral URL, then proceeds to the "real" website where AffiliateWP is installed, the `affwp_ref_visit_id` will hopefully be generated and tracking will work as usual.

Based on this link, it looks like custom JS is possible:
http://docs.leadpages.net/#recommendations-amp-notes-about-files-and-folders

<blockquote>
Best practice! Put common or custom Javascript code in a single file in the js/ directory (i.e.js/functions.js).
</blockquote>

**Comment by pippinsplugins** [comment]
It'd be really cool if there is a way we could hook into it and add the JS automatically.

**Comment by sumobi** [comment]
@pippinsplugins I've sent LeadPages a support enquiry and linked them here.

**Comment by sumobi** [comment]
Here's a gist that should work for this: https://gist.github.com/sumobi/44322e0c35ef307be1bc

**Comment by pippinsplugins** [comment]
So we just have users add this to their page?
```html
 
<!-- jQuery is required -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
 
<!-- jQuery cookie is required -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
 
<script>

jQuery(document).ready(function($) {

	// Configuration options
	
	// the referral variable, eg "ref". Must match the referral variable on your site where AffiliateWP is installed
	var referral_variable = "ref";

	// target URL where AffiliateWP is installed
	var target_url = "http://yoursite.com";

	// name of the cookie. Should not match the name of AffiliateWP's cookies
	var cookie_name = "affwp_ref_value";

	// End Configuration options
	

	// get the cookie value
	var cookie = $.cookie( cookie_name );

	// get the value of the referral variable from the query string
	var ref = affiliatewp_arl_get_query_vars()[referral_variable];

	// if ref exists but cookie doesn't, set cookie with value of ref
	if ( ref && ! cookie ) {
		var cookie_value = ref;

		// Set the cookie and expire it after 24 hours
		$.cookie( cookie_name, cookie_value, { expires: 30, path: '/' } );
	}
	

	// split up the query string and return the parts
	function affiliatewp_arl_get_query_vars() {
		var vars = [], hash;
		var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
		for (var i = 0; i < hashes.length; i++) {
			hash = hashes[i].split('=');
			vars.push(hash[0]);
			vars[hash[0]] = hash[1];
		}
		return vars;
	}


	// the affiliate ID will usually be the value of the cookie, but on first page load we'll grab it from the query string
	if ( cookie ) {
		affiliate_id = cookie;
	} else {
		affiliate_id = ref;
	}

	// affiliate ID exists, change the URLs on the page
	if ( affiliate_id ) {
		// get all the targeted URLs on the page that start with the specific URL
		var target_urls = $('a[href^="' + target_url + '"]');

		console.log( target_urls );

		// modify each target URL on the page
		$(target_urls).each( function() {
			
			// get the current href of the link
			current_url = $(this).attr('href');
			
			console.log( updateQueryStringParameter( current_url, referral_variable, affiliate_id ) );

			// append a slash to the URL if it doesn't exist
			current_url = current_url.replace(/\/?$/, '/');

			$(this).attr('href', updateQueryStringParameter( current_url, referral_variable, affiliate_id ) );
			
		});

	}

	function updateQueryStringParameter(uri, key, value) {
	  var re = new RegExp("([?|&])" + key + "=.*?(&|#|$)", "i");
	  if (uri.match(re)) {
	    return uri.replace(re, '$1' + key + "=" + value + '$2');
	  } else {
	    var hash =  '';
	    var separator = uri.indexOf('?') !== -1 ? "&" : "?";    
	    if( uri.indexOf('#') !== -1 ){
	        hash = uri.replace(/.*#/, '#');
	        uri = uri.replace(/#.*/, '');
	    }
	    return uri + separator + key + "=" + value + hash;
	  }
	}
	
});
</script>
```

**Comment by sumobi** [comment]
@pippinsplugins Works when I test it, they would need to configure the first 2 config options. LeadPages allows you to enter custom JS into the pages but I haven't got an account to test.

**Comment by sumobi** [comment]
Oh yeah, I guess you can chuck it straight into the page also, but I think they'd want it on every page, hence using LeadPages custom JS insert area.

**Comment by pippinsplugins** [comment]
Sweet, so we just need to get a doc written up on how to do this.

**Comment by sumobi** [comment]
:+1: We almost had a customer get this implemented on their leadpages site, but then they decided to go a different route. From what I saw on their LP landing page they had added the code and the cookie was properly set, but they didn't understand the concept of changing the `target_url` to their "real" site.

**Comment by ramiabraham** [comment]
Related: https://secure.helpscout.net/conversation/260605187/0/

**Comment by santiazpi** [comment]
Code works like a charm by adding to each lead page end-of-body tracking code - and of course, outgoing links much be an exact match to the target_url Thank you @pippinsplugins !

**Comment by santiazpi** [comment]
I must restate, no, it does not work with the wordpress plugin. For whoever is looking for a hack, here is how I did for Leadpages:
Edited /wp-content/plugins/leadpages/App/Front/Controllers/ and at line 191 or around added:
`$html_add_to_body_close = <<<EOF
/*code above minus jQuery*/
</body>
EOF;

$html = str_replace( '</body>', $html_add_to_body_close, $html);
`
In case it helps anybody else

**Comment by secoskyj** [comment]
What I've done is create a Wordpress page with a javascript redirect on it to the Leadpage.  The Wordpress page gets the cookies on the client just before sending them to the Leadpage.  The URL changing might be confusing for folks, but it may be good enough for now.

I have this javascript code on the Wordpress page "product-page-ref" to redirect to the real product page.  I use "product-page-ref" with my affiliates.

```
<script>
window.location = "http://example.com/product-page";
</script>

```
