### ISSUE TITLE
Allow paragraphs in referral descriptions

### ISSUE THREAD

**Issue by ryanduff** [affiliatewp/AffiliateWP#531]
Referral description should allow for more than a single line. 

Proposing:
* Make form element text area rather than text input
* Run output through wpautop() or similar to support newlines/formatting
* Add filter to table class to allow output to be filtered

**Comment by pippinsplugins** [comment]
Aside from tweaking the display of the description field in the Referrals table, I don't see any issue with this.

@sumobi ?

**Comment by ryanduff** [comment]
What did you mean by tweaking? Not sure I followed what you meant there. 

As far as I'm concerned-- should just respect linebreaks or something on output. Saving data to DB with newline characters and because the text outputs as-is from the DB it all just runs together. 

Wouldn't make much sense to allow multi-line on saving if it wasn't appropriately formatted on output ;)

**Comment by pippinsplugins** [comment]
We'd just need to make sure that a long description doesn't break the table.

That does bring up the question of how to best display it then. Since we definitely don't want long descriptions displayed inline in the table, should we have a details page?

**Comment by ryanduff** [comment]
That makes sense. Maybe just not show description in table if over x characters long? 

It'll always show in the text area when looking at the edit referral screen. 

Similar comparison would be user notes field in RCP

**Comment by pippinsplugins** [comment]
Showing on the edit screen would work fine. I like the idea of at least showing the excerpt of the description since the vast majority of the time it will be just a few words long.

**Comment by pippinsplugins** [comment]
Since we're getting close to getting 1.6 pushed out and this isn't pressing, I'm going to punt it to 1.7.

**Comment by pippinsplugins** [comment]
Thanks @fjarrett !

**Comment by fjarrett** [comment]
:bow: happy to help
