### ISSUE TITLE
Choose which automatic emails we want to send

### ISSUE THREAD

**Issue by naomicbush** [affiliatewp/AffiliateWP#532]
Right now, emails are automatically sent with no UI or even a filter to turn them off. I had no idea emails were being sent behind-the-scenes so I ended up with notifications going out before the site was ready.

**Comment by sumobi** [comment]
@naomicbush See this example for turning off the affiliate approval email: http://docs.affiliatewp.com/article/644-disable-affiliate-approval-emails

The other 2 emails can be turned off in much the same way

**Comment by naomicbush** [comment]
@sumobi thanks. That's how I'm handling it, but I still think there should still be a warning and a UI or a proper filter.

**Comment by sumobi** [comment]
Why do you need a filter when there's the remove_action? Was it just the affiliate approval that got sent out when you imported users? The only others are admin notification when an affiliate registers and a new referral email for the affiliate which they have to turn on from the affiliate dashboard. 

There are lots of improvements coming to emails soon so we could possibly add a checkbox in the admin. Thoughts @pippinsplugins?

I'll see what we can do about including a note in the docs to warn people to disable the emails when importing etc and with the "auto register new users" as affiliates.

**Comment by naomicbush** [comment]
Because remove_action is the brute-force way to handle it, while the filter lets me know that the plugin author knows that I might want to override this and will account for it and not break things in the future. I see it as the "polite" way to allow people to extend your plugin :-)

**Comment by pippinsplugins** [comment]
With the introduction of the email settings (started in #392), we will be adding a lot better control. Primarily we'll be added settings for all emails so the exact messages can be defined.

I don't see `remove_action` as brut forcing. It's a different approach than a filter but no more right or wrong.

**Comment by pippinsplugins** [comment]
#392 has been merged into `release/1.6` so we now have settings for each of the emails that gets sent out. I'm going to go ahead and close this one out.

**Comment by Basilakis** [comment]
Regarding that one here, there is still no setting checkbox, for other than the main email for the administrator ( To send or not )

**Comment by sumobi** [comment]
@Basilakis What version are you on? There should be this option above the logo field

![screen shot 2017-01-14 at 2 17 19 pm](https://cloud.githubusercontent.com/assets/52581/21950893/3c0c9712-da64-11e6-9645-98c54696e0bf.png)
