### ISSUE TITLE
Sorting affiliates by name clears list

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#534]
When clicking "Name" on the affiliates page to sort them the affiliates disappear. 

WordPress database error Unknown column 'name' in 'order clause' for query SELECT * FROM wp_affiliate_wp_affiliates  ORDER BY name asc LIMIT 0,30; made by do_action('affiliates_page_affiliate-wp-affiliates'), call_user_func_array, affwp_affiliates_admin, AffWP_Affiliates_Table->prepare_items, AffWP_Affiliates_Table->affiliate_data, Affiliate_WP_DB_Affiliates->get_affiliates

**Comment by pippinsplugins** [comment]
Thanks @tubiz !
