### ISSUE TITLE
Referral amount with WC coupon incorrect

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#541]
WooCommerce 2.3.3
AffiliateWP 1.5.2

Steps to reproduce:

1. Set up a new product in WooCommerce and set it's price to $59.
2. Set the product's referral rate to 50%
3. Set a coupon code in WC to take $20 of the cart

## Expected result - $19.50 referral

$59 - $20 discount = $39 total
50% of $39 = $19.50 referral

## Actual result - $9.50 referral

This is how I think it's being worked out:

50% of $59 = $29.50 referral
$29.50 - $20 discount = $9.50 referral

As you can see in the actual result, the referral isn't being based on the total minus the discount. @pippinsplugins would you agree that this is a bug? I've tested locally and I receive the same $9.50 referral as the customer which I believe is incorrect.

**Comment by pippinsplugins** [comment]
While you're break down appears right based on the numbers, the code disagrees:
```php
if( $cart_discount > 0 ) {

	$discount = $cart_discount / count( $items );

}

$product_total -= $discount;

if( $cart_shipping > 0 && ! affiliate_wp()->settings->get( 'exclude_shipping' ) ) {

	$shipping       = $cart_shipping / count( $items );
	$product_total += $shipping;

}

if( ! affiliate_wp()->settings->get( 'exclude_tax' ) ) {

	$product_total += $product['line_tax'];

}

if( $product_total <= 0 ) {
	continue;
}
```

**Comment by pippinsplugins** [comment]
Found it! Turns out with WooCommerce 2.3 they have started adding discount to product line totals, so there is no longer a need for us to manually remove discount amounts, as we did before:

```php
if( $cart_discount > 0 ) {

    $discount = $cart_discount / count( $items );

}

$product_total -= $discount;
```
