### ISSUE TITLE
Affiliate Discount display issue

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#542]
As reported by customer. Have replicated with WC 2.3.3

![screen shot 2015-02-17 at 9 45 29 am](https://cloud.githubusercontent.com/assets/52581/6219042/c6c8c93a-b689-11e4-8790-1db8d930698b.png)

**Comment by sumobi** [comment]
It's caused by this CSS rule WooCommerce now has in their admin stylesheet:

    .wc_addons_wrap .products,.simplify-commerce-banner,.order_actions li#actions,#woocommerce-coupon-data .panel-wrap,#woocommerce-product-data .panel-wrap,.woocommerce .panel-wrap {
        overflow:hidden;
    }

**Comment by pippinsplugins** [comment]
I wonder if removing that will have any negative side effects . . .

**Comment by pippinsplugins** [comment]
Yep, super bad: 
![screen shot 2015-02-18 at 11 16 20 am](https://cloud.githubusercontent.com/assets/1034109/6252397/9c04ce3e-b75f-11e4-9714-41d1db2f72c4.png)

**Comment by pippinsplugins** [comment]
I've just played with automatically positioning the results above the input field based on the height of the search results.

@sumobi Could you pull down master and let me know what you think? Make sure script debug is enabled.

**Comment by sumobi** [comment]
@pippinsplugins Looks good to me, actually prefer it on top now. We should probably make ours 50% width like there inputs so it blends in nicer:

![screen shot 2015-02-19 at 10 06 16 am](https://cloud.githubusercontent.com/assets/52581/6256702/201cdd1e-b81f-11e4-811e-97efb5a01a05.png)

How about putting the loading icon inside the input? at the moment it overlaps the help tip:
![screen shot 2015-02-19 at 10 10 04 am](https://cloud.githubusercontent.com/assets/52581/6256752/8b7ae664-b81f-11e4-9dbb-cef945ff37d0.png)

something like

    .affwp-ajax {
        position: absolute;
        right: 30px;
        top: 5px;
    }

**Comment by pippinsplugins** [comment]
I have the width to 50% now but I'm having trouble getting the ajax indicator positioned properly. Ideas?

**Comment by sumobi** [comment]
The CSS above should have worked, but I did it in the browser. I'll have a look

**Comment by sumobi** [comment]
Oh I know why, the ajax loader would need to be wrapped in another container that also had the input field in it

**Comment by sumobi** [comment]
While we're here, does Affiliate Discount really need the `?` at the end. I think we could remove it, it still makes sense.

**Comment by pippinsplugins** [comment]
I'm fine with removing it.

**Comment by sumobi** [comment]
What if we just left the loader where it was? it's not that bad, although it could come down a few pixels
![screen shot 2015-02-19 at 10 58 43 am](https://cloud.githubusercontent.com/assets/52581/6257675/1d410914-b827-11e4-9260-81a85d4ef249.png)

**Comment by pippinsplugins** [comment]
If we remove the ?, we can leave it where it is.
