### ISSUE TITLE
MarketPress Integration

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#543]
We've had a few customers request integration with MarketPress:

https://wordpress.org/plugins/wordpress-ecommerce/

There's also the pro version:
http://premium.wpmudev.org/project/e-commerce/

**Comment by tubiz** [comment]
Let me take this.

**Comment by sumobi** [comment]
awesome @tubiz !

**Comment by tubiz** [comment]
@sumobi @pippinsplugins  as regards the MarketPress integration am through with it, but the issue now
 is MarketPress doesn't have any actions to hook into if a transaction is cancelled or a refund is made, this means there is no way to revoke a referral when this occurs.
This are the order status that MarketPress have Received, Paid, Shipped, Closed and Trash.
Suggestions will be appreciated toward this.

**Comment by pippinsplugins** [comment]
Excellent!

We could revoke when an order is trashed. That'd better than nothing.

**Comment by tubiz** [comment]
Ok, will add support for revoking a referral when an order is trashed.

**Comment by pippinsplugins** [comment]
Things for @sumobi and I to do:
- [ ] Add final PHPDoc
- [ ] Final testing

**Comment by pippinsplugins** [comment]
This all looks great @tubiz !
