### ISSUE TITLE
Minify jquery.cookie.js

### ISSUE THREAD

**Issue by GaryJones** [affiliatewp/AffiliateWP#545]
The `jquery.cookie.js` file that is referenced on the front-end of sites running this plugin is not minified. It appears to be the only `assets/js` file that isn't minified.

Is there a reason for this?

https://github.com/carhartl/jquery-cookie appears to both have a new release (1.4.1 compared to AWP's 1.4.0), and a Grunt task which supports uglifying the source file.

**Comment by pippinsplugins** [comment]
Pretty sure it's just because there was not a minified version of the file when we first used it.

We'll get it added!
