### ISSUE TITLE
Referral status rejected with failed credit card charge even when subsequent charges are successful

### ISSUE THREAD

**Issue by renegadesk** [affiliatewp/AffiliateWP#546]
![edit_order_ _goodmix_superfoods_ _wordpress](https://cloud.githubusercontent.com/assets/507331/6386685/4a29cd58-bdd1-11e4-9d8b-d23cffb94e43.jpg)

Order notes attached, this one has the referral status as "rejected". Is this expected behaviour? Perhaps we could also check for future order changes such as an order being marked as complete, which should change the referral from rejected to unpaid.

**Comment by pippinsplugins** [comment]
Why did the transaction go from Approved in Braintree to Declined?

The "rejected" status is correct since the payment was declined.

**Comment by renegadesk** [comment]
Yep that makes sense, but if the transaction is then re-tried and it is successful, then the transaction is complete and the order is a success. In this case, the referral should be a success as well.

**Comment by renegadesk** [comment]
Hey @pippinsplugins any further thoughts on this one? Is it something you are expecting to work on? Cheers.

**Comment by pippinsplugins** [comment]
I suspect this is similar to #614

We'll look at it again for 1.6.2.

**Comment by pippinsplugins** [comment]
@renegadesk Any chance you could test this again the current `master` branch? I believe it's resolved now.

**Comment by renegadesk** [comment]
Sure can Pippin, thanks for the update! I should be able to try within the next week.

**Comment by fjarrett** [comment]
Hey @renegadesk, any updates from your end on the outcome of this?

**Comment by renegadesk** [comment]
Hey there @fjarrett apologies for not getting back to you guys! I haven't had a case come up where I've been able to replicate this exact situation, but with PayPal the issue seems to be solved.

**Comment by pippinsplugins** [comment]
I'm going to close this out then. If it ever pops up again, feel free to re-open.
