### ISSUE TITLE
Add-on Idea: tax form generator (1099)

### ISSUE THREAD

**Issue by mgibbs189** [AffiliateWP/AffiliateWP#549]
The IRS requires sending out a 1099 form for U.S. users earning more than $600.

Maybe we can create an add-on to let users download their 1099 form from their account page (and/or notifies them via email)?

**Comment by pippinsplugins** [comment]
I'd love to see this

**Comment by sumobi** [comment]
:+1:

**Comment by zackkatz** [comment]
:+1:

**Comment by michaelbeil** [comment]
:+1: from a user and myself. 

https://secure.helpscout.net/conversation/164785342/26386/?folderId=205529

**Comment by worldtravlr** [comment]
@mgibbs189 beat me to it!  Would love this!

As many of your customers may be from the USA and any affiliate that makes more than $600 per year has to be issued a 1099, it would be really awesome if there was a free or paid plugin that would allow affiliates to enter their mailing address, Tax ID/SSN, etc and then if at the end of the year, we could just go into AffiliateWP and click a button/run a report to export PDFs of 1099s ready to be sent to the affiliates. Even cooler would be if those PDFs could then be added to each unique affiliates Dashboard and a notification sent to them to login and download the documents.

Not sure if there is any interest, but we pay about $250 a year to get 1099s done, so would be willing to pay something similar to that for a plugin that would make it quicker and easier :-)

**Comment by DrewAPicture** [comment]
Related discussion on #517.
