### ISSUE TITLE
Creatives template needs HTML adjustments/more flexibility

### ISSUE THREAD

**Issue by sdavis2702** [affiliatewp/AffiliateWP#550]
This is stemming from an [EDD site issue](https://github.com/easydigitaldownloads/EDD-Site/issues/456) and I want to change the order of the content for each creative on the page as well as adjust the HTML. I haven't confirmed this myself but Pippin said it's not editable at the moment.

In [this particular case](https://easydigitaldownloads.com/your-account/affiliate-area/?tab=creatives), I want to put the title/dimensions of the creative above the creative and the code, as I feel that makes more sense. I also want the code to be wrapped in `pre` tags since it's code. 

So a little more control here (and maybe even core adjustments) is the goal.

**Comment by sumobi** [comment]
@sdavis2702 

description is now included at the top

![screen shot 2015-03-04 at 4 24 58 pm](https://cloud.githubusercontent.com/assets/52581/6494934/1bf9aee4-c28b-11e4-99d6-bcba69216d00.png)

**Comment by sumobi** [comment]
@sdavis2702 

We've also added both `pre` and `code` tags to ensure a consistent experience across themes.

![screen shot 2015-03-04 at 4 28 01 pm](https://cloud.githubusercontent.com/assets/52581/6494973/7ad02b78-c28b-11e4-88cd-864db9687eef.png)

**Comment by sumobi** [comment]
The above commits also add a `description` parameter to the [affiliate_creative] shortcode
