### ISSUE TITLE
Woo commerce discount for returning customers 

### ISSUE THREAD

**Issue by Rajbir4all** [affiliatewp/AffiliateWP#551]
Hello,

Is it possible to make a hook for discount to returning customers those who already placed an order with us and done with a payment.

If they visit our website again i want to give them 10% discount .

please suggest.

Thanks

**Comment by sumobi** [comment]
@Rajbir4all Absolutely, but this doesn't have anything to do with AffiliateWP. If you'd like to give returning customers a discount, you would write some code to interact with WooCommerce.

I'm going to close this issue since it's not related to AffiliateWP.

**Comment by Rajbir4all** [comment]
Where can i post this then ??

Sent from my HTC

----- Reply message -----

**Comment by sumobi** [comment]
@Rajbir4all You need to contact WooCommerce support
