### ISSUE TITLE
Inactive affiliate sometimes given referrals 

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#554]
We just have a report of a site that had a referral get created for an inactive affiliate.

Referrals should never be created when an affiliate is NOT active.

This particular customer was using EDD and EDD Commissions. I don't think they are related but I'm noting them here just in case.

**Comment by ryanduff** [comment]
Possibly related to #559 ?

**Comment by pippinsplugins** [comment]
Pretty sure this is now fixed via 2ab7226dfc1599c3013d1f23569e189340842c0e and 461c6188dd335b977a8eac3a9e5686164bf5d76f
