### ISSUE TITLE
Add products column to referrals table

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#556]
We need to add a `products` column to the referrals DB to hold the details of all products purchased and their respective referral rates.

I propose we store product details as a serialized array with the following keys:
- name
- price
- referral_amount
- id

This will allow us to track and look up how much of the referral total each product in a purchase is responsible for. With this information, store owners will be able to refund one product in a purchase and then properly adjust the commission total to reflect the refund. Right now it's all or nothing.

This change is required for us to fix #555

**Comment by codelion7** [comment]
This is an excellent idea, and I think it will be perfect for my next project. I'm going to be expanding the PMP integration to allow user's to set Per Membership Level, Per Product Commission Rates.So for example, site admins will be able to set a different commission rate for the sale of Level 1 Memberships, based on the Membership Level of the referring affiliate.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by ryanduff** [comment]
Going to try and get this one wrapped up and submit a PR submitted in the next few days. May also kill the need for #531 by having a dedicated products column.

**Comment by pippinsplugins** [comment]
Awesome, thanks @ryanduff !

**Comment by pippinsplugins** [comment]
@ryanduff I'm working on this now. Sorry if you'd already done some work on it.

**Comment by pippinsplugins** [comment]
For 1.6, I'm adding this to all integrations that support per-product rates, which means WooCommerce, EDD, and Exchange.

**Comment by pippinsplugins** [comment]
The products of a referral can be set like this:
``php
$referral_id = affiliate_wp()->referrals->add( 
	array(
		'amount'       => $referral_total,
		'reference'    => $payment_id,
		'description'  => $this->get_referral_description( $payment_id ),
		'affiliate_id' => $this->affiliate_id,
		'context'      => $this->context,
		'products'     => $this->get_products( $payment_id )
	)
);
```

Retrieving the products is as simple as accessing the `products` property of the referral object returned by `affwp_get_referral()`.
