### ISSUE TITLE
Inactive affiliates can receive commission when using tracked discount codes

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#559]
So far this is the case with EDD, will test with WC etc soon

**Comment by sumobi** [comment]
WooCommerce is affected also

**Comment by ryanduff** [comment]
It looks like `is_valid_affiliate()` is trying to be a bit too clever on the return line. I've run into some screwy circumstances and had unexpected results. 

https://github.com/affiliatewp/AffiliateWP/blob/28816991213f6eb206c7a708d5eee47d837f5ff7/includes/class-tracking.php#L530

Going to take a stab at this over the weekend along w/ some unit tests to cover all scenarios and ensure we get the right response. 

Both EDD and WooCommerce use that function so it should resolve both instances noted here.

**Comment by pippinsplugins** [comment]
@ryanduff Awesome, thanks so much.

**Comment by sumobi** [comment]
:+1:
