### ISSUE TITLE
Clarification: AffiliateWP and EDD Discount Codes

### ISSUE THREAD

**Issue by mgibbs189** [affiliatewp/AffiliateWP#561]
Hi, let's say an EDD product costs $100.

* The user enters a 40% off Discount Code
* The user was referred by an affiliate with a 20% referral rate.

The user pays $60. Should the affiliate earn $12 (20% of $60) or $20?

**Comment by mgibbs189** [comment]
Actually, nevermind. It's way too late :)

It looks like the $12 answer is correct, and how AffiliateWP is handling it.

**Comment by pippinsplugins** [comment]
:)
