### ISSUE TITLE
Filter the creatives arguments

### ISSUE THREAD

**Issue by seb86** [affiliatewp/AffiliateWP#562]
When adding a new creative or editing a creative, there is no filter applied to the arguments.

**Comment by pippinsplugins** [comment]
There are several actions / filters you can user actually.

Could you tell me what you're trying to do? I can point you in the right direction (assuming this is a filter).

**Comment by seb86** [comment]
What I would like to do is create a custom field for my client that allows him to place a custom embed code rather than a text link or image. I put these filters in place so that the custom field data is passed through. Was I wrong to do this?

**Comment by pippinsplugins** [comment]
No, not wrong, it's just unnecessary.

You can use the `affwp_insert_creative` hook to add custom data to a creative.

**Comment by pippinsplugins** [comment]
Closing as wontfix since the affwp_insert_creative hook can be used.
