### ISSUE TITLE
Show an affiliate their current referral rate

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#572]
We should show an affiliate their current referral rate on their affiliate dashboard. This would also integrate with the tiered affiliate rates add-on and change depending on the tier they are on.

**Comment by ryanduff** [comment]
Isn't this currently on the statistics tab? 

https://github.com/affiliatewp/AffiliateWP/blob/7c35fedd2532193b4fb73c0e41419d45b661586a/templates/dashboard-tab-stats.php#L43

**Comment by sumobi** [comment]
@ryanduff you're absolutely right :) Too early I guess
