### ISSUE TITLE
 Retrieves the affiliate's email address with WP function

### ISSUE THREAD

**Issue by yogoeasy** [affiliatewp/AffiliateWP#574]
In /includes/affiliate-functions.php

1. Remove line 260:
<code>global $wpdb;</code>

2. Modify line 276:
<code>$email   = $wpdb->get_var( $wpdb->prepare( "SELECT user_email FROM $wpdb->users WHERE ID = '%d'", $user_id ) );</code>

into:
<code>$user_info = get_userdata($user_id);</code>
<code>$email   = $user_info->user_email;</code>

refer: http://codex.wordpress.org/Function_Reference/get_userdata

**Comment by pippinsplugins** [comment]
@yogoeasy Are you proposing this for performance reasons?

**Comment by yogoeasy** [comment]
@pippinsplugins  I think it's more native.

**Comment by pippinsplugins** [comment]
We did it this way because it has better performance.

**Comment by yogoeasy** [comment]
I see, thanks.

**Comment by ghost1227** [comment]
@pippinsplugins Can this be closed as `wont-fix`?

**Comment by michaelbeil** [comment]
@ghost1227 it would appear so.

**Comment by pippinsplugins** [comment]
Yes.
