### ISSUE TITLE
Add support for Sprout Invoices

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#575]
We should add support for Sprout Invoices.

**Comment by pippinsplugins** [comment]
#573

**Comment by dancameron** [comment]
Thank you! :thumbsup:

**Comment by dancameron** [comment]
https://github.com/affiliatewp/AffiliateWP/pull/588

**Comment by pippinsplugins** [comment]
Looks like a little of the formatting on the integrations class got overwritten. No big deal; just noting it for reference so we don't forget it

**Comment by dancameron** [comment]
What's weird is I noticed that too but only on github; not when I look at the files in sublime (or textmate).

**Comment by pippinsplugins** [comment]
It's the spaces vs tabs issue.

We use tabs for indention; spaces for alighment.
