### ISSUE TITLE
Integration Hooks

### ISSUE THREAD

**Issue by dancameron** [affiliatewp/AffiliateWP#577]
These actions aren't technically necessary but when I worked on my integration I was looking for an easy way to load up the Affiliate_WP_Base subclass at the ideal time, which I could not find. This is different than filtering the integrations via affwp_enabled_integrations becuase there's no way to have the loop load up the subclass (i.e. require) since the file path is a constant (and defined).

I guess I could have simply asked "How would you advise an third-party integration without modifying core?", since you might have a better solution.

PR #576

**Comment by pippinsplugins** [comment]
I've renamed the hooks to `affwp_integrations_load` and `affwp_integrations_loaded` for consistency with the rest of our hooks.
