### ISSUE TITLE
Pending/rejected/inactive affiliates should not see dashboard or see shortcode data

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#583]
Currently, pending, rejected and inactive affiliates can see the affiliate dashboard. They can also see content placed in the [affiliate_content] shortcodes, creatives etc. Only active affiliates should see these.

**Comment by pippinsplugins** [comment]
@sumobi Could you submit the PR for this so we can get it merged in from your fork?

**Comment by pippinsplugins** [comment]
#584
