### ISSUE TITLE
Error w/ PMP revoke_referral_on_delete() & reference_link()

### ISSUE THREAD

**Issue by codelion7** [AffiliateWP/AffiliateWP#594]
I just noticed that the revoke_referral_on_delete() function is currently using the $order_id as the reference to pass into reject_referral(). Since the reference stored for PMP referrals is actually the $order->code, deleted PMP orders aren't being rejected.

The reference_link() function is also using the $order->code (which is stored as the reference for PMP referrals). Because of this, clicking on the reference link takes you to a New Order screen in PMP, instead of taking you to the order directly.

**Comment by codelion7** [comment]
The way things are now, the PMP $order->code is being used as the reference for all PMP referrals, and the actual $order->id is being stored as "custom" referral data. 

Ideally, I would like to free up the custom PMP referral data so that I can use it to keep track of "referral types". I'm in the process of finishing the PMP integration for the MLM add-on, and I need to be able to track whether the referral was Direct, Indirect, or Spillover.

What do you guys think?

**Comment by pippinsplugins** [comment]
@codelion7 We could certainly consider it but we have to take into account existing pending referrals that could break because of the change.

**Comment by pippinsplugins** [comment]
Let's go ahead and make the change.

**Comment by codelion7** [comment]
This is true. To get around that, we could create a setting that would loop through all of the existing PMP referrals and check to see if their reference is numeric, and if not, we update the reference with the custom value.

**Comment by pippinsplugins** [comment]
Probably best to write an upgrade routine that runs when 1.6 is installed.
We have an API for doing that already.

**Comment by codelion7** [comment]
Yes, I like it. Using an upgrade routine makes much more sense. Alright, I'll start making the change in the PMP integration file. Where can I find an example/documentation on how to use the upgrade API?

**Comment by pippinsplugins** [comment]
Here you go! https://github.com/affiliatewp/AffiliateWP/blob/master/includes/admin/class-upgrades.php

Note: we already have an upgrade routine created for 1.6 so look at `release/1.6` for that. Since it's going to be a large upgrade, we should look at using our stepped routine that we use for imports / migrations: 

https://github.com/affiliatewp/AffiliateWP/blob/master/includes/admin/tools/class-migrate-base.php
https://github.com/affiliatewp/AffiliateWP/blob/master/includes/admin/tools/class-migrate-affiliates-pro.php

**Comment by codelion7** [comment]
Ok, so now PMP integration has an order id based reference, which is consistent with the other integrations. 

With phase 2 of this process, should the 1.6 upgrade routine function call replace the affiliate_wp()->affiliate_meta->create_table() function call and include it as one of the steps? And in which file should the  upgrade routine function be defined?

**Comment by pippinsplugins** [comment]
Yes, the create_table() call has to be part of the upgrade routine. It can run before the stepped routine.

For the stepped routine, I would suggest setting it up to show an admin notice that asks for the user to click a link to opt-into the upgrade.

**Comment by pippinsplugins** [comment]
I'll be more than happy to write the upgrade routine if you are unsure or don't want to :)

**Comment by codelion7** [comment]
I do think it would be best if you handle the upgrade routine, since I'm not too familiar with the process as of yet. I am still interested in learning how to do it though.

**Comment by michaelbeil** [comment]
Closing this unless an issue arises again.
