### ISSUE TITLE
Creative/s template file

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#595]
We should have a template file for the creatives. We should also support adding single creative templates such as `creative-10.php` which will only affect the creative with an ID of 10.

**Comment by sumobi** [comment]
At the same time as we do this I'd like to remove the `title` attribute from a creative's anchor link altogether. There's a lot of evidence to suggest that an anchor's title attribute is ignored and it can actually do more harm than good.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
@sumobi ready for testing.

**Comment by sumobi** [comment]
:+1:

**Comment by sumobi** [comment]
@pippinsplugins creative.php works fine for me in the `affiliatewp` folder. I couldn't get a single creative template working though, eg: `creative-1.php`.

Can we call it `creatives.php` instead of `creative.php`?

**Comment by pippinsplugins** [comment]
I prefer singular since it matches WP core.

For example, it's always `page.php` not `pages.php`.

**Comment by pippinsplugins** [comment]
I have no idea why `creative-1.php` doesn't work . . . .

**Comment by pippinsplugins** [comment]
OK I see. It's detecting / loading `creative.php` before `creative-1.php`. If you delete `creative.php`, `creative-1.php` loads

**Comment by pippinsplugins** [comment]
But I don't really know why . . .

**Comment by sumobi** [comment]
@pippinsplugins good point on the naming, I have no idea on the above either.

**Comment by pippinsplugins** [comment]
We are going to not support `creative-#.php` for now. I can't seem to figure out why that doesn't work.

If someone needs to make creative-specific changes in the template file, they can add an ID check, like this:

```php
if( $affwp_creative_atts['id'] == 23 ) {
    // something
} else {
   // something else
}
```

**Comment by frnkoc** [comment]
How can i arrange the creatives to show from newest to oldest?

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
