### ISSUE TITLE
Add an affiliate with custom status

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#603]
Customer request, thoughts?

Currently we can add a new affiliate, but can't add their status. Possible options would be `pending`, `inactive`, or `active`.

**Comment by pippinsplugins** [comment]
Yeah, I think we should add it.

**Comment by pippinsplugins** [comment]
Ready for testing @sumobi

**Comment by sumobi** [comment]
@pippinsplugins works great :+1: When an affiliate was manually added previously they were always added as "pending" if require approval is enabled. Are we in agreement that since we're allowing custom statuses, we should just ignore the require approval settings when manually adding?

**Comment by pippinsplugins** [comment]
@sumobi yes I think so.

**Comment by sumobi** [comment]
:+1:
