### ISSUE TITLE
Most Valuable Affiliates box sorting incorrectly

### ISSUE THREAD

**Issue by mgibbs189** [affiliatewp/AffiliateWP#605]
Hey guys,

The "Most Valuable Affiliates" box on the overview page seems to be sorting by newest affiliates, instead of by earnings.

**Comment by pippinsplugins** [comment]
You're 100% right. Oops.

**Comment by pippinsplugins** [comment]
Looks like this was broken with https://github.com/affiliatewp/AffiliateWP/commit/e658defc3f2b305e811cc9acc3a1290f6172ccfc

**Comment by mgibbs189** [comment]
Awesome! Thanks for the quick resolution, @pippinsplugins
