### ISSUE TITLE
Storing Custom Referral Data

### ISSUE THREAD

**Issue by codelion7** [affiliatewp/AffiliateWP#607]
As I've previously mentioned, I've developed a way to keep track of a "Referral Type" by storing it in the 'custom' column of the referrals table. As of now, I'm storing the referral type as a simple string, but I'm wondering if it's a better idea to store it as an associative array? 

This would allow us to specify which data we want to retrieve from the custom column, and it allows for additional info to be stored in the 'custom' column.

What do you guys think is the best procedure for this?

**Comment by pippinsplugins** [comment]
Can you give me an example of the types you have so far?

This might be a good case for a dedicated column.

**Comment by codelion7** [comment]
So far, I have "Direct", "Indirect", and I'm thinking of adding a 3rd type for "Spillover", but I'm sure that we could think of some other referral types. I initially thought that a Referral Type column would be the way to go, but it would mean that we would have to update quite a few functions.

**Comment by codelion7** [comment]
Well @pippinsplugins , upon further inspection, it appears that using the "custom" referral column to store the referral type may not be feasable. I'm finishing up the MLM add-on and I'm in the process of making sure that it's compatible with the Recurring Referrals add-on. I noticed that the order id is stored in the "custom" column, which causes a conflict with my existing method of storing the referral type.

Do you think it's better to create a referral meta table, or just add a referral type column to the existing referrals table?

**Comment by pippinsplugins** [comment]
Let's close this in lieu of  #672

**Comment by codelion7** [comment]
Agreed
