### ISSUE TITLE
Disable referrals for certain forms in Gravity Forms

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#609]
When Gravity Forms is set up, every form will generate a referral if an affiliate is being tracked. We should allow the user to disable certain forms from generating referrals

**Comment by pippinsplugins** [comment]
Sounds good to me! Let's try to get it in 1.7

**Comment by sumobi** [comment]
@pippinsplugins the PR above adds a checkbox to enable referrals for the form. 

![screen shot 2015-05-19 at 6 18 26 pm](https://cloud.githubusercontent.com/assets/52581/7696670/7a90d7da-fe53-11e4-878a-e15a42479293.png)

I think it makes more sense to have to enable referrals rather than disable referrals for every Gravity Form that is created. It also keeps the consistency with the other form elements which you have to "enable" to use.

Speaking of which, how do we handle backwards compatibility? Do we create an upgrade routine for v1.7 that grabs all current gravity forms, and enables the new checkbox option? This would prevent existing forms from suddenly not generating referrals.

**Comment by pippinsplugins** [comment]
I'd be inclined to have a `disable` option simply for the backwards compatibility issue, but we could do an upgrade routine as well.

If we're going for consistency, let's write the description as `Enable referral creation for this form` so it matches the fields above it.

**Comment by sumobi** [comment]
If we had a disable option then every time some one created a new form, they'd have to remember to disable referrals. I can't imagine all forms needing to generate referrals.

**Comment by pippinsplugins** [comment]
True. Let's do an upgrade routine.

**Comment by pippinsplugins** [comment]
@fjarrett mind testing this?

**Comment by fjarrett** [comment]
@pippinsplugins Sure thing!

**Comment by pippinsplugins** [comment]
This is now merged into `release/1.7`. Tagging as `needs testing` for one final testing round before closing it.

**Comment by sumobi** [comment]
@pippinsplugins @fjarrett haven't been able to fault it so far

**Comment by pippinsplugins** [comment]
@sumobi Did you test the upgrade routine as well?
