### ISSUE TITLE
Coupon base class

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#611]
As Pippin has suggested we should have a base coupon class that handles all the coupons for various integrations

**Comment by pippinsplugins** [comment]
I'm trying to remember what all we discussed this class handling. @sumobi do you remember?

**Comment by sumobi** [comment]
@pippinsplugins this would be the base class that would handle automatic coupon codes when affiliates registered, ala https://github.com/AffiliateWP/AffiliateWP/issues/426

**Comment by DrewAPicture** [comment]
Closing this in favor of #426 since the object is also being introduced there.
