### ISSUE TITLE
Form label and description consistency

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#613]
Currently the descriptions underneath the input fields labels are the labels and wrap onto two lines. Just like WP core we should have the titles as the labels and put the description onto a second lines using the right classes.

Current:
![screen shot 2015-04-05 at 8 28 46 pm](https://cloud.githubusercontent.com/assets/52581/6999491/9016a97a-dbd2-11e4-878f-9dd509d4f47c.png)

WP core:
![screen shot 2015-04-05 at 8 30 25 pm](https://cloud.githubusercontent.com/assets/52581/6999496/9ff5b05c-dbd2-11e4-88e2-375f8ac55c93.png)

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by sumobi** [comment]
Beautiful :+1:

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
@pippinsplugins @ghost1227 Looks good to me :+1:
