### ISSUE TITLE
Update referral total when customer purchases more products in same WooCommerce session

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#614]
AffiliateWP creates a "pending" referral when the order initially goes to PayPal. However if you go to PayPal but then go back to the site (without clicking cancel order) and purchase more items, the referral is not updated when the customer pays via PayPal. 

This means the affiliate loses out in the referral on the new items purchased. This is because WooCommerce keeps the same session/same order until payment has been made. We should update AffiliateWP to re-calculate the referral amount/description etc when the WooCommerce order is updated.

___
##### The initial order being created in WooCommerce, note the order total of $75
![screen shot 2015-04-06 at 10 16 52 am](https://cloud.githubusercontent.com/assets/52581/7006353/189101a6-dc46-11e4-906a-e6f3eeb2e7bb.png)

___
##### The initial referral being created in AffiliateWP:

![screen shot 2015-04-06 at 10 17 22 am](https://cloud.githubusercontent.com/assets/52581/7006365/2686c0a2-dc46-11e4-8b68-680667eb0022.png)

___
##### When you proceed to PayPal the second time, the order is updated, note the total amount has now updated to $2,175.00

![screen shot 2015-04-06 at 10 18 21 am](https://cloud.githubusercontent.com/assets/52581/7006396/6082e61e-dc46-11e4-9488-d7337663b21a.png)

**Comment by pippinsplugins** [comment]
Milestoning for 1.6.2

**Comment by pippinsplugins** [comment]
Punting to 1.6.3. We need to get 1.6.2 out sooner to fix some issues with MemberPress.
