### ISSUE TITLE
Add default CSS for <pre> tags

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#626]
A lot of theme's might not have proper styling for `pre` tags. Since we switched to using pre tags for the creatives we should add some default CSS just in case.

**Comment by sumobi** [comment]
After deep thought I've decided we should at least make them look semi nice on themes that don't support pre and code tags. By that I mean add a background color and border. Code is pretty much ripped straight from 2015 with some slight tweaks.

![screen shot 2015-05-20 at 5 38 39 pm](https://cloud.githubusercontent.com/assets/52581/7719611/1615317e-ff17-11e4-86cb-a61de6219e3f.png)

**Comment by pippinsplugins** [comment]
:+1:
