### ISSUE TITLE
Campaign tracking for affiliates

### ISSUE THREAD

**Issue by bekarice** [affiliatewp/AffiliateWP#627]
While the "Visits" and "Referrals" tabs are really useful, it can be difficult to see what's actually converting for affiliates. For example, "Referrals" tell you what product was purchased, and "Visits" can tell you the referring URL that converted, but there's not really a way to know which visit led to which purchase, or what referral sources are most valuable.

Campaign tracking could be a great addition for this, as affiliates can then append a campaign to differentiate their links from one another, i.e., `affiliatewp.com/?ref=3&campaign=sidebar`

An overview for campaigns could be added to "Statistics" to provide data for campaigns. It could show you the total commission value, number of commissions, and conversion rate for each campaign -- something like this:

#### Campaigns
|     Campaign     | Visits | Converted | Conversion Rate | Total Value | 
|:--------------------:|:-------:|:--------------:|:----------------------:|:----------------:|
|   no campaign   |  149  |       6         |            4.0%        |     $126.48    |
| post-20150321 |   27   |        4         |          14.8%        |      $33.32    |
|       sidebar       |    231 |        7        |             3.0%        |     $109.31   |
| 10off (COUPON) |   8   |       n/a      |            n/a            |     $143.14   |

## Things to Consider

 - Would probably warrant addition of a "campaign" field to "Affiliate URLs" and append it to the generated URL: https://cldup.com/dpDh3_zKuG.png
 - The campaign could also be added to the "Referrals" table: https://cldup.com/BLLNv3TnQg.png
 - Do you still need "Visits" if campaigns can show you what's converting instead? (Probably, but worth considering.)
 - This may be related to #458 , as affiliate-specific coupons could be tracked along with campaigns. There's a pretty obvious conflict though: what if the affiliate specifies a campaign in the referral link _and_ the affiliate coupon is used? I'd vote that coupon campaigns override other campaigns, just like they do for referral links (affiliate-specific coupon always goes to the linked affiliate, not necessarily the referrer, so it makes sense that you shouldn't track the conversion based on the referrer's campaign when the coupon is used).<br /><br />
However, tracking coupons as a campaign that overrides others has the potential to significantly interfere with manual campaign tracking to see where the referral came from, and perhaps warrants keeping coupon tracking separate. While I'd really love to see coupon tracking added to the affiliate dashboard, I'd also want to ensure it doesn't interfere with my own campaign tracking. Food for thought anyway.
 - How does this work if you use a different referral link structure? i.e., `http://affiliatewp.com/ref/3`

**Comment by pippinsplugins** [comment]
Such a great idea.

Related: #372

**Comment by pippinsplugins** [comment]
I'm going to go ahead and milestone this for 1.7 so we can look at ways to do it.

**Comment by bekarice** [comment]
Bah sorry, totally missed that issue as I looked through for an existing one. Apparently he and I were on the same wavelength this week!

I disagree that "hits / visits" are not as valuable of a metric fwiw -- lets affiliates easily compare pageviews vs visits for that campaign, providing a way to see the funnel for referrals (since not every link will have clicks tracked on the affiliate's site to measure hits + not a bad thing to have both for comparison).

Pageviews for post / page / campaign location --> visits / clicks via that campaign --> actual conversions makes for a helpful overview.

And now I'll be avoiding writing the word `campaign` until it looks normal again :stuck_out_tongue_closed_eyes:  Thanks!

**Comment by smsmyth** [comment]
+1 :)

**Comment by worldtravlr** [comment]
So does this mean this feature will be available in Version 1.7?  Any ideas on a release date?  My affiliates are going to love you for this!!  So excited to have this!  Thanks so much @pippinsplugins and the team.

**Comment by pippinsplugins** [comment]
@worldtravlr Yes I think so. I'm not making a promise but that's my hope. We will begin active development on 1.7 in the next three weeks.

**Comment by pippinsplugins** [comment]
I have the first pass at this working.

If a referral URL contains a campaign, it will now get recorded in the visit and referral DBs. The admin pages have been updated to support filtering / searching fir visits and referrals by a specific campaign.

Things that are done:

- ?campaign=test will get tracked on affiliate URLs
- Referrals page can be filtered by appending `&campaign=test` to the admin URL
` Referrals page can be searched for referrals from a campaign with `campaign:test`
- Visits page can be filtered by appending `&campaign=test` to the admin URL
` Visits page can be searched for visits from a campaign with `campaign:test`

Todo:

1. Add input in Affiliate URL generator to enter a campaign
2. Add a campaign stats table to the `Statistics` tab in the affiliate area
3. Add a way for affiliates to view just their referrals / visits that originated from a specific campaign

@sumobi could you start testing this?

**Comment by worldtravlr** [comment]
Awesome @pippinsplugins.  Excited to check it out.  Could you also possible add a to do of:

Add/update affiliate area short codes to handle this option/table?

Of course not as much of a priority, but would be nice for those of us who use the short codes extensively.

**Comment by pippinsplugins** [comment]
@worldtravlr what kind of updates to the shortcodes are you hoping to see? I've already started on the main updates to them as listed above.

**Comment by worldtravlr** [comment]
Thanks @pippinsplugins.  Good question.  I was referring to - https://affiliatewp.com/addons/affiliate-area-shortcodes/ - just to make sure we are on the same page.  Sorry if this should go on a different thread, etc.

As for those, there are a few things I think would be awesome to have added that I am missing:

* Add a shortcode to only show "Referral URL Stats" thats separate from "Referral URL Visits"
* Add a shortcode for "Order Details" That acts similar to the built in affiliate area tabs in that if the user has order details enabled, it will show the tables and if not, it would either not show anything or have some filler text like "This feature is not enabled for your account", etc.  If this filler text could be easily customize vie child theme and/or in the admin area that would be awesome.
  *Have option for Order Details shortcode to use pagination.  For example [affiliate_area_order_details pages=yes number_per_page=15]

Hope that helps and please let me know if you have any questions.

**Comment by pippinsplugins** [comment]
Yep same page :)

Thanks for the feedback! I'll post more previews here for feedback as I make progress.

**Comment by worldtravlr** [comment]
Awesome thanks @pippinsplugins.  Really appreciate how awesome this plugin is!  

Also just saw this:

pippinsplugins referenced this issue from a commit an hour ago
 @pippinsplugins	Add campaign to export file. #627

Does that mean that affiliates will have the option to easily export their referral information from the affiliate dashboard via  button of some sort?  that would be an amazing option especially if it was by table as it could be really helpful for them to be able to export their "Order Details" and/or Conversion data for their own import and/or analysis.

**Comment by sumobi** [comment]
@pippinsplugins I've run through what you've done so far and it works perfectly, excellent work :+1:  

I had a completely different idea about how to tackle this, as per https://github.com/affiliatewp/AffiliateWP/issues/372 but your way is so much better. I was thinking we could allow the affiliate to use any query string they wanted (myself and @worldtravlr were discussing this) but we wouldn't be able to do any of the things you've made possible in the admin. Can't wait to see more!

**Comment by pippinsplugins** [comment]
@worldtravlr We don't have an option for affiliates to export their own data yet, but that could be easily done. The export option I added is for site admins in Affiliates > Tools > Export.

**Comment by worldtravlr** [comment]
Thanks @pippinsplugins.  I know about that option and am working with @tubiz to create a plugin/code edit to be able to export order details and a bit more on the backend and then maybe later the same for the front end as if "Order Details" are enabled, it would be super convenient for affiliates to be able to download that info to CSV from the affiliate area to be able to send those customer a special buy through my link free thank you gift :-)

**Comment by pippinsplugins** [comment]
Ok this is ready for thorough testing:
![screen shot 2015-09-15 at 2 26 19 pm](https://cloud.githubusercontent.com/assets/1034109/9887535/c855e748-5bb5-11e5-8f43-df36739e324c.png)

I've setup a new MySQL view for the campaigns data that pulls information from the visits table and makes it easily accessible: 

![screen shot 2015-09-15 at 2 27 10 pm](https://cloud.githubusercontent.com/assets/1034109/9887567/ed526ddc-5bb5-11e5-8c5a-13f070a8ff1a.png)

Because of the view, it's possible sites that have huge amounts of visits data will take a while to perform the upgrade to 1.7. We need to test this on large sites to confirm.

**Comment by pippinsplugins** [comment]
When testing, please deactivate and re-activate AffiliateWP

**Comment by worldtravlr** [comment]
This is so Awesome!  Way to go @pippinsplugins  and @sumobi!  Amazing!  Affiliate the world over will love it.  Great job!

**Comment by pippinsplugins** [comment]
:)

I'm not sure on the wording of `Unique Visits`. The column is actually showing the number of distinct URLs that have been clicked (think landing pages). Any suggestions on what to label that column?

**Comment by bekarice** [comment]
> I'm not sure on the wording of Unique Visits. The column is actually showing the number of distinct URLs that have been clicked (think landing pages).

@pippinsplugins So not quite sure what you're measuring -- are unique visits distinct URLs to your site from the affiliate? like:

 - `mysite.com/download/stripe/?ref=1&campaign=landing`
 - `mysite.com/?ref=1&campaign=landing`

So each of those would be tracked as a "unique visit", but both under campaign == landing? Might call them "Sources" in that case, but not sure I'm understanding what they represent.

> Ok this is ready for thorough testing

Happy to :smile_cat: looks like you're missing a file though -- fatal error while installing from https://github.com/affiliatewp/AffiliateWP/tree/issue/627/

```
Warning: require_once(/wp-content/plugins/AffiliateWP/includes/class-campaigns-db.php): failed to open stream: No such file or directory in /wp-content/plugins/AffiliateWP/affiliate-wp.php on line 284
```

**Comment by pippinsplugins** [comment]
@bekarice That's correct. Your example would count as 2 uniques.

**Comment by pippinsplugins** [comment]
@bekarice whoops! missing file fixed.

**Comment by worldtravlr** [comment]
Glad to test on my system as well, but I am using all shortocdes for the Affiliate Area.  Will this work with those yet?

**Comment by pippinsplugins** [comment]
@worldtravlr It depends on the [affiliate_area] short code for now.

**Comment by sumobi** [comment]
@pippinsplugins deactivating/re-activating AffiliateWP doesn't seem to generate the campaigns DB table. Running on multisite installation

**Comment by pippinsplugins** [comment]
How are you verifying the table is there? Note, it's not a real table. It's
a view (virtual table)

**Comment by sumobi** [comment]
By the error:

    WordPress database error Table 'affwp.wp_50_affiliate_wp_campaigns' doesn't exist for query SELECT * FROM wp_50_affiliate_wp_campaigns WHERE affiliate_id = 4; made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/twentysixteen/page.php'), get_template_part, locate_template, load_template, require('/themes/twentysixteen/template-parts/content-page.php'), the_content, apply_filters('the_content'), call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, Affiliate_WP_Shortcodes->affiliate_area, Affiliate_WP_Templates->get_template_part, Affiliate_WP_Templates->locate_template, load_template, require('/plugins/AffiliateWP/templates/dashboard.php'), Affiliate_WP_Templates->get_template_part, Affiliate_WP_Templates->locate_template, load_template, require('/plugins/AffiliateWP/templates/dashboard-tab-stats.php'), affwp_get_affiliate_campaigns, Affiliate_WP_Campaigns_DB->get_campaigns, QM_DB->query

**Comment by sumobi** [comment]
![screen shot 2015-09-16 at 2 11 30 pm](https://cloud.githubusercontent.com/assets/52581/9894853/e01b8f00-5c7c-11e5-8f0a-46e454aebeec.png)

**Comment by pippinsplugins** [comment]
Is your affwp version option set to 1.7 already? If so, lower it and then
run again.

**Comment by sumobi** [comment]
Ahh that'll be why :)

**Comment by sumobi** [comment]
Oh damn, it's already 1.6.5
![screen shot 2015-09-16 at 2 14 03 pm](https://cloud.githubusercontent.com/assets/52581/9894879/33d92864-5c7d-11e5-861b-766d0c8a8c2f.png)

**Comment by pippinsplugins** [comment]
@sumobi Tracked it down. Try again now and it should work.

**Comment by bekarice** [comment]
:+1: looking good on my end, don't have huge data sets to test the upgrade routine though.

What if you use "Unique URLs" or "Unique Links" instead of "Unique Visits" since that's the number of different URLs that have used that campaign?

**Comment by pippinsplugins** [comment]
I like both of those options. @sumobi preference?

**Comment by pippinsplugins** [comment]
Merging into release/1.7

**Comment by sumobi** [comment]
@pippinsplugins I like `Unique Links` but would be happy with either
