### ISSUE TITLE
Highest converting URLs

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#63]
The Overview page should get a new widget that lists the 5 URLs with the highest conversion rate.

**Comment by tubiz** [comment]
PR: #2533 

![issue 63-1](https://user-images.githubusercontent.com/602184/35283554-d6b6a6a2-0058-11e8-88c8-0ce541cb5363.png)

![issue 63-2](https://user-images.githubusercontent.com/602184/35283556-d6e6d94e-0058-11e8-94a9-cb7b118f1b82.png)

**Comment by pippinsplugins** [comment]
@gspice could you give this a test please?

**Comment by gspice** [comment]
@pippinsplugins  Testing feedback:  The new box appears on the Overview page as expected, however, it appears to be using the **Referring URL** column value for the calculations which often is a value of _Direct Traffic_.   Would it be better to do the aggregate calculations on the **Landing Page** column value?  Even with Direct Traffic it would show a specific page might be converting more over another.  Or, should both be considered?  Knowing what pages converted the most and also what referring URLs converted the most (excluding Direct Traffic).

**Comment by pippinsplugins** [comment]
@gspice yes, thank you for noticing that.

@tubiz could you adjust that please?

**Comment by tubiz** [comment]
@gspice thanks for noticing that.

@pippinsplugins I will update the PR with the changes.

**Comment by pippinsplugins** [comment]
@tubiz just needs one small change.

**Comment by tubiz** [comment]
@pippinsplugins I will make the change shortly.
