### ISSUE TITLE
Deleting a referral does not show notice

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#632]
When you delete a referral, the `Referral deleted successfully` notice is not being shown. 

Looks like we need to set up an action for it if deleting from within the admin and add a `wp_safe_redirect` which adds `affwp_notice=referral_deleted`.

**Comment by pippinsplugins** [comment]
Happy with that @sumobi ?

**Comment by sumobi** [comment]
@pippinsplugins I like the confirmation, but I think there should still be the "Referral deleted successfully" message when you delete a referral.
