### ISSUE TITLE
Affiliate application rejection email

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#639]
Looks like we don't have an open issue on this. We should have a rejection email that is sent to an affiliate when their application is rejected.

**Comment by pippinsplugins** [comment]
@sumobi this is ready for testing.

**Comment by sumobi** [comment]
@pippinsplugins I'm not seeing the rejection reason appear in the email that is sent. There's also a rogue `%s` in the email field: 
![screen shot 2015-07-28 at 10 37 05 pm](https://cloud.githubusercontent.com/assets/52581/8929406/50606266-3579-11e5-8a05-fe4ddb1cc28d.png)
