### ISSUE TITLE
Few bugs found around

### ISSUE THREAD

**Issue by metuza** [affiliatewp/AffiliateWP#645]
In the admin overview page, table "Most Valuable Affiliates" the td colspan="3" should be changed to td colspan="4", also the same for the "Referrals" page/tab in affiliates area of frontend, td colspan="3" should be changed to td colspan="4".

In the following locations there is 3 textstrings without a textdomain, points to default.
includes/admin/AFFWP_Plugin_Updater.php:164, 171, 311
includes/admin/class-addon-updater.php:186, 193, 280

And in these locations 2 textstrings uses the EDD textdomain.
includes/integrations/class-edd.php:410
includes/integrations/class-rcp.php:168
includes/integrations/class-woocommerce.php:263
includes/integrations/class-exchange.php:243

Brgds
Rune

**Comment by sumobi** [comment]
Thanks @metuza, we'll look into these issues and get them fixed
