### ISSUE TITLE
"Referral Awarded!" needs more information

### ISSUE THREAD

**Issue by tushonline** [AffiliateWP/AffiliateWP#652]
1) Found that, some referral amount in notification email shows just the currency symbol "$" without the actual amount.

2) Referral Awarded email should also show, (in case of Woocommerce) the actual product URL for which the commission is awarded. Right now it's very vague & generic. Or, am I missing something?

Thanks

**Comment by pippinsplugins** [comment]
1). Did these referrals have real amounts?

2). That's something we will be adding support for in the future.
