### ISSUE TITLE
Can't remove affiliate from Affiliate Discount field

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#653]
Once an affiliate is added to the `Affiliate Discount?`field they are unable to be removed again.

![screen shot 2015-04-20 at 9 55 22 am](https://cloud.githubusercontent.com/assets/52581/7232848/71966bd0-e743-11e4-831c-0e9198e2d850.png)

**Comment by sumobi** [comment]
@pippinsplugins this also affects EDD, possibly otheres

**Comment by sumobi** [comment]
EDD is also affected

**Comment by sumobi** [comment]
iThemes Exchange fixed via https://github.com/affiliatewp/AffiliateWP/commit/8b6c685a2b1166748d603ad6c61b563a88ca8f07

**Comment by sumobi** [comment]
RCP fixed via https://github.com/affiliatewp/AffiliateWP/commit/e7b88d36af99bca519e018f88ebf6c79a2ff148b

@pippinsplugins Feel free to double check, otherwise we can close this one.

**Comment by pippinsplugins** [comment]
All looks good to me.
