### ISSUE TITLE
Remove OptimizeMember user query from our ajax user search

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#657]
OptimizeMember causes unexpected results on our pages that perform user searches, such as the add affiliate screen. 

This line from OM causes many users with the same username to appear:
    add_action("pre_user_query", "c_ws_plugin__optimizemember_users_list::users_list_query");

As discussed, we'll add a new hook to our `includes/admin/ajax-actions.php` file and then remove their action from a compatibility file.

**Comment by pippinsplugins** [comment]
@sumobi Can you test this? `master` branch.

**Comment by sumobi** [comment]
@pippinsplugins works great
