### ISSUE TITLE
Affiliate account is added again with a page refresh after being deleted from admin

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#660]
1. Register as an affiliate and stay on the affiliate dashboard
2. As an admin, delete the affiliate from the admin
3. Back as the affiliate, refresh the page, the account is now added again

**Comment by pippinsplugins** [comment]
I can't replicate this.

**Comment by sumobi** [comment]
@pippinsplugins I can't either now, guess the code gods fixed it. Let's close it and re-open if I spot it again.

**Comment by pippinsplugins** [comment]
:+1:
