### ISSUE TITLE
Improved user searching

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#665]
We should improve our user search that is shown when adding new affiliates, adding discount codes etc.

Currently when searching for a user via the affiliate discount fields, it will show all users, which means you can select the username of a pending affiliate.

Any other suggestions to improve the user search are welcome.

**Comment by ryanduff** [comment]
Run an affiliate query to get affiliate user ids by status of pending then use it as a NOT IN clause in the query for users would probably be the best approach off the top of my head.

**Comment by pippinsplugins** [comment]
@ryanduff I like that approach.
