### ISSUE TITLE
Long links flow outside the table in affiliate area

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#669]
I think this sums it up fairly well

![affiliatewp-1](https://cloud.githubusercontent.com/assets/52581/7324201/a8a1b5c4-ea79-11e4-8434-c657414cfea6.png)

**Comment by sumobi** [comment]
Looks fine on 2015 so probably related to only some themes. I propose we add some CSS to make sure this doesn't happen, probably the same CSS we have to add here: https://github.com/affiliatewp/AffiliateWP/issues/626

![screen shot 2015-04-24 at 12 05 13 pm](https://cloud.githubusercontent.com/assets/52581/7324243/3e57fe0c-ea7a-11e4-8ddf-604954bb819d.png)

**Comment by pippinsplugins** [comment]
Tagged for 1.6.3.
