### ISSUE TITLE
Create referrals when a user registers

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#671]
We should allow referrals to be created when a user signs up via the standard WP user registration form. The only way to do this currently is via the conversion script shortcode but it would be much more reliable hooking into the WP registration process.

This would also allow integration with plugins such as OptimizePress where customers just want to use it for lead tracking.

**Comment by pippinsplugins** [comment]
Excellent idea.

**Comment by sumobi** [comment]
Going to close this one. The Sign Up Referrals add-on would be the ideal candidate for this https://github.com/AffiliateWP/affiliatewp-signup-referrals/issues/12
