### ISSUE TITLE
Add referral type column

### ISSUE THREAD

**Issue by codelion7** [AffiliateWP/AffiliateWP#672]
@sumobi , @pippinsplugins , do you think it's better to create a referral meta table, or just add a referral type column to the existing referrals table?

I'm beginning to notice that the "custom" column in the referrals table is not flexible enough for storing additional data for a particular referral. It won't allow for more than one custom value at a time, unless it's modified to store data in an associative array, which may work also. 

For example:
The PMP integration for  the Recurring Referrals add-on stores the payment transaction id in the "custom" referral column. The MLM add-on also stores the "Referral Type" in the "custom" referral column. So basically, these 2 important data values will overwrite each other when used together.

Any ideas on how I can get around this?

**Comment by pippinsplugins** [comment]
I think we should do a referral type. @sumobi and I discussed this recently and decided there are a lot of great opportunities to register custom referral types.

**Comment by codelion7** [comment]
Sounds good to me. How would we handle referrals that have more than 1 type? 

Like in the example above, the Referral Type would be both a Recurring Referral and an Indirect Referral, if the sale was made by a sub affiliate. I'm thinking that it may be best to store the data as an array in our new "referral_type" column, to allow for multiple values.

**Comment by pippinsplugins** [comment]
I've gone ahead and renamed this to "Add referral type column" and am going to milestoneit for 1.7

**Comment by pippinsplugins** [comment]
Punting to 1.8 due to size of 1.7 already.

**Comment by amdrew** [comment]
Closing in favor of https://github.com/AffiliateWP/AffiliateWP/issues/2198
