### ISSUE TITLE
Allow product commission based on variation

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#673]
Currently AffiliateWP allows you to disable referrals from being generated on certain products. It would be handy to take this even further and only allow some product variation from receiving commission.

**Comment by ramiabraham** [comment]
related: https://secure.helpscout.net/conversation/113299038/14977/

**Comment by sumobi** [comment]
https://secure.helpscout.net/conversation/127680315/18222/

**Comment by wordmaid** [comment]
Another request on this: https://secure.helpscout.net/conversation/211463342/35705/?folderId=205524

**Comment by BurlesonBrad** [comment]
:heavy_plus_sign: :100: 
https://www.facebook.com/groups/woohelp/permalink/1977478349145277/

![aff-wp-variations](https://cloud.githubusercontent.com/assets/6208757/16924886/0cc4adba-4ce7-11e6-95ab-f17572bd02b2.png)

**Comment by michaelbeil** [comment]
This is being done in #1559.

**Comment by pippinsplugins** [comment]
#1559 is for WooCommerce only.

**Comment by pippinsplugins** [comment]
Closing this as a duplicate.
