### ISSUE TITLE
Test mode

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#674]
We should think about adding a checkbox that the admin can enable that allows them to get visual feedback while testing the system. 

If they're logged into the same account as an affiliate we can alert them via a JS popup. If a visit was not made when they used the link we can let them know that the affiliate is pending, or doesn't exist. When they make a successful order we can let them know the referral was, or was not created. This will be much better than a doc article and decrease the number of support tickets we receive.

**Comment by codelion7** [comment]
I love this idea. Very useful.

**Comment by sumobi** [comment]
@pippinsplugins Now that we have the debugging mode I think we can close this, would you agree?

**Comment by pippinsplugins** [comment]
Yes.
