### ISSUE TITLE
Coupon tracking for MemberPress

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#676]
Requested by customer: https://www.memberpress.com/tour/

**Comment by pippinsplugins** [comment]
Shouldn't be hard to do.

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/127136510/18102/

**Comment by pippinsplugins** [comment]
Ready for testing!

**Comment by michaelbeil** [comment]
sweet!
