### ISSUE TITLE
Action Hook Needed for Adding Custom Callbacks in Settings Class

### ISSUE THREAD

**Issue by codelion7** [affiliatewp/AffiliateWP#677]
When adding the Software Licensing system to AffiliateWP MLM, I couldn't find a way to add my own custom callback to the Settings class. My goal was to simply create a slightly modified version of the existing license callback, but without an action hook, I had no way to register the callback function.

I think an action hook would pave the way for more customized input fields to be added to the existing settings structure. What do you guys think?

PS. I did find a way to use the text callback, and modify it to behave like the license callback does, but it could be smoother.

**Comment by pippinsplugins** [comment]
Hmm, you're absolutely right.
