### ISSUE TITLE
inputs and textarea fields missing border when themes remove border on .required class

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#678]
Some themes such as Canvas by WooThemes have a `.required` CSS class. This sets all borders to `0`.

    .required {
        border: 0 none;
        color: #c00;
    }

Because of this, it causes the inputs and textarea on the affiliate registration from to lose their borders.

**Comment by kim07** [comment]
:+1:

**Comment by sumobi** [comment]
@pippinsplugins I can't think of a way to get around this without explicitly setting a border color and width which I don't think we should do (the theme should style it). The closest I got was:

    .affwp-form .required {
        border: 1px solid inherit;
    }

But the inherit doesn't pick up the color so we get this:

![screen shot 2015-06-25 at 11 02 00 am](https://cloud.githubusercontent.com/assets/52581/8343457/a190b920-1b29-11e5-9334-a242ec680a7d.png)

Since it's only 1 theme that we're aware of that does this I wonder if we should just ignore it.

**Comment by sumobi** [comment]
Actually, maybe a black border is better than nothing at all. At least then it's not invisible and the site owner can see what the issue is

**Comment by sumobi** [comment]
The above also means that themes who don't have the required CSS rule will now have a black border. I vote we close.

**Comment by pippinsplugins** [comment]
I prefer a dark gray border. That's what I do in RCP. Seems to work well across the board.

**Comment by pippinsplugins** [comment]
`#333333` or something like that.

**Comment by sumobi** [comment]
So we explicitly set a 1px solid dark grey border rather than relying on the theme's border color? i think we may just get more support tickets asking why the border color changed

**Comment by pippinsplugins** [comment]
Yep.

**Comment by sumobi** [comment]
Ok then, let's do that, how about a nice light -ish grey like 2015 ?

**Comment by pippinsplugins** [comment]
Works for me.
