### ISSUE TITLE
Incorrect referral rate with a tier and per-product rate

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#685]
Tiered Affiliate Rates + EDD (possibly others)

Set up:

- Tier set at 75% commission when X number of paid referrals has been reached
- product set up at 0.5 commission (50%)
- global affiliate rate of 20%

The affiliate is correctly moved up to 75% commission level as shown on the affiliate page, however at purchase, their commission rate was calculated at 50%. As discussed, the affiliate rate (either set on edit affiliate screen or from tiered affiliate rates) should trump a per-product rate.

**Comment by sumobi** [comment]
@pippinsplugins 

I've had a crack at this but came up short. Since tiered affiliate rates simply filters the affiliate's rate there's no way of knowing that "hey, this is a tiered affiliate rate, override the per-product rate". 

The only way I can think of solving this would be to store an affiliate's current tiered rate in a db column rather than filtering it. When the affiliate reaches the next tier, we'd update this rate. This way, we can check:

1. If the affiliate has a custom rate set on the edit affiliate screen. This will use the current affwp_affiliate_has_custom_rate() function and trump all other rates set.

2. If the affiliate has a tiered affiliate rate. In this case it will trump the per-product rate.

3. If there a per-product referral rate set. This will override the global affiliate rate.

4. If there's no other rates set, fallback to global affiliate referral rate.

If we store an affiliate's current tiered rate it would also allow us to reset the rates after X amount of time, as per https://github.com/affiliatewp/tiered-affiliate-rates/issues/6

Any thoughts so far?

**Comment by pippinsplugins** [comment]
Going to look at this tomorrow.

**Comment by sumobi** [comment]
Good luck :+1:

**Comment by pippinsplugins** [comment]
I'm reluctant to store the tiered rates in the affiliate's settings as it will likely cause problems when someone goes in and adjusts the tiered rates (accounts wouldn't reflect them right away).

**Comment by pippinsplugins** [comment]
The problem is this part of `affwp_calc_referral_amount()`:
```php
	$has_custom = affwp_affiliate_has_custom_rate( $affiliate_id );

	if( $has_custom || empty( $rate ) ) {

		// If the affiliate has a custom rate set, use it. If no rate is specified, use the fallback
		$rate = affwp_get_affiliate_rate( $affiliate_id );

	}
```

The `affwp_get_affiliate_rate` filter only fires when there is no custom rate set.

**Comment by pippinsplugins** [comment]
Wait, no, that's not true. It's because the product rate is passed in.

**Comment by pippinsplugins** [comment]
@sumobi I think I've worked this out.

Instead of checking if an affiliate has a custom rate, I've set `affwp_get_affiliate_rate()` up with a 3rd, optional parameter that lets us pass in a custom rate (per-product rates in this case). Doing this allows the `affwp_get_affiliate_rate` filter to still run.

It appears to work properly.

Could you give it a try?

**Comment by sumobi** [comment]
:+1: Absolutely

**Comment by sumobi** [comment]
@pippinsplugins This works brilliantly from what I have tested :+1:

**Comment by pippinsplugins** [comment]
Excellent, merging then.
