### ISSUE TITLE
WP Job Manager integration

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#688]
https://wpjobmanager.com/

It would be fairly neat to provide an integration for WP Job Manager, perhaps with the paid listing add-on: https://wpjobmanager.com/add-ons/wc-paid-listings/. Affiliates could refer companies to post jobs and earn a commission for example.

**Comment by pippinsplugins** [comment]
I could be wrong but I'm pretty sure this already works with the WooCommerce integration.

Paid listings simply sets up Jobs as products that get purchased in WooCommerce. It sends customers through the standard Woo checkout process, so our integration will work.
