### ISSUE TITLE
Fedora integration

### ISSUE THREAD

**Issue by scottwyden** [AffiliateWP/AffiliateWP#689]
usefedora.com has its own affiliate program, but I see beneficts of integrating with AWP.  For example, I sell ebooks and Lightroom presets using EDD, and plan on selling courses using Fedora.  I'd much rather have 1 affiliate program than 2.

**Comment by pippinsplugins** [comment]
Doesn't look like they have an API, so a true integration is unlikely to be possible, but you can use the conversion script short code for it: http://docs.affiliatewp.com/article/77-affiliate-conversion-script
