### ISSUE TITLE
MemberMouse creating $0.00 referral when zero referrals are ignored

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#693]
MemberMouse seems to be creating a $0.00 referral even when "ignore zero referrals" is enabled

https://secure.helpscout.net/conversation/89346520/9059/

@pippinsplugins we discussed this briefly at LoopConf. If you could be so kind to see why it's bypassing the conditional ;)

**Comment by pippinsplugins** [comment]
I think ^ might fix it.
