### ISSUE TITLE
Improve the referral variable field

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#694]
We should prevent the Referral Variable field from being blank (customer removed it completely today), having spaces, or having any query strings in it (customer did this also).

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
I noted a customer today also entered the full URL of their site, including the referral variable and an affiliate ID.

**Comment by sumobi** [comment]
I noticed a customer today on v1.7.6, they had set their referral URL to `?edible-insects` which messed up the pretty URLs. We'll need to take another look at this and strip out `?`.

**Comment by DrewAPicture** [comment]
@sumobi I think this case was covered when we switched to using `sanitize_key()` in 8345c70a for #1014. Can you please test?

"?edible-insects" saved as "edible-insects" on 1.8 trunk, for instance.

**Comment by sumobi** [comment]
@DrewAPicture I can confirm that `?edible-insects` is now saved without the `?` however we also lose the `-`. It's saved as `edibleinsects`. I believe a hyphen should be allowed, would you agree?

**Comment by sumobi** [comment]
Cancel that, all is working fine, we can close this
