### ISSUE TITLE
Add filter to affwp_notify_on_new_referral()

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#697]
We get a lot of requests to use AffiliateWP as a basic lead tracking system which it's great for. 

However if a referral is created at a $0.00, the affiliate will be notified (if turned on) that they received a $0.00 referral. For lead tracking, this is something the site admin doesn't want to do. The site admin can indeed disable $0.00 referrals from being generated, but then you can't use it as a lead tracking tool.

My suggestion would be to add a filter around the $emails->send() function and pass the `$referral` to the filter. This way we can now send the email based on certain conditions, ie disable emails if the amount is `$0.00`. I'm sure there will be other interesting uses also.

    function affwp_custom_notify_on_new_referral( $return, $referral ) {

	    // don't send referral emails on $0.00 referrals
	    if ( 0.00 == $referral->amount ) {
		    $return = false;
	    }
	
	    return $return;
    }
    add_filter( 'affwp_notify_on_new_referral', 'affwp_custom_notify_on_new_referral', 10, 2 );

**Comment by codelion7** [comment]
This is a superb solution. I was just trying to think of a way to get around sending emails for $0 referrals myself. I'm going to be adding a setting to AffiliteWP MLM, that will allow you to choose whether or not to give a referral commission to the Direct Affiliate every time. 

This will allow for "Spillover Referrals", in which affiliate referrals would be generated based on the Matrix Structure you've created in the settings. This sort of "Pass-on-the-sales" feature is quite common among MLM systems.

**Comment by pippinsplugins** [comment]
:+1:
