### ISSUE TITLE
Redirect not working on shortcode

### ISSUE THREAD

**Issue by dexterchua19** [affiliatewp/AffiliateWP#701]
Hi, after loging using the form through the [affiliate_login redirect=""], what ever link i put inside the redirect, it always redirect to homepage, what i'm trying is redirect this to affiliate page. The code from other reports are updated, just fresh install this plugin, then when trying to redirect, its always redirected to home page instead of the value of the redirect. Thanks

**Comment by sumobi** [comment]
Hi @dexterchua19! Please send us a support email from http://affiliatewp.com/support/ - It sounds like you might have another plugin conflicting with the redirect.
