### ISSUE TITLE
Add Event Espresso integration

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#705]
This has been requested at least a couple of times now.

Latest one: https://secure.helpscout.net/conversation/92548655/9634/

**Comment by sumobi** [comment]
:+1:

**Comment by tubiz** [comment]
@sumobi @pippinsplugins have started working on this.

**Comment by pippinsplugins** [comment]
@tubiz Great!

**Comment by sumobi** [comment]
Awesome @tubiz

**Comment by tubiz** [comment]
@pippinsplugins will try and finish this today so that it can be included with version 1.7

**Comment by pippinsplugins** [comment]
@tubiz Great!

**Comment by tubiz** [comment]
@nerrad @tn3rb am currently working on an EventEspresso integration for AffiliateWP.
Will appreciate is you can share some hooks to tie into the purchase and refund process.

**Comment by nerrad** [comment]
hey @tubiz sounds great!  Would you be able to ask your question in the Event Espresso issues please?  I realize you will likely want to track the integration in this thread however it will benefit our users more if we answer in our repository.

It's a holiday weekend here in Canada (both @tn3rb and I are canucks) so you likely won't get a response until Tuesday.  In the meantime, all Event Espresso filter hooks are prefixed with `FHEE_` and all action hooks are prefixed with `AHEE_`, that may help you search for useful hook until we're able to respond.

**Comment by tubiz** [comment]
Hi @nerrad have submitted a new issue on Event Espresso github repo.
Thanks for the guide on how to locate all hooks in EventEpresso.
Enjoy your holiday.

**Comment by sumobi** [comment]
+1
https://secure.helpscout.net/conversation/125761060/17720/

**Comment by pippinsplugins** [comment]
@tubiz Anything I can help out with here?

**Comment by tubiz** [comment]
@pippinsplugins have started on it,  no issues so far. Will be done this weekend.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by tubiz** [comment]
@pippinsplugins still working on the Event Espresso integration. Will have it finished soon.

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/136436290/20581/

**Comment by wordmaid** [comment]
Another request for this integration - any updates?

Ref: https://secure.helpscout.net/conversation/138923527/21242/

**Comment by tubiz** [comment]
Hi @wordmaid @michaelbeil @pippinsplugins sorry for the delay in getting this finished. Will make sure it is finished next week.

**Comment by sumobi** [comment]
https://secure.helpscout.net/conversation/144145767/22469/?folderId=205524

**Comment by peterwk** [comment]
Was the plugin ever finished?

**Comment by michaelbeil** [comment]
@peterwk: If you are referring to the integration of Event Espresso into AffiliateWP, then no, not yet.

**Comment by nerrad** [comment]
Hey there.  We are jumping on with using AffiliateWP to power our invite only affiliate system on eventespresso.com and once I got into the code I realized how easy it would be to build an integration between our core product (Event Espresso 4) and your add-on so I knocked that off this morning.  I was kinda surprised because I thought it would be a more difficult thing considering the length of time this thread has been active (but at the same time completely understand how other projects can interfere with development).  

We're going to be offering it to our members as an add-on but if you'd like to get access/co-ordinate release someone can reach out to garth{at}eventespresso.com.

**Comment by pippinsplugins** [comment]
@nerrad I'd love to discuss including the integration directly in our plugin. We've found that to be the most reliable method for us since it allows us to make changes across all integrations at one time if ever necessary.

**Comment by nerrad** [comment]
oh?  I thought your integrations were separate add-ons?  All I've done is build an add-on for EE that integrates with AffiliateWP.

**Comment by pippinsplugins** [comment]
They are all included directly in the main plugin, not separate plugins.

**Comment by nerrad** [comment]
I think we'd prefer to keep it as a separate add-on and here's why.  The initial iteration is a very simple integration that basically works for any onsite or offsite payment gateways we use that will complete the transaction before awp's affiliate id cookie expires.  In future iterations (if there is demand) we'd need to track the affiliate id on the transaction as meta somewhere so we can apply the correct conversion tracking when a transaction is completed when the cookie is not available or when event admin's complete registrations/transactions via the admin logged in as a separate user.

So long and short of it, its likely easier for both of us if we keep it as a separate add-on and take on the burden of maintaining it as the more complicated side of the integration is the EE side (you guys have done a really good job of making it easy to hook in to track conversions though!).

So we'd definitely be interested in maybe getting listed on the third-party-addons section you have on your site.  But just thought I'd chime in here to see where things are at and how we can maybe coordinate with you.  Again I'm just the code monkey that put this together, any business related convo should probably go to garth{at}eventespresso.com.

**Comment by pippinsplugins** [comment]
We can list it as a 3rd party add-on if you wish to do it that way though keep in mind that that will mean any and all support required by customers for the integration will have to be handled by your team. If we build it into the core plugin, we handle the support.

**Comment by garthkoyle** [comment]
The Event Espresso and AffiliateWP integration is now available: https://eventespresso.com/product/eea-affiliatewp/

**Comment by pippinsplugins** [comment]
@garthkoyle awesome!

@sumobi could you get it listed please?

**Comment by sumobi** [comment]
@pippinsplugins Sure can

**Comment by michaelbeil** [comment]
Closing this out the now that the Event Espresso team has built out the integration add-on.

Cheers :coffee:.

**Comment by sethshoultes** [comment]
Hey Pippin,

Thanks for working with us on this. Would it be possible to get the integration listed on your website (https://affiliatewp.com/integrations/ and https://affiliatewp.com/add-ons/3rd-party/)?

Please let us know if you need anything.

Thanks!

**Comment by sumobi** [comment]
Hey @sethshoultes!

I've added it to the 3rd party add-ons page: https://affiliatewp.com/add-ons/3rd-party/

The `/integrations/` page is only for official integrations included inside the core AffiliateWP plugin as only as these can be set up with 1 click.

**Comment by sethshoultes** [comment]
Thanks!

Seth Shoultes
