### ISSUE TITLE
Add affiliate's username to Edit Affiliate screen

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#711]
It would be nice to be able to see the affiliate's username on the `Edit Affiliate` screen, in the same fashion as the User ID:

![screen shot 2015-05-28 at 12 27 37 pm](https://cloud.githubusercontent.com/assets/52581/7850335/f2afa4f2-0534-11e5-826d-7abb067fe176.png)

**Comment by pippinsplugins** [comment]
:+1:
