### ISSUE TITLE
WooCommerce shop disappears when front page set to shop and referral link used

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#716]
WooCommerce
AffiliateWP 1.6.2

If you set the WordPress front page to show WooCommerce's Shop it looks like this:

![screen shot 2015-06-06 at 1 47 42 pm](https://cloud.githubusercontent.com/assets/52581/8017738/a29f3926-0c52-11e5-9590-70c03e81c0cb.png)

![screen shot 2015-06-06 at 1 49 57 pm](https://cloud.githubusercontent.com/assets/52581/8017752/f4405b16-0c52-11e5-813c-f8d2f7694375.png)

If you use a referral link on the homepage the shop disappears:

![screen shot 2015-06-06 at 1 48 26 pm](https://cloud.githubusercontent.com/assets/52581/8017742/ba57d91a-0c52-11e5-8bec-3c68e0291c35.png)

If you comment out this line everything works fine:
https://github.com/affiliatewp/AffiliateWP/blob/master/includes/class-tracking.php#L170

**Comment by pippinsplugins** [comment]
That explains the influx of tickets

**Comment by pippinsplugins** [comment]
@sumobi could you test this now in `master`?
