### ISSUE TITLE
Notice when no integrations are enabled

### ISSUE THREAD

**Issue by TimothyBJacobs** [affiliatewp/AffiliateWP#722]
Slightly embarrassing; we recently had a site where, for some reason, our Exchange integration was disabled. This went unnoticed for a few days until our client noticed referrals weren't being processed.

It'd be great, if a notice would be displayed when there are no integrations enabled. This could be dismissible too, if a user is doing custom integrations. I'd be happy to submit a PR if you think this is something that could go in.

**Comment by pippinsplugins** [comment]
I don't think I'm opposed to it so long as it is dismissable.

**Comment by TimothyBJacobs** [comment]
Awesome, I'll work up a PR.

**Comment by pippinsplugins** [comment]
Ready for testing!
