### ISSUE TITLE
Are the settings sanitized?

### ISSUE THREAD

**Issue by grappler** [affiliatewp/AffiliateWP#724]
I was looking at the `class-settings.php` and found the filter [`affwp_settings_sanitize_' . $type`](https://github.com/affiliatewp/AffiliateWP/blob/master/includes/admin/settings/class-settings.php#L149) but I could not find any place where the filter was being hooked into to sanitize the values.

Am I missing something here?

**Comment by grappler** [comment]
I was looking to hooking into the filter and it does not seem to work. The filter `affwp_settings_sanitize` works fine.

**Comment by pippinsplugins** [comment]
Resolved in #726

**Comment by pippinsplugins** [comment]
Whoops, meant the filter now fires.

**Comment by pippinsplugins** [comment]
In 1.7, the following is supported:

1. A sanitization callback can be provided when registering settings with the `sanitize_callback` option. Example:
```php
'license_key' => array(
	'name' => __( 'License Key', 'affiliate-wp' ),
	'desc' => '<p class="description">' . sprintf( __( 'Please enter your license key. An active license key is needed for automatic plugin updates and <a href="%s" target="_blank">support</a>.', 'affiliate-wp' ), 'http://affiliatewp.com/support/' ) . '</p>',
	'type' => 'license',
	'sanitize_callback' => 'sanitize_text_field'
),
```
If a callback is provided, it gets added via `add_filter( 'affwp_settings_sanitize_' . $type, $sanitize_callback, 10, 2 );`

2. Default field types (checkbox, text, etc) get sanitized via appropriate callbacks. These are added with `add_filter()` too so they can be removed if necessary.

**Comment by sumobi** [comment]
Looks good to me!

**Comment by pippinsplugins** [comment]
This is preventing the referral rate type from being saved properly. It reverts to percentage.
