### ISSUE TITLE
Add action hook when affiliate is deleted

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#728]
We should add an action hook that fires when an affiliate is deleted. This would be handy for deleting affiliate specific data. In the product rates add-on for example I store data against the user meta. When an affiliate is deleted I'd like to also remove the associated user meta.

Hook here?
https://github.com/affiliatewp/AffiliateWP/blob/master/includes/affiliate-functions.php#L418

Or perhaps a `affwp_post_delete_' . $type` hook here (we'd need to start passing in the type)?
https://github.com/affiliatewp/AffiliateWP/blob/master/includes/class-db.php#L142

**Comment by pippinsplugins** [comment]
:+1:

Let's add it to `affwp_delete_affiliate()`

**Comment by codelion7** [comment]
That's a good catch @sumobi, I definitely agree with @pippinsplugins. This should be added to 'affwp_delete_affiliate()' in efforts to pass in the '$delete_data'.
