### ISSUE TITLE
Conflict with iThemes Sync updates

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#730]
There is a conflict with Sync from iThemes that causes a fatal error during the update process.

My guess is that Sync does not work through the admin so `is_admin()` is not true.

**Comment by sumobi** [comment]
:+1:

**Comment by blogjunkie** [comment]
Hi, was this merged into the plugin? v1.6.5 has lost this patch - https://github.com/affiliatewp/AffiliateWP/commit/087ffef23d76adba3896c1d563487cae276d60fa

**Comment by pippinsplugins** [comment]
@blogjunkie it's being included in v1.7.
