### ISSUE TITLE
Add margin bottom to .affwp-form CSS selector

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#734]
On a number of customer sites the login form is right up against the bottom of the registration form button. 

It looks something like this (simulation):

![screen shot 2015-06-25 at 10 28 17 am](https://cloud.githubusercontent.com/assets/52581/8342979/f0574880-1b24-11e5-81b4-b503d724648c.png)

This is generally caused by the theme removing bottom margin on last `p` element using something like `p:last-child { margin-bottom: 0}`. 

2015 looks fine because the button is containing inside a P tag:

![screen shot 2015-06-25 at 10 26 05 am](https://cloud.githubusercontent.com/assets/52581/8342945/a136c2f8-1b24-11e5-9e98-5ef879fec2a4.png)

I think we should add bottom margin to the forms:

    .affwp-form {
	    margin-bottom: 20px;
    }

This will also make sure that if there's anything else placed under the login form, the form on the settings or urls tab then it won't also run up against the form.

**Comment by sumobi** [comment]
20px seems adequate to me

**Comment by pippinsplugins** [comment]
:+1:
