### ISSUE TITLE
Incorrect value in URL generator when using affiliate area shortcodes add-on

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#745]
It was something we never planned for but apparently over 100 people like to split the affiliate area up using the shortcodes from https://wordpress.org/plugins/affiliatewp-affiliate-area-shortcodes/

The only issue that has been reported so far is that when the shortcode to display the "Profile Settings" is placed above the shortcode to output the "Referral URL Generator", the "Generate URL" button grabs the wrong value of the hidden field with an ID of `affwp-affiliate-id`. This is because we have 2 hidden fields with the same ID and it's grabbing the one from the profile settings.

line that grabs the wrong value:
https://github.com/affiliatewp/AffiliateWP/blob/master/assets/js/frontend.js#L7

We could make a small change to fix this:

`affId = $( this ).find( '#affwp-affiliate-id' ).val(),`

Or maybe we should simply rename the IDs on the inputs so they are never the same (HTML spec would agree here).

**Comment by fjarrett** [comment]
I think prefixing IDs here will just result in making them long and obnoxious:

```html
id="affwp-affiliate-dashboard-url-generator-affiliate-id"
```

Would probably be better to just use classes for targeting defining the scope by the proper container. This would solve the problem and follow HTML spec but without requiring an über verbose ID naming convention.

**Comment by pippinsplugins** [comment]
Scoping :+1:

**Comment by pippinsplugins** [comment]
Just need to remin files then we're good to close this.
