### ISSUE TITLE
Add Action Hook to Uninstall.php

### ISSUE THREAD

**Issue by codelion7** [AffiliateWP/AffiliateWP#746]
A customer just made me aware of the fact that the Remove "Data on Uninstall" setting only deletes the core AffiliateWP tables in the database. In my opinion, this is one of the most important features of AffiliateWP, and I think that it would be great to add an action hook to affiliatewp/uninstall.php, in efforts to allow any tables created by add-ons to be deleted as well. @pippinsplugins, does this sound feasible?

**Comment by pippinsplugins** [comment]
I disagree.

Uninstalling AffiliateWP should not uninstall add-ons. What if the add-on got left activated for some reason?

Each plugin should have it's own uninstall routine. At least that's my initial view. 100% up for bing convinced otherwise :)

**Comment by codelion7** [comment]
You're right about localizing the uninstall routine to each respective plugin. However, this also creates additional work for the user. If I want to clear the data for AffiliateWP and everything related to it, I would then have to uninstall each add-on before finally uninstalling AffiliateWP. I think that most people, like my customer, will assume that when you enable the "Remove Data on Uninstall" setting, it will wipe ALL data associated with AffiliateWP.

**Comment by pippinsplugins** [comment]
Oh I 100% agree on that.

I'm not opposed to adding a hook, but I do still think add-ons should have their own uninstall routines.

**Comment by codelion7** [comment]
Maybe the best thing to do is to implement an uninstall routine for each add-on (with settings to match), and also allow the AffiliateWP uninstall routine to delete ALL AffiliateWP data as well. This way, if you simply want to uninstall and clear the data for a particular add-on, while keeping your other AffiliateWP data intact, you can set the setting for that add-on alone. And if you want to clear all AffiliateWP data including the add-ons, you simply enable the "Remove Data on Uninstall" setting.

**Comment by pippinsplugins** [comment]
For us to remove all data, the add-ons would have to be hooked into our action hook.

That could definitely work, but I'd rather not have two options. If you're removing data, it's highly unlikely you'll want to keep some of it.
