### ISSUE TITLE
Template files can't be placed in child themes

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#758]
According to [this ticket](https://secure.helpscout.net/conversation/102177925/12104/), template files must be placed in the parent theme and cannot be placed in the child theme.

**Comment by fjarrett** [comment]
@pippinsplugins I can't access that Help Scout ticket.

**Comment by pippinsplugins** [comment]
@fjarrett  https://cloudup.com/c5JU2ODJfPh

**Comment by fjarrett** [comment]
@pippinsplugins Thanks!

**Comment by fjarrett** [comment]
@pippinsplugins I am unable to reproduce this issue.

Created a dummy child theme called `twentytwelve-child` and the template override path was:

```
wp-content/themes/twentytwelve-child/affiliatewp/emails/footer-default.php
```

The email template override from a child theme works fine for me. Works from a parent theme too.

![screen_shot_2015-07-13_at_4_26_10_pm](https://cloud.githubusercontent.com/assets/522158/8661257/07f6265e-297c-11e5-8fe6-c3f3fd2fe086.png)

**Comment by pippinsplugins** [comment]
Great! Chalking it up to user error then :)
