### ISSUE TITLE
Update checks

### ISSUE THREAD

**Issue by GaryJones** [AffiliateWP/AffiliateWP#760]
On Plugins, and Network Plugins admin pages, AffiliateWP (and EDD) seems to be doing something funky with setting transients that causes other plugins to do updates.

Here's Query Monitor, showing that plugins from Yoast (cc @jdevalk) are getting an update check, triggered by AffiliateWP:
![screenshot 2015-07-10 11 52 58](https://cloud.githubusercontent.com/assets/88371/8617307/6b4478c0-26fa-11e5-9219-47137f8da6df.png)

Here's another showing that AWP, and also EDD (cc @pippinsplugins) are triggering updates for the http://www.wproute.com/downloads/eu-vat-support-for-edd/ plugin
![screenshot 2015-07-10 09 11 57](https://cloud.githubusercontent.com/assets/88371/8617330/9d88c890-26fa-11e5-8416-83d862b00a9a.png)

Occasionally, I get update checks galore:
![screenshot 2015-07-10 09 10 58](https://cloud.githubusercontent.com/assets/88371/8617378/1bf94a6a-26fb-11e5-8f37-583bb103ec81.png)

I asked the EDD-Vat author, Bill Seddon, about the calls to wproute, and this was his reply:

> When I review the monitor output you provided I see there are updates requests to my site made by EDD and Affiliate Pro. These should not cause my updater to check for updates so why do they appear in your list?
 
> I believe the answer can be found in both these plugins.  I’ll use AffiliateWP Pro as the example.  The updater for this plugin is here: includes/admin/AFFWP_Plugin_Updater.php  As the plugins page is rendered, this Affiliate WP updater function is called: ‘show_update_notification’.  Bizarrely it is called in response the edd-mailChimp plugin being listed (see do_action(‘after_plugin_row_edd-mailchimp/edd-mailchimp.php’) in the output you provided).  I’m going to guess that I don’t experience your problem because I don’t use Affiliate Pro or edd-mailchimp.
 
> You may know that in order to return update information to WordPress, plugins must implement a filter 'pre_site_transient_update_plugins' to return to WordPress information about the plugin.  My plugin updater does this and so do the updaters for EDD and Affiliate WP.  The WordPress 'pre_site_transient_update_plugins' filter is invoked whenever the WordPress function set_site_transient() is called with the update plugins cache as a parameter.  The set_site_transient() function is called by the Affiliate WP function ‘show_update_notification’.  The Affiliate WP function removes its own 'pre_site_transient_update_plugins'  filter before calling set_site_transient() *with the update plugins cache* as a parameter because it does not want its own filter implementation to run.  Unfortunately, then *all other* filter implementations will be invoked including mine.  The consequence is that 'pre_site_transient_update_plugins' are called multiple times as the plugins list page is generated.
 
> I don’t believe it is appropriate for a plugin to call set_site_transient to update the plugins cache while the plugins list is being generated – this is a task for WordPress.  I can understand the motivation because in a multi-site WordPress installation, working out when to retrieve plugin update information is tough.  However I do believe it is why my site is accessed so frequently.

To be honest, I'm not au fait with the update mechanisms inside AWP / EDD to fully understand the problem, so in this case, I'm just a frustrated end-user.

I've put a copy of his mu-plugins updater file at https://gist.github.com/GaryJones/a616ff5319cf1b549284. If improvements could be taken from it and incorporated into the AWP / EDD update libraries to address certain cases described in the notes in that file, and if fixes can be made so that HTTP requests are not triggered for other plugins which hook into the triggered filter, then it would make my plugins page not timeout with a 504 response on every other view.

Thank you.

**Comment by jdevalk** [comment]
The worst part is that EDD Software Licensing does a database query to validate the license for each of these requests... I've just (literally 30 minutes ago) submitted a pull to fix that.

**Comment by pippinsplugins** [comment]
@jdevalk Thank you for the "polite" comment. We have the other issue open to improve that and I'll look at your PR shortly.

@GaryJones I think I know why this is happening and will dig into it now.

**Comment by pippinsplugins** [comment]
`show_update_notification()` checks the plugin name and only continues if it is the same file as passed to the class instance:
```php
	/**
	 * show update nofication row -- needed for multisite subsites, because WP won't tell you otherwise!
	 *
	 * @param string  $file
	 * @param array   $plugin
	 */
	public function show_update_notification( $file, $plugin ) {

		if ( ! current_user_can( 'update_plugins' ) ) {
			return;
		}

		if ( ! is_multisite() ) {
			return;
		}

		if ( $this->name != $file ) {
			return;
		}
```

I don't see how that would be failing unless perhaps `$this->name` is different than `$file`. I'll double check.

**Comment by pippinsplugins** [comment]
Note, `pre_site_transient_update_plugins` is called during `show_update_notification` because that's the only way we can make updates show across the board on a multisite install.

**Comment by pippinsplugins** [comment]
@GaryJones Are you on the latest AffiliateWP version?

**Comment by GaryJones** [comment]
AffiliateWP 1.6.4
EDD 2.4.1
WP 4.2.2, multisite, but only a single (blog 1) site on it.

**Comment by jdevalk** [comment]
@pippinsplugins didn't intend to troll or be mean, just highlight what makes the issue even harder on our end.

**Comment by pippinsplugins** [comment]
I believe this is all resolved now.

@GaryJones do you see this problem or has it gone away?

**Comment by GaryJones** [comment]
For various reasons, I'm not using EDD on any site right now, so I'm unable to test. If you feel it's resolved, then close the ticket, and if I ever get around to repeating my previous setup, I'll comment here if necessary.

**Comment by pippinsplugins** [comment]
NO worries, I'm pretty certain it's resolved due to some recent changes to the Software Licensing extension. If you do ever encounter it again, let us know.
