### ISSUE TITLE
UserPro integration

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#764]
A customer has registered their interest in an integration with UserPro:
http://codecanyon.net/item/userpro-user-profiles-with-social-login/5958681

HelpScout ticket: https://secure.helpscout.net/conversation/104112796/12672/

Integration would involve registering affiliates via UserPro and also awarding commission via the UserPro Payments add-on: http://codecanyon.net/item/payment-addon-for-userpro/9653341

If anyone else is interested in this I'd love to hear about it.

**Comment by pippinsplugins** [comment]
It's a pretty popular plugin. :+1:

**Comment by DKENT213** [comment]
Pippin, please make AffiliateWP compatible with UserPro! I want to use your plugin as I know it's the best available but I just can't without this issue being solved. Help!

**Comment by pippinsplugins** [comment]
@DKENT213 It's on the todo list :)

There were many reasons for removing plugins from Envato though here is not the place to have that conversation. If you'd like to email me, I'd be more than happy to share :)

**Comment by designlab9898** [comment]
The integration allows to add a flat rate of referral Commission. What if I'm using AffiliateWP MLM Ranks add-on that upgrades this Referral Rate if Affiliate promoted to higher rank? 
And does this UserPro integration also pays out  Indirect Referrals Rewards?

**Comment by sumobi** [comment]
@designlab9898 Is your question about the sign up referrals pro add-on and how it integrates with the 3rd party add-ons you mentioned? If so, please open a support ticket with the developer of the MLM and Ranks add-ons. This repository is only for discussion related to the development of the core AffiliateWP plugin, thanks.

**Comment by sumobi** [comment]
Integration with UserPro is provided by the Signup Referrals add-on
