### ISSUE TITLE
A referral rate of 0 cannot be set unless you enter 0.00

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#765]
Related: https://github.com/affiliatewp/AffiliateWP/issues/723

We've seen some customers who have wanted to disable the global commission rate entirely. They go ahead and enter `0` into the input field but the commission rate on the Affiliates -> Affiliates admin page still shows 20%. 

![screen shot 2015-07-14 at 12 54 12 pm](https://cloud.githubusercontent.com/assets/52581/8664178/8ecedeea-2a27-11e5-866b-1add4f933c65.png)

![screen shot 2015-07-14 at 12 54 25 pm](https://cloud.githubusercontent.com/assets/52581/8664177/8eca44de-2a27-11e5-9939-efbaf2821fe6.png)

Entering `0.00` instead of `0` fixes this and the commission rate is correctly shown as `0%` on the affiliates screen. 

![screen shot 2015-07-14 at 12 54 37 pm](https://cloud.githubusercontent.com/assets/52581/8664182/a0ab9950-2a27-11e5-8b18-7a71e1a5ec74.png)

![screen shot 2015-07-14 at 12 54 48 pm](https://cloud.githubusercontent.com/assets/52581/8664181/a0ab84e2-2a27-11e5-9244-e59e6b508dab.png)

The commission rate input field however shows as `0` when saved, even after entering `0.00`.

We should allow `0` or `0.00` to be entered and have the commission rate set to 0%.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
This is fixed in my testing

**Comment by pippinsplugins** [comment]
This works perfectly for me too. As soon as #723 is tested once more, we'll merge #826 into `release/1.7` and close both issues.

**Comment by pippinsplugins** [comment]
@sumobi Happy with this one too? It's been merged into `release/1.7`

**Comment by sumobi** [comment]
@pippinsplugins Yep!
