### ISSUE TITLE
Product has commission disabled but description is not showing for 0.00 referral

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#766]
If you disable referrals on a $10 download with EDD:

![screen shot 2015-07-14 at 3 28 29 pm](https://cloud.githubusercontent.com/assets/52581/8665840/02c45b76-2a3d-11e5-8c85-aa588876f72b.png)

The referral looks like this. Note the blank description:

![screen shot 2015-07-14 at 3 29 08 pm](https://cloud.githubusercontent.com/assets/52581/8665847/19a0f930-2a3d-11e5-823e-8d955e10b46b.png)

The affiliate sees this referral in their affiliate area which also has a blank description:

![screen shot 2015-07-14 at 3 29 42 pm](https://cloud.githubusercontent.com/assets/52581/8665851/3591f892-2a3d-11e5-9e29-57a506cb9c86.png)

Cool, we briefly discussed this here: https://github.com/affiliatewp/AffiliateWP/issues/321#issuecomment-58954424. Looking at it now, it once again doesn't make sense to me. If we're going to disable a download's commission by checking a box and show a $0.00 referral, why would we hide the description?

There is of course the `Ignore Zero Referrals?` option under settings -> misc for when we really want to block the referral entirely.

![screen shot 2015-07-14 at 3 41 22 pm](https://cloud.githubusercontent.com/assets/52581/8665992/cd6a47c2-2a3e-11e5-808c-c31ffa9b8b5f.png)

But if we aren't blocking the referral using the above option and showing a $0.00 referral, we really should be showing the description also.

**Comment by fjarrett** [comment]
@sumobi Sounds like this issue is closely related to #767. In fact, this issue may supersede it.

**Comment by pippinsplugins** [comment]
I think @fjarrett is right. Let's revisit this once #767 is merged in.

**Comment by pippinsplugins** [comment]
@fjarrett Just confirmed that this still happens with the fix for #767.

**Comment by pippinsplugins** [comment]
Proposal for how to do it in #778 (works)
