### ISSUE TITLE
Stray comma in referral description

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#767]
If you purchase 2 downloads, and 1 download has commission disabled, you end up with a stray comma at the end.

![screen shot 2015-07-14 at 4 51 27 pm](https://cloud.githubusercontent.com/assets/52581/8666662/998e94c6-2a48-11e5-97b8-6958a4b420f1.png)

The second referral is where `Download Two` was just purchased by itself.

**Comment by pippinsplugins** [comment]
@sumobi This is ready for testing.

**Comment by sumobi** [comment]
@fjarrett @pippinsplugins still seems to be adding a comma for me

**Comment by pippinsplugins** [comment]
@sumobi Hmm, I don't see any way that it could. Not to ask the obvious but are you sure you were on the right branch?

**Comment by sumobi** [comment]
@pippinsplugins I was on the right branch as I could see the new integration code but who knows :) I'll test again

**Comment by pippinsplugins** [comment]
@sumobi if it still doesn't work, I'll dig in more.

@fjarrett I can't see any reason it wouldn't work as it.

**Comment by pippinsplugins** [comment]
@sumobi @fjarrett it works for me: https://cloudup.com/cFmRe18XPQm
