### ISSUE TITLE
Fatal error when Gravity Forms plugin is deactivated

### ISSUE THREAD

**Issue by fjarrett** [affiliatewp/AffiliateWP#771]
Can we safely assume that users may accept referrals via Gravity Forms, and then later decide not to use the plugin anymore, or maybe not for a limited period of time?

Currently a fatal error will be thrown on the Referrals screen if:

1. Gravity Forms integration is enabled
2. Referrals exist that have a `gravityforms` context
3. Gravity Forms is deactivated

It's not a blocker because you can safely rid the error by unchecking the integration.

@sumobi Thoughts?

![screen shot 2015-07-14 at 1 19 58 pm](https://cloud.githubusercontent.com/assets/522158/8681137/59ad3618-2a2b-11e5-8f26-2d332d7915e6.png)

**Comment by pippinsplugins** [comment]
Yes, definitely need to assume that users may stop using Gravity Forms.

Let's add a function or class exists check.

**Comment by sumobi** [comment]
:+1:
