### ISSUE TITLE
Delete bulk action not working from dropdown below list table

### ISSUE THREAD

**Issue by fjarrett** [affiliatewp/AffiliateWP#777]
If you try to delete one or more affiliates using the Bulk Actions dropdown menu below the List Table, the page just refreshes and nothing happens. The Bulk Actions dropdown _above_ the List table works fine.

![screen shot 2015-07-16 at 7 45 38 am](https://cloud.githubusercontent.com/assets/522158/8722884/b34dbd8c-2b8e-11e5-98a7-02e6636c0cf1.png)

I tried the same approach on Referrals and it worked for me. So this issue seems to be isolated to the Affiliates screen only.

**Comment by pippinsplugins** [comment]
I suspect this is due to input field names. I believe the bottom field is supposed to be named `action_2` or something like that.

**Comment by fjarrett** [comment]
@pippinsplugins Yep that sounds right to me. I haven't dug into it yet.

**Comment by sumobi** [comment]
@fjarrett @pippinsplugins tested, no issues that I can see :+1:
