### ISSUE TITLE
Incorrect total items found calculations when filtering visits

### ISSUE THREAD

**Issue by fjarrett** [affiliatewp/AffiliateWP#783]
As I was working on #578 I discovered a problem with total items found calculations.

![screen_shot_2015-07-20_at_5_45_21_pm](https://cloud.githubusercontent.com/assets/522158/8789341/36d228de-2f07-11e5-9517-27f3df734326.png)

And upon looking into it further I found that the `count()` methods provided for Affiliates, Referrals, Creatives, and Visits are all actually duplicating query logic from their respective `get_*()` methods.

An easy way to consolidate the logic would be to add support for a second argument to every `get_*()` method.

#### Example

Take visits, for example. Setting a `$count` param to `true` would simply return the total number of results found, rather than the results themselves. This would be `false` by default.

```php
public function get_visits( $args = array(), $count = false ) {
```

So the entire `count()` method could just become:

```php
public function count( $args = array() ) {
	return $this->get_visits( $args, true );
}
```

This approach maintains all backwards compatibility for instances of:

```php
$count = affiliate_wp()->visits->count( array( 'some' => 'arg' ) );
```

**Comment by pippinsplugins** [comment]
This is soooooo much better :)

Let's put it in 1.7.

**Comment by pippinsplugins** [comment]
Working perfectly for me.

@sumobi just need a thumbs up from you

**Comment by sumobi** [comment]
How about 3 :+1:  :+1:  :+1:
