### ISSUE TITLE
Affiliate emails being sent to the affiliate's payment email address

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#791]
@pippinsplugins @fjarrett 

Emails such as the application pending and application accepted are being sent to the affiliate's payment email address. They should be sending to the affiliate's WP email address.

To replicate, simply sign up as an affiliate and enter both an email address and payment email address and you'll receive the emails at the payment email address. 

If you dump out an affiliate's email address onto the page you'll see it's grabbing the payment email:
https://github.com/affiliatewp/AffiliateWP/blob/master/includes/affiliate-functions.php#L336-L337

Since we need to get both the affiliate's email address in certain situations like sending emails, and we also need to grab the payment email we could pass in a new parameter to the function to determine which email we want. 

Ideally, and since this issue has cropped up before I think we should make a new `affwp_get_affiliate_payment_email()` function to keep things simpler, and update any code that needs the payment email address.

ticket: https://secure.helpscout.net/conversation/106671756/13317/

**Comment by pippinsplugins** [comment]
:+1:

**Comment by fjarrett** [comment]
I'm on it.

**Comment by sumobi** [comment]
Thanks!

**Comment by pippinsplugins** [comment]
Pretty sure this is good to go but will test once more to be sure.

**Comment by pippinsplugins** [comment]
Merged into `release/1.7`.

@sumobi looks good to me. Could you give it a once over as well?

**Comment by sumobi** [comment]
@pippinsplugins  looks good to me
