### ISSUE TITLE
Shortcodes not available when doing_ajax

### ISSUE THREAD

**Issue by juanvillegas** [affiliatewp/AffiliateWP#793]
Hey,

maybe mine is a very specific use case, but trying to render the generic referral tracking script using an ajax call, I noticed the shortcode is not available. The problem is the following section: https://github.com/affiliatewp/AffiliateWP/blob/master/affiliate-wp.php#L258

Shortcodes are not instantiated when the user is an admin (thats fine), but notice that doing_ajax will also fall under the is_admin umbrella.

We fixed by reque_once the shortcode file.

Juan

**Comment by pippinsplugins** [comment]
It should be available. admin-ajax.php sets `is_admin()` as true.

Are you ajax calls going through admin-ajax.php?

**Comment by pippinsplugins** [comment]
Oh, no, sorry, I have that backwards. You're right.

We'll fix that.

**Comment by pippinsplugins** [comment]
We just need to load short codes globally.

**Comment by juanvillegas** [comment]
thanks sir!

sorry, github never sent me a notification for this!  :(
