### ISSUE TITLE
Direct to Site Sale Affiliate/Credit Tracking

### ISSUE THREAD

**Issue by worldtravlr** [AffiliateWP/AffiliateWP#794]
Hello awesome AffiliateWP Team!  I previously used Affiliates Pro by itthinx and while the rest of the plugin and support was very unintuitive and not recommended, (so glad I switched over to AffiliateWP!) there was one feature that I do miss.

Built into the affiliate program settings as a simple check box was the option to track direct to site sales as a commission easily.  So at any time I could login and look at the affiliate commission made by Direct and know that that is how much profit I would be making from all the various products in my store.

For example:

$100 Product
- Affiliate 1 sends customer = gets $30 credit
- Affiliate 2 sends customer = gets $30 credit
- No Affiliate sends customer (direct site visit) = Special Affiliate called Direct gets $50 credit

Is this an option in AffiliateWP and/or is there a way to maybe force credit any non-affilite sale to a certain affiliate? If that is possible, I could just create an affiliate named Direct and then credit any non-affiliate sales to that user for much easier accounting purposes. 

I think this could be useful to others and would like to put this in as a feature request for future version and/or as an optional Add-on?  The gaol is to be able to easily see what is selling the best direct or affiliates and how much each is making, etc.  If there is another idea for how to implement I am open to that as well.

Thanks so much.

P.S.  This is a feature/enhancement request

---

Here is a related discussions about it on the itthinx website. http://www.itthinx.com/plugins/affiliates/ 

Terry Ladouceur April 17, 2015 at 5:03 am # I need to set a default affiliate ID for when a visitor comes to the site without a referral ID associated with it. Example, visitor comes to http://www.buyonegramgold.com/?gold=4 that gets associated with Affiliate ID 4 and I can use that to dynamically pull info from that affiliates profile such as user_login etc. But if a visitor comes to http://www.buyonegramgold.com/ without a Affiliated ID I want to use a default ID of 1, so I can still use code to pull info from an affiliate profile such as user_login and in this case it would be affiliate 1. I know there is the Default setting to assign any purchases to that default ID when a purchase is made but I need the ID assigned when they visit the site immediately. Thanks in advance for any assistance. Terry Ladouceur

antonio April 17, 2015 at 5:52 am # Hi Terry, in Affiliates->Settings:referrals you can enable "Store direct referrals" so whenever a referral is suggested and no affiliate is attributable to it, the referral will be attributed to Direct (ID 1). If you need to create the cookie always, you can use 'affiliates_parse_request' function in affiliates/lib/core/wp-init.php as reference to create your own solution. Regards, Antonio B.

Terry Ladouceur April 17, 2015 at 2:49 pm # Thanks Antonio, that is exactly what I needed. I have been able to now hard code a default ID so that my dynamically created links to third party sites will be sure to contain an affiliate ID even if the user arrives at the site without one. Terry Ladouceur

**Comment by pippinsplugins** [comment]
There isn't at this time but I have seen others want the same feature.

We can definitely consider adding it.

**Comment by worldtravlr** [comment]
Awesome thanks @pippinsplugins for considering it!  Our accountant and my team would love to have this feature as it would save us a bunch of math which only the acountant is good at :+1:

**Comment by worldtravlr** [comment]
One idea may be to add a few lines of PHP somewhere (with a checkbox in the settings) that would see if any affiliate cookie had been set on the customers browser and if not, would allow you to credit that sale to a specific Affiliate ID that it would either auto create called Direct, or you could specify via affiliate ID or username in the settings.  No idea how complicated than could be, but seems like a somewhat simple solution from my non-programer point of view (so could be way off :-)

**Comment by tubiz** [comment]
@worldtravlr a plugin can be created to add this feature to AffiliateWP pending when it is added to AffiliateWP. You can contact me for more information on this.

**Comment by worldtravlr** [comment]
Thanks @tubiz.  I found a temporary workaround until implemented.

**Comment by DrewAPicture** [comment]
Seems like this might be related (in part) to the discussion on #245.

**Comment by DrewAPicture** [comment]
Closing in favor of the Direct Link Tracking add-on. See #245.

**Comment by pippinsplugins** [comment]
This should be re-opened, actually, as it's not the same thing as Direct Link Tracking.

**Comment by sumobi** [comment]
@AffiliateWP/core @worldtravlr 

While this seems like a handy thing to have, I don't feel like it belongs in core since it's not tracking anything to do with referral sales, but rather the opposite - what was tracked _not_ through affiliate sales.

In saying that, I do see it's usefulness and I'd love to see a free add-on. IMO though it feels a bit hacky assigning referrals to a special affiliate. It may reflect on reporting and cause some confusion.

Unless anyone disagrees I vote we close this or tag as free add-on so it can be built.

**Comment by pippinsplugins** [comment]
I agree.

**Comment by worldtravlr** [comment]
Thanks team.  Could we look into it as a free ad-on?  Could I submit that somewhere else or is that not of interest?  I understand either way and thanks again.

**Comment by sumobi** [comment]
@worldtravlr Absolutely. If you have some code/a plugin we'd love to see it hosted on WordPress.org and we'll link to it on our 3rd party add-ons page. Otherwise, we can certainly consider building a free add-on.

**Comment by worldtravlr** [comment]
Thanks @sumobi. No problem.  Here is the code we have used for this.  I think you kindly made it for us.

`/*
 * Credits direct site sales to Specified Affiliate such as Direct for easier profit tracking
 *
 * @since 1.0
 */

function affwp_custom_credit( $order_id = 0, $posted ) {

    // affiliate to credit
    $affiliate_id = ##;

    // amount of referral
    $referral_amount = $$.¢¢;

    // set status
    $referral_status = 'pending';

    // set description
    $referral_description = 'Direct to site sale';

    // was the customer referred?
    $was_referred = affiliate_wp()->tracking->was_referred();

    // customer was not referred, add referral to specific affiliate
    if ( ! $was_referred ) {

    	// Check if referral exists before adding.
    	$existing = affiliate_wp()->referrals->get_by( 'reference', $order_id, 'woocommerce' );
    	if ( $existing ) {

    		affwp_set_referral_status( $existing, $referral_status );

    	} else {

	        affiliate_wp()->referrals->add(
	            array(
	                'affiliate_id' => $affiliate_id,
	                'amount'       => $referral_amount,
	                'status'       => $referral_status,
	                'description'  => $referral_description,
	                'reference'    => $order_id,
	                'context'      => 'woocommerce'
	            )
	        );

    	}
    }
}

if ( function_exists( 'affiliate_wp' ) ) {
	// add_action( 'woocommerce_checkout_order_processed', 'affwp_custom_credit', 10, 2 );
}`

**Comment by sumobi** [comment]
Oh yeah, I remember now!

Thanks for that, we'll definitely need to make it support other integrations other than WooCommerce etc.
