### ISSUE TITLE
Referrals not being generated for new WooCommerce customers

### ISSUE THREAD

**Issue by clickstudio** [affiliatewp/AffiliateWP#797]
I have just noticed that new WooCommerce customer orders are not generating referrals.

I am using 'Auto Register New Users' which is working fine but there is no actual referral being generated for the referring affiliate.

I have tested this with all add-ons disabled and saw no difference.

Has anyone else reported this recently ?

**Comment by pippinsplugins** [comment]
Do you mean referrals are not generated when new customers make a purchase or that referrals are not generated when new accounts are created?

**Comment by clickstudio** [comment]
When an unregistered person makes a purchase, their user account, and affiliate account is created automatically after checkout. 

That's working as expected however if that person was referred, no referral is generated for the affiliate.

For users who are already linked to an affiliate, their referrals are generated fine.

I suspected this had something to do with the Lifetime Referrals add-on but I un-installed it. Made no difference.

I am about to re-install AffiliateWP and all add-ons to see if that helps.

**Comment by clickstudio** [comment]
@pippinsplugins 
@sumobi 

I am convinced that this issue is related to the referrers previous order status.

I have 'Lifetime Commissions' enabled, and 'Auto Register New Users' enabled.

When a new customer (no user account) places an order (after being referred), there are no referrals generated if the referrers previous order has a status of 'Processing'. 

I know I have mentioned this in another thread for consideration but it is a real issue guys. Orders with the status of 'Processing' have ready been paid for and should not prevent referrals being generated.

I may not change an order to 'Complete' for 1-2 days (Picked, packed, and shipped) and even longer for back orders. In that time the customer (I hope) has already referred people.

If those people place an order there is no referral generated and I am not 100% sure but it seems as if the two users are not linked either.

This breaks the entire process and I can't add the affiliate program to my site while this logic is in place.

**Comment by ramiabraham** [comment]
*(related, HS13557)*

**Comment by clickstudio** [comment]
Hi Rami,

Slightly unrelated to this issue, can you please tell me if it is possible to hook into the following functions ?

file: affiliate-wp/includes/integrations/class-woocommerce.php

functions:
add_pending_referral()
mark_referral_complete()

I am trying to hook into them using something like the following but can’t get it working:

add_action( 'wc_autoship_payment_complete', array( Affiliate_WP_WooCommerce, 'add_pending_referral' ), 10 , 2);

Any advise would be greatly appreciated.

Thanks
Tim
