### ISSUE TITLE
Add "Unpaid Referrals" column to Affiliates page

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#798]
A customer has requested an "Unpaid Referrals" column for the main Affiliates screen (Affiliates -> Affiliates) in addition to the "Paid Referrals" column that is already there.

ticket:
https://secure.helpscout.net/conversation/107896006/13629/

Here is their reasoning for this:

> Since there's a lag in paying many affiliate (e.g. we offer a 90 day money back guarantee, so we don't pay our affiliate for 90 days) We need to be able to track the unpaid referrals for all affiliate in addition to the paid referrals. It would be great if there was an additional column to quickly look at how all affiliate are doing without drilling down to each affiliate's page.

I think this would be nice, any objections?

ticket: https://secure.helpscout.net/conversation/107896006/13629/

**Comment by pippinsplugins** [comment]
No objections here.

**Comment by sumobi** [comment]
Had another 2 requests for this over the past week
