### ISSUE TITLE
Gravity Forms: referral description is blank when no products are purchased

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#799]
Related: https://github.com/affiliatewp/AffiliateWP/issues/609

When a referral is created using the Gravity Forms integration we pass the products into the referral's description. When we don't use products the description is blank: 

![screen shot 2015-07-28 at 9 19 29 pm](https://cloud.githubusercontent.com/assets/52581/8927828/5c6f557c-356e-11e5-865c-c0e3a830a1d6.png)

See:
https://github.com/affiliatewp/AffiliateWP/blob/master/includes/integrations/class-gravityforms.php#L45

Instead of having a blank description I feel we should populate this with something useful like the form's title or description so you can easily see which form on the site generated the referral without having to click anywhere else. 

![screen shot 2015-07-28 at 9 13 18 pm](https://cloud.githubusercontent.com/assets/52581/8927713/7f48318c-356d-11e5-8079-e096f9dbd99b.png)

The only issue I can see is if the admin named their form's title and description something private, and didn't necessarily want anyone to see it. If allow this, it will show up in the affiliate's referrals table on the front end. 

How about we add a new input field to the form settings, a place for the admin to add a label that will show as the referral's description, but only when products are not purchased?

@fjarrett @pippinsplugins

**Comment by pippinsplugins** [comment]
A new input field may be a bit overkill in my opinion.

I'd prefer that we just default to the form's title. I can't think of any reason that would be super private.

**Comment by fjarrett** [comment]
The form title being private does seem like an edge case to me. If affiliates are earning referrals off a form, both the site admin and their affiliates should have a unified view of what object those referrals came through. Using the form title is the simplest way of doing that.

**Comment by sumobi** [comment]
Sounds good to me

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
Looks like this isn't working, perhaps it didn't get merged in properly
