### ISSUE TITLE
Clarify the product-specific rate fallback verbiage

### ISSUE THREAD

**Issue by fjarrett** [affiliatewp/AffiliateWP#805]
In light of the changes coming in #751 I think this line is a little misleading. It makes it sound like product rates, in fact, take priority over individual affiliate rates...

![screen_shot_2015-07-31_at_10_35_37_am](https://cloud.githubusercontent.com/assets/522158/9011330/456c9870-3772-11e5-9322-f7f31b16f0a1.png)

Maybe instead it should say something like:

> Leave blank to use the site default referral rate.

**Comment by pippinsplugins** [comment]
:+1:
