### ISSUE TITLE
ActiveCampaign add-on

### ISSUE THREAD

**Issue by wordmaid** [affiliatewp/AffiliateWP#807]
A customer has requested an ActiveCampaign (http://www.activecampaign.com/) integration. 

Ticket: https://secure.helpscout.net/conversation/109032985/13892/

**Comment by ghost1227** [comment]
This is now available as a free extension on .org. Please feel free to contact me with any questions or suggestions.

https://wordpress.org/plugins/affiliatewp-activecampaign/
