### ISSUE TITLE
Website URL field can be bypassed with a space

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#810]
In Safari and Chrome the website URL field can be bypassed by entering a space into the field.

![screen shot 2015-08-07 at 12 52 29 am](https://cloud.githubusercontent.com/assets/52581/9111850/c82a2c56-3c9e-11e5-9a32-0dc1f0a1ec4f.png)

![screen shot 2015-08-07 at 12 52 40 am](https://cloud.githubusercontent.com/assets/52581/9111849/c82643ca-3c9e-11e5-86eb-b417b1751540.png)

**Comment by pippinsplugins** [comment]
Whoops.
