### ISSUE TITLE
Incorrect referral URLs when using a # inside [affiliate_referral_url] shortcode and referral URL generator

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#811]
When a hash (#) is used in the [affiliate_referral_url] shortcode it appends a slash (/) to the end of the URL which is incorrect:

    Shortcode:
    [affiliate_referral_url url="http://affwp.dev/2015/03/22/hello-world/#comment"]

    Shortcode output:
    http://affwp.dev/2015/03/22/hello-world/?ref=3#comment/ 

If you take away the trailing slash above it still does not correctly store the AffiliateWP cookies. Only without the hash (and everything after) does it work, eg:

    http://affwp.dev/2015/03/22/hello-world/?ref=3

As per the "Basics" section of https://en.wikipedia.org/wiki/Fragment_identifier we know that the above should have worked as the hash must always be at the end, after any query string arguments.

Using pretty URLs work correctly and the AffiliateWP cookies are stored in the browser.

    http://affwp.dev/2015/03/22/hello-world/ref/3/#comment 

And finally, there's an issue with using #'s in the Referral URL Generator. It should strip the fragment identifier out, and append it to the very end of the URL, after the query string. The correct URL should have been:

    http://affwp.dev/?ref=3#something

![screen shot 2015-08-07 at 1 17 53 pm](https://cloud.githubusercontent.com/assets/52581/9126860/c18404cc-3d06-11e5-8a91-fc56aae0fc11.png)

**Comment by pippinsplugins** [comment]
@sumobi let me know if you'd like any help with this

**Comment by sumobi** [comment]
@pippinsplugins will do

**Comment by sumobi** [comment]
@pippinsplugins One thing left on this which involves regex. I hope you're a pro.

Here's the issue:

A referral URL that contains a fragment identifier does **not** store a visit:
http://affwp.dev/2015/03/22/hello-world/?ref=3#comment

This is because it's only splitting the URL on `&` and doesn't take `#` into account:
https://github.com/affiliatewp/AffiliateWP/blob/master/assets/js/tracking.js#L85

If the URL contains `#` the `hashes` variable becomes:
http://test.affwp.dev/ref/4#comment

instead of:

http://test.affwp.dev/ref/4

And because of this, the `ref` is set to `4#comment` instead of `4`, thus does not store the visit.

We need to pass a regular expression into the `.split('&');` that takes into account `&` or `#`. The closest I got was:

`/(&)|(#)/`

Clearly that's incorrect.

**Comment by worldtravlr** [comment]
This is also an issue when trying to supply buy now links for woocommerce to affiliates.  For example:

     [affiliate_referral_url url="https://example.com/cart/?add-to-cart=23"]

does not translate the second "?" to an "&" and produce:

    https://example.com/cart/?ref=3&add-to-cart=23

as it should.

**Comment by sumobi** [comment]
@worldtravlr I'll test it and get that fixed for v1.7 if it's still an issue.

**Comment by worldtravlr** [comment]
Thanks @sumobi!  Keep up the awesome work!

**Comment by sumobi** [comment]
@worldtravlr Can't seem to replicate, looks like it's already fixed in the latest master. I used:

`[affiliate_referral_url url="https://example.com/cart/?add-to-cart=23"]`

and the link is shown on the page as:

`https://example.com/cart/?add-to-cart=230&ref=4`

Can you test the latest master on your dev site and see if it's still an issue for you?

**Comment by worldtravlr** [comment]
Looks perfect!  Thanks @sumobi.  I may not have time to test it on my dev server, but if you have tested and looks good to you, then sounds great.  I was trying it on the previous version and have not used any master builds, so would assume all is well :+1:

Awesome work and thanks for fixing these as well as the affiliate number shortcode in the interim.  May be worth adding the affiliate number shortcode to the shortcode plugin just for an additional option for the affiliate area.

**Comment by sumobi** [comment]
You're welcome.

> May be worth adding the affiliate number shortcode to the shortcode plugin just for an additional option for the affiliate area.

Sounds good to me

**Comment by worldtravlr** [comment]
:+1:  :-)

**Comment by pippinsplugins** [comment]
@sumobi This is ready for testing. I've fixed URLs with fragment identifiers.

**Comment by sumobi** [comment]
@pippinsplugins 

This now stores a visit
http://test.affwp.dev/hello-world/?ref=4#comment

However pretty affiliate URLs are no longer working for me, eg:
http://test.affwp.dev/hello-world/ref/4/

If I switch back to master they work again

**Comment by sumobi** [comment]
The visit is stored as `http://test.affwp.dev/hello-world/?#comment` in the visits admin screen

**Comment by pippinsplugins** [comment]
Did the cookies get set correctly?

**Comment by sumobi** [comment]
The cookies don't get set at all when using pretty affiliate URLs

**Comment by pippinsplugins** [comment]
@sumobi Can you force refresh to make sure your JS isn't cached?

**Comment by sumobi** [comment]
@pippinsplugins didn't help

**Comment by pippinsplugins** [comment]
What about with non-pretty?

**Comment by sumobi** [comment]
non pretty works great still

**Comment by pippinsplugins** [comment]
K, that helps

**Comment by pippinsplugins** [comment]
@sumobi Ok I believe I've fixed it.

**Comment by sumobi** [comment]
@pippinsplugins pretty referral links are now working for me :+1:

**Comment by pippinsplugins** [comment]
Yay!

**Comment by pippinsplugins** [comment]
Merged into `release/1.7`

**Comment by sumobi** [comment]
@pippinsplugins Looks like an issue that I thought was solved has popped back up.

If you enter a URL into the `Page URL` input field that contains a fragment identifier then it should strip it out and place it at the very end of the URL.

Wrong:
Input: http://affwp.dev/2015/03/22/hello-world/#comment
Output: http://affwp.dev/2015/03/22/hello-world/#comment/?ref=4

Correct:
Input: http://affwp.dev/2015/03/22/hello-world/#comment
Output: http://affwp.dev/2015/03/22/hello-world/?ref=4#comment

![screen shot 2015-09-17 at 1 16 24 pm](https://cloud.githubusercontent.com/assets/52581/9922567/587c5404-5d3e-11e5-8f61-1ac2b3d039fa.png)

**Comment by sumobi** [comment]
Actually no, it works fine, JS files were cached :)

**Comment by pippinsplugins** [comment]
yay!
