### ISSUE TITLE
Fallback referral tracking method doesn't work if user enter big number on cookie expiration days setting

### ISSUE THREAD

**Issue by maurisrx** [AffiliateWP/AffiliateWP#812]
Hello,

When user enter big number on cookie expiration days setting when using fallback referral tracking method, the cookie is only stored with session expiration time and it will disappear when visitor close the browser.

It may be caused by PHP `setcookie()` expiration time limit which limits the maximum amount of time cookie can be stored. Can it be fixed by using something like this:

`$cookie_exp = $cookie_exp > 3650 ? 3650 : $cookie_exp;`

When user enter the cookie exp time with value more than 3650 days / 10 years, set 3650 days as maximum value that can be stored in the cookie.

Thanks,
Mauris

**Comment by pippinsplugins** [comment]
Thanks for the heads up!

**Comment by sumobi** [comment]
Just ran into this issue on a customer ticket :+1:
