### ISSUE TITLE
Provide a default affiliate agreement

### ISSUE THREAD

**Issue by zackkatz** [AffiliateWP/AffiliateWP#816]
Have a lawyer draft a generic affiliate agreement that handles things like:

* Better define the affiliate relationship: affiliates are not employees
* Handling arbitration: they can't sue for rejected commissions
* Define prohibited promotional methods: generic enough to be obvious (no spamming, illegal methods, promoting on illegal websites)
* No using paid links with the site's URL as the display links (you could use variables that get swapped out with the blog's URL)
* Specifies the cookie duration, as set in the settings (again, a placeholder variable would work)

This could also be open-sourced in a stand-alone AffiliateWP repo, allowing for pull requests. I understand laws are different for each country, state, etc, but a nice starting point would be great.

### Samples 

* [Here's GravityView's current affiliate agreement](https://gravityview.co/account/affiliates/agreement/) that tries to implement this stuff in a basic way without laywers.
* [ShareASale's agreement](http://www.shareasale.com/agreement.cfm) with more lawyer-y stuff.
* [ThemeForest's agreement](http://themeforest.net/legal/affiliate#becoming-an-affiliate)

**Comment by sumobi** [comment]
:+1: We've had many customers ask if we have an agreement they could use. Usually we point them to our own. 

If we had a blueprint it would be one less thing for someone to worry about. A small handful of customers have said that not having an agreement has been a real barrier in getting their affiliate system set up.

**Comment by pippinsplugins** [comment]
My only concern with this is the possible legal ramifications.

If we give someone a blueprint agreement and then they get sued, we could potentially get pulled into that.

**Comment by zackkatz** [comment]
Well, add a clause like Elance on their documents:

> This Standard Affiliate Agreement is a sample provided for your information only and may not be relied upon as legal advice. This agreement might not be appropriate for your requirements. AffiliateWP makes no warranty about the suitability of this sample agreement and accepts no liability arising out of the use of this agreement. Please consult your legal or business advisor for further information or advice.

**Comment by zackkatz** [comment]
Who knows, you may be just as liable for *not* providing one! Lawyers are crafty people…

**Comment by DrewAPicture** [comment]
I'd definitely be concerned about the legal ramifications of passing along a template to all affiliates regardless of their particular locales and laws. If we really wanted to provide one there would have to be a rock solid indemnity clause (like Elance's).

Closing as *maybe later*.
