### ISSUE TITLE
Add Saudi Riyal

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#821]
We should add the Saudi Riyal as a currency, it's been requested a few times. We've also been given a full Arabic translation and the Saudi Riyal is a common currency for Arabic speakers.

**Comment by pippinsplugins** [comment]
Is it available in WooComemrce and other plugins?

**Comment by sumobi** [comment]
WooCommerce lists Saudi Arabia as a country but I don't see a currency for it. They do have the United Arab Emirates Dirham though.
