### ISSUE TITLE
Pretty permalinks cause 404 on product archive pages

### ISSUE THREAD

**Issue by ramiabraham** [affiliatewp/AffiliateWP#833]
Examples:

http://affiliatewp.dev/product-category/stuff/ref/1

http://affiliatewp.dev/product-category/stuff/ref/username

**Comment by pippinsplugins** [comment]
We should see if this fails on all archives. Might not just be limited to product archives.

**Comment by ramiabraham** [comment]
- 404 on EDD product categories as well
- Works on default WP post categories 
- Works with an arbitrary cpt
- Works on several cpt-based plugins which are not primarily commerce-based, such as the Tribe calendar

**Comment by pippinsplugins** [comment]
That makes me think it's a priority issue.

**Comment by pippinsplugins** [comment]
I see the issue, at least for WooCommce. The rewrite rules are not registered on the categories.
![screen shot 2015-09-04 at 7 57 38 am](https://cloud.githubusercontent.com/assets/1034109/9684035/8b456c90-52da-11e5-8192-ece1124916b0.png)

**Comment by pippinsplugins** [comment]
@ramiabraham @sumobi could you guys test this?

**Comment by pippinsplugins** [comment]
Related core ticket: https://core.trac.wordpress.org/ticket/33728#ticket

**Comment by ramiabraham** [comment]
Issue persists for me  with patch applied; are you getting the same behavior?

**Comment by pippinsplugins** [comment]
Refreshed permalinks?

**Comment by ramiabraham** [comment]
Yes, via core ui and explicit `flush_rewrite_rules`. This *does* fix the the WP core issue, but it persists in WC and EDD.

**Comment by pippinsplugins** [comment]
Damn . . . it completely fixed it for me. Testing again now.

**Comment by pippinsplugins** [comment]
Yep fixes for me.

@ramiabraham if you install a rewrite rules inspector (let me know if you're not sure which to use or need a recommendation), do you see the /ref/ rewrite for product categories?

**Comment by sumobi** [comment]
@pippinsplugins 

1. Visited WooCommerce category page which resulted in 404 as this issue outlines
2. Created branch from issue/833 but a category page still results in a 404
3. Flushed permalinks and category page now works
4. Switched back to master branch without patch, still working correctly

I see the ref rewrite for product categories
![screen shot 2015-09-05 at 7 45 23 pm](https://cloud.githubusercontent.com/assets/52581/9698366/bb6dad88-5406-11e5-8d98-29b614bd14e1.png)

**Comment by pippinsplugins** [comment]
@sumobi it still works after switching back to master because rewrite rules
are persistent. They are only recreated when they are told to be.

**Comment by sumobi** [comment]
Yeah just making sure. I tested with a fresh install and patch. Issue is definitely fixed after flushing permalinks. Damn permalinks...

**Comment by pippinsplugins** [comment]
Marking as fixed then.
