### ISSUE TITLE
affwp_get_affiliate_id ajax call made for all non-affiliate visits to site

### ISSUE THREAD

**Issue by mindylue** [affiliatewp/AffiliateWP#836]
In tracking.js, the affwp_get_affiliate_id ajax call is being made every time a non-affiliate visitor loads a page on the site. The issue is coming from ref not being checked for undefined in the conditional on line 25: `if( ! $.isNumeric( ref ) ) {`

**Comment by pippinsplugins** [comment]
Thanks for the report! We'll get that fixed.
