### ISSUE TITLE
Affiliate Area & Reports Chart

### ISSUE THREAD

**Issue by worldtravlr** [AffiliateWP/AffiliateWP#848]
Hi AffiliateWP Team.  I would like to put in a formal request to improve the charts for the affiliate area and reports.  We just had a big sale and while smaller volume sales and/or affiliates/affiliate programs may find the current charts useful and helpful, if there is a lot of volume, in their current form, they do not seem to be very helpful.

I am attaching some of the charts here to show you what that looks like.  For our sale we had a single product that was applicable for commission and we had three commission tiers.  The sale lasted only 5 days and had a lot of commissions come through.  The current chart just lists commissions by date or time as a collection of dots.

I have included an example of Woocommerce reports chart which I feel does a great job of showing actual impact, etc.

Instead of showing just dot on a line, I think it would be much more helpful and intuitive if the affiliate and reports could show total by day.  For example, maybe day one the affiliate made something like the following:

Day 1 - $2,000 in total affiliate commissions
Day 2 - $3,000
Day 3 - $1,800
Day 4 - $2,500
Day 5 - $5,000
Day 6 - $5,500

So the chart would look something like this:

![screen shot 2015-09-21 at 10 53 53 am](https://cloud.githubusercontent.com/assets/6686642/9995298/63047ee2-604f-11e5-8ce0-f800dde4a3e3.jpg)

Here is how that currently might look:
![11988648_10207165833600142_2601321433176794026_n-1](https://cloud.githubusercontent.com/assets/6686642/9995081/43c850c2-604e-11e5-9eed-3a33671457e8.jpg)
And from the admin it is even more confusing for the combined affiliate referrals.
![screen shot 2015-09-21 at 10 45 33 am](https://cloud.githubusercontent.com/assets/6686642/9995069/38877af8-604e-11e5-9145-2033654febbe.jpg)
Here is a full example of the Woocommerce reports chart so you can see the additional info it can show.  This could be maybe hits, conversions rates, rejected referrals, pending referrals, etc.
![woocommerce-reports-sales-by-date-950x540-1](https://cloud.githubusercontent.com/assets/6686642/9995075/3caabbf4-604e-11e5-84d6-a6f87d767f91.png)

Hope that helps and please let me know if you have any questions.  Thanks so much.

**Comment by pippinsplugins** [comment]
Yes yes yes.

Related #616

**Comment by worldtravlr** [comment]
Awesome!  Thanks so much and sorry I missed the other one.

**Comment by michaelbeil** [comment]
@worldtravlr that looks mighty nice. Do you by chance have a PR for the above charts?

**Comment by worldtravlr** [comment]
Thanks @michaelbeil.  Sorry for the confusion, but what is a PR?

**Comment by michaelbeil** [comment]
Hey @worldtravlr, no worries. PR is a pull request on GitHub. We are checking into this, though, and should have something out in the near future.

**Comment by worldtravlr** [comment]
Thanks @michaelbeil and sorry for the noob question.  Makes sense.  

I have not made a PR.  This is more of a feature request and, sadly, I do not have the coding skills needed to contribute as much as I wish I could.  Here is a better mockup using WooCommerce reporting features as a base.  Not sure if these can be used via GPL and/or what EDD has for reporting options that may be pulled into this, but hope it helps.

![affiliatewp---chart-mock-up-from-woocommerce-reports](https://cloud.githubusercontent.com/assets/6686642/10436351/d3bce8fe-70f3-11e5-80b6-8997a497afc9.png)

Do you have any timeline you could share for near future?  Are we talking weeks, months, 6+ months, etc.?  Thanks so much and excited to check it out once updated.

**Comment by pippinsplugins** [comment]
@worldtravlr I'd love to say a few months but I can't promise that.

**Comment by worldtravlr** [comment]
Thanks @pippinsplugins.  No worries and I understand.  Excited it has a Milestone and I know all your customers and their affiliates will love any improvement possible with the reporting charts.  Thanks and don't hesitate to let me know if I can help with mockups or further descriptions/ideas and glad to do so!

**Comment by worldtravlr** [comment]
Your team probably already knows about this, but this may help a lot in plotting the data nicely without to much effort for the charting GUI - http://www.chartjs.org .  Hope it helps.

**Comment by sumobi** [comment]
:+1: I've used chartJS for something else recently, it's really nice.

**Comment by worldtravlr** [comment]
Very cool @sumobi!  Thought you might already know about it.  Did you use it of EDD or one of the EDD recommended them by chance?  Would love to see what you did with it.

**Comment by sumobi** [comment]
@worldtravlr So far I've only used it for this plugin to show happiness ratings: https://github.com/sumobi/help-scout-happiness-report/issues/3

**Comment by worldtravlr** [comment]
Very cool!  Love it! :+1:

**Comment by zackkatz** [comment]
:+1:

**Comment by worldtravlr** [comment]
Looks like we are still a ways away from 1.8 so I am assuming this would probably be looked at more in February or march?

**Comment by pippinsplugins** [comment]
Yes. We're hoping to start actively working on it sometime this month.

**Comment by worldtravlr** [comment]
Awesome @pippinsplugins.  May try and see if I can send some help your way on it :+1:

**Comment by sumobi** [comment]
Here's some feedback on reporting from a customer
https://secure.helpscout.net/conversation/161633016/25627/?folderId=205524

**Comment by tubiz** [comment]
Hi @sumobi I am working on this ticket . I will be grateful if you can share some feedbacks on reporting from customers so that i can know what changes needs to be done.
I plan to use ChartJS for this, will like the AffiliateWP team to give a go ahead on this.
Thanks.

**Comment by sumobi** [comment]
@tubiz Awesome! If you can, please post any ideas/thoughts you have here so we can discuss them. 

:+1: to ChartJS, we'll most likely be using that also.

Here's the above HelpScout feedback from the customer for consideration:

> reporting. having the ability to see not only listing of affiliate referrals but also the sum total. and when setting a date range - seeing sum total they earned, without need to download csv and waste time. this way i see fast what to pay them esp when have a few affiliates and want fast overview. 

> also, in admin's affiliate reports tab should be ability to: 

> [a] select affiliate and see total earned lifetime and per custom time,

> [b] see all affiliates and what they earned lifetime and per custom time i want to see/ this mo/last mo. 

> [c] have ability to set number i want to see like top 10 best or top 50 earners and the period. last/least active ones, most active ones. the conversion rate from affiliate traffic. 

> [d] ability to see who converts best their traffic. conversion rate per aff'. like when hovering over the number of visits in affiliates tab, or best as own column.

**Comment by pippinsplugins** [comment]
Closed in favor of #1076
