### ISSUE TITLE
Add support for URL blacklists

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#851]
PR: #1379

A customer has asked about the option to blacklist certain URLs in order to prevent referrals from those locations: http://affiliatewp.com/version-1-7-released/#comment-15003

**Comment by sumobi** [comment]
Sounds like a neat idea

**Comment by pippinsplugins** [comment]
I'm going to punt this to 1.9.

**Comment by sumobi** [comment]
@AffiliateWP/core whatever happened to this? seems like there was some work done, it got moved, but then closed again.

**Comment by pippinsplugins** [comment]
@sumobi Not sure.

I've restored the PR and updated it to go into `release/2.0`.

@DrewAPicture could you refresh the PR please?

**Comment by sumobi** [comment]
👍

**Comment by DrewAPicture** [comment]
@pippinsplugins Refreshed and added hook docs.

**Comment by sumobi** [comment]
Works for me.

Currently it only kills the visit when coming from the blacklisted site. If you already have the visit cookie stored, then a referral can still be created. 

Since cookies can be stored for a long period I think we should also prevent any referrals from being generated if the visit is tied to the blacklisted URL. 

Could we look up the referral being generated, grab the visit ID, then check that visit for the blacklisted URL?

**Comment by pippinsplugins** [comment]
Yeah we should be able to do that pretty easily.

**Comment by pippinsplugins** [comment]
Actually I don't think we should check if the existing visit came from a blacklisted URL, simply because that will add a second set of DB queries every time. We don't currently query the data from the visit when recording a referral. In order to check if it's blacklisted, we would need to pull out the visit data, slowing down referral tracking.

**Comment by DrewAPicture** [comment]
I agree about not slowing down referral tracking.

**Comment by pippinsplugins** [comment]
@DrewAPicture let's get some unit tests in here then and merge.

**Comment by sumobi** [comment]
interesting, hadn't thought of that

**Comment by pippinsplugins** [comment]
Merged but then remembered we still need unit tests so leaving open :P

**Comment by DrewAPicture** [comment]
Tests added in #1897. `$url` parameter in `affwp_is_url_banned()` was also made required.

**Comment by DrewAPicture** [comment]
Tests passed, merged #1897.

**Comment by pippinsplugins** [comment]
:+1:
