### ISSUE TITLE
Problem with 1.7 upgrade routine in #751

### ISSUE THREAD

**Issue by nathanrice** [affiliatewp/AffiliateWP#852]
When the 1.7 upgrade routine runs, it's supposed to find all the instances of percentage referral rates between 0 and 1 and multiply by 100 to make this a valid percentage.

Problem is, this should include the default referral rate. But it seems like it's stalling out right here:
https://github.com/affiliatewp/AffiliateWP/blob/master/includes/admin/class-upgrades.php#L141-L145

Best I can tell, if the upgrade routine doesn't find any custom (not default) affiliate rates, it returns early. But it shouldn't, because it still needs to change the default value if it meets the criteria.

**Comment by pippinsplugins** [comment]
@nathanrice By default, do you mean default site wide?

**Comment by nathanrice** [comment]
Yes, the value set in Settings.

**Comment by nathanrice** [comment]
Basically, [this](https://github.com/affiliatewp/AffiliateWP/blob/master/includes/admin/class-upgrades.php#L159) gets ignored if [this](https://github.com/affiliatewp/AffiliateWP/blob/master/includes/admin/class-upgrades.php#L141) returns no results.

**Comment by nathanrice** [comment]
Give me a few minutes, and I'll update my fork so I can submit a PR.

**Comment by pippinsplugins** [comment]
Thanks @nathanrice! I'll push out the update now.
