### ISSUE TITLE
Affiliate ID via an endpoint like EDD-SL

### ISSUE THREAD

**Issue by shazahm1** [AffiliateWP/AffiliateWP#855]
On every page load there is an ajax call for the affiliate ID. Can this be changed to happen in an endpoint so [plugins endpoints](https://github.com/dannyvankooten/plugin-endpoints) can be used to reduce load time? I use this with EDD-SL with fantastic results. Presently the load time of the ajax call is about 1.3sec whereas an EDD-SL call only takes about 300millisecs. I would expect to see similar improvement in load time.

Thanks for your consideration!

**Comment by pippinsplugins** [comment]
I'm not sure what you mean. How could it use an endpoint since we have to look at every URL to see if there is an affiliate ID supplied.
