### ISSUE TITLE
Auto Register users as affiliates not working 

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#861]
Looks like `Auto Register New Users` is broken in v1.7. Customer reverted to 1.6.5 and it then works.
https://secure.helpscout.net/conversation/125769388/17725/

I have also replicated the issue. The affiliate is created, but there isn't a status:

![screen shot 2015-09-27 at 11 35 04 pm](https://cloud.githubusercontent.com/assets/52581/10122287/696a4bb0-6570-11e5-843f-25c64b32eab6.png)

**Comment by sumobi** [comment]
@pippinsplugins Tested thoroughly but would appreciate some extra eyes on this.

Tested:

- Adding an affiliate through the admin with a custom status
- The default affiliate registration form (the status is set via class-register.php anyway)
- Auto registering users as affiliates when registering on the site
- All of the above with `Require approval` enabled.

**Comment by pippinsplugins** [comment]
Looks good to me.
