### ISSUE TITLE
Database error for 'wp_affiliate_wp_campaigns'

### ISSUE THREAD

**Issue by tushonline** [AffiliateWP/AffiliateWP#863]
Why does it show Error & 'Corrupt' 
Using 1.7.3 

![image](https://cloud.githubusercontent.com/assets/4390051/10132792/08b0c05c-65f6-11e5-9714-fe479d9fd153.png)

**Comment by pippinsplugins** [comment]
@tushonline Is that showing after running an `optimize` query on the DB?

**Comment by tushonline** [comment]
@pippinsplugins that's correct

**Comment by pippinsplugins** [comment]
@tushonline Besides when optimizing it, does the campaigns view appear to be working?

**Comment by tushonline** [comment]
See these screens. Please let me know if you need anything more

![image](https://cloud.githubusercontent.com/assets/4390051/10191658/9ea0ed82-6793-11e5-8379-205d927ecf37.png)

![image](https://cloud.githubusercontent.com/assets/4390051/10191694/ea08288a-6793-11e5-8ea4-ed2d35552836.png)

**Comment by tushonline** [comment]
Hi. Do we have any update on this? Same issue persist with latest update too.

**Comment by pippinsplugins** [comment]
I've still been unable to identify any issue here and do not see the same corrupt status that you do.

We're leaving it open so that we can hopefully track it down but there is no ETA yet.

**Comment by raisonon** [comment]
I get this with this table: https://www.dropbox.com/s/agz8hr5kvdyfz27/Screenshot%202015-12-06%2016.52.32.png?dl=0

**Comment by pippinsplugins** [comment]
@raisonon that is a separate issue.

@tushonline Views cannot be optimized so turns out this is not a problem. See this: https://dba.stackexchange.com/questions/43671/optimize-command-issuing-view-is-not-base-table-and-corrupt-error-messages

To avoid the issue, simply don't try and optimize the table.

As this is invalid, I'm going to close this.
