### ISSUE TITLE
Fatal error: Call to a member function get_column_by() on a non-object

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#867]
@pippinsplugins Customer is receiving this error when activating AffiliateWP on a GoDaddy hosting account:

 `   Fatal error: Call to a member function get_column_by() on a non-object in /home/content/p3pnexwpnas02_data02/27/2776527/html/wp-content/plugins/affiliate-wp/includes/affiliate-functions.php on line 38`

ref: https://secure.helpscout.net/conversation/126847333/18012/

If I comment out the referenced function then it shows a new fatal error about the `get()` function. 

We have another ticket with the same error from the 26th: https://secure.helpscout.net/conversation/125368395/17649

I wonder if it's GoDaddy specific.

**Comment by sumobi** [comment]
Looks like the issue went away as per the other ticket:

> Ok… Here's what I found. I disabled the plugins one by one and try reactivating after each deactivation. Well of course, I was distracted and I deactivated two apps before trying to activate affiliatewp and of course it was that time that it worked… LOL. However, between the two apps (Relevanssi and Woozone) it would most likely be woozone. In any case I did try deactivating affiliatewp and reactivating those two individually then reactivating affiliatewp and could not duplicate the previous error. So it seems that the issue is that it needs to be activated first and after that it doesn't matter.

**Comment by pippinsplugins** [comment]
Let's keep an eye out for similar cases.

**Comment by sumobi** [comment]
:+1:

**Comment by sumobi** [comment]
Another customer: https://secure.helpscout.net/conversation/130774759/19080/

**Comment by sumobi** [comment]
Interestingly enough the customer above was also running the Relevanssi plugin.

**Comment by michaelbeil** [comment]
Relevanssi. what a bother.

**Comment by sumobi** [comment]
Customer above deactivated Relevanssi and reactivated again, followed by AffiliateWP and this fixed the issue. It seems to only happens once, as deactivating Relevanssi/AffilateWP multiple times doesn't produce the issue again.

**Comment by michaelbeil** [comment]
So, it seems like the gremlin of choice is Relevanssi. Deactivating and reactivating that plugin solves the issue.

Mastor @sumobi has done it again.

**Comment by sumobi** [comment]
Haha

**Comment by sumobi** [comment]
Another: https://secure.helpscout.net/conversation/132343139/19489/

**Comment by pippinsplugins** [comment]
This also gets triggered by the `Tweet2Download` plugin:

https://secure.helpscout.net/conversation/159730570/25098/
https://wordpress.org/plugins/tweet2download/

**Comment by michaelbeil** [comment]
Noted @pippinsplugins.

**Comment by sumobi** [comment]
Another report of this, though customer is not using the above 2 plugins:
https://secure.helpscout.net/conversation/160615951/25356/?folderId=205527

Customer has said they have tried with all plugins deactivated and the same issue occurs. Regardless, here's a list of their active plugins:

Actionable Google Analytics: by Tatvic – CC-V3-1.2
Ajax Search Pro: by Ernest Marcinko – 4.6
Ninja Popups: by ArsCode – 4.2.5
CategoryTinymce: by Kevin Heath – 3.6.4
Contact Form 7: by Takayuki Miyoshi – 4.3
Custom 404 Error Page: by Kaspars Dambis – 0.2.4
Fusion Core: by ThemeFusion – 1.7.5.1
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Heartbeat Control: by Jeff Matson – 1.0.3
Easy HTTPS (SSL) Redirection: by Tips and Tricks HQ – 1.4
MailChimp: by MailChimp and Crowd Favorite – 1.4.2
Ni Woocommerce Custom Order Status: by Anzar Ahmed – 1.0
NextScripts: SNAP Pro Upgrade Helper: by Next Scripts – 1.3.4
WooCommerce Product Filter: by Mihajlovic Nenad – 5.0.1
WooCommerce Pushover Integration: by Shop Plugins – 1.0.10
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.8.0.1
Recent Posts Widget Extended: by Satrya – 0.9.9.5
Regenerate Thumbnails: by Viper007Bond – 2.2.4
Revolution Slider: by ThemePunch – 4.6.93
WooCommerce Infinite Scroll and Ajax Pagination: by SB Themes – 1.0
SEO Redirection: by Fakhri Alsadi – 3.4
Smart Cleanup Tools: by Milan Petrovic – 4.3.3
NextScripts: Social Networks Auto-Poster: by Next Scripts – 3.4.29
WP woocommerce best selling products by category: by WP Online Support – 1.0
Stop Spammers Spam Control: by Keith P. Graham – 6.15
Super Socializer: by Team Heateor – 6.6.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.11.21.22

(NEVER UPDATE) Woocommerce ShortCodes Products By Categories: by WP-Zone – 1.8 (MODIFIED)
WooCommerce Abandon Cart Lite Plugin: by Tyche Softwares – 2.3
Woocommerce Alphbetical Search: by Magnigenie – 1.0
WooCommerce Authorize.net Reporting: by WooThemes / SkyVerge – 1.3.2
WooCommerce Cart Notices: by WooThemes / SkyVerge – 1.4.1
WooCommerce Cost of Goods: by WooThemes / SkyVerge – 1.9.3
WooCommerce Coupon Campaigns & Tracking: by WooThemes – 1.0.1 – 1.0.2 is available
WooCommerce Customer History: by Brian Richards – 1.1.1
(NEVER UPDATE) WooCommerce Customer/Order CSV Export: by WooThemes / SkyVerge – 3.10.1 (MODIFIED) – 3.10.4 is available
WooCommerce Amazon Payments Advanced Gateway: by WooThemes – 1.4.3 – 1.4.6 is available
WooCommerce Authorize.net AIM Gateway: by WooThemes / SkyVerge – 3.4.5 – 3.4.6 is available
WooCommerce PayPal Payments Advanced Gateway: by Kiran P – 1.18 – 1.21 is available
WooCommerce Gift Card: by Magenest – 2.6
LiveChat WooCommerce: by LiveChat – 1.1.0
WooCommerce Perfect SEO url: by Perfect SEO url – 2.4.2
WooCommerce Google Product Feed: by Lee Willis – 5.2.1
WooCommerce Products without featured images: by Hermes Alves – 0.1
Woocommerce Request a Review: by Code Ninjas – 1.0
WooCommerce Shipment Tracking: by WooThemes – 1.4.1
WooCommerce Social Login: by WooThemes / SkyVerge – 1.6.0
WooCommerce Subscribe to Newsletter: by WooThemes – 2.3.0 – 2.3.1 is available
WooCommerce Table Rate Shipping: by Bolder Elements – 3.6.4
WooCommerce: by WooThemes – 2.4.7
WooThemes Helper: by WooThemes – 1.5.9
WordPress HTTPS: by Mike Ems – 3.3.6
Yoast SEO Premium: by Team Yoast – 2.3.5
WP All Import Pro: by Soflyy – 4.2.6
Wp Mail Bank: by Tech Banker – 1.34
WP-Mail-SMTP: by Callum Macdonald – 0.9.5
WP-Optimize: by Ruhani Rabin – 1.8.9.10
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.88
WP Robots Txt: by Christopher Davis – 1.1
WP Rocket: by WP Rocket – 2.6.15
WP-SpamShield: by Scott Allen – 1.9.6.8
WordPress SEO News: by Team Yoast – 2.2.5
(DO NOT UPDATE) YITH WooCommerce Wishlist: by Yithemes – 2.0.11 (MODIFIED)

**Comment by pippinsplugins** [comment]
@sumobi test this please?

**Comment by sumobi** [comment]
@pippinsplugins works fine here
