### ISSUE TITLE
In favor of a .gitattributes file

### ISSUE THREAD

**Issue by michaelbeil** [affiliatewp/AffiliateWP#869]
For the ignorance of several files on download of a zip from GH, we could add an `export-ignore` attribute to such files. 

For example:

`.travis.yml export-ignore`

https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#Exporting-Your-Repository

I already have a PR ready if we would want this.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
PR would be great!
