### ISSUE TITLE
Nonce check missing from process_bulk_action()

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#870]
The `process_bulk_action()` method is missing it's nonce check. We need to double check all list table classes for this.

**Comment by pippinsplugins** [comment]
This doesn't work quite right. Looks like nonce verification is not working.

**Comment by pippinsplugins** [comment]
It's failing because the nonce name is wrong.

It's `bulk-{plural}` not just `{plural}`.

**Comment by jaredatch** [comment]
The nonce key generated is "bulk-{plural}". Current only validating against {plural} key which is incorrect.

https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-wp-list-table.php#L1175

**Comment by pippinsplugins** [comment]
@fjarrett Ha, nice timing :D
