### ISSUE TITLE
Referral URL Visits

### ISSUE THREAD

**Issue by chriscct7** [AffiliateWP/AffiliateWP#872]
The Referral URL Visits should have a column for date and time

**Comment by pippinsplugins** [comment]
In the admin?

**Comment by chriscct7** [comment]
No, on the frontend, like on EDD's affiliate page.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by DrewAPicture** [comment]
Added a PR: #1374 

**Before:**

![Old table](http://cl.ly/3j0i3z2z031J/Screen%20Shot%202016-06-25%20at%202.17.02%20PM.png)

**With PR:**

![Visit Date column](http://cl.ly/1z210t18202D/Screen%20Shot%202016-06-25%20at%202.01.50%20PM.png)
