### ISSUE TITLE
Show website address in the affiliate overview

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#873]
> Would it be possible to show the website address in the affiliate overview ? Sometimes the affiliate name is not really clear, so the url should give some more info on this user. The selection to display this could be the same as in the wordpress admin, with a screen options button on the top of that page to display or hide this field ?

https://secure.helpscout.net/conversation/120833428/16942/

**Comment by pippinsplugins** [comment]
:+1:
