### ISSUE TITLE
URLs in Visits table incorrect with pretty permalinks enabled

### ISSUE THREAD

**Issue by ghost1227** [AffiliateWP/AffiliateWP#876]
While working on #843, I discovered that with pretty permalinks enabled for affiliate URLs, the visits table displays landing pages inclusive of the ref variable as shown below:

![](http://cloud.section214.com/image/0I0O102F0v1z/Image%202015-10-05%20at%206.56.48%20PM.png)

Without pretty permalinks, the `?ref=x` query variable is removed before it is displayed. This is handled in the `includes/class-visits-db.php` file through the following line:

`$data['url'] = remove_query_arg( affiliate_wp()->tracking->get_referral_var(), $data['url'] );`

Removing the query arg this way doesn't work with pretty permalinks, so we'll have to find another way to handle it or add a check for pretty permalinks and strip the ref some other way.

**Comment by ghost1227** [comment]
> get_query_var() only retrieves public query variables that are recognized by WP_Query. This means that if you create your own custom URLs with their own query variables, get_query_var() will not retrieve them

**Comment by pippinsplugins** [comment]
We'll need to explode the URL if no query arg is found that matches the referral variable and then look to see if any of the URL pieces match the query var.

**Comment by ghost1227** [comment]
That's the only place I see that matches that particular var. I should note that we're never actually defining that as a query var... which is why remove_query_arg isn't working.

**Comment by ghost1227** [comment]
Though, since that's a configurable variable, I'm not sure how feasible defining it would be.

**Comment by pippinsplugins** [comment]
It's intentionally not defined as a query var.

**Comment by ghost1227** [comment]
So then if no query arg is found, explode the URL, check the pieces, and if one matches the query var, remove it and the following piece?

**Comment by pippinsplugins** [comment]
Yep!

**Comment by ghost1227** [comment]
@pippinsplugins dunno if you're going to like how i did it, but that PR fixes it.

**Comment by ghost1227** [comment]
@pippinsplugins Updated unit tests

**Comment by pippinsplugins** [comment]
@ghost1227 We'll include it in 1.8
