### ISSUE TITLE
Log in and registration form share same field IDs

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#884]
When `allow registration` is enabled the affiliate area shows a login and registration form. When they are both shown, the field IDs of the `username` and `password` fields between the 2 forms are identical. If you click the `username` or `password` label on the login form, it jumps you up to the username or password field of the registration form. 

We should make sure the IDs are unique.

**Comment by pippinsplugins** [comment]
@sumobi Could you test this one to make sure none of our CSS is now broken?

**Comment by sumobi** [comment]
will do

**Comment by ghost1227** [comment]
@pippinsplugins @sumobi I checked the CSS and there's noting explicitly applied to that ID.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
:+1:
