### ISSUE TITLE
Deleting own affiliate account is unintuitive

### ISSUE THREAD

**Issue by ghost1227** [AffiliateWP/AffiliateWP#893]
If you select to delete your own affiliate account, it still displays the "Delete affiliate's user accounts as well?" checkbox. Of course, if you check it it bypasses the deletion preventing you from removing your own account, but the checkbox probably shouldn't show at all.

**Comment by DrewAPicture** [comment]
New PR against `release/1.8`: #1218

**Comment by DrewAPicture** [comment]
In 7abc1ab, I've reworked the affiliate deletion messaging a bit more thoroughly than originally intended to provide the best possible experience for four possible contexts:

1. Single affiliate being deleted (not current user)
2. Single affiliate being deleted (current user)
3. Multiple affiliates being deleted (not including current user)
4. Multiple affiliates being deleted (including current user)

Screenshots are forthcoming.

**Comment by DrewAPicture** [comment]
1. Single affiliate being deleted (not current user): 

Note the singular-context strings.
![Single affiliate, not current user](http://cl.ly/1Q1L1E1q0U1v/Screen%20Shot%202016-04-20%20at%206.24.32%20PM.png)

2. Single affiliate being deleted (current user):

Note the singular-context strings and missing checkbox.
![Single affiliate, current user](http://cl.ly/3Y0h2j1C3q3F/Screen%20Shot%202016-04-20%20at%206.28.49%20PM.png)

3. Multiple affiliates being deleted (not including current user):

Note the plural-context strings and the visible checkbox
![Multiple affiliates, not current user](http://cl.ly/3B2G062o3m16/Screen%20Shot%202016-04-20%20at%206.29.57%20PM.png)

4. Multiple affiliates being deleted (including the current user)

Note the plural-context strings and the visible checkbox. Also note the addition of the "current user will not be deleted" notice for the checkbox.
![Multiple affiliates, with current user](http://cl.ly/0g3D122q113X/Screen%20Shot%202016-04-20%20at%206.30.43%20PM.png)

**Comment by sumobi** [comment]
@DrewAPicture Thanks for the detailed screenshots.

1. For a single affiliate deletion I wonder if we should also change the title of the page to "Delete Affiliate" and the primary button to "Delete Affiliate", thoughts?

2. I added my own user account (admin) as an affiliate and then tried to delete. I'm still seeing the checkbox: 

    ![screen shot 2016-04-21 at 10 36 18 pm](https://cloud.githubusercontent.com/assets/52581/14706228/82412a2a-0811-11e6-81f1-4c59b960c7e2.png)
![screen shot 2016-04-21 at 10 36 02 pm](https://cloud.githubusercontent.com/assets/52581/14706229/82415c20-0811-11e6-8177-1293b5408700.png)

3. Similar to the above, when I delete the current user (admin) and 2 other affiliates, I don't see the bolded message as per your last screenshot:

    ![screen shot 2016-04-21 at 10 37 41 pm](https://cloud.githubusercontent.com/assets/52581/14706272/c2cc71bc-0811-11e6-9e62-40b6f9bcba00.png)

**Comment by DrewAPicture** [comment]
@sumobi:
> For a single affiliate deletion I wonder if we should also change the title of the page to "Delete Affiliate" and the primary button to "Delete Affiliate", thoughts?

I took a look at the core flow for deleting users and one small change to the proposed approach here would do it. Essentially, the page title always remains "Delete Users", but the button text is more generic to the number, "Confirm Deletion". Sneaky, but useful.

Mostly I worry about adding too many strings for the same purpose but merely based on singular vs plural. Doing it in direct help text vs fixture text provides a reasonable balance.

![Core delete users](http://cl.ly/150d0k2S3E0C/Screen%20Shot%202016-04-21%20at%209.44.49%20AM.png)

![Core delete user](http://cl.ly/1602360F1A3o/Screen%20Shot%202016-04-21%20at%209.41.26%20AM.png)

> I added my own user account (admin) as an affiliate and then tried to delete. I'm still seeing the checkbox:
> Similar to the above, when I delete the current user (admin) and 2 other affiliates, I don't see the bolded message as per your last screenshot:

Hmm, that's perturbing. Let me look into it further.

**Comment by DrewAPicture** [comment]
OK, I finally figured out what was going on. Turns out I was trying to query for affiliates by ID which isn't supported in `get_affiliates()` currently.

I've submitted #1221 to add the ability to query for specific affiliate objects by ID.

In the meantime, I've adjusted the query in 87aa5ea to grab affiliates by ID.

@sumobi Please retest :)

**Comment by michaelbeil** [comment]
Looks good here. 
![screen shot 2016-04-21 at 1 34 31 pm](https://cloud.githubusercontent.com/assets/4752949/14720188/d145b3d0-07c5-11e6-93a5-93e695f48db8.png)

Should we change the button from `Delete Affiliates` to `Confirm Deletion`?

I think that would be a good string change.

**Comment by DrewAPicture** [comment]
@michaelbeil You beat me by 5 minutes ;)

The button text was updated in 9d03bc2.

**Comment by michaelbeil** [comment]
Sweet deal.

**Comment by michaelbeil** [comment]
Looks great!
![screen shot 2016-04-21 at 1 58 00 pm](https://cloud.githubusercontent.com/assets/4752949/14720857/185ef8fa-07c9-11e6-8a17-35a186faf525.png)

**Comment by sumobi** [comment]
@DrewAPicture All looks perfect to me

**Comment by DrewAPicture** [comment]
Merged #1218.
