### ISSUE TITLE
Visitor and Referral tables aren't extensible

### ISSUE THREAD

**Issue by ghost1227** [AffiliateWP/AffiliateWP#895]
Right now, the visitor and referral tables aren't extensible. Since we're using a custom database and manually setting up `WP_List_Table`, we can't use the traditional `manage_posts_columns` filter to add columns to the table. We should add filters to allow extending these tables (RE: https://github.com/affiliatewp/AffiliateWP/issues/154).

**Comment by pippinsplugins** [comment]
Let's fix that.
