### ISSUE TITLE
Affiliates cannot be approved

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#902]
Affiliates cannot be approved. Here's after I clicked the "accept" action on the affiliate:

(using latest master)

![screen shot 2015-10-11 at 1 35 56 pm](https://cloud.githubusercontent.com/assets/52581/10414035/37b46a1c-701d-11e5-95b4-05332b2c0266.png)

If I go back to the page, the affiliate is still pending

![screen shot 2015-10-11 at 1 37 33 pm](https://cloud.githubusercontent.com/assets/52581/10414037/494e2f88-701d-11e5-8d46-c02245cc1967.png)

@pippinsplugins are you able to replicate?

**Comment by sumobi** [comment]
I can confirm that affiliate approval was working fine in 1.7.4, can't find a release archive zip for 1.7.5

**Comment by pippinsplugins** [comment]
This is due to the nonce we added to bulk action processing. Same cause as #906

**Comment by michaelbeil** [comment]
Confirmed here as well.
