### ISSUE TITLE
Affiliate ajax user search pops up again after selecting affiliate

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#903]
The affiliate ajax user search pops up again, after selecting the affiliate. It shouldn't pop up again when an affiliate has been selected

Video of issue:
https://cloudup.com/c1e3ZPAMmSp

![screen shot 2015-10-11 at 2 31 03 pm](https://cloud.githubusercontent.com/assets/52581/10414218/bb80bf10-7024-11e5-8cb2-1b9187f2fb75.png)

**Comment by ghost1227** [comment]
@sumobi This could be tied in to the issue on switching to Select2

**Comment by sumobi** [comment]
:+1: https://github.com/affiliatewp/AffiliateWP/issues/754

**Comment by zackkatz** [comment]
Yeah, really annoying issue. :+1: on #754 !!!

**Comment by pippinsplugins** [comment]
I'm going to fix this for now. It's a small fix whereas #754 is pretty extensive.

**Comment by sumobi** [comment]
Sounds good to me

**Comment by DrewAPicture** [comment]
Added a PR with a slightly different approach than simply attempting to fix the magically-reappearing-dialog: #1250

**Comment by pippinsplugins** [comment]
@DrewAPicture Excellent! I've never seen how to extend the autocomplete in core. Love it :)

**Comment by pippinsplugins** [comment]
Works great here.

@sumobi please test once.

**Comment by michaelbeil** [comment]
Adding affiliates and referrals is not working with this current implementation. @DrewAPicture is investigating further.

**Comment by DrewAPicture** [comment]
@michaelbeil Adding referrals and affiliates hould be working on the latest revision of `issue/903`.

**Comment by ramiabraham** [comment]
Works 💯  here

**Comment by michaelbeil** [comment]
Works wonderfully 🎉 .

**Comment by pippinsplugins** [comment]
Oh, need to check that filtering visits works.

**Comment by DrewAPicture** [comment]
> Oh, need to check that filtering visits works.

Looks like it.

**Comment by DrewAPicture** [comment]
Merged #1250.
