### ISSUE TITLE
Campaign Names not being recorded

### ISSUE THREAD

**Issue by wordmaid** [affiliatewp/AffiliateWP#907]
Campaign names not showing after multiple tests. Was testing a customer’s ticket using various campaign names and noticed that campaigns were correctly shown as converted, but not by name. It shows a “None set” campaign name and lumps all campaigns together. 

Different campaigns: https://cloudup.com/ctAgHKo3IBR
"None set": https://cloudup.com/cUULr2B_hPG

Tried using various URL formats and another test site, and still didn’t work. Could be broken?

**Comment by sumobi** [comment]
:+1: replicated issue

**Comment by sumobi** [comment]
@pippinsplugins the cookie that stores the campaign name is not set
