### ISSUE TITLE
Change default referral status of gravity form from pending to unpaid

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#914]
When a gravity form is submitted (not a product form), the default referral status is `pending`. Just like other integrations, this should be created with a status of `unpaid`.

**Comment by pippinsplugins** [comment]
I've made it so that forms with a price of `0` automatically mark the referral as paid.

**Comment by sumobi** [comment]
:+1: Good idea. I think you meant "unpaid"

**Comment by pippinsplugins** [comment]
Yes.
