### ISSUE TITLE
"Credit last referrer" option breaking referrals, generating multiple visit IDs

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#915]
So far there are 3 support tickets related to this:
https://secure.helpscout.net/conversation/130952542/19134/
https://secure.helpscout.net/conversation/131147259/19196/
https://secure.helpscout.net/conversation/131144914/19193/

Here's a summary of 2 scenarios where it fails:

## Scenario 1
When the customer uses an affiliate's ID and then moves between pages, the visit ID eventually becomes `-2`. If you stay on the same page and refresh each time, a new visit is stored in the DB. The referral is still created in my testing however since the visit ID changes to `-2`, the visit is not updated to show as converted. The affiliate ID remains intact (unlike scenario 2 below).

## Scenario 2
A customer uses an affiliate's referral URL, lands on the homepage, then registers as a WP user. The affiliate ID is wiped from the cookies when visiting the WP user registration page, and then coming back to the site. Since the affiliate's ID is wiped, no referral is created when the customer purchases. Like scenario 1 above, the visit ID also changes to `-2`.

___

### Steps to reproduce scenario 1

- MS installation
- `Credit Last Referrer` enabled
- EDD integration (but also broken on WooCommerce)
- logged in or logged out user

1. Make sure `Credit Last Referrer` is enabled from the settings
2. Use an affiliate's referral URL to the site homepage (could be any page) and a visit will be created as usual. Note the visit ID set in the `affwp_ref_visit_id` cookie.
3. Refresh the current page. The visit ID increments by `1`. If you keep refreshing, it keeps incrementing by `1` and more and more visits are stored in Affiliates -> Visits.
4. Click to go to another page, the visit ID increments again by 1 again. Refresh that page and the visit now changes to `-2`. Since the visit ID changes to `-2`, when the referral is generated, it doesn't show the visit as converted.

### Steps to reproduce scenario 2

- Single site installation:
- Using EDD integration
- `Credit Last Referrer` enabled
- Logged out user 

1. Use an affiliate's referral URL to the site homepage and a visit will be created as usual. Note the visit ID set in the `affwp_ref_visit_id` cookie.
2. Add /wp-login.php?action=register to the URL to simulate going to register as a user
3. One the WP registration screen, click the "Back site" link and the bottom
4. Look at the cookies and you'll see that the `affwp_ref`cookie has been removed. The `affwp_ref_visit_id` cookie shows another incremented visit ID until you click to go to another page, at which point it then changes to `-2`.

Moving around pages also increments the visit ID as per the other scenario and it eventually becomes `-2`.

**Comment by pippinsplugins** [comment]
I'll dig into this later this week.

**Comment by pippinsplugins** [comment]
@sumobi can you test that PR?

**Comment by michaelbeil** [comment]
I am seeing everything clear on MS, EDD, and PR branch. `affwp_ref` 1 was replaced by by `affwp_ref` 2 and a conversion took place, wtith the `affwp_ref_visit_id` increasing, until after checkout it changed back to -2. Refreshes show, but so does the convesrion: http://beil.io/wA9v

**Comment by sumobi** [comment]
@pippinsplugins so far so good, just tested scenario 1 and the visit ID no longer increments or changes to -2. Referral is correctly generated

**Comment by sumobi** [comment]
@pippinsplugins Just tested the first scenario on a single site installation (double checked I had the updated code) and when using the referral link on the site homepage it still has the same issue. After using the referral link you can refresh again and the visit ID stays the same, but if you then refresh again and again it creates new visit IDs.

**Comment by sumobi** [comment]
@pippinsplugins Oh I know why, my single site test doesn't have script debug enabled :+1: let's try again

**Comment by sumobi** [comment]
There we go, all working fine so far, I'm going to keep testing but looks like we'll be able to close this one out soon. @michaelbeil I didn't see the visit change to -2 after checkout for me, can you replicate each time?

**Comment by pippinsplugins** [comment]
Woot.

**Comment by michaelbeil** [comment]
Not near my comp right now, so if all is passing for you and @pippinsplugins, then we should be good.

**Comment by sumobi** [comment]
@pippinsplugins opening this again. Wrote a massive comment and then the answer struck me in the face. We forgot to apply the changes here to the minified files.

Can replicate the issues in this issue by turning off `SCRIPT_DEBUG` in v1.7.8 which should have fixed it.

**Comment by pippinsplugins** [comment]
Sigh . . . fixed.
