### ISSUE TITLE
404 pages on referral URLs when AffiliateWP deactivated/activated

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#917]
We seem to have a high number of tickets about 404 errors when using pretty affiliate URLs. One instance where this can be replicated is when AffiliateWP is deactivated and then activated again - the rewrite rules are lost and the page 404s. Using WooCommerce to test but I've replicated with EDD also.

Steps to replicate:

1. go to a product page in WooCommerce such as http://affwp.dev/product/product-one/ref/1/
2. deactivate AffiliateWP
3. activate AffiliateWP
4. refresh the product page and it shows `Oops! That page can't be found` 

Visiting Settings -> Permalinks fixes the issue and the page can be found with referral variable intact. if we can fix this I'm sure it will bring down the number of 404 tickets.

**Comment by pippinsplugins** [comment]
We should regenerate rewrites at the following points:
- on activation
- anytime the referral var is changed
- perhaps auto detect when certain plugins (like WooCommerce) are activated and the refresh again

**Comment by pippinsplugins** [comment]
@sumobi Please test this on `issue/917`

Note: I've made it so that our rewrites get flushed everytime _our_ settings are saved. It is now more reliable to save our settings screen than to save the permalinks screen.

**Comment by sumobi** [comment]
@pippinsplugins It flushes fine when saving the affwp settings. Were you going to make it so it flushes on activation as per above? If I deactivate/activate AffiliateWP the issue persists.

**Comment by pippinsplugins** [comment]
It does flush on activation already.

**Comment by sumobi** [comment]
hmm didn't work for me, still had 404 page. Will try again

**Comment by sumobi** [comment]
@pippinsplugins tried EDD and WC URLs, after deactivating and activating they show as 404 pages still. Only saving affwp works

**Comment by pippinsplugins** [comment]
That's what I found as well. I'm not sure that's a problem really though. Resaving permalinks invokes the WooCommerce / EDD rewrites to update. Saving our settings does only our rewrites.

Any opposition to marking as solved and always asking customers to save our settings?

**Comment by sumobi** [comment]
@pippinsplugins I'm fine with that. I guess I'm not understanding why when AffiliateWP is activated we can't just flush the rewrite rules to fix the 404 page. Is it because we can't do both commands in a single go? activate + flush

**Comment by pippinsplugins** [comment]
Rewrite mysteries?

Honestly I don't really know.

**Comment by sumobi** [comment]
There are clearly forces here beyond our control
