### ISSUE TITLE
Pretty affiliate URLs don't work on some exchange pages

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#920]
Pretty affiliate URLs don't work on some exchange pages. Here's a list of exchange's URLs:

![screen shot 2015-10-21 at 4 36 28 pm](https://cloud.githubusercontent.com/assets/52581/10627085/e802acac-7811-11e5-97d6-92dae946761d.png)

`/store` for example does not work:

![screen shot 2015-10-21 at 4 35 06 pm](https://cloud.githubusercontent.com/assets/52581/10627094/fa057132-7811-11e5-848f-df33fca908c1.png)

![screen shot 2015-10-21 at 4 35 15 pm](https://cloud.githubusercontent.com/assets/52581/10627100/01566c84-7812-11e5-8513-64594f875109.png)

Flushing permalinks does not help. @pippinsplugins can you replicate?

`/account` is another that won't work. A single product page works fine.

**Comment by pippinsplugins** [comment]
Probably related to our other pretty permalink issues. Will dig in asap.

**Comment by sumobi** [comment]
:+1:

**Comment by sumobi** [comment]
/account works
/store works
/store/cart works
/store/checkout works
/account/profile works
All other account pages work

@pippinsplugins The only one that doesn't work for me is /account/log-in. It loads the hello world post whether logged in or not.

![screen shot 2015-10-24 at 3 38 18 pm](https://cloud.githubusercontent.com/assets/52581/10708454/4e7bc6d0-7a65-11e5-8ddc-3ecb9b7b263e.png)

**Comment by pippinsplugins** [comment]
Only when referral var is set?

**Comment by sumobi** [comment]
yup

**Comment by pippinsplugins** [comment]
@sumobi Turns out the login page not working is an iThemes Exchange bug, at least I think it is.

Would you be opposed to me just not registering a pretty rewrite for that one page? While the rewrite won't work, nor tracking on that page (super rare any way), at least it will show properly.

**Comment by sumobi** [comment]
@pippinsplugins I'm fine with that. Only had 1 customer that specifically wanted to use a referral link on that page.

**Comment by pippinsplugins** [comment]
K. They can still use non-pretty URLs.
