### ISSUE TITLE
How to use add_error() on the affiliate dashboard to display a validation result when updating custom affiliate settings fields

### ISSUE THREAD

**Issue by Olsm** [AffiliateWP/AffiliateWP#922]
I have added a custom field to registration and the affiliate dashboard settings tab.

For displaying the error during the affiliate registration I am using this:
affiliate_wp()->register->add_error

But this does not work for the affiliate dashboard.

So, is there a way to add validation errors on this page?
Or can you add this to the next version like for registration. 
For example: affiliate_wp()->dashboard->add_error

**Comment by pippinsplugins** [comment]
@Olsm Are you performing a redirect after adding the error?

**Comment by Olsm** [comment]
I am not sure I understand your question.

No, I only added the error with affiliate_wp()->register->add_error.
On registration this works fine, but nothing happens on affiliate dashboard settings tab.

Where should we redirect to on the settings page?
The user should stay on the settings page and display an error when the validation for the field fails.

**Comment by pippinsplugins** [comment]
Where did you add it?

**Comment by Olsm** [comment]
I customized this example: https://gist.github.com/sumobi/1b0a8a87e274e69bca68#file-gistfile1-php-L50
and added these hooks in addition to affwp_process_register_form:
add_action( 'affwp_update_profile_settings', 'affwp_custom_process_register_form');
add_action( 'affwp_update_affiliate_profile_settings', 'affwp_custom_process_register_form');

The validation only works on the registration page, not in affiliate dashboard.

**Comment by pippinsplugins** [comment]
Where on the affiliate dashboard would you expect an error to show, when updating the profile settings?

**Comment by Olsm** [comment]
Like on the registration page where you reload the page with a red error on top should be sufficient.

**Comment by michaelbeil** [comment]
We have added better error handling since this issue was opened, so I am wondering if we should close this out. 

@Olsm is this still an issue?

**Comment by pippinsplugins** [comment]
Let's go ahead and close. Re-open if you disagree.
