### ISSUE TITLE
Notice "Your affiliate profile has been updated" does not go away after saving settings in affiliate dashboard

### ISSUE THREAD

**Issue by Olsm** [affiliatewp/AffiliateWP#924]
When affiliates save settings in the affiliate dashboard, they get the notice "Your affiliate profile has been updated". When clicking on other tabs in the dashboard, this notice is still there. The parameter in the url is not removed: affiliate-area/?tab=settings&affwp_notice=profile-updated.

If affiliate go to other page on the website, then back to affiliate dashboard, or remove the "&affwp_notice=profile-updated" parameter from the url, the notice disappears.

**Comment by pippinsplugins** [comment]
We'll get that fixed!

**Comment by zackkatz** [comment]
:+1:
