### ISSUE TITLE
Add Forms tab to settings

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#931]
We're discussing the possibility of adding a "forms" tab to the settings page. For now we should add a checkbox that enables/disables the website URL field. Some site owners have told us that their affiliates do not typically have a website. 

We could also add some options to make certain fields required/not required.

Anything else?

**Comment by pippinsplugins** [comment]
We could also make promotional methods have an option.

**Comment by worldtravlr** [comment]
One thing we look for with affiliates is social reach and newsletter subscribers as we have found both of those and most importantly newsletter subscribers to be a good indicator of how high impact that affiliate might be.  Currently we just use gravity forms integration for our affiliate application as it allows a lot more options and is more customizable for our needs, but social followers/newsletter subscriber might be a good question to as and if you are going to add promotional method options as a dropdown or checkboxes, you could make the number asks conditional so they would only show if the affiliate check Facebook, Twitter, Newsletter, etc.  This may be getting to robust and code heavy for what is mainly meant to be an affiliate plugin and is something handled by the Gravity & Ninja Forms integrations if desired, but just some ideas in case they help.

**Comment by pippinsplugins** [comment]
Excellent idea @worldtravlr

**Comment by wordmaid** [comment]
Another customer request to hide the website URL field on the registration form. This will be so awesome. :+1: 

Ref: https://secure.helpscout.net/conversation/136009447/20459/

**Comment by sumobi** [comment]
Thinking about this some more...

If we're going to have a "forms" tab we should list out all the current fields of the default form. It doesn't feel right having a new tab for just a few options or even less.

Some fields such as "Username" will always be required, but we should still list it and either grey it out, or say that it cannot be disabled for X reason. We finally do something similar with the registration form when the user is logged in to make it clearer.

The forms tab could look something like the below. You would enable or disable options as required. Note how the required fields are already pre-selected, based on how the form _currently_ works (for backwards compatibility).

Which fields should be required for the affiliate registration?:

- [X] Your Name
- [X] Username
- [X]  Account Email
- [ ] Payment Email
- [X] Website URL
- [ ] How will you promote us?
- [X] Password
- [X] Confirm Password

The above means that we need a way to enable options by default when AffiliateWP is first installed. I don't think this is currently possible. We usually turn it around and add "Disable this field" options. I don't think this is the best approach here. For backwards compatibility we should keep everything exactly the same.

BTW we should change the error message for "Invalid email" to "Invalid account email"

Going a bit deeper, we could also add options to remove fields completely so customers don't have to modify the template file. Adding fields however will only be possible through the pro add-ons, or through the template file.

If the site owner chose to remove the password fields for example, we could automatically generate a password for the affiliate, or more preferably, send them an email so they can set it themselves. If the username field isn't present on the form, we can generate the username from the email address. Less friction for the initial sign up.

As much as it would be awesome to include social follower counts etc (as per Griffin's comment above) we know that once we add this, we'll get requests to add more fields and then it becomes a mess. We might as well build an entire form builder, but this is best left to an actual form plugin (hence the pro add-ons).

**Comment by pippinsplugins** [comment]
I like the idea of a checkbox for each field.

**Comment by sumobi** [comment]
Related: https://github.com/AffiliateWP/AffiliateWP/pull/1855

**Comment by sumobi** [comment]
Closed in favour of https://github.com/AffiliateWP/AffiliateWP/issues/1443
