### ISSUE TITLE
Simplify URL Visit Column

### ISSUE THREAD

**Issue by TimothyBJacobs** [AffiliateWP/AffiliateWP#933]
In the front-end, it'd be great if a more simple URL could be displayed. This would be by stripping the domain and the referral arg.

Before:
`http://www.mysite.com/product/product-name/ref/username`

After:
`/product/product-name/`

All of that extraneous info means that the column almost necessarily wraps, and is difficult to understand.

Thoughts?

**Comment by TimothyBJacobs** [comment]
Related to #876. But this would only be on the front-end, and would strip the domain name as well.

**Comment by pippinsplugins** [comment]
I like this but I do wonder what the impact would be on less technical users.

For someone who is not technically versed in the idea of `slugs`, does `/product/product-name` mean the same thing as `http://www.mysite.com/product/product-name/`?

**Comment by TimothyBJacobs** [comment]
Would maybe marking it as a link make it more clear?

A reference would be Gravity Forms' entry view.
<img width="300" alt="gravity forms entry embed url" src="https://cloud.githubusercontent.com/assets/3460448/10762016/7e5c2b92-7c9a-11e5-8faa-00765a6563f7.png">

**Comment by pippinsplugins** [comment]
Ah yes, that is nice.

I'd note be opposed to that at all.

We could also make the title attribute the complete URL so that it shows when hovering over.

**Comment by TimothyBJacobs** [comment]
Cool, I'll work up a PR.

**Comment by pippinsplugins** [comment]
Awesome, thanks!

**Comment by TimothyBJacobs** [comment]
I'm not sure what the branching policy is here, but could #877 be merged into develop or a release branch for 1.8? It provides `affwp_sanitize_visit_url()` which would be a helpful start.

**Comment by pippinsplugins** [comment]
We need to get #877 merged in first but I have not tested it yet so I don't want to merge until I have.

**Comment by TimothyBJacobs** [comment]
Ok, sounds good.

**Comment by pippinsplugins** [comment]
@TimothyBJacobs #877 was merged into master!

**Comment by TimothyBJacobs** [comment]
Before
![shortened visits before](https://cloud.githubusercontent.com/assets/3460448/13136058/42fe497e-d5e4-11e5-8bbf-17f7f38b93b6.png)

After
![shortened visits after](https://cloud.githubusercontent.com/assets/3460448/13136063/47fcc78e-d5e4-11e5-8233-f0ae50bf7e81.png)

**Comment by pippinsplugins** [comment]
I love this!

**Comment by TimothyBJacobs** [comment]
Awesome!

**Comment by michaelbeil** [comment]
This is really nice @TimothyBJacobs.

**Comment by TimothyBJacobs** [comment]
Thanks!

**Comment by DrewAPicture** [comment]
Moved PRs from #1109 to #1217 to diff against `release/1.8`.

**Comment by DrewAPicture** [comment]
After checking out #1217 out a little bit, some notes:
* Should we not also apply this shortening effect to those Referring URLs when they're actually URLs?
* Title attributes in links aren't great for accessibility, but in lieu of a better suggestion, that might be the best option to display the full URL for the time being
* @TimothyBJacobs In unit tests dataProvider you created, what is the significance of the `privateVar` query var and is there logic somewhere that precludes it from displaying the human-readable form?

**Comment by DrewAPicture** [comment]
@TimothyBJacobs: Nevermind on the `privateVar` stuff, I see it now. Essentially if it is an unregistered query var, it isn't part of the whitelist.

**Comment by DrewAPicture** [comment]
@pippinsplugins Gave this a once over and added some minor accessibility improvements on the advice of a core a11y team member. Looks good.

**Comment by pippinsplugins** [comment]
Let's merge once unit tests pass.

**Comment by michaelbeil** [comment]
FWIW, all checks out great here and all unit tests passed.

**Comment by michaelbeil** [comment]
![screen shot 2016-04-25 at 2 54 55 pm](https://cloud.githubusercontent.com/assets/4752949/14796952/b4acdab8-0af5-11e6-99bc-477c078b27b2.png)

**Comment by pippinsplugins** [comment]
Merged!
