### ISSUE TITLE
Should we make the affiliate_login shortcode redirect to affiliate area by default?

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#934]
A lot of customers open support tickets about seeing a white page when an affiliate logs in and they always ask how can an affiliate be redirected to the affiliate area instead. The solution is to add the redirect parameter and link it to the affiliate area. 

The reason we don't automatically redirect is in case the site owner wants to keep the affiliate on the same page and show some kind of content using the [affiliate_content] shortcode. I'm not sure if anyone actually does this. Should we leave as is, or redirect an affiliate by default to the affiliate area? Any other solution to reduce the number of support tickets?

**Comment by pippinsplugins** [comment]
I'm all for making the default redirect to the affiliate area.

How about we update the `redirect` parameter to accept several options:

1. `referrer` - This would send them back to the page they were on before visiting the registration page
2. `current` - This would send them back to the same page
3. Any URL

This could also apply to the log in form.

**Comment by sumobi** [comment]
@pippinsplugins I like that idea

**Comment by pippinsplugins** [comment]
Tagged for 1.8

**Comment by worldtravlr** [comment]
Cool! :+1:

**Comment by sumobi** [comment]
Calling all testers

**Comment by michaelbeil** [comment]
On branch `issue/934`: Both login and registration redirect to the affiliate area accordingly. 

:cake:

**Comment by DrewAPicture** [comment]
Tested #1143 and can confirm the following scenarios:

`[affiliate_login]`: Redirects to Affiliate Area page
`[affiliate_login redirect="current"]`: Redirects to the page with the shortcode on it
`[affiliate_login redirect="referrer"]`: Redirects to the referrer that sent me to the login page
`[affiliate_login redirect="https://affiliatewp.com"]`: Redirects to the given URL

`[affiliate_registration]`: Redirects to Affiliate Area
`[affiliate_registration redirect="current"]`: Redirects to the page with the shortcode on it
`[affiliate_registration redirect="referrer"]`: Redirects to the referrer that sent me to the registration page
`[affiliate_registration redirect="https://affiliatewp.com"]`: Redirects to the given URL.

:+1:

**Comment by pippinsplugins** [comment]
Merged.
