### ISSUE TITLE
pmpro doesn't set discount_code

### ISSUE THREAD

**Issue by curtismchale** [AffiliateWP/AffiliateWP#937]
Looking at add_pending_referral there is not discount code set in the `$order` variable in PMP. That means that AffWP throws errors at checkout as it tries to get part of an object that was never set in the first place.

The `$_REQUEST` at the time does have a `discount_code` parameter (if the user used a code that is). The closest things that PMP seems to pass is the `certificate_id` though I'm still trying to figure out how it defines that parameter since even using a discount code with just base PMP installed and using a discount code still never has that parameter set.

As it is, I don't see how AffWP is ever going to catch an affiliate discount code as codes are used in PMPro.

**Comment by pippinsplugins** [comment]
I wonder if it varies for each gateway. When first merged in, I believe I tested it with Stripe.

@curtismchale which gateway are you testing with?

**Comment by curtismchale** [comment]
Stripe testing gateway currently. I don't actually see anything in the code that sets this at all. It appears to be coming from an SQL query where you get all the table columns back as objects and none of the table columns have this set.

Though like I said, $_REQUEST does have the discount_code param

**Comment by pippinsplugins** [comment]
Will look closer at it for 1.8

**Comment by pippinsplugins** [comment]
Feedback from Jason: https://cloudup.com/cdfGe4GpIO8
