### ISSUE TITLE
Create an add-on for automatic coupons

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#938]
> I've had a think and a look around a few plugins. I now think all I really need to be able to do, is to give an automatic discount to a user if they have come to the site via an affiliate link.
 
> Is this possible with AffiliateWP and WooCommerce coupons? If not, I could put a plugin together if you can tell me the underlying process involved (i.e. is there a 'referral' action in AffiliateWP that I could hook into to apply a discount). 

https://secure.helpscout.net/conversation/133279225/19735/

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/165018833/26453/?folderId=205524

**Comment by sumobi** [comment]
https://github.com/AffiliateWP/AffiliateWP/issues/426

**Comment by michaelbeil** [comment]
In favor of 426, I am gonna close this out.
