### ISSUE TITLE
Add affiliate first and last name to exported affiliate .csv file

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#942]
Should we add the affiliate's first and last name to the exported affiliate CSV file? This seems like it would be handy when exporting affiliates to MailChimp etc.

Gist:
https://gist.github.com/sumobi/10dba51d2155c0af69a8

**Comment by michaelbeil** [comment]
oh, yes! makes sense.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
Looks like my clone made a code snippet for this:
https://gist.github.com/sumobi/10dba51d2155c0af69a8

**Comment by pippinsplugins** [comment]
@sumobi @michaelbeil ready for testing.

**Comment by michaelbeil** [comment]
Works well. Ready to be merged.
