### ISSUE TITLE
Better website URL field validation

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#947]
PR: #1437

The validation on the website URL field is kinda sucky. If you enter something like `oigfdjkg` it doesn't ask you to enter it again.

**Comment by pippinsplugins** [comment]
@sumobi ready for some testing.

**Comment by sumobi** [comment]
@pippinsplugins 

My test URL of `oigfdjkg` passed verification and I was able to register:

![screen shot 2016-07-16 at 11 40 33 am](https://cloud.githubusercontent.com/assets/52581/16891188/2734bc4c-4b4a-11e6-8fa2-05a42dab5921.png)

It seems it's not firing the JS at all, can't see any validation notices, no JS errors in console.

I cleared cache and double-checked the frontend.js file to see your latest changes. I think we should also have PHP validation of the URL field in addition to JS.

**Comment by pippinsplugins** [comment]
Did you have `SCRIPT_DEBUG` on?

**Comment by sumobi** [comment]
Yep. I also verified that I could see your changes in the JS file so I know it was definitely loaded

**Comment by sumobi** [comment]
Hah, I know why. This issue is for the URL field on the affiliate registration form. You wrote a patch for the URL generator inside the Affiliate Area :)

**Comment by sumobi** [comment]
Tested the `Page URL` field in the affiliate area, works great.

![screen shot 2016-07-18 at 7 34 33 pm](https://cloud.githubusercontent.com/assets/52581/16908320/af42face-4d1e-11e6-8a93-42821d147e78.png)

Let's add a margin top so there's a bit of a gap. I used `10px` for direct link tracking.

**Comment by pippinsplugins** [comment]
Oh .... lol. We might as well add similar validation to both.

**Comment by michaelbeil** [comment]
Works well for the URL generator inside the Affiliate Area.

**Comment by pippinsplugins** [comment]
@sumobi URL validation added to registration form.

**Comment by sumobi** [comment]
👍
