### ISSUE TITLE
Add "current" to URL parameter in [affiliate_referral_url] shortcode

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#949]
@wordmaid has suggested that the [affiliate_referral_url] shortcode should be able to easily support the current page, without having to enter the full URL each time.

Eg: `[affiliate_referral_url url="current"]`

This would make it easier for an admin to place the shortcode on various pages, and also means that if the URL was later changed, the shortcode wouldn't need to be updated.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
I'd actually propose we make the current URL the default.

**Comment by sumobi** [comment]
@pippinsplugins that was my initial thought but how can we provide backwards compatibility for those already using [affiliate_referral_url]?

**Comment by ramiabraham** [comment]
Could have it set as the current url by default - not being dependent on specifying `current` as the 'url'. If 'url' is empty, use current url.

**Comment by pippinsplugins** [comment]
@ramiabraham problem is that doing so would make all existing shortcodes that don't have a URL specified change from homepage to current URL.

**Comment by pippinsplugins** [comment]
Let's re-vote on this please. Two options:

A. Make the shortcode default to the current page's URL. This could result in site's changing from showing the home page to showing the current URL. Not a major problem but might result in some flack.

B. Add a `url="current"` parameter to the shortcode. This is the least offensive to backwards compatibility but is a non-intuitive usage that I really don't like.

**Comment by michaelbeil** [comment]
Seems like A is the better option as we can prepare for any support tickets.

**Comment by sumobi** [comment]
A

**Comment by pippinsplugins** [comment]
Ready for testing.

**Comment by sumobi** [comment]
@pippinsplugins works great for me
