### ISSUE TITLE
Integrate affiliate_area with the Woo my-accounts page

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#950]
> how can I integrate the affiliate-area into my woocommerce my-accounts page into a new tab?

Could be great to add this feature to a future version of AffiliateWP or as an add-on.

https://secure.helpscout.net/conversation/136519784/20603/

**Comment by TimothyBJacobs** [comment]
This is how I did it for my site using Exchange.

![screen shot 2015-11-05 at 12 30 19 pm](https://cloud.githubusercontent.com/assets/3460448/10976304/0c9c19b0-83b9-11e5-92de-d19b6e996170.png)
![screen shot 2015-11-05 at 12 30 28 pm](https://cloud.githubusercontent.com/assets/3460448/10976305/0c9cc90a-83b9-11e5-99d7-691472f241a1.png)

**Comment by pippinsplugins** [comment]
I like that.

**Comment by sumobi** [comment]
Closing in favor of https://github.com/AffiliateWP/AffiliateWP/issues/2108
