### ISSUE TITLE
Add a description to our export-referrals class

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#952]
> Is there a way to export an affiliate's referrals and actually show the description for what they received commission on? When I do a general export under tools > export it just says "membermouse" under the context column and nothing else. However in the admin under the referrals page it actually says what they received commission on. The export report isn't very helpful. 

Currently we have an array that includes affiliate ID, email, payment email, amount, currency, campaign, reference, context, status, and date. May be neat to show a description of the purchase/referral in the export file.

https://secure.helpscout.net/conversation/136882837/20715/

**Comment by pippinsplugins** [comment]
:+1:
