### ISSUE TITLE
PMP hijacks "Lost Password?" link

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#953]
When a user attempts to click the "Lost Password?" link (http://beil.io/1bvp2), they are taken to the PMP member page (http://beil.io/18YgK).

>Testing the login page on my site and when I hover over the Forgotten Password link you can see the hyperlink at the bottom left it is pointing to. This automatically is pointing to a different plug in (a membership plugin) and when the link is actually clicked it goes to the membership home page.

**Comment by pippinsplugins** [comment]
Milestoning for 1.9 to see if we can fix it.

**Comment by pippinsplugins** [comment]
This doesn't happen to me. Closing as invalid now. Can re-open if we have additional reports or someone else replicates it.
