### ISSUE TITLE
Currencies aren't in alphabetical order

### ISSUE THREAD

**Issue by nathanrice** [affiliatewp/AffiliateWP#954]
Well, they are, but it's the 3 letter code that is used to alphabetize them. Only problem is that the users selecting a currency don't see that code, they only see the label.

I'd suggest alphabetizing by the label.

**Comment by pippinsplugins** [comment]
I agree.

**Comment by nathanrice** [comment]
Cool. I'll work up the PR.

**Comment by pippinsplugins** [comment]
Awesome, thanks!

**Comment by pippinsplugins** [comment]
Thanks @nathanrice !
