### ISSUE TITLE
Add affiliate username to the Affiliates screen

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#959]
It would be very useful to see the affiliate's WordPress username on the main Affiliates screen. By showing the username, admins won't have to click "Edit" on every affiliate to find a username they may be looking for. Also, two or more affiliates may have the same name/display name which makes it hard to find the correct affiliate. What do you think about adding another column or some way to show this? I realize the columns are pretty tight as it is...

Also, when I tried to use the search box on the Affiliates screen and searched for an affiliate's WordPress username, the affiliate didn't come up.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
:+1:

**Comment by pippinsplugins** [comment]
This is done.
