### ISSUE TITLE
Allow search by affiliate username in Affiliates screen

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#960]
Currently it's not possible to search for affiliates by username in the Affiliates screen. If affiliates' usernames are added to this screen, it would be handy to be able to search by username as well (given this is what affiliates are able to use in their referral URLs).

Ref: https://github.com/affiliatewp/AffiliateWP/issues/959

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
:+1:

**Comment by DrewAPicture** [comment]
Added a PR + tests: #1176

**Comment by michaelbeil** [comment]
This works beautifully @DrewAPicture.

**Comment by pippinsplugins** [comment]
Excellent.
