### ISSUE TITLE
WooCommerce - affiliate rate per product variation

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#964]
When a user has one variable product with multiple variations. Each variation is a different price (it is the option between digital and physical products) so those may be a different commission. But on a variable product we do not have the ability to assign a different commision for each variation. 

Could be a good addition with regards to flat rates.

https://secure.helpscout.net/conversation/138634535/21180/

**Comment by pippinsplugins** [comment]
The only time that they *can't* be the same commission is when using flat rates, at least in my opinion.

Great addition, I just don't think it's quite as black and white :)

**Comment by sumobi** [comment]
related: https://github.com/affiliatewp/AffiliateWP/issues/673

**Comment by michaelbeil** [comment]
Correctamundo. Only with flat rates was what I was thinking too. I forgot to mention that above.

**Comment by michaelbeil** [comment]
How did I not noticed that other ticket?

**Comment by pippinsplugins** [comment]
PR with some work on this: #1180

**Comment by pippinsplugins** [comment]
Note: the `Save Changes` box inside of the variation settings does not currently save our new fields, only the main product update button does.

**Comment by pippinsplugins** [comment]
@michaelbeil @sumobi could you both please test this?
![screen shot 2016-08-22 at 5 32 51 pm](https://cloud.githubusercontent.com/assets/1034109/17874004/78d20e04-688e-11e6-93cb-bbdf5fa95fa6.png)

**Comment by michaelbeil** [comment]
This is working wonderfully. 

If no variable rate is set, the product rate is used, and if no product rate is set, the default rate is used. 

Affiliate > Variable > Product > Default

**Comment by michaelbeil** [comment]
Ok, it seems like there may be a bug with save in the variations tab. After setting a referral rate and saving the changes, the referral rate field is then blank, or the disable referral option is unchecked.

**Comment by michaelbeil** [comment]
Oh, I just reread https://github.com/AffiliateWP/AffiliateWP/issues/964#issuecomment-241571026. Noted.

**Comment by michaelbeil** [comment]
We should note the variation like so: `Product name - variation`

![screen shot 2016-08-22 at 7 49 13 pm](https://cloud.githubusercontent.com/assets/4752949/17876642/9e80922a-68a1-11e6-8b33-9099a522ebd3.png)

**Comment by pippinsplugins** [comment]
Saving works properly now.

**Comment by pippinsplugins** [comment]
Ok this is ready for further testing @michaelbeil @sumobi!

**Comment by sumobi** [comment]
@pippinsplugins As soon as I click on the "variations" tab after setting up attributes I get this error:

```
PHP Notice:  Undefined index: reference in /wp-content/plugins/AffiliateWP/includes/integrations/class-base.php on line 356
```

**Comment by pippinsplugins** [comment]
You broke it.

**Comment by pippinsplugins** [comment]
@sumobi fixed.

**Comment by sumobi** [comment]
@pippinsplugins Works great for me! Tried 3 different variations as individual purchases, and then tried to trick it and purchase them altogether. Commission was calculated perfectly each time, nice work.

**Comment by michaelbeil** [comment]
I still cannot get referral rate changes to save from the variations tab.

**Comment by pippinsplugins** [comment]
@michaelbeil what happens?

**Comment by michaelbeil** [comment]
I save changes and the referral rate is lost.

**Comment by pippinsplugins** [comment]
Which save changes button? The one inside the tab?

**Comment by michaelbeil** [comment]
Yes.

**Comment by pippinsplugins** [comment]
No JS errors?

**Comment by pippinsplugins** [comment]
I just tested again and it's working fine for me.

@michaelbeil are you on the latest version of WooCommerce?

**Comment by pippinsplugins** [comment]
I'm going to merge into `release/1.9`. We can continue to adjust if needed based on Michael's feedback.

**Comment by michaelbeil** [comment]
This is all clear. Note for future self: referral rate will be blank upon save if you disable referrals on a variation.

**Comment by michaelbeil** [comment]
Note to future self: everything works fine and do not panic.
