### ISSUE TITLE
Lifetime Commission referral amount calculated incorrectly, broken iThemes Exchange integration with lifetime referrals

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#965]
The issue/s:

1. Commission amounts in Lifetime Commissions are being incorrectly calculated when an affiliate has a per-affiliate referral rate set. It seems to have been broken since v1.7 of AffiliateWP where there were many changes made to referral rates. So far we have ~3 tickets on this and I expect there to be more.

    The current implementation Lifetime Commissions can be much, much simpler. I rewrote some of the add-on over the weekend so integration classes are no longer needed (yay!). It’s now super reliable since AffiliateWP does all the heavy lifting (as it should), I’m no longer filtering any rates (only 1 affiliate ID) so it should just work. This also means we can now easily support other integrations - Paid Memberships Pro and Gravity Forms integrations are pretty much done.

    I can’t however release a Lifetime Commissions add-on update until we release a new version of AffiliateWP with the PR attached merged.

2. The iThemes Exchange integration in Lifetime Commissions broke lifetime referrals in v1.7.7 due to this PR: https://github.com/affiliatewp/AffiliateWP/pull/908.

You might want to sit down for this, I've touched integration classes and a few key changes were made (luckily so far everything works in my testing):

See this branch for changes so far:
https://github.com/affiliatewp/AffiliateWP/commit/c05e6bccbe4674fe24140134bae63a34c671c869

1. It tidies up the integrations (only main ones for now) so any instance of `$this->affiliate_id` now uses the `get_affiliate_id()` function we already have in the base class:

    https://github.com/affiliatewp/AffiliateWP/blob/master/includes/integrations/class-base.php#L180

    The `affwp_get_referring_affiliate_id filter` is currently pretty useless since all the integrations call `$this->affiliate_id`, bypassing the function and included filter.

    This change allows better flexibility and *shouldn’t* break any existing integrations since they will just use the existing affiliate ID from `$this->affiliate_id`. It only means they won’t yet work with Lifetime Commissions or any other add-on that uses the `affwp_get_referring_affiliate_id` filter:

    https://github.com/affiliatewp/AffiliateWP/blob/master/includes/integrations/class-base.php#L181

2. Where possible, the reference ID is passed to the `get_affiliate_id()` function. This allows Lifetime Commissions to filter the affiliate ID, based on the purchase information, and without having to filter anything else like it did previously. This makes Lifetime Commissions super reliable, and also makes it possible for other add-ons to filter the affiliate ID is more creative ways. The filter now provides the reference number and context in addition to the affiliate ID.

3. In `class-base.php`, the `insert_pending_referral()` function will now use an affiliate ID if it’s been passed in via the `$data` array, otherwise it uses the affiliate ID determined by the `get_affiliate_id()` function. This is for integrations like iThemes Exchange and PMP, where the tracked coupon logic is bundled in the same function as the normal logic for creating a referral. If a tracked affiliate coupon is used, the coupon's linked affiliate ID is now passed into the `insert_pending_referral()` function, and we can make sure that it overrides the affiliate ID if it’s being modified from the `affwp_get_referring_affiliate_id` filter. As we all know, a tracked coupon should override a normal referral, including commissions generated by the Lifetime Commissions add-on.

    The `calculate_referral_amount()` function now also accepts an affiliate ID if passed in, otherwise it uses the affiliate ID determined by the `get_affiliate_id()` function. It also passes this affiliate ID into the `get_product_rate()` function, through the `$args` array. This is so that when the affiliate ID is filtered, the correct referral amounts can be calculated for the new affiliate ID.

4. In each integration class, the affiliate ID is now retrieved from the `get_affiliate_id()` function, putting it to more use. Additionally, the affiliate ID is now passed into the base class’s `calculate_referral_amount()` function as mentioned above. This is so if the affiliate ID is ever changed from within the integrations (IE the affiliate ID from a tracked affiliate coupon) it can retrieve the correct amount of the referral, based on the new affiliate ID. If we don’t do this, the affiliate ID will be changed from the `affwp_get_referring_affiliate_id` filter, but the amount will be calculated based on the original affiliate. Since we included the `affwp_get_referring_affiliate_id` filter, I think it's a good idea we start using it where possible.

5. The `is_affiliate_email()` function now accepts an affiliate ID. This seems counter-intuitive but there’s a good reason for it (and I can’t think of another way to approach this just yet). Since an integration like WooCommerce now gets its affiliate ID from the `get_affiliate_id()` function in the base class (so it can be filtered), the current implementation of `is_affiliate_email()` fails since it currently looks at `$this->affiliate_id` for the affiliate ID, rather than the `get_affiliate_id()` function. Since a tracked coupon changes the affiliate ID in WooCommerce (and others) we need to pass that affiliate ID into the function to check if the email/s matches correctly.

6. And finally, there were some formatting changes.

I’m fairly confident this hasn’t broken any existing integrations, I’ve so far tested all the ones I’ve modified and everything is working as usual (normal referrals, tracked coupons, per-product rates etc) but would certainly love some extra eyes on this.

I’ve started some exhaustive testing in case I really broke something:

## Easy Digital Downloads

- [x] Purchase product where affiliate has per-affiliate referral rate set. Commission should be based on the affiliate’s referral rate.
- [x] Purchase product where affiliate has per-affiliate referral rate set, and product has a per-product referral rate set. Commission should be based on the affiliate’s referral rate.
- [x] Purchase product with per-product referral rate set (no per-affiliate rate set). Commission should be based on the product referral rate.
- [x] Purchase product with no per-product or per-affiliate referral rate. Commission should be based on the global referral rate.
- [x] Purchase product with referrals disabled. No Commission should be recorded
- [x] Purchase using tracked affiliate coupon, while tracking another affiliate. Commission should be awarded to affiliate linked to coupon
- [x] Purchase using tracked affiliate coupon, while not tracking another affiliate. Commission should be awarded to affiliate linked to coupon.
- [x] Purchase using tracked affiliate coupon, and a per-affiliate referral rate. Commission should be awarded to affiliate linked to coupon and also based on their per-affiliate rate.
- [x] Purchase using tracked affiliate coupon and a per-product referral rate. Commission should be awarded to affiliate linked to coupon and also based on the per-product rate (unless per-affiliate rate was set).
- [x] Purchase using the same email address as the affiliate being tracked. Commission should not be awarded
- [x] Credit Last Referrer enabled + purchase using multiple referral links. The last affiliate referred should be awarded the commission

## Easy Digital Downloads + Lifetime Commissions

- [x] Purchase product while linked to an affiliate. Commissions should be awarded to the linked affiliate.
- [x] Purchase product while linked to an affiliate, but tracking another affiliate. Commissions should be awarded to the linked affiliate.
- [x] Purchase product while linked to an affiliate, using a tracked affiliate coupon code. Commissions should be awarded to linked coupon affiliate
___
## WooCommerce

- [x] Purchase product where affiliate has per-affiliate referral rate set. Commission should be based on the affiliate’s referral rate.
- [x] Purchase product where affiliate has per-affiliate referral rate set, and product has a per-product referral rate set. Commission should be based on the affiliate’s referral rate.
- [x] Purchase product with per-product referral rate set (no per-affiliate rate set). Commission should be based on the product referral rate.
- [x] Purchase product with no per-product or per-affiliate referral rate. Commission should be based on the global referral rate.
- [x] Purchase product with referrals disabled. No Commission should be recorded
- [x] Purchase using tracked affiliate coupon, while tracking another affiliate. Commission should be awarded to affiliate linked to coupon
- [x] Purchase using tracked affiliate coupon, while not tracking another affiliate. Commission should be awarded to affiliate linked to coupon.
- [x] Purchase using tracked affiliate coupon, and a per-affiliate referral rate. Commission should be awarded to affiliate linked to coupon and also based on their per-affiliate rate.
- [x] Purchase using tracked affiliate coupon and a per-product referral rate. Commission should be awarded to affiliate linked to coupon and also based on the per-product rate (unless per-affiliate rate was set).
- [x] Purchase using the same email address as the affiliate being tracked. Commission should not be awarded
- [x] Credit Last Referrer enabled + purchase using multiple referral links. The last affiliate referred should be awarded the commission

## WooCommerce + Lifetime Commissions

- [x] Purchase product while linked to an affiliate. Commissions should be awarded to the linked affiliate.
- [x] Purchase product while linked to an affiliate, but tracking another affiliate. Commissions should be awarded to the linked affiliate.
- [x] Purchase product while linked to an affiliate, using a tracked affiliate coupon code. Commissions should be awarded to linked coupon affiliate

Other integration testing to follow… thoughts @pippinsplugins? (see branch here: https://github.com/affiliatewp/AffiliateWP/commit/c05e6bccbe4674fe24140134bae63a34c671c869)

**Comment by sumobi** [comment]
@pippinsplugins here's the new filter in Lifetime Commissions to show you how much simpler it is: https://github.com/affiliatewp/affiliate-wp-lifetime-commissions/blob/issue/28/integrations/class-base.php#L10

**Comment by michaelbeil** [comment]
This is lovely. Perusing all of it in a bit.

**Comment by wordmaid** [comment]
## iThemes Exchange

I've run through iThemes Exchange testing as per the below:

- [x] Purchase product where affiliate has per-affiliate referral rate set. Commission generated should be based on the affiliate’s referral rate.

- [x] Purchase product where affiliate has per-affiliate referral rate set, and product has a per-product referral rate set. Commission generated should be based on the affiliate’s referral rate.

- [x] Purchase product with per-product referral rate set (no per-affiliate rate set). Commission should be based on the product referral rate.

- [x] Purchase product with no per-product or per-affiliate referral rate. Commission should be based on the global referral rate.

- [x] Purchase product with referrals disabled. A $0 referral is generated, and therefore no commission should be recorded.

- [x] Purchase using tracked affiliate coupon, while tracking another affiliate. Commission should be awarded to affiliate linked to coupon

- [x] Purchase using tracked affiliate coupon, while not tracking another affiliate (using no affiliate link). Commission should be awarded to affiliate linked to coupon.

- [x] Purchase using tracked affiliate coupon, and a per-affiliate referral rate. Commission should be awarded to affiliate linked to coupon and also based on their per-affiliate rate (on the total after the discount).

- [x] Purchase using tracked affiliate coupon and a per-product referral rate. Commission should be awarded to affiliate linked to coupon and also based on the per-product rate (unless per-affiliate rate was set).

- [ ] Purchase using the same email address as the affiliate being tracked. Commission should not be awarded. (**Pending this issue:** https://github.com/affiliatewp/AffiliateWP/issues/974)

- [x] Credit Last Referrer enabled + purchase using multiple referral links. The last affiliate referred should be awarded the commission (and their per-affiliate commission rate if set).

**Comment by pippinsplugins** [comment]
Awesome.

@sumobi are you happy with it? If so, I can give it one last look and then merge

**Comment by sumobi** [comment]
@pippinsplugins @wordmaid is testing PMP, I'm having one last comb over + doing some more testing, and then it's all yours.

**Comment by sumobi** [comment]
@wordmaid tested with Gravity Forms and I tested with Ninja Forms - both are still generating referrals. I'm going to assume referrals still work across all integrations and the ones we've touched in this issue.

**Comment by wordmaid** [comment]
## Paid Memberships Pro

PMP testing done, everything seems to be working fine. Checklist below.

- [x] Purchase membership where affiliate has per-affiliate referral rate set. Commission generated should be based on the affiliate’s referral rate.

- [x] Purchase membership with no per-affiliate referral rate. Commission should be based on the global referral rate.

- [x] Purchase using tracked affiliate coupon, while tracking another affiliate. Commission should be awarded to affiliate linked to coupon

- [x] Purchase using tracked affiliate coupon, while not tracking another affiliate (using no affiliate link). Commission should be awarded to affiliate linked to coupon.

- [x] Purchase using tracked affiliate coupon, and a per-affiliate referral rate. Commission should be awarded to affiliate linked to coupon and also based on their per-affiliate rate (on the total after the discount).

- [x] Purchase using the same email address as the affiliate being tracked. System shouldn’t allow you to create an account as email address is taken.

- [x] Credit Last Referrer enabled + purchase using multiple referral links. The last affiliate referred should be awarded the commission (and their per-affiliate commission rate if set).

**Comment by sumobi** [comment]
@pippinsplugins I think I'm ready to call it a day on this, all yours

**Comment by pippinsplugins** [comment]
@sumobi Just one small change. See any reason that would affect anything negatively?

**Comment by sumobi** [comment]
@pippinsplugins that should be fine (I hope) :)

**Comment by sumobi** [comment]
@pippinsplugins see commit above and let me know your thoughts. We need to make the `$reference` available on the `affwp_get_affiliate_rate` filter so we can alter the affiliate's commission rate, based on the purchase. This is so https://github.com/AffiliateWP/affiliate-wp-lifetime-commissions/issues/26 will be possible with the new changes.

**Comment by sumobi** [comment]
Here's an example of how Lifetime Commissions would filter this:
https://gist.github.com/sumobi/679217a56409f3a822b2

**Comment by pippinsplugins** [comment]
@sumobi That looks fine to me.
