### ISSUE TITLE
Add affiliate first and last name, and username to exported Referrals .csv file

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#973]
Following on from https://github.com/affiliatewp/AffiliateWP/issues/942... adding the affiliate's first and last name, and username to the exported referrals CSV file would make it much more useful (so site owners don't have to go searching for email addresses for each affiliate).

**Comment by michaelbeil** [comment]
:+1:

**Comment by sumobi** [comment]
Looks like I made a code snippet some time ago for this: https://gist.github.com/sumobi/10dba51d2155c0af69a8

**Comment by michaelbeil** [comment]
request: https://secure.helpscout.net/conversation/186328375/30930/?folderId=205529

**Comment by sumobi** [comment]
@AffiliateWP/core ready for testing (I have tested).

**Comment by pippinsplugins** [comment]
Looks good.

**Comment by DrewAPicture** [comment]
This needs to be updated for the batch processor.

**Comment by DrewAPicture** [comment]
Actually, nvm. Looks like `Export_Referrals` was created after this was merged so we're good ;)
