### ISSUE TITLE
iThemes Exchange: Affiliate can earn a commission using their own email address when using Guest Checkout

### ISSUE THREAD

**Issue by wordmaid** [affiliatewp/AffiliateWP#974]
Integration: iThemes Exchange

I was helping @sumobi test https://github.com/affiliatewp/AffiliateWP/issues/965 and I noticed when I use the same affiliate email address as the affiliate that I was tracking via cookies, a referral was still created. I also tested with the master branch and again a referral was created when I used the same email address as the affiliate that I was tracking. I was using Exchange's Guest Checkout add-on. I also tested as a logged-in user, and no referral was created (as expected).

**Comment by sumobi** [comment]
The guest email address is never passed to the `is_affiliate_email()` method in Exchange.

We can get the guest email address like this:

`$email = it_exchange_get_cart_data( 'guest-checkout-user' );`
`$email = is_array( $email ) ? reset( $email ) : $email;`

**Comment by TimothyBJacobs** [comment]
@sumobi Just an FYI, that won't work when the session is no longer around. Which will cause an issue with PayPal and other transient transaction gateways, the correct function to use is `it_exchange_get_transaction_customer_email`. When the Guest Checkout add-on is active, the add-on will override that value to give the correct email address.

**Comment by sumobi** [comment]
@TimothyBJacobs Awesome, thanks! didn't think of that
