### ISSUE TITLE
Incorrect commission rate in RCP when only global referral rate set

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#980]
Latest master branch.

RCP works out the commission amount fine when there is a per-membership level referral rate and when there is a per-affiliate referral rate. If both those are left blank it uses the global referral rate, but calculates the commission rate wrong.

A global commission rate of 20% on a $100 membership level is worked out at $1.00 instead of the expected $20.

@pippinsplugins can you replicate? Somehow it's working out the commission rate to be 1%

**Comment by sumobi** [comment]
If you var_dump the `$rate` right here you'll see it's `1`, so strange:
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-base.php#L238

**Comment by pippinsplugins** [comment]
I've seen this happen before.

**Comment by pippinsplugins** [comment]
@sumobi Ready for testing.

**Comment by sumobi** [comment]
@pippinsplugins works great
