### ISSUE TITLE
Add bulk actions menu to Creatives

### ISSUE THREAD

**Issue by lisag** [AffiliateWP/AffiliateWP#983]
This would make it much easier for site admins to quickly activate/deactivate/delete multiple creatives for a sale period or time period, plus allow for any other bulk actions that are added in the future (i.e. scheduling (ref https://github.com/AffiliateWP/AffiliateWP/issues/982)).

**Comment by amdrew** [comment]
PR: https://github.com/AffiliateWP/AffiliateWP/pull/2436

@pippinsplugins I have been defeated by nonce. 

Could you please have a look at these lines and spot the problem? Everything works great _except_ with this conditional enabled: https://github.com/AffiliateWP/AffiliateWP/blob/issue/983/includes/admin/creatives/class-list-table.php#L342-L344

Sidenote: @lisag would reallllllllllly like this for 2.1.7 so she can better manage creatives during our sales. If you can spot the issue she would be really happy.

**Comment by pippinsplugins** [comment]
@amdrew fixed!

**Comment by amdrew** [comment]
@pippinsplugins Hah, thanks. All working here!
