### ISSUE TITLE
AffiliateWP deactivated after update

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#984]
I've noticed this behaviour a couple of times. On a single site installation I updated AffiliateWP from v1.7.7 to v1.7.10 (clicking the update link on the main plugins page) and AffiliateWP was deactivated automatically after the update completed.

**Comment by pippinsplugins** [comment]
Is your folder name changing?

**Comment by michaelbeil** [comment]
That is odd. I do not see that on a multisite setup.

**Comment by sumobi** [comment]
@pippinsplugins No, folder name is always `affiliate-wp`

**Comment by pippinsplugins** [comment]
I updated it on the EDD site today and didn't have any issues.

**Comment by sumobi** [comment]
I always break things

**Comment by sumobi** [comment]
@pippinsplugins I think I know is causing this now, you were right. Something to do with multiple plugin folder, noticed the same thing with EDD today. I like to have multiple plugin versions to test between so I usually have `affiliate-wp` which is always the latest, and then `affiliate-wp-v1.7.8`, `affiliate-wp-v1.7.9` etc. When I update one of the folders with a different name it does some weird stuff.
