### ISSUE TITLE
Set $0.00 referrals in Formidable Pro to "unpaid"

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#985]
$0.00 referrals in Formidable Pro are set to `Pending` status. I think these should be set to `Unpaid` automatically since there isn't any payment involved.

We did something similar in Gravity Forms https://github.com/AffiliateWP/AffiliateWP/issues/914

**Comment by DrewAPicture** [comment]
Added a PR: #1242

**Comment by pippinsplugins** [comment]
PR looks good to me.
