### ISSUE TITLE
Decimal separator in "Most valuable affiliates" section

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#987]
Within the "Overview" section, when a Decimal Separator is set to present "," the "Most valuable affiliates" and "recent referrals" areas have values that are still presented with a "." decimal separator.

![issue-1](https://cloud.githubusercontent.com/assets/4752949/11379222/d543bb48-92b4-11e5-9de0-86dc7a0b2ee7.png)

Replicated locally as well: https://cloudup.com/cO9CeSihSe8.

https://secure.helpscout.net/conversation/141660289/21872/?folderId=634609

**Comment by michaelbeil** [comment]
Perhaps ouur currenct filter needs a look at: https://github.com/AffiliateWP/AffiliateWP/blob/6358820c4358ed9ee88d73d900bf863218fb6ebe/includes/admin/overview/overview.php#L180-L217

**Comment by DrewAPicture** [comment]
@michaelbeil This might be fixed as a side effect of #1322. Needs testing.

**Comment by michaelbeil** [comment]
This is fixed with #1323.

**Comment by michaelbeil** [comment]
I am seeing an issue with this again in both the **Most valuable affiliates** and **recent referrals** areas.
![screen shot 2016-08-09 at 7 30 32 pm](https://cloud.githubusercontent.com/assets/4752949/17538086/c96de2ec-5e67-11e6-9729-0de9f7fe31b6.png)

**Comment by michaelbeil** [comment]
Ok, confirmed that the issue is only in branch `release/1.9`.

This should be fine once we re-merge master.
