### ISSUE TITLE
Problem when viewing Referrals in the WP Dashboard

### ISSUE THREAD

**Issue by PShilling** [AffiliateWP/AffiliateWP#99]
![screen shot 2014-04-03 at 2 32 21 pm](https://cloud.githubusercontent.com/assets/6529456/2599419/a4e7dfa4-bae0-11e3-81a6-818220d7772f.png)

{Sorry if this has already been reported}

Using EDD as the integration I used the tool to import from the old Affilate Pro plugin.

It had create a few records, all of them test so I was looking to delete them.

I'm not sure if this is directly related to the fact that these referral records where imported but when using the tool to view various status 'unpaid' 'pending' etc.. 

eg admin.php?page=affiliate-wp-referrals&status=pending

The number total of these status don't add up.

Then I used the bulk action tool to delete all, the page reloads but the delete does not happen.

**Comment by DrewAPicture** [comment]
No followup from the reporter in two years ago, closing.
