### ISSUE TITLE
Allow search by user's First Name in New Affiliate screen

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#991]
Would it make sense to also be able to search for the affiliate's first name in the New Affiliate screen? Currently search is by username, however in the Affiliates -> Affiliates area it shows affiliates by their First Name as per their user account. Would it be tricky/confusing to add this so site admins can search either by name or by username?

Also, currently instructs admin to "Begin typing the name of the affiliate to perform a search for their associated user account." Perhaps it would be more clear to say "Begin typing the **user**name of the affiliate to perform a search for their associated **WordPress** user account."

Relates to showing the affiliate's username in the Affiliates area (currently shows first name): https://github.com/AffiliateWP/AffiliateWP/issues/959

And also this older issue: https://github.com/AffiliateWP/AffiliateWP/issues/71

**Comment by pippinsplugins** [comment]
If we can, let's do it.

**Comment by DrewAPicture** [comment]
This has been possible since 1.8 at least where I know we added username search support.
