### ISSUE TITLE
Export is not possible without 'manage_options' capability

### ISSUE THREAD

**Issue by mattsims** [AffiliateWP/AffiliateWP#996]
The `Affiliate_WP_Export` class has a function `can_export()`, the returned result of which is filterable using the `affwp_export_capability` filter (by default, export requires the `manage_options` capability). However, even if this is filtered to return true, an export will still fail unless the user has the `manage_options` capability, as this is checked for multiple times in `/includes/admin/tools/export/export.php`, e.g.
```php
if( ! current_user_can( 'manage_options' ) ) {
  return;
}
```

As such, to make this filter useable then it needs to be applied here also, i.e.
```php
if( ! apply_filters( 'affwp_export_capability', current_user_can( 'manage_options' ) ) ) {
  return;
}
```
I'm also wondering why the default required capability is `manage_options` and not `export_affiliate_data`?

Happy to submit a pull request if necessary, just let me know :)

Regards,

Matt.

**Comment by pippinsplugins** [comment]
Hey Matt!

Good catch! It is definitely intended to be `export_affiliate_data` so the `manage_options` default was just left in by mistake.

**Comment by mattsims** [comment]
Happy to help!

Also, while we're on the subject, access to the `Tools` menu (which contains all the export functionality), is only possible with the `manage_affiliate_options` capability – should this also use the `export_affiliate_data ` capability instead? And just use the `manage_affiliate_options` capability for restricting access to the `Settings` menu?

Regards,

Matt.

**Comment by pippinsplugins** [comment]
`Tools` probably should be accessible with `export_affiliate_data` but we'll then need to ensure that individual options inside of tools have the proper capabilities checks. Not all of them are accessible to `export_affiliate_data`.

**Comment by michaelbeil** [comment]
Nice find @mattsims.
