### ISSUE TITLE
Fallback tracking doesn't work for pretty affiliate URLs

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#998]
Fallback tracking doesn't work for pretty affiliate URLs.

Steps to reproduce

1. Create a JS error in the theme
2. Enable fallback tracking
3. Test with a pretty affiliate URL, eg /ref/admin

**Comment by michaelbeil** [comment]
Great find. For some reason, I thought I sent this in. 

:+1: for a fix.

**Comment by pippinsplugins** [comment]
Whoops!

**Comment by sumobi** [comment]
@pippinsplugins It works great. I originally discovered that the visits were incrementing but then I remembered https://github.com/AffiliateWP/AffiliateWP/issues/1002 and disabled credit last referrer

**Comment by pippinsplugins** [comment]
Sweet, merging then.
