### ISSUE TITLE
Warning: number_format() expects parameter 1 to be double, string given

### ISSUE THREAD

**Issue by osthafen** [AffiliateWP/AffiliateWP#999]
Hi,
I found a little warning-bug:

I's comming up with the $amount if the decimal or thousands separator are altered via str_replace:

Warning: number_format() expects parameter 1 to be double, string given in
 ../wp-content/plugins/affiliate-wp/includes/misc-functions.php on line 158

https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/misc-functions.php#L158

Greetings
Martin

**Comment by pippinsplugins** [comment]
Hi Martin!

Could you show me an example of how you're altering it before the notice is displayed?

**Comment by osthafen** [comment]
Hi Pippin,
I'm not altering it via code it's just in the settings page:
wp-admin/edit.php?post_type=download&page=edd-settings

sorry only german it's the german notation:
Tausender-Trennzeichen . Das Symbol, um die Tausender abzutrennen; gewöhnlich . (Punkt) oder , (Komma).
Zehner-Trennzeichen , Das Symbol, um die Zehner-Werte abzutrennen; gewöhnlich , (Komma) oder . (Punkt).

**Comment by michaelbeil** [comment]
What should the German notation be @osthafen?

**Comment by osthafen** [comment]
Everything is ok with the german notation. It's just the error coming up if you choose the german notation in the setting.
The function number_format() expects the parameter to be double but a string is provided. It's displaying this error warning int the overview page: /admin.php?page=affiliate-wp
'Warning: number_format() expects parameter 1 to be double, string given in ......./httpdocs/wp-content/plugins/affiliate-wp/includes/misc-functions.php on line 158'
![image](https://cloud.githubusercontent.com/assets/525826/11603877/1193bcae-9ae6-11e5-84bf-8ce2834d9d86.png)

**Comment by pippinsplugins** [comment]
Thanks, we'll get that fixed.

**Comment by DrewAPicture** [comment]
Added a PR: #1170.

Includes a test for the float value and fixes an unrelated undefined notice triggered when testing commas as decimal separators.
